### ISSUE TITLE
无法在Shadowsocks上面使用

### ISSUE THREAD

**Issue by Alienero** [xtaci/kcptun#1]
您好，我在本地搭建了一个环境， shadowsocks-go client ->kcp client -> kcp server -> shadowsocks-go server, 但是他们看起来并不工作，只有偶尔有数据可以加载成功

**Comment by xtaci** [comment]
建议试一下ssh tunnel， 另外，试前重启下 client/server
 shadowsocks我并不清楚工作原理。

**Comment by Alienero** [comment]
go get -u更新后工作正常，这个是一个很棒的项目，衷心感谢，希望将来也能共享一份pr

**Comment by xtaci** [comment]
非常欢迎，共同建设
