### ISSUE TITLE
Broken Pipe现象讨论

### ISSUE THREAD

**Issue by appleatiger** [xtaci/kcptun#10]
一天大约出现两次断流，说明还是会被ISP检测到，。

**Comment by xtaci** [comment]
已经很好了

**Comment by xtaci** [comment]
ISP会对出口流量进行限制，间歇性的屏蔽，这个是无法解决的问题。

**Comment by appleatiger** [comment]
好的，看来要做均衡负载。

**Comment by appleatiger** [comment]
但是同一台服务器，kcptun断流了，ss就一切正常

**Comment by appleatiger** [comment]
是只阻断udp？

**Comment by xtaci** [comment]
应该是你的路由器所有外出的到某台机器的数据包全部丢弃， ss是tcp传输的，解决不了tcp丢包降速的问题。 另外会检查下是不是yamux造成的阻塞。

**Comment by jannson** [comment]
我在实现一个游戏加速的方案的时候，也发现 UDP 过快会被阻塞。然后我不得不实现 UDP in TCP 的方案。但是这样又有一个问题，那就是 偶尔 UDP 的延迟非常大，因为 tcp 有 ack丢包就很慢。
我心理有一个方案不知道是否可行，就是把 UDP 包封装成 fake tcp 包，发到服务器端不走 tcp 协议栈，而直接当 UDP 来处理。相当于把 UDP 弄成 TCP 包的样子，协议已经完全不是 TCP 了。不知道是否可行？

**Comment by xtaci** [comment]
@jannson 可行，相当于用原始套接字自己实现一遍tcp

**Comment by jannson** [comment]
@xtaci 请教： 如果服务器启用多个 UDP 端口，客户端随机连接某一个端口。这样对 “流量阻断” 会不会有所改善？

**Comment by xtaci** [comment]
要看ISP是对端口还是整个IP的阻断。

这个阻断每天就是两三次，每次5～10分钟。

如果要真正改善此问题，应该用 haproxy 做四层的负载均衡，连接到两个不同的服务器。

**Comment by zwb-ict** [comment]
@xtaci 请教一个负载均衡问题，kcp把一个完整的UDP包在应用层做了分片，经过负载均衡后，负载均衡器能保证将这些分片都发给同一个server，使其能够完整重组吗？

**Comment by xtaci** [comment]
负载均衡分两种
1. 启动两个client，两个server，haproxy -> client1(2) - server1(2)这种前端tcp四层均衡
2. 第二种就是你说的UDP分片，server是以 saddr,sport,raddr,rport这个四元组作为会话key的，只要你能保证转发到server的最终数据包满足这个条件就可以，比如通过NAT，没试过，理论上可行

**Comment by dapao9999** [comment]
我用电信，经常断流，一个YouTube都看不完就断了，然后过一段时间又好了，不过能用的时候速度还是挺快的。

**Comment by xtaci** [comment]
断流真的没有办法啊，我这边的电信还好，每天一两次。

**Comment by nxtreaming** [comment]
UDP 被墙阻断是很正常的事情，完全看墙的心情。
很多时候不是流量特征被墙发现而导致的丢包，而是墙会故意丢包30%的UDP数据，为了给TCP让路。
国内有个兄弟搞的FinalSpeed的加速方案，虽然效果不错，但由于采用了更恶劣的UDP发包策略（设置好发包速度的带宽上限后，会以此上限速度进行数据发送和接收），完全是一种损人利己的行为。

----------------
Founder of http://slicelayer.com

**Comment by xtaci** [comment]
@nxtreaming 我觉得可能还是ISP的QoS控制，不太清楚，这个问题我没法解决，能满足日常使用就行了。主要是简单。

**Comment by nxtreaming** [comment]
是的，ISP的QoS控制策略的可能性更大。

此外，UDP传输有很多坑，因为其不同的网站的的路由路径上的MTU不一样，可能出现某些IP包在某些路由器上被强制fragment，我做的VPN方案就遇到此类情况。

----------------
Founder of http://slicelayer.com

**Comment by xtaci** [comment]
@nxtreaming path MTU至少要1400才能用kcptun, 低mtu的链路没有考虑，属于低效链路 。

**Comment by nxtreaming** [comment]
On Wed, May 11, 2016 at 1:02 PM, Daniel Fu <notifications@github.com> wrote:

> @nxtreaming <https://github.com/nxtreaming> path MTU至少要1400才能用kcptun,
> 低mtu的链路没有考虑，属于低效链路 。
>
我的测试发现很多时候 MTU在1360以内，比如连欧洲的很多服务器，例如欧洲西部的DOTA2游戏服务器时候就发现从上海电信到它的MTU是 1252 。

**Comment by xtaci** [comment]
嗯，这个考虑增加 -mtu参数给个可选项吧

**Comment by jannson** [comment]
昨天使用的时候我也想说，需要这个 mtu 选项！

之前别人测试是说，好像没有针对 ip 进行限速，仅仅是基于 端口。所以我才提出那个方案。但也是临时性的，哪天他们不高兴了，可能就直接 ip 限速，多端口也就黄了。

**Comment by xtaci** [comment]
-mtu 已经expose

**Comment by zwb-ict** [comment]
@xtaci 请教个问题， 你对udt协议了解的多吗？对于带宽延迟积较大的场景，是否只需根据最大带宽和rtt，计算出能打满带宽的窗口，关闭拥塞，或发生拥塞时，窗口不要降的太多，就可以解决带宽延迟积较大问题。

**Comment by xtaci** [comment]
那你怎么知道是真的网络拥堵还是被强迫丢包呢？

**Comment by zwb-ict** [comment]
@xtaci 请问kcp的非退让流控是否等价于TCP关闭拥塞吗，区别是什么？被强迫丢包指的是（假设接收端处理速度足够快）？我想是否可以用kcp，在非退让流控的情况，加大发送窗口，将带宽打上去，来解决带宽延迟积较大的问题。

**Comment by xtaci** [comment]
对，关闭拥塞后，完全按照 两端的wnd的大小来发送，那么就出现一个问题，假设这个窗口非常的大，出现网络故障的时候，即使按照1.5倍的时间退让，短期内也会重传大量的包，包的多少和窗口大小线性相关，比如你把窗口开到1024的发送，然后一个client在上传数据，然后把服务器关掉，client就会resend大量的数据，短期内甚至把上行带宽占满(过30秒后，yamux等上层的keepalive会终止链接，或者deadlink=20次重传终止。） 所以，上行窗口我故意调小为128个packet，就是为了避免在这种情况下占用太多上行带宽。

**Comment by xtaci** [comment]
至于这个snd_wnd/rcv_wnd参数需不需要暴露，还是只暴露snd，让rcv = snd，我还比较纠结，没有想明白。

**Comment by xtaci** [comment]
@jannson 降低CPU的途径如下,你可以尝试在你的fork上改来试试:

1. NewCipher creates and returns a new cipher.Block. The key argument should be the AES key, either 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256. 即是在kcp-go中，所有NewCipher的地方，只传入pass[:128]，执行AES-128加密

2. 不加--tuncrypt，这是一层额外的加密，一般的安全性下，是不需要加这个参数的。

**Comment by jannson** [comment]
好的，感谢~~~

**Comment by jannson** [comment]
很纠结，看到加了 tuncrypt mtu值就变小了好多。
如果不加 tuncrypt，udp数据头部就是 kcp 的协议头部啊？不是有明显特征的么？

**Comment by xtaci** [comment]
tuncrypt和mtu没有任何关系哈 @jannson

**Comment by xtaci** [comment]
-tuncrypt 是secureConn的一个iv，是上层的stream做加密，和底层数据包传输没有任何关系。

不加密的方式只有一种，就是 DialEncrypted/ListenEncrypted的时候，key传入 nil 

@jannson

**Comment by jannson** [comment]
stream 加密是最好的，原本我是这么认为的，所以都加密使用，但是看到这里：
如果有 block 的时候，mtu 确实小了啊？
	if block != nil {
		sess.kcp.SetMtu(IKCP_MTU_DEF - headerSize)

**Comment by xtaci** [comment]
@jannson 
这样吧，如果-key "" 的时候，那么我就传入 nil，明文通信，我改一下

**Comment by xtaci** [comment]
这样的话，可以用 -key "" -tuncrypt实现只做stream加密，不做UDP数据包加密

**Comment by xtaci** [comment]
@jannson 更新下kcp-go，已经提交 -key "" 的时候，不做数据包加密

**Comment by xtaci** [comment]
但是，我还是**强烈建议**，默认状态还是应该数据包加密

sess.kcp.SetMtu(IKCP_MTU_DEF - headerSize)

这里之所以要减去头部headerSize，是因为有16字节的OTP+16字节的MD5要固定占用

@jannson

**Comment by jannson** [comment]
重新看了代码看明白了。tuncrypt 提供流加密，而 key 是 udp 自己的加密。
如果 -key "" -tuncrypt 那意味着 kcp 协议的头部是暴露在外面的。

@xtaci 那么请教一个问题，如果牺牲一些安全行，同时还带来混淆数据的功能，能否固定住 IV 值啊？这样 IV 不传输，但是同样有混淆数据的目的。

**Comment by xtaci** [comment]
不能固定，固定+空key就相当于明文了，IV在这里相当于stream层面的密码，对明文信息(比如http)有基本的特征保密（比如GET,POST,Host字符串)，这里**最好还应该用DH(Diffie-Hellman)做KEY交换**，但是DH还会多一个服务器的回包，我就没做，会话发起时, 一来一回两个包也是一种特征，毕竟我是通过-key保证安全性的，-key的安全性绝对重要，所以我暂时没用DH，交换IV只多一个数据包的代价，带来更高的强制性安全性。

当然，kcp这里我们不谈信息安全性，因为大多数的网站都有https这种TLS加密，是不可能破译的，kcp的头部(24字节)是一个重要的协议特征，是需要通过加密来去掉的。

**Comment by jannson** [comment]
我的目标是去掉：sess.kcp.SetMtu(IKCP_MTU_DEF - headerSize) 这里的 headerSize
因为每个报文都占了一个 headerSize 感觉好浪费。
因为 kcp 头部也有写占用。这样 1500 大小的帧再减去拨号（或者VPN）中间的一些头部。
我这样纠结是不是很有必要？

"Highly secure packet level encryption(AES-256-CFB-MD5-OTP) without signature. -- 高安全的数据包加密，保障数据包安全" 能简单解释下它的原理么？

**Comment by xtaci** [comment]
链接：https://www.zhihu.com/question/45556316/answer/99274175

kcp-go加密(包加密)：

1. client/server预共享同一个字符串(PSK)，这个字符串通过计算SHA256后，得到一个长度为32字节的数组，作为通信双方AES-256-CFB加密的密钥。
2. CFB加密模式是以上一个AES BLOCK(16字节)加密后得到的密文作为输入，再一次AES加密(16B)后和明文执行XOR得到当前密文的，因此是前后有序连贯；每16字节的加密，解密都依赖于上一个16字节的输入的。由于UDP不是有序到达的数据包，可能数据包的顺序完全被打乱，不能以整个会话流作为CFB加密，因此CFB单次加密长度限定为当前UDP包长度。(参考 Block cipher mode of operation)
3. 相同的加密算法，相同的KEY，相同的输入，必然得出相同的密文。 在传输过程中，很可能有相同的信息出现，比如，头部魔数，会话ID，如果UDP数据包第一个16B的数据块恰巧包含着相同的信息，那么每个数据包的头部16B必然是相同的密文，这种就被称为数据包的特征。这是第一种情况，第二种情况是，同一个数据包被重传，如果两次加密后的数据包完全一致，也产生一种数据传输特征。这种特征会导致破译上的便利，通过猜测，验证，可以推断出部分信息。（请参考ECB模式)
4. 请注意，到目前为止，我说的都是单一UDP包的加密，也就是大约1400字节的故事。
5. 为了去掉特征，我们可以以单一UDP包CFB模式加密为基础(前向依赖的加解密过程)，在首部填充随机数，即填入16B长度的首部，从/dev/urandom中读取，或者从CryptGenRandom中读取 ，引入这个随机数后，根据CFB的依赖性质，同一份数据包因为头部不同，两次加密会得出完全不同的两个结果，类似于OTP ，或者PGP中通过私钥对随机KEY的加密。
6. 但数据包依然可能被篡改，比如电磁脉冲干扰，会导致数据包内容变更，完整性(integrity)破坏，进而影响数据包解读。UDP包没有对数据部分进行checksum，这里简单通过对数据进行MD5求和，并加密这个MD5，然后附加到头部第17-32字节，每次收到数据包解密后进行验证，如果出现两个不同的MD5值，直接丢包让协议进行重传即可。

**Comment by xtaci** [comment]
@jannson 不用纠结这个问题，现在的网络传输特征是，流量（包大小）没问题，延迟(RTT，丢包)才是问题。

**Comment by jannson** [comment]
感谢，解释很明白。
题外话： 原来 @xtaci 与 kcp 协议原作者都是同一个学校的阿。我们是校友！

**Comment by xtaci** [comment]
@jannson 哈哈，skywind3000是我同学。校友好！

**Comment by appleatiger** [comment]
好吧，一日不见已经完全不知所云，按这个趋势，作者需要将更多的精力投入到对readme的修改中。。。我这边的限制主要是基于UDP本身的限制，改换端口是没有用的，但也不是对IP的绝对封锁，改换成TCP协议的ss时，一切都好。所以我目前的设置是采用一台域外服务器，上面搭建ssr和kcptun，然后再用一台国内云服务器搭建haproxy，然后本地用ssr的服务器负载均衡，策略为低错误优先，目前一切正常。

**Comment by appleatiger** [comment]
又或者如果在已有ssr的基础上可以只使用key参数隐藏kcptun的特征，其实已经完全不需要tuncrypt参数？

**Comment by jannson** [comment]
如果已有 SSR 是不需要 tuncrypt. SSR 已经提供流加密.
不过我是觉得根本没有必要使用 SSR 作为上层, 因为 SSR 针对的是 tcp 的. 变成了 UDP 的情况, 之前对 TCP 的一些手段已用不上了, SSR 也没有必要了.

目前我是完全不用 tuncrypt 参数的. 有一层包加密足够了. 就是混淆下就行.

**Comment by appleatiger** [comment]
用ssr已经变成了习惯性和体验一致性的一种选择吧，并不是基于技术性的考虑，毕竟那是整套的解决方案。

**Comment by yaleh** [comment]
根据我观测到的情况，应当进一步考虑现有实现可能存在的问题。

先说明一下，我的客户端是 Raspberry Pi。

在客户端及日本服务端同时 iftop 检测流量。在客户端使用 docker pull 同步镜像，可观测到客户端 kcptun UDP RX 在 6 MBps 左右，服务端 kcptun UDP TX 9MBps 左右。上行 ACK 流量较小，不到 100KBps。持续 30s 到 60s TX和RX 同时降为 0。过 30s 到 40s 恢复。

看上去是有点像运营商 QoS 。可再想想还是有问题：此时两端 queue 中肯定都是有数据的，实现正常应该会重发，那么 TX 就不应该是 0。运营商 QoS 把 RX 变成 0 是说得通的，TX 为 0 就应当检查一下实现问题了。

一点愚见，请指正。

**Comment by xtaci** [comment]
@yaleh docker更新的很慢，建议直接下载二进制测试，可以调整mtu,sndwnd,rcvwnd

**Comment by xtaci** [comment]
@yaleh 持续掉包导致重传rto退让很长时间，tx为0是正常的

**Comment by dapao9999** [comment]
sndwnd,rcvwnd 的最大值和最小值是多少啊

**Comment by xtaci** [comment]
@dapao9999 没有最大值和最小值，这个值会影响到，突然的服务器断线，反复重传导致的突然的上行流量增加，计算方式可以参考kcp-go的SetRetries函数的说明，也可以参考tcp的tcp_retries2的sysctl说明，经验值是上行128个窗口，下行1024个窗口

**Comment by xtaci** [comment]
如果家用带宽偏低，可以适当调低 sndwnd/rcvwnd，比如减半为 100/800

**Comment by xtaci** [comment]
可以试下如下的参数组合:
1. -mtu 1300 -sndwnd 1024 -rcvwnd 1024 -mode normal
2. -mtu 1300 -sndwnd 64 -rcvwnd 512 -mode fast

**Comment by jannson** [comment]
这个问题我也跟踪下，前天晚上在家遇到，下载 国外100M 的测试速度文件，常常下载一会就速度变为0 然后超时.这个应该是好重现的。

 -mtu 1450 -sndwnd 128 -rcvwnd 1024 -mode fast
今天晚上再重现下。

**Comment by jannson** [comment]
我家里是 100M 下载，4M 上传的电信的。

**Comment by xtaci** [comment]
@jannson 这个问题我们都跟踪一下，找到一个合适的解决办法，算法

**Comment by xtaci** [comment]
@jannson 1450的mtu我测试是很容易掉线的，地区差异，1300是非常安全的一个值

**Comment by jannson** [comment]
@xtaci 但是我拨号，并用 tracepath 测试得到的是 1492 啊？就中间拨号少了 8 byte。

**Comment by appleatiger** [comment]
服务器端的-sndwnd 默认是1024 客户端默认是128 数值不一样有影响吗？我连续两日的测试结果KCPTUN的掉线率为0，当然我是三线均衡负载状态，通过云服务器转发的有11%的掉线率，直连也是无出错，共计通过kcptun跑了1374M的下行和100M上行。

**Comment by xtaci** [comment]
确实是很奇怪，我用tracepath得到的结果，掉线率很高，调低后就没有问题。

**Comment by xtaci** [comment]
@appleatiger 上下行带宽本来就不均等哈，没有影响，去两者的最小值。

**Comment by appleatiger** [comment]
中间通过的网路只要有一个是低MTU的，就会造成拆包而反复发包至阻塞吧，所以还是低点好，保不准中间有MTU低的节点，我选1300。

**Comment by xtaci** [comment]
@jannson @appleatiger  UDP的QoS可能还和端口有关系，不知道ISP是如何对待的，我在服务器端用rtsp（554/udp）这个端口，感觉很不错。

**Comment by jannson** [comment]
@xtaci 换了 另外一个端口, 不与你的一样的. 同时 mtu 改为 1350 .确实可以下载了,能达到 1200KB/s 左右.不够平稳,波动会比较大. 说明改 mtu 是真实有效的.

**Comment by jannson** [comment]
是不是我的网络丢包严重,我看服务器给我外网 ip 发的数据达到 5Mb/s.
而我接收的速度才2Mb/s ?

**Comment by xtaci** [comment]
@jannson 我觉得其实有道理，从normal到fast的梯度太大， 应该更细分一点，
参数上我想调整一下，default变为normal, normal变为delay的fast，fast保持不变，kcptun的默认传输改为sess.kcp.NoDelay(0, 10, 2, 1)

**Comment by xtaci** [comment]
@jannson

    switch mode {
    case MODE_FAST:
        sess.kcp.NoDelay(1, 10, 2, 1)
    case MODE_NORMAL:
        sess.kcp.NoDelay(0, 20, 0, 1)
    default:
        sess.kcp.NoDelay(0, 20, 0, 0)
    }

这组参数你觉得如何

**Comment by xtaci** [comment]
或者再增加一个梯度
 sess.kcp.NoDelay(1, 20, 2, 1)

**Comment by yaleh** [comment]
考虑加上丢包率计算和 FEC 吧

**Comment by xtaci** [comment]
@yaleh
FEC怎么加，UDP包长不同

**Comment by yaleh** [comment]
加 buffer, 延时窗口可以小点(如10ms)。buffer 满或窗口时间到就打包这段时间的所有 payload 重新分片加 FEC 发出去。

当然，这么改是很大了。

**Comment by xtaci** [comment]
@yaleh 对，就是会有延时

**Comment by yaleh** [comment]
假设当前吞吐量 2MBps ，计 1K+ 个包，则每 10ms 有超过 10 个包，做 FEC 够了。10ms 的延迟也是可以接受的。如果实现了效果应该是有的。

**Comment by xtaci** [comment]
@yaleh fec起码纠结了两个月到底要不要做，和传输特征有关。

**Comment by yaleh** [comment]
是指时序特征被检测出来？这个不用太担心吧。

**Comment by xtaci** [comment]
@yaleh 不是，信道的传输特征，有些是量大，有些是要求响应时间快。

**Comment by yaleh** [comment]
本来就都是接 TCP 的，主要还是关心量的问题。网游这样会对 10ms 延迟敏感的应用本来就是用 UDP 啊。

**Comment by yaleh** [comment]
按照前面的计算，5ms 的延迟也够做 20% 冗余的 FEC 了。

**Comment by xtaci** [comment]
@yaleh 某些tcp也是要求rtt的，比如dns tcp解析，另外，如果要做fec改动会比较大，必须加入包长度的两个字节了

**Comment by yaleh** [comment]
DNS 换个 UDP 端口明文走就好，随便哪个 udp tunnel 工具都能走，不是 kcptun 主要应用场景啊。

包结构的修改肯定是少不了了。实际上是在原来的包外又封了一层。

**Comment by xtaci** [comment]
@yaleh 所以很纠结，因为有会引入其他工具，又会增加头部，带来的效果有没有fast resend好，不得而知啊

**Comment by yaleh** [comment]
实测 mode 参数，中国电信到日本，fast2 吞吐率最高，normal 吞吐率只有前者 1/3 ；有效 TCP 流量比 KCP 流量还是 1/3 。

**Comment by jannson** [comment]
今天我测试还发现, kcptun 对带宽的使用远远不够. 比如我 100M 电信,但服务器发送测试发现发送数据的带宽仅有 5M.到我电脑上的时候就只有 2M了.

要是能有一个机制,服务器上发送 80M.不管中间丢了多少包,但相信到电脑上的速度会快很多! 我弄了好几个实现, 比较增长sndwnd 长度, 或强制 youtube 选用 720p 画面的视频.发现sndwnd 变长并不能增加发送带宽,反而让youtube强制选用更优势的画面,增长了发送量.

说明如果带动了发送量,带宽是能增加上去的.

**Comment by xtaci** [comment]
@jannson 这个测试提醒了我， 吞吐上不去，多半是ack不够及时，我尝试改一下。

**Comment by yaleh** [comment]
有必要做个 Wireshark extension 来分析 kcp 流量

**Comment by xtaci** [comment]
@jannson @yaleh 提交了及时ack的release,可以测试一下，流量分析后面有空再弄

**Comment by yaleh** [comment]
额，能不能弄个顺序的版本号，别光用日期。

**Comment by xtaci** [comment]
日期最合适哈，一目了然

另外，我觉得dante不行，速度还不如 https://github.com/armon/go-socks5 下面的example程序

**Comment by jannson** [comment]
@xtaci 平常我是早上同一地点同一服务器测试的，这次是昨天晚上测试，用了你的最新软件。
之前常常在 2Mb/s 徘徊，这次能达到 3.6Mb/s。但是还是不够稳定，3.6 持续一会又会降低下去，过一阵子能升回来。
我用 (256/512, 512/512) 感觉速度快一些，用 (256/1024, 1024/1024) 的 sndwnd/rcvwnd 要慢一些。
发送的带宽还是拉不上去。我很关心项目对视频的带动作用，这个应用场景是典型吧。但是发送还只是 5~6Mb/s 速度还是会提不上去。

**Comment by dapao9999** [comment]
**看YouTube显示的速度很快，但是缓冲很慢，经常停止，然后再接着缓冲**

**Comment by xtaci** [comment]
```
root@vultr:~# iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 4.00 MByte (default)
------------------------------------------------------------
[  4] local 172.7.7.1 port 5001 connected with 172.7.7.2 port 55453
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-18.0 sec  5.50 MBytes  2.56 Mbits/sec     <-- connection via kcptun
[  5] local 45.32.xxx.xxx port 5001 connected with 218.88.xxx.xxx port 17220
[  5]  0.0-17.9 sec  2.12 MBytes   997 Kbits/sec     <-- direct connnection via tcp
```
最新的性能对比， 是原有2.5倍的速度，再往上做，就要做wireshark分析了。
基本感觉是，带宽利用率，延迟，数据冗余度，不可兼得。

**Comment by jannson** [comment]
我觉得关键是 带宽利用率 吧。最好占满 50% 的带宽，能看 1080p 的视频。虽然延迟也是本程序要关心的重点，但是相比使用场景来说，让带宽占用率更高，会更好吧。哈哈。

**Comment by xtaci** [comment]
中国的网络真的很复杂，传输高了，也许丢包跟着就高了，ISP的QoS很难琢磨，我觉得有2.5倍的速度，比起tcp还是好多了，后面我考虑做传输特征分析，有数据支撑后，再继续优化了。

**Comment by jannson** [comment]
好的。目前有个软件叫 Finalspeed，也是把 tcp 转 udp 在满带宽发送数据，那速度是相当惊人的。

**Comment by xtaci** [comment]
嗯，那种数据传输冗余度一定高的惊人，相当流氓的做法。对同一出口的其它设备，相当不友好哈。

**Comment by nxtreaming** [comment]
On Thu, May 19, 2016 at 12:52 PM, dcdc8888 <notifications@github.com> wrote:

> *看YouTube显示的速度很快，但是缓冲很慢，经常停止，然后再接着缓冲*
>
>
看 YouTube TCP是王道，用UDP没有优势。

**Comment by xtaci** [comment]
绝对比tcp快， 如果慢，观察下丢包率是不是极高，后端建议3proxy

**Comment by jannson** [comment]
@xtaci 直接 output 两次我都想尝试了。不过太简单粗暴了。并不喜欢。所以需要协议来友好的规划阿！
没详细看 kcp 协议的 resend。比如预计大于 三个传输时间没有收到 ack 包直接重传这样的机制。

如果放在路由器里边，并做好分流，只有部分数据才会这样，并且只有一台设备。很合理的。

**Comment by xtaci** [comment]
@jannson 重传机制是有的，快速重传 + RTO重传。

现在速度上去不的原因是，丢包重传的等待时间，限制了速度的提升，我觉得最好的降低延迟的方法，还是FEC(前向纠错)

**Comment by yaleh** [comment]
昨天初步测试了下电信是否存在和如何 QoS udp 流量。初步结果看 TX 和 RX 为零不是电信 QoS 直接造成的。今晚再测一下再汇报详细情况。

**Comment by xtaci** [comment]
**初步想了下FEC的最简易的实现:**

1. - 包头增加SEQID(Uint32)，序号从0开始
2. - 包头增加数据包长度(uint16)
3. - 包头增加HAS_FEC标志 (byte)
4. - FEC通过 fec = p1 xor p2 xor p3计算
5. - 接收方对SEQID先做reordering，去重(de-dup)
6. - 每N(假设N=3)个数据包计算一个FEC，如果包没有计算FEC，标示0，有标示1(byte)，通过-fec 3指定，-fec 0不加任何头部，兼容原有数据包。发送端和接收端必须指定相同的fec值
7. - 假设收到1,3,[4],6,7,8,[9]数据包，中括号的是FEC数据包，reordering后的结果
8. - 输入1,3数据包到kcp
9. - 在读到SEQID = 4号FEC包时，向前读取N个包，检查到2号包丢失，fec-group{1,3,4}可纠错2号包，纠错后，将2号包input到kcp.
10. - 输入6,7,8号包，5号包被丢弃了，利用协议层ARQ重传
11. - 读到9号包，6,7,8完整，input6,7,8后，9以前的包全部清空
12. - 总之就是一旦读到FEC包，就查询前面三个包是否连续，如果丢一个就恢复，然后清空reorder队列

**Comment by xtaci** [comment]
分层为:
api -> protocol -> fec -> encryption -> transport

**Comment by jannson** [comment]
@xtaci 我觉得很赞！相信速率又提升1倍以上。主要不用重传了！

**Comment by jannson** [comment]
@xtaci 今天早上用最新的 fec 分支,并使用 fast2 模式,成功最高达到 8Mb/s. 之前最开始是 2Mb/s,之后达到 3.8Mb/s. 今天周末不知道怎么回事就达到 8Mb/s.很兴奋!

但是很可惜, 就是容易断开. 一会又提示 yamux 又要重连了! 然后整个网络都无法上网.我感觉是程序哪里的 BUG导致.我还需要确认.

**Comment by xtaci** [comment]
@jannson 嗯，这是第一个版本，肯定有潜在的bug，需要慢慢调，还没有做review哈，这几天跟踪.

**Comment by zwb-ict** [comment]
@xtaci @jannson @yaleh 请问你们这些方面的知识是怎么积累的？我在一家做大数据的公司负载海外数据的实时接收（主要特点是带宽延迟积较大），自己一个人搞（之前做芯片模拟的），有很多比如QoS、流量阻断、FEC这些之前都没听过。感觉有时测试测不到点上，挺着急的，更别提对已有协议进行修改了。

**Comment by xtaci** [comment]
@jannson 我已经合并到master分支了，以后在master分支测试！

**Comment by xtaci** [comment]
@zwb-ict 我一般是不懂的就google

**Comment by xtaci** [comment]
@xtaci @jannson @yaleh  FEC的相关问题到 https://github.com/xtaci/kcptun/issues/18 这里讨论

**Comment by zwb-ict** [comment]
@xtaci 好的明白了，谢谢。

**Comment by ligf** [comment]
@jannson 你编译的梅林版本的文件 是否经过strip

**Comment by jannson** [comment]
@ligf 有 strip 过，并且有 upx 过。 golang 编译的二进制本来就很大的。

**Comment by trivita** [comment]
我觉得可能最后 NoDelay 的参数也得放开，我客户端服务器两边调试，udp 链接能建立起来，一开始只有 default 模式可以正常使用，过了一会儿断流，但是 udp 链接还是能建立起来，只是数据传输没有了。

**Comment by yaleh** [comment]
发现 rpi3b 上一个核跑满了。估计有效载荷低和这个有关系。回头试试关掉加密会不会好些

**Comment by jannson** [comment]
现在默认的编译选项没有开启 golang 的 cpu 的多核特性！

**Comment by xtaci** [comment]
1.6之后的编译，默认就设置为GOMAXPROCS的

**Comment by jannson** [comment]
哦，好像是哪里看到说明。到是忘记了。

**Comment by wxyzh** [comment]
不懂怎么设置 wnd，mtu设成了1450。用haproxy做了5线的负载均衡,效果还不错
Video ID:c6rP-YP4c5I
Dimensions:854 x 480
Resolution:1920 x 1080@24
Volume:100%
Stream Host:r12---sn-o097znek
Stream Type:https
CPN:o60bWPsx0tJWtvn-
Mime Type:video/webm; codecs="vp9"
DASH:yes (248/251)
Connection Speed:13222 Kbps
Buffer Health:56.5 s

本地是百兆移动专线，vps是费力蒙的linode

**Comment by xtaci** [comment]
@wxyzh mtu要实测，默认是比较安全的值

**Comment by wxyzh** [comment]
@xtaci 实际测的mtu比1450要大些

**Comment by xtaci** [comment]
@wxyzh 你要减掉IP头部+ UDP头部

**Comment by wxyzh** [comment]
@xtaci 我是用ping去测试的，tracepath得到的是1500

**Comment by wxyzh** [comment]
`iperf3.exe -c 127.0.0.1 -p 21058 -f M
Connecting to host 127.0.0.1, port 21058
[  4] local 127.0.0.1 port 2969 connected to 127.0.0.1 port 21058
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  1.38 MBytes  1.37 MBytes/sec
[  4]   1.00-2.00   sec   768 KBytes  0.75 MBytes/sec
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 MBytes/sec
[  4]   3.00-4.00   sec   896 KBytes  0.87 MBytes/sec
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 MBytes/sec
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 MBytes/sec
[  4]   6.00-7.00   sec  1.00 MBytes  1.00 MBytes/sec
[  4]   7.00-8.00   sec  0.00 Bytes  0.00 MBytes/sec
[  4]   8.00-9.00   sec   896 KBytes  0.88 MBytes/sec
[  4]   9.00-10.00  sec  0.00 Bytes  0.00 MBytes/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  4.88 MBytes  0.49 MBytes/sec                  sender
[  4]   0.00-10.00  sec  4.01 MBytes  0.40 MBytes/sec                  receiver`
iperf的测试结果是这样的。0.00Bytes的是不是断流了？
