### ISSUE TITLE
pbkdf2与加密握手

### ISSUE THREAD

**Issue by tcz001** [xtaci/kcptun#100]
目前的authentication方式有问题，salt为固定数据无法防住replay攻击，建议用nonce+pseudorandom来生成shared key【类似WPA-psk的形式】，如果觉得可以，我可以完成后发pull request

**Comment by xtaci** [comment]
你可以先PR，再讨论

**Comment by tcz001** [comment]
cool

2016年8月7日 下午9:14，"xtaci" <notifications@github.com>写道：
