### ISSUE TITLE
能编译一个tomato arm能用的程序吗？

### ISSUE THREAD

**Issue by ilasx** [xtaci/kcptun#101]
root@MiWiFi:/tmp/home/root# cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 0 (v7l)
processor       : 0
BogoMIPS        : 1998.84

processor       : 1
BogoMIPS        : 1998.84

Features        : swp half thumb fastmult edsp 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Northstar Prototype
Revision        : 0000
Serial          : 0000000000000000

目前只能用armv5的程序。一会就崩溃了

**Comment by ilasx** [comment]
Linux内核 2.6.36.4

**Comment by xtaci** [comment]
dmesg输出什么， 崩溃消息是什么

**Comment by ilasx** [comment]
没有消息，内存直接跑满就挂了

**Comment by ilasx** [comment]
我再试一次，一会看看log

**Comment by ilasx** [comment]
一切正常，就是程序没了。
2016/08/08 23:43:08 stream opened
2016/08/08 23:43:08 stream opened
2016/08/08 23:43:08 stream opened
2016/08/08 23:43:08 stream opened
2016/08/08 23:43:08 stream opened
2016/08/08 23:43:09 stream opened
2016/08/08 23:43:09 stream opened
2016/08/08 23:43:09 stream opened
2016/08/08 23:43:10 stream opened
后台程序没了。我之前看过内存跑满了。我也不知道什么时候没的

**Comment by xtaci** [comment]
如果是内存导致的，dmesg会有消息(oom killer)

**Comment by ilasx** [comment]
没有任何提示，看起来都是正常的。但是不能上网，重新开主程序就好了。我想可能是没有匹配的程序吧。

**Comment by silent-x** [comment]
内存太小或者内核太老了 换新一点的内核试试看

**Comment by ilasx** [comment]
@silent-x 换不了，tomato 用的就是老的内核，内存256应该不吃紧吧

**Comment by silent-x** [comment]
什么机器 256内存还只上tomato？rg200/hg320系列？

**Comment by ilasx** [comment]
@silent-x 小米R1D，原生的小米定制openwrt不好用

**Comment by hzshang** [comment]
`运行后服务器端日志重复这样显示
```
2016/08/10 13:54:37 [ERR] yamux: Failed to read header: broken pipe
2016/08/10 13:54:38 remote address: (我的ip地址):52978
2016/08/10 13:54:38 dial tcp 127.0.0.1:8388: getsockopt: connection refused

```
