### ISSUE TITLE
[ERR] yamux: keepalive failed: i/o deadline reached

### ISSUE THREAD

**Issue by xiaojiulala** [xtaci/kcptun#103]
[用的是kcpserver那个一键安装包，有些服务器就正常，但部分服务器就显示如图下方所示的这样，没法连上网站。系统都是centos6.服务器本地宽带ping也都没问题不丢包。](https://s10.postimg.org/3rriy3k21/MCRFEID4_NH_TC0_AJKCLVQLM.png)

**Comment by xiaojiulala** [comment]
https://s10.postimg.org/3rriy3k21/MCRFEID4_NH_TC0_AJKCLVQLM.png

**Comment by xtaci** [comment]
这个不是我做的，你可以问作者。

**Comment by xiaojiulala** [comment]
不是，昨天用你原版也都提示这个，后来换了一键安装包也一样。后来换了其他服务器就可以了，请问这个提示一般是什么问题造成的，二楼的链接你点击看看

**Comment by xtaci** [comment]
keepalive的问题基本就是UDP端口被屏蔽。
