### ISSUE TITLE
使用后带宽反而严重缩水

### ISSUE THREAD

**Issue by jm33-m0** [xtaci/kcptun#104]
我尝试了一下[shadowsocks-plus](https://github.com/shadowsocks-plus/shadowsocks-plus), 使用效果非常显著：50Mbps对等，单Shadowsocks只能跑不到20Mbps，用自带kcptun的ss+，可以跑满50Mbps。。
但是当我使用kcptun+ss的时候（按照README的指导设置），带宽甚至不会超过10Mbps
请问我的情况应该如何配置才可以达到ss+的效果？
谢谢！

**Comment by jm33-m0** [comment]
PS 我的测速在[fast.com](https://fast.com)完成

**Comment by xtaci** [comment]
贴参数

**Comment by jm33-m0** [comment]
Server: `kcp_server -t 127.0.0.1:443 --key "password" -l 0.0.0.0:465 -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2`
Client: `./client_linux_amd64 -l :1088 -r <server>:465 --key "password" -mtu 1400 -sndwnd 128 -rcvwnd 1024 -mode fast2 -dscp 46`

**Comment by jm33-m0** [comment]
尝试改变了sndwnd和rcvwnd也是没用

**Comment by xtaci** [comment]
那就不清楚了，第一次出现这种问题。

**Comment by jm33-m0** [comment]
我发现使用ss+的时候如果使用python版sslocal配合ss+ server的话速度最快，也稳定，使用它配套的local客户端反而不稳定且速度不如python版本。。
是不是ISP的问题？或者我需要在ss+那边提一下这个问题

**Comment by xtaci** [comment]
ss+我不清楚，你可以问下作者。

**Comment by wxyzh** [comment]
建议参考ss+去设置kcptun，窗口大小都是1024  mtu1350 等等

jm33_m0 <notifications@github.com>于2016年8月9日周二 21:40写道：
