### ISSUE TITLE
windows 10中cmd命令执行程序，指定上传MTU等参数不生效或者日志有误

### ISSUE THREAD

**Issue by yyysuo** [xtaci/kcptun#105]
现象：执行命令指定MTU为1400，日志为1350

执行命令：
client_windows_amd64.exe -l :12948 -r IP:PORT -key password -nocomp true -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2 -dscp 46 -conn 4

日志如下：
2016/08/09 23:37:10 version: 20160808
2016/08/09 23:37:10 listening on: [::]:12948
2016/08/09 23:37:10 encryption: aes
2016/08/09 23:37:10 nodelay parameters: 0 20 2 1
2016/08/09 23:37:10 remote address: IP:PORT
2016/08/09 23:37:10 sndwnd: 128 rcvwnd: 1024
2016/08/09 23:37:10 compression: false
2016/08/09 23:37:10 mtu: 1350
2016/08/09 23:37:10 datashard: 10 parityshard: 3
2016/08/09 23:37:10 acknodelay: false
2016/08/09 23:37:10 dscp: 0
2016/08/09 23:37:10 sockbuf: 4194304
2016/08/09 23:37:10 keepalive: 10
2016/08/09 23:37:10 conn: 1
2016/08/09 23:37:11 stream opened
2016/08/09 23:37:13 stream opened

**Comment by xtaci** [comment]
-nocomp true ====> -nocomp

**Comment by yyysuo** [comment]
谢谢！
