### ISSUE TITLE
希望尽快支持配置文件

### ISSUE THREAD

**Issue by huijiewei** [xtaci/kcptun#107]
往 brew 提交的时候已经跪在这一步了

**Comment by xtaci** [comment]
很多软件都不支持配置啊。  也没有计划要支持， 不灵活。

**Comment by blankhang** [comment]
.... 那能不能麻烦给下 win开机自动启动的教程啊

**Comment by lizongzeshunshun** [comment]
@blankhang 

# Client

写个bat，比如

``` bash
client_windows_amd64 -r "<SERVER_IP>:554" -l ":8388" -mode fast2
```

然后注册表放开机启动项。
> 在开始——运行中输入regedit，展开HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run。在右边框中新建一个字符串的键，把名字命令为你可添加程序的名字（可以随便取），把它的键值设置这个程序的完整路径。

# Server

同样是bat，内容改一下放开机启动项就行了

**Comment by wxyzh** [comment]
计划任务，不用改注册表

LIZONGZE <notifications@github.com>于2016年8月12日周五 21:12写道：
