### ISSUE TITLE
能否不用snappy换其他库来压缩

### ISSUE THREAD

**Issue by silent-x** [xtaci/kcptun#108]
看上去snappy在go-mips32下有问题 导致不能开启压缩

**Comment by xtaci** [comment]
两端必须同时启用或关闭

**Comment by silent-x** [comment]
现象是如果server开启 client开启后 只要有数据传输 client就报错退出了 callstack显示是snappy里面的

**Comment by xtaci** [comment]
不换了
1. 本来加snappy都挺勉强的，实际压缩效率不高，因为大部分数据都是加密数据。
2. 没有golang的足够快的压缩算法，压缩如果耗时，还不如直接传输更快。

**Comment by testcaoy7** [comment]
可不可以试试LZO呢，LZO也是实时压缩的

**Comment by xtaci** [comment]
你可以试试，实在兴趣不大。 comp只有在某些特殊的情况下，有那么一点效果。
最好的是lz4。

**Comment by testcaoy7** [comment]
@xtaci 是的，最好的是LZ4

**Comment by xtaci** [comment]
所以这个balance在于压缩速度和传输速度的平衡，另外lz4并没有一个很好的native golang的版本。
