### ISSUE TITLE
linux服务端在传输流量大的时候占用偏高

### ISSUE THREAD

**Issue by dolphinpaopao** [xtaci/kcptun#109]
openVZ VPS，系统：debian7 x86mini，cpu：志强D-1540@2GHz   单核心，内存：512MB，SWAP：64MB。
server：./server_linux_386 -l :29900 -t 127.0.0.1:8388 -key test -mtu 1400 -sndwnd 1024 -rcvwnd 1024 -mode fast -nocomp &
server版本：20160808，20160809，20160810均试过，在带宽传输到50Mb左右，kcptun的cpu占用率就跑到了40%-50%，对于很多单核心的vps来说cpu此时的占用偏高，很多VPS商家有限制不能长时间占用如此多的资源，所以望作者能优化一下，万分感谢。

**Comment by xtaci** [comment]
如果能优化，我早就优化了，确实没有办法。

**Comment by dolphinpaopao** [comment]
再次感谢作者，看来需要下次入多核心的了。

**Comment by dolphinpaopao** [comment]
@xtaci 抱歉再次打扰一下，今天测试的时候同样发现了#66报告的那个缓冲问题，最新版同样的存在。

**Comment by xtaci** [comment]
这个没有办法，在高速传输的时候，一个不可FEC恢复的包，就会导致RTO时间间隔的传输空缺。表现出来就是  慢快快慢快快。

**Comment by dolphinpaopao** [comment]
原来如此，谢谢解答。

**Comment by xtaci** [comment]
@dolphinpaopao 试下0811

**Comment by dolphinpaopao** [comment]
@xtaci 感谢更新，刚刚测试了一下最新版，server端在高带宽传输时的CPU占用并没有改善。不知道是否可以通关过调用相关硬件指令集加速来改善这种情况。

**Comment by bettermanbao** [comment]
@xtaci linux arm v7的client端，CPU使用也没看到降低。
不过无所谓了，4核的arm cpu，跑到10Mbps，CPU占用率也就在150%。

root@orangepione:/# cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 5 (v7l)
processor       : 0
BogoMIPS        : 2285.71

processor       : 1
BogoMIPS        : 2285.71

processor       : 2
BogoMIPS        : 2285.71

processor       : 3
BogoMIPS        : 2285.71

Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : sun8i
Revision        : 0000
Serial          : 94355037028e2c00001c

**Comment by xtaci** [comment]
解释一下:
1. 这个优化只对客户端有效
2. 在CPU已经到达极限的情况下，优化的结果是提升了速度，而不是降低CPU
3. 我的测试环境是x86_64

附:
![before](https://cloud.githubusercontent.com/assets/2346725/17610565/c65c9556-6071-11e6-97eb-e79196b3823b.jpg)

![after](https://cloud.githubusercontent.com/assets/2346725/17610564/c628986e-6071-11e6-8deb-859a16e4fe58.jpg)

**Comment by dolphinpaopao** [comment]
@xtaci 客户端我的是win10 x64，硬件配置还算主流，就算是跑到40Mb-50Mb带宽的时候，cpu占用在0.9%-1.3%徘徊，这是很低的，所以并没有在意client的资源占用情况。。。。另外，此次client的优化包括全平台么，linux and arm？未来打算在路由器和手机上面尝试一下kcptun。谢谢。

**Comment by xtaci** [comment]
全平台的client端

**Comment by dolphinpaopao** [comment]
Thanks，有机会我试一下其他平台。

**Comment by wxyzh** [comment]
可以尝试用haproxy去连接多个kcptun

dolphinpaopao <notifications@github.com>于2016年8月12日周五 11:26写道：

**Comment by Smallthing** [comment]
志强D-1540 太差了，一个45W的soc。。。
