### ISSUE TITLE
CPU优化讨论

### ISSUE THREAD

**Issue by xtaci** [xtaci/kcptun#11]
降低CPU的途径如下:

1. NewCipher creates and returns a new cipher.Block. The key argument should be the AES key, either 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256. 即是在kcp-go中，所有NewCipher的地方，只传入pass[:16]，执行AES-128加密，如果-key给的足够长，依然很安全(8位以上数字字母)

2. 不加--tuncrypt，这是一层额外的加密，上层有TLS/SSL加密的情况下，是不需要加这个参数的。

**Comment by jannson** [comment]
chacha20
chacha20-ietf 加密的支持？不知道效果如果，会不会计算得更快？
还有，加密方式能否自己进行选择？

**Comment by xtaci** [comment]
现在大多数设备的cpu都应该支持aes-ni指令，AES加密有硬件支持的情况下，不一定慢。
另外，rc4的加密在数据包层面固定偏移位置能直接xor推导出特征,弃用。
DES的加密没有硬件支持，太慢。
chacha20如果是rc4这种stream cipher,对于**包级别**依然无法去特征。
(比如包头部偏移32个字节就可以猜测kcp头部，xor做实验，验证下一个包的kcp)。

总之，在包级别，只能用block cipher
在传输层，可以自己在上面实现一层TLS就能保证数据的安全，这一层才能选择chacha20/rc4/des这些。

**Comment by jannson** [comment]
原来如此。明白了~

**Comment by riobard** [comment]
Salsa20/ChaCha20 用随机 nonce 就可以去特征了。详见 https://nacl.cr.yp.to/secretbox.html
