### ISSUE TITLE
Possible to attach a pseudo TCP header or rebase the protocol on TCP?

### ISSUE THREAD

**Issue by PeterCxy** [xtaci/kcptun#110]
Here in Suzhou, China Telecom's QoS policy strictly limits the rate of UDP transmission to no more than 10Mbps (at least it is the case with my 100Mbps ADSL) while randomly dropping outgoing UDP packets to non-standard ports. Even if KCP itself can improve the stability and reduce the latency of TCP connections, this limit on UDP packets' rate makes the efforts devoted to KCP all in vain. So I wonder if it is possible to attach a pseudo TCP header (like what ShadowVPN once did) or just rebase the protocol on TCP?

**Comment by xtaci** [comment]
The key problem to rebase on TCP is the Router. 
When a TCP-RST packet is received on your router.  It will definitely delete the NAT(port mapping).

**Comment by PeterCxy** [comment]
It is not the server side that sets the limit. It is the local ISP instead. AFAIK my local ISPs all have similar QoS policies.
On Aug 10, 2016 10:21 PM, xtaci <notifications@github.com> wrote:One possible solution is to set up another hop server which does not limit udp.

**Comment by xtaci** [comment]
I mean ：

Your PC(tcp) -> eg: Aliyun VPS -> kcptun-> eg: Oversea VPS -> .....

**Comment by PeterCxy** [comment]
Even UDP traffic inside China is subject to the QoS policy. It's applied by my local ISP.
On Aug 10, 2016 10:36 PM, xtaci <notifications@github.com> wrote:I mean ：

Your PC(tcp) -> eg: Aliyun VPS -> kcptun-> eg: Oversea VPS -> .....

**Comment by testcaoy7** [comment]
TCP Obfuscation is a good idea. I think PeterCxy means to send a UDP package with TCP header so that ISP will think it is a TCP package but it is actually a UDP package.

**Comment by testcaoy7** [comment]
ShadowVPN "Use libnetfilter_queue to receive and drop fake TCP packet" and "Performance looks good".

**Comment by PeterCxy** [comment]
@testcaoy7 Yes, if it is not possible to rebase the protocol to TCP, a pseudo TCP header will do for most QoS policies. ShadowVPN has once applied such method and looks good here. However the ShadowVPN repo is now deleted and I cannot refer to the commit now.

**Comment by xtaci** [comment]
No, I won't do that for some reason.

If you wish to do this , just fork and make changes, but I won't merge that.

**Comment by testcaoy7** [comment]
@PeterCxy Pseudo TCP header will do the job perfectly. You cannot rebase the protocol on TCP, otherwise KCP will become no better than a aggressive congestion control algorithm.
