### ISSUE TITLE
CPU & MEM & BPS

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#111]
请看截图，LAN1口接的是一台kcptun中转的本地服务器，用的是20160808 linux arm的kcptun版本。

蓝色uplink流量是远端的VPS发往本地kcptun中转服务器的UDP流量，橙色download的流量是kcptun解包还原后发往客户端的实际数据流量。两者波动基本同步，这是合理的。

请教一下作者，这种波动是正常的吗？是否可以通过优化kcptun的参数，平滑波动？
另外本地收到的UDP流量和解包后的实际流量，差不多是2:1的关系。kcptun本身的系统开销应该没有这么大吧？那这是不是代表本地收到的UDP包中有将近一半的包是重复的的或者错误的？谢谢！

![kcptun](https://cloud.githubusercontent.com/assets/17328315/17577230/c150a8e6-5fad-11e6-8248-efbcc6336fab.jpg)

**Comment by xtaci** [comment]
是真的丢包， UDP丢包就是这么严重，最准确的统计是通过 kill -SIGUSR1 pid， 把那个贴出来。

**Comment by bettermanbao** [comment]
蓝色的unlink流量是本地收到的UDP流量，不是服务器发出来的UDP流量。
如果丢包的话，不是在路上已经丢了吗？本地的kcptun应该是收不到这些包的吧？也就不应该在本地流量中被统计到。

我运行kill  -SIGUSR1没有任何输出，进程也不会被kill掉。系统是ARM平台的Ubuntu 16.04.1 LTS 3.4.112-sun8i

root@orangepione:~# uname -a
Linux orangepione 3.4.112-sun8i #14 SMP PREEMPT Tue Jul 5 16:28:14 CEST 2016 armv7l armv7l armv7l GNU/Linux

**Comment by xtaci** [comment]
你吞掉日志了吧。

**Comment by bettermanbao** [comment]
真的吞掉了，呵呵。
我吐出来了，你看看是不是真的丢包那么严重。

2016/08/11 11:25:18 KCP SNMP:&{BytesSent:163668 BytesReceived:49589511 MaxConn:1 ActiveOpens:1 PassiveOpens:0 CurrEstab:1 InErrs:0 InCsumErrors:10 InSegs:87295 OutSegs:5707 OutBytes:3025739 RetransSegs:369 FastRetransSegs:0 EarlyRetransSegs:0 LostSegs:369 RepeatSegs:124 FECRecovered:22 FECErrs:0 FECSegs:20143}

**Comment by xtaci** [comment]
两端都要发出来

**Comment by bettermanbao** [comment]
log来了

Server:

root@ubuntu:~# 2016/08/11 11:34:34 KCP SNMP:&{BytesSent:80438050 BytesReceived:226943 MaxConn:2 ActiveOpens:0 PassiveOpens:2 CurrEstab:1 InErrs:0 InCsumErrors:18 InSegs:8539 OutSegs:146212 OutBytes:184679566 RetransSegs:45428 FastRetransSegs:3237 EarlyRetransSegs:3472 LostSegs:38719 RepeatSegs:0 FECRecovered:0 FECErrs:0 FECSegs:1971}

Client:
root@orangepione:~# 2016/08/11 11:34:59 KCP SNMP:&{BytesSent:244992 BytesReceived:84021935 MaxConn:1 ActiveOpens:1 PassiveOpens:0 CurrEstab:1 InErrs:0 InCsumErrors:18 InSegs:151993 OutSegs:8952 OutBytes:5128544 RetransSegs:311 FastRetransSegs:0 EarlyRetransSegs:0 LostSegs:311 RepeatSegs:1090 FECRecovered:1064 FECErrs:0 FECSegs:35065}

**Comment by xtaci** [comment]
很正常啊 BytesSent ~= BytesReceived 
RepeatSegs / InSegs 也很低啊

**Comment by xtaci** [comment]
FEC首先就增加了> 30%的浪费，为了响应时间，在于流量的话可以关掉FEC。

**Comment by bettermanbao** [comment]
了解了，谢谢。目前用下来速度方面的确挺好的。
今天正好注意到流量曲线不够平滑，见1楼截图。这个可以通过微调sndwnd rcvwnd参数改善吗？

**Comment by xtaci** [comment]
这个我这里也是这样的，初步估计是一个不可恢复的包，导致了RTO超时，这段时间就是波谷。

**Comment by bettermanbao** [comment]
感谢回答！

**Comment by xtaci** [comment]
@bettermanbao https://github.com/xtaci/kcptun/releases/tag/v20160811  试下这个，看下曲线。

**Comment by bettermanbao** [comment]
好的，等一下试试效果。

**Comment by Biercenter** [comment]
在这里看到恩山坛友了，呵呵。我测试的K2和小米mini路由器也是速度一下窜很高，一下就卡住了，CPU负载显示100%。参数调成fast或者normal会有改善，但还是不稳定。

**Comment by bettermanbao** [comment]
平滑效果明显，并且速度也有所提升。大赞一下作者！

![kcptun2](https://cloud.githubusercontent.com/assets/17328315/17581143/2994ea3e-5fd6-11e6-8eb1-1d5aee9a1416.jpg)

**Comment by bettermanbao** [comment]
@Biercenter mt7620跑kcptun太勉强了，我是外挂了一个orange pi专门跑kcptun的，路由器只负责分流。

**Comment by xtaci** [comment]
好的，借用一下你的图用来发release!

**Comment by xtaci** [comment]
@bettermanbao 平滑度现在受到-sockbuf隐藏参数的影响

**Comment by bettermanbao** [comment]
欢迎借图，好奇问一下MaxStreamWindowSize设置为sockbuf(hidden)，是不是只是增大了接收缓存？看截图，感觉客户端接收到的UDP流量（蓝色）平滑效果比实际数据（橙色）的平滑效果要更加明显。

**Comment by xtaci** [comment]
其实是减小了缓存大小， 因为yamux的窗口更新策略很保守，窗口越大更新越慢，相当于窗口更新对于链路传输状况敏感度降低了。换句话说，yamux在这种情况下，没有感受到网络的阻塞。

**Comment by xtaci** [comment]
根本的解决办法是，去掉yamux的窗口。

**Comment by bettermanbao** [comment]
原来如此，新版我试用一段时间，再给你反馈。谢谢！

**Comment by fydexx** [comment]
太流弊了，搬瓦工VPN，实测0808版 1080p 无压力，更新到0811后，1440p无压力

**Comment by Biercenter** [comment]
楼上服务器和客户端参数是多少？还有客户端是什么机子？我搬瓦工还是卡顿，求参数

**Comment by braveguywallce** [comment]
不好意思请教下， -sockbuf隐藏参数 我在执行程序时和其它参数一起手动输入吗？

**Comment by testcaoy7** [comment]
请问sockbuf设置多少比较合适呢，我现在设置为67108864（64MB）

**Comment by xtaci** [comment]
sockbuf = 带宽时延乘积

**Comment by xtaci** [comment]
@bettermanbao https://github.com/xtaci/kcptun/releases/tag/v20160811 试下，换了系统调用，降低CPU使用率。

**Comment by braveguywallce** [comment]
＠xtaci 我客户端的带宽下行速率最大为 50 M b/s, 客户端到VPS时间延迟90ms, 那么我是否在server和client的命令中设置 -sockbuf 50 000*0.090 = -sockbuf 4500 ?

谢谢！

**Comment by xtaci** [comment]
基本不用调整

是50Mbps * 0.09s = 5MB/s * 0.09s = 450KB

**Comment by gkl1368** [comment]
这个流量图是怎么出来的？求解？

**Comment by bettermanbao** [comment]
@gkl1368 运行kcp的中转服务器连到路由器的某个口，然后观察这个网口的流量就可以了。uplink就是收到的UDP数据流，downlink就是解包后实际的数据流。

**Comment by gkl1368** [comment]
是哪个软件显示的？

**Comment by bettermanbao** [comment]
@gkl1368 路由器自带的web界面

**Comment by gkl1368** [comment]
哦。好的 谢谢

**Comment by wxyzh** [comment]
用nload大概能看出来

**Comment by braveguywallce** [comment]
＠bettermanbao
我现在的方案也是把SS架设在路由器上，但是路由器不适合跑kcptun, 所以我想单独再搞台树莓派，连在路由器上，专门跑kcptun, SS还是交给路由跑。当然，把kcptun+SS都放在树莓派上也可以。所以请教你现在的方案是怎么搞的？配置方案能大概介绍下吗？

**Comment by bettermanbao** [comment]
@braveguywallce 我用的是黑名单方案，dnsmasq转发黑名单里的域名到本地的pdnsd，pdnsd把dns请求转换成TCP协议，通过ss-redir发给8.8.8.8。dnsmasq同时把黑名单里的域名加入指定ipset，用iptable指定这个ipset的流量全部走ss-redir。ss-redir的服务器指向本地的kcptun中转服务器。

这套方案的缺点是黑名单可能需要定期维护，以及无法中转UDP流量。优点也很明显就是整套方案中任何一个环节出问题都不会影响正常网站的访问速度。

另外，我买的是国产的orange pi one，装armbian的ubuntu 16.04用起来很方便。配齐整套不过120元，性价比很高，推荐你淘宝去搜下。

**Comment by braveguywallce** [comment]
＠bettermanbao
谢谢！那么你的整套系统，SS还是放在了路由上，只是把server指向了装了Kcptun的orange pi one, 我用的是白名单，国内IP一律绕过，国外IP全部走SS。
我下午先找台局域网的PC跑Kcptun，把PC当作Pi来用了看看效果。

**Comment by bettermanbao** [comment]
@braveguywallce 
是的，不过你要注意因为kcptun不能转发UDP流量，所以DNS请求必须用pdnsd转换成TCP。我刚开始用的是ss-tunnel直接转发UDP的DNS请求，所以失败了。

**Comment by Comah** [comment]
太棒了。0811现在能编译一下放到7620上面用吗？现在用的是HIBOY的0808华硕固件，带宽是12M，勉强能跑满，但是CPU长期100%，而且会有断流的现象。但是效果真的很好，也方便。辛苦了

**Comment by braveguywallce** [comment]
@bettermanbao 谢谢经验！但是是否可以把ss-tunnel指向真实VPS, 而不是树莓派，这样ss-tunnel无需经过kcptun， kcptun只处理ss-redir转发来的tcp流量？

**Comment by braveguywallce** [comment]
＠Comah   go的东东放在路由上跑，不合适，树莓派很便宜，不若直接搞一个，跑得也舒服。

**Comment by bettermanbao** [comment]
@braveguywallce ss-tunnel可以指向真实的VPS

**Comment by Comah** [comment]
@braveguywallce  是的，如果自己宽带大的话我会考虑树莓，但是这几天在7620（极三）上面连续跑了三天，提速效果很明显，我觉得这个方案其实性价比挺高的,如果以后的更新能优化一下绝对可以长期用7620+ovz+tcptun高性价比放方案。

**Comment by bettermanbao** [comment]
@Comah https://github.com/bettermanbao/openwrt-kcptun/releases

**Comment by Comah** [comment]
@bettermanbao 啊！万分感谢！

**Comment by xtaci** [comment]
@bettermanbao 我在release上加了你的link

**Comment by braveguywallce** [comment]
@bettermanbao 
咦？不是arm平台的路由器，kcptun也支持了？

**Comment by Comah** [comment]
@bettermanbao 感谢编译。更新好完跑了一下，现在CPU的占用大大降低，1.2m/s顶峰也就50-70%左右。断流现象没有了。原来用你编译的那个旧版，CPU使用率长期都在100%，而且断流现场有点严重。再次感谢你和xtaci 。

**Comment by bettermanbao** [comment]
@braveguywallce 我有编译MIPS32的kcptun，ar71xx和ramips的路由器可用。

@Comah 1.2M bit 还是 byte？为什么我的mt7620 64M内存运行速度一直不理想呢。。。流量一大就出错退出。

**Comment by wxyzh** [comment]
@Comah 1.2Mbit/s 还是1.2MByte/s 我这在虚拟机里面跑的一般也就到20Mbps左右

**Comment by braveguywallce** [comment]
@bettermanbao @xtaci 

I have finished the test, the result is pretty awesome! My solution is as below:
1. SS deployed and working on the Router.
2. Kcptun deployed and working on one PC in the LAN, cause I still haven't any Pi on my hands, and I have to use the PC as the Pi.
3. Turn the UDP relay function off in the Router, just leaves the ChinaDNS working alone. without the upside UDP-server. But you still can use the UDP relay function only if you set the server for ss-tunnel separately.
4. The final speed is up to 9048-11257 kbps and keeps stable. Before that, it is only 748 kbps.

I would like to purchase a Raspberry Pi and install the kcptun on this. This is a really good solution for this moment and I would like recommend it to you all!

@xtaci  Thank you and appreciate your great work !

**Comment by Biercenter** [comment]
今天用另一台手机测试了一下，把kcptun客户端运行在手机上，然后通过局域网，路由器ss服务器端口指定到手机ip，也有改善。如果全部在路由器上运行，必须调低参数，不然还是会卡

**Comment by Comah** [comment]
@wxyzh 1.2MB/s 刚好就是我的12M电信宽带的速度了。
但不知什么原因，reboot VPS之后很难再连得上去.

**Comment by Comah** [comment]
@bettermanbao 我的是128m 内存的7620 ，下午换了你编译的版本，开始跑的时候很快很稳定，CPU也像更新日志所述一样降低了很多，但连续高速跑了一段时间之后server端自动断开，一直到现在都连不上。reboot之后重新执行脚本参数运行，但是还是无响应。

**Comment by bettermanbao** [comment]
换端口，流量太大，端口被封了，我也遇到过。
不要用fast2，用fast mode。

**Comment by Biercenter** [comment]
@bettermanbao 端口被封指服务器端口被封还是路由器端口？我一直是fast模式，可能是路由器性能问题，我这里fast2比fast卡，所以一直用的fast。

**Comment by Comah** [comment]
@bettermanbao 是的，我之前也是过换端口就可以恢复。但这次换了N个端口都不行。SS和KCPTUN的端口都换了。

**Comment by xtaci** [comment]
@Comah 重启光猫，电信经常会把路由表弄出问题。

**Comment by testcaoy7** [comment]
@Biercenter 用的normal，已经可以把电信的国际带宽出口撑满了，fast也没意义了

**Comment by Comah** [comment]
@xtaci 感谢。现在可以了，换了N个端口，重连了N次之后。。但还是会断开和很难链上
我看了HIBOY改的华硕固件，他的server版本是：selfbuild ，用他提供的这个自定义版本配合路由端基本上秒连上。
路由器上挂KCPTUN还是非常必要的，因为设备太多。一次性部署好之后基本无忧，太方便了。

**Comment by braveguywallce** [comment]
@xtaci @bettermanbao 
今天装了树莓派 3 b型，Arm7 v1 , 1G 内存，配合路由跑kcptun 20160811, 效果相当好！即使以很高的速度，比如 2.5-3.5 MB/s 下载数百兆的大文件，系统也运行平稳，没有windows下的崩溃。

CPU 占用率很有趣，下载大文件的时候，通讯刚开始握手，一下子窜到120-150%，这时候的下载速率在500-700KB, 但是一旦下载速率超过2MB, CPU的占用率反而降到了很低，大约在10-15%，并保持到下载结束，曲线表示呈f(x)=1/x的姿态。

用来看youtube 1080p的时候，CPU在树莓派上的占用率一般稳定在20%-30%，属于可以接受的范围。但是内存占用一般都比较大，无论看高清视频还是高速下载文件，内存都要用掉200-300M，比较吓人。好在树莓派有1G内存，也能对付。

以上测试没开启加密方式，明天我开启加密再测试下。

**Comment by xtaci** [comment]
@braveguywallce 非常详细，内存是个很刁钻的问题，这个问题我在openwrt x64的设备上也碰到过（2-300M），但是在ubuntu运行的时候，相同的二进制，内存占用始终很小。 我的猜测是内存碎片的问题，需要进一步分析。

**Comment by bettermanbao** [comment]
@braveguywallce 我的orange pi运行kcptun，fast mode，最快不超过10Mbps，一般稳定在6Mbps，cpu占用基本在20-150%。
内存到没注意过，明天我看看。想象中应该不大，肯定没200-300M这么多，我的系统是ubuntu 16.04。

**Comment by braveguywallce** [comment]
@bettermanbao 
我的树莓派是官方自带的Raspbian, 就是Debian 8.0的内核。

我的本地带宽是下行50M, 也是fast mode 放youtube 1080p 的时候，youtube connection speed 都保持在9-11 Mbps, 这时候CPU 占用率就是在f(x)=1/x的y=20-30%的位置（x=下载速率，y=CPU ratio)，但是一旦下载速率突破2MB,稳定在3MB,   CPU ratio马上就下来，只有10%甚至更低，非常有趣！我目前不知道为啥这么快的速度， CPU ratio反而这么低？难道是系统误显示？明天我开启加密了再用合适的工具比较严谨地验证下。

**Comment by xtaci** [comment]
另外，可以通过GOGC环境变量控制内存分配，释放策略
https://golang.org/pkg/runtime/ 这里有解释

The GOGC variable sets the initial garbage collection target percentage. A collection is triggered when the ratio of freshly allocated data to live data remaining after the previous collection reaches this percentage. The default is GOGC=100. Setting GOGC=off disables the garbage collector entirely. 


GOGC可以尝试调低为20, 30之类的尝试观察内存最大用量。

$ GOGC=30 ./client_linux_arm7 ....

**Comment by bettermanbao** [comment]
@braveguywallce 我猜测cpu下降可能是丢包率下降造成的，这个假设是否逻辑，召唤作者 @xtaci 来解答。

**Comment by xtaci** [comment]
@braveguywallce @bettermanbao 这个逻辑不成立，CPU高的原因，我猜测是大量的内存分配造成的，一旦内存分配到达一个稳定的水位线，则没有内存分配了，都是反复利用内存池。

**Comment by braveguywallce** [comment]
@xtaci 我观察到kcptun在系统结束高速下载任务后，内存释放需要一段时间,在树莓派上大约3 minute会把占用的大量内存释放到空闲待机水平。明天去试试看GOGC对内存管理是否有用。

**Comment by xtaci** [comment]
@braveguywallce 那就对了，就是这个问题。降低GOGC会提高GC的频率，更快的返还给系统。

**Comment by bettermanbao** [comment]
@xtaci 那是否可以增加一个内存预分配的参数？对于内存富裕的设备在启动时就分配好一定的内存，从而降低cpu的突发升高？

**Comment by xtaci** [comment]
@bettermanbao CPU突发是个小问题，时间很短。 内存回收策略是内置还是GOGC控制，这个是需要考虑的。

**Comment by xtaci** [comment]
https://blog.golang.org/go15gc

At a higher level, one approach to solving performance problems is to add GC knobs, one for each performance issue. The programmer can then turn the knobs in search of appropriate settings for their application. The downside is that after a decade with one or two new knobs each year you end up with the GC Knobs Turner Employment Act. Go is not going down that path. Instead we provide a single knob, called GOGC. This value controls the total size of the heap relative to the size of reachable objects. The default value of 100 means that total heap size is now 100% bigger than (i.e., twice) the size of the reachable objects after the last collection. 200 means total heap size is 200% bigger than (i.e., three times) the size of the reachable objects. If you want to lower the total time spent in GC, increase GOGC. If you want to trade more GC time for less memory, lower GOGC.

**Comment by bettermanbao** [comment]
@xtaci 其实在arm/x86/amd64平台上运行，CPU，内存已经都不是瓶颈了。我个人觉得如何提高有效载荷比和控制延时才是今后更新的大方向。

**Comment by xtaci** [comment]
是的，算法是根本。

**Comment by braveguywallce** [comment]
@xtaci  今天继续测试，加上了加密方法 tea, 无论看1080p还是1440p的youtube视频，kcptun的CPU开销（60%-145%）和内存占用（约30-100M)都没啥大的问题。现在的问题还是通过kcptun高速下载大文件，比如500M以上的youtube视频，内存开销惊人，会很快跃升到300M以上，即使设置GOGC=30, 但是没有什么帮助，随着下载时间的进行，本地下载速度逐渐增大到3MB/s 以上，kcptun的内存开销居然达到500多M, 这个需要后续的改进。否则以后压根无法在小路由上运行下载大文件。

另外，我建议server & client都要加上crypt, 今天整天没遇到疑似QoS的问题发生，connection speed一直很快很稳定。

@bettermanbao  你可以尝试用你的orange pi下载大的视频文件，看看CPU和Memory的情况。

**Comment by xtaci** [comment]
@braveguywallce 如果内存没有办法通过GOGC改善，下个版本我准备尝试加上定期GC。

**Comment by braveguywallce** [comment]
@xtaci 目前除了客户端高速持续长时间下载大文件的时候占用内存过大以外，一般的看看HD视频啥的内存都没有问题。我明天再调节下GOGC参数看看。

**Comment by xtaci** [comment]
好的，能通过GOGC解决最好。

**Comment by Cye3s** [comment]
说到内存，x64 Openwrt 的确是看youtube高清后内存会暴增，我现在的做法是一天重启一次kcptun客户端，很稳定
其实2G内存占用个600M也没感觉，毕竟还有将近一半的Free
另外，弄个x86或x64的多网卡板来跑openwrt，很方便，kcptun+ss+dnsmasq+ipset一机解决，基本不会有性能问题

**Comment by xtaci** [comment]
@Cye3s GOGC=20 ./client......  基本能稳， 另外定期重启是个好办法。

**Comment by Cye3s** [comment]
好，我加上这个参数看看，这两天先不定时重启

**Comment by bettermanbao** [comment]
@braveguywallce 我下载了几段youtube的视频，观察到了和你完全相同的现象。
开始的时候下载速度不快，700-800KB/s，CPU占用150%左右，kcptun的内存占用也不多。下载一段时间后，速度突然飙升到4-5MB/s，这时内存使用就开始飙升，CPU利用率反而下降很多。实时流量参考截图，蓝色的是client收到的KCP协议的UDP包，橙色的是client还原的原始数据。

感觉末端的速度爆发是kcptun把缓存的数据一下子全部吐了出来。

**Comment by braveguywallce** [comment]
@xtaci 抱歉，我测试做得不够全面！今天测试从几个大的站点下载1G大文件，结果遇到了新的情况。基本上有两种情况：

1. 和下载youtube视频类似，起始速度比较小，kcptun client的效率比较低，后面会突然冲高速，后半段kcptun的效率很高，本地路由提示出站和入站的流量基本一致，这种情况下kcptun client的内存也会比较大，通常都要200M以上。
2. 和下载youtube视频不一样，kcptun client的效率从开始到结束保持基本恒定的状态，较低，下载速度始终在700KB-1MB,，比较稳定，但是Kcptun本地内存占用却一直很低，大约不超过65M. 

这样的话，是否要考虑目标主机的因素了？从不同主机下载大文件，本地端的内存占用是不一样的。

**Comment by w12928293** [comment]
@braveguywallce 
请教下，如果想路由上跑ss，树莓派上跑kcp的客户端的话，是不是vps上需要装kcpserver和ss服务端？

还是vps上只装kcpserver，树莓派上装kcpclient和ssserver？

**Comment by braveguywallce** [comment]
@w12928293 

You have to install the server of both kcptun & ss in your VPS, and you can deploy the kcptun client in the Raspberry Pi alone, with SS working on the Router. 

It's simple, easy & high efficiency!

**Comment by w12928293** [comment]
@braveguywallce 多谢回复。

原谅我愚钝，有些地方还是没弄明白。如果是那样的话

比如：vps：10.10.10.10，ss端口443，kcp端口554
树莓派lan：192.168.0.2，kcp监听端口1080
这样的话，我路由上的ss应该怎么配置才能利用到kcp的加速效果呢？看起来kcp好像和ss是完全独立了。

**Comment by braveguywallce** [comment]
@w12928293 
No, you can't use 1080 as the local port for kcptun, leave it as default , like 12940, and set the "server port" of your  SS client as the" local port" of kcptun.

**Comment by w12928293** [comment]
@braveguywallce 
奥，原来kcpclient不能用1080。。。
比如是local是12940，那我路由上ss处ip是192.168.0.2，端口是12940，密码是ssServer的密码。这样对吗？
vps上kcpserver的加速端口是不是要填ssserver的端口，127.0.0.1:443？

**Comment by lizongzeshunshun** [comment]
@w12928293 
Server: kcptun(server) + ssserver
Client: kcptun(client) + sslocal

比如Vps 10.10.10.10，ss端口443，kcp的-t参数要设为"127.0.0.1:443"，-l就是你的":554"
Local的Kcptun的-r参数设置为"10.10.10.10:554"，-l随便（例如-l ":6666"）
那么Local的SS的服务器ip设为127.0.0.1，服务器端口设为6666

**Comment by w12928293** [comment]
@lizongzeshunshun 
多谢回复！
好像是明白了，这样的话我的树莓派上只需要跑一个kcpclient就可以了对吧。

**Comment by lizongzeshunshun** [comment]
@w12928293 
其实这张图表达的很明白了
![KCPTUN](https://github.com/xtaci/kcptun/blob/master/kcptun.png?raw=true)

可以树莓派跑kcptun(client)，路由器跑shadowsocks，这样应该是效率最高的了
shadowsocks的服务器ip设为pi的内网ip就行了

**Comment by w12928293** [comment]
@lizongzeshunshun 
我正在这样尝试，还没成功。。。
弱弱的问下，树莓派应该下那个版本的client。。。我用linux386的怎么跑步起来。。。

**Comment by lizongzeshunshun** [comment]
@w12928293 
树莓派应该是arm架构的，应该下
**kcptun-linux-arm-20160816.tar.gz**

**Comment by w12928293** [comment]
@lizongzeshunshun 
果然啊！成功了！

太感谢了！

最开始执行语句老长了，加了各种参数。。。然后跑不起来

后来我用作者提供的默认的
服务器: ./server_linux_amd64 -t "127.0.0.1:443" -l ":554" -mode fast2  // 转发到服务器的本地8388端口
客户端: ./client_darwin_amd64 -r "服务器IP地址:554" -l ":8388" -mode fast2    // 监听客户端的本地8388端口
成功了，

可是 怎么添加开机启动及后台运行呢？

**Comment by braveguywallce** [comment]
@w12928293  please use google to find answers by yourself first, then come to ask.

**Comment by w12928293** [comment]
@braveguywallce 

教育的对。
折腾了好久，实在是有点着急了，抱歉！
多谢你的解答，还有@lizongzeshunshun。

**Comment by braveguywallce** [comment]
yamux kuptun的CPU/MEM 问题目前在smux kcptun上初步有了比较好的解决，参考 #168

**Comment by henryshen033** [comment]
@w12928293 请问你最后如何成功设置开机启动的，我把加入命令加入/etc/rc.local和新建一个systemctl都试过了，都失败了，但是source /etc/rc.local是能够运行的，当然我确定开机是会加载/etc/rc.local的
