### ISSUE TITLE
getsockopt错误，无法连上

### ISSUE THREAD

**Issue by yuan78** [xtaci/kcptun#112]
VPS报错如下：

2016/08/10 23:17:07 dial tcp 127.0.0.1:8388: getsockopt: connection refused
2016/08/10 23:17:07 [ERR] yamux: Failed to read header: broken pipe

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Does your ISP or VPS **blocked UDP**?
5. Does your VPS **firewall** allows UDP pass through?
6. Are you using the **same version** for both client & server
7. Did you correctly set the ```-target value, -t value	target server address (default: "127.0.0.1:12948")``` on the server side?

**Comment by yuan78** [comment]
1. Are you using the latest release?    Reply :  Yes,
2. Which OS do you use?  Reply : VPS: ubuntu 14.04, Client: WIN64
3. Which end for this issue related to, client or server? Reply :  Both for server and client
4. Does your ISP or VPS blocked UDP?   Reply : Not sure
5. Does your VPS firewall allows UDP pass through?  Reply :  no firewall
6. Are you using the same version for both client & server Reply :  Yes 
7. Did you correctly set the -target value, -t value target server address (default: "127.0.0.1:12948") on the server side? Reply :  Yes, comand as follow:

./server_linux_amd64 -t "127.0.0.1:8388" -key "onlymeconnectA@a" -crypt "aes" -l ":968" 


./client_windows_amd64 -r "VPS IP:968" -key "onlymeconnectA@a" -crypt "aes"-l ":8688"

**Comment by xtaci** [comment]
#102

**Comment by yuan78** [comment]
root@default:~# telnet 127.0.0.1:8388
telnet: could not resolve 127.0.0.1:8388/telnet: Name or service not known
root@default:~# telnet 23.83.239.172:8388
telnet: could not resolve 23.83.239.172:8388/telnet: Name or service not known

**Comment by imtrobin** [comment]
我用vultr, 也不能接。

Are you using the latest release? Yes,
Which OS do you use? VPS: ubuntu, Client: win7 64bit
Does your ISP or VPS blocked UDP? No
Does your VPS firewall allows UDP pass through?
sudo ufw status
Status: inactive
Are you using the same version for both client & server? Yes

Server:
~/kcptun# ./server_linux_amd64 -t "0.0.0.0:8388" -key "onlymeconnectA@a" -crypt "aes" -l ":968"
2017/07/29 02:43:01 version: 20170525
2017/07/29 02:43:01 listening on: [::]:968
2017/07/29 02:43:01 target: 0.0.0.0:8388
2017/07/29 02:43:01 encryption: aes
2017/07/29 02:43:01 nodelay parameters: 0 30 2 1
2017/07/29 02:43:01 sndwnd: 1024 rcvwnd: 1024
2017/07/29 02:43:01 compression: true
2017/07/29 02:43:01 mtu: 1350
2017/07/29 02:43:01 datashard: 10 parityshard: 3
2017/07/29 02:43:01 acknodelay: false
2017/07/29 02:43:01 dscp: 0
2017/07/29 02:43:01 sockbuf: 4194304
2017/07/29 02:43:01 keepalive: 10
2017/07/29 02:43:01 snmplog:
2017/07/29 02:43:01 snmpperiod: 60
2017/07/29 02:43:01 pprof: false
2017/07/29 02:43:01 remote address: X.X.X.X:59964
2017/07/29 02:43:01 dial tcp 0.0.0.0:8388: getsockopt: connection refused
2017/07/29 02:43:02 dial tcp 0.0.0.0:8388: getsockopt: connection refused
2017/07/29 02:43:03 dial tcp 0.0.0.0:8388: getsockopt: connection refused


Client:
D:\Program Files\Net\KcpTun>client_windows_amd64 -r "X.X.X.X:968" -key "onlymeconnectA@a" -cryp
t "aes" -l ":8688"
2017/07/29 10:43:01 version: 20170525
2017/07/29 10:43:01 listening on: [::]:8688
2017/07/29 10:43:01 encryption: aes
2017/07/29 10:43:01 nodelay parameters: 0 30 2 1
2017/07/29 10:43:01 remote address: X.X.X.X:968
2017/07/29 10:43:01 sndwnd: 128 rcvwnd: 512
2017/07/29 10:43:01 compression: true
2017/07/29 10:43:01 mtu: 1350
2017/07/29 10:43:01 datashard: 10 parityshard: 3
2017/07/29 10:43:01 acknodelay: false
2017/07/29 10:43:01 dscp: 0
2017/07/29 10:43:01 sockbuf: 4194304
2017/07/29 10:43:01 keepalive: 10
2017/07/29 10:43:01 conn: 1
2017/07/29 10:43:01 autoexpire: 0
2017/07/29 10:43:01 scavengettl: 600
2017/07/29 10:43:01 snmplog:
2017/07/29 10:43:01 snmpperiod: 60
2017/07/29 10:43:01 connection: 192.168.0.100:59964 -> X.X.X.X:968
2017/07/29 10:43:04 stream opened
2017/07/29 10:43:06 stream closed
2017/07/29 10:43:07 stream opened
2017/07/29 10:43:07 stream closed
2017/07/29 10:43:08 stream opened
2017/07/29 10:43:08 stream closed

**Comment by abusizhishen** [comment]
dial tcp 127.0.0.1:8388: getsockopt: connection refused
