### ISSUE TITLE
[ERR] yamux: Failed to read header: snappy: corrupt input

### ISSUE THREAD

**Issue by wupeng1211** [xtaci/kcptun#114]
[ERR] yamux: Failed to read header: snappy: corrupt input

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Does your ISP or VPS **blocked UDP**?
5. Does your VPS **firewall** allows UDP pass through?
6. Are you using the **same version** for both client & server
7. Did you correctly set the ```-target value, -t value	target server address (default: "127.0.0.1:12948")``` on the server side?

**Comment by wupeng1211** [comment]
wget https://github.com/xtaci/kcptun/releases/download/v20160808/kcptun-linux-amd64-20160808.tar.gz

**Comment by xtaci** [comment]
-nocomp must be specified on both side.

**Comment by wupeng1211** [comment]
好的，我试试最新版，谢谢

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Are you using the **same version** for both client & server
5. Did you correctly set the ***-target value, -t value	target server address (default: "127.0.0.1:12948")*** on the server side?
6. Can ```telnet target port``` successful?
7. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
