### ISSUE TITLE
yamux: Failed to read header: broken pipe

### ISSUE THREAD

**Issue by ShikiYuki** [xtaci/kcptun#115]
server 参数
./server_linux_amd64 -l :8000 -t 127.0.0.1:9527 -key key -mtu 1350 -sndwnd 2048 -rcvwnd 2048 -mode fast2

client参数
client_windows_386.exe -l :29900 -r  serverIP:8000 -key key -mtu 1350 -sndwnd 64 -conn 1 -rcvwnd 512 -mode fast2 -dscp 46

server端log
2016/08/11 15:47:53 version: 20160811
2016/08/11 15:47:53 listening on  [::]:8000
2016/08/11 15:47:53 encryption: aes
2016/08/11 15:47:53 nodelay parameters: 1 20 2 1
2016/08/11 15:47:53 sndwnd: 2048 rcvwnd: 2048
2016/08/11 15:47:53 compression: true
2016/08/11 15:47:53 mtu: 1350
2016/08/11 15:47:53 datashard: 10 parityshard: 3
2016/08/11 15:47:53 acknodelay: false
2016/08/11 15:47:53 dscp: 0
2016/08/11 15:47:53 sockbuf: 4194304
2016/08/11 15:47:53 keepalive: 10

client端log
2016/08/11 23:47:38 version: 20160811

2016/08/11 23:47:38 listening on: [::]:29900

2016/08/11 23:47:38 encryption: aes

2016/08/11 23:47:38 nodelay parameters: 1 20 2 1

2016/08/11 23:47:38 remote address: serverIP:8000

2016/08/11 23:47:38 sndwnd: 64 rcvwnd: 512

2016/08/11 23:47:38 compression: true

2016/08/11 23:47:38 mtu: 1350

2016/08/11 23:47:38 datashard: 10 parityshard: 3

2016/08/11 23:47:38 acknodelay: false

2016/08/11 23:47:38 dscp: 46

2016/08/11 23:47:38 sockbuf: 4194304

2016/08/11 23:47:38 keepalive: 10

2016/08/11 23:47:38 conn: 1

2016/08/11 23:47:52 stream opened

2016/08/11 23:48:38 [ERR] yamux: keepalive failed: i/o deadline reached

2016/08/11 23:48:38 [ERR] yamux: Failed to read header: broken pipe

2016/08/11 23:48:38 stream closed

2016/08/11 23:48:38 session shutdown

2016/08/11 23:48:38 stream opened

2016/08/11 23:49:36 stream closed

2016/08/11 23:49:38 [ERR] yamux: keepalive failed: i/o deadline reached

2016/08/11 23:49:38 [ERR] yamux: Failed to read header: broken pipe

2016/08/11 23:50:02 session shutdown

2016/08/11 23:50:02 stream opened

2016/08/11 23:50:02 stream opened

请教一下这个参数上有没有什么问题，如果配置没有问题，是ISP的干扰的话，只能暂时放弃折腾了

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Are you using the **same version** for both client & server
5. Did you correctly set the ***-target value, -t value	target server address (default: "127.0.0.1:12948")*** on the server side?
6. Can ```telnet target port``` successful?
7. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.


https://github.com/xtaci/kcptun#故障排除-lollipop

**Comment by ShikiYuki** [comment]
1. latest release on both server and client side

2. server: Debian 8.5 x64. client: Win 10 pro x64 ver 1607

3. it seems error messages only appear in client log

4. yes, for server kcptun-linux-amd64-20160811, for client kcptun-windows-386-20160811(some issue while downloading amd64, using 386 instead)

5. I thought my -t value is ok, as I'm using port 9527 as my ss port

6. do you mean telnet 127.0.0.1 9527 on server? I got this:
telnet 127.0.0.1 9527
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

7. -key is the same on both side, -nocomp, -datashard, -parityshard, -crypt are not used in either side, I guess that means they are default valve on both side?

**Comment by xtaci** [comment]
does iptables allows UDP passthrough on your server?

**Comment by ShikiYuki** [comment]
抱歉，能请教下如何检查vps上的UDP passthrough情况吗

网络配置不熟悉，不是太明白哪一项参数是对应这个的

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:10443 /* eth0 (ocserv3) */
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:10443 /* eth0 (ocserv4) */

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            192.168.10.0/24      /* eth0 (ocserv2) */
ACCEPT     all  --  192.168.10.0/24      0.0.0.0/0            state RELATED,ESTABLISHED /* eth0 (ocserv5) */

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by ShikiYuki** [comment]
今晚又尝试了一下，一直得到如下的log
2016/08/12 23:12:20 stream closed

2016/08/12 23:12:20 stream opened

2016/08/12 23:12:20 stream closed

2016/08/12 23:12:20 stream opened

server端和client端都是这样
网页还是无法打开，broken pipe倒是没出现

**Comment by xtaci** [comment]
I have no idea.    everything is normal.

**Comment by ShikiYuki** [comment]
A couple of minutes ago I reinstalled vps, re installed ss&kcptun, re-downloaded client, and now it works.

No idea why...

Sorry for bothering you.
