### ISSUE TITLE
YouTube的Flash模式和HTML5模式使用时的效果不同。

### ISSUE THREAD

**Issue by tanbofan** [xtaci/kcptun#116]
使用Flash模式的时候基本没什么问题，但是用Html5模式的时候就有卡顿，不知道各位有这样的问题吗？

**Comment by dolphinpaopao** [comment]
win10 x64，nvidia显示卡，chrome x64默认的html5播放器正常。出现卡顿考虑网络、显卡驱动、安全软件防火墙这些原因。

**Comment by tanbofan** [comment]
我用的是OSX系统，回家用win10测试一下吧！

**Comment by xtaci** [comment]
应该首先考虑升级到最新的chrome
