### ISSUE TITLE
client request of supporting connects to Server via http / socks proxy

### ISSUE THREAD

**Issue by yumin9822** [xtaci/kcptun#117]
Hi,
  This request is about the KCP client. Because my laptop at company connects to internet via a http proxy.  It has no direct connection to internet. So I  am requesting clients to support http/ socks proxy just like SSR client does.  
![global_proxy.PNG](https://ooo.0o0.ooo/2016/08/12/57ad74c55814a.png)

Thanks!

**Comment by yumin9822** [comment]
请求客服端增加支持http socks代理连接server的功能。

**Comment by xtaci** [comment]
It's completely impossible. you have to do some kind of Relaying.

**Comment by yumin9822** [comment]
OK， Thanks for your comments.
