### ISSUE TITLE
麻烦给下最新版本的 配置文件样例好吗 

### ISSUE THREAD

**Issue by blankhang** [xtaci/kcptun#118]
包括服务端 与 客户端的...
另外默认的加密是 AES 如果更改呢
我发现 升级到最新的 客户端 配置文件好像不对 启动报错了
非常感谢!

**Comment by dolphinpaopao** [comment]
请仔细阅读首页的相关内容，上面都有详细的解释说明，目前加密支持aes，tea，xor和none，服务端和客户端分别都加上--crypt tea或者--crypt xor或者--crypt none参数实现加密方式更换。其中none为不加密。

**Comment by blankhang** [comment]
我指的是 能让 客户端 直接方便启动 -c client.json 就能跑起来的 样例 并没有
只有基础的说明 我想看的是 生成的 配置文件.... 而不是直接启动加参数 的 这样 每次启动 太麻烦了.

**Comment by dolphinpaopao** [comment]
#107 作者表示没有计划支持配置文件，linux系统编辑/etc/rc.local即可实现，windows也可自己添加开机启动。

**Comment by xtaci** [comment]
@blankhang 你把启动命令写到一个.bat文件就可以了啊
