### ISSUE TITLE
服务端更新是否需要客户端跟着更新？

### ISSUE THREAD

**Issue by icecrack** [xtaci/kcptun#119]
服务器端更新了程序后，客户端是否需要更新，这个是否可以在更新说明里给加上？

**Comment by xtaci** [comment]
只要能通 都不是必须更新 但建议更新

**Comment by icecrack** [comment]
如果只是桌面版好说，因为你是客户端服务器一起发布的，可以更新，而移动端是别的开发者更新的，如果移动客户端不支持的话，在部署服务器端就会有选择性的更新了。现在只能现部署后测试，不行再退档。

**Comment by xtaci** [comment]
都是兼容的。
