### ISSUE TITLE
至从用了 mtu 选项的版本，感觉没有以前好用，确认下。

### ISSUE THREAD

**Issue by jannson** [xtaci/kcptun#12]
现象是，百度什么很好访问，确认走代理。但是 google 偶尔可以偶尔不行，很频繁。

当选用加密的时候：
https://github.com/xtaci/kcp-go/blob/master/sess.go#L108

加密的 mtu 会比默认 减去 headerSize

但是为何 SetMtu 这里的时候又没有减去？ 会有什么后果？

mtu 值需要客户端与服务器端的 mtu值能通，不被分片就可以了吧？不关新与其它服务器的 mtu 值的关系。

我准备去掉 Mtu 选项试试。

**Comment by xtaci** [comment]
SetMtu是减去了的，你更新下kcp-go
mtu只要不分片就行了

**Comment by jannson** [comment]
现在好了，昨晚研究半天，才发现跟 mtu 相关。应该可以编译给小部分人使用了，加了代理的。
感谢大神的耐心。

**Comment by xtaci** [comment]
嗯，功德一件。

**Comment by xtaci** [comment]
@jannson 我的release编译用的https://github.com/xtaci/kcptun/blob/master/build-release.sh 这个脚本
主要是用来设定VERSION
