### ISSUE TITLE
possible QoS problem? 

### ISSUE THREAD

**Issue by braveguywallce** [xtaci/kcptun#120]
下午用局域网的PC跑 kcptun 大概有了2-3个小时，起始下载速度非常快，达到2.5-3.0 MB/s, 但是用了一段时间后，速度急剧降低，播放视频大约只能到 500 kbps的龟速。在服务器上更换了端口以后，速度一下子又恢复了。
这是否是kcptun高速发送UDP包触发了ISP的QoS 机制？ Kcptun有否这方面的伪装机制而躲过这样的QoS?网络环境：电信
版本：20160808

**Comment by wxyzh** [comment]
估计困难，最主要的原因是，宽带提速，但是国际出口没增加到相应的带宽。我上午用curl从vps上下文件，能满速，到中午的时候就只有100K了。

**Comment by braveguywallce** [comment]
![kcptun](https://cloud.githubusercontent.com/assets/5782014/17642422/e60c190a-6178-11e6-931f-008a30a16de3.jpg)
另外，下载大文件，kcptun for windows 就会崩溃。

**Comment by xtaci** [comment]
@braveguywallce 崩溃问题从未出现过，建议更新到最新版本测试。

**Comment by xtaci** [comment]
电信只有一条海底光缆，是严重不足的，任何QoS都可能。联通有四条海底，从未出现过问题。

**Comment by braveguywallce** [comment]
@xtaci 好的，我把PC当LAN中的服务器跑也是权宜之计，后天树莓派到了以后我还是放在Linux环境下测试比较好。
谢谢！
