### ISSUE TITLE
Mac版经常出现速度极慢的状况

### ISSUE THREAD

**Issue by isbaseby** [xtaci/kcptun#121]
服务器和客户端版本是0811的，具体表现为在看一段时间YouTube(1小时左右)就后出现速度极慢(几百kbps)，正常情况在5000kbps,重启kcptun后会恢复正常，然后过一段时间又会出现这个问题。

而这个时候在服务端和客户端用iftop对比查看，客户端入站流量确实只有几百kbps，但是服务端出站流量却是实际消耗流量的10倍左右。(当然，服务端的流量都是kcptun的，没有其他服务占用流量)

而且经过几天使用，发现同样的网络环境和kcptun配置并且在同样的时间段，android版shadowsocks开启kcptun可以跑到2MB/S，Mac版只能跑到不到1MB/S。

kcptun配置如下
--crypt none --mtu 1400 --sndwnd 128 --rcvwnd 512  -dscp 46 -mode fast2

**Comment by xtaci** [comment]
crypt最好加上 none的时候，协议是暴露的。 另外1024以下的服务器端口受影响较小。

**Comment by isbaseby** [comment]
@xtaci  我用的554端口，在Mac端也是配合shadowdocks使用的，这样也会出问题？

**Comment by xtaci** [comment]
crypt是必须有的，即便是最简单的xor模式，也应该要有。

**Comment by isbaseby** [comment]
多谢，换成了tea，用一段时间再来反馈

xtaci <notifications@github.com>于2016年8月13日周六 21:52写道：

**Comment by isbaseby** [comment]
@xtaci 
用这个配置  
--crypt none --mtu 1400 --sndwnd 128 --rcvwnd 512 -dscp 46 -mode fast2
经过几天发现问题还是没有解决，每次出现速度极慢的情况都要手动重启kcptun
