### ISSUE TITLE
奇怪的无法通信的问题

### ISSUE THREAD

**Issue by testcaoy7** [xtaci/kcptun#122]
从昨天下午开始无法连通

症状：
客户端和服务器都有stream opened 和 stream closed信息，上层软件（SS）的配置也是完全正确的，不经过KCP直接连接SS，可以通。

此外，现在服务器和客户端很容易出现：
[ERR] yamux: keepalive failed: i/o deadline reached
[ERR] yamux: Failed to read header: broken pipe
这两条记录。

SS监听在10000端口上，KCP的服务器参数：
kcptun -mtu 1400 -sndwnd 512 -rcvwnd 512 -mode normal -l 0.0.0.0:500 -t 127.0.0.1:10000 -crypt none -datashard 10 -parityshard 3 -dscp 46 -sockbuf 5767168

KCP客户端的参数：
kcptun -mtu 1400 -sndwnd 256 -rcvwnd 512 -mode normal  -l 127.0.0.1:2016 -r VPS:500 -crypt none -datashard 10 -parityshard 3 -dscp 46 -sockbuf 5767168

**Comment by xtaci** [comment]
-crypt aes

**Comment by testcaoy7** [comment]
@xtaci 试过了，换任何加密都不行。还试过重启光猫、换VPS、换端口，均不行。

**Comment by xtaci** [comment]
ping观察丢包率。

**Comment by testcaoy7** [comment]
100个Ping数据包，无一丢失。最后还是通过换端口解决了。是这样的，无法通信的时候我查看了SS的日志，表现和正常时一样，说明我这边到VPS没问题，而是VPS到我这边出了问题，应该是我的光猫的端口被运营商禁用的问题，几个常换的端口都不行，换了个随机的端口就通了。

**Comment by xtaci** [comment]
你是不是用了光猫的nat，而不是自己拨号的pppoe?

**Comment by testcaoy7** [comment]
@xtaci 是的，我用的不是自己拨号的PPPoE

**Comment by xtaci** [comment]
光猫上有防火墙

**Comment by testcaoy7** [comment]
电信真恶心，防火墙关不掉，只能设为低

**Comment by xtaci** [comment]
可以打1000号修改为pppoe

**Comment by hbxntsxw** [comment]
@testcaoy7 你好，我的情况跟你一样。请问你修改端口是指修改你例子里面的500、10000，还是2016啊？我电脑死活连不上，电脑版shadowsocks流量只出不进，而shadowsock安卓版自带的kcptun填上参数后都使用正常。谢谢！

**Comment by testcaoy7** [comment]
@hbxntsxw 修改KCP服务器端的端口，也就是例子中的500，不要用敏感端口，500是IKEv2和VPN密钥交换的端口，可能正是我使用敏感端口引起了运营商的注意，你可以试试用80端口

**Comment by hbxntsxw** [comment]
@testcaoy7 @xtaci 
我修改端口也不行，连不上。服务端和客户端stream open和closed也会有。也会这两个错误：
[ERR] yamux: keepalive failed: i/o deadline reached
[ERR] yamux: Failed to read header: broken pipe
奇怪的是相同网络下Android版shadowsocks自带的kcptun却能正常连接，速度也很快。这应该不是端口被封造成的吧？修改端口安卓上同样可以连上，但是电脑和路由器就是不行。真的想不出来是什么问题了。

**Comment by testcaoy7** [comment]
@hbxntsxw 等新版本发布再看看

**Comment by hbxntsxw** [comment]
今天再试了一下，发现电脑上的shadowsocks可以正常连上安卓手机上运行的kcptun，但就是连接不上电脑本身运行的kcptun。

**Comment by eneslau** [comment]
有人解决了吗？我也遇到这个问题了...

**Comment by Tao314** [comment]
一样的问题，有人解决的话，共享下啊
