### ISSUE TITLE
kcptun automatic reconnection

### ISSUE THREAD

**Issue by KarlM256** [xtaci/kcptun#123]
Before firing issue, make sure you figured out the following common questions.

1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Are you using the **same version** for both client & server
5. Did you correctly set the ***-target value, -t value	target server address (default: "127.0.0.1:12948")*** on the server side?
6. Can ```telnet target port``` successful?
7. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
8. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)

**Comment by KarlM256** [comment]
In using Shadowsocks on Android with KCP support, I have an occasional disconnect. It seems to happen when the phone is idle. If I turn off battery optimization for Shadowsocks on my phone (Nexus 6, current Marshmalow) the problem goes away and the connection stays up for a long time. I also have an issue that sometimes when I connect to the server from Shadowsocks Android, it fails to start. If I disconnect and reconnect it almost always works.

I saw some comments about dynamically adjusting parameters to optimize the link. I would not like to have the parameters change automatically, or at least have the default be to maintain static parameters.

I would like to see KCP detect when the link fails and restart it.

**Comment by xtaci** [comment]
it's up to ss on android to detect network stats change.
