### ISSUE TITLE
请问服务器端的参数，客户端是否需要保持一致

### ISSUE THREAD

**Issue by xiaojiulala** [xtaci/kcptun#124]
sndwnd 128 -rcvwnd 1024 假如这两个参数服务器端这样填，客户端数值是否需要保持一致  conn多线程的，需要服务器先开启吗

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun#参数调整-lollipop

这里有说明

**Comment by xiaojiulala** [comment]
conn好像没说明

**Comment by xtaci** [comment]
conn只能在客户端设置

**Comment by xiaojiulala** [comment]
好的，谢谢，wiki或者首页那里最好带这些链接，也不用发帖问你了，只是提个建议。

**Comment by wxyzh** [comment]
@xiaojiulala 我记得readme里有说明哪些参数必须一致的
