### ISSUE TITLE
docker镜像如何运行？

### ISSUE THREAD

**Issue by tanbofan** [xtaci/kcptun#125]
想将KCPTUN部署到docker中，但是执行“docker run -d -p 1505:1505 -p 29900:29900 xtaci/kcptun -r xxx.xxx.xxx.xxx:29900 -l :1505 -key test -mtu 1400 -mode fast3”会报错：“FATA[0000] Error response from daemon: Cannot start container 7058434a682a58f9bdeec1e88ff9cfad10c3866bfdb7416d01fb959ad5f13af1: [8] System error: exec: "-r": executable file not found in $PATH”。请问该如何启动docker镜像？

**Comment by xtaci** [comment]
docker run -d -p 1505:1505 -p 29900:29900 xtaci/kcptun ***client*** -r xxx.xxx.xxx.xxx:29900 -l :1505 -key test -mtu 1400 -mode fast3

**Comment by tanbofan** [comment]
问题已解决，感谢！

**Comment by cishimingyuan** [comment]
Mark
