### ISSUE TITLE
带宽利用率过低？？

### ISSUE THREAD

**Issue by chestnutprog** [xtaci/kcptun#126]
![image](https://cloud.githubusercontent.com/assets/13086194/17662614/509d3e60-6319-11e6-805c-d3be594d899a.png)
fast2模式
好像如果速度瓶颈在服务器那么浪费只有几分之一。。。下载和看油管好像都有超大的浪费

**Comment by dolphinpaopao** [comment]
#66 缓存问题。下载完成后统计一下下载所用时间就知道实际速度不止这点。

**Comment by chestnutprog** [comment]
那有办法通过改参数尽量减少这个问题的影响吗

**Comment by chestnutprog** [comment]
感觉除了缓存可能和别的因素有关，我发现如果服务器访问目标的速度小于带宽的话这个问题就基本不会出现，但是如果果服务器访问目标的速度远大于带宽的话似乎速度就一直很慢。。。。。。。。

**Comment by bettermanbao** [comment]
@dolphinpaopao 你描述的问题，我也遇到了。可能是kcptun的bug。

**Comment by xtaci** [comment]
如果是和目标服务器的速度有关，那么问题是在kcptun的TCP 部分

**Comment by xtaci** [comment]
归根结底还是yamux的问题，yamux内部有个recvLoop，会一直读到内部缓存中。

**Comment by bettermanbao** [comment]
recvLoop缓存把数据吐出来的触发条件是什么？

**Comment by xtaci** [comment]
@bettermanbao 客户端从tcp中读取 --- recv()

**Comment by xtaci** [comment]
yamux的流控确实太低端了

**Comment by bettermanbao** [comment]
kcptun不是一直在读取吗？照道理缓存应该很小，收到的数据马上就被读取了。

**Comment by xtaci** [comment]
应用程序并没有及时读取

**Comment by bettermanbao** [comment]
下载的时候，应用程序会发生不及时读取？不是很理解

**Comment by xtaci** [comment]
@bettermanbao 这个太正常了， 比如视频流，只需要满足frame rate的读取就够了，不需要不停的读取。   不同于下载，这个是yamux的bug。

**Comment by bettermanbao** [comment]
视频可以理解，但是我是下载的时候开始几百K速度，快结束的时候速度突然飙到几M，你可以看这里最后的截图。

https://github.com/xtaci/kcptun/issues/111

**Comment by xtaci** [comment]
这么说起来，图形看上去是先一次性收到kcptun client，然后再一次性送到应用程序？

**Comment by bettermanbao** [comment]
截图里3个橙色的波峰，感觉这次下载期间发生了3次缓存被全部读取。
蓝色的UDP数据流全程基本稳定，波动仅发生在原数据流。感觉缓存被完全读取需要某些触发条件。

**Comment by bettermanbao** [comment]
这个现象在下载大文件时容易被察觉，浏览网页等传输小文件是，应该完全不会察觉。

**Comment by xtaci** [comment]
那么可能性只有这两种:
1. 应用程序没有发起recv()。
2. 应用程序发起了recv()，但因为某种原因（抢占maybe) 阻塞了。

**Comment by xtaci** [comment]
@bettermanbao 我目前能修改的只有第二种可能，应用程序是否读了我没法推断，等会儿我尝试修改一个地方，看一下是否有变化。

**Comment by xtaci** [comment]
[kcptun-windows-amd64-20160816.tar.gz](https://github.com/xtaci/kcptun/files/419675/kcptun-windows-amd64-20160816.tar.gz)
[kcptun-linux-amd64-20160816.tar.gz](https://github.com/xtaci/kcptun/files/419676/kcptun-linux-amd64-20160816.tar.gz)
[kcptun-darwin-amd64-20160816.tar.gz](https://github.com/xtaci/kcptun/files/419677/kcptun-darwin-amd64-20160816.tar.gz)


@bettermanbao 试下这个我临时编译的。

**Comment by chestnutprog** [comment]
几乎没变化。。。。

**Comment by dolphinpaopao** [comment]
@bettermanbao 感觉不像是bug，更多的像是效率问题，坐等以后改进了。

**Comment by braveguywallce** [comment]
@xtaci @bettermanbao 我找了比较好的网络环境，和国外VPS的通讯非常通畅，分别实验了开启kcptun和关闭kcptun，因为本来网络环境就很畅通，开关kcptun对youtube视频的connection speed没有影响，开启kcptun后connection speed还要略高一些。但是影响的是buffer health 缓冲度，缓冲度越长就越方便观看，说明kcptun传递tcp数据的效率越高，开启kcptun后，虽然和connection speed还是很快，但是视频的缓冲度明显比较短，不利于观看，可能kcptun客户端把接收的数据没有及时迅速地被应用程序所读取。而关闭kcptun后，buffer health 缓冲度明显就长很多了，是开启kcptun时的3-5倍，这样就比较方便观看。

这是否是kcptun的缓存释放问题？

**Comment by xtaci** [comment]
在不丢包的环境，kcp肯定是比不上tcp的，因为多了不少开销。

**Comment by braveguywallce** [comment]
＠xtaci  明白了，谢谢！

**Comment by bettermanbao** [comment]
目前的kcptun已经很棒了，可以说已经做到让国内绝大多数的宽带访问国外绝大多数的VPS都能秒开1080p的视频了。再次感谢作者！

**Comment by xtaci** [comment]
我只不过是做了点翻译工作而已。 😄

**Comment by wxyzh** [comment]
kcptun参数-mode "normal" -mtu 1450 -nocomp 服务器监听udp80 其他参数默认。
iperf3的测试结果如下
$ iperf3 -c 127.0.0.1 -p 12345 -f M -n 100M -R -i 10
Connecting to host 127.0.0.1, port 12345
Reverse mode, remote host 127.0.0.1 is sending
[  4] local 127.0.0.1 port 57892 connected to 127.0.0.1 port 12345
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  20.0 MBytes  2.00 MBytes/sec                  
[  4]  10.00-20.00  sec  19.3 MBytes  1.93 MBytes/sec                  
[  4]  20.00-30.00  sec  22.3 MBytes  2.23 MBytes/sec                  
[  4]  30.00-40.00  sec  19.8 MBytes  1.97 MBytes/sec                  
[  4]  40.00-49.12  sec  18.7 MBytes  2.05 MBytes/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-49.12  sec   122 MBytes  2.49 MBytes/sec    1             sender
[  4]   0.00-49.12  sec   104 MBytes  2.11 MBytes/sec                  receiver

iperf Done.

**Comment by ragnaroks** [comment]
我这边测试的是搬瓦工/ramnode/hostus,都是ovz512款(注:搬瓦工cpu限制7%),流量计算均为双向计算.
仅使用"-mode default",其他参数默认,测速文件为我放aws的168M.BIN.

搬瓦工无丢包,下载均速3.66mbyte/s,消耗450.44M总流量,1:2.68的效率.

ramnode丢包30%+,均速不到1mbyte/s,消耗总流量1.8G,1:11的效率,惨不忍睹

hostus丢包10%+,均速不到1mbyte/s,消耗总流量841M,1:5的效率

总的来说,要想翻的爽,不丢包是关键.

**Comment by xtaci** [comment]
@ragnaroks #137

**Comment by ragnaroks** [comment]
@xtaci 

对比测试,
vpsA: do 512M,无丢包,kvm
vpsB: hostus 512M,无丢包,kvm
服务端参数: -mode normal -crypt none
客户端参数: -mode fast2 -crypt none
加速效果: youtube,240Mbyte(下载文件,非在线观看) A: 30Mbps    B: 8Mbps
流量消耗: A: 266Mbyte    B: 2.7Gbyte

结论:
1.不丢包是必须的
2.hostus的流量可能是假的(锐速稳定15倍发包,最开始以为是内核问题)

**Comment by ragnaroks** [comment]
又发现一个有趣的现象,部分下载工具(wget/curl)会导致数倍发包,100M的文件会消耗500M流量,但是用浏览器去直接缓冲这个文件,基本不到1:1.1的消耗.
![down_file](https://cloud.githubusercontent.com/assets/7598199/17879471/ccabf6ca-6924-11e6-8f8c-c7a9da328eea.png)

**Comment by wxyzh** [comment]
@ragnaroks 建议你测试下在不同带宽时的UDP丢包率，然后根据丢包率去调整-datashard 和 -parityshard 。我这边根据 #137 设置的，测试下载100MB的文件时服务端rx和tx的比例是1:1.2左右。
另外我的wnd设置的是512，因为我用iperf测试udp丢包率的时候，在20Mbps的带宽时丢包率激活为0。

**Comment by ragnaroks** [comment]
@wxyzh 
我这边100Mbps上下对等,测试即使是100Mbit的速率丢包率仅0.5%以下,-t 3600,
顺便说一下,被当作dos给封号了.

参数 "-r server:8000 -l :12948 -crypt none -mode manual -nodelay 0 -resend 0 -nc 1 -interval 20",入网108M/出网216M.

参数"-r server:8000 -l :12948 -crypt none -mode manual -nodelay 0 -resend 0 -nc 1 -interval 20 -rcvwnd 512",服务端设置"-sndwnd 512",入网108M/出网156M

参数"-r server:8000 -l :12948 -crypt none -mode manual -nodelay 0 -resend 0 -nc 1 -interval 20 -rcvwnd 256",服务端设置"-sndwnd 256",入网108M/出网142M

有此可见,目前好像512的窗口确实比较适合,不过我接的是电联双百,主网卡是联通,如果同时利用2张网卡的话,200Mbps可能1024更合适?
