### ISSUE TITLE
Problem about kcptun over ipv6

### ISSUE THREAD

**Issue by aod321** [xtaci/kcptun#127]
Sorry to bother you,but I got such problem when I try to use kcptun on my openwrt.
Could you tell me what should I do to fix it?Any help would be  appreciated!
error log:
root@OpenWrt:~# kcptun -l :12948 -r [2604:xx]:29900  -key test -mtu 1400 -sndwnd 256 -rcvwnd 2048 -mode fast2 -dscp 46
2016/07/13 10:09:49 version: SELFBUILD
2016/07/13 10:09:50 listening on: [::]:12948
2016/07/13 10:09:50 encryption: aes
2016/07/13 10:09:50 nodelay parameters: 1 20 2 1
2016/07/13 10:09:50 remote address: [2604:XX]:29900
2016/07/13 10:09:50 sndwnd: 256 rcvwnd: 2048
2016/07/13 10:09:50 compression: true
2016/07/13 10:09:50 mtu: 1400
2016/07/13 10:09:50 datashard: 10 parityshard: 3
2016/07/13 10:09:50 acknodelay: false
2016/07/13 10:09:50 dscp: 46
2016/07/13 10:09:50 conn: 1
2016/07/13 10:11:46 stream opened
panic: runtime error: slice bounds out of range

goroutine 11 [running]:
github.com/golang/snappy.encodeBlock(0x105ae014, 0x12ac8, 0x12ac8, 0x10582000, 0x21c, 0x10000, 0x18bfddac)
	/opt/mipsgo/src/github.com/golang/snappy/encode_other.go:175 +0x10c4
github.com/golang/snappy.Encode(0x105ae012, 0x12aca, 0x12aca, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/golang/snappy/encode.go:37 +0x370
github.com/golang/snappy.(*Writer).write(0x1053c6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/golang/snappy/encode.go:229 +0x280
github.com/golang/snappy.(*Writer).Flush(0x1053c6c0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/golang/snappy/encode.go:272 +0xb0
main.(*compStream).Write(0x1053a660, 0x10626000, 0x21c, 0x8000, 0x21c, 0x0, 0x0)
	/home/openwrt/kcptun/client/main.go:39 +0x88
bytes.(*Reader).WriteTo(0x10538e20, 0x771ca4a8, 0x1053a660, 0x771ca4c0, 0x10538e20, 0x0, 0x0)
	/opt/mipsgo/src/bytes/reader.go:131 +0x13c
io.Copy(0x771ca4a8, 0x1053a660, 0x771ca490, 0x10538e20, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:354 +0xac
github.com/hashicorp/yamux.(*Session).send(0x1053e000)
	/opt/mipsgo/src/github.com/hashicorp/yamux/session.go:387 +0x34c
created by github.com/hashicorp/yamux.newSession
	/opt/mipsgo/src/github.com/hashicorp/yamux/session.go:109 +0x5c0

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0x10532178, 0x72, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:84 +0x4c
net.(*pollDesc).WaitRead(0x10532178, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:89 +0x48
net.(*netFD).accept(0x10532140, 0x0, 0x771c8ad8, 0x1053ab70)
	/opt/mipsgo/src/net/fd_unix.go:419 +0x3dc
net.(*TCPListener).AcceptTCP(0x1051c7b8, 0x1051c3d8, 0x0, 0x0)
	/opt/mipsgo/src/net/tcpsock_posix.go:234 +0x58
main.func·004(0x105008c0, 0x0, 0x0)
	/home/openwrt/kcptun/client/main.go:267 +0x19ac
reflect.Value.call(0x1f1840, 0x288a88, 0x13, 0x23da48, 0x4, 0x10529b6c, 0x1, 0x1, 0x0, 0x0, ...)
	/opt/mipsgo/src/reflect/value.go:419 +0xff0
reflect.Value.Call(0x1f1840, 0x288a88, 0x13, 0x10529b6c, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/reflect/value.go:296 +0xb0
github.com/urfave/cli.HandleAction(0x1f1840, 0x288a88, 0x105008c0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/urfave/cli/app.go:485 +0x27c
github.com/urfave/cli.(*App).Run(0x1055c000, 0x1050a000, 0x11, 0x11, 0x0, 0x0)
	/opt/mipsgo/src/github.com/urfave/cli/app.go:244 +0x9e0
main.main()
	/home/openwrt/kcptun/client/main.go:283 +0xff4

goroutine 5 [select]:
github.com/xtaci/kcp-go.(*UDPSession).updateTask(0x1050a1b0)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:429 +0x2e0
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:104 +0x5fc

goroutine 6 [runnable]:
github.com/xtaci/kcp-go.(*UDPSession).outputTask(0x1050a1b0)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:336 +0x1804
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:105 +0x62c

goroutine 7 [select]:
github.com/xtaci/kcp-go.(*UDPSession).readLoop(0x1050a1b0)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:535 +0x578
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:107 +0x668

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0x105330b8, 0x72, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:84 +0x4c
net.(*pollDesc).WaitRead(0x105330b8, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:89 +0x48
net.(*netFD).readFrom(0x10533080, 0x10595800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x771c8ad8, 0x1053aad4)
	/opt/mipsgo/src/net/fd_unix.go:269 +0x418
net.(*UDPConn).ReadFromUDP(0x1051c3f0, 0x10595800, 0x800, 0x800, 0x4c, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/udpsock_posix.go:67 +0x108
github.com/xtaci/kcp-go.(*UDPSession).receiver(0x1050a1b0, 0x10532280)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:516 +0x108
created by github.com/xtaci/kcp-go.(*UDPSession).readLoop
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:532 +0x84

goroutine 10 [select]:
github.com/xtaci/kcp-go.(*UDPSession).Read(0x1050a1b0, 0x105d2000, 0x4, 0x12ace, 0xc, 0x0, 0x0)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:169 +0x854
io.ReadAtLeast(0x771ca1e0, 0x1050a1b0, 0x105d2000, 0x4, 0x12ace, 0x4, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:298 +0x118
io.ReadFull(0x771ca1e0, 0x1050a1b0, 0x105d2000, 0x4, 0x12ace, 0x10534800, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:316 +0x6c
github.com/golang/snappy.(*Reader).readFull(0x105322c0, 0x105d2000, 0x4, 0x12ace, 0x1, 0x1)
	/opt/mipsgo/src/github.com/golang/snappy/decode.go:108 +0x6c
github.com/golang/snappy.(*Reader).Read(0x105322c0, 0x10530000, 0x1000, 0x1000, 0xc, 0x0, 0x0)
	/opt/mipsgo/src/github.com/golang/snappy/decode.go:128 +0x1bc
main.(*compStream).Read(0x1053a660, 0x10530000, 0x1000, 0x1000, 0xc, 0x0, 0x0)
	/home/openwrt/kcptun/client/main.go:34 +0x5c
bufio.(*Reader).fill(0x1053c720)
	/opt/mipsgo/src/bufio/bufio.go:97 +0x1fc
bufio.(*Reader).Read(0x1053c720, 0x1053a130, 0xc, 0xc, 0x105387e0, 0x0, 0x0)
	/opt/mipsgo/src/bufio/bufio.go:174 +0x25c
io.ReadAtLeast(0x771ca2a8, 0x1053c720, 0x1053a130, 0xc, 0xc, 0xc, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:298 +0x118
io.ReadFull(0x771ca2a8, 0x1053c720, 0x1053a130, 0xc, 0xc, 0xc, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:316 +0x6c
github.com/hashicorp/yamux.(*Session).recvLoop(0x1053e000, 0x0, 0x0)
	/opt/mipsgo/src/github.com/hashicorp/yamux/session.go:418 +0x14c
github.com/hashicorp/yamux.(*Session).recv(0x1053e000)
	/opt/mipsgo/src/github.com/hashicorp/yamux/session.go:406 +0x38
created by github.com/hashicorp/yamux.newSession
	/opt/mipsgo/src/github.com/hashicorp/yamux/session.go:108 +0x594

goroutine 12 [select]:
github.com/hashicorp/yamux.(*Session).keepalive(0x1053e000)
	/opt/mipsgo/src/github.com/hashicorp/yamux/session.go:302 +0x23c
created by github.com/hashicorp/yamux.newSession
	/opt/mipsgo/src/github.com/hashicorp/yamux/session.go:111 +0x5fc

goroutine 15 [select]:
main.handleClient(0x771ca2f8, 0x1051c3d8, 0x771ca318, 0x10536080)
	/home/openwrt/kcptun/client/main.go:75 +0x65c
created by main.func·004
	/home/openwrt/kcptun/client/main.go:278 +0x1cdc

goroutine 16 [select]:
github.com/hashicorp/yamux.(*Stream).Read(0x10536080, 0x1061e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/hashicorp/yamux/stream.go:125 +0x458
io.Copy(0x771ca398, 0x1051c448, 0x771ca350, 0x10536080, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:362 +0x208
net.genericReadFrom(0x771ca338, 0x1051c3d8, 0x771ca350, 0x10536080, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/net.go:404 +0xb4
net.(*TCPConn).ReadFrom(0x1051c3d8, 0x771ca350, 0x10536080, 0x771ca380, 0x1051c3d8, 0x0, 0x0)
	/opt/mipsgo/src/net/tcpsock_posix.go:72 +0x118
io.Copy(0x771ca338, 0x1051c3d8, 0x771ca350, 0x10536080, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:358 +0x154
main.func·001()
	/home/openwrt/kcptun/client/main.go:64 +0xd8
created by main.handleClient
	/home/openwrt/kcptun/client/main.go:66 +0x448

goroutine 17 [select]:
github.com/hashicorp/yamux.(*Session).waitForSendErr(0x1053e000, 0x1053ab10, 0xc, 0xc, 0x771ca490, 0x10538e20, 0x10616300, 0x0, 0x0)
	/opt/mipsgo/src/github.com/hashicorp/yamux/session.go:338 +0x330
github.com/hashicorp/yamux.(*Stream).write(0x10536080, 0x10626000, 0x21c, 0x8000, 0x61248, 0x0, 0x0)
	/opt/mipsgo/src/github.com/hashicorp/yamux/stream.go:183 +0x594
github.com/hashicorp/yamux.(*Stream).Write(0x10536080, 0x10626000, 0x21c, 0x8000, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/hashicorp/yamux/stream.go:139 +0x158
io.Copy(0x771ca430, 0x10536080, 0x771ca448, 0x1051c3d8, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:364 +0x288
main.func·002()
	/home/openwrt/kcptun/client/main.go:70 +0xd8
created by main.handleClient
	/home/openwrt/kcptun/client/main.go:72 +0x578

**Comment by xtaci** [comment]
I don't have guarantee stability on SELFBUILD version, you can try offical releases.

**Comment by xtaci** [comment]
try add -nocomp to both sides

**Comment by aod321** [comment]
'try add -nocomp to both sides'
I do just as you say,and it works now!THX😊
