### ISSUE TITLE
not work  连不上

### ISSUE THREAD

**Issue by kenneth104** [xtaci/kcptun#128]
截图
Screenshot
[https://public.lightpic.info/image/38B3_57B229940.jpg](url)
![1](https://cloud.githubusercontent.com/assets/15079279/17679087/78207a62-636c-11e6-8ed7-75e50402810f.png)

服务器正常监听kcptun端口，防火墙没有过滤，client端加了`-sndwnd 1024`后参数一致

server will listen the kcptun port
iptables allow all tcp&udp(with out 3306)
client use `-sndwnd 1024` it's looklike the server command

Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Are you using the **latest release**?
yes

2. Which **OS** do you use?
win10

3. Which end for this issue related to, **client or server**?
client

4. Are you using the **same version** for both client & server
yes

5. Did you correctly set the ***-target value, -t value	target server address (default: "127.0.0.1:12948")*** on the server side?
yes,use  `-t "127.0.0.1:1025" -l "127.0.0.1:38399"`

6. Can ```telnet target port``` successful?
I can't  `telnet: Unable to connect to remote host: Connection refused`

7. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
yes,with out any command

8. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
yes

**Comment by kenneth104** [comment]
欧漏
telenet失败

问题在哪？？

**Comment by chestnutprog** [comment]
你防火墙开了么→_→
