### ISSUE TITLE
Stability issues on Android clients

### ISSUE THREAD

**Issue by Mygod** [xtaci/kcptun#129]
Original issue: https://github.com/shadowsocks/shadowsocks-android/issues/801

**Comment by triaqu** [comment]
在网络切换时也容易出现SSL无法连接问题，需要重置才能使用。

**Comment by xtaci** [comment]
you are asking questions for another repo.

**Comment by Mygod** [comment]
So post this on kcp-go?

**Comment by xtaci** [comment]
ask ss

**Comment by Mygod** [comment]
> Closing as an upstream issue.
