### ISSUE TITLE
更新到最新版，还有出现keepalive failed: i/o deadline reached报错

### ISSUE THREAD

**Issue by fydexx** [xtaci/kcptun#131]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Are you using the **latest release**?  V20160816
2. Which **OS** do you use?                server-debian  client-windows 7
3. Which end for this issue related to, **client or server**?  client-windows 7
4. Are you using the **same version** for both client & server   都是 V20160816
5. Did you correctly set the ***-target value, -t value	target server address (default: "127.0.0.1:12948")*** on the server side?

server:
./server_linux_386 -l :21100 -t 127.0.0.1:449 -key xxx -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2 > kcptun_main.log 2>&1 &

client:
client_windows_amd64 -l :449 -r x:x:x:x:21100 -key xxx -mtu 1400 -sndwnd 128 -rcvwnd 1024 -mode fast2 -dscp 46

6. Can ```telnet target port``` successful? 
7. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.

server:
./server_linux_386 -l :21100 -t 127.0.0.1:449 -key xxx -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2 > kcptun_main.log 2>&1 &

client:
client_windows_amd64 -l :449 -r x:x:x:x:21100 -key xxx -mtu 1400 -sndwnd 128 -rcvwnd 1024 -mode fast2 -dscp 46

8. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)

故障现象：使用一段时间后，突然无法翻墙，出现以下错误。
过段时间又可以了。

2016/08/16 04:03:44 [ERR] yamux: keepalive failed: i/o deadline reached
2016/08/16 04:03:44 [ERR] yamux: Failed to read header: broken pipe
2016/08/16 04:03:44 keepalive timeout
2016/08/16 04:03:44 stream closed
2016/08/16 04:24:12 remote address: 12x.x7.2x4.1xx:58737
2016/08/16 04:25:10 stream opened
2016/08/16 04:26:42 [ERR] yamux: keepalive failed: i/o deadline reached
2016/08/16 04:26:42 [ERR] yamux: Failed to read header: broken pipe
2016/08/16 04:26:42 keepalive timeout

2016/08/16 04:59:14 stream closed
2016/08/16 04:59:17 stream closed
2016/08/16 04:59:20 stream opened
2016/08/16 04:59:21 stream opened
2016/08/16 04:59:21 stream opened
2016/08/16 04:59:21 stream opened
2016/08/16 04:59:31 stream closed
2016/08/16 04:59:31 stream closed
2016/08/16 04:59:31 stream closed
2016/08/16 04:59:34 stream closed

**Comment by fydexx** [comment]
又出新版本？效率真高。感谢！

先来更新......

**Comment by fydexx** [comment]
更新后，还是有问题

2016/08/16 05:13:42 [ERR] yamux: keepalive failed: i/o deadline reached
2016/08/16 05:13:42 [ERR] yamux: Failed to read header: broken pipe
2016/08/16 05:13:42 keepalive timeout
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed
2016/08/16 05:13:42 stream closed

**Comment by xtaci** [comment]
没有其他办法，换端口，降窗口。

**Comment by wxyzh** [comment]
这个真的没办法，我跑了一天，客户端大概出现了44次broken pipe。实际上应该更多。
我现在是用的haproxy中转的SS，写了个ACL。用脚本去判断KCPtun的连通状态，正常状态是通过kcptun连接ss，如果kcptun不通，就让haproxy直接连接vps
