### ISSUE TITLE
Header signing option

### ISSUE THREAD

**Issue by KarlM256** [xtaci/kcptun#132]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Are you using the **same version** for both client & server
5. Did you correctly set the ***-target value, -t value	target server address (default: "127.0.0.1:12948")*** on the server side?
6. Can ```telnet target port``` successful?
7. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
8. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)

**Comment by KarlM256** [comment]
Hi...

I use kcptun with shadowsocks. I would like to protect the UDP packets from insertion of malicious packets in the communications. Is there a way to protect the packet headers and prevent inserting packets into the "stream". One way would to do this would be to sign the packet headers so that false packets could be thrown out.

Is there a way to protect against malicious packets, or would you consider adding a new crypt option to protect the headers?

Thanks,

...Karl

**Comment by xtaci** [comment]
It's already encrypted if you add -crypt options.

**Comment by KarlM256** [comment]
Hi...

I looked up what the other methods for crypt do. What does XOR do? Is there anything dynamic to the process? How much security does it add?

Thanks,

...Karl

**Comment by xtaci** [comment]
<img width="682" alt="frame" src="https://cloud.githubusercontent.com/assets/2346725/17726165/c53bd59a-6483-11e6-9132-9e4ca3d3b44f.png">
https://github.com/xtaci/kcp-go/blob/master/crypt.go#L126
