### ISSUE TITLE
server hanging on win 10 pro 64

### ISSUE THREAD

**Issue by KarlM256** [xtaci/kcptun#133]
Hi...

I have noticed while using kcptun with shadowsocks-android, that sometimes the connection hangs AND restarting the connection from the client side will not fix the problem. If I then restart the server, it fixes the problem.

Is this a known problem?

Thanks,

...Karl

**Comment by xtaci** [comment]
you are asking for another repository.

**Comment by KarlM256** [comment]
Hi...

Sorry if I was not clear. The server is running on Windows 10 pro 64. I believe that sometimes the kcptun server hangs, because restarting the client does not restore operation, so I assume that the server has hung. Restarting the server fixes the problem.

...Karl
