### ISSUE TITLE
是否能增加自动重连或者热重启的功能。

### ISSUE THREAD

**Issue by DukeChina** [xtaci/kcptun#134]
目前版本一定要server先开启，client再开启才能正确连接，如果server restart，则client需要跟server一样重启才能用（只有一次认证？），获取更换网络后也会丢失连接（现在server记录当前client状态？），是否可以支持自动重连，在server没响应的情况下，client主动请求认证，体验类似SS？可以说热重启么？

**Comment by xtaci** [comment]
你多等一下，肯定会自动重连的。

**Comment by DukeChina** [comment]
and 现在一个端口只支持一个设备连接么？我这边好像用手机连接了，电脑就连不上了

**Comment by xtaci** [comment]
怎么可能
