### ISSUE TITLE
Commit 0036171 : resend maybe too high

### ISSUE THREAD

**Issue by kmahyyg** [xtaci/kcptun#135]
I donnot want to update to the latest version,  I thought resend 3x is too high.If like this,why shouldn't I use netspeeder?

You know , some Service Provider didn't allow you to use resend programs.

So,Could you please add an argument on both side of server and client to allow us set the value of resend?

**Comment by xtaci** [comment]
you misunderstood that, it has nothing to do with resend 3x times.
