### ISSUE TITLE
为什么用了kcptun速度反而不如直连了？

### ISSUE THREAD

**Issue by kmahyyg** [xtaci/kcptun#136]
I use the 20160811 version on both side (20160816 is also not worked!).

Server&Client :  

    --crypt none --mode fast --mtu 1200 --nocomp --dscp 46 --rcvwnd 64 --sndwnd 64

(listened on port: ss port +20)(redirect success)(iptables set correct)

Debian 8 x64 hosted on bandwagonhost los angeles

Client: WinXP SP3 or Win8.1
Network: Yunnan Telecom Wi-Fi in my home (10Mbps)

Speed Tested using fast.com

When use KCPTUN , downloading something from npr with Chrome 52 always like this:
1.4 mb/s ... 0 byte/s ... 0 byte/s
when directly connect to ss :  250 kb/s

Test Speed using fast.com:
(Using --datashard 10   --parityshard 0 before)  (KCPTUNed/Direct) 1.4Mbps 1Mbps
(now using the default value) 350kbps 1.4Mbps

Why?

**Comment by xtaci** [comment]
It's the worst case I ever seen.

slowest access network + worst oversea bandwidth of ISP + slowest VPS.

I cannot help you .

**Comment by wxyzh** [comment]
先要明确kcptun的使用范围

xtaci <notifications@github.com>于2016年8月18日周四 15:22写道：

**Comment by kmahyyg** [comment]
but i can using direct connection to my vps , i used netspeeder before,it's more stable.

also in the same network in my house, speed of connecting to japan GMO vps  is  8mbps+(speedtest.net)

BTW,  @xtaci   Is there anything wrong with my arguments?or can be optimized?

**Comment by kmahyyg** [comment]
Still V160811
But Changed to:

    --rcvwnd 128 --sndwnd 128

Test reported more fast than ever before(5.+ mbps,the same network,fast.com)

But There's something wrong in the cmd i have never seen before:

> 2016/08/19 08:09:04 sndwnd: 128 rcvwnd: 128
2016/08/19 08:09:04 compression: false
2016/08/19 08:09:04 mtu: 1200
2016/08/19 08:09:04 datashard: 10 parityshard: 3
2016/08/19 08:09:04 acknodelay: false
2016/08/19 08:09:04 dscp: 46
2016/08/19 08:09:04 sockbuf: 4194304
2016/08/19 08:09:04 keepalive: 10
2016/08/19 08:09:04 conn: 1
2016/08/19 08:13:36 [ERR] yamux: keepalive failed: i/o deadline reached
2016/08/19 08:13:36 [ERR] yamux: Failed to read header: broken pipe
2016/08/19 08:23:56 session shutdown

**Comment by xtaci** [comment]
#137 discuss here
