### ISSUE TITLE
同样的设置,0816的版本比0725的版本速度慢很多

### ISSUE THREAD

**Issue by alexliyu** [xtaci/kcptun#138]
服务器是linux的, 客户端也是linxu的.
参数都是--crypt none --mtu 1350 -sndwnd 2048 -rcvwnd 2048 --mode fast3 --dscp 46 
在服务器与客户端都是0725版本, youtube差不多1.2 MB, 速度很稳定,差不多就在700-1.2MB之间浮动.
但是换成最新的0816版本, 那么速度就在0-500KB之间浮动, 是新版本修改了什么隐藏参数了么?

**Comment by xtaci** [comment]
只有一个微小调整，不会导致这么大的变化，测试过的。

另外，#137 可以参考。

**Comment by alexliyu** [comment]
策略1： 通过超时重传＋快速重传，响应速度优先（最大化响应时间）：
-mode manual -nodelay 1 -resend 2 -nc 1 -interval 20

策略2： 仅仅通过超时重传, 带宽效率优先（有效载比优先)。
-mode manual -nodelay 1 -resend 0 -nc 1 -interval 40 或
-mode manual -nodelay 0 -resend 0 -nc 1 -interval 20

策略3: 尽可能通过FEC纠删，最大化传输速度：
-mode manual -nodelay 0 -resend 0 -nc 1 -interval 40 -datashard 5 -parityshard 2

三种模式都尝试了,没有一种模式速度能和0725版本一样的.

看youtube 720p的0725版本3000kpbs以上,这个最新版本就很地了.

-mode manual -nodelay 1 -resend 0 -nc 1 -interval 40
这个速度快点,但是还是没有0725版本速度快.

**Comment by alexliyu** [comment]
主要我发现0816版本速度波动很厉害, 经常个位数

**Comment by xtaci** [comment]
-mode manual -nodelay 1 -resend 1 -nc 1 -interval 20
试试这个

**Comment by alexliyu** [comment]
alex@alex-MS-7640:~/shadow/new_kcp$ ./client_linux_386 -l 127.0.0.1:1090 -r x.x.x.169:21 --crypt none --mtu 1350 -sndwnd 1024 -rcvwnd 1024 --dscp 46  --sockbuf 31457280 --mode manual -nodelay 1 -resend 1 -nc 1 -interval 20
2016/08/18 22:16:39 version: 20160816
2016/08/18 22:16:39 listening on: 127.0.0.1:1090
2016/08/18 22:16:39 encryption: none
2016/08/18 22:16:39 nodelay parameters: 1 20 1 1
2016/08/18 22:16:39 remote address: 61.221.75.169:21
2016/08/18 22:16:39 sndwnd: 1024 rcvwnd: 1024
2016/08/18 22:16:39 compression: true
2016/08/18 22:16:39 mtu: 1350
2016/08/18 22:16:39 datashard: 10 parityshard: 3
2016/08/18 22:16:39 acknodelay: false
2016/08/18 22:16:39 dscp: 46
2016/08/18 22:16:39 sockbuf: 31457280
2016/08/18 22:16:39 keepalive: 10
2016/08/18 22:16:39 conn: 1

更糟, 不超过300K

**Comment by xtaci** [comment]
我check一下。

**Comment by alexliyu** [comment]
辛苦了, 按照你的测试数据,应该0816版本更高,但是实际上我不管怎么更换参数,都是0725速度更高.

**Comment by xtaci** [comment]
是的，我也观察到了，正在check

**Comment by xtaci** [comment]
初步估计是因为重传少了（载比提高），导致前向纠错数据包不够，需要时间找出最佳方案。

**Comment by alexliyu** [comment]
加油,大神

**Comment by xtaci** [comment]
@alexliyu 暂时回滚了今天对fastack的改动，貌似是这个引起的重传不足，FEC包不足。重新下载试一下。

**Comment by alexliyu** [comment]
我用的是release的0816, 编译好的.所以应该不是今天的改动引起的.

**Comment by xtaci** [comment]
我刚上传了，覆盖了。
