### ISSUE TITLE
请支持一个 config.json 这样的配置

### ISSUE THREAD

**Issue by jannson** [xtaci/kcptun#14]
在以往的观察当中，更多用户喜欢 config.json 的配置。类似： ./kcp_server -c config.json

这样的好处是文件容易传输，密码什么的在里面。启动也方便。用 cli 常常忘记上次写的密码是什么，参数有哪些。

**Comment by xtaci** [comment]
有道理，考虑怎么加

**Comment by xtaci** [comment]
@jannson 如果有gui，最好通过gui解决参数和保存问题，做 json解析比较麻烦，需要先定义结构体，然后Unmarshal，代码很冗余。
另一种方式是， 通过环境变量 ，例如  EnvVar: "KCPTUN_KEY", 所有的参数都可以支持从环境变量中读取，如果有一个简单的启动脚本，或者最好gui，也能很方便的解决。

**Comment by jannson** [comment]
OK。

我知道怎么弄了~
一键脚本里，提示用户配置完服务器之后，在打印出来命令提示用户如何再 windows 里面运行吧。

然后路由器固件我弄一个 gui 来配置客户端。

**Comment by xtaci** [comment]
嗯，ss易用性确实做的好，不过我还是更想保持项目代码的清晰度。尽量用整合的方案来提供易用性吧。
@jannson

**Comment by jannson** [comment]
今天纠结了半天, 我决定还是改代码来实现 config.json 的配置.
很多真实的使用环境是, 多人合买服务器, 但希望是独立密码独立端口的. 这样脚本就需要加很多个 kcp 进程才能达到效果.
Golang 的话我还不如直接在服务器端实现一个进程支持多个独立的端口与密码得了.  对服务器的资源要求低, 一个进程只有一个垃圾回收器.

虽然如此, 我修改的版本还是要兼容原来的配置, 并跟用户说明,此版本仅仅是对配置作了改变,其它的还是 kcptun 原来的功能与性能.

**Comment by jannson** [comment]
这样处理的话代码肯定是无法干净了,因为现在的 server 与 client 代码是完全独立的. 但是加了配置,肯定应该是有一个公共的配置模块.

**Comment by xtaci** [comment]
嗯，支持！

**Comment by oskiller** [comment]
阳光同学，加你qq没回应啊 那个gonet我们打算用哈 咨询一下 有别的联系方式没有 我们也在成都
