### ISSUE TITLE
求助，好像不怎么稳定不知道是不是我设置的问题。。

### ISSUE THREAD

**Issue by lbbboy** [xtaci/kcptun#141]
[ERR] yamux: keepalive failed: connection write timeout
2016/08/13 06:47:43 [ERR] yamux: Failed to write header: broken pipe
2016/08/13 06:47:43 stream closed
2016/08/13 06:47:43 keepalive timeout
2016/08/13 06:47:43 [ERR] yamux: Failed to read header: broken pipe

./server_linux_386 -t 127.0.0.1:443 -mode fast2 -mtu 1464 -sndwnd 163 -rcvwnd 163

服务端和客户端都是最新版。

**Comment by dolphinpaopao** [comment]
-l :8989

**Comment by xtaci** [comment]
#137
