### ISSUE TITLE
Please add chacha20 as crypto method

### ISSUE THREAD

**Issue by netroby** [xtaci/kcptun#142]
Please add chacha20 as crypto method

**Comment by xtaci** [comment]
chacha20 is stream cipher, not block cipher. It's not suitable for packet encryption.

**Comment by testcaoy7** [comment]
@xtaci You can add Camellia and ARIA as well as GOST cipher family. Camellia is Japan equivalent to AES. ARIA is Korea equivalent and the GOST is Russia equivalent.

**Comment by xtaci** [comment]
@testcaoy7 do they have stable libraries?

**Comment by testcaoy7** [comment]
@xtaci 
ARIA: https://github.com/dgryski/go-krcrypt
Camellia: https://github.com/dgryski/go-camellia
GOST: https://github.com/rmuch/gost

No way to make sure these code is correct and secure. 
If you can use C++ in the programming, please use Botan crypto library.

**Comment by xtaci** [comment]
oops... no star at all. I cannot use that.

**Comment by testcaoy7** [comment]
@xtaci There is no need to add lot of ciphers any way.  The goal of kcptun is being fast, which means TEA is the best.

**Comment by xtaci** [comment]
AES-128 is the fastest for  Intel's CPU.

**Comment by lunaset** [comment]
Why not support twofish as alternative of aes? Look like it would serve performance-optimization better.

http://csrc.nist.gov/archive/aes/round1/conf2/Schneier.pdf

**Comment by xtaci** [comment]
twofish can be added, it's in the standard library.
AES benefits from CPU's hardware accelerated instructions,  it's definitely the fastest for i386 & amd64.

**Comment by lunaset** [comment]
Got it.

If AES-NI's widely supported,AES would be best definitely.

**Comment by testcaoy7** [comment]
@xtaci Sadly, my phone does not support hardware AES. This is the reason I chose TEA. I think kcptun does not need ultimate privacy protection and TEA is adequate enough. After all, speed comes first. 

PS: Twofish is a little slow.

**Comment by xtaci** [comment]
@testcaoy7 encryption is VERY important to kcptun's HEADER SECURITY. TEA is a fast and security algorithm only if you specify a STRONG-PASSWORD, like 16Bytes.

**Comment by xtaci** [comment]
```
BenchmarkAES128-4      	  200000	     11394 ns/op
BenchmarkAES192-4      	  100000	     12055 ns/op
BenchmarkAES256-4      	  100000	     13741 ns/op
BenchmarkTEA-4         	   50000	     26717 ns/op
BenchmarkSimpleXOR-4   	 3000000	       438 ns/op
BenchmarkBlowfish-4    	   30000	     47789 ns/op
BenchmarkNone-4        	20000000	       105 ns/op
BenchmarkCast5-4       	   20000	     60071 ns/op
BenchmarkTripleDES-4   	    2000	    870758 ns/op
BenchmarkTwofish-4     	   20000	     66515 ns/op
PASS
ok  	github.com/xtaci/kcp-go	36.064s
```

**Comment by lunaset** [comment]
@xtaci Thanks for your report :-)

**Comment by xtaci** [comment]
@netroby I found that salsa20 can be added to kcptun. Salsa20 has a very special architecture, which has no internal state.

**Comment by xtaci** [comment]
```
BenchmarkAES128-4      	  200000	     11021 ns/op
BenchmarkAES192-4      	  200000	     12697 ns/op
BenchmarkAES256-4      	  100000	     13877 ns/op
BenchmarkTEA-4         	   50000	     28570 ns/op
BenchmarkSimpleXOR-4   	 3000000	       484 ns/op
BenchmarkBlowfish-4    	   30000	     49196 ns/op
BenchmarkNone-4        	20000000	       108 ns/op
BenchmarkCast5-4       	   20000	     62520 ns/op
BenchmarkTripleDES-4   	    2000	    868267 ns/op
BenchmarkTwofish-4     	   20000	     67651 ns/op
BenchmarkXTEA-4        	   20000	     79698 ns/op
BenchmarkSalsa20-4     	  300000	      5137 ns/op
PASS
```

salsa20 is really fast!

**Comment by lunaset** [comment]
Isn't salsa20 a stream cipher,which be considered inappropriate for KCP causes of security flaw?

**Comment by xtaci** [comment]
salsa20 is not a traditional rc4 like pseudo-random sequence generator which outputs xor stream. 
it's more like block ciphers.

**Comment by lunaset** [comment]
Cool ! It's high time to learn more about cryptography.

**Comment by xtaci** [comment]
a new release has been published, you can test for yourself.

**Comment by testcaoy7** [comment]
@xtaci 
I find a very good golang crypto library here:
https://github.com/dedis/crypto

And it contains a very interesting cipher called NORX.

Detail of NORX can be find here:
https://norx.io/

**Comment by amosnet** [comment]
@xtaci 
according to my experience from hours ago I upgraded to "release 0820", so far I could tell and confirm that Salsa20 does reduce CPU% on raspberry pi 3, perhaps all devices based on ARM platform.

Thank you.

**Comment by xtaci** [comment]
@testcaoy7 no, I won't add that thing. only extraordinary algorithms & classic algorithms will be consider.

**Comment by testcaoy7** [comment]
@xtaci I understand. NORX is highly experimental anyway. Salsa20 works like a charm. Thank you for your hard work.

**Comment by netroby** [comment]
Leave this closed.

**Comment by testcaoy7** [comment]
@xtaci I wonder if the encryption will apply to the payload. Most folks use kcptun with shadowsocks (or ssh) and shadowsocks (or ssh) has its own encryption. I think it is  pointless to encrypt data twice. If kcptun do encrypt its payload, I wonder if you can add a flag to the kcptun which will allow user to encrypt kcp protocol and leave payload untouched.

**Comment by xtaci** [comment]
It's impossible to diff kcp protocol from payload at session level.  at the moment, encryption twice is a must if you need header security.

**Comment by daiaji** [comment]
所以salsa20比chacha20更适合kcp？

**Comment by salesiss** [comment]
CONGRATULATIONS; a compliment. I got used to some intel and texas instruments work on mux, their high-end stuff at that time. You, xtaci re-discovered the /software/ mux (ours was a hardware mux), this thing (mutiplexing) works really wonders. Go ahead and i'm not begin neither jealous nor worried, just amused. We'll try a better assessment on your code, later and if possible, but so far, you made a difference. Good.
