### ISSUE TITLE
8.20日版本好像比较稳定，没有出现断流情况。

### ISSUE THREAD

**Issue by lbbboy** [xtaci/kcptun#145]
2016/08/20 09:28:34 version: 20160820
2016/08/20 09:28:34 listening on  [::]:29900
2016/08/20 09:28:34 encryption: aes
2016/08/20 09:28:34 nodelay parameters: 1 20 2 1
2016/08/20 09:28:34 sndwnd: 163 rcvwnd: 163
2016/08/20 09:28:34 compression: true
2016/08/20 09:28:34 mtu: 1400
2016/08/20 09:28:34 datashard: 10 parityshard: 3
2016/08/20 09:28:34 acknodelay: false
2016/08/20 09:28:34 dscp: 46
2016/08/20 09:28:34 sockbuf: 4194304
2016/08/20 09:28:34 keepalive: 10

2016/08/20 09:29:18 stream opened
2016/08/20 09:29:19 stream opened
2016/08/20 09:29:19 stream opened
2016/08/20 09:29:20 stream closed
2016/08/20 09:29:20 stream opened
2016/08/20 09:29:20 stream opened
2016/08/20 09:29:20 stream opened
2016/08/20 09:29:20 stream opened
2016/08/20 09:29:20 stream closed
2016/08/20 09:29:20 stream opened
2016/08/20 09:29:20 stream closed
2016/08/20 09:29:20 stream opened
2016/08/20 09:29:21 stream closed
2016/08/20 09:29:21 stream closed
2016/08/20 09:29:21 stream opened
2016/08/20 09:29:21 stream opened
2016/08/20 09:29:21 stream closed
2016/08/20 09:29:21 stream opened
2016/08/20 09:29:22 stream closed
2016/08/20 09:29:22 stream opened
2016/08/20 09:29:22 stream opened
2016/08/20 09:29:23 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:24 stream opened
2016/08/20 09:29:28 stream opened
2016/08/20 09:29:30 stream opened
2016/08/20 09:29:30 stream opened
2016/08/20 09:29:33 stream closed
2016/08/20 09:29:33 stream closed
2016/08/20 09:29:33 stream closed
2016/08/20 09:29:33 stream opened
2016/08/20 09:29:33 stream opened
2016/08/20 09:29:33 stream opened
2016/08/20 09:29:33 stream opened
2016/08/20 09:29:33 stream opened
2016/08/20 09:29:33 stream opened
2016/08/20 09:29:34 stream opened
2016/08/20 09:29:35 stream opened
2016/08/20 09:29:35 stream closed
2016/08/20 09:29:37 stream opened
2016/08/20 09:29:46 stream closed
2016/08/20 09:29:50 stream opened
2016/08/20 09:29:52 stream closed
2016/08/20 09:29:52 stream closed
2016/08/20 09:29:52 stream opened
2016/08/20 09:30:28 stream opened
2016/08/20 09:31:01 stream closed
2016/08/20 09:31:02 stream closed
2016/08/20 09:31:24 stream opened
2016/08/20 09:33:21 stream closed
2016/08/20 09:33:32 stream closed
2016/08/20 09:33:34 stream closed
2016/08/20 09:33:34 stream closed
2016/08/20 09:33:34 stream closed
2016/08/20 09:33:34 stream closed
2016/08/20 09:33:34 stream closed
2016/08/20 09:33:34 stream closed
2016/08/20 09:33:34 stream closed
2016/08/20 09:33:35 stream closed
2016/08/20 09:33:35 stream closed
2016/08/20 09:33:36 stream closed
2016/08/20 09:33:43 stream closed
2016/08/20 09:33:44 stream closed
2016/08/20 09:33:44 stream closed
2016/08/20 09:33:44 stream closed
2016/08/20 09:33:44 stream closed
2016/08/20 09:33:44 stream closed
2016/08/20 09:33:51 stream closed
2016/08/20 09:34:34 stream closed
2016/08/20 09:34:59 stream closed
2016/08/20 09:35:01 stream closed
2016/08/20 09:35:01 stream opened
2016/08/20 09:35:26 stream closed
2016/08/20 09:35:32 stream closed
2016/08/20 09:35:41 stream opened
2016/08/20 09:35:42 stream opened
2016/08/20 09:35:42 stream opened
2016/08/20 09:35:42 stream opened
2016/08/20 09:35:42 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:43 stream opened
2016/08/20 09:35:44 stream opened
2016/08/20 09:35:46 stream opened
2016/08/20 09:35:46 stream opened
2016/08/20 09:35:46 stream opened
2016/08/20 09:35:46 stream opened
2016/08/20 09:35:46 stream opened
2016/08/20 09:35:46 stream opened
2016/08/20 09:35:51 stream opened
2016/08/20 09:35:58 stream opened
2016/08/20 09:36:05 stream opened
2016/08/20 09:36:12 stream closed
2016/08/20 09:36:12 stream closed
2016/08/20 09:36:19 stream closed
2016/08/20 09:36:26 stream opened
2016/08/20 09:36:33 stream closed
2016/08/20 09:37:34 stream closed
2016/08/20 09:37:40 stream opened
2016/08/20 09:37:52 stream closed
2016/08/20 09:38:23 stream opened
2016/08/20 09:38:42 stream closed
2016/08/20 09:38:44 stream opened
2016/08/20 09:38:58 stream closed
2016/08/20 09:39:30 stream opened
2016/08/20 09:39:38 stream opened
2016/08/20 09:39:42 stream closed
2016/08/20 09:39:43 stream closed
2016/08/20 09:39:43 stream closed
2016/08/20 09:39:43 stream closed
2016/08/20 09:39:43 stream closed
2016/08/20 09:39:46 stream closed
2016/08/20 09:39:48 stream closed
2016/08/20 09:39:52 stream closed
2016/08/20 09:39:52 stream closed
2016/08/20 09:39:55 stream closed
2016/08/20 09:39:55 stream closed
2016/08/20 09:39:55 stream closed
2016/08/20 09:39:55 stream closed
2016/08/20 09:39:56 stream closed
2016/08/20 09:39:56 stream closed
2016/08/20 09:39:59 stream closed
2016/08/20 09:40:28 stream closed
2016/08/20 09:40:38 stream closed
2016/08/20 09:40:58 stream closed
2016/08/20 09:40:58 stream closed
2016/08/20 09:40:58 stream closed
2016/08/20 09:41:06 stream opened
2016/08/20 09:41:06 stream opened
2016/08/20 09:41:09 stream opened
2016/08/20 09:41:09 stream opened
2016/08/20 09:41:09 stream opened
2016/08/20 09:41:09 stream opened
2016/08/20 09:41:09 stream opened
2016/08/20 09:41:09 stream opened
2016/08/20 09:41:09 stream opened
2016/08/20 09:41:09 stream opened
2016/08/20 09:41:11 stream opened
2016/08/20 09:41:11 stream opened
2016/08/20 09:41:11 stream opened
2016/08/20 09:41:11 stream opened
2016/08/20 09:41:12 stream closed
2016/08/20 09:41:13 stream opened
2016/08/20 09:41:13 stream opened
2016/08/20 09:41:15 stream opened
2016/08/20 09:41:15 stream opened
2016/08/20 09:41:15 stream opened
2016/08/20 09:41:15 stream opened
2016/08/20 09:41:15 stream opened
2016/08/20 09:41:16 stream opened
2016/08/20 09:41:26 stream opened
2016/08/20 09:41:31 stream opened
2016/08/20 09:41:34 stream opened
2016/08/20 09:41:34 stream closed
2016/08/20 09:41:35 stream opened
2016/08/20 09:41:35 stream opened
2016/08/20 09:41:35 stream opened
2016/08/20 09:41:35 stream opened
2016/08/20 09:41:39 stream opened
2016/08/20 09:41:42 stream closed
2016/08/20 09:41:47 stream opened
2016/08/20 09:41:47 stream opened
2016/08/20 09:41:51 stream closed
2016/08/20 09:41:55 stream closed
2016/08/20 09:41:56 stream opened
2016/08/20 09:41:59 stream closed
2016/08/20 09:41:59 stream closed
2016/08/20 09:42:35 stream closed
2016/08/20 09:42:42 stream closed
[root@~]# 2016/08/20 09:43:42 stream closed  挂了。。
2016/08/20 09:45:10 stream closed
2016/08/20 09:45:10 stream closed
2016/08/20 09:45:12 stream closed
2016/08/20 09:45:12 stream closed
2016/08/20 09:45:12 stream closed
2016/08/20 09:45:12 stream closed
2016/08/20 09:45:12 stream closed
2016/08/20 09:45:12 stream closed
2016/08/20 09:45:14 stream closed
2016/08/20 09:45:18 stream closed
2016/08/20 09:45:18 stream closed
2016/08/20 09:45:20 stream closed
2016/08/20 09:45:22 stream closed
2016/08/20 09:45:22 stream closed
2016/08/20 09:45:23 stream closed
2016/08/20 09:45:23 stream closed
2016/08/20 09:45:23 stream closed
2016/08/20 09:45:23 stream closed
2016/08/20 09:45:28 stream closed

**Comment by xtaci** [comment]
https://github.com/hashicorp/yamux/pull/39
