### ISSUE TITLE
salsa20和libsodium 1.011

### ISSUE THREAD

**Issue by sijidou** [xtaci/kcptun#146]
感谢。
一步一步根据教程让基本不懂代码的菜鸟也可以飞跃万里长城，好开心。
反馈一个bug：
20号版本，使用了salsa20 后效率提升好多啊。后来我在服务器端升级了libsodium到1.011，就连不上去了，怎么测试都连不上，换成默认加密就没问题，原因未知...

**Comment by dolphinpaopao** [comment]
最新git clone 编译安装，暂未发现问题。

**Comment by bubbless** [comment]
```
echo /usr/local/lib > /etc/ld.so.conf.d/usr_local_lib.conf
ldconfig
```
我用salsa20也是不行。

**Comment by bubbless** [comment]
Releases 8.30  Shadowsocks-android 3.0.7测试salsa20 正常了。
