### ISSUE TITLE
proposal: use io.CopyBuffer instead of io.Copy in client/server

### ISSUE THREAD

**Issue by defia** [xtaci/kcptun#149]
io.Copy() will allocate a []byte of 32*1024 length each time, which add pressures to gc.

Use sync.Pool or [leaky buffer](https://github.com/shadowsocks/shadowsocks-go/blob/master/shadowsocks/leakybuf.go) in [Effective Go](https://golang.org/doc/effective_go.html#leaky_buffer) to reuse []byte and pass them to io.CopyBuffer() will be better choice.

// CopyBuffer is identical to Copy except that it stages through the
// provided buffer (if one is required) rather than allocating a
// temporary one. If buf is nil, one is allocated; otherwise if it has
// zero length, CopyBuffer panics.

**Comment by xtaci** [comment]
32kb is enough for a single read/write, and the buffer would be used across a stream.  
I don't think CopyBuffer will improve GC.

**Comment by defia** [comment]
sync.Pool was added since go 1.3, CopyBuffer function was introduced to io package since go 1.5, while leaky buffer,which described in the artical Ideal Go, was used in shadowsocks-go since a long time ago.  
All of above methods , help developer archive better control of allocation with simple code modification. 
IMO, there is no reason to avoid using it.

**Comment by xtaci** [comment]
https://golang.org/src/io/io.go?s=12830:12908#L357

look above

the only difference between CopyBuffer & Copy is a temporarily allocated buffer。 and the 32KB buffer for kcptun is allocated for each session. 

https://github.com/xtaci/kcptun/blob/master/client/main.go#L64

the allocation speed for general usage is extremely slow.

It will only be useful if you have a very short connection, and re-establish it frequently , like establishing 100 connections per second.

**Comment by defia** [comment]
LOW still means some cost right? 

Kcptun was aiming at some low end devices, such as routers and mobile phones, why not apply this small optimize?
All you need to do is to add these codes and use CopyPoolBuffer instead of io.Copy
```
var pool = &sync.Pool{New: func() interface{} { return make([]byte, 8192) }}

func CopyPoolBuffer(p1, p2 io.ReadWriteCloser) (written int64, err error) {
	b := pool.Get().([]byte)
	defer pool.Put(b)
	return io.CopyBuffer(p1, p2, b)

}
```
`
如果不是考虑到需要在client和server复用这部分代码，会对项目目前结构有修改我就自己提pr了。。

**Comment by xtaci** [comment]
ok , make a PR. I'll review.
