### ISSUE TITLE
路由器可以装吗?要装哪个版本的呢?

### ISSUE THREAD

**Issue by asdyjd** [xtaci/kcptun#150]
华硕或者OPENWRT的固件,我的这个自带SHADOWSOCKS,而且已经可以用了.
要加KCPTUN的话,下哪个版本的呢?

**Comment by zpfsqzyl** [comment]
arm

**Comment by shutup** [comment]
看你路由器的架构，arm用arm版，mips用mips版（https://github.com/bettermanbao/openwrt-kcptun/releases）。

**Comment by qiumzh** [comment]
有没有相应的教程
