### ISSUE TITLE
当我开启kcptun服务的时候，不管是服务端还是客户端网络都会非常的卡？！

### ISSUE THREAD

**Issue by qiumzh** [xtaci/kcptun#151]
各路大神，请问一下你们，有没有试过这样的情况呢：
当我在客户端开识启kcptun服务的时候，同一局域网的网速会被拖的很慢，开个百度都慢得要死。。
服务端也是卡卡的，打一行命令也是卡1秒以上才能显示出来。。。
是不是我哪里的配置出错了呢？
请大神们多指教。
谢谢。
（小尾巴：https://blog.meduo.cc  ）

**Comment by kmahyyg** [comment]
unable to reproduce

**Comment by wxyzh** [comment]
能说下你的软硬件以及网络环境吗？

kmahyyg <notifications@github.com>于2016年8月22日周一 15:44写道：

**Comment by qiumzh** [comment]
哈哈，这个我调整回来了，已经可以正常使用了。
不得不吐嘈一下的就是这个kcptun真比finalspeed还要耗流量。
你们觉得呢。。。
（小尾巴：https://blog.meduo.cc ）

**Comment by ragnaroks** [comment]
在不丢包(<1 in 3600),我这边测试的情况基本也是kcptun比finalspeed消耗的多,但是你总不能在手机上装个fs吧...再说现在各种扶墙专用32/64M kvm,上finalspeed是不现实的.
