### ISSUE TITLE
同样的参数，windows下面速度比Linux下面快

### ISSUE THREAD

**Issue by xuan880** [xtaci/kcptun#152]
同样的参数，我发现在windows下面的时候kcptun的速度比Linux下面快很多，YouTube看4k视频windows下面速度最低也是一万三左右，最高可以接近三万，但是Linux下面，总是五千到一万左右跳动，这是为啥？
![screenshot_20160822_235302](https://cloud.githubusercontent.com/assets/2383369/17861446/bb69b80e-68c3-11e6-91cd-0e46f4d686ef.png)
![default](https://cloud.githubusercontent.com/assets/2383369/17861449/bca7d534-68c3-11e6-8602-4c6133713ccb.png)

**Comment by xuan880** [comment]
增加向前纠错，不同的模式我都试过了，windows下面速度总是比Linux下面快这是什么原因。
这个是十个纠错包的情况下的速度，不管怎么设置Linux下面就是比不上windows。
![screenshot_20160823_001051](https://cloud.githubusercontent.com/assets/2383369/17862142/883d25da-68c6-11e6-92ef-0d3f2b450c45.png)
![default](https://cloud.githubusercontent.com/assets/2383369/17862143/88828a30-68c6-11e6-881b-956871b7e0ca.PNG)

**Comment by ragnaroks** [comment]
来自萎软的神秘力量,我和你完全相反

**Comment by w12928293** [comment]
我这也是，树莓派上速度只有win上的差不多三分之一

**Comment by xtaci** [comment]
神奇 难道是tcp的部分没有调参数的原因？

**Comment by xuan880** [comment]
@xtaci 我在Linux修改-sockbuf参数才能勉强比得上windows下面的速度，我还用虚拟机下的XP跑过kcptun来测速，Linux下面的速度依旧比不上虚拟机中的速度。

**Comment by xtaci** [comment]
好的，我尝试改一个地方。

**Comment by xtaci** [comment]
试下0823，重新下载。

**Comment by xuan880** [comment]
@xtaci 最新版性能比原来好了些，但是YouTube上面显示的速度还是比不上windows下面。

**Comment by xtaci** [comment]
@xuan880 这会不会是html5播放器和flash播放器的差异。

**Comment by xuan880** [comment]
@xtaci 改用Flash的话速度的确能上升一些，看同样分辨率的视频Flash的确比HTML5流畅，但是我测试的时候用的都是HTML5播放器，非要说不同的话就是windows下面的firefox支持视频硬解，Linux下面不支持，不过这个对网速应该没影响呀。

**Comment by xtaci** [comment]
@xuan880 很难说。我觉得可以尝试下在windows下，分别用firefox和chrome播放同一视频，并切换解码器试试。

**Comment by braveguywallce** [comment]
@xuan880 我看到你这么说，还真的特地在本地windows 7 上跑了实验呢。结果恰恰相反，ARM7平台上的Linux版本更加稳定快速。我的kcptun版本是0820. 电信50M网络。你说的情况未必就是kcptun自己的问题。@xtaci  反正我就用0820版本，目前很稳定，还没遇到server或者client崩溃的情况。

**Comment by xtaci** [comment]
@braveguywallce 很有趣的问题，很想知道真相。

**Comment by braveguywallce** [comment]
@xtaci  ARM7 平台我用kcptun下载youtube视频现在都可以跑到3.5MB的高速度，0820的版本，salsa20加密，没啥问题。
另外我在window 7下面， firefox和chrome都测试过了，kcptun的参数设置和Linux下一模一样，并没有楼主描述的问题。 我觉得视频播放网速的快慢和很多因素有关，真的很难从一个个例能说明什么，本身我们的网络和路由都不是恒定的，而是一直在变化的，时快时慢，但是从我这边来看，arm7平台下0820Linux版本，使用体验很稳定很好！

**Comment by xuan880** [comment]
@xtaci 我又用虚拟机测试了一下，YouTube上面的速度依旧是windows快于Linux，Linux显示的速度只有windows的一半还不到，但是我发现实际卡顿程度没有太大区别，用fast测速也没太大区别，很奇怪呀。

**Comment by xtaci** [comment]
哦， 虚拟机。。。

**Comment by xuan880** [comment]
@xtaci 实体机也是一样，来回重启太麻烦了

**Comment by xtaci** [comment]
无法判断， 只能以测速为准，应用层影响因素太多了。

**Comment by w12928293** [comment]
@xuan880 你好，你调的-sockbuf参数多少合适？我这linux下也很慢。。。

**Comment by xuan880** [comment]
@w12928293 这个要根据你的带宽和延迟自己算，我的网络情况下是12000000左右。

**Comment by cs8425** [comment]
@xuan880 
格式一個vp9一個avc你確定這樣比有意義?
找一個測速網站測比較準啦

**Comment by weyou** [comment]
我发现了和楼主相同的问题，在RaspberryPi3，和OpenWRT上分别安装kcptun，Openwrt是出口路由器，RPi3是百兆有线连接到OpenWRT。 kcp版本是2017308 arm7。这是用tcping测试延迟RPi3上的KCP的结果差不多450ms左右：
C:\Windows\system32>tcping64 -h www.google.com

** Requesting "" from www.google.com:
(for various reasons, kbit/s is an approximation)


Probing 172.217.26.36:80/tcp - HTTP is open - time=1.651ms rcv_time=447.778 status=200 bytes=10933 kbit/s=~195.329
Probing 172.217.26.36:80/tcp - HTTP is open - time=1.769ms rcv_time=450.313 status=200 bytes=10980 kbit/s=~195.064
Probing 172.217.26.36:80/tcp - HTTP is open - time=2.525ms rcv_time=456.891 status=200 bytes=10957 kbit/s=~191.853
Probing 172.217.26.36:80/tcp - HTTP is open - time=2.490ms rcv_time=454.527 status=200 bytes=10928 kbit/s=~192.341

Ping statistics for 172.217.26.36:80
     4 probes sent.
     4 successful, 0 failed.
Approximate trip times in milli-seconds:
     Minimum = 1.651ms, Maximum = 2.525ms, Average = 2.109ms
Approximate download times in milli-seconds:
     Minimum = 447.778ms, Maximum = 456.891ms, Average = 452.377ms
同样的，直接将kcptun跑在OpenWRT上，测试的结果跟上面不相上下。

但是直接用windows上kcp客户端测试延迟：
C:\Windows\system32>tcping64 -h --proxy-server 127.0.0.1 --proxy-port 2080 www.g
oogle.com

** Requesting "" from www.google.com:
(for various reasons, kbit/s is an approximation)


Probing 127.0.0.1:2080/tcp - HTTP is open - time=19.473ms rcv_time=272.515 status=200 bytes=10893 kbit/s=~319.777
Probing 127.0.0.1:2080/tcp - HTTP is open - time=0.772ms rcv_time=282.949 status=200 bytes=11008 kbit/s=~311.236
Probing 127.0.0.1:2080/tcp - HTTP is open - time=0.793ms rcv_time=281.376 status=200 bytes=10934 kbit/s=~310.873
Probing 127.0.0.1:2080/tcp - HTTP is open - time=0.328ms rcv_time=350.682 status=200 bytes=10949 kbit/s=~249.776

Ping statistics for 127.0.0.1:2080
     4 probes sent.
     4 successful, 0 failed.
Approximate trip times in milli-seconds:
     Minimum = 0.328ms, Maximum = 19.473ms, Average = 5.342ms
Approximate download times in milli-seconds:
     Minimum = 272.515ms, Maximum = 350.682ms, Average = 296.880ms  
延迟相差还是很大的。
