### ISSUE TITLE
is there a possibility to fake tcp packet header for kcp against QoS from ISP?

### ISSUE THREAD

**Issue by lunaset** [xtaci/kcptun#154]
when I measure uplink speed of server using iperf, i found the almost 1/2 of udp packet dropped in domestic router, as well as tcp test return no bad report. seems the QoS strategy my local ISP applies isn't friendly to udp transport.

despite kcptun could serve demands at the expense of approximately quadruple bandwidth use until now, perhaps there is a call to take some solution against more strict QoS policy in future,and using fake tcp packet  header may be one option in this case.

**Comment by jannson** [comment]
But the fake tcp header maybe detected by the ISP or firewall.  it may drop the fake tcp packet as it's not a valid tcp connection.

**Comment by siril233** [comment]
IMHO,   tempering IP header
makes a stronger fingerprint;
requires some, hmm... extensive coding;
reduces compatibility (with firewalled VPS server such as azure,  or privilege/resource restricted clients)

so...   utilizing standard TCP/UDP should be a better choice.

**Comment by lunaset** [comment]
@siril233 i have no idea if a fake packet can bypass firewall ,although kcp could be accepted by the firewall of AWS when udp allowed only. utilizing standard TCP/UDP should be a better choice ,and it would be a long spot .

BTW, for such a private transport layer protocol , fingerprint might not be worst problem currently ,rather users number does in my perspective .

**Comment by lunaset** [comment]
@siril233 

tell me about it . implementing this may way off what kcptun was designed for too much .

exactly bandwidth like tcp flood could be treated as violation of tos more than a legal application. 

all right ,load-balance ,mptcp or something like that should be our man ,not net-speeder.

**Comment by siril233** [comment]
@lunaset 

---------

Probably fingerprint of flooding is a avoidable problem,   after some magical transformation/encryption, packets carrying same data could be completely different.
But implementing this requires libpcap or other similar underlying library,   root access is mandatory, coding is a bit tougher.
At least this level of obfuscation is beyond the capabilities of kcp protocol,  
I think such obfuscation (disguise a custom protocol) is beyond the design of kcptun.

---------

Seems that the author is not willing to add features too complicated to implement or beyond the capability of kcp protocol.

I suggested multi-link load balancing and failover  and on-the-fly port change in another issue #159  , the author advised me to implement one myself.
despite of my poor programming skills, I am tempted to try implement a multi-link load balancing portproxy myself.

----------

@xtaci   please clarify this if I am wrong .

**Comment by xtaci** [comment]
@siril233 that's exactly my option.
a question: how do you solve TCP-RST problem(it will kill the router mapping).

**Comment by siril233** [comment]
@xtaci     

we are not talking about tcp,  but something looks like tcp and acts differently .

If we can implement a customized “tcp" protocol,  there are many choices:

1.   ignore rst packet  (require public internet address on both side),  nat mapping is no longer a problem.
     our non-standard "tcp” protocol could be more intelligent
     than government supported DPI system (u know what i‘m referring to)，
     because there is no need to scale up to some TB/s
2.   send packets with redundancy,  load balance real data on multiple encrypted tunnels 
     with different fingerprints,  different routing path,
     and create encrypted tunnels dynamically,    make it as difficult as possible to analyze

**Comment by lunaset** [comment]
@siril233 sounds like what v2ray works on now ,which use a branch of kcp (calls mKCP) & dangling port as well.

ip whitelist could be made ,but there's still a long way to go for gov. put all outbond traffic in control - at least not in too brutal way like that for now.

**Comment by xtaci** [comment]
@siril233 It's far beyond my original intention. I'll just ***stick to the fundamentals***, let the open-source community do the improvements & changes, such as ... P2P.

**Comment by siril233** [comment]
@xtaci 

IPv6 is different,  it is network layer protocol, requires device support all along the path,
or various IPv6 over IP solutions.

---------------

the "magical multi-link tunnel"  does all the magic in transport layer (and above),  
based on IP protocol (and IPv6, probably),   
require a client application and a server application (or completely p2p)
hmm...  something like an improved tor

---------------

The main problem of IPv6 deployment is lack of business motivation,   not technical 

---------------

reinvent tcp is difficult ,  but reinvent udp is a bit easier, probably.
the objective of such a protocol is obfuscation (or encryption) ,  and QoS bypass, 
quite different form the design purpose of tcp or udp

**Comment by chinawrj** [comment]
@siril233 你好，你的idea听起来很有趣的样子，我也想过这个问题。可以使用raw ip API来实现tcp的三次握手之后进行无ack／无windows的传输，接一单通过三步握手让中间路由建立起nat maping之后，就可以把这个接口当作UDP类似的来使用，同时通过伪装的tcp header中的fake seq来利用QOS对TCP的高优先级以及QOS对数据量小的TCP的高优先级（QOS通过TCP中的seq来判断流量大小，这样可以做到无状态检测）。  
个人觉得还是使用TCP随机分段技术比较好一点，即针对于一个client发起的tcp连接，在kcptun client在传输数据到server的过程中使用多个tcp连接分段传输。比如一个client发起的tcp连接要传输10M数据，那么kcptun就发起10个tcp连接，每个连接传输1M之后就断开。这样能规避TCP TOS
有兴趣我们可以一起交流一下。

**Comment by wangyu-** [comment]
@lunaset @chinawrj 
my repo implemented this idea,and its able to pass through NAT
https://github.com/wangyu-/udp2raw-tunnel
