### ISSUE TITLE
教练! 有Snappy压缩库为什么没有LZMA/XZ/LZ4压缩库喵?

### ISSUE THREAD

**Issue by mindcat** [xtaci/kcptun#155]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

**Comment by mindcat** [comment]
有着LZMA压缩库可以使用手机流量节省流量喵! 猫猫听说LZ4比Snappy压缩又好又快喵 另外求Linux tsocks/udp转发功能喵

**Comment by wxyzh** [comment]
丢包少了，自然会省流量

**Comment by mindcat** [comment]
@wxyzh 这个回应是什么鬼喵? 牛头不对马嘴喵?...

**Comment by wxyzh** [comment]
@mindcat 压缩会增加运算量，对于已经加密的数据压缩的效果并不好。所以，何必呢。如果真的要省流量的话，建议用一个服务器去中转，例如 mobile------aliyun-------vps。
建议用kill -SIGUSR1 pid 去看看两端的信息

**Comment by shuimu98** [comment]
你喵喵喵的是什么鬼

**Comment by xtaci** [comment]
是的喵，压缩只会在某些极少数环境才有用喵。

**Comment by ragnaroks** [comment]
kcp本身不是为了省流量设计的,与其在压缩上面想办法,不如弄个免流.

**Comment by mindcat** [comment]
喵...
