### ISSUE TITLE
教练! 有UDP动态转发功能喵? 就像sshuttle喵!

### ISSUE THREAD

**Issue by mindcat** [xtaci/kcptun#156]
```sudo sshuttle --method tproxy --python /usr/bin/python2 --disable-ipv6 -v --exclude 198.148.115.168 --exclude 8.8.8.8 --exclude 8.8.4.4 --exclude 114.114.114.114 --exclude 192.168.1.0/24 --exclude 192.168.58.0/24 --exclude 127.0.0.0/8 --exclude 198.148.115.168 -r 198.148.115.168 0/0```

**Comment by xtaci** [comment]
没有
