### ISSUE TITLE
急！这个是什么一个情况？

### ISSUE THREAD

**Issue by qiumzh** [xtaci/kcptun#157]
![33](https://cloud.githubusercontent.com/assets/12442026/17920982/2aade4aa-6a0a-11e6-90c9-bfeae49e3c11.png)

**Comment by blooddrunk** [comment]
similar problem for me

**Comment by qiumzh** [comment]
找到原因了 我把参数-nocomp去掉就可以了 如果加上就出现这个情况。

**Comment by lbbboy** [comment]
-nocomp 不压缩真能解决？？我的是会断流。头疼。。
