### ISSUE TITLE
请问下能不能出个服务器端的详细配置，是否可以单独使用kcptun服务器端，还是要搭配ss使用？

### ISSUE THREAD

**Issue by ThomasLiaoQian** [xtaci/kcptun#162]
首页就只教了一个简单的服务器端配置只有一条命令，不知道是否可以从单独的配置文件载入参数？有没有具体的方法？
另外在百度搜索大多是一个kcptun+ss搭配的教程，目前kcptun真的还需要和ss搭配才能使用吗？
本来在用clang的一键kcp的，但是17天之前更新了windows客户端就非常不稳定，想试用一下原版

**Comment by lizongzeshunshun** [comment]
1. 没有配置文件
2. 不能单独使用，可以搭配ss/dante等
(ps: -t 参数指定搭配的应用的ip/端口）

**Comment by xtaci** [comment]
google搜到的网友的玩法： 
![cmpwujwusaajjsd](https://cloud.githubusercontent.com/assets/2346725/18039885/a9c5f872-6dd9-11e6-90e6-2fa249ce3761.jpg)
