### ISSUE TITLE
断流

### ISSUE THREAD

**Issue by baggiogogo** [xtaci/kcptun#163]
你好，情况是这样的，kcptun会被我自己设置的路由QOS策略丢包导致断流。
比如：观看YouTube切换清晰度或者拉动进度条时会发生，会导致YouTube报错。ipadYouTube客户端。kcptun部署在vps和家中的树莓派上。
如关掉路由qos，则不会产生。路由系统是routeros。
困扰我的是，如只使用SS，同样被qos丢包，那么YouTube是可以持续的，不会报错或者无法观看。
现在要么我只有关掉qos，或者关掉kcptun，两者取其一。已调整过无数参数测试。
可以帮忙想想办法或出出主意吗，谢谢。

**Comment by baggiogogo** [comment]
补充，不是每个视频都会产生这样的情况，很奇怪。

**Comment by siril233** [comment]
建议先关闭qos，  调试  kcptun  的参数，到速度和有效载荷满意的程度为止；
kcptun发包逻辑相当。。。暴力，多倍发包看起来好可怕， 我都不敢在公司用了。

另外，qos应该可以添加例外吧

autoexpire参数试过了没，似乎可以一定程度上对抗按udp session识别的qos

------------------

其原因推测是两方面：
1.  缺适当的 flow control。。。（不止是congestion control）。。。
2.  ISP给的可用出国带宽随时段变化而变化 （丢包率变化），调试好的参数可能几小时后就变得不适当了。

------------------

我观察到有些时段 隧道可用 30Mbps，占用40~50Mbps；
另一些时段 隧道可用不到20Mbps，占用带宽 50~60Mbps。。。
  （可能测试方法不够准确， 网页测速结果 和 对ovpn over kcptun 的tun0  和  eth  分别  iftop 看见的）
感觉我们需要一个新项目，牺牲加密等级 和 延迟  换取  够用的可用带宽 和 合理的带宽利用率。

**Comment by baggiogogo** [comment]
谢谢回复，目前暂停使用kcptun中，大部分时间我的vps线路还行，可以满足我1080p的需求，也确实如您所说在某些时段下降到只能看720p，就是奔着任何时段都愉快的1080这个想法，尝试使用kcptun，牺牲点流量无妨，估计我太菜哪里有问题，慢慢再捋捋。
另外那个随机端口的想法确实很酷！

**Comment by baggiogogo** [comment]
![image](https://cloud.githubusercontent.com/assets/21306212/18081791/823de2c4-6ece-11e6-80f2-3236157fb812.png)
解决了，qos类型里面要丢大包，默认是丢50，小包是丢10。有同样困扰的朋友可以试试。
一直都按照应该丢小包或者甚至不丢包的思路走，今天瞎填个100，居然把问题解决了。瞎猫碰上死耗子。目前不会报错了，正常缓冲。
