### ISSUE TITLE
ss+kcptun怎样调整参数才能最大程度降低联机游戏丢包

### ISSUE THREAD

**Issue by zardonc** [xtaci/kcptun#167]
联通50m 搬瓦工Fremont节点 丢包20%左右
部署了kcptun后下载速度提升不小原本googleplay xboxlive 4m/s左右，之后基本能稳定在10-20m/s
cod 战地等游戏ping值有所降低但是仍然不稳定联美西服务器ping保持在180-280ms之间偶尔会突然飙升至600+并且查看战地4内置的网速测试丢包在1%-30%之间波动

尝试了normal/fast/fast2不同模式网速略有不同，但是游戏联机的状况大同小异都很严重，想了解如何调整参数才能有效降低游戏联机的丢包，哪些参数对丢包有较大影响，不同mtu是否有影响？

**Comment by xtaci** [comment]
游戏是最需要快速响应的，可以尝试 
```
-mode manual -nodelay 1 -resend 1 -nc 1 -interval 10
```

**Comment by zardonc** [comment]
多谢，还有不同的mtu会有影响吗？

**Comment by jannson** [comment]
确定游戏数据走了 kcptun 吗？很可能就没有走吧。游戏不走 tcp 的话就不走 kcptun

**Comment by zardonc** [comment]
不确定啊，可能真的是没走吧

**Comment by zardonc** [comment]
怎样将游戏的udp流量转为tcp?openvpn?

**Comment by baggiogogo** [comment]
win版的ss我记不清是否可以udp转发了，安卓是可以的。不可以的话找找ssr看看是否可以，服务端记得相应配置-u参数，防火墙打开相应端口。

**Comment by baggiogogo** [comment]
抱歉看成udp转发，ssr我记得看介绍有功能为把udp包在tcp发送或把tcp包在udp中发送（不是原文，大意），可以去看看能否实现你想要的，如实现那减少了其它工具的学习成本。

**Comment by xtaci** [comment]
<img width="411" alt="2016-09-01 9 56 11" src="https://cloud.githubusercontent.com/assets/2346725/18152701/7459a83e-702a-11e6-8dff-b44e6aa52397.png">
<img width="450" alt="2016-09-01 9 56 30" src="https://cloud.githubusercontent.com/assets/2346725/18152700/7458329c-702a-11e6-803c-07afbce2b5ba.png">
<img width="413" alt="2016-09-01 9 55 22" src="https://cloud.githubusercontent.com/assets/2346725/18152699/745807c2-702a-11e6-8c52-c3158a654ecd.png">


传输曲线比yamux平滑。

**Comment by zardonc** [comment]
是呀，我需要的是将udp包在tcp里发送

**Comment by haodong** [comment]
@xtaci 二楼的参数适合ovpn over kcptun吗？
现有的参数我用fast2，基本连上游戏一小时左右必掉！

**Comment by xtaci** [comment]
@haodong ovpn是三层的，根本不存在断的问题，快速切换也不会影响

**Comment by haodong** [comment]
@xtaci 昨晚测试，连上一小时左右掉线，出现`broken pipe`
```
2017/04/04 22:43:10 remote address: xx.xx.x.xx:62813
2017/04/04 22:43:10 stream opened
2017/04/04 22:43:10 stream closed
2017/04/04 22:43:10 stream opened
2017/04/04 22:43:15 stream closed
2017/04/04 22:43:23 broken pipe
2017/04/05 00:26:37 stream closed
2017/04/05 00:27:10 broken pipe
```
服务器到客户端的丢包率在1%左右。
