### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by lbbboy** [xtaci/kcptun#169]
2016/09/01 11:02:18 version: 20160830
2016/09/01 11:02:18 listening on: [::]:12948
2016/09/01 11:02:18 encryption: salsa20
2016/09/01 11:02:18 nodelay parameters: 1 20 2 1   这里配置设置的是 1 10 2 1，启动后1 20 2 1 。
2016/09/01 11:02:18 remote address: vps:29900
2016/09/01 11:02:18 sndwnd: 140 rcvwnd: 140
2016/09/01 11:02:18 compression: true
2016/09/01 11:02:18 mtu: 1464
2016/09/01 11:02:18 datashard: 0 parityshard: 0
2016/09/01 11:02:18 acknodelay: false
2016/09/01 11:02:18 dscp: 46
2016/09/01 11:02:18 sockbuf: 4194304
2016/09/01 11:02:18 keepalive: 10
2016/09/01 11:02:18 conn: 1

**Comment by xtaci** [comment]
-mode manual?

**Comment by lbbboy** [comment]
是用 json启动的，需要修改那个地方？

**Comment by baggiogogo** [comment]
"mode": 改manual

**Comment by lbbboy** [comment]
@baggiogogo 我是用配置文件啊。。。

**Comment by baggiogogo** [comment]
编辑json文件，把mode项后面的fast之类改成manual，如没mode项则添加，可以参考作者给出的json范例。要注意的是有几个参数服务端和客户端必须一致，参考wiki。

**Comment by Cye3s** [comment]
json配置文件里不指定某个参数的话，是用默认值吧？

**Comment by lbbboy** [comment]
@Cye3s 是我疏忽，mode 没改 manual 下面修改参数就没用了。
