### ISSUE TITLE
建议分析现有丢包和冗余情况，并考虑进一步改进方向

### ISSUE THREAD

**Issue by yaleh** [xtaci/kcptun#17]
建议分析现有情况：

* 发送冗余度（重发比例）
* 接收冗余度
* 丢包率

方法和工具：

* Debug log
* 增加统计实现和 log
* Wireshark extension

进一步改进方向：

* ACK 和重发机制改进
* FEC

现在直观的感受是接收端冗余度很高，应该有空间进一步提高吞吐率和带宽利用率。

**Comment by xtaci** [comment]
会的，很好的建议， 感觉是实时性，冗余度，网络吞吐三者不可同时拥有。
