### ISSUE TITLE
能否开发ramips版本？？

### ISSUE THREAD

**Issue by lbbboy** [xtaci/kcptun#170]
非常想直接在路由上使用，ramips版有一个开发者在开发，但是更新速度有点慢。跟不上原作者的速度。。

**Comment by dolphinpaopao** [comment]
参见Wiki，可自行编译。

**Comment by Anyfc** [comment]
不知道 https://github.com/EasyPi/openwrt-kcptun 这个能不能 用？？？

**Comment by lbbboy** [comment]
@dolphinpaopao @Anyfc 我不会编程。。

**Comment by braveguywallce** [comment]
@lbbboy  找台VPS搭建一个环境，交叉编译即可，没什么技术难度，自己慢慢google吧。
