### ISSUE TITLE
youtube流畅，googleplay下载断流的问题

### ISSUE THREAD

**Issue by chk970222** [xtaci/kcptun#171]
在使用过程中有个问题，请教一下。我用的0902服务端版本，win10也是同样版本号，网络环境是50M电信，VPS是搬瓦工。现在碰到的问题：我正常连接后，youtube看1080P应该是比较稳定的，速率大概在3000kpbs-7000kpbs，当然大部分时候在3000多，这问题都不大。但是我手机端用googleplay下载软件时，经常性的断流，完全没有数据流量。请问我现在该如何修改，谢谢。
服务端参数：-key *** -crypt aes-128 -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -dscp 46 -datashard 70 -parityshard 30 -mode manual -nodelay 0 -resend 0 -nc 1 -interval 40 -nocomp
客户端参数：-key "***" -crypt aes-128 -nocomp -datashard 70 -parityshard 30 -conn 4 -mtu 1400 -sndwnd 256 -rcvwnd 1024 -dscp 46 -mode manual -nodelay 0 -interval 20 -resend 0 -nc 1

**Comment by braveguywallce** [comment]
你用的是什么手机端？shadowsocks-android迄今只支持到kcptun 0830版，和0902版本完全不兼容，因此是无法工作的。另外，smux 0902版本手机端下载文件还存在些问题。

**Comment by chk970222** [comment]
@braveguywallce 哦，这个忘了说，我手机通过电脑端的shadowsocks共享给局域网使用的，这难道有影响？那就太诡异了。我刚才把服务端和客户端都更新到最新版，结果还是一样，看1080P视频较流畅（几乎没卡顿），我也不计较那些数字；但是用googleplay下软件还是会半天开始下，下一会就完全没数据，等很久又下一会，如此反复。

**Comment by txdywy** [comment]
遇到类似问题
