### ISSUE TITLE
broken pipe  看过历史issue 没找到一样的情况 前来求救

### ISSUE THREAD

**Issue by tianrking** [xtaci/kcptun#174]
网络 联通宽带20m 服务器 ubuntu Linux o-l 2.6.32-042stab116.2 #1 SMP Fri Jun 24 15:33:57 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux
尝试使用shadowsocks配合kcptun 客户端Android 理论配置正确 不开kcptun可正常连接 开启后可以发送数据接收不到数据
服务器日志如下   谢谢
root@o-l:/home/kcptun# ./ser* -l ":443" -t "0.0.0.0:251" -mode manual -nodelay 0 -resend 0 -nc 1 -interval 40 -dscp 46 -nocomp -mtu 1400 -crypt aes-128 -datashard 70 -parityshard 30
2016/09/03 22:55:33 version: 20160902
2016/09/03 22:55:33 listening on: [::]:443
2016/09/03 22:55:33 target: 0.0.0.0:251
2016/09/03 22:55:33 encryption: aes-128
2016/09/03 22:55:33 nodelay parameters: 0 40 0 1
2016/09/03 22:55:33 sndwnd: 1024 rcvwnd: 1024
2016/09/03 22:55:33 compression: false
2016/09/03 22:55:33 mtu: 1400
2016/09/03 22:55:33 datashard: 70 parityshard: 30
2016/09/03 22:55:33 acknodelay: false
2016/09/03 22:55:33 dscp: 46
2016/09/03 22:55:33 sockbuf: 4194304
2016/09/03 22:55:33 keepalive: 10
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:53 remote address: 219.147.152.95:37295
2016/09/03 22:55:53 broken pipe
2016/09/03 22:55:54 remote address: 219.147.152.95:37295
2016/09/03 22:55:54 broken pipe
2016/09/03 22:55:54 remote address: 219.147.152.95:37295
2016/09/03 22:55:54 broken pipe
2016/09/03 22:55:54 remote address: 219.147.152.95:37295
2016/09/03 22:55:54 broken pipe
2016/09/03 22:55:54 remote address: 219.147.152.95:37295
2016/09/03 22:55:54 broken pipe

**Comment by braveguywallce** [comment]
把server端 target改成你vps的真实ip试试看。

**Comment by lizongzeshunshun** [comment]
-t 参数错误 ，应该是"127.0.0.1:<your-ss-port>"

**Comment by Anyfc** [comment]
更新shadowsocks到最新版 试试

**Comment by bubbless** [comment]
[https://github.com/shadowsocks/shadowsocks-android/releases/tag/v3.1.0](https://github.com/shadowsocks/shadowsocks-android/releases/tag/v3.1.0)
> Update SMUX based KCPTUN.
Warning: You should update your kcptun server to the latest.

版本要对应，SMUX支持才行。

**Comment by Jackiepie** [comment]
在github上找到安卓最新的3.1.0版本才能用

**Comment by tianrking** [comment]
好哒 原来是 问的安卓版本的问题  新版需要SMUX支持 到github上更新下可以用了 @bubbless @Jackiepie 同样谢谢braveguywallce lizongzeshunshun
braveguywallce ->"把server端 target改成你vps的真实ip试试看。我这里操作效果和“:端口号" 或者“0.0.0.0:端口号”一样  lizongzeshunshun->-t 参数错误 ，应该是"127.0.0.1:ss端口"  我试了下 0000和127001都行，不是这个原因导致的
谢谢大家了 可以close了
