### ISSUE TITLE
刚启动的时候速度很快，但是一会就没有速度了

### ISSUE THREAD

**Issue by CuminLo** [xtaci/kcptun#175]
服务器参数
```
--key xxxx --mtu 1400 --sndwnd 2048 --rcvwnd 2048 --mode fast3 --crypt aes --dscp 46 --datashard 70 --parityshard 30 --nodelay 0 --resend 0 --nc 1 --interval 40 --nocomp
```

客户端参数
```
--key "xxxx" --crypt "aes" --mode fast3 --dscp 46 --nocomp --rcvwnd 2048 --sndwnd 2048 -nodelay 0 -resend 0 -nc 1 -interval 40 --datashard 70 --parityshard 30
```

刚启动的时候，看YTB视频速度很快，但是一会就会停止，即使重启也一样，一会也没有速度了。
从log中看视频停止的时候，log也没有了。

服务器是搬瓦工。
家里用的长城带宽。

对参数没有更深层次的了解，恳请各位大大给予帮助。

**Comment by bubbless** [comment]
那你应该把客户端的 rcvwnd 和sndwnd 做下调整，mode尝试fast或者fast2,加密方法试试salsa20 ，我搬瓦工看土鳖2K和4K无压力。仔细阅读README，多看看issue.

**Comment by CuminLo** [comment]
@bubbless 感谢回复。这几个参数也确实调整过，因为没啥效果，所以我才把参数调到最大，以为会有好转。。。

**Comment by CuminLo** [comment]
@bubbless 长城宽带这个确实没办法了。家里人已经买了两年。。。

**Comment by braveguywallce** [comment]
长城宽带的带宽很多时候是小区共用的，不是独享带宽，请远离长宽。

**Comment by braveguywallce** [comment]
另外你把mode从fast3改为manual

**Comment by kzwr** [comment]
部分地区的长城宽带会屏蔽UDP流量，广州地区的长城宽带偶尔晚上UDP流量直接截断
