### ISSUE TITLE
UDP relay doesn't work when using Shadowsocks over kcptun

### ISSUE THREAD

**Issue by smounives** [xtaci/kcptun#177]
OS: Windows 10 RS1 Build 14393.105
Shadowsocks Client: Latest commit [514bb02](https://github.com/shadowsocks/shadowsocks-windows/commit/514bb02098933c8a08095564c7c6fc545a8a5fe2) of shadowsocks-windows v3.2
Shadowsocks Server: [shadowsocks-libev v2.5.0](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v2.5.0)
kcptun: [v20160904](https://github.com/xtaci/kcptun/releases/tag/v20160904)
command line I used: 
```
server_linux_amd64 -l :[port] -t 127.0.0.1:[ss_port] --crypt none --mtu 1200 --nocomp --mode normal --dscp 46 --parityshard 0

client_windows_amd64.exe -l 127.0.0.1:1090 -r [server]:[port] --crypt none --mtu 1200 --nocomp --mode normal --dscp 46 --parityshard 0
```

When I directly using shadowsocks, the UDP relay works properly, but shadowsocks over kcptun not.

**Comment by D-Bood** [comment]
I think you want to turn FEC off and it should be `-datashard 0` on both sides

**Comment by smounives** [comment]
@D-Bood  If I add `-datashard 0`, there is an error (or waring? I don't know)
```
~# 2016/09/05 18:24:14 version: 20160904
2016/09/05 18:24:14 listen udp :8399: bind: address already in use
net.ListenUDP
github.com/xtaci/kcp-go.ListenWithOptions
	/Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:778
main.main.func1
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:303
runtime.call32
	/usr/local/go/src/runtime/asm_amd64.s:479
reflect.Value.call
	/usr/local/go/src/reflect/value.go:434
reflect.Value.Call
	/usr/local/go/src/reflect/value.go:302
github.com/urfave/cli.HandleAction
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:244
main.main
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:347
runtime.main
	/usr/local/go/src/runtime/proc.go:183
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2086

[2]+  Exit 255
```

**Comment by braveguywallce** [comment]
It's the problem of your configuration on the shadowsocks, the server is set up as "localhost"  in the shadowsocks client when you use it over kcptun, while all udp packages will be relayed to the server "localhost" by shadowsocks too instead of  the ultimate VPS server, and kcptun doesn't work with udp relay, so you got the issue.

to solve this problem, you have to run shadowsocks  in this way:

`ss-local -s 127.0.0.1 -p 1090 -k passwd -m chacha20 -l 1080 -b 0.0.0.0 &
ss-local -s <server_ip> -p 443 -k passwd -m chacha20 -l 1080 -U -b 0.0.0.0`

**Comment by smounives** [comment]
@braveguywallce Thanks a lot!

**Comment by fy0** [comment]
Same problem, sslocal -U not exists.
Server: shadowsocks-py 2.9.1
kcptun-svr -t "127.0.0.1:1234" -l ":5678" -mode fast2
kcptun-clt.exe -r "server_ip:5678" -l ":1234" -mode fast2

sslocal -s 127.0.0.1 -p 1234 -k 123 -l 9876 -b 0.0.0.0

test code:
```python
s = socks.socksocket(socket.AF_INET, socket.SOCK_DGRAM)
s.set_proxy(socks.SOCKS5, "localhost", 9876)
msg = b'\x5c\x6d\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x03www\x05baidu\x03com\x00\x00\x01\x00\x01'

s.sendto(msg,('8.8.8.8',53))
print(s.recv(4096))
```

Still not work, help!
@xtaci @braveguywallce

**Comment by dearneo** [comment]
@fy0 If you are using window OS, you can try kcptun-gui , this kcptun client support RDP relay.
[https://github.com/GangZhuo/kcptun-gui-windows](url)

**Comment by fy0** [comment]
@dearneo  transfer only, no boost, right?

**Comment by dearneo** [comment]
@fy0 yeah, i think so.

**Comment by fy0** [comment]
@dearneo Well, I noticed xtaci said udp over kcptun won't be supported, so we have no way.
