### ISSUE TITLE
如何调整参数才能避免VPS再度被冻结

### ISSUE THREAD

**Issue by icecrack** [xtaci/kcptun#179]
今天使用VPS（Sentris家的廉价VPS）番墙看Youtube过程中，VPS被封了，封的理由是   “abuse high burst bw server_linux_am”
使用的KCPTUN版本为最新的SMUX版，参数如下：
-key test -mtu 1400 -sndwnd 256 -rcvwnd 2048 -mode fast2 -dscp 46

想知道下，如何调整参数才能避免服务器再度被冻结。

**Comment by baggiogogo** [comment]
这个不好说，按照字面理解肯定是突发的时候占了太多共享带宽，先把vps的带宽限制一下，限制到不超过你的下载带宽，参考wiki，然后在流畅观看的前提下尽可能把参数调温柔些，比如normal之类，然后安天命吧，除非你不用，不然还是他说了算。

**Comment by xtaci** [comment]
一分价钱一分货是颠簸不破的真理

**Comment by braveguywallce** [comment]
廉价VPS是共享带宽的，你大量快速发包，把带宽占据了，肯定会被封的。换个独享带宽的VPS就没事了。

**Comment by icecrack** [comment]
@braveguywallce   独享带宽的VPS，在购买页面哪里有提示？  KVM的都是独享的吗？

**Comment by icecrack** [comment]
@baggiogogo   嗯，我再去调整下带宽控制，再被冻结，估计这次就不能再解封了。

**Comment by bettermanbao** [comment]
我也是sentris，用了很久fast mode，一直很稳定。

**Comment by icecrack** [comment]
@bettermanbao 你服务器用的什么参数？ 服务器进行流量控制了吗？ 平时看Youtube多么？

**Comment by Comah** [comment]
你用的是sentris吧？我今天早上也被封了。。旧版没被封过，早上更新了最新版本之后被封了。。
Suspension Reason:abuse high burst bw 
加密是salsa20 压缩禁用了 其他全部默认

**Comment by sgf** [comment]
这和kcp本身没关系吧
廉价的东西悠着点，毕竟人家开起门来做生意 谁想亏本？

**Comment by imsong52** [comment]
我用搬瓦工,流量一个星期就被占完了

**Comment by icecrack** [comment]
@Comah  你的现在啥情况了？

**Comment by icecrack** [comment]
@sgf  说的没错，不希望把带宽都给占了，只想速度快点，流畅看个480p的youtube就行。不贪心1080p的

**Comment by hangaj** [comment]
用fast就行了。。也能流畅1080

**Comment by bettermanbao** [comment]
我的sentris也被封了，也是看youtube造成的。
20Mbps传输了10分钟后被封，现在降到10Mbps使用，目前还没有被封。

**Comment by punklee2014** [comment]
@bettermanbao，请教，用的是3年缴费的那种吗？怎么设置参数？速度一直上不去。谢谢！

**Comment by bettermanbao** [comment]
@punklee2014 fast sndwnd rcvwnd 128 youtube显示2.5-3.0Mbps，720p肯定能够流畅播放。

**Comment by ninggu2008** [comment]
@bettermanbao 
sentris的openvz，centos怎么限制带宽，流量控制？readme里面的命令报错啊，把网卡名字换成我vps的，也还是报错。

**Comment by bettermanbao** [comment]
sndwnd rcvwnd别超过256就可以了

**Comment by ninggu2008** [comment]
我都不敢设置fast了，改成normal了。窗口改成160了。
