### ISSUE TITLE
0904版退出连接后，仍然向客服端发包。

### ISSUE THREAD

**Issue by triaqu** [xtaci/kcptun#180]
几台VPS，其中有两台是OVZ，debian系统，只装了SS和kcptun，昨天升的0904，今早发现没连接这两台，但有每秒几兆的流量在跑，iftop看，一台连接的是单位正在用的电脑的IP，但电脑没用kcptun连这个VPS，一台连接的是家里的IP，家里的电脑是关了的。
关闭服务器端的kcptun后VPS流量就正常了。
server.json
{
    "listen": ":2019",
    "target": "127.0.0.1:2017",
    "mode": "fast",
    "mtu": 1350,
    "sndwnd": 64,
    "rcvwnd": 512,
    "keepalive":10
}

**Comment by xtaci** [comment]
如何重现，服务器有心跳包，如果30秒～1分内没有数据，就不会有数据传输了。 #168 内讨论。

**Comment by triaqu** [comment]
今天重启服务后还没出现这个问题。
具体什么原因也不清楚，昨天在手机和电脑上都用过，其间在手机上出现未打开网络应用，但手机在wifi下一直显示有4M的流量，重启路由，切换ss接入点后一直都是大流量，甚至重启了手机，搞不清什么原因。
今天在VPS的监控上看到有流量才把服务重启后正常。也许是手机app引起的吧。
