### ISSUE TITLE
关于 json 配置文件的困惑

### ISSUE THREAD

**Issue by wang20150419** [xtaci/kcptun#182]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

现在 kcptun 用新版 速度稳定，看youtube 720p流畅。对个人而言，不需要花大价钱购买配置高的VPS，
非常满意，感谢作者的付出。

遇到的困惑是：
 @xtaci 提供了三个策略，如：
      策略1： 通过超时重传＋快速重传，响应速度优先（最大化响应时间）：
-mode manual -nodelay 1 -resend 2 -nc 1 -interval 20

这里的 mode，是 manual 模式，是不是可以理解为 fast2, fast 等模式，内部有不同的
      nodelay  resend  nc interval 等参数？
如果是这样的话，在 json  配置文件的 范例 里，有：
    {
         ...
          "mode": "fast2",
         ..
         "nodelay": 0,
         "interval": 40,
         "resend": 0,
         "nc": 0,.
          ...
    }
        按这个配置文件， fast2 和后面指定的nodelay  resend  nc interval 等参数，到底是谁在起作用呢？

**Comment by xtaci** [comment]
fast/fast2/fast3 相当于使用内置的 nodelay resend nc interval参数.
只有在-mode manual的时候，nodelay resend nc interval 才会生效。

**Comment by CuminLo** [comment]
@xtaci 这样的啊。一直理解错了
