### ISSUE TITLE
带宽利用率调优之谜

### ISSUE THREAD

**Issue by agentmario** [xtaci/kcptun#183]
服务端与客户端均为 0906 版，使用双向最高 100M 带宽 ipv6 链路连接 conoha 东京机房，当前客户端参数如下
```
-datashard 10 -parityshard 3 -conn 2 -mtu 1400 -sndwnd 512 -rcvwnd 512 -dscp 46 -autoexpire 60 -acknodelay -mode normal
```
我在双端尝试过 mtu 1350 ,snd/rcvwnd 512~2048, normal 到 fast2 模式，data/parityshart 70-30/10-3 等多种组合, 但带宽利用率始终只有 30% 左右，跑满 100M 带宽的时候 ss 的实际下行速率只有 30M 左右，请问这是否为 ipv6 特有问题

**Comment by xtaci** [comment]
acknodelay 在99.9%的情况下都不应该使用 mode 用fast2
