### ISSUE TITLE
Broken pipe error on linux server

### ISSUE THREAD

**Issue by mfat** [xtaci/kcptun#184]
I'm constantly getting "Broken Pipe" error message after running kcptun on my linux server.
I have shadowsocks and use the following command:

`./server_linux_amd64 -t "127.0.0.1:8388" -l ":4000"`

My shadowsocks config is as follows:

```
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "password":"xxxxxxx",
    "timeout":600,
    "method":"rc4-md5"
}
```

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Are you using the **same version** for both client & server
5. Did you correctly set the ***-target value, -t value	target server address (default: "127.0.0.1:12948")*** on the server side?
6. Can ```telnet target port``` successful?
7. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
