### ISSUE TITLE
mtu sndwnd rcvwnd三个参数的设置原则？

### ISSUE THREAD

**Issue by kuoruan** [xtaci/kcptun#185]
写了个服务端配置工具，但是作为一个数据网络方面的小白，对此三个参数的设置一直有疑问。当前想要增加一个自动计算参数的功能，特来向作者请教。
1.此三个参数的计算应考虑哪些因素？
2.如若本地带宽 50Mbps 上下对等，假定不考虑服务器带宽，且本地网络环境良好，本地到服务端的 ping 值为 200ms，详细的计算步骤？
3.mtu 的具体含义和确定方式？
4.当本地的 rcvwnd 和服务端的 sndwnd 不一致时，默认使用哪个？

**Comment by xtaci** [comment]
![946px-ethernet_type_ii_frame_format svg](https://cloud.githubusercontent.com/assets/2346725/18375541/d8f57588-7689-11e6-8ba0-3ea64c12ae56.png)

1. LINK MTU 是设备所能传输的最大的数据包大小（设备能力），通常为1500(以太帧), pppoe为1480, 这是link layer, IP头部通常为20B, UDP头部为8B, 因此
1480 －20 －8 ＝ 1452，这是UDP 数据的理论最大值。(1452里面包含KCP头部和数据)。
但不一定接入的帧大小就是最佳的传输大小，如果有封装／承载。 小一点是保险一点的。1400通常没有问题。 KCP里面的MTU是指 LINK MTU - IP HEADER - UDP HEADER的大小(1452最大)

2.  永远无法正确的估算带宽，链路中间任意一个网络设备都可能丢包。只能按照期望带宽来设定，比如我期望达到50Mbps， MTU=1400, PING=200ms 的情况下。
```
BDP = 50Mbps*200ms = 10Mb = 1MB    (这是socket buffer至少应该保障的大小)
对应到WIND =  1MB/1400 ～= 1024 (packets)
```
这是不丢包的情况下。
这个速度还需要减去FEC的包的的数据量
主页有计算方式。

3. 当本地的 rcvwnd 和服务端的 sndwnd 不一致时，哪个小以哪个为准。

**Comment by kuoruan** [comment]
上面说到了 socket buffer 计算出来是 1MB，那倘若我保持默认为 4MB，那么 WIND 就应该为 4MB/MTU ？

**Comment by xtaci** [comment]
不是， window 和socket buffer没有关系， 也不是没有关系， socketbuffer 必须大于window才不会成为瓶颈。

**Comment by kuoruan** [comment]
倘若我使用上述的窗口大小，发现产生了大量的重传，浪费了大量的流量，我应该如何调整呢？单方面的调整接收窗口？

**Comment by xtaci** [comment]
是的，只能这样， 而且你看到的ping值远低于真实的UDP丢包率。

**Comment by PHCSJC** [comment]
好吧，我给懒人做个最不精确的总结：
50M带宽：服务器的sndwnd和客户端rcvwnd都设置为1024
100M带宽：服务器的sndwnd和客户端rcvwnd都设置为2048
200M带宽：服务器的sndwnd和客户端rcvwnd都设置为4096
以此类推，除非你特懒就按此来，否则请按正确的方法推算。
