### ISSUE TITLE
请问ios有运行的可能吗？

### ISSUE THREAD

**Issue by JamesPe725** [xtaci/kcptun#186]
你好，请问越狱的iOS有可能使用吗？

**Comment by shutup** [comment]
越狱手机，按道理是可以的，不知道会不会有人写个包装出来。或者运行在路由器这个选择不错。

**Comment by choicky** [comment]
iOS 9 提供了相应的接口，理论上可以存在iOS客户端了。

**Comment by gaoyifan** [comment]
kcptun只要支持udp、tcp socket就能运行啊，与是否越狱没什么关系吧

**Comment by zpfsqzyl** [comment]
但是目前没有听说开发。。。

**Comment by gaoyifan** [comment]
go语言本来就支持iOS平台嘛

**Comment by kmahyyg** [comment]
越狱后通过终端运行darwin prebuilt版本，我的touch4 ios6.16可用

**Comment by Nobiel** [comment]
求教越狱后如何通过终端运行darwin prebuilt版本

**Comment by kmahyyg** [comment]
去cydia安装terminal.
'''su'''
  '''nohup /folder/kcpclient -c ./config.json '''

2016年11月6日 21:14，"Nobiel" <notifications@github.com>写道：

**Comment by zpfsqzyl** [comment]
请问为什么要用su命令？不用su不行吗？
2016年11月7日 上午1:53，kmahyyg <notifications@github.com>写道：去cydia安装terminal.

'''su'''

  '''nohup /folder/kcpclient -c ./config.json '''



2016年11月6日 21:14，"Nobiel" <notifications@github.com>写道：

**Comment by kmahyyg** [comment]
linux/Darwin下需要su权限以打开socket。否则会提示: socket : permission denied.

2016年11月7日 07:42，"zpfsqzyl" <notifications@github.com>写道：

**Comment by Nobiel** [comment]
谢谢。请问darwin prebuilt版本是什么版本，不知是release里面的哪个文件？

**Comment by shutup** [comment]
@Nobiel IOS真机都是arm的。Mac是darwin

**Comment by Nobiel** [comment]
@shutup 抱歉，还是有点不明白。所以我该从哪里下载客户端？itouch用darwin prebuilt版本是什么意思，iPhone要怎样做呢？下载运行kcptun-darwin-amd64、kcptun-linux-arm？

**Comment by zpfsqzyl** [comment]
iPhone是arm或者arm64

**Comment by gaoyifan** [comment]
@Nobiel  需要自己编译
```
export GOOS=darwin
export GOARCH=arm64
```
然后`go build`

不过我在测试的时候，darwin-arm可以正常编译，darwin-arm64报错：

```
# _/Users/yifan/Workspace/go/kcptun/client
warning: unable to find runtime/cgo.a
/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /var/folders/x9/12l0nc71725g5y0p7t3mzlbc0000gn/T/go-link-482520878/go.o, file was built for unsupported file format ( 0xCF 0xFA 0xED 0xFE 0x0C 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /var/folders/x9/12l0nc71725g5y0p7t3mzlbc0000gn/T/go-link-482520878/go.o
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
go version go1.7.3 darwin/amd64
Darwin 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64
```
