### ISSUE TITLE
使用流量控制出现错误提示

### ISSUE THREAD

**Issue by sendmail** [xtaci/kcptun#188]
tc.sh
tc qdisc del dev venet0 root
tc qdisc add dev venet0 root handle 1: htb
tc class add dev venet0 parent 1: classid 1:1 htb rate 32mbit
tc filter add dev venet0 protocol ip parent 1:0 prio 1 handle 10 fw flowid 1:1
iptables -t mangle -A POSTROUTING -o venet0  -j MARK --set-mark 10

vps是ovz的网卡是venet0

 RTNETLINK answers: No such file or directory
We have an error talking to the kernel

没有这样的文件？是需要自行建立还是什么问题？

**Comment by xtaci** [comment]
不清楚ovz能不能用tc

**Comment by sendmail** [comment]
@xtaci 那还有别的什么方法可以来控制流量吗？

**Comment by xtaci** [comment]
降窗

**Comment by dolphinpaopao** [comment]
我试过好几家，OVZ不能用TC，因为内核。
