### ISSUE TITLE
session scavenged

### ISSUE THREAD

**Issue by jiawei-zheng** [xtaci/kcptun#189]
版本20160912
服务端参数：server_linux_amd64 -l :29900 -t 127.0.0.1:5288 -key “test” -sndwnd 2048 -rcvwnd 2048 -mode manual -nodelay 0 -resend 0 -nc 1 -interval 40 -nocomp -dscp 46 -crypt aes-128 -datashard 70 -parityshard 30 > kcptun.log 2>&1 &

客户端参数：client_windows_amd64.exe" -l :9527 -r 104.251.228.201:29901 -key "test" -crypt aes-128 -nocomp -datashard 70 -parityshard 30 -sndwnd 256 -rcvwnd 2048 -dscp 46 -mode manual -nodelay 0 -interval 40 -nc 1

客户端日志：
2016/09/13 20:58:04 stream closed
2016/09/13 20:58:04 stream closed
2016/09/13 20:58:04 stream closed
2016/09/13 20:58:05 session scavenged

服务端日志：
2016/09/13 08:26:15 version: 20160912
2016/09/13 08:26:16 listening on: [::]:29901
2016/09/13 08:26:16 target: 127.0.0.1:8989
2016/09/13 08:26:16 encryption: aes-128
2016/09/13 08:26:16 nodelay parameters: 0 40 0 1
2016/09/13 08:26:16 sndwnd: 2048 rcvwnd: 2048
2016/09/13 08:26:16 compression: false
2016/09/13 08:26:16 mtu: 1350
2016/09/13 08:26:16 datashard: 70 parityshard: 30
2016/09/13 08:26:16 acknodelay: false
2016/09/13 08:26:16 dscp: 46
2016/09/13 08:26:16 sockbuf: 4194304
2016/09/13 08:26:16 keepalive: 10
2016/09/13 08:31:22 remote address: 218.17.158.85:57336
2016/09/13 08:31:22 remote address: 218.17.158.85:57334
2016/09/13 08:32:22 broken pipe
2016/09/13 08:32:22 broken pipe

**Comment by LiR1cky** [comment]
我也碰到了这个问题，重启服务器端可破所以我现在的临时解决方案是在crontab里设置每半小时重启一次服务器端。
但确实是在引入autoexpire和换成SMUX之后这个问题变得显著了，症状是客户端持续的stream closed/session scavenged, 而服务器端日志在这段时间内没有更多的状态更新了。

**Comment by lemondog** [comment]
确实经常这样

**Comment by xiaobailong24** [comment]
#210 防火墙增加UDP设置
