### ISSUE TITLE
下载大文件的同时，打开网页速度很慢？

### ISSUE THREAD

**Issue by kokutoukiritsugu** [xtaci/kcptun#190]
我的参数
client_windows_amd64.exe -l :12948 -r %ip%:29900 -key %key% -mode manual -nodelay 0 -resend 0 -nc 1 -interval 40 -dscp 46 -nocomp -mtu 1400 -crypt aes-128 -datashard 27 -parityshard 3

版本是今天的 
kcptun-windows-amd64-20160912.tar.gz

服务器用的python版ssr或者go版本ss
客户端go版本ss或者c#版本ssr。

在下载大文件的同时，打开网页的速度就很慢。
是我参数有问题吗？感觉像隧道被占用了一样。

**Comment by choicky** [comment]
我就是简单地用了-mode fast3而已，虽然不能最大化vps网速，但目前已经满足了，1080P能流畅播放，暂时没发现什么问题。
