### ISSUE TITLE
关于Windows客户端的2个Issues

### ISSUE THREAD

**Issue by swordgreen** [xtaci/kcptun#192]
在Windows 10 64bit操作系统上，最近使用client_windows_amd64.exe（20160912版本）发现两个问题。
1. 将笔记本休眠后再开机，client_windows_amd64.exe 100%奔溃，需要重新启动。
2. 每次在启动client_windows_amd64.exe后，需要等待几分钟才开始有流量，但之后保持正常。

我利用kcptun对shadowsocks进行加速，shadowsocks工作一切正常。kcptun的相关参数如下：
    "crypt": "salsa20",
    "mode": "manual",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 350,
    "rcvwnd": 350,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 0,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 1,
    "interval": 20,
    "resend": 0,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
不知是我的个例问题还是普遍问题。欢迎大家讨论。

**Comment by xtaci** [comment]
这个是没有网络情况下正常退出，只不过退出的消息有点吓人，当成crash了。
怎么改善还不清楚。

**Comment by swordgreen** [comment]
谢谢回复。能保持无网络的情况下不退出吗？这样不用每次打开笔记本都重新启动kcptun客户端。还有那个启动后需要等待一段时间可能是什么原因呢？我设定的为开机自动启动，结果每次开机后都需要等好几分钟才能开始使用网络。
谢谢开发这么好用的加速软件！

**Comment by xtaci** [comment]
非常容易的，但是我还不确定这样好还是不好。

**Comment by swordgreen** [comment]
我认为没有网络的情况下应该保持程序运行，等网络联通后自动工作。一般的服务类程序不都是这样吗？如果意外断网，还必须要重启程序，这个有点感觉不合常理。

**Comment by xtaci** [comment]
嗯，如果作为服务器看是有道理的，我考虑下

**Comment by swordgreen** [comment]
嗯，如果是部署在路由器上这点就很重要了，路由器拨号上网，掉线重拨的频率很高。

**Comment by xtaci** [comment]
[kcptun-darwin-386-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478703/kcptun-darwin-386-20160918.tar.gz)
[kcptun-darwin-amd64-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478704/kcptun-darwin-amd64-20160918.tar.gz)
[kcptun-freebsd-386-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478705/kcptun-freebsd-386-20160918.tar.gz)
[kcptun-freebsd-amd64-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478708/kcptun-freebsd-amd64-20160918.tar.gz)
[kcptun-linux-386-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478710/kcptun-linux-386-20160918.tar.gz)
[kcptun-linux-amd64-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478706/kcptun-linux-amd64-20160918.tar.gz)
[kcptun-linux-arm-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478707/kcptun-linux-arm-20160918.tar.gz)
[kcptun-windows-386-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478709/kcptun-windows-386-20160918.tar.gz)
[kcptun-windows-amd64-20160918.tar.gz](https://github.com/xtaci/kcptun/files/478711/kcptun-windows-amd64-20160918.tar.gz)

@swordgreen 你可以试下这个，如果没问题，会在下个release中加入此特性。

**Comment by xtaci** [comment]
@swordgreen 这个问题我看了下，没有想的那么简单，如果要加入不断线的特性，cpu使用率会高不少。

**Comment by xtaci** [comment]
@swordgreen 一个简单的workaround
```
$ cat start.sh
#!/bin/sh
while true; do
	./client_darwin_amd64 -r xxxxxxxxx
	sleep 1
done
```

**Comment by xtaci** [comment]
[kcptun-darwin-386-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479165/kcptun-darwin-386-20160919.tar.gz)
[kcptun-darwin-amd64-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479166/kcptun-darwin-amd64-20160919.tar.gz)
[kcptun-freebsd-386-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479167/kcptun-freebsd-386-20160919.tar.gz)
[kcptun-freebsd-amd64-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479170/kcptun-freebsd-amd64-20160919.tar.gz)
[kcptun-linux-386-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479169/kcptun-linux-386-20160919.tar.gz)
[kcptun-linux-amd64-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479168/kcptun-linux-amd64-20160919.tar.gz)
[kcptun-linux-arm-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479172/kcptun-linux-arm-20160919.tar.gz)
[kcptun-windows-386-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479171/kcptun-windows-386-20160919.tar.gz)
[kcptun-windows-amd64-20160919.tar.gz](https://github.com/xtaci/kcptun/files/479173/kcptun-windows-amd64-20160919.tar.gz)

想到一个简单的办法，试下这个版本。

**Comment by swordgreen** [comment]
@xtaci 兄更新好快。我去测试一下新版。随后报告。

**Comment by swordgreen** [comment]
@xtaci 经过测试，问题已经解决！ 断网、休眠、睡眠后客户端不会退出，服务器端重启以及客户端重启后恢复网络的速度也很快！再次感谢做出的努力！

**Comment by xtaci** [comment]
好的，放入release了。
