### ISSUE TITLE
最近一直出现这个错误在公司跟家里不同的电脑都一样 keepalive failed: i/o deadline reached

### ISSUE THREAD

**Issue by huang5307** [xtaci/kcptun#193]
一直出现最底下的错误，似乎是这两天才开始的，之前使用正常，请问如何解决？
*************************** begin ***************************
2016/09/16 10:11:20 version: 20160830
2016/09/16 10:11:20 listening on: [::]:8989
2016/09/16 10:11:20 encryption: none
2016/09/16 10:11:20 nodelay parameters: 1 20 2 1
2016/09/16 10:11:20 remote address: 52.74.175.38:29900
2016/09/16 10:11:20 sndwnd: 1024 rcvwnd: 1024
2016/09/16 10:11:20 compression: true
2016/09/16 10:11:20 mtu: 1350
2016/09/16 10:11:20 datashard: 10 parityshard: 3
2016/09/16 10:11:20 acknodelay: false
2016/09/16 10:11:20 dscp: 0
2016/09/16 10:11:20 sockbuf: 4194304
2016/09/16 10:11:20 keepalive: 10
2016/09/16 10:11:20 conn: 1
2016/09/16 10:11:20 autoexpire: 60
2016/09/16 10:12:00 [ERR] yamux: keepalive failed: i/o deadline reached
2016/09/16 10:12:00 [ERR] yamux: Failed to read header: broken pipe

**Comment by dfdragon** [comment]
参考一下 #34 #53 #65 。另外，先更新一下c/s两端的版本，现在的最新版本是v20160912，还有，修改一下你的内容，IP地址就不要贴了：）
