### ISSUE TITLE
dial tcp 127.0.0.1:12948: getsockopt: connection refused

### ISSUE THREAD

**Issue by weiyu99** [xtaci/kcptun#198]
1. Netgear R700 with DD-WRT v3.0-r27365M (06/18/15) kongac
2. server_linux_arm5 version: 20160919
3. kcptun server 设置：
   {
   "listen": ":29900",
   "target": "127.0.0.1:12948",
   "key": "wiYaYo99",
   "crypt": "aes",
   "mode": "fast2",
   "mtu": 1350,
   "sndwnd": 1024,
   "rcvwnd": 1024,
   "nocomp": false
   }
4. error message on server side:

root@DD-WRT:/jffs# ./server_linux_arm5 -c kcp-server.json 
2016/09/22 05:28:28 version: 20160919
2016/09/22 05:28:28 listening on: 0.0.0.0:29900
2016/09/22 05:28:28 target: 127.0.0.1:12948
2016/09/22 05:28:28 encryption: aes
2016/09/22 05:28:28 nodelay parameters: 1 20 2 1
2016/09/22 05:28:28 sndwnd: 1024 rcvwnd: 1024
2016/09/22 05:28:28 compression: true
2016/09/22 05:28:28 mtu: 1350
2016/09/22 05:28:28 datashard: 10 parityshard: 3
2016/09/22 05:28:28 acknodelay: false
2016/09/22 05:28:28 dscp: 0
2016/09/22 05:28:28 sockbuf: 4194304
2016/09/22 05:28:28 keepalive: 10
2016/09/22 05:28:57 remote address: 电信IP:60605
2016/09/22 05:29:15 dial tcp 127.0.0.1:12948: getsockopt: connection refused
2016/09/22 05:29:16 dial tcp 127.0.0.1:12948: getsockopt: connection refused
2016/09/22 05:29:16 dial tcp 127.0.0.1:12948: getsockopt: connection refused
2016/09/22 05:29:17 dial tcp 127.0.0.1:12948: getsockopt: connection refused
2016/09/22 05:29:17 dial tcp 127.0.0.1:12948: getsockopt: connection refused
2016/09/22 05:29:17 dial tcp 127.0.0.1:12948: getsockopt: connection refused
2016/09/22 05:29:18 dial tcp 127.0.0.1:12948: getsockopt: connection refused

有人知道这是什么问题吗？

谢谢！

**Comment by braveguywallce** [comment]
你在路由器上部署server端？

**Comment by weiyu99** [comment]
@braveguywallce 是呀

**Comment by braveguywallce** [comment]
为什么在路由器上部署server端？你打算怎么用kcptun?

**Comment by weiyu99** [comment]
路由器放台湾，上面跑 kcptun + ss

**Comment by ANDI-Mckee** [comment]
arm架构啊，kcptun放在服务器没错。
不过这个运行命令好像和官方的不一样，官方是：./server_linux_amd64 -t "127.0.0.1:8388" -l ":4000" -mode fast2

**Comment by weiyu99** [comment]
不是命令执行问题，我在 router 上面有跑 ss-server 端口 1234, 我把 target 改成 "127.0.0.1:1234" 也是报同样的错。最后改成 "router ip: 1234" 才解决的，不懂为何 127.0.0.1 就不行。

**Comment by RubberBoy** [comment]
应该是监听端口设的是 ip:1234,而不是 0.0.0.0:1234

**Comment by gitbufenshuo** [comment]
监听 127.0.0.1 只有在你本机 connect 127.0.0.1 :1234 , 在别的地方如何 ping 127.0.0.1 。写成 0.0.0.0 就好了，就是监听所有本机 IP了。在另一台服务器上就可以 ping 通了。

**Comment by zeanzhou** [comment]
More specifically, it's due to the misconfiguration of ss. The config file of ss should be

>{
    "server":"0.0.0.0",
    "server_port":PORT,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":PASSWORD,
    "timeout":300,
    "method":"rc4-md5"
}


 Then your ss is listening to all IPs attached to your VPS, and now you are able to set target in kcptun like 

> 127.0.0.1:PORT
