### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by zwb-ict** [xtaci/kcptun#2]
@xtaci 您好，我在

```
426 packets transmitted, 359 received, 15% packet loss, time 425007ms
rtt min/avg/max/mdev = 343.108/485.715/644.402/77.218ms
```
的网络环境（欧洲aws实时发送数据=>北京阿里云收到后返回200，traceroute -I 显示18跳）下进行测试。

client端部署在欧洲aws上，连接 client端的是4个node进程，keepalive的超时时间设置为2分钟。
server端部署在国内阿里云上，阿里云机器的带宽是10M，server端转发给nginx（server和nginx在同一台机器），nginx直接返回200。

4个node进程刚启动后，其中三个进程的套接字会涨到200左右，然后回落到20，另一个稳定在40左右。
之后client出现下面信息：

```
2016/03/19 11:03:09 read tcp 127.0.0.1:54321->127.0.0.1:46589: use of closed network connection
2016/03/19 11:03:10 stream **opened**
2016/03/19 11:03:10 <nil>
2016/03/19 11:03:10 stream closed
2016/03/19 11:03:10 read tcp 127.0.0.1:54321->127.0.0.1:46590: use of closed network connection
2016/03/19 11:03:11 stream opened
2016/03/19 11:03:11 <nil>
2016/03/19 11:03:11 stream closed
2016/03/19 11:03:11 read tcp 127.0.0.1:54321->127.0.0.1:46591: use of closed network connection
2016/03/19 11:03:11 stream opened
2016/03/19 11:03:11 <nil>
2016/03/19 11:03:11 stream closed
2016/03/19 11:03:11 read tcp 127.0.0.1:54321->127.0.0.1:46592: use of closed network connection
2016/03/19 11:03:12 stream opened
2016/03/19 11:03:12 <nil>
2016/03/19 11:03:12 stream closed
2016/03/19 11:03:12 read tcp 127.0.0.1:54321->127.0.0.1:46593: use of closed network connection
2016/03/19 11:03:12 <nil>
2016/03/19 11:03:12 stream closed
2016/03/19 11:03:12 read tcp 127.0.0.1:54321->127.0.0.1:46594: use of closed network connection
2016/03/19 11:03:12 stream opened
2016/03/19 11:03:12 <nil>
2016/03/19 11:03:12 stream closed
```

查看套接字，前三个进程的套接字还是稳定在20，另一个由40涨到200左后，最后降到20.，同时4个node 程序无法向client发送数据，出现异常信息
```
socket hang up
```
node 进程由pm2 守护，程序对异常有处理，当发生这类异常时，会尝试重新发送，但一直没能成功。

发送的数据大小平均为**52981**字节。

请问：
1. 发生use of closed network connection的原因是什么，如何解决？（我之前加了连接池，可以避免这个错误的发生，但觉得不是最好的解决方案）；
2. 在这样的网络环境下，kcp的一些参数比如像窗口size的大小，怎样设置比较合理，依据是什么；
3. 正常发送的数据大小大约是211924（测试时的4倍）字节，这样的数据大小kcp调整参数后，是否可以发送？（我尝试过2倍，发送不成功，卡住了。具体原因还没查）

期待您的回复，非常感谢！

**Comment by zwb-ict** [comment]
@xtaci 抱歉，忘记描述系统信息和go的版本了：

**Go version**: 1.6 当前官方链接最新版；

**AWS OS info**: Linux version 3.10.0-229.el7.x86_64 (mockbuild@x86-035.build.eng.bos.redhat.com) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-7) (GCC) ) #1 SMP Thu Jan 29 18:37:38 EST 2015

**阿里云 OS info**：
Linux version 3.10.0-123.9.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Thu Nov 6 15:06:03 UTC 2014

**AWS limits.conf**
```
#*               soft    core            0
#*               hard    rss             10000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#@student        -       maxlogins       4

# End of file
*        hard    nofile           655350
*        soft    nofile           655350
root        soft    nofile           655350
root        hard    nofile           655350
```

**阿里云 limits.conf**
* soft nofile 65535
* hard nofile 65535

**Comment by xtaci** [comment]
请问：

> 1. 发生use of closed network connection的原因是什么，如何解决？（我之前加了连接池，可以避免这个错误的发生，但觉得不是最好的解决方案）；

首先，kcptun的这种多client的使用方式，我并不推荐，请注意README中的一段:
openvpn client -> kcptun client -> kcptun server -> openvpn server (最佳实践)
ssh tunnel client -> kcptun client -> kcptun server -> sshd (推荐应用)
browser socks5 -> kcptun client -> kcptun server -> ssh -D socks5 server (简易)

你的用法属于简易方式，即短链接为主的连接，必然会出现很多close消息，我的推荐是单链接，即ssh -D 在client端执行，一对kcptun c/s最好只承载一条tcp连接。

> 2. 在这样的网络环境下，kcp的一些参数比如像窗口size的大小，怎样设置比较合理，依据是什么；

窗口大小的设置，以fast模式来说，主要的依据是，上行流量带宽，下行流量带宽。
比如上行128KB/s流量，单个数据包平均大小1000B， 那么上行窗口大小为128即可占满所有带宽。
下行同理。

> 3.  正常发送的数据大小大约是211924（测试时的4倍）字节，这样的数据大小kcp调整参数后，是否可以发送？（我尝试过2倍，发送不成功，卡住了。具体原因还没查）

kcp-go 的 sess.go处理过 大数据包的分隔，详见Write函数， 原则上，接收端的窗口大小必须大于单个数据包的大小，否则可能出现分片无法整合，无法接收完整数据而卡住。

**Comment by zwb-ict** [comment]
谢谢 @xtaci，还想请教一下关于数据边界的问题

一、数据边界完全由自己的client和server想办法解析是吗？

1.  tcp这块从
```
			bts := <-ch_buf
			n, err := conn.Read(bts)
```
及下面的
```
			select {
			case ch <- bts:
```

还有
```
		case bts, ok := <-ch_client:
			if !ok {
				return
			}
			if _, err := conn_peer.Write(bts); err != nil {
```
来看在TCP传输这块是没有做数据边界的保护。

2. 在sess.go的write函数中
```
	for {
		if len(b) <= max { // in most cases
			s.kcp.Send(b)
			break
		} else {
			s.kcp.Send(b[:max])
			b = b[max:]
		}
	}
```
如果进入else分支也无法保证数据边界。

二、对于发送长度不固定的情况，数据边界的保证怎样做比较高效呢？

**Comment by xtaci** [comment]
这个通常来说，是两个字节的头部，表示长度， 后面是数据。用io.ReadFull可以完整读取。
具体可以参考gonet2的处理方式:

https://github.com/gonet2/agent/blob/master/src/agent/main.go#L90

**Comment by zwb-ict** [comment]
谢谢@xtaci。
