### ISSUE TITLE
使用kcp加速流量稍大时内网主机ping内网网关（mt7620路由器）频繁丢包且延迟高

### ISSUE THREAD

**Issue by ChapterEstatic** [xtaci/kcptun#201]
内网raspberry pi上跑kcp，路由器跑ss-libev指向pi，当使用kcp流量稍大（500-600k的样子），ping 内网网关丢包严重，延迟也从<1ms  100-200ms来回跳，在播放一个u2b视频时打开第二个u2b视频会等半天都加载不出页面
server配置
nohup /root/kcptun/server_linux_386 -l :554 -t 127.0.0.1:443 -crypt salsa20 -key *** -sndwnd 2048 -rcvwnd 2048 -mode manual -nodelay 0 -resend 0 -nc 1 - interval 40 -dscp 46 -nocomp -mtu 1400 -crypt salsa20 -datashard 5 -parityshard 2 > kcptun.log 2>&1 &
client配置
nohup /root/kcptun/client_linux_arm7 -l :12948 -r *.*.*.*:554 -key *** -sndwnd 64 -rcvwnd 512 -mode manual -nodelay 0 -resend 0 -nc 1 - interval 40 -dscp 46 -nocomp -mtu 1400 -crypt salsa20 -datashard 5 -parityshard 2 > kcptun.log 2>&1 &
路由器配置ss-libev的加密为chacha20，不使用kcp加速时，路由上直接通过ss-libev连接server上的ss-server看u2b时，ping 路由器正常

**Comment by xtaci** [comment]
注意防火墙，wifi信号强度，干扰。

**Comment by ChapterEstatic** [comment]
设备均有线连接，路由器是openwrt 15.05，之前是自带的ss-libev 2.2.2版本，今天换了个最新的2.5.3-1似乎情况好了很多，我再研究研究

**Comment by ChapterEstatic** [comment]
效果很不错！25M广电网，超售hk softlayer vps都能u2b 1W-1W5Kbps
