### ISSUE TITLE
服务端经常断,必须重启才能重新使用 ( DSCP?)

### ISSUE THREAD

**Issue by lengyue524** [xtaci/kcptun#203]
{
    "listen": ":29900",
    "target": "127.0.0.1:443",
    "key": "mykey",
    "crypt": "salsa20",
    "mode": "fast2",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}
上面是我的配置文件。
机器配置，ubuntu系统 512m内存。
经常使用没多久就无法连接了。只能重启。

**Comment by mhqschen** [comment]
最近也发现了这个问题

**Comment by zhg-em** [comment]
是有这个问题，但过一段时间又会恢复。

**Comment by bubbless** [comment]
我搬瓦工也是，尤其是WIFI切换到4G，不可用的几率非常高。重启kcptun服务后才正常。

**Comment by PterX** [comment]
![tr](https://cloud.githubusercontent.com/assets/1871048/18983592/72db72c8-8720-11e6-9428-ce9f05621241.png)

最近大家要慎用了，最近同样出现断流现象。用udp追踪发现直接被阻断了，tcp正常。
kcp开启了加密，以及各种参数调整。用了一会就会被阻断。应该是被加入检测了。

**Comment by xtaci** [comment]
电信是这样的

**Comment by bubbless** [comment]
WIFI环境有电信和联通，基本即连即用，但是WIFI切换到China Unicom 4G 就会出现无法连接的情况，一直4G状态基本都可用，到特定的基站附近连原版SS都无法连接。

**Comment by xtaci** [comment]
这个问题有可能和DSCP有关，可以尝试默认值0

**Comment by mhqschen** [comment]
发现访问大量图片的网页，会出发这个断流，概率100%。
重启kcptun后恢复。

客户端：
![2016-10-02 08 36 18](https://cloud.githubusercontent.com/assets/9138710/19017804/b8cc3234-887b-11e6-9c47-ff447ee44c93.png)

服务器：
![2016-10-02 08 36 35](https://cloud.githubusercontent.com/assets/9138710/19017805/c4174598-887b-11e6-9c95-96611328575c.png)

客户端错误：
![2016-10-02 08 20 41](https://cloud.githubusercontent.com/assets/9138710/19017806/ca0a68c2-887b-11e6-9bac-8138ef3b366f.png)

**Comment by xtaci** [comment]
不要用标准端口，换成其他的。

**Comment by bubbless** [comment]
[https://zh.wikipedia.org/wiki/TCP/UDP端口列表](https://zh.wikipedia.org/wiki/TCP/UDP%E7%AB%AF%E5%8F%A3%E5%88%97%E8%A1%A8)
最好用官方的UDP >1024
别人测试443也是不错的选择。

**Comment by braveguywallce** [comment]
我前面用salsa20，有几天网速突然降了很多，以为是VPS人为限制UDP快速发包导致，去问了下，结果VPS服务商根本没动过。我把端口改了，加密算法换成aes-192，目前已经用了一个多礼拜，kcptin一切正常。电信网络。

**Comment by xtaci** [comment]
有个issue说的随机化端口是个很有趣的idea.

**Comment by zhg-em** [comment]
尝试将DSCP改成0，修改端口，将加密算法换成aes-192等，但结果是然并卵。
vps是搬瓦工的，是不是服务商有什么限制？

**Comment by gatalon** [comment]
有这样的情况，上海有线，时断时续。
国庆有在恩山论坛看到万恶的政府有关于加强管制的消息，可能是真的了。

**Comment by braveguywallce** [comment]
@zhg-em 我用的VPS很不错，服务和支持很好，当然价格也比搬瓦工贵很多，和他们确认过，他们对kcp协议没有任何网速的限制，也没有放置任何speed limiter在我的主机上，我换成aes-192加密算法后，迄今快两周了，一切正常，建议你联系下VPS，因为搬瓦工是共享带宽，而且超售严重，可能是VPS做的限制，未必就是国内的ISP的问题。

**Comment by braveguywallce** [comment]
@gatalon 不要见风就是雨，本来东方有线就是最差的网络之一，不建议使用。你可以用traceroute -U -p ports of kcptun 查下你的ISP有没有对你特定端口的udp通讯阻断，另外你的vps供应商有没有对kcp这样快速发包的协议有没有限制，我这边查下来，国内三大ISP迄今并未采取什么阻断UDP通讯的特别措施，用下来正常的，多虑了。

**Comment by gatalon** [comment]
@braveguywallce执行命令到一个中国电信骨干网的ip然后后面就没有了。

**Comment by baggiogogo** [comment]
昨天一台VPS用KCPTUN突然连接不上，前天都还可以正常使用，表现形式的是两端连接一切正常，可以看见连接信息，open close等等，但就是无法正常上网，思来想去，换443试验，可以正常使用，但好景不长，过了没多久又出现一样的情况。应该被精准阻断了，好在狡兔三窟，没有深究，这台就装锐速作为备用了。HOHO

**Comment by braveguywallce** [comment]
@baggiogogo 我觉得还是要尽量严谨些才好，不能轻易下结论说被GFW BLOCK。
今天我在外地，蹭邻居的网，他是电信10M的，等于和他共享带宽，还被我占掉了这么多，LINUX LAPTOP， SS + KCPTUN都在本机上跑。
![2016-10-04 21 11 51](https://cloud.githubusercontent.com/assets/5782014/19075448/897f6570-8a77-11e6-81da-a579bfcdb0cc.png)

**Comment by baggiogogo** [comment]
Video ID:wfoI-m-3vOk
Dimensions:854 x 480
Resolution:1920 x 1080@30
Volume:12%
Stream Host:r3---sn-npo7zn7z
Stream Type:https
CPN:bimo1dOoqqJUb_JV
Mime Type:video/webm; codecs="vp9"
DASH:yes (248/251)
Connection Speed:10212 Kbps
Buffer Health:39.5 s
Network Activity:1148 KB
Dropped Frames:
10M联通光纤，三台不同国家的VPS，经过一段时间对KCPTUN的学习了解，每一台都可以调到相同的水准，峰值13000多youtube连接速度，可以满足我任何时段1080的需求。
所以，请相信我绝对不会犯比如被防火墙挡掉的低级错误，一家之言，总之大家还是多留个心，温柔的使用。

**Comment by cmdlot** [comment]
我也遇到了，有两台，一台搬瓦工，另一台是另一家的，搬瓦工正常，另一家就是头一天晚上用了，第二天晚上就不能用了，没看日志和top，我是个简单不爱动脑不折腾的人，为了不动脑筋，就是粗暴的设置成了每天下班之前自动重启，回去根没有问题一样用，没烦恼，妥妥的

**Comment by huadi016** [comment]
@cmdlot 我找了好久没找到每天重启的，可否给我分享一个。

**Comment by cmdlot** [comment]
定时任务 @huadi016

**Comment by huadi016** [comment]
@cmdlot 重启系统吗?具体怎么实现，我小白

**Comment by cmdlot** [comment]
yum install ntp
cp -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

yum install vixie-cron
yum install crontabs
chkconfig --level 35 crond on

crontab -e
复制下面内容 ( 30 17 代表 17:30 )
30 17 * * * /sbin/shutdown -r now


可查看服务器运行时间：
uptime 

我也是小白，别再问我了 怕暴露智商
