### ISSUE TITLE
luci-app-kcptun 开发完成，欢迎测试反馈

### ISSUE THREAD

**Issue by kuoruan** [xtaci/kcptun#204]
[https://github.com/kuoruan/luci-app-kcptun/releases](https://github.com/kuoruan/luci-app-kcptun/releases)

感谢作者的 Log 支持，没 Log 选项支持的话我还不好办。。

**Comment by xtaci** [comment]
wow!!!

**Comment by baggiogogo** [comment]
谢谢@xtaci以及@kuoruan的努力，必须赞。

**Comment by braveguywallce** [comment]
辛苦啦！点赞！
只是我手头的两个路由器还是NETGEAR WNDR4300，可能拖不动，希望其它有更强悍路由器的同学多多测试

**Comment by JimLee1996** [comment]
厉害呢~

**Comment by choicky** [comment]
谢谢@xtaci以及@kuoruan的努力，必须赞。

我路由器安装的是 merlin 。merlin 目前有个插件是搭配kcp-server的。但尚未有搭配ss的kcptun。

**Comment by w12928293** [comment]
真是个好消息，看来我的4300又能重出江湖了

**Comment by wxyzh** [comment]
@choicky @jannson 
koolshare 的梅林改版 要找小宝去弄了，现在固件里带的是[jannson/kcptun](https://github.com/jannson/kcptun)

**Comment by ninggu2008** [comment]
试了，很好用。可惜我路由性能太差。。
