### ISSUE TITLE
关于终端的输出

### ISSUE THREAD

**Issue by dfdragon** [xtaci/kcptun#205]
做了一个简单的测试如下：
```
package main

import (
	"fmt"
	"log"
	"os"
)

func main() {
	log.SetOutput(os.Stdout)
    fmt.Printf("hello, world\n")
	log.Println("hello, test\n")
}
```
如果注释掉log.SetOutput(os.Stdout)，只能捕获到hello, world的输出；去掉注释，hello, world和hello, test均能捕获（如果在终端中运行，无论怎样都能输出这两行），截图如下：

![log](https://cloud.githubusercontent.com/assets/9766935/18839301/1260fdae-843d-11e6-9e97-44a65f1e1211.png)

**Comment by dfdragon** [comment]
利用源码重新编译了一次kcptun客户端，只在main函数的第一行加入了log.SetOutput(os.Stdout)，编译后运行的效果如下图，现在不用2>&1也可以捕获到控制台的输出，并且可以准确获取进程PID。不知道加入这一行后是否会影响程序的其它部分，希望通盘考虑后能够加入，这样就能解决osx下的一个大问题。
![kcptun](https://cloud.githubusercontent.com/assets/9766935/18883575/5bf590ae-8516-11e6-9504-b71aabd69b8c.png)

**Comment by baggiogogo** [comment]
辛苦了

**Comment by xtaci** [comment]
没问题的

**Comment by wxyzh** [comment]
只是把以前输出到stderr的内容，改成了输出到stdout。
能否把正常的info输出到stdout，把一些报错输出到stderr？

**Comment by xtaci** [comment]
你说的这种属于分级log , loglevel

**Comment by dfdragon** [comment]
@xtaci 我自己写了一个popen函数替代原有的popen，这样我可以利用dup2将fork出的子进程stderr与stdout关联，程序已经测试成功，你那边不改也可以了
