### ISSUE TITLE
kcptun osx客户端配置管理

### ISSUE THREAD

**Issue by dfdragon** [xtaci/kcptun#207]
osx版的客户端配置管理软件发布第一版，请在[这里](https://github.com/dfdragon/kcptun_xclient/releases)下载。

软件基本照搬windows版的实现，但部分功能还在完善中，正在逐步添加，希望大家提出意见。

**Comment by dfdragon** [comment]
firemonkey框架编译后生成的文件实在是太大，这个问题有点无解

**Comment by chansonjon** [comment]
闪退
