### ISSUE TITLE
是否考虑增加一个命令行选项 "--pid filename" ?

### ISSUE THREAD

**Issue by raszzh** [xtaci/kcptun#208]
作者您好，我建议增加一个命令行选项："--pid filename" 。把进程ID记录到指定文件中。

有这个选项后，停止脚本就能很方便的找到PID。

谢谢！

**Comment by LiR1cky** [comment]
自己写个停止脚本就是了，以server_linux_amd64为例
PID=`ps -ef | grep server_linux_amd64 | grep -v grep | awk '{print $2}'`
if [[ "" !=  "$PID" ]]; then
  echo "killing $PID"
  kill -9 $PID
fi

**Comment by xtaci** [comment]
start-stop-daemon 可能获得pid，应该是标准方式产生 /var/run/xxxx.pid

**Comment by wxyzh** [comment]
我喜欢用killall

xtaci <notifications@github.com>于2016年9月29日周四 22:21写道：

**Comment by raszzh** [comment]
用 start-stop-daemon 解决问题了。
kill的方法一个实例能用，但如果启动了多个实例，不记录pid无法只停止其中的一个。
