### ISSUE TITLE
如果不加密

### ISSUE THREAD

**Issue by raszzh** [xtaci/kcptun#209]
配合Shadowsocks使用，Shadowsocks用了很强的加密算法。而kcptun配置为不加密，这样不安全吗？为什么？

**Comment by xtaci** [comment]
不安全，因为协议封装，你可以认为是一层层套瓷。

UDP是最外层，进来是FEC层，再进来是KCP层，再进去才是SS那一层。

kcptun加密是在UDP层的加密，因此可以保护FEC/KCP协议头部。 SS加密仅仅是流层加密。

**Comment by weyou** [comment]
@xtaci 我的理解是这种情况下，外层加密仅仅是为了不被wall识别出特征字段是吗？

**Comment by xtaci** [comment]
@weyou 是为了保证数据的包的完整性，参考：https://en.wikipedia.org/wiki/Authenticated_encryption

**Comment by jearton** [comment]
普通的ss流量会被运营商检测出来吧，然后就会被限速或者封IP。套了一层kcp就不好说了

**Comment by xiaoze1332** [comment]
@xtaci 
作者你好，我在kcptun外面又嵌套了udp2raw,也就是将kcp封装成了tcp。
udp2raw默认自带“aes-128”加密。
所以连接方式为: ss server=>kcptun server=>udp2raw server

所以是否我可以认为kcptun server不加密,也会保护头部，不会被识别出来？
