### ISSUE TITLE
server端没响应

### ISSUE THREAD

**Issue by warrior-wwy** [xtaci/kcptun#210]
ubuntu12.04 64bit，0922的版本
使用最简单方式运行
服务端：./server_linux_amd64 -t "127.0.0.1:443" -l : -mode fast2
客户端：./client_windows_amd64  -l :2100 -r x.x.x.x:2219 -mode fast2
，其他参数默认，检查过两边一致。
服务端防火墙2219打开，客户端ss监听127.0.0.1:2100，还是没法上网
客户端出现
“λ .\client_windows_amd64.exe -l :2100 -r x.x.x.x:2219 -mode fast2
2016/09/30 23:01:06 version: 20160922
2016/09/30 23:01:06 listening on: [::]:2100
2016/09/30 23:01:06 encryption: aes
2016/09/30 23:01:06 nodelay parameters: 1 20 2 1
2016/09/30 23:01:06 remote address: 52.192.229.192:2219
2016/09/30 23:01:06 sndwnd: 128 rcvwnd: 1024
2016/09/30 23:01:06 compression: true
2016/09/30 23:01:06 mtu: 1350
2016/09/30 23:01:06 datashard: 10 parityshard: 3
2016/09/30 23:01:06 acknodelay: false
2016/09/30 23:01:06 dscp: 0
2016/09/30 23:01:06 sockbuf: 4194304
2016/09/30 23:01:06 keepalive: 10
2016/09/30 23:01:06 conn: 1
2016/09/30 22:56:18 stream opened
2016/09/30 22:56:19 stream opened
2016/09/30 22:56:20 stream opened
2016/09/30 22:56:21 stream opened
2016/09/30 22:56:30 session scavenged
2016/09/30 22:56:46 stream opened
2016/09/30 22:56:48 stream closed
2016/09/30 22:56:48 stream closed
2016/09/30 22:56:48 stream closed
”
服务端没反应
`0 14:53:23 version: 20160922
2016/09/30 14:53:23 listening on: [::]:2219
2016/09/30 14:53:23 target: 127.0.0.1:443
2016/09/30 14:53:23 encryption: aes
2016/09/30 14:53:23 nodelay parameters: 1 20 2 1
2016/09/30 14:53:23 sndwnd: 1024 rcvwnd: 1024
2016/09/30 14:53:23 compression: true
2016/09/30 14:53:23 mtu: 1350
2016/09/30 14:53:23 datashard: 10 parityshard: 3
2016/09/30 14:53:23 acknodelay: false
2016/09/30 14:53:23 dscp: 0
2016/09/30 14:53:23 sockbuf: 4194304
2016/09/30 14:53:23 keepalive: 10`

另外，git clone 后运行build_realse.sh，生成一些空的tar.gz压缩文件

**Comment by xtaci** [comment]
100%是防火墙

**Comment by gatalon** [comment]
我也突然遇到这个问题了，昨天弄好久没弄好，怎么办？

**Comment by xtaci** [comment]
换端口

**Comment by gatalon** [comment]
换过端口还是不行。
nc -vuz测试udp端口是通的，可是服务器端就是没有反应。

**Comment by gatalon** [comment]
怀疑是isp做了限制，我是上海有线的。正常使用Shadowsocks正常。

**Comment by gatalon** [comment]
找到问题了，还是我的路由器防火墙的问题，整个路由器自动翻墙把我搞蒙了，谢谢啦。

**Comment by warrior-wwy** [comment]
今天检查了一下确实是防火墙设置问题，之前只是设置了tcp端口开放，增加udp之后ok了，谢谢了。 @xtaci

**Comment by xiaobailong24** [comment]
确实防火墙增加UDP就可以了，谢谢各位！

**Comment by hxpp** [comment]
@xiaobailong24 can you tell me how to add UDP on the firewall. Which firewall do u mean,the server or the client?  Best to show me a pic,pls. im new here. I can speak Chinese.

**Comment by xiaobailong24** [comment]
@hxpp centos 7 x64, replace 29999 with your PORT.

sudo iptables -I INPUT -p tcp -m tcp --dport 29999 -j ACCEPT 
sudo iptables -I INPUT -p udp -m udp --dport 29999 -j ACCEPT

**Comment by hxpp** [comment]
@xiaobailong24 My system is Centos 6 x86  not 7；KCPtun configuration is
{
    "localaddr": ":443",
    "remoteaddr": "23.106.156.164:29900",
    "key": "XXXXXX",
    "crypt": "aes",
    "mode": "fast",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}
so can I write like this:
sudo iptables -I INPUT -p tcp -m tcp --dport 29900 -j ACCEPT
sudo iptables -I INPUT -p udp -m udp --dport 29900 -j ACCEPT
sudo iptables-save

**Comment by xiaobailong24** [comment]
I guess your port should be 443. 
23.106.456.164:29900 is your ss server port.

you can do it:
sudo iptables -I INPUT -p tcp -m tcp --dport 29900 -j ACCEPT
sudo iptables -I INPUT -p udp -m udp --dport 29900 -j ACCEPT
sudo iptables -I INPUT -p tcp -m tcp --dport 443 -j ACCEPT
sudo iptables -I INPUT -p udp -m udp --dport 443 -j ACCEPT
sudo iptables-save

**Comment by hxpp** [comment]
@xiaobailong24 
![image](https://cloud.githubusercontent.com/assets/24197243/20645725/b91525d2-b4a1-11e6-80f7-bdae008c9f4e.png)

Have I succeed?  I think maybe I repeated this times, did it matter?

**Comment by xiaobailong24** [comment]
@hxpp 
It doesn't matter. And does kcptun work successfully now?

**Comment by hxpp** [comment]
@xiaobailong24 it works very good utill now. I think I succeed. Thank you very much for ur patient to help me- a boy who suck cock for a living. God bless u. I love u and this great Github.

**Comment by xiaobailong24** [comment]
@hxpp
 haha. You are welcome and enjoy it!

**Comment by josephzjw** [comment]
还有一个可能性是在客户端把KCP服务器地址写成了127.0.0.1，而不是远端服务器地址，也会出现类似的情况...

**Comment by Geooooorge** [comment]
我是PC机连在路由器之后，正常的ss可以访问。但是加上kcp后客户端一直是stream open，session scavenged,服务端没反应，然后在路由器以及PC机的防火墙里都加上了
sudo iptables -I INPUT -p tcp -m tcp --dport 9898 -j ACCEPT
sudo iptables -I INPUT -p udp -m udp --dport 9898 -j ACCEPT
sudo iptables -I INPUT -p tcp -m tcp --dport 8989 -j ACCEPT
sudo iptables -I INPUT -p udp -m udp --dport 8989 -j ACCEPT
但是还是不行，还是服务端没反应。不知到什么原因。@xiaobailong24,@xtaci

**Comment by xiaobailong24** [comment]
@Geooooorge 
sudo iptables-save

**Comment by Geooooorge** [comment]
@xiaobailong24 
下面是路由器里的

:zone_wan_output - [0:0]
:zone_wan_src_REJECT - [0:0]
-A INPUT -p tcp -m tcp --dport 8989 -j ACCEPT 
-A INPUT -p udp -m udp --dport 8989 -j ACCEPT 
-A INPUT -p udp -m udp --dport 9898 -j ACCEPT 
-A INPUT -p tcp -m tcp --dport 9898 -j ACCEPT 
-A INPUT -p udp -m udp --dport 9898 -j ACCEPT 


这是PC
# Completed on Tue Dec  6 14:33:29 2016
# Generated by iptables-save v1.4.21 on Tue Dec  6 14:33:29 2016
*filter
:INPUT ACCEPT [914:210725]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1550:362512]
-A INPUT -p udp -m udp --dport 9898 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9898 -j ACCEPT
-A INPUT -p udp -m udp --dport 8989 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8989 -j ACCEPT
-A INPUT -p udp -m udp --dport 9898 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9898 -j ACCEPT

**Comment by xiaobailong24** [comment]
@Geooooorge 
kcptun服务器部署在哪里的？
是要在服务器端开端口，不是客户端

**Comment by Geooooorge** [comment]
@xiaobailong24 
还是有问题。。主要我手机用着一直没问题啊。。。手机ss+kcp都没问题。。PC的话我的mac可以，但是ubuntu就不行

**Comment by xiaobailong24** [comment]
@Geooooorge 
那可能是客户端配置的问题了，你再试试吧。ubuntu用的什么软件？

**Comment by Geooooorge** [comment]
@xiaobailong24 
ubuntu上ss是直接敲命令的
kcp是直接下载编译好的
json文件应该没错的。。。对了好几遍了。。。。

**Comment by xiaobailong24** [comment]
@Geooooorge 
建议把命令和配置文件贴出来让大家帮忙看一下。必要的内容🉑马赛克

**Comment by Geooooorge** [comment]
kcp的配置
{
	"localaddr": ":9898",
	"remoteaddr": "vps:8989",
	"crypt": "salsa20",
	"mode": "fast2",
	"conn": 1,
	"mtu": 1400,
	"sndwnd": 1536,
	"rcvwnd": 1536,
	"nocomp": false,
	"log": "/home/george/kcptun/kcptun.log"
}
ss命令
nohup sslocal -s 127.0.0.1 -p 9898 -k "passwd" > ~/log/ss.log &

上面的127.0.0.1替换成VPS地址的时候是可以fq的。
kcp启动命令是./client_linux_amd64 -c ~/kcptun/config.json 2>&1 &

**Comment by xiaobailong24** [comment]
@Geooooorge 
是不是本地9898端口被占用，建议换端口试试。1080或1082

**Comment by Geooooorge** [comment]
@xiaobailong24 
不是这个原因
log里一直是stream open和closed，还有session scavenged
但是服务端的日志里没有反应。

**Comment by xiaobailong24** [comment]
@Geooooorge 
那我不知道了，把防火墙关了试试吧。

**Comment by Geooooorge** [comment]
@xiaobailong24
关了可以了。。。。
服务器端是要增加9898端口还是9898（ss）和8989（服务端KCP）都要增加？

**Comment by Geooooorge** [comment]
@xiaobailong24
关了可以了。。。。
服务器端是要增加9898端口还是9898（ss）和8989（服务端KCP）都要增加？

**Comment by xiaobailong24** [comment]
@Geooooorge 
应该是只增加服务端KCP的端口（8989）就行。我都加上了。

**Comment by hxpp** [comment]
@xiaobailong24  I find that the code we input last time disappear when I restart my server, can we have a way to make sure what we input save forever whether we restart or not. bro.

**Comment by hxpp** [comment]
@Geooooorge it seems like that u are the same question with me.

**Comment by Geooooorge** [comment]
@xiaobailong24 
又不行了。。。。真是醉了

**Comment by xiaobailong24** [comment]
@hxpp 
try:
```
sudo root
```
then: 
```
iptables -I INPUT -p tcp -m tcp --dport 29900 -j ACCEPT
iptables -I INPUT -p udp -m udp --dport 29900 -j ACCEPT
iptables -I INPUT -p tcp -m tcp --dport 443 -j ACCEPT
iptables -I INPUT -p udp -m udp --dport 443 -j ACCEPT
iptables-save
```
finally:
restart

**Comment by Geooooorge** [comment]
@xiaobailong24 
现在是通过增加规则，没有整个关闭防火墙 可以用了。。
不过油管上有些图片显示不了是为什么

**Comment by xiaobailong24** [comment]
@Geooooorge 
生命贵在折腾。

**Comment by hxpp** [comment]
@xiaobailong24 not working. It still disappeared when I reboot.

**Comment by xiaobailong24** [comment]
@hxpp 
Try my latest reply. I have done it just now and it is working.

**Comment by hxpp** [comment]
@xiaobailong24   Help.  How to save and quit?
![image](https://cloud.githubusercontent.com/assets/24197243/20920086/942f7e22-bbd9-11e6-9517-a194ab891557.png)
...is this right? I can not back..5555

**Comment by xiaobailong24** [comment]
@hxpp 
```
**Esc**->**:wq**
```
It's a command of **vim**

**Comment by hxpp** [comment]
let's start from the first line.------"sudo vim /etc/sysconfig/iptables"
when I code this , it comes like this:  
![image](https://cloud.githubusercontent.com/assets/24197243/20920527/4016a192-bbdb-11e6-97e4-685331961e9e.png)
what should I do now?

**Comment by xiaobailong24** [comment]
@hxpp 
'''
R
'''

**Comment by hxpp** [comment]
@xiaobailong24
When I press R ,something new like this: "
"/etc/sysconfig/iptables" 30L, 896C
Swap files found:
-- More --
"
then what? Help pls...

**Comment by xiaobailong24** [comment]
@hxpp 
http://lovesoo.org/delete-edit-file-warning-swap-file-already-exists.html
 And my hangout is xiaobailong24@gmail.com

**Comment by hxpp** [comment]
@xiaobailong24 I destroyed my KcpTun....... I want to cry....  It can not use anymore.
I need to calm down by walking my dog .......

**Comment by xiaobailong24** [comment]
@hxpp 
Nothing is impossible!

**Comment by blackmatch** [comment]
服务器：linode centOS7 64bit
客户端: macOS10.12.2
想实现shadowsocks+kcptun。
服务器设置shadowsocks在8365端口。
服务器kcptun配置：
./server_linux_amd64 --datashard 10 --parityshard 3 --nocomp --key "kcptun@140225" --crypt "salsa20" --listen ":29900" --target "127.0.0.1:8365" --mode "fast3" --rcvwnd 4096 --sndwnd 4096 --mtu 1400

客户端kcptun配置：
./client_darwin_amd64 --datashard 10 --parityshard 3 --nocomp --key "kcptun@140225" --crypt "salsa20" --localaddr ":8365" --remoteaddr "服务器IP:29900" --mode "fast3" --rcvwnd 4096 --sndwnd 4096 --mtu 1400

客户端shadowsocks配置：
127.0.0.1:8365

问题：
客户端有输出stream opend，服务器没有任何响应。把服务器防火墙关了也不行。各位帮帮看一下。 @xiaobailong24

**Comment by josephzjw** [comment]
你不用kcptun直接用shadowsocks可以科学上网么？

**Comment by blackmatch** [comment]
@josephzjw 可以的

**Comment by josephzjw** [comment]
@blackmatch 我和你的配置差不多，不过我的窗长是1024，不是4096，我选的是fast2 mode

**Comment by guliujian** [comment]
你在服务器端netstat -anp |grep 29900看一下

**Comment by blackmatch** [comment]
换了fast2和1024窗口还是一样 @josephzjw

**Comment by blackmatch** [comment]
![2016-12-29 15 05 50](https://cloud.githubusercontent.com/assets/12443954/21538475/7792a24c-cdd8-11e6-8ad9-e20e760b2841.png)
netstat -anp |grep 29900

**Comment by JuncoJet** [comment]
客户端和服务端的iptables -F了，貌似还是老样子
家里很稳定，难道公司的思科ASA防火墙配置问题？

**Comment by blackmatch** [comment]
@JuncoJet 你试试把客户端和服务器端的下面这三个参数逐渐减小看看：
--rcvwnd 1024 --sndwnd 1024 --mtu 500

**Comment by luoganzhi** [comment]
客户端ShadowSocks IP地址改为服务端ip 试试 @blackmatch

**Comment by luoganzhi** [comment]
@blackmatch  端口也要改为kcp的端口  29900
