### ISSUE TITLE
macos 底下如何让kcptun开机启动？

### ISSUE THREAD

**Issue by ccc1924** [xtaci/kcptun#212]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
macos
9. Which end for this issue related to, **client or server**?

开机启动脚本提示the action run shell script encountered an error
脚本卡机后手动执行没有问题

**Comment by mhqschen** [comment]
用automator建立个shell脚本，然后开机自启动就行了。

**Comment by bylevel** [comment]
用 launchctl ，写个plist 放到 ~/Library/LaunchAgents下面就行
