### ISSUE TITLE
经常出现stream closed,怎么办？调了rcvwnd,sndwnd

### ISSUE THREAD

**Issue by howcan** [xtaci/kcptun#217]
![image](https://cloud.githubusercontent.com/assets/16412020/19212808/3e181aa6-8d8c-11e6-90ac-ebdca0eeff38.png)
经常出现这个，服务端日志也是这样的。手动调了rcvwnd,sndwnd，20M电信光纤。sndwnd调了128，rcvwnd，256.
试过64 128，也试过128 512，感觉一样。
虽然ytb，720或者1080都不卡。但是还是想弄清楚出现这个stream closed是什么原因

**Comment by lizongzeshunshun** [comment]
```stream closed``` 是正常现象

**Comment by howcan** [comment]
@lizongzeshunshun 啊，是正常现象啊。为什么会出现这个呢，可以详细说明 一下吗，感谢

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/blob/master/client/main.go#L58
