### ISSUE TITLE
有没有人因为用kcptun被主机商封了的，东西不错，有点忐忑

### ISSUE THREAD

**Issue by cmdlot** [xtaci/kcptun#219]
毕竟占用那么多资源，高峰时期还能那么大带宽的，新上车，问问老司机有没有被封的

**Comment by qadet123** [comment]
搬瓦工表示稳定无异常，kcp数据包都是通过udp协议发送的，要封也是封端口，总不能把udp协议封了吧

**Comment by cmdlot** [comment]
我之前也用搬瓦工，有个服务器被黑了乱发邮件被封了。搬瓦工是要么不封VPS，一封就要钱，还要个没完。现在只买来爬墙。就是怕哪天说占用太多带宽给封了，怕怕

**Comment by wang20150419** [comment]
"有个服务器被黑了乱发邮件被封了"， 我的也是，反复查了无病毒。奇怪的很，不知道为啥，也不解封。其实是搬瓦工的维护能力差劲。

**Comment by cmdlot** [comment]
我是一台里面一个网站中毒被投诉了，他直接关了我5台所有服务器。后来移出来换到阿里云自己解决了
损失好几千块。建议没买过搬瓦工的基友最好先好好先好好读一下搬瓦工的协议，他可以以协议里的任何一条封你，然后管你要钱。不过我觉得他也是看人的，所以有价值的东西最好还是别放到廉价服务器，教训啊

**Comment by cmdlot** [comment]
搬瓦工是没有什么服务的，卖了以后有问题他会找你麻烦，以协议条款来要挟要钱。也不会帮你解决什么问题

**Comment by guojian0624** [comment]
vultr 东京服务器IP疑似被墙，今天换了一个。

**Comment by cmdlot** [comment]
我发现用一键脚本就很容易被GFW干扰，大概是参数都一样的原因，特征太明显，所以用脚本安装的时候最好端口啊，加密方式这些的不要用默认的，很容易被干扰。

**Comment by zpfsqzyl** [comment]
有的ss一键脚本有问题，注意一下。

**Comment by icecrack** [comment]
之前被警告过了，再发现就封了

**Comment by bettermanbao** [comment]
sentris VPS被 suspend 2次了，流量也不大，就是20Mbps左右的出站流量。
郁闷啊

**Comment by kmahyyg** [comment]
超售严重，然后管理面板都进不去……

趁早弃坑

2016年11月2日 15:07，"bettermanbao" <notifications@github.com>写道：

**Comment by jiawei-zheng** [comment]
马丹，我的就被封了。。。pzea

**Comment by zzhhbyt1** [comment]
你们被扫出来然后走你们代理发垃圾邮件的，可以看看是不是没加密好或者是某个ss客户端开启了局域网共享结果局域网内有挂了马的设备把你给扫出来了。@wang20150419

**Comment by zpfsqzyl** [comment]
那么这是ss的问题，不是kcptun

**Comment by zzhhbyt1** [comment]
不，我说的这种情况属于自己使用的时候脑残的问题。。和ss和kcptun没关系。

**Comment by goxofy** [comment]
会被警告, 继续用的话可能会被封

**Comment by ninggu2008** [comment]
@bettermanbao 对sentris而言，20mbps已经算大的了。sentris邮件明确说了，1G出口服务器卖给几百人，每个人平均多少可以自己算，偶尔突发10mbps应该安全。要速度，只能买贵的了。
用用ss，应该10mbps足够，好奇你20mbps是用来干啥了（难道4K？），是不是参数设定不当，前向纠错开大了或者窗口开大了。

**Comment by ninggu2008** [comment]
按默认参数用kcptun，sentri那种2刀一年的，肯定会被封。sentris的话，肯定不能带宽持续20mbps以上，而默认参数是给50mbps准备的。所以小白很危险。还好我宽带只有10mbps，而且翻到教程调窗口，所以一开始就调的低。
sentris这种128内存，1G硬盘的，没几天，爆破记录 /var/log/btmp secure都有百兆大小，内存也被这些记录占满。自从用fail2ban和秘钥登陆以来，内存占用大幅降低，btmp也很小了。

**Comment by hehongbo** [comment]
因为超流量被bwh关停过。关停前会有邮件警告，关停后机器彻底suspend，面板的console和文件管理器都无法使用，数据也无法导出只能乖乖等下个月流量重置。经历过几个主机商，都跑过kcptun，都没有被封。

**Comment by flipphos** [comment]
很正常。超流量被主机商停用而已。和kcptun没有必然联系。我之前没用kcptun的时候也发生过。
就是流量用超被停机，用什么用超了是你的事情了。

**Comment by cssnote** [comment]
我平时只用kcptun看看Youtube，网页浏览速度也会快很多，用了一年多没事，甚至 ip被block后，kcptun竟然还能用，不用kcptun就出不了墙。
