### ISSUE TITLE
是否可以用kcptun来加速加密vpn呢？

### ISSUE THREAD

**Issue by appleatiger** [xtaci/kcptun#22]
如题，已知软路由支持pptp代理，支持域名分流，支持多线DNS，是不是可以采用kcptun来连接pptp服务器端和客户端？

**Comment by xtaci** [comment]
没试过，应该可以吧，只要是tcp的，毕竟是传输承载

**Comment by appleatiger** [comment]
实测没有成功，可以看到kcptun 客户端和服务端有握手，但是最后超时提示端口已关闭。

**Comment by xtaci** [comment]
可能路由表被改变了

**Comment by appleatiger** [comment]
google了一下说还有一个gre47协议的问题，看来行不通。

**Comment by kxmp** [comment]
@appleatiger  你不知道有ssl vpn么

**Comment by appleatiger** [comment]
公司的软路由不支持ssl vpn，又需要透明代理到局域网中，是现实需求。

**Comment by kxmp** [comment]
@appleatiger 你是需要让整个局域网都连kcp是吧.

**Comment by appleatiger** [comment]
局域网内都需要翻墙，但是又不可能一台一台去设置socks代理。其实就是需要透明代理。

**Comment by jannson** [comment]
我研究了下，还真没有找到类似 pptp connection over proxy 的安装配置方法。
如果是 openvpn 倒是可以，把 openvpn 配置在基于一个 tcp 的 代理服务器上。
看来简单的办法应该是 换路由器，或增加一台能运行 kcptun 的路由器了。

**Comment by appleatiger** [comment]
最简单办法看来是增加一台网关服务器了，网关机上做ss透明代理。

**Comment by lins05** [comment]
试过 kcptun 上面封装 openconnect ，性能提升不大，不过我感觉更可能是 openconnect  的问题。

**Comment by xtaci** [comment]
一层层的套瓷，有效载荷下降的快啊
