### ISSUE TITLE
[ERR] yamux: keepalive failed: i/o deadline reached是什么情况？

### ISSUE THREAD

**Issue by ruiruige** [xtaci/kcptun#220]
我配置了半天，提issue前也检查了好几遍配置，还是搞不定

1.有谁能麻烦帮我看一下？这个问题也搜不到
2.或者你们谁上我的账号试试你那边能连吗？

GUI

![image](https://cloud.githubusercontent.com/assets/8370100/19278724/f77fdc64-9010-11e6-80fe-55509746c6c8.png)

server

![image](https://cloud.githubusercontent.com/assets/8370100/19278883/9ca6194c-9011-11e6-844b-5850e1e9ce1b.png)

016/10/12 00:10:13 stream closed
2016/10/12 00:10:18 [ERR] yamux: keepalive failed: i/o deadline reached
2016/10/12 00:10:18 [ERR] yamux: Failed to read header: broken pipe
2016/10/12 00:10:18 stream closed
2016/10/12 00:10:18 stream closed
2016/10/12 00:10:18 stream closed
2016/10/12 00:10:18 stream closed
2016/10/12 00:10:18 stream closed
2016/10/12 00:10:18 session shutdown
2016/10/12 00:10:18 stream opened
2016/10/12 00:10:18 stream opened
2016/10/12 00:10:43 stream opened
2016/10/12 00:10:48 stream closed
2016/10/12 00:10:48 stream closed
2016/10/12 00:11:03 [ERR] yamux: Invalid protocol version: 1
2016/10/12 00:11:03 stream closed
2016/10/12 00:11:03 [ERR] yamux: keepalive failed: session shutdown
2016/10/12 00:11:03 session shutdown
2016/10/12 00:11:18 stream opened
2016/10/12 00:11:39 [ERR] yamux: Invalid protocol version: 1
2016/10/12 00:11:39 stream closed
2016/10/12 00:11:39 [ERR] yamux: keepalive failed: session shutdown
2016/10/12 00:11:39 session shutdown
2016/10/12 00:11:43 stream opened

**Comment by qadet123** [comment]
你这是客户端的日志吗，可以去server看看本地udp端口有没有被正常监听，没有的话检查一下防火墙设置

**Comment by ruiruige** [comment]
@qadet123 
![image](https://cloud.githubusercontent.com/assets/8370100/19279165/d018adfc-9012-11e6-8d3a-92c4d372a1c3.png)
这是netstat -anp的显示  按理来说应该监听了吧？

**Comment by ruiruige** [comment]
如果哪位好心同学有条件的话 帮我试一下图中的帐号密码能否连上吧  感激不尽
ss加密方式chacha20  密码相同  谢谢了

**Comment by baggiogogo** [comment]
检查服务端，客户端连了下并无报错。正常ss可以连接吗

**Comment by ruiruige** [comment]
@baggiogogo 
直连我的服务器 ss可以连接  端口9105  密码 whx20202   加密chacha20 （需要安装libsodium  很快的）

难道是我客户端问题？

**Comment by baggiogogo** [comment]
连接正常，你客服端有问题

**Comment by ruiruige** [comment]
@baggiogogo   谢谢啊！
我在确认一下  是直连和 KCPTUN都正常吗？

**Comment by baggiogogo** [comment]
正常，截图我不发了，肯定客服端问题，一会把编辑掉你IP，不安全。

**Comment by ruiruige** [comment]
@baggiogogo  非常感谢 我一会把服务器给改下  谢谢了

**Comment by baggiogogo** [comment]
不客气

**Comment by LiR1cky** [comment]
yamux是老版本了，你这说明服务器端用的是很老的版本。
客户端用的是哪个版本？我怀疑你是用的是基于yamux的服务器端配合了基于SMUX的新版客户端所以不匹配造成的。建议把服务器端和客户端同时更新到相同的版本

**Comment by ruiruige** [comment]
我按网上教程装的  server是最新的1009
![image](https://cloud.githubusercontent.com/assets/8370100/19295271/13aa050e-9066-11e6-8ca2-430b906ce7af.png)

现在我没搞定这个问题  但是我换了个办法：
- 找了个国内高流量 2U4G的机器
- 那个机器是linux的  肯定不像windows那么多情况
- 机器上运行kcptun客户端，然后shadowsocks 链接本地端口
- 为了安全 ss提供服务的1080绑定本地（好像ss的1080不能设置密码？）
- 使用polipo代理服务器，上层指向本地ss提供的1080 sock，auth 设置账号密码（只能支持basic模式 不是很安全）
- 连接polipo的http代理

**Comment by lavenresearch** [comment]
@ruiruige 

我也遇到这个问题，换了服务器的版本以后就好了。你这应该还是服务器客户端版本不匹配的问题。

我用的是，服务器（v20170315），android kcptun ss 插件（v0.0.4），shadowsocks android 客户端（v4.1.3）。
