### ISSUE TITLE
运行一段时间以后htop会显示很多kcptun的进程

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#221]
如图，请问这种情况正常吗？谢谢。
ps -ef 以及 top 都只显示一个进程。

![htop](https://cloud.githubusercontent.com/assets/17328315/19334955/41f31578-9132-11e6-8b5d-9d87f2ab3c6f.png)

**Comment by xtaci** [comment]
感觉是同一个process的多个thread。你可以用tree方式显示

**Comment by bettermanbao** [comment]
的确是很多thread，但是kcptun开那么多thread，有回收机制吗？

**Comment by xtaci** [comment]
每个阻塞syscall操作， 比如gethostbyname，就会导致一个新的thread，用完后适当时候就会回收。

**Comment by bettermanbao** [comment]
谢谢解答。

另外汇报一下最近的使用经验，依旧是kcptun嵌套ss，运行在orange pi上。
Allwinner H3 ARM v7的CPU，4核关掉3个核，只留一个核1.2GHz工作。内存降频到132MHz，hdmi/gpu和usb全部关掉。
做了这些节能优化后，CPU温度从65度下降到35度，待机功耗从1.2W下降到0.5W。实际使用网速没感到区别，稳定在 0.8-1.0 MByte/s。

我承认我比较折腾。
