### ISSUE TITLE
能否单独使用 kcptun 翻墙？

### ISSUE THREAD

**Issue by pexcn** [xtaci/kcptun#223]

**Comment by lollyhero** [comment]
kcpserver https://github.com/clangcn/kcp-server

**Comment by josephzjw** [comment]
答案是不是不能啊？

**Comment by testcaoy7** [comment]
不能，kcptun只是一个将其他协议封装为UDP，再用KCP算法控制UDP发包的转换程序，不能用来绕过防火墙。要干这件事，你需要能绕过防火墙的其他程序，比如著名的SS

**Comment by pexcn** [comment]
可以吧

**Comment by josephzjw** [comment]
你没有配置ss就可以科学上网了嘛？

**Comment by pexcn** [comment]
这个不是可以嘛：https://github.com/clangcn/kcp-server
