### ISSUE TITLE
数据压缩在mips编译的情况下不可用

### ISSUE THREAD

**Issue by fy0** [xtaci/kcptun#224]
可能这是一个snappy的BUG，错误信息是主体是 panic: runtime error: slice bounds out of range
开 -nocomp 错误就没了。

此外关于ipv4这个库在编译mips版本时有一个简单的办法：
go get client 之后会出错，直接切到代码目录，然后 ack-grep ipv4 一发
当前版本(20161009)是只有 /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go
然后直接把涉及 ipv4 的import注释掉，函数内容注释掉改成 return nil
重新编译就好了，这样只是少个DSCP罢了。

以下是错误信息（感觉没什么卵用）：
2016/10/17 16:46:22 main.go:259: version: SELFBUILD
2016/10/17 16:46:24 main.go:295: listening on: [::]:3157
2016/10/17 16:46:24 main.go:296: encryption: aes
2016/10/17 16:46:24 main.go:297: nodelay parameters: 1 20 2 1
2016/10/17 16:46:24 main.go:298: remote address: 104.156.229.12:3154
2016/10/17 16:46:24 main.go:299: sndwnd: 128 rcvwnd: 1024
2016/10/17 16:46:24 main.go:300: compression: true
2016/10/17 16:46:24 main.go:301: mtu: 1350
2016/10/17 16:46:24 main.go:302: datashard: 10 parityshard: 3
2016/10/17 16:46:24 main.go:303: acknodelay: false
2016/10/17 16:46:24 main.go:304: dscp: 0
2016/10/17 16:46:24 main.go:305: sockbuf: 4194304
2016/10/17 16:46:24 main.go:306: keepalive: 10
2016/10/17 16:46:24 main.go:307: conn: 1
2016/10/17 16:46:24 main.go:308: autoexpire: 0
2016/10/17 16:46:26 main.go:57: stream opened
2016/10/17 16:46:26 main.go:57: stream opened
panic: runtime error: slice bounds out of range

goroutine 18 [running]:
github.com/golang/snappy.encodeBlock(0x105bc014, 0x12ac8, 0x12ac8, 0x10594000, 0x210, 0x10000, 0xe38f4cf5)
    /opt/mipsgo/src/gocode/src/github.com/golang/snappy/encode_other.go:175 +0x10c4
github.com/golang/snappy.Encode(0x105bc012, 0x12aca, 0x12aca, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/golang/snappy/encode.go:37 +0x370
github.com/golang/snappy.(_Writer).write(0x1053c750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/golang/snappy/encode.go:229 +0x280
github.com/golang/snappy.(_Writer).Flush(0x1053c750, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/golang/snappy/encode.go:272 +0xb0
main.(_compStream).Write(0x1053a6c0, 0x1051eb40, 0x210, 0x210, 0x210, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:40 +0x88
github.com/xtaci/smux.(_Session).writeBinary(0x1050a4c0, 0x1051eb40, 0x210, 0x210, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:272 +0xa4
github.com/xtaci/smux.(*Stream).Write(0x10560080, 0x10628000, 0x208, 0x8000, 0x208, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/smux/stream.go:88 +0x6a8
io.Copy(0x778ce440, 0x10560080, 0x778ce458, 0x1051c268, 0x0, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/io/io.go:364 +0x288
main.func·002()
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:67 +0xd8
created by main.handleClient
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:67 +0x578

goroutine 1 [IO wait]:
net.(_pollDesc).Wait(0x1050a238, 0x72, 0x0, 0x0)
    /opt/mipsgo/src/net/fd_poll_runtime.go:84 +0x4c
net.(_pollDesc).WaitRead(0x1050a238, 0x0, 0x0)
    /opt/mipsgo/src/net/fd_poll_runtime.go:89 +0x48
net.(_netFD).accept(0x1050a200, 0x0, 0x778ccaf8, 0x1053a390)
    /opt/mipsgo/src/net/fd_unix.go:419 +0x3dc
net.(_TCPListener).AcceptTCP(0x1051c838, 0x1051c270, 0x0, 0x0)
    /opt/mipsgo/src/net/tcpsock_posix.go:234 +0x58
main.func·005(0x10500b40, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:376 +0x2620
reflect.Value.call(0x223a28, 0x2c931c, 0x13, 0x276a70, 0x4, 0x10529ac0, 0x1, 0x1, 0x0, 0x0, ...)
    /opt/mipsgo/src/reflect/value.go:419 +0xff0
reflect.Value.Call(0x223a28, 0x2c931c, 0x13, 0x10529ac0, 0x1, 0x1, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/reflect/value.go:296 +0xb0
github.com/urfave/cli.HandleAction(0x223a28, 0x2c931c, 0x10500b40, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/urfave/cli/app.go:487 +0x27c
github.com/urfave/cli.(*App).Run(0x10566000, 0x1050a000, 0x7, 0x7, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/urfave/cli/app.go:245 +0x9e0
main.main()
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:406 +0x1418

goroutine 5 [syscall]:
os/signal.loop()
    /opt/mipsgo/src/os/signal/signal_unix.go:21 +0x30
created by os/signal.init·1
    /opt/mipsgo/src/os/signal/signal_unix.go:27 +0x58

goroutine 6 [chan receive]:
main.sigHandler()
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/signal.go:23 +0x150
created by main.init·1
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/signal.go:15 +0x48

goroutine 7 [select]:
github.com/xtaci/kcp-go.(*UDPSession).updateTask(0x1050c1b0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:483 +0x33c
created by github.com/xtaci/kcp-go.newUDPSession
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:110 +0x568

goroutine 8 [select]:
github.com/xtaci/kcp-go.(*UDPSession).outputTask(0x1050c1b0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:389 +0x1934
created by github.com/xtaci/kcp-go.newUDPSession
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:111 +0x598

goroutine 9 [select]:
github.com/xtaci/kcp-go.(*UDPSession).readLoop(0x1050c1b0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:601 +0x528
created by github.com/xtaci/kcp-go.newUDPSession
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:113 +0x5d8

goroutine 11 [IO wait]:
net.(_pollDesc).Wait(0x1050a0b8, 0x72, 0x0, 0x0)
    /opt/mipsgo/src/net/fd_poll_runtime.go:84 +0x4c
net.(_pollDesc).WaitRead(0x1050a0b8, 0x0, 0x0)
    /opt/mipsgo/src/net/fd_poll_runtime.go:89 +0x48
net.(_netFD).readFrom(0x1050a080, 0x1056a800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x778ccaf8, 0x1053a0f0)
    /opt/mipsgo/src/net/fd_unix.go:269 +0x418
net.(_UDPConn).ReadFromUDP(0x1051c2f8, 0x1056a800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/net/udpsock_posix.go:67 +0x108
net.(_UDPConn).ReadFrom(0x1051c2f8, 0x1056a800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/net/udpsock_posix.go:82 +0x104
github.com/xtaci/kcp-go.(_UDPSession).receiver(0x1050c1b0, 0x1050a400)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:582 +0x124
created by github.com/xtaci/kcp-go.(*UDPSession).readLoop
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:598 +0x84

goroutine 12 [select]:
github.com/xtaci/kcp-go.(_UDPSession).Read(0x1050c1b0, 0x105e8000, 0x4, 0x12ace, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:172 +0x8a8
io.ReadAtLeast(0x778ce288, 0x1050c1b0, 0x105e8000, 0x4, 0x12ace, 0x4, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/io/io.go:298 +0x118
io.ReadFull(0x778ce288, 0x1050c1b0, 0x105e8000, 0x4, 0x12ace, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/io/io.go:316 +0x6c
github.com/golang/snappy.(_Reader).readFull(0x1050a480, 0x105e8000, 0x4, 0x12ace, 0x1, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/golang/snappy/decode.go:108 +0x6c
github.com/golang/snappy.(_Reader).Read(0x1050a480, 0x105fe000, 0x8, 0x10008, 0x10500fa0, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/golang/snappy/decode.go:128 +0x1bc
main.(_compStream).Read(0x1053a6c0, 0x105fe000, 0x8, 0x10008, 0x2, 0x0, 0x0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:35 +0x5c
io.ReadAtLeast(0x778ce358, 0x1053a6c0, 0x105fe000, 0x8, 0x10008, 0x8, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/io/io.go:298 +0x118
io.ReadFull(0x778ce358, 0x1053a6c0, 0x105fe000, 0x8, 0x10008, 0x778bfb7c, 0x0, 0x0)
    /opt/mipsgo/src/io/io.go:316 +0x6c
github.com/xtaci/smux.(_Session).readFrame(0x1050a4c0, 0x105fe000, 0x10008, 0x10008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:155 +0x104
github.com/xtaci/smux.(_Session).recvLoop(0x1050a4c0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:190 +0x1d8
created by github.com/xtaci/smux.newSession
    /opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:58 +0x314

goroutine 13 [select]:
github.com/xtaci/smux.(*Session).keepalive(0x1050a4c0)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:238 +0x360
created by github.com/xtaci/smux.newSession
    /opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:59 +0x340

goroutine 14 [select]:
main.scavenger(0x1050a580)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:423 +0x648
created by main.func·005
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:373 +0x2608

goroutine 15 [select]:
main.handleClient(0x778ce370, 0x1051c268, 0x778ce390, 0x10560080)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:70 +0x65c
created by main.func·005
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:402 +0x30ec

goroutine 16 [select]:
main.handleClient(0x778ce370, 0x1051c270, 0x778ce390, 0x10560100)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:70 +0x65c
created by main.func·005
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:402 +0x30ec

goroutine 17 [select]:
github.com/xtaci/smux.(_Stream).Read(0x10560080, 0x10620000, 0x8000, 0x8000, 0x0, 0x778c89c0, 0x1051c068)
    /opt/mipsgo/src/gocode/src/github.com/xtaci/smux/stream.go:57 +0x38c
io.Copy(0x778ce410, 0x1051c338, 0x778ce3c8, 0x10560080, 0x0, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/io/io.go:362 +0x208
net.genericReadFrom(0x778ce3b0, 0x1051c268, 0x778ce3c8, 0x10560080, 0x0, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/net/net.go:404 +0xb4
net.(_TCPConn).ReadFrom(0x1051c268, 0x778ce3c8, 0x10560080, 0x778ce3f8, 0x1051c268, 0x0, 0x0)
    /opt/mipsgo/src/net/tcpsock_posix.go:72 +0x118
io.Copy(0x778ce3b0, 0x1051c268, 0x778ce3c8, 0x10560080, 0x0, 0x0, 0x0, 0x0)
    /opt/mipsgo/src/io/io.go:358 +0x154
main.func·001()
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:64 +0xd8
created by main.handleClient
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:64 +0x448

goroutine 19 [runnable]:
main.func·001()
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:64
created by main.handleClient
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:64 +0x448

goroutine 20 [runnable]:
main.func·002()
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:67
created by main.handleClient
    /opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:67 +0x578

**Comment by xtaci** [comment]
嗯，换了一个snappy库，如果再有问题我也没办法。mips不会编译。

**Comment by xtaci** [comment]
dscp是很重要的特性

**Comment by fy0** [comment]
@xtaci  2333 因为我自己是不用dscp的，另外wiki中的修复方法好像已经不行了，我不懂Golang，就简单粗暴的方式修了。回头我试一下给你个新库的反馈

**Comment by fy0** [comment]
@xtaci  看来这个只是一个fork，相似的错误仍然在重复

2016/10/20 09:50:52 main.go:57: stream opened
panic: runtime error: slice bounds out of range

goroutine 17 [running]:
github.com/klauspost/compress/snappy.encodeBlock(0x105a4014, 0x12ac8, 0x12ac8, 0x10594000, 0x210, 0x10000, 0x247483ac)
	/opt/mipsgo/src/gocode/src/github.com/klauspost/compress/snappy/encode_other.go:175 +0x10c4
github.com/klauspost/compress/snappy.Encode(0x105a4012, 0x12aca, 0x12aca, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/klauspost/compress/snappy/encode.go:37 +0x370
github.com/klauspost/compress/snappy.(*Writer).write(0x1050a090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/klauspost/compress/snappy/encode.go:229 +0x280
github.com/klauspost/compress/snappy.(*Writer).Flush(0x1050a090, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/klauspost/compress/snappy/encode.go:272 +0xb0
main.(*compStream).Write(0x1053a6d0, 0x1051eb40, 0x210, 0x210, 0x210, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:40 +0x88
github.com/xtaci/smux.(*Session).writeBinary(0x105442c0, 0x1051eb40, 0x210, 0x210, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:272 +0xa4
github.com/xtaci/smux.(*Stream).Write(0x10568080, 0x10626000, 0x208, 0x8000, 0x208, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/smux/stream.go:88 +0x6a8
io.Copy(0x774ca3c0, 0x10568080, 0x774ca3d8, 0x1051c268, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:364 +0x288
main.func·002()
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:67 +0xd8
created by main.handleClient
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:67 +0x578

goroutine 1 [runnable]:
syscall.Syscall6(0x10ee, 0x3, 0x1052937c, 0x10529378, 0x80080, 0x0, 0x0, 0xffffffff, 0x0, 0xb)
	/vagrant/go-mips32/src/syscall/asm_linux_mips32x.s:45 +0x10
syscall.accept4(0x3, 0x1052937c, 0x10529378, 0x80080, 0x10544501, 0x0, 0x0)
	/vagrant/go-mips32/src/syscall/zsyscall_linux_mips32le.go:1306 +0x6c
syscall.Accept4(0x3, 0x80080, 0xa, 0x0, 0x0, 0x0, 0x0)
	/vagrant/go-mips32/src/syscall/syscall_linux.go:421 +0x84
net.accept(0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/sock_cloexec.go:47 +0x54
net.(*netFD).accept(0x10544080, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_unix.go:416 +0x2e8
net.(*TCPListener).AcceptTCP(0x1051c2a0, 0x1051c268, 0x0, 0x0)
	/opt/mipsgo/src/net/tcpsock_posix.go:234 +0x58
main.func·005(0x10500b40, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:376 +0x2620
reflect.Value.call(0x223a28, 0x2c9324, 0x13, 0x276a70, 0x4, 0x10529ac0, 0x1, 0x1, 0x0, 0x0, ...)
	/opt/mipsgo/src/reflect/value.go:419 +0xff0
reflect.Value.Call(0x223a28, 0x2c9324, 0x13, 0x10529ac0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/reflect/value.go:296 +0xb0
github.com/urfave/cli.HandleAction(0x223a28, 0x2c9324, 0x10500b40, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/urfave/cli/app.go:487 +0x27c
github.com/urfave/cli.(*App).Run(0x10566000, 0x1050a000, 0x5, 0x5, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/urfave/cli/app.go:245 +0x9e0
main.main()
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:406 +0x1418

goroutine 5 [syscall]:
os/signal.loop()
	/opt/mipsgo/src/os/signal/signal_unix.go:21 +0x30
created by os/signal.init·1
	/opt/mipsgo/src/os/signal/signal_unix.go:27 +0x58

goroutine 6 [chan receive]:
main.sigHandler()
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/signal.go:23 +0x150
created by main.init·1
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/signal.go:15 +0x48

goroutine 7 [select]:
github.com/xtaci/kcp-go.(*UDPSession).updateTask(0x1050c1b0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:483 +0x33c
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:110 +0x568

goroutine 8 [select]:
github.com/xtaci/kcp-go.(*UDPSession).outputTask(0x1050c1b0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:389 +0x1934
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:111 +0x598

goroutine 9 [select]:
github.com/xtaci/kcp-go.(*UDPSession).readLoop(0x1050c1b0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:601 +0x528
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:113 +0x5d8

goroutine 10 [select]:
github.com/xtaci/kcp-go.(*UDPSession).Read(0x1050c1b0, 0x105c8000, 0x4, 0x12ace, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:172 +0x8a8
io.ReadAtLeast(0x774ca280, 0x1050c1b0, 0x105c8000, 0x4, 0x12ace, 0x4, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:298 +0x118
io.ReadFull(0x774ca280, 0x1050c1b0, 0x105c8000, 0x4, 0x12ace, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:316 +0x6c
github.com/klauspost/compress/snappy.(*Reader).readFull(0x10544280, 0x105c8000, 0x4, 0x12ace, 0x1, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/klauspost/compress/snappy/decode.go:108 +0x6c
github.com/klauspost/compress/snappy.(*Reader).Read(0x10544280, 0x105f4000, 0x8, 0x10008, 0x105008c0, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/klauspost/compress/snappy/decode.go:128 +0x1bc
main.(*compStream).Read(0x1053a6d0, 0x105f4000, 0x8, 0x10008, 0x2, 0x0, 0x0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:35 +0x5c
io.ReadAtLeast(0x774ca2d8, 0x1053a6d0, 0x105f4000, 0x8, 0x10008, 0x8, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:298 +0x118
io.ReadFull(0x774ca2d8, 0x1053a6d0, 0x105f4000, 0x8, 0x10008, 0x774bbb40, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:316 +0x6c
github.com/xtaci/smux.(*Session).readFrame(0x105442c0, 0x105f4000, 0x10008, 0x10008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:155 +0x104
github.com/xtaci/smux.(*Session).recvLoop(0x105442c0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:190 +0x1d8
created by github.com/xtaci/smux.newSession
	/opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:58 +0x314

goroutine 11 [select]:
github.com/xtaci/smux.(*Session).keepalive(0x105442c0)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:238 +0x360
created by github.com/xtaci/smux.newSession
	/opt/mipsgo/src/gocode/src/github.com/xtaci/smux/session.go:59 +0x340

goroutine 12 [select]:
main.scavenger(0x10544380)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:423 +0x648
created by main.func·005
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:373 +0x2608

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0x105457b8, 0x72, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:84 +0x4c
net.(*pollDesc).WaitRead(0x105457b8, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:89 +0x48
net.(*netFD).readFrom(0x10545780, 0x10572800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x774c8b60, 0x1053a2b0)
	/opt/mipsgo/src/net/fd_unix.go:269 +0x418
net.(*UDPConn).ReadFromUDP(0x1051c340, 0x10572800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/udpsock_posix.go:67 +0x108
net.(*UDPConn).ReadFrom(0x1051c340, 0x10572800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/udpsock_posix.go:82 +0x104
github.com/xtaci/kcp-go.(*UDPSession).receiver(0x1050c1b0, 0x10544440)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:582 +0x124
created by github.com/xtaci/kcp-go.(*UDPSession).readLoop
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcp-go/sess.go:598 +0x84

goroutine 15 [select]:
main.handleClient(0x774ca2f0, 0x1051c268, 0x774ca310, 0x10568080)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:70 +0x65c
created by main.func·005
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:402 +0x30ec

goroutine 16 [select]:
github.com/xtaci/smux.(*Stream).Read(0x10568080, 0x1061e000, 0x8000, 0x8000, 0x0, 0x774c49c0, 0x1051c068)
	/opt/mipsgo/src/gocode/src/github.com/xtaci/smux/stream.go:57 +0x38c
io.Copy(0x774ca390, 0x1051c2b8, 0x774ca348, 0x10568080, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:362 +0x208
net.genericReadFrom(0x774ca330, 0x1051c268, 0x774ca348, 0x10568080, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/net.go:404 +0xb4
net.(*TCPConn).ReadFrom(0x1051c268, 0x774ca348, 0x10568080, 0x774ca378, 0x1051c268, 0x0, 0x0)
	/opt/mipsgo/src/net/tcpsock_posix.go:72 +0x118
io.Copy(0x774ca330, 0x1051c268, 0x774ca348, 0x10568080, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:358 +0x154
main.func·001()
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:64 +0xd8
created by main.handleClient
	/opt/mipsgo/src/gocode/src/github.com/xtaci/kcptun/client/main.go:64 +0x448

**Comment by dfangboy** [comment]
snappy和mips mipsle 有冲突。关闭压缩就没问题了。
