### ISSUE TITLE
KCPTUN服务端到底怎么安装？

### ISSUE THREAD

**Issue by myveb** [xtaci/kcptun#226]
google了半天，也只找到第三方写的一键脚本，官方有手动安装教程吗？首页说明里的看不太明白

**Comment by xtaci** [comment]
1. 下载
2. 解压
3. 运行

完成

**Comment by myveb** [comment]
感谢大神

**Comment by ftsm** [comment]
下载后解压开,然后直接命令运行或者做个配置文件再运行
我开始也是弄的别人的一键脚本,各种安装有问题,后来直接解压开就可以运行,随机启动做下rc.local就好了

**Comment by myveb** [comment]
@ftsm 能告诉是哪个命令不？我已经下载解压了

**Comment by myveb** [comment]
@xtaci 请问大神，运行的命令是什么呢？

**Comment by lizongzeshunshun** [comment]
client(win)直接命令行
`client_windows_amd64 --参数`

server(linux)
`./server_linux_amd64 --参数`

32位改amd64即可

**Comment by myveb** [comment]
@lizongzeshunshun 谢谢，服务器提示没有server_linux_amd64这个文件，我是在kcptun-master目录下操作的

**Comment by lizongzeshunshun** [comment]
@redapple0204 你想自己编译？

**Comment by lizongzeshunshun** [comment]
@myveb 你想自己编译？

**Comment by myveb** [comment]
@lizongzeshunshun 我只是想运行

**Comment by lizongzeshunshun** [comment]
@myveb 下载release...

**Comment by myveb** [comment]
@lizongzeshunshun 算了，我暂时放弃，谢大神

**Comment by ftsm** [comment]
你要看你的是什么版本,你在服务器要下载对应版本的程序
例如我的是centos6 我就下载的是kcptun-freebsd-amd64-20161009.tar.gz这个最新的
例如我当前的路径是/root
makedir kcptun
cd kcptun
wget 上面的包地址
tar -zxf kcp*.gz
然后在/root/kcptun/下就有server_linux_amd64这个文件了
然后vi /etc/rc.local
加一行 /root/kcptun/server_linux_amd64 -l :服务器KCP监听端口 -t 127.0.0.1:本地SS端口 -key 加密密钥 -crypt salsa20 >/root/kcptun.log 2>&1 &
wq保存后reboot
等重新启动完毕用ps x看看进程有没有KCP有就运行成功了.
