### ISSUE TITLE
kcp+socks5,最终socks5的udp穿透失效了

### ISSUE THREAD

**Issue by TongxiJi** [xtaci/kcptun#229]
kcptun只是针对tcp,没有转发udp,  这应该不算是一个bug..
我只是想问下未来有支持么...
因为像某些游戏确实是tcp udp都跑,比如小学生游戏LOL.

我现在在用kcptun+socks5玩欧洲wow私服, 8美金的5-10%的丢包小鸡,游戏都不掉线,真是逆天了,真是为游戏而生的东西啊!

**Comment by xtaci** [comment]
没有计划支持udp转发，不过如果能有个第三方程序把udp转换为tcp，然后tcp转回udp，应该就解决了。

**Comment by TongxiJi** [comment]
说起来,badvpn的tun2socks,处理udp转发就是自己搞了一套(转为tcp,远程有个udpgw处理),并没有直接用socks5原生协议的方式,还真是歪打正着.哈哈.
所以kcptun最终是否支持udp转发,我也不执着.纯粹想问一下.

**Comment by TongxiJi** [comment]
还是想用sockscap64+kcptun+socks5玩LOL,可是kcptun不支持udp啊,  直接卡读条界面了,
能否加个选项对于普通udp包直接转发而不经过任何处理呢?直接block感觉好不舒服

**Comment by xtaci** [comment]
ovpn over kcptun?

**Comment by diyism** [comment]
大牛参考下 https://github.com/letolab/udp-over-tcp?files=1 的代码呢, 能把udp也搞定的话, iptables tproxy+kcptun+socks5 udpassociate就绝配了

**Comment by diyism** [comment]
找到个简单解决方案:
Client side:
socat -T15 udp4-recvfrom:53,reuseaddr,fork tcp:localhost:10053
kcptun_client_linux -r "vps_ip:60053" -l ":10053" -mode fast2 -key "fuck ccp fuck ccp"

Server side:
kcptun_server_linux -t "127.0.0.1:10053" -l ":60053" -mode fast2 -key "fuck ccp fuck ccp"
socat tcp4-listen:10053,reuseaddr,fork udp:8.8.8.8:53
