### ISSUE TITLE
这发包是不是不太正常

### ISSUE THREAD

**Issue by kxmp** [xtaci/kcptun#23]
我客户端才600k速度
然后服务端发送是4000多KB的速度...
最可怕的是客户端速度跑到1MB左右
服务端差不多用了10-12MB左右速度.....

**Comment by xtaci** [comment]
正常啊，上下行本来就不对称， sndwnd可以调大试试

**Comment by kxmp** [comment]
@xtaci 你意思说我如果用他看视频 我客户机用了400k网速
服务器就需要用400k*10=4000k左右网速么?! 这个利用率这么低哇!!

**Comment by xtaci** [comment]
这个和参数又关系， 首先必须了解一点，实时性和带宽利用率是不可调和的。
降低实时性，增大有效载荷比的方法：
1. 关闭acknodelay
2. 两端关闭 前向纠错 -fec 0
3. 提高mtu -mtu 1400

**Comment by kxmp** [comment]
改了参数也都差不多.....
看起来只能给游戏用...

**Comment by kxmp** [comment]
今天测了下新版 发现改善很大
默认参数 效率比以前高多了.  随便测了下发现流量占用是1.6
抗丢包能力也秒杀以前了.

**Comment by kxmp** [comment]
新版测了测 发现越来越稳定 占用也很好.
当初提到的那个发包 应该是服务器直接把数据扔给buffer了 这个也算的.
实际流量根本没那么大.
