### ISSUE TITLE
用了扩软博客的一键安装包，出现Exited too quickly错误

### ISSUE THREAD

**Issue by myveb** [xtaci/kcptun#230]
安装包地址是这里：https://blog.kuoruan.com/110.html
安装成功了
但是在服务端使用service supervisord start时，出现：
```
 * Starting supervisord:                                                 [ OK ]
kcptun                           BACKOFF   Exited too quickly (process log may have details)
```
使用supervisorctl start kcptun时，出现：
`FATAL     Exited too quickly`

我先后用了debian7和ubuntu14.04，都是这个情况，求大神指点

**Comment by xtaci** [comment]
@kuoran

**Comment by ftsm** [comment]
去查一下supervisord 的配置
在/etc/supervisor/conf.d下看看kcptun.conf的配置
如果kcp指定了-c参数加载配置的话去看一下kcp本身的配置文件是否有错

**Comment by kuoruan** [comment]
看一下 supervisor 的日志，里边应该有说明
