### ISSUE TITLE
运行时间一长后出现 getsockopt: connection refused

### ISSUE THREAD

**Issue by guojian0624** [xtaci/kcptun#232]
centOS 7 x64 vultr的vps
安装shadowsocks-go，KCP版本20161009
config.json文件如下
{
    "listen": ":29001",
    "target": "127.0.0.1:9001",
    "key": "XXXXX",
    "crypt": "aes",
    "mode": "fast2",
    "mtu": 1400,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10,
    "log": "/root/kcptun/kcptun9001.log"
}
服务器刚运行的时候是好好的。过一段时间后就无法连接了。单独使用SS都不行。
log里出现
2016/10/22 06:50:04 dial tcp 127.0.0.1:9001: getsockopt: connection refused
2016/10/22 06:50:34 broken pipe
要重启服务器就好了。

**Comment by haroldTlan** [comment]
你好，请问问题解决了吗，除了重启服务器之外还有别的办法吗

**Comment by guojian0624** [comment]
@haroldTlan 后来该用了libev的SS就没有这问题了。
