### ISSUE TITLE
某些情况下使用有风险，大家可以关注下

### ISSUE THREAD

**Issue by kelvinblood** [xtaci/kcptun#233]
可能是我的服务器本来就被关照过，偶尔会有端口被GFW。

偶然使用了kcptun，两天后整个IP在国内就无法访问了。

所以大家使用的时候要斟酌一下。如果你发送的包有可能会被关照，那么使用kcptun就加大了风险。

**Comment by feizhenzhuang** [comment]
我觉得是不是ISP封了UDP包啊
