### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by Biercenter** [xtaci/kcptun#234]
今天用wiki里的教程编辑路由器版出错了，换成docker还是不行。请大家帮我看看。
代码：
/go/src/golang.org/x/net/ipv4 # go get -v golang.org/x/net/ipv4
golang.org/x/net/ipv4
# golang.org/x/net/ipv4

./zsys_linux_mips32le.go:7: sysIP_TOS redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:7
./zsys_linux_mips32le.go:8: sysIP_TTL redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:8
./zsys_linux_mips32le.go:9: sysIP_HDRINCL redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:9
./zsys_linux_mips32le.go:10: sysIP_OPTIONS redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:10
./zsys_linux_mips32le.go:11: sysIP_ROUTER_ALERT redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:11
./zsys_linux_mips32le.go:12: sysIP_RECVOPTS redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:12
./zsys_linux_mips32le.go:13: sysIP_RETOPTS redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:13
./zsys_linux_mips32le.go:14: sysIP_PKTINFO redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:14
./zsys_linux_mips32le.go:15: sysIP_PKTOPTIONS redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:15
./zsys_linux_mips32le.go:16: sysIP_MTU_DISCOVER redeclared in this block
    previous declaration at ./zsys_linux_arm64.go:16
./zsys_linux_mips32le.go:16: too many errors

还有下面这个命令怎么用？ 搬瓦工debian8,输入后回车没反映。谢谢
kill -SIGUSR1 pid 可以在控制台打印出SNMP信息

**Comment by xtaci** [comment]
https://github.com/bettermanbao/openwrt-kcptun

**Comment by wxyzh** [comment]
go get golang.org/x/net
