### ISSUE TITLE
日志提示：set tcp 127.0.0.1:8388: setsockopt: no buffer space available

### ISSUE THREAD

**Issue by renhuailin** [xtaci/kcptun#235]
后台的日志里打印这个：set tcp 127.0.0.1:8388: setsockopt: no buffer space available， 这是问题吗？反正看youtube还行，没掉。

**Comment by xtaci** [comment]
sysctl可以调大sock buffer的最大约束

**Comment by renhuailin** [comment]
这个对性能有影响吗？如果有，mac下怎么调？

**Comment by xtaci** [comment]
在高速传输的时候才会影响，默认值4MB是比较安全的。可以调小。
