### ISSUE TITLE
有没有动态调参的可能？

### ISSUE THREAD

**Issue by metalwood** [xtaci/kcptun#236]
就是同一条连接，传输数据的过程中，根据网络状况动态设定kcptun的参数

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/28
很早以前想过，结论是无法评估什么是最优参数，很主观的评判，大家对最优的定义不同。
而且，动态调整非常容易受到ISP干扰。

**Comment by metalwood** [comment]
谢谢！我的意思是，允许在连接已建立正在传输的过程中动态调整，收发自动保持同步，相当于提供一个动态调参的接口，而具体参数调成多少，kcptun不管。

**Comment by xtaci** [comment]
提供接口不如直接重启啊

**Comment by metalwood** [comment]
网络状况会变化，为了适应网络变化而调整参数，但有些尽量不掉线的应用场景下，调参就重启，难以接收。
