### ISSUE TITLE
使用kcp后，看了很多帖子，调整了好久的参数，速度很不稳定，求帮助

### ISSUE THREAD

**Issue by vh2h** [xtaci/kcptun#238]
服务端：搬瓦工，443端口

网络环境：100M教育网

参数如下：-autoexpire 60 -crypt "salsa20" -mode "fast2" -mtu 600 -dscp 46 -nocomp -sndwnd 500 -rcvwnd 900

现象：服务端同时安装了finnalspeed和kcptun。
若在windows使用finalspeed看youtube或者下载一些东西，速度很稳定在30-50Mbps，飞一般的感觉。

关掉电脑，同样一根网线，连上路由器，用安卓端的ss+kcp，youtube速度就是（单位：KB/S）300，0，200，300，0，200，300，20，0......这种，跳跃极大，然后过个10分钟就断流了，qq都发不出。尝试过调小mtu，调整加密方法，调整 -sndwnd  -rcvwnd ，设置dscp为0等，好像都没有用。

电脑端没有装kcp因为有finnalspeed，finnalspeed很快。

我使用kcp的唯一目的就是在手机上看youtube和下载google play的软件，其他用途基本没有。

我的搬瓦工流量根本用不完，不用考虑流量的问题。我的下载速度只需稳定在300KB/s左右就行，无需很高，但求稳定+不断流就好。

调整了一整天没有调好，请各位大神给予帮助，谢谢

**Comment by xtaci** [comment]
fs是模拟的tcp，和kcptun的udp有本质的不同，信道质量差非常多。

可以试试 FEC 5:5，如果不能改善，也没有办法了。

**Comment by vh2h** [comment]
@xtaci 谢谢您的及时回复，请问如何调整FEC 5:5，看不懂这是什么意思。服务端和客户端都需要调整吗？谢谢！

**Comment by xtaci** [comment]
服务器: ./server_linux_amd64 -t "服务器IP地址:8388" -l ":4000" -datashard 5 -parityshard 5
客户端: ./client_darwin_amd64 -r "服务器IP地址:4000" -l ":8388" -datashard 5 -parityshard 5

是的

**Comment by vh2h** [comment]
@xtaci 好的，我去试试，非常感谢 :)

**Comment by vh2h** [comment]
@xtaci  唉，反而更慢更不稳定了，可能是校园网的udp丢包过于严重了，还是用回以前的算了。

十分感谢您能做出这么好用且通用的工具，这真是很伟大的一件事情，谢谢。顺祝好！

**Comment by xtaci** [comment]
嗯，校园网没有太好的办法。

**Comment by wang20150419** [comment]
校园网不至于这么烂，kcptun youtube 5000kbps没问题。ipv6的话，就用不着翻墙了，直接上youtube，大概 10000kbps 以上。

**Comment by yerlur** [comment]
安卓端怎么配置啊
kcp参数

**Comment by lijijordan** [comment]
请问搬瓦工的vps好些 还是 linode的日本节点速度快？
