### ISSUE TITLE
server端进程无故退出

### ISSUE THREAD

**Issue by Cye3s** [xtaci/kcptun#24]
版本：kcptun-linux-amd64-20160602.tar.gz
运行环境：CentOS Linux release 7.2.1511 (Core)  x64位  512M内存的VPS
运行命令：./kcptun_server -t "127.0.0.1:1583" -l "0.0.0.0:1755" -mtu 1480 -key "xxxxx" >/dev/null 2>&1 &
现象：运行一段时间后server端进程消失

把运行日志输出到log文件，也只能看到某个stream open后就没有后继日志了，进程就退出了
而Ubuntu 14.04.4 x64 PC机上的客户端跑得很稳定

**Comment by xtaci** [comment]
可以检查下dmesg，是不是oom killer

**Comment by Cye3s** [comment]
dmesg没看到，不过发现更新了20160603的版本，我用新版再试下看看

**Comment by Cye3s** [comment]
新版也是会自动退出，用nohup运行就行了，跑了3天都正常

**Comment by xtaci** [comment]
正常的， 一般是用tmux开个窗口用
