### ISSUE TITLE
How to tunnel multiple TCP services through one KCP connection?

### ISSUE THREAD

**Issue by vimagick** [xtaci/kcptun#240]
My ISP has blocked all IP traffic except `53/udp`.
I'm running kcptun on my VPS to tunnel ss-server.

```
         HOME       ->            ISP            ->            VPS
       8388/tcp                 53/udp                      8388/tcp
```

The problem is I cannot tunnel other TCP services any more.
I need to buy another VPS to bind `53/udp`.

It'll be very helpful if I can reuse the kcp tunnel for multiple services.

Thanks! :+1:

**Comment by xtaci** [comment]
maybe ovpn?

**Comment by vimagick** [comment]
Great solution. 👍 

Do one thing, do it well!

**Comment by kmahyyg** [comment]
@vimagick Could you please give me some guidance?

**Comment by vimagick** [comment]
@kmahyyg

I can run openvpn at port 53/udp.
Client will send all traffic to VPN.

**Comment by xtaci** [comment]
@kmahyyg  ovpn/tcp over kcptun
