### ISSUE TITLE
v20161028 版在win10X64版OS Build14393.351内存控制反而不入v20161025版

### ISSUE THREAD

**Issue by wansen** [xtaci/kcptun#241]
![capture](https://cloud.githubusercontent.com/assets/15998863/19797569/8639c61c-9d1e-11e6-9e4c-ed14cb9250a3.PNG)
当看youtube时，如图，一直增涨中。

**Comment by xtaci** [comment]
需要在相同条件下对比，并且需要观察稍微长一点的时间。

**Comment by wansen** [comment]
![capture](https://cloud.githubusercontent.com/assets/15998863/19797716/54596f98-9d1f-11e6-81f5-698586e533d0.PNG)
退出浏览器后，这两个进程也不能相应的释放内存。
