### ISSUE TITLE
服务端使用配置文件客户端使用命令行参数无法通信

### ISSUE THREAD

**Issue by powerofchaos** [xtaci/kcptun#242]
客户端os：win7 x32
服务端os：centos 6.8 x64 
版本：20161025
在一方使用命令行传参，一方使用-c指定配置文件入参时，无法进行通信。但当双方同时使用配置文件或命令行传参时，正常通信。
客户端使用的命令参数如下：-l :1090 -r serv_ip:4436 --crypt xor --mtu 1300 --sndwnd 256 --rcvwnd 2048 --mode fast2 --nocomp --datashard 70 --parityshard 30
服务端使用的命令行参数：-l :4436 -t 127.0.0.1:4432 --crypt xor --mtu 1300 --sndwnd 2048 --rcvwnd 2048 --mode fast2 --nocomp --datashard 70 --parityshard 30
客户端使用-c入参时：
-c client_nocrypt.json
{
    "localaddr": ":1090",
    "remoteaddr": "serv_ip:4436",
    "key": "",
    "crypt": "xor",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1300,
    "sndwnd": 128,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}
服务端端使用-c入参时：
-c server_nocrypt.json
{
    "listen": ":4436",
    "target": "127.0.0.1:4432",
    "key": "",
    "crypt": "xor",
    "mode": "fast2",
    "mtu": 1300,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}

**Comment by xtaci** [comment]
"key": "", 默认值不对

**Comment by powerofchaos** [comment]
试了一下确实是key的问题，我还以为xor就不用配置key了。。
