### ISSUE TITLE
Different use case: throughput 

### ISSUE THREAD

**Issue by zuzzurro** [xtaci/kcptun#243]
Hi, this is mostly a question for the moment.
I have been playing a little with this nice tool and I would like to know if this tool could be used for streaming purposes.

Right now it seems to me that it may not work that well when pushing multiple streams at high bitrates through a wan link. I tried pushing three 25Mbps streams and while the one works fine and is able to run at full speed, the additional streams seem to saturate the link at around 45Mbps.

The client uses 70% of the cpu (without compression and encryption). I also tried playing with the window sizes but it does not seem to have any effect.

The bandwidth between client and server is pretty large (more than 300Mbps according to nuttcp).

Do you guys think this should work?

**Comment by xtaci** [comment]
have you tried -sockbuf options?

all options are here:
https://github.com/xtaci/kcptun/blob/master/client/config.go#L29

**Comment by xtaci** [comment]
besides, it mostly depends on the loss rate of your wan link. 
try adjusting anything related to loss rate.  mtu, FEC.

**Comment by zuzzurro** [comment]
Well, I know the link is good and that the problem seems to be more on the application side. In any case I will try the sockbuf option too.
My question was more about the way kcptun is currently used vs what I am trying to do. I can expect that if the scenarios are different it may not be tuned to the one I need..

**Comment by xtaci** [comment]
kcptun is a tool for experimenting kcp protocol(kcp-go), and kcp-go is intended mainly for RTS game in my company, in order to get lower latency.

but some people founds kcptun alone is very suitable for censored network with high loss rate（eg: > 30% packet loss)。
