### ISSUE TITLE
使用一段时间后掉速，掉到差不多无法连接。重启服务即可解决，何解

### ISSUE THREAD

**Issue by cjjdaq** [xtaci/kcptun#245]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.
1. Check your `-key xxx` for at least 3 times, **_MAKE SURE**_ both sides share the same secret.
   密码相同
2. `-nocomp, -datashard, -parityshard,  -key, -crypt` **_must be the same**_ on both side.

--crypt salsa20 --nocomp --dscp 46 --mtu 1350 --mode fast2
-datashard, -parityshard未设置
1. Did you correctly set the **_-target**_ on the server side?

target了ssr的端口
1. **_MAKE SURE**_ `telnet target port` on your server successful(don't ask me why couldn't).

ssr工作正常。客户端直链可以正常工作。
1. Does your **_firewall allows UDP**_ communications? (including your ISP Cable-Modem)
   中国电信 未对udp封锁
2. Are you using the **same version** for both client & server
   客户端与服务端使用最新的1028版。每个新版出来立即升级
3. Are you using the **latest release**?
   是
4. Which **OS** do you use?

服务器用的centos x64 客户端用openwrt x64
1. Which end for this issue related to, **client or server**?

环境，电信100M， vultr，ssr通过kcptun加速。ping值160，丢包率5%以内。

当前面临的问题：正常情况下，fast测试一般20M左右。通过拨号换ip，换的特定的ip，fast会稳定在40M左右。可能是qos的问题。国际出口大上海魔都。

不正常的问题，一般用着用着就没速度了，表现在我持续看youtube视频。到最后速度掉没了，连144p都无法看，打开墙外网站也超级慢了，或者直接就不能翻墙了。
这时候的处理方法。重启服务端的kcptun服务，客户端重新提交（等于重连）。一切恢复正常。

**Comment by xtaci** [comment]
可以通过 -autoexpire 300 设定自动重连

**Comment by cjjdaq** [comment]
感谢恢复，使用此法看看有没有改善

**Comment by devcodewak** [comment]
autoexpire 定时重连，这个参数好。
@xtaci 请看下 gitter

**Comment by cjjdaq** [comment]
@xtaci 使用autoexpire参数无效呀。必须要将进程关掉重新启动才有效果

**Comment by xtaci** [comment]
建议你更换端口

**Comment by cjjdaq** [comment]
好的，现在用的是65531端口，等再掉速的时候更换看看效果。

**Comment by cjjdaq** [comment]
好像使用autoexpire会使游戏掉线，目前换成了443端口，去掉了autoexpire参数

**Comment by kmahyyg** [comment]
端口改低点，过高端口有些机房会qos

**Comment by ljyloo** [comment]
我这里也是同样的情况，不过我这里不是掉速，是直接用不了了。重启服务端与客户端才能重新使用。广州电信

**Comment by kmahyyg** [comment]
降低端口号，调整服务器sysctl.conf

2016年11月6日 00:20，"LittleBlackBird" <notifications@github.com>写道：

**Comment by ljyloo** [comment]
服务器sysctl.conf具体要怎么改？

**Comment by cjjdaq** [comment]
从10号版本开始，重启服务都无法连接了。而且直连ssr没有问题。

**Comment by xtaci** [comment]
10号版本有问题，已删除。 用11号

**Comment by cjjdaq** [comment]
不知道是什么原因，早上升级了11好的版本，也是一会就断开了，重启也没有用，中午换回5号版本，使用良好。

**Comment by cjjdaq** [comment]
是不是服务端用32位，客户端也必须要32位？

**Comment by zzw6776** [comment]
一样的情况，11号版本，默认fast2配置，电脑看u2b没压力，不会断开
手机挂ss
上googleplay下载东西差不多2m/s  持续30秒会中断，无任何网络链接，大概10~20秒后又会自己恢复
@xtaci

**Comment by cjjdaq** [comment]
@xtaci 我发现我的问题和其他断流的人一样，闲置一段时间突然使用服务端就broken pipe无法翻墙，改端口，改mtu都没办法得到改善。服务器ip一天一换都没用。
