### ISSUE TITLE
你好，请问能否把kcptun添加到Windows服务里面

### ISSUE THREAD

**Issue by caicy1991** [xtaci/kcptun#248]
首先，非常感谢作者的无私分享，能用上作者的软件真的非常荣幸！
我的服务端是Debian8，客户端是Windows7，参数调节后可正常使用，主要是用来玩韩国游戏的，VPS是韩国的，中间加了上海阿里云转发。
但现在的想法就是能否把Windows的客户端命令启动方式添加到Windows Service里面，这样就不用在使用的时候还要注意那个命令符窗口，避免不小心关闭了。网上找到创建服务的命令是sc create，通过这个命令创建成功后的服务并不能正常启动，想问下是方法不对还是客户端不支持？

**Comment by wang20150419** [comment]
使用  nssm, https://nssm.cc/download

**Comment by dfdragon** [comment]
还有一种不用服务的办法：新建计划任务，“触发器”设定为开机自动运行，“操作”中填写你要运行的命令行，最后把这个计划任务的用户改为SYSTEM，这样可以开机运行且避免出现控制台窗口。

**Comment by wxyzh** [comment]
nssm比较好用

**Comment by caicy1991** [comment]
@wang20150419 @wxyzh 谢谢回复，能否告知下nssm具体的使用步骤

**Comment by wang20150419** [comment]
使用方法在这里： https://nssm.cc/usage
