### ISSUE TITLE
stream刚open就瞬间closed，无法使用

### ISSUE THREAD

**Issue by zhangcx93** [xtaci/kcptun#249]
从昨天开始，开启kcptun以后无法连接，server和client端log显示所有的请求stream刚open就closed，参数完全没改过，重新开也无效。
log如下：
```
2016/11/02 01:13:58 stream opened
2016/11/02 01:13:58 stream closed
2016/11/02 01:13:58 stream opened
2016/11/02 01:13:59 stream closed
2016/11/02 01:13:59 stream opened
2016/11/02 01:13:59 stream closed
2016/11/02 01:14:01 stream opened
2016/11/02 01:14:01 stream opened
2016/11/02 01:14:02 stream closed
2016/11/02 01:14:02 stream opened
2016/11/02 01:14:02 stream closed
2016/11/02 01:14:02 stream opened
2016/11/02 01:14:02 stream closed
2016/11/02 01:14:02 stream closed
2016/11/02 01:14:03 stream opened
2016/11/02 01:14:03 stream closed
2016/11/02 01:14:03 stream opened
2016/11/02 01:14:04 stream closed
```
server端参数如下：
`./server_linux_amd64 -t 127.0.0.1:443 -l :4000 --mode fast2 --sndwnd 1024 --rcvwnd 1024
`client端参数如下：
`./client_darwin_amd64 -r MY_IP:4000 -l :443 --mode fast2 --rcvwnd 1024 --sndwnd 256
`
然后不用kcptun直接连shadowsocks就没有问题。

**Comment by baggiogogo** [comment]
换个端口试试

**Comment by zhangcx93** [comment]
@baggiogogo 刚试了把端口改了，把--mode改成fast，或者normal，把加密方式，密码都改了，都是一样的结果。

**Comment by baggiogogo** [comment]
如果一切参数你确定没问题，那就不用想了，引起注意了，不管是ISP还是GFW，我有个VPS，有两个IP，其中一个IP，kcptun无论如何都连不上，症状刚开始和你这个一样，也是开始好好的，后来突然有一天就OVER。

**Comment by zhangcx93** [comment]
@baggiogogo 但是无论是ssh访问还是ss直接使用都没问题，kcptun也是能够连上只不过会瞬间closed掉。而且不开kcptun无论是开启或者关闭ss的UDP Forwarding都可以用，也就是说UDP还是好的，没被封。这个症状应该值得研究。

**Comment by baggiogogo** [comment]
是的，一样的，并不是封IP，只是kcptun无法连接，我在一个帖子里面说过这个问题，我这个IP到现在也依旧这个症状。如果你感兴趣，可以多试试不同的端口，我试过，很BT，可能一些端口可以正常连接，一切OK，但不超过10分钟就废掉，再连，就连不上了。

**Comment by kmahyyg** [comment]
试试ssr的那个udp over tcp/tcp over udp，请给下你所在地和本地isp及接入带宽，尝试调小mtu ，或者参考 #137 策略三。不排除协议被特征检测的可能……

**Comment by zhangcx93** [comment]
@kmahyyg 用的武汉电信50m，尝试了策略3的参数无效，尝试了mtu调成了1000无效。

**Comment by baggiogogo** [comment]
![default](https://cloud.githubusercontent.com/assets/21306212/19900923/381eb732-a0a0-11e6-9d3a-c0f6865d1bcc.JPG)

**Comment by choicky** [comment]
有朋友在天津，宽带好像是广电还是其他的网络。

连ss都用不了。症状类似，就是新端口号刚开始能用，几分钟后就会永远挂掉；换一个新端口，也是几分钟就挂掉。

**Comment by ifreefly** [comment]
最后解决了吗？
我也遇到了这种情况，但是用手机客户端可以连接上，很奇怪。。。

**Comment by zhangcx93** [comment]
@ifreefly 我放弃治疗这个vps了。。不过你手机能连上说不能可以拯救一下。。

**Comment by ifreefly** [comment]
@zhangcx93 搞定了
我遇到的问题是这样的：
1.我机器上装了迅雷极速版本，装了这个版本以后无法使用3.x版本的shadowsocks
2.在使用低版本的2.5.6的shadow的时候参数配置错了。

因此我的解决方案是使用低版本的shadowsocks（2.5.6），然后正确配置参数。

**Comment by ifreefly** [comment]
@zhangcx93 建议你先试试手机上能否正常连接

**Comment by silvernoo** [comment]
把ss-server端的一次性连接关掉就可以用了，你可以试试，我用的libev版

**Comment by Matiejun** [comment]
大家有解决的办法吗？

**Comment by vincentor** [comment]
> 把ss-server端的一次性连接关掉就可以用了，你可以试试，我用的libev版

支持这个答案，我参考这个回答把 ss server 的 fast open 参数去掉就可以了

**Comment by PeakIO** [comment]
> 把ss-server端的一次性连接关掉就可以用了，你可以试试，我用的libev版

非常感谢，解决了。记得把ss和kcptun重启一下。

**Comment by tortoo** [comment]
@vincentor @PeakIO  请问下，这个一次性连接的英文是什么？是fast open吗？我之前在/etc/sysctl.conf 中加入了net.ipv4.tcp_fastopen = 3这句，然后config里把fast open值改为true，这应该就开启了它，结果ss-local的log里启动kcptun之前总会启动fast open，后面就反复stream opened和steam cloesd。但按你们说的貌似无法去掉它，我在/etc/sysctl.conf 里把这句用# 注销掉了，也在ss sever中config.json中把fast open值改为false，然后重启ss和kcptun，结果症状依旧，log里还是会在启动kcptun之前启动fast open。最后我在config.json中删了fast open这一行，再重启ss和kcptun，状况还是一样，没有变化。

想问下你们具体是怎么做的，这个一次性连接是否就是fast open，如何彻底关闭它？
