### ISSUE TITLE
如何评价kcptun的加密策略，是否存在安全隐患？

### ISSUE THREAD

**Issue by oozj** [xtaci/kcptun#25]
作者：任思远
链接：https://www.zhihu.com/question/45556316/answer/99388655
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

随便看了一下，可以看出以下问题出来：

第一，这个设计里面说“消息摘要采用MD5，杜绝非法篡改”这是完全错误的。防止消息篡改要用Message Authentication Code，不能用Hash function，不管是怎么Hash都是不能防止篡改的。更何况MD5做Hash根本不合格，早破解成筛子了。正确的做法是AEAD Cipher，比如AES-GCM或者chacha20-poly1305。

第二，我简单的看了一下源码，似乎两个方向（客户端到服务端和服务端到客户端）用的是相同的IV（encryptor和decryptor用同样的IV的初始化）。这意味着AES-CFB有IV重用，这是绝对的错误用法，直接导致攻击者能够解密数据包。（作者扯了半天的所谓OTP只是所有加密算法的基本要求，然而如果我的理解没错，他没用对）。

第三，基于UDP的安全协议都有被replay attack的可能，这个协议好像没有写怎么防止？

第四，这个PSK是程序随机生成还是用户指定？如果是用户指定，用SHA256生成key是不够的，因为用户指定的key往往强度不够，需要用key stretching function比如scrypt或者pbkdf2-hmac来处理。

可能还会有别的问题。

**Comment by xtaci** [comment]
协议层不需要考虑这些问题，  安全是TLS做的。

**Comment by renzhn** [comment]
老罗：知乎上有很多太监在讨论体位

**Comment by d0w0b** [comment]
我来回答下有关协议加密的重要性
由于众所周知的原因，协议头部分的数据非常的有价值，比如来去地址，这就给大数据分析提供了可能，看看你去了哪？经常跟谁？从而分析你的行为，这也是行为建模里常用的手段，明文的数据越少，越难发现你是干什么的，特征是什么。虽然损失性能，但是提高了分析难度，在目前的对抗查水表的手段里，尽可能的加密非常的重要
我也是小白，但是学长在做课题时说过这个问题，所以就现学现卖了

**Comment by sueccku** [comment]
加密和混淆是两回事，很多时候真正需要的是混淆，攻击也极少有破解内容的，基本都是干扰协议让连接没法继续。
如果你说的加密是防止内容被解密的话，我认为他尽管不算顶尖，但已经够了：第一，如果你没有被盯上，只要很简单的加密就能达到加密目的，因为实时解密对设备要求很大，窃听者不可能对每一个人都解密，也不可能镜像每一个人的数据然后对每个人都解密，你要是被盯上，就是用aes9999加密有什么用，上超算还不是分分钟的事，而且还要考虑正常传输下服务器、客户端的运算能力，算法不能太难，另一方面，kcptun是一个传输用的协议，安全性是两端要做的事，不是传输通道要做的事，就目前的网络环境而言，你要假想传输通道是不安全的，就像尽管说tcp有一定防丢包机制，但几乎每一个重要的软件都是假想tcp完全不可靠。
如果这里的加密是指为了混淆而加密，或者为了去除数据头的特征，kcptun就显得有点业余了，对抗查水表是相当羸弱的

**Comment by xtaci** [comment]
-ldflag 不仅能注入VERSION，也能注入SALT。这个问题不要再讨论了，言尽于此。
