### ISSUE TITLE
Windows client端 命令行启动问题

### ISSUE THREAD

**Issue by Yifei0727** [xtaci/kcptun#252]
在用的所有Windows10 x64
client是 7月份至今 版本
命令行脚本启动读取不到提供的参数
编写 `runkcp.bat`
```
client_windows_amd64.exe -r my.kcpserver.com:443
```
实际配置不同
双击bat 执行后 显示版本等信息
数秒后显示 找不到 vps
如果先启动一个命令行 cmd
在命令行中将 上述内容粘贴执行则正常。
经过调试，发现通过调用shell来启动的都是无法读取到 后面的参数的，因此导致这个问题。
因此我一直没有一种能一键启动的脚本。
不知道是不是go 语言问题？
我想问下作者有意向增加这方面的优化？

**Comment by wxyzh** [comment]
用配置文件

張艺飞 <notifications@github.com>于2016年11月3日周四 18:01写道：

**Comment by Yifei0727** [comment]
这样啊，我说一直都见这方面有支持呢，多谢🙏
但为啥从bat启动就读不到提供的参数呢？

wxyzhen <notifications@github.com>于2016年11月3日周四 18:03写道：

**Comment by peakvision** [comment]
我是参数启动，没有问题

**Comment by Yifei0727** [comment]
@peakvision 命令行的确没有问题。
问题在于如果编写将你的命令行内容通过 bat脚本或者 vb 亦或者Python 等 启动脚本都是启动后 获取不到命令行参数 导致不能使用

peakvision <notifications@github.com>于2016年11月4日周五 01:32写道：

**Comment by peakvision** [comment]
我是一个.bat文件

在 2016年11月4日 下午9:43，張艺飞 <notifications@github.com>写道：

**Comment by Yifei0727** [comment]
如果`runkcp.bat`
```
client_windows_amd64.exe -c kcp-config.json
```
@wxyzh 这样就可以用了，让人匪夷所思 - -
为啥第一种方式就不行呢 - -！

**Comment by peakvision** [comment]
有可能你的bat文本文件内含有特殊字符，特别是你的内容经过浏览器处理过。粘贴到cmd.exe会过滤掉特殊字符。
