### ISSUE TITLE
关于程序的结构有几个不成熟的建议

### ISSUE THREAD

**Issue by gzmud** [xtaci/kcptun#253]
（1）fec层和kcp层在作用上有重叠，是否可以合并优化？
（2）fec现在使用rs码，采用 ldpc码是否更接近香农极限，而且可以实现某些自适应算法？
（3）sndwnd、rcvwnd参数，能否改成全局控制的带宽控制参数sndbw，rcvbw而不是单个session的？
（4）server端和client的sndbw，rcvbw能否视作各自带宽的上限在握手的时候协商后，作为单个session的发送上限，避免发送过快浪费带宽？
另外
貌似server和client设置不同的mtu并不影响session的建立，未知是否影响通信

**Comment by xtaci** [comment]
答疑如下:
1. KCP层重在 ”预测丢包“   , FEC重在 “可还原性“,  是对有噪信道两种不同的方法论的结果。
2. 这里你误解了“纠删码“ 和 “纠错码” 的区别。RS既可以是纠删码，也可以是纠错码，LDPC是纠错码，如果LDPC更好，为何RAID还使用RS码？
3. 可以，但更好的方法是QUIC使用的stream based ARQ， 即整体窗口+个体重传
4. sndwnd/rcvwnd等价于带宽上限，参考带宽计算公式

mtu是IP层的概念，不影响。

**Comment by gzmud** [comment]
受教了。
但是
哪server和client的--mtu参数作用主要是什么？

**Comment by gzmud** [comment]
对于第2点，有点疑问，我认为如果kcp的fec层每帧都有顺序号、确认号，对丢失的帧，或超过了可以容忍延时的帧可以填0，作为误码来译码了

**Comment by xtaci** [comment]
fec当然有序号啊，而且是严格的。 建议你仔细看fec实现。
