### ISSUE TITLE
freebsd kcptun使用异常

### ISSUE THREAD

**Issue by ccc1924** [xtaci/kcptun#254]
2016/11/04 15:23:49 TCP SetWriteBuffer: set tcp 127.0.0.1:40771: setsockopt: no buffer space available
2016/11/04 15:23:49 stream opened
2016/11/04 15:23:49 stream closed
2016/11/04 15:23:49 stream closed
2016/11/04 15:23:49 stream closed
2016/11/04 15:23:49 TCP SetReadBuffer: set tcp 127.0.0.1:40772: setsockopt: no buffer space available
2016/11/04 15:23:49 TCP SetWriteBuffer: set tcp 127.0.0.1:40772: setsockopt: no buffer space available
2016/11/04 15:23:49 stream opened
2016/11/04 15:23:49 stream closed
2016/11/04 15:23:49 TCP SetReadBuffer: set tcp 127.0.0.1:40773: setsockopt: no buffer space available
2016/11/04 15:23:49 TCP SetWriteBuffer: set tcp 127.0.0.1:40773: setsockopt: no buffer space available
2016/11/04 15:23:49 stream opened
2016/11/04 15:23:49 stream closed
2016/11/04 15:23:49 TCP SetReadBuffer: set tcp 127.0.0.1:40774: setsockopt: no buffer space available
2016/11/04 15:23:49 TCP SetWriteBuffer: set tcp 127.0.0.1:40774: setsockopt: no buffer space available

参数
/root/kcptun/server_freebsd_amd64 -l :xxxx -t 127.0.0.1:xxxx  -key xxxxx -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2

这个参数在linux下不会出问题

**Comment by ifreefly** [comment]
密码暴露了。。。。

**Comment by xtaci** [comment]
fb的默认sockbuf的限制 可以调大系统参数

**Comment by ccc1924** [comment]
调到多大合适？

**Comment by xtaci** [comment]
just google "freebsd socket buffer tuning"

**Comment by xtaci** [comment]
kcptun默认值是4MB

**Comment by ccc1924** [comment]
我把kern.ipc.maxsockbuf: 调到了4194304，还是没有解决问题

**Comment by xtaci** [comment]
https://fasterdata.es.net/host-tuning/freebsd/

**Comment by ccc1924** [comment]
成功解决，谢谢

**Comment by alfantor** [comment]
我也是这个问题：
`# ./server_freebsd_amd64 -t "45.63.60.159:62181" -l ":4000" -mode fast2
2016/11/17 02:04:04 version: 20161111
2016/11/17 02:04:04 listening on: [::]:4000
2016/11/17 02:04:04 target: 45.63.60.159:62181
2016/11/17 02:04:04 encryption: aes
2016/11/17 02:04:04 nodelay parameters: 1 20 2 1
2016/11/17 02:04:04 sndwnd: 1024 rcvwnd: 1024
2016/11/17 02:04:04 compression: true
2016/11/17 02:04:04 mtu: 1350
2016/11/17 02:04:04 datashard: 10 parityshard: 3
2016/11/17 02:04:04 acknodelay: false
2016/11/17 02:04:04 dscp: 0
2016/11/17 02:04:04 sockbuf: 4194304
2016/11/17 02:04:04 keepalive: 10
2016/11/17 02:04:04 SetDSCP: setsockopt: invalid argument
2016/11/17 02:04:04 SetReadBuffer: set udp [::]:4000: setsockopt: no buffer space available
2016/11/17 02:04:04 SetWriteBuffer: set udp [::]:4000: setsockopt: no buffer space available
`
按照[https://fasterdata.es.net/host-tuning/freebsd/](url)改了，还是一样。

**Comment by ligf** [comment]
@ccc1924 你是怎么改的 我用的freenas没成功呢
