### ISSUE TITLE
一个疑问，为什么单边调整窗口、MTU可以改善

### ISSUE THREAD

**Issue by peakvision** [xtaci/kcptun#256]
不少帖子都反应只调整客户端的sndwnd, recvwnd, mtu即可以改善速度（丢包率？），请问这是什么原因呢？

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/blob/master/kcp.go#L691

取小者

**Comment by xtaci** [comment]
mtu完全是瞎猫碰死耗子，可能也许大概是ISP对小包更包容吧

**Comment by peakvision** [comment]
谢谢，找到代码了。
MTU好像没有取小值计算？一般来说瓶颈不在服务器端，降低服务器端到客户端的udp包大小对丢包有帮助。iperf测试，如果服务器发过来的是大包，还得狂丢。

**Comment by wang20150419** [comment]
功能建议：两端的参数不同时，以客户端为准。这样的话，调参数就不需要两头跑了。当然，mtu 例外。
