### ISSUE TITLE
想问一个问题，为什么加速ssh会unexpectedly closed, 加上ss访问服务器ip就可以

### ISSUE THREAD

**Issue by keytouch** [xtaci/kcptun#257]
根据我所理解的逻辑不应该会有这样的问题啊
os：win7_x64
version:1105
我检查过hosts.deny
ssh的配置里把usedns关了（不知道有没有影响），不过还是不行，只有走ss可以。
想知道为什么

**Comment by keytouch** [comment]
unexpectedly closed是指sftp连接时（用的127.0.0.1:port）的错误，
sftp设置着ss的socks5代理，用服务器ip，成功访问。

**Comment by xtaci** [comment]
autoexpire会主动关闭连接。

**Comment by keytouch** [comment]
不是连接了以后断开的，是一开始直接报这个错

**Comment by coldemoon** [comment]
@keytouch 可以用，请（同时）检查（客户端和服务端）配置。putty 和 WinSCP 都已测试通过，不过由于 autoexpire 原因，一段时间会断开连接。@xtaci autoexpire是必须的吗？能不能设置永不超期？
另外，我从 20160922 版开始使用（配合SS），一直都有一个问题：不定时会出现“broken pipe”断流问题，等待几分钟到十几分钟自动恢复。用 4 台不同服务商、不同地理位置、不同架构的 VPS ，本地分别使用 client_windows_amd64、client_linux_arm5（路由器） 测试过多次，没有改善。唯一相同的是服务端都是用的 CentOS 6 64bit，和这个应该没有关系吧？？
而且诡异的是 4 台服务器会同时出现这个问题，所以是我本地 ISP（西南地区某市电信） 的问题吗？？
本人小白一枚，有什么常识性的错误还请各位轻喷。有一样问题的欢迎来讨论。为了不浪费 issues 版面，就不新开 issue 了。

**Comment by xtaci** [comment]
1.  默认autoexpire就是关闭的。
2. 如果是同时出问题，高度怀疑是路由器 或 服务器的问题。
