### ISSUE TITLE
kcp有时不能用

### ISSUE THREAD

**Issue by Magikarp96** [xtaci/kcptun#258]
图形操作界面用的是dfdragon的，重启10次只有1次是可以正常使用的，其余均无下行速度。

**Comment by kmahyyg** [comment]
请给出参数及操作环境

2016年11月7日 00:54，"Qimars" <notifications@github.com>写道：

**Comment by Magikarp96** [comment]
win10 参数没改变 有时能连上有时连不上

**Comment by alex43211** [comment]
log里报什么错了？
