### ISSUE TITLE
在快速 TCP RX 情况下的 QoS

### ISSUE THREAD

**Issue by yaleh** [xtaci/kcptun#26]
在较大的 TCP 侧带宽情况下，即使使用 tc sfq 控制这一侧输入，KCP TX 队列仍会被少数大流量连接占慢，导致大量短连接响应缓慢。最典型的是从千兆以太局域网中向 pppoe 拨号的 WAN 上传大文件，会导致 web  page 访问缓慢 主要原因是 kcp TX 使用的是 fifo 策略，在 TCP rx 快于 kcp TX 时不利于小流量连接。而由于 kcptun 进程的发出的 udp sport 一致，也无法在 kcp 侧 TX 上使用 tc sfq 来处理这一问题。

有两种处理方法：

* kcptun client 连接 server 时使用多个 udp sport, 甚至为每个 TCP 连接分配不同的 udp sport。此时即可使用 tc sfq 进行 QoS 。
* 在 kcp tx 上应用 TCP 连接信息，实现类似 tc sfq 的机制。此时无需外部的 tc sfq 即可改善短连接体验。

**Comment by yaleh** [comment]
这一问题在 kcptun server 也是可能出现的，只要满足 TCP rx 快于 kcp tx 即可能出现。

在 kcptun 内部的实现修改前的替代方案是使用多个 kcptun 进程，并使用 iptables 等负载均衡将 TCP 连接分配至多个 kcptun 进程。此时各 kcptun 进程会有不同的 udp sport ，可用 tc sfq 进行 QoS 。

**Comment by xtaci** [comment]
@yaleh 非常好的分析，这个问题我是这么解决的，对于局域网来说，要做到绝对的流量均匀，必须要在IP层完成TC，即不能在四层做。   简单的解决方法是，OVPN over KCPTUN，在tun0上做tc，这样虽然ovpn会多一些头部，有效载荷变低，但这是**很可靠的解决办法**，对于**企业应用**是非常合适的，虽然这样对于视频这样的大流量传输并不友好。 

另外提醒一点，根据LARTC的描述，sfq是不能单独用的，需要配合htb设定来用。这部分我没有深究，因为我的场景已经完全够用。   **企业应用**的最大问题，就是网盘类应用占用大量的上行带宽，（主要是Amazon S3的上行），这点你可以根据S3的IP范围做iptable过滤，Amazon公布了IP范围的JSON。简单处理下即可。

**Comment by yaleh** [comment]
查了下 iptables, hashlimit 应该可以在这一场景下配合 tc 实现降低大流量连接的 prio 。待会儿试一下。
