### ISSUE TITLE
关于平均包大小

### ISSUE THREAD

**Issue by caicy1991** [xtaci/kcptun#260]
看了好多Issues，平均包大小是BytesSent / OutSegs，Win下并没有SNMP可以查看这个信息，但看到其他Issues后，发现这个平均包大小有16k，有64k，还有1000k的，有没有一个大众值？

**Comment by xtaci** [comment]
嗯，讲错了，是OutBytes／OutSegs  ，这个值在大概就是1K多

**Comment by caicy1991** [comment]
好的，多谢

**Comment by wattic** [comment]
> 嗯，讲错了，是OutBytes／OutSegs ，这个值在大概就是1K多

我测了下我的vps，是1.7k，但是我的主机上就只有60. 这是哪里不对么？
