### ISSUE TITLE
请问能否提供page size为64K的release？

### ISSUE THREAD

**Issue by liufanl** [xtaci/kcptun#261]
因为家里的NAS系统是page size为64K的debian，自己对交叉编译不太熟悉，不知道作者能否提供相应的release？

**Comment by shutup** [comment]
这个会有影响嘛？

**Comment by liufanl** [comment]
@shutup 有影响，内核和程序page size不一样的话，是不能运行的。

**Comment by bettermanbao** [comment]
cat /proc/cpuinfo

输出发上来看一下

**Comment by liufanl** [comment]
@bettermanbao 
WDMyCloud:~# cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 1 (v7l)
processor       : 0
BogoMIPS        : 1299.25

processor       : 1
BogoMIPS        : 1299.25

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 1

Hardware        : Comcerto 2000 EVM
Revision        : 0001
Serial          : 0000000000000000

**Comment by shutup** [comment]
@liufanl arm版的release不行嘛？kcptun-linux-arm-20161118.tar.gz

**Comment by liufanl** [comment]
@shutup 不行。page size和kernel不一致

**Comment by shutup** [comment]
@liufanl 查了一下资料，确实是会有影响的。使用64K的设定，主要用于一些数据交换多的场景，而我们一般的设备都是4k的。鉴于你的设备是NAS,那么使用64k就正常了。 此时有两种方案解决，一种需要换你NAS的系统，另一种就是要合适的工具链来进行编译了（这里需要进一步的了解，我继续了解一下）。

**Comment by liufanl** [comment]
@shutup 非常感谢！！

**Comment by rawrence** [comment]
@liufanl 试试这个
[client_linux_arm7.zip](https://github.com/xtaci/kcptun/files/611641/client_linux_arm7.zip)

**Comment by liufanl** [comment]
@rawrence 好像不行
WDMyCloud:/usr/local/kcptun# ./client_linux_arm7
unexpected fault address 0x1954d8
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1954d8 pc=0x1954d8]

goroutine 1 [running, locked to thread]:
runtime.throw(0x1e10b8, 0x5)
        /opt/src/go/src/runtime/panic.go:596 +0x70 fp=0x10639f94 sp=0x10639f88
runtime.sigpanic()
        /opt/src/go/src/runtime/signal_unix.go:276 +0x20c fp=0x10639fb8 sp=0x10639f94
main.init()
        /opt/gopath/src/github.com/xtaci/kcptun/client/signal.go:29 fp=0x10639fbc sp=0x10639fbc
runtime.main()
        /opt/src/go/src/runtime/proc.go:173 +0x198 fp=0x10639fe4 sp=0x10639fbc
runtime.goexit()
        /opt/src/go/src/runtime/asm_arm.s:1017 +0x4 fp=0x10639fe4 sp=0x10639fe4
WDMyCloud:/usr/local/kcptun#
