### ISSUE TITLE
IDM（internet download manager)用kcp代理下载速度异常

### ISSUE THREAD

**Issue by yueyingjuesha** [xtaci/kcptun#262]
在服务器（Ubuntu14.04)上安装的是最新的kcp，客户端也是最新的，并且在服务器端设置了socks5代理程序（https://sourceforge.net/projects/mocks/ ）
用idm下载同一个服务器中的文件到本地，idm代理设置成本地kcptun端口后下载，刚开始有速度，但始终只能创建1个连接，后来下载速度越来越慢，最后卡住不动。但是用浏览器将代理端口设置成socks端口后fq速度正常，想问下这是因为kcptun不支持多线程下载吗？
服务器端配置：
    "listen": ":29900",
    "target": "127.0.0.1:10080", //(服务器端的10080是mocks socks5代理的端口)
    "key": "test",
    "crypt": "salsa20",
    "mode": "fast2",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10,
    "conn": 8
}

本地配置：
--localaddr ":12948" --remoteaddr "xxx.xxx.xxx.xxx:29900" --conn 8 --crypt salsa20 --key "test" --mode fast2 --datashard 70 --parityshard 30 --sndwnd 128 --rcvwnd 1024 --mtu 1350 --dscp 46 --autoexpire 0 --sockbuf 4194304 --acknodelay false --keepalive 10

还有一个疑问是如果用kcptun加速shadowsocks时，ss目标地址都填的是本地地址，那岂不是在跨越gfw的时候只有kcp协议，ss只是充当两边端口的转换成socks5代理的作用？

**Comment by xtaci** [comment]
上层应用的差异性太多，看具体手册吧。

kcptun只做一件事情， TCP的流的转发。
