### ISSUE TITLE
连接频繁中断 

### ISSUE THREAD

**Issue by chenTest2013** [xtaci/kcptun#263]
福建移动 20M 带宽
默认fast配置 除了端口和关闭压缩,其他默认配置.
最近总是出现连接中断的情况
具体表现为:
1.在线看视频,没隔10-30分钟中断一次,客户端有大量的stream opened,有几个session scavenged,然后服务端日志最后一行是broken pipe,下面在没有任何信息了,貌似收不到客户端的请求了.
2.然后等10-30分钟,又连接上.
3.期间不管怎么调参数,(极少的概率)偶尔可连上
4.如此反复1-3.
5.直接连ss端口可连上.
请问:大家的是什么样的?这种情况大概原因是什么?

**Comment by ljyloo** [comment]
我也一样的情况，用了作者的参数也这样，无头绪

**Comment by ljyloo** [comment]
#228 这里的三楼好像说出了真相

**Comment by chenTest2013** [comment]
@ljyloo  也许是的.

**Comment by katosun2** [comment]
特别是长城宽带，只要是出境的大UDP包，直接封30分钟到几个小时不等。只有TCP为能正常连接。

**Comment by PterX** [comment]
https://github.com/xtaci/kcptun/issues/228
@ljyloo @chenTest2013 降低MTU，有比较好的效果。目前除了14:00多会固定断一次，其他时候都不会断了。电信网络。

**Comment by sixleaves** [comment]
如果是降低MTU是降低链路层的最大帧大小，那对应的最大数据报大小应该也要调整吧，没看过代码，但觉得应该是这样。

**Comment by chenTest2013** [comment]
这几天又测试了,贴上我的参数  
   "crypt": "salsa20",
    "mode": "fast",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 512,
    "sndwnd": 512,
    "rcvwnd": 512,
    "datashard": 5,
    "parityshard": 5,
    "dscp": 0,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
现在情况好多了
