### ISSUE TITLE
是否加入参数自调谐功能，本人外行

### ISSUE THREAD

**Issue by channingbox** [xtaci/kcptun#265]
在客户端的选项  

1. 有效载荷比优先/响应速度优先/系统默认-折中        (只保留三项，太多反而不知道选择哪个)
2. 参数锁定                                                          (在第一项已选择的情况下进行微调)
       客户端**解锁**时自动调优客户端与服务端参数并同步，客户端**锁定**时调节结束并设置最优参数为默认
3.  服务器地址 xxx.xxx.xxx.xxx 端口 xxxxx
4.  加密方式 aes-256-cfb/salsa20/chacha20-ietf   （保留最常用的几个）

多次调节参数只需在客户端调节，服务器端不动。隐藏大量参数的好处是降低使用难度，方便软件升级。

**Comment by xtaci** [comment]
普通用户网上有很多方案，这个是针对专家用户的。
