### ISSUE TITLE
内存问题集中贴

### ISSUE THREAD

**Issue by xtaci** [xtaci/kcptun#267]
建议测试下 1110版本，怀疑kcp的窗口计算有误，导致了不明的内存增长。
现在我试了下，内存在22M RES左右。

@bettermanbao

**Comment by bettermanbao** [comment]
呵呵，更新的好快啊。
1105版目前已经在64M内存的路由上稳定运行，等我试试新版告诉你结果。

**Comment by xtaci** [comment]
@skywind3000

**Comment by bettermanbao** [comment]
@xtaci 内存使用确实有所改善，原来一看视频可用内存很快就降到1-2M，现在看了5分钟，还有5M左右。感谢升级。

**Comment by skywind3000** [comment]
不是 buffer积累？为何说窗口计算有误呢？

**Comment by xtaci** [comment]
``` 
func (kcp *KCP) wnd_unused() int32 {
 -	if len(kcp.rcv_queue) < int(kcp.rcv_wnd) {
 -		return int32(int(kcp.rcv_wnd) - len(kcp.rcv_queue))
 +	if wnd := int(kcp.rcv_wnd) - len(kcp.rcv_queue) - len(kcp.rcv_buf); wnd >= 0 {
 +		return int32(wnd)
  	}
  	return 0
  }
```

wnd_unused并没有计算到rcv_buf中的量，假如我收到1, 3,4,5... 100 ，wnd=100，只有2号包丢失，那么rcv_queue大小是1，通知对方的我的窗口大小是100 - 1 =99, 实际上窗口只差一个就填满， 我的理解是这样。 @skywind3000

**Comment by skywind3000** [comment]
不是这样理解的，首先“远程窗口大小”决定的并不是 “当前可以发送多少数据”，而是 ”当前**从snd_una开始，还能**新发多少数据“：

```cpp
	// calculate window size
	cwnd = _imin_(kcp->snd_wnd, kcp->rmt_wnd);
	if (kcp->nocwnd == 0) cwnd = _imin_(kcp->cwnd, cwnd);

	// move data from snd_queue to snd_buf
	while (_itimediff(kcp->snd_nxt, kcp->snd_una + cwnd) < 0) {
		IKCPSEG *newseg;
		if (iqueue_is_empty(&kcp->snd_queue)) break;

		newseg = iqueue_entry(kcp->snd_queue.next, IKCPSEG, node);

		iqueue_del(&newseg->node);
		iqueue_add_tail(&newseg->node, &kcp->snd_buf);
		kcp->nsnd_que--;
		kcp->nsnd_buf++;

		newseg->conv = kcp->conv;
		newseg->cmd = IKCP_CMD_PUSH;
		newseg->wnd = seg.wnd;
		newseg->ts = current;
		newseg->sn = kcp->snd_nxt++;
		newseg->una = kcp->rcv_nxt;
		newseg->resendts = current;
		newseg->rto = kcp->rx_rto;
		newseg->fastack = 0;
		newseg->xmit = 0;
	}
```

当前还能发多少新数据，显然，在你情况下1,3,4,5...100受到了，接收者本地 rcv_wnd=100的情况下，rcv_queue大小是1，剩余 99个，指的是：**你从2开始，还可以发送99个包过来**
然后通知回去，发送者收到 ack1，却没有收到ack2，尽管受到 ack3, ack4，而发送者的snd_una却一直=2，发送者只能发送 2开始到101的序号的包。

这个行为和tcp一模一样，不可能那个2没收到，就窗口一路跑下去，那要窗口干嘛啊。

**Comment by skywind3000** [comment]
内存增长最直接的原因就是“发不过去一直缓存”，这时应该加一个判断，如果网络没能力发送需要发送的数据，kcptun应该禁止对本地tcp端口的 “读操作” ，这样tcp的buffer满了以后，另外一端tcp的也就不会持续发送了。内存就止住了。

**Comment by xtaci** [comment]
我消化一下。

**Comment by xtaci** [comment]
嗯，理解了，想错了一个地方。 
@skywind3000 看下这个呢：
https://github.com/xtaci/kcp-go/commit/6168f7381e3205fb5e17ee4752ff50848c14f7b8

**Comment by skywind3000** [comment]
滑动窗口本来就是当头一个字节收不到就不能移动，不能随意扩大的。这个没收到的字节把“滑动窗口”给“挡住”了，如果收到这个字节，窗口才能继续往后“滑动”

**Comment by xtaci** [comment]
嗯，就是una + cwnd就卡住了发送的窗口范围。理解了

**Comment by xtaci** [comment]
@skywind3000 小于una的ack是不需要发送的，这个你觉得有没有问题？

**Comment by bettermanbao** [comment]
你们讨论的太高端了，我实际用下来，最近这次更新感觉对速度和内存影响都不大。

**Comment by xtaci** [comment]
@bettermanbao 越辩越明，听@skywind3000大师讲解

**Comment by skywind3000** [comment]
@xtaci 不能这么改，不能要这个判断，`ack.sn > kcp.rcv_nxt` 不管是 >还是 >= 都不能要。
接收方受到一个包是否回应 ack的规则是：
1. 如果受到包的 sn > 接收方的 rcv_nxt + rcv_wnd 则不回应ack，因为超过本地接收窗口大小，没能力处理。
2. 其他条件都要回应 ack（包括你自己加上去的 `ack.sn > kcp.rcv_nxt` 判断），

因为 rcv_nxt 向前+1的规则是完整连续的收到了前面的包，这时新来一个包的 sn < rcv_nxt的话，
只能说明本地明明已经完整处理了该包了，远程却持续发送过来，只能说，远端“不知道我已经收到这个包了”，最常见的情况就是上一次收到这个包时，发送回去的 ack丢失，远端发送者不知道这个包成功了。

所以即便 sn < rcv_nxt，你也应该让 ack发送回去啊。

**Comment by skywind3000** [comment]
当然，una可以一定程度上补救这个事情，但是如果分开看两套系统，<rcv_nxt的ack就该发过去，否则这套ack系统是有问题的，不能独立工作的，必须依靠una才行，una, ack两套独立系统，设计初中是独立工作，但是互相加强。而不是谁要依靠谁。

**Comment by xtaci** [comment]
嗯，我先删除掉这个release， 再消化下

**Comment by bettermanbao** [comment]
@skywind3000 什么时候能写一个c/c++的kcptun就好了，期待啊。

**Comment by skywind3000** [comment]
我有，但是没法开源，牵扯公司代码。

**Comment by skywind3000** [comment]
2012年就开发出来了，

**Comment by skywind3000** [comment]
kcp是我自己兴趣开发出来放着网上好几年，然后后面我自己项目用了，C++版本的叫 QuickNet，虽然我是主要开发，但是也有我指挥很多其他同事开发的部分，况且是算在上一个项目的开发时间上的，开源不妥当。

**Comment by xtaci** [comment]
@skywind3000 我考虑的是，在同一个包内，如果 N个ack 都小于 una值都去掉，我觉得应该是等价的才对，并且能降低包大小

**Comment by xtaci** [comment]
如果不考虑你的初衷，就是必须ack/una 都存在，这个优化是否正确，能降低ack数据包的流量？@skywind3000

**Comment by skywind3000** [comment]
能降低数据包流量，但是能降的比例可能微不足道，
内存积累归根结底要控制 tcp端的接收节奏，本来就是数据转发系统的一个重要任务：“接口间流控”，不做这个的话，光靠改 kcp，是无解的。

**Comment by xtaci** [comment]
ok，一个ack也是24个字节，100个ack就两个数据包了， 聊胜于无吧。

接口间流控实际是做了的，可能默认值偏大， smux的recv bucket 能控制速率。

**Comment by xtaci** [comment]
已重新发布1111版本，只加了ack降低特性。
