### ISSUE TITLE
Golang官方已经支持 mips 和 mipsle 了

### ISSUE THREAD

**Issue by kuoruan** [xtaci/kcptun#268]
下次编译的时候希望考虑同时编译 mips 和 mipsle 版本
https://github.com/golang/go/commit/ad366fdbe40eea7f4fbdc75e8a27304c696793f1

**Comment by xtaci** [comment]
嗯，是个好消息。不知道什么时候release

**Comment by bettermanbao** [comment]
太好了~~~
