### ISSUE TITLE
如何编译个MIPS版本给路由器用？

### ISSUE THREAD

**Issue by gandalfwong** [xtaci/kcptun#27]
能否在QEMU通过虚拟环境编译一个客户端版用在路由器上?

**Comment by xtaci** [comment]
臣妾做不到啊

**Comment by gandalfwong** [comment]
呵呵，我意思是请教编译的命令，我自己会动手。:-)

**Comment by xtaci** [comment]
mips32 没有golang的官方支持，只能用gccgo做编译，而这是一个痛苦的过程。
我的binary编译脚本：
https://github.com/xtaci/kcptun/blob/master/build-release.sh
依赖的库很少，根据编译错误提示，挨个go get下来就行了

**Comment by gandalfwong** [comment]
感谢！ 我有空时自己挖个坑试试。 :-)

**Comment by gandalfwong** [comment]
我在mips64上运行都有点慢， 放弃mips32了。  
  
Sent from [Nylas N1](https://link.nylas.com/link/a9bfrjr67py6abrlsz8eafezs
/local-
3d6a1de3-cfda/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1&r=cmVwbHkrMDAwOTc4N2I0MWE1ZGNmNzQ1Yzg5NzRiMGZmYjJiOGQwZWI1NmI5ZjA0YmZlMDA0OTJjZjAwMDAwMDAxMTM3ZmJhYmM5MmExNjljZTA5NzM0NDc3QHJlcGx5LmdpdGh1Yi5jb20=),
the extensible, open source mail client.  
![](https://link.nylas.com/open/a9bfrjr67py6abrlsz8eafezs/local-
3d6a1de3-cfda?r=cmVwbHkrMDAwOTc4N2I0MWE1ZGNmNzQ1Yzg5NzRiMGZmYjJiOGQwZWI1NmI5ZjA0YmZlMDA0OTJjZjAwMDAwMDAxMTM3ZmJhYmM5MmExNjljZTA5NzM0NDc3QHJlcGx5LmdpdGh1Yi5jb20=)

On 6月 20 2016, at 10:07 晚上, bettermanbao &lt;notifications@github.com&gt;
wrote:  

> mips32的我编译成功了，bin在这里，你可以试试，性能很差。2Mbps封顶。  
>  [https://github.com/bettermanbao/openwrt-
kcptun/releases](https://github.com/bettermanbao/openwrt-
kcptun/releases&r=cmVwbHkrMDAwOTc4N2I0MWE1ZGNmNzQ1Yzg5NzRiMGZmYjJiOGQwZWI1NmI5ZjA0YmZlMDA0OTJjZjAwMDAwMDAxMTM3ZmJhYmM5MmExNjljZTA5NzM0NDc3QHJlcGx5LmdpdGh1Yi5jb20=)

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/xtaci/kcptun/issues/27#issuecomment-227152334&r=cmVwbHkrMDAwOTc4N2I0MWE1ZGNmNzQ1Yzg5NzRiMGZmYjJiOGQwZWI1NmI5ZjA0YmZlMDA0OTJjZjAwMDAwMDAxMTM3ZmJhYmM5MmExNjljZTA5NzM0NDc3QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe/AAl4e8MIC-
MP1fRwDj1PWmqSQloa2cKkks5qNp68gaJpZM4IuVMX&r=cmVwbHkrMDAwOTc4N2I0MWE1ZGNmNzQ1Yzg5NzRiMGZmYjJiOGQwZWI1NmI5ZjA0YmZlMDA0OTJjZjAwMDAwMDAxMTM3ZmJhYmM5MmExNjljZTA5NzM0NDc3QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AAl4ewFtiR5RQrK7B_yi_GvkVY8zRCxhks5qNp68gaJpZM4IuVMX.gif)
