### ISSUE TITLE
似乎是随机断流导致下载速度很快但是加载网页不全求帮助~

### ISSUE THREAD

**Issue by TMily** [xtaci/kcptun#270]
目前参数如下：
服务端
-sndwnd 2048  -rcvwnd 2048    -key XXX     -mode manual 
-nodelay 0    -resend 2       -nc 1        -interval 20 
-dscp 46      -nocomp         -mtu 1400    -crypt aes-128 
-datashard 30 -parityshard 15
客户端
-sndwnd 256   -rcvwnd 2048   -key XXX      -mode manual 
-nodelay 0    -resend 2      -nc 1         -interval 20 
-dscp 46      -nocomp        -mtu 1400     -crypt aes-128  
-datashard 30 -parityshard 15-autoexpire 30
客户端和服务端均为1111版
服务器是V家西雅图，客户端为天津联通200M
现象是测速时在2048窗口和30：15FEC下可以跑到60Mbps有效载荷，如果继续扩大窗口最高可跑到90Mbps左右有效载荷。但是此时实际带宽消耗已达到240Mbps。
测速过程中就会遭遇断流的问题比如用SpeedTest-cli测速的时候会出现服务器列表拉取失败，或者测试结果分享链接加载失败的情况。
在加载网页时大量的资源会加载失败，甚至第一次打开网页会直接提示站点不可达。如果是比较大的站点比如youtube刷新一次基本可以加载完全但是在开发者工具中看实际还是有资源加载失败，如果是其他网站的话则有可能无论怎么刷新都会有关键的资源加载失败导致网站显示出现问题。
尝试过的调整：
更换服务器，V家的三个美西节点都试过了，还试过BWG，由于不希望IP是JP或者SGP的所以并没有尝试亚洲节点。
调整MTU，尝试过缩小MTU至512但问题依旧。
调整FEC，尝试增大FEC比例到5：5甚至5：15~~但问题依旧
调整DSCP，没有效果
调整窗口大小，1024，2048，4096，3072都尝试过，没有改变

**Comment by katosun2** [comment]
1、-autoexpire 30 是不是设置得太低了，试一下不设？
2、断流还可能和ISP有关，udp强制丢包导致，这个就没救了。

**Comment by TMily** [comment]
-autoexpire 30 这个是为了解决之前遇到的 闲置一段时间之后断流的问题添加的 试过去掉没有效果

**Comment by xtaci** [comment]
re-download

**Comment by TMily** [comment]
感谢X大，不过现象依然存在，似乎是有一定改善因为Youtube第一次加载基本能正常显示了，但在开发者工具中看还是有失败。而比较小的网站几乎没有改善，第一次加载几乎肯定加载不全。

**Comment by TMily** [comment]
尝试更换更标准的非46DSCP似乎大幅改善，但是目前的DSCP取值导致延迟上涨近100%。查了下资料感觉可能是DSCP=46时的加速转发机制会导致边缘路由将不满足要求的包大面积丢弃造成随机的一过性连接中断，这个可以通过其他参数进行优化么？
