### ISSUE TITLE
RFC-20161114001: The [Client Know The Target Addr] listen flag

### ISSUE THREAD

**Issue by netroby** [xtaci/kcptun#271]
## Design: 

At this mode. The kcptun server configured with the new flag:  ```-cktta 1```
By running at this mode. the kcptun server do not know client want to request what addr. until the client connection to the kcptun and tell kcptun server it want to request the target address.
Then kcptun server will know it  and keep the target addr in the memory. once the connection closed. kcptun server will remove the record from memory.

The kcptun client should using the new flag:``` -target-addr 192.168.7.13:8080``` to tell the server , once connection ready. it should be forward to the 192.168.7.13:8080 port.

## Problem:

In current kcptun, we can not specify more upstream addr . we should set up more than one kcptun server instance. 
It will use more memory/cpu . For example. we want to forward MySQL, proxy server , smtp server with kcptun 

server side.
```
192.168.7.13:3306 # MySQL
192.168.7.12:8123 # Squid proxy
192.168.7.11:25 # SMTP
```

## Solution:
If we have the new listen flag. we can let client choose where the kcptun server should connect to .
And save memory/cpu usage.

**Comment by xtaci** [comment]
like ssh -L

so you can tunnel traffic of ssh tunnel?

**Comment by netroby** [comment]
SSH so slow. not suite for this usage. we would like to using kcptun to transfer data between our two datacenter. 

Actually, we do it for one service(mysql) for now. very amazing and fast. so we would like to extend to more services

**Comment by xtaci** [comment]
have you ever tried ovpn over kcptun?

**Comment by netroby** [comment]
that's slow and more complex. thanks.

**Comment by netroby** [comment]
we only need to forward some service. so may not want to set a vpn to cross two datacenter

**Comment by xtaci** [comment]
i'll look into that.

**Comment by netroby** [comment]
If you are busy , have no time or no interest to add more feature like this. please let me know. i will close this. 
And i would like to develop an solution base on kcptun . 
Again, appreciate your service and hard work.

**Comment by xtaci** [comment]
of course, you could submit  PR to me. make sure the code is short & clean, and step by step.

**Comment by xtaci** [comment]
modifications and forks are also encouraged.  I could add a link to your project if it's available.

**Comment by netroby** [comment]
Quick and dirty , but it works for me . Welcome code review and comments.

**Comment by netroby** [comment]
Draft a test release  https://github.com/netroby/kcptun/releases/tag/v20161117
