### ISSUE TITLE
how to set server to listen on both ipv6 and ipv4 address?

### ISSUE THREAD

**Issue by iampkuhz** [xtaci/kcptun#272]
hi, I'v set this on my linode vps (ubuntu 14.04 64 bit).
However, I could only use shadowsocks android client by ipv6 configure.
If I turn the shadowsocks server to ipv4 address (same vps), kcptun not work.

I was trying to setup 2 kcptun server process in my vps. the tow kcptuns only differ in the server port and whether enable ipv6 address. However, it won't work... (still only the ipv6 kcptun work)

How can I enable both?

thanks

**Comment by xtaci** [comment]
https://golang.org/pkg/net/#ResolveTCPAddr

this is how golang resolve address

**Comment by iampkuhz** [comment]
Sorry for mistake.
I find it already listened both ipv6 and ipv4 address. I forget to remove default kcp configure in shadowsocks...
