### ISSUE TITLE
在mac上不能用了

### ISSUE THREAD

**Issue by XieSen** [xtaci/kcptun#274]
系统版本是10.12.1，client版本是kcptun-darwin-amd64-20161111

使用同样的参数配置连接同一个server（server版本是20161111），在Windows和Ubuntu上面（client版本也是20161111）都能连上网，但是在mac不可以，是不是mac版的二进制文件有问题啊

**Comment by xtaci** [comment]
已测试，二进制没有发现问题。

**Comment by wang20150419** [comment]
出现 setreadbuffer: set udp x.x.x.x:55235: setsockopt: no buffer space available , setwritebuffer后面也是这一串。需要如何配置？关键是，用户折腾命令行之类的很吃力。

**Comment by xtaci** [comment]
能用就不用去管

**Comment by XieSen** [comment]
@xtaci 你那里是可用的吗，我当前系统版本是10.12.1，系统升级前（10.12）是可用的

server确定是好的，因为windows和ubuntu上面都可以用，就mac上用不了

需要提供什么日志吗

**Comment by xtaci** [comment]
我就是用的mac，如果有问题我应该最先发现

**Comment by KngEast** [comment]
我也是，10.12.1，反复确认本地xx.json配置参数，都没错，而且以前这个参数也是可以用的。用windows使用正常，mac死活连不上

**Comment by xtaci** [comment]
我是10.12

**Comment by xtaci** [comment]
升级到10.12.1， 测试无问题。

**Comment by XieSen** [comment]
我也是纯命令行参数启动的，试过好几个版本的client，都不行
/usr/local/bin/kcptun -l :9000 -r 23.106.152.62:29900 -crypt salsa20 -mode fast2 -nocomp

**Comment by XieSen** [comment]
同样的参数，同样的网络，在windows上面可用

**Comment by xtaci** [comment]
此处无法重现。

**Comment by KngEast** [comment]
我现在只能mac用虚拟机win上kcptun

**Comment by xtaci** [comment]
<img width="460" alt="4c769e70-7d49-4da4-bd76-ae8d63338c43" src="https://cloud.githubusercontent.com/assets/2346725/20378174/623f0ec8-accf-11e6-91b4-edc7924f3710.png">

**Comment by KngEast** [comment]
我解决了
说一下错在哪里
1.我ss加密方式是aes
2.我kcptun加密方式是salsa20
错在我ss客户端里127.0.0.1的服务器配置加密方式选了salsa20，换成aes就ok
（貌似以前的版本选salsa20也可以的，难道我记错了？）

**Comment by YangYunLong** [comment]
求mac版kcptun教程 谢谢各位

**Comment by XieSen** [comment]
今天仔细检查了一下，的确是我ss客户端加密方式选错了，眼瞎了，一直没发现，抱歉了哈@xtaci

**Comment by Great-Li-Xin** [comment]
有着同样的问题，kcptun在Mac 上不可用
![sc1](https://cloud.githubusercontent.com/assets/17794470/23205350/7f3b1354-f924-11e6-9b5e-bc1b7b018050.jpg)

**Comment by Great-Li-Xin** [comment]
有着同样的问题，kcptun在Mac 上不可用
![sc1](https://cloud.githubusercontent.com/assets/17794470/23205478/f69f67f6-f924-11e6-9dc1-2d7f97874dff.jpg)
