### ISSUE TITLE
kcptun 的server端不能监听443低端口吗?

### ISSUE THREAD

**Issue by chenTest2013** [xtaci/kcptun#275]
kcptun server的配置文件如下 
 "listen": ":443",
   "target": "127.0.0.1:26687",
错误信息:
listen udp :443: bind: permission denied
net.ListenUDP
github.com/xtaci/kcp-go.ListenWithOptions
	/Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:851
main.main.func1
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:311
runtime.call16
	/usr/local/go/src/runtime/asm_386.s:498
reflect.Value.call
	/usr/local/go/src/reflect/value.go:434
reflect.Value.Call
	/usr/local/go/src/reflect/value.go:302
github.com/urfave/cli.HandleAction
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:487
github.com/urfave/cli.(*App).Run
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:245
main.main
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:355
runtime.main
	/usr/local/go/src/runtime/proc.go:183
runtime.goexit
	/usr/local/go/src/runtime/asm_386.s:1612
将端口该443,440这些低端口都报这样的错,server端是以root运行,并且确定443,440没有其他程序占用,还是报权限拒绝.
这是怎么回事?

**Comment by netroby** [comment]
低于1024的端口，需要root权限．你这个报错是权限不足的提示，用root用户试一下．　windows的话，用管理员权限启动试试

**Comment by chenTest2013** [comment]
问题找到了,是supervisor的配置问题,感谢提示@netroby

**Comment by sunnyhuangpei** [comment]
@chenTest2013 你好，遇到了和你一样的问题，请问怎么解决的呢，多谢。
