### ISSUE TITLE
貌似dscp参数会影响断流（客户端 session scavenged 服务端 broken pipe）

### ISSUE THREAD

**Issue by choicky** [xtaci/kcptun#277]
我是深圳电信网络。

使用  -dscp 46 ，网速比 -dscp 0 快一点。
但是，前者会断流，客户端间歇性出现 session scavenged ，服务端间歇性出现 broken pipe

把 -dscp 改为 0 后，稳定很多。

**Comment by xtaci** [comment]
https://en.wikipedia.org/wiki/Differentiated_services#Commonly_used_DSCP_values
还有很多选择

**Comment by choicky** [comment]
作为一个律师.... 能看懂那个页面的每个单词，但不理解其意义啊.. .

只看到 dscp 取值 46 和 0 时在 Drop probability 这里都是 N/A T_T

**Comment by xtaci** [comment]
都是蒙

**Comment by xtaci** [comment]
这些值是路由器解释的，怎么解释，要不要解释，完全取决于当事路由器。

**Comment by bettermanbao** [comment]
律师竟然会来github。。。。

**Comment by choicky** [comment]
我还用 thinkphp 编过一个案件管理系统啊，丢在 github 呢 😃

**Comment by Alexander-Chen** [comment]
![screenshot_20161122-084237](https://cloud.githubusercontent.com/assets/18066264/20506999/f9a80438-b092-11e6-9602-0338bd0e3f15.png)
![screenshot_20161122-084242](https://cloud.githubusercontent.com/assets/18066264/20507002/fd588c1a-b092-11e6-8cab-668ce77e854e.png)
  大家帮我看看  我手机客户端哪里参数填写的不对吗，为什么连不上 谢谢

**Comment by choicky** [comment]
首先，你得保证ss能正常使用。
![qq 20161122093124](https://cloud.githubusercontent.com/assets/10532949/20507676/22a6cabe-b097-11e6-91d8-b6ca15d3dac3.png)


然后，如要启用kcptun加速，需要服务器段开启kcptun，并在客户端开启kcptun。
shadowsocks默认采用kcptun加速ss，即，kcptun服务端必须是加速ss服务端的。
因此，只需要填写kcptun服务端的端口号，以及 -crypt -mode -key 这几个。
![qq 20161122093135](https://cloud.githubusercontent.com/assets/10532949/20507680/26517236-b097-11e6-8390-767594549168.png)

**Comment by msly** [comment]
@Alexander-Chen 你的是中间少空格吧,参数都连到一起了

**Comment by Alexander-Chen** [comment]
我中间加了空格也不行啊。。是不是格式有错误
  能不能把你们的手机客户端参数格式截个图给我看一看
     谢谢！

发件人: msly [mailto:notifications@github.com]
发送时间: 2016年11月22日 13:53
收件人: xtaci/kcptun <kcptun@noreply.github.com>
抄送: Alexander Chan <cx-0118@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [xtaci/kcptun] 貌似dscp参数会影响断流（客户端 session scavenged 服务端 broken pipe） (#277)


@Alexander-Chen<https://github.com/Alexander-Chen> 你的是中间少空格吧,参数都连到一起了

**Comment by choicky** [comment]
@Alexander-Chen 我已经跟你说得很明确你错在哪里了啊

**Comment by Alexander-Chen** [comment]
然而我改了之后还是连不上啊。。
能不能看看你的手机客户端的参数格式
谢谢

发件人: Choicky ZHOU [mailto:notifications@github.com]
发送时间: 2016年11月23日 10:46
收件人: xtaci/kcptun <kcptun@noreply.github.com>
抄送: Alexander Chan <cx-0118@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [xtaci/kcptun] 貌似dscp参数会影响断流（客户端 session scavenged 服务端 broken pipe） (#277)


@Alexander-Chen<https://github.com/Alexander-Chen> 我已经跟你说得很明确你错在哪里了啊

**Comment by choicky** [comment]
@Alexander-Chen 我早就发图了啊，你还在问图

**Comment by fortitudezhang** [comment]
搞dscp感觉都有点玄学了：）反正靠蒙，有可能机房出口路由器都重设了qos...
