### ISSUE TITLE
关闭FEC后，内存使用大幅降低。

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#278]
刚才抽空试了一些参数组合，偶尔发现FEC才是内存大量占用的元凶。

先说明一下我这边的的情况：

1. 魔都电信100M宽带，每天上午直连国外网站速度还行，下午开始到晚上访问国外网站速度很慢。
2. kcptun部署在MT7620 + 64M内存的路由器上配合SS透明代理使用，使用的是20161105版kcptun。
3. VPS是sentris的，流量一大就会被封。测试下来rcvwnd和sndwnd设置128长时间运行不会被封。

参数如下，速度可以稳定在2.5Mbps以上，youtube 720p非常流畅，1080p基本流畅。
因为我这边电信不同时段的丢包率差别很大，所以尝试把FEC关了，用fast2模式。FEC固定的带宽开销在丢包率低的情况下比较浪费带宽。不容让丢失的包直接用fast2的快速重传找回，这样动态带宽利用率更高。因为本身window只是128，所以带宽很宝贵。

于是关闭FEC后，发现原先64M内存的路由器看一段时间视频后，可用内存必定会降到1-2M之间，现在可用内存永远维持在14M以上。CPU使用率也略微降低，但传输速度仍维持原水平。

    "crypt": "salsa20",
    "mode": "fast2",
    "autoexpire": 300,
    "sndwnd": 128,
    "rcvwnd": 128,
    "datashard": 0,
    "parityshard": 0,
    "dscp": 46,
    "nocomp": true,

所以为题来了，开FEC后的大量内存占用是正常情况吗？

BTW, 下面这组加密耗时的评估源码能否提供下？我想看看在MIPS平台下运行的结果，谢谢！

BenchmarkAES128-4         200000         11182 ns/op
BenchmarkAES192-4         200000         12699 ns/op
BenchmarkAES256-4         100000         13757 ns/op
BenchmarkTEA-4             50000         26441 ns/op
BenchmarkSimpleXOR-4     3000000           441 ns/op
BenchmarkBlowfish-4        30000         48036 ns/op
BenchmarkNone-4         20000000           106 ns/op
BenchmarkCast5-4           20000         60222 ns/op
BenchmarkTripleDES-4        2000        878759 ns/op
BenchmarkTwofish-4         20000         68501 ns/op
BenchmarkXTEA-4            20000         77417 ns/op
BenchmarkSalsa20-4        300000          4998 ns/op

**Comment by xtaci** [comment]
1. 开启FEC，内存必然的会高， 问题可能出在fec的数据包过期策略。 可能可以优化。
2. FEC可以降低最大延迟，这是必然的。

**Comment by xtaci** [comment]
加密速度是来自于 crypt_test.go 在kcp-go里面的Benchmark， 运行
go test -run=^$ -bench .

**Comment by bettermanbao** [comment]
理解FEC打开后必定会使用更多的内存。
顺便请教一下，fast2模式下，客户端发现丢包后，是立刻请求重传的对吗？

**Comment by xtaci** [comment]
都不是“请求”的，都是“猜”的，rtt，跳过数，作为猜的基础。

**Comment by xtaci** [comment]
如果FEC只保留一个两个 FEC group大小的滑动窗口，可能能降低很大的内存使用。

**Comment by xtaci** [comment]
@bettermanbao 我提交了kcp-go的一个FEC改动，你可以试试效果。长期运行。

**Comment by bettermanbao** [comment]
我试试看，另外FEC的参数你觉得我的网络情况设成多少为好？

还有，server和client都要更新吗？还是仅仅更新client测试就可以了？

**Comment by xtaci** [comment]
只需要client测试就可以了。
FEC默认值我觉得在大多数情况下就挺好，10:3用来兜底RTO的延迟。

**Comment by bettermanbao** [comment]
测试结果来了，看了10分钟视频，FEC 用的 10 3，剩余内存稳定在10M左右。比原来有明显改善！！！

**Comment by xtaci** [comment]
嗯，挺好，那我做个release

**Comment by notedit** [comment]
不知道 有没有看过webrtc的 fec 实现

**Comment by xtaci** [comment]
@bettermanbao ARM的加密测试结果之后发出来我看看。

**Comment by xtaci** [comment]
@notedit 没有看过webrtc的fec，如何实现的？

**Comment by bettermanbao** [comment]
MIPS需要先交叉编译.go的源码，其实我没看懂你刚才的命令是需要编译kcp-go里的哪几个.go文件才能运行？ 麻烦再解释一下吧。

**Comment by xtaci** [comment]
x86上是直接 在kcp-go目录下运行 go test -run=^$ -bench . 就出结果了。

arm得看看go test怎么把测试编译成一个exe文件，还没试过。

**Comment by bettermanbao** [comment]
go build -ldflags "-s -w" -o kcp-go_linux_mips32le ./

编译出来的文件无法运行，能否给一个单独的.go文件，运行后就能输出结果的。

**Comment by LiR1cky** [comment]
看了下代码的变更，对FEC queue的限制改变挺大的。
8192->3*(dataShard+parityShard)
以我目前用的fec(30,15)为例，从8192降到了135

今晚回家测试一下在此限制下对加速性能是否有影响，如果不影响的话降低内存损耗肯定是好事：）

**Comment by xtaci** [comment]
嗯，三个段的阈值，拍脑袋的，基本就是假定经过三个段后不会有乱序到达的数据包。

**Comment by bettermanbao** [comment]
fec(10, 3)用新版测试下来，加速性能丝毫不受影响。

另外原来fec queue设得那么长，应该完全没必要吧？原来的8192也是拍脑袋想出来的吧？ 

还有benchmark那个能否写个简单的.go文件，MIPS构架只能用go build生成2进制文件，然后运行。没法直接运行go test。

**Comment by xtaci** [comment]
8192那个本意是通过fecExpire（30s)过期的来清空队列，尽可能的等待乱序包。
这个大小，也就是8次sndwnd的大小，也就只能容纳8个rtt，也就是几秒的数据。

现在这种方式，就完全放弃等待，乱序当作丢弃。

**Comment by bettermanbao** [comment]
go test 我好像可以运行了，等我试试看。

**Comment by xtaci** [comment]
两种资源控制方式
1. 最大队列容量。
2. 定时器扫描清除。

现在的3倍队列是强化第一类控制，弱化第二类控制。 之前是强化第二类控制。

**Comment by bettermanbao** [comment]
go test -bench 应该可以，等我周一再试试看吧。

**Comment by xtaci** [comment]
For instance, the command

	go test -v -args -x -v

will compile the test binary and then run it as

	pkg.test -test.v -x -v

**Comment by xtaci** [comment]
For instance, the command

	go test -v -myflag testdata -cpuprofile=prof.out -x

will compile the test binary and then run it as

	pkg.test -test.v -myflag testdata -test.cpuprofile=prof.out

**Comment by bettermanbao** [comment]
结果来了，salsa20竟然比xor还快。。。

BenchmarkAES128             500             3547706 ns/op
BenchmarkAES192             500             2688590 ns/op
BenchmarkAES256            1000            2179011 ns/op
BenchmarkTEA                  1000            1270455 ns/op
BenchmarkSimpleXOR       2000              635707 ns/op
BenchmarkBlowfish           1000            1446814 ns/op
BenchmarkNone             30000                 36694 ns/op
BenchmarkCast5               1000             2095292 ns/op
BenchmarkTripleDES              30          38259857 ns/op
BenchmarkTwofish               300            4787182 ns/op
BenchmarkXTEA                 1000            1895292 ns/op
BenchmarkSalsa20             2000              619567 ns/op

[root@R6850:/tmp]#cat /proc/cpuinfo
system type             : MediaTek MT7620
machine                 : Lenovo Y1S
processor               : 0
cpu model               : MIPS 24KEc V5.0
BogoMIPS                : 385.02
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r2
ASEs implemented        : mips16 dsp
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by xtaci** [comment]
有意思，基本和amd64一致，差异可能是字节对齐导致的，参考xor.go

**Comment by bettermanbao** [comment]
原来以为xor会比salsa20快很多，不过无所谓了。
今天这个更新绝对里程碑的，MIPS32的CPU+ 64M内存的路由可以完美运行就意味着目前市面上大多数家用路由都可以运行了。再次赞一下作者！

**Comment by xtaci** [comment]
集体智慧 ：）

**Comment by choicky** [comment]
手机、办公室电脑、家里电脑、路由器等多个地方用到 kcptun ，懒得折腾，所以kcptun参数都相同。

5M以上的网速就能满足我的要求。

所以主要目标就是保证这套参数在各个地方都能稳定使用。

而实践中，路由器中是最难稳定的。路由器中，使用的是含有kcptun的ss插件，这插件启用kcptun后经常出现著名的"problem detected"问题。

经过一番试验，发现关闭FEC能显著降低"problem detected"的出现频率。可能开启FEC导致kcptun进程比较耗资源，进程被干掉了。

ps，得加上 -nocomp ，否则路由器网速非常慢，估计路由器没有能力解压导致的。

**Comment by LiR1cky** [comment]
梅林的固件里要稳定用kcptun需要安装插件中心里的虚拟内存，另外目前1118版的client还没更新到梅林SS插件里，更新后应该能显著降低内存消耗的。

我昨晚试了下1118版，加速效果跟1111没有明显差异。内存消耗确实降低了。感谢作者提供这么好的工具！

**Comment by choicky** [comment]
之前pd时，以为是内存不够，就加了256m虚拟内存。系统里面也显示这虚拟内存了，但pd问题还在。

怀疑是路由器固件对，每个进程耗用的，资源量有阈值，超过了就干掉了。我发现系统内存耗用量才50多m也会出现pd

**Comment by LiR1cky** [comment]
PD有时只是显示问题，我经常碰到上网正常但显示PD的情况…尤其是使用kcptun的情况下。所幸我还有个x86的NAS所以就把kcptun client放在nas上了，这样稳定很多性能也更好

**Comment by bettermanbao** [comment]
可能是梅林固件的问题，我用openwrt，pdns作为dnsmasq的上游把dns请求转换成tcp形式通过ss转发给8.8.8.8，ss再通过kcptun连到vps。在1118版以前也能稳定运行，我路由是mt7620 + 64M内存的K2，rcvwnd sndwnd我设得比较小，设成128，网速接近3Mbps。更新1118版后256也能稳定运行了，网速也翻倍到6Mbps。你们刷梅林的路由应该各方面都比我的K2好很多，性能上肯定不是问题。

**Comment by wang20150419** [comment]
WNDR4300, 128M 内存，安装运行后，一会儿就退出来了。咋办？

**Comment by bettermanbao** [comment]
下载1118版，sndwnd rcvwnd设成256

**Comment by wang20150419** [comment]
需要设置其他环境变量吗？看到你的64M跑的欢，我才在 WNDR4300上试的， sndwnd = rcvwnd=128, 启动前可用内存 75M,  可启动，ps 显示和其他进程不一样，比较怪，再ps，就找不到它了。

**Comment by bettermanbao** [comment]
不需要其他设置，你关压缩了吗？

**Comment by wang20150419** [comment]
哦，压缩我用的缺省值。

**Comment by choicky** [comment]
我路由器一定得关闭压缩，否则很卡

**Comment by TMily** [comment]
2.5Mbps？ 好可怜。。。确认不是2.5MB/s？

**Comment by choicky** [comment]
2.5mbps已经能流畅看720p以及一部分1080p了吧，可以了 😀

**Comment by bettermanbao** [comment]
2.5Mbps是因为rcvwnd设得比较小128，我的VPS流量一大会被封。瓶颈不在路由器，调大rcvwnd可以轻松上10Mbps。

**Comment by TMily** [comment]
好吧 作为飙速党我刚刚跑出了95Mbps。。

**Comment by choicky** [comment]
我有时候也是飙速党。
但，为了让家里wifi能随时流畅YouTube，就得把稳定放在首位了，因为kcptun断流或挂掉时老婆和小孩并不会去路由器进行设置啊。

**Comment by bettermanbao** [comment]
我写了一个watchdog，30秒检查一次wget一次google.com，出错就重启kcptun和ss，这样就不担心不稳定了。

**Comment by choicky** [comment]
@bettermanbao 怎么操作的？是不是先开启路由器的telnet，然后ssh进入，然后写脚本、运行之类的？

麻烦给个教程... 我只是一个律师啊，真的是律师 ^_^

**Comment by TMily** [comment]
@choicky 你的路由是openwrt的么 openwrt有个官方的包watchcat，用那个就可以吧你可以让路由发现翻墙不通的时候reboot

**Comment by choicky** [comment]
@bettermanbao 我不是openwrt，我是改版的梅林

**Comment by TMily** [comment]
有计划任务功能么我用的X86 Openwrt 不太了解梅林

**Comment by TMily** [comment]
检测网络的shell挺简单的 下面这个示例只是判断没有重启KCP的部分你可以自己补充下 先ps获得PID kill掉再启动或者你如果是写了服务的可以直接重启服务
修改完后把脚本添加到计划任务定期执行就好
`#!/usr/bin/bash
#
#检测网络链接&&ftp上传数据  
function networkAndFtp()  
{  
    #超时时间  
    timeout=5  
      
    #目标网站  
    target=www.baidu.com  
  
    #获取响应状态码  
    ret_code=`curl -I -s --connect-timeout $timeout $target -w %{http_code} | tail -n1`  
  
    if [ "x$ret_code" = "x200" ]; then  
        #网络畅通  
    else  
        #网络不畅通  
    fi  
}
`

**Comment by bettermanbao** [comment]
等我回家把我的watchdog贴给你吧。
基本思路是找到ss的启动脚本，把kcptun的启动命令和watchdog一起加进去，让kcptun和watchdog随ss一起启动和停止。

watchdog的脚本里面用wget测试google的联通情况。

**Comment by wang20150419** [comment]
关闭压缩后，在网件的WNDR4300上跑的超级爽。（128M内存）

**Comment by bettermanbao** [comment]
我现在在用的脚本来了，简单实用，随ss启动一起启动，随ss停止一起停止。

#!/bin/sh

while true; do
        sleep 30
        LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")

        wget -s -q http://www.google.com.hk
        if [ "$?" == "0" ]; then
                echo "[$LOGTIME] No problem."
        else
                wget -s -q http://www.baidu.com
                if [ "$?" == "0" ]; then
                        echo "[$LOGTIME] Problem decteted, restart Shadowsocks."
                        /etc/init.d/shadowsocks restart
                else
                        echo "[$LOGTIME] Network problem. Do nothing."
                fi
        fi
done
