### ISSUE TITLE
求一份kcptun mac版的详细教程 感谢

### ISSUE THREAD

**Issue by YangYunLong** [xtaci/kcptun#279]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

**Comment by xtaci** [comment]
README就是以mac+linux为蓝本的。

**Comment by KngEast** [comment]
其实你缺的多是图形界面，给你个
https://github.com/dfdragon/kcptun_xclient

**Comment by KngEast** [comment]
该作者给windows也做了图形界面，两者几乎一样，蛮好用的

**Comment by YangYunLong** [comment]
怎么运行起来GUI呢？

**Comment by KngEast** [comment]
放到应用程序里再运行，否则闪退

**Comment by YangYunLong** [comment]
运行那个文件？

**Comment by YangYunLong** [comment]
@KngEast  mac 用什么软件打开你那个Pascal写的GUI ?

**Comment by YangYunLong** [comment]
@KngEast  需要下载fpc 吗？

**Comment by YangYunLong** [comment]
@xtaci  不知道如何配置 有详细的教程吗？

**Comment by xtaci** [comment]
所有的详细教程都是README的一种解释和应用。

**Comment by KngEast** [comment]
@YangYunLong  从这个网址下载，https://github.com/dfdragon/kcptun_xclient/releases

**Comment by YangYunLong** [comment]
@KngEast  多谢 多谢

**Comment by benqiu** [comment]
多谢，上面提供的客户端，终于解决了，比较烧脑，端口号周转次数太多了。

**Comment by Rainsho** [comment]
开始没看到macOS系统的GUI，用这个一键安装脚本https://github.com/kuoruan/kcptun_installer在服务器端安装完，直接把生成的“客户端”配置另存为config.json，然后用-c config.json启动客户端服务，目前好像一切正常。

**Comment by chenxiccc** [comment]
@Rainsho 请问 @kuoruan 的一键安装脚本安装后 **客户端**的config.json文件在哪个目录？我只在/usr/share/kcptun 下找到了 Server端的配置文件。

**Comment by Rainsho** [comment]
@chenxiccc 没有自动生成文件，但控制台会输出PC端可用配置，是json格式的，你把他复制下来然后新建个json文件就可以了。

**Comment by chenxiccc** [comment]
@Rainsho 多谢~~

**Comment by Globl** [comment]
@Rainsho 已经在 vps 上整了 kcptun 的服务端，也看到了你说的控制台输出 pc 端可用配置。但是保存下来，在我 mac 上怎么使用。。。

**Comment by Rainsho** [comment]
@Globl 安装对应版本的客户端，使用 -c 指定配置文件。差不多是这个样子的: 

```bash
./client_darwin_amd64 -c ./config.json
```

**Comment by Globl** [comment]
@Rainsho mac 是哪个版本。。。

**Comment by Globl** [comment]
额。。搞定了。。。3Q

**Comment by fatezeronight** [comment]
进入图形化界面最上面的文件选择框里面放什么？

**Comment by walkerwzy** [comment]
> @Globl 安装对应版本的客户端，使用 -c 指定配置文件。差不多是这个样子的:
> 
> ```shell
> ./client_darwin_amd64 -c ./config.json
> ```

```
./kcptun -c ../kcptun-config.json 
2019/05/17 18:30:28 version: 20190515
2019/05/17 18:30:28 initiating key derivation
2019/05/17 18:30:28 listening on: 127.0.0.1:8388
2019/05/17 18:30:28 encryption: aes-192
2019/05/17 18:30:28 nodelay parameters: 1 20 2 1
2019/05/17 18:30:28 remote address: 188.166.235.199:29900
2019/05/17 18:30:28 sndwnd: 2048 rcvwnd: 2048
2019/05/17 18:30:28 compression: true
2019/05/17 18:30:28 mtu: 1350
2019/05/17 18:30:28 datashard: 10 parityshard: 3
2019/05/17 18:30:28 acknodelay: false
2019/05/17 18:30:28 dscp: 0
2019/05/17 18:30:28 sockbuf: 4194304
2019/05/17 18:30:28 smuxbuf: 4194304
2019/05/17 18:30:28 keepalive: 10
2019/05/17 18:30:28 conn: 1
2019/05/17 18:30:28 autoexpire: 0
2019/05/17 18:30:28 scavengettl: 600
2019/05/17 18:30:28 snmplog: 
2019/05/17 18:30:28 snmpperiod: 60
2019/05/17 18:30:28 quiet: false
2019/05/17 18:30:28 connection: 0.0.0.0:55697 -> 188.166.235.199:29900
```
这是连接成功了吗? 我本地建http代理, 端口8388? 无效

**Comment by walkerwzy** [comment]
> @Globl 安装对应版本的客户端，使用 -c 指定配置文件。差不多是这个样子的:
> 
> ```shell
> ./client_darwin_amd64 -c ./config.json
> ```

```
./kcptun -c ../kcptun-config.json 
2019/05/17 18:30:28 version: 20190515
2019/05/17 18:30:28 initiating key derivation
2019/05/17 18:30:28 listening on: 127.0.0.1:8388
2019/05/17 18:30:28 encryption: aes-192
2019/05/17 18:30:28 nodelay parameters: 1 20 2 1
2019/05/17 18:30:28 remote address: xxx.xxx.xxx.xxx:29900
2019/05/17 18:30:28 sndwnd: 2048 rcvwnd: 2048
2019/05/17 18:30:28 compression: true
2019/05/17 18:30:28 mtu: 1350
2019/05/17 18:30:28 datashard: 10 parityshard: 3
2019/05/17 18:30:28 acknodelay: false
2019/05/17 18:30:28 dscp: 0
2019/05/17 18:30:28 sockbuf: 4194304
2019/05/17 18:30:28 smuxbuf: 4194304
2019/05/17 18:30:28 keepalive: 10
2019/05/17 18:30:28 conn: 1
2019/05/17 18:30:28 autoexpire: 0
2019/05/17 18:30:28 scavengettl: 600
2019/05/17 18:30:28 snmplog: 
2019/05/17 18:30:28 snmpperiod: 60
2019/05/17 18:30:28 quiet: false
2019/05/17 18:30:28 connection: 0.0.0.0:55697 -> xxx.xxx.xxx.xxx:29900
```

这样是成功了吗? 当我尝试去建立http和socks5的127.0.0.1:8388的代理, 均无效:
```
2019/05/17 18:34:28 stream closed 43
2019/05/17 18:34:32 stream opened 45
2019/05/17 18:34:33 stream closed 45
2019/05/17 18:34:40 stream opened 47
2019/05/17 18:34:41 stream opened 49
2019/05/17 18:34:42 stream opened 51
2019/05/17 18:34:44 stream opened 53
2019/05/17 18:34:51 stream opened 55
2019/05/17 18:35:01 stream opened 57
2019/05/17 18:35:03 stream opened 59
2019/05/17 18:35:10 stream closed 47
2019/05/17 18:35:11 stream closed 49
2019/05/17 18:35:12 stream closed 51
2019/05/17 18:35:14 stream closed 53
2019/05/17 18:35:14 stream opened 61
```

**Comment by Rainsho** [comment]
@walkerwzy 差不多是这样工作的 ss-server -> kcptun-server -> kcptun-client -> ss-client -> ... 

我猜测你可能少了本地的 ss-client 去连本地的 kcptun-client 的过程

**Comment by walkerwzy** [comment]
> @walkerwzy 差不多是这样工作的 ss-server -> kcptun-server -> kcptun-client -> ss-client -> ...
> 
> 我猜测你可能少了本地的 ss-client 去连本地的 kcptun-client 的过程

是的,我用ss的密码建了kcptin-client监听端口的代理后就连上了
