### ISSUE TITLE
如何查看SNMP信息？

### ISSUE THREAD

**Issue by longdanie** [xtaci/kcptun#281]
新手，费老大劲才在搬瓦工上部署好KCPTUN，今天就测试了一天，跑了20G的流量，可怜我每月总共也才只有100G的流量，如何通过查询SNMP信息来最优化我的KCPTUN，以达到流量与速度的平衡？求指导！
服务器信息：搬瓦工年费$2.99元的服务器，应该是OpenVZ系统
软件：shadowsocks，搬瓦工面板自带安装

**Comment by baggiogogo** [comment]
配置文件里面指定下log，然后按照wiki操作，可以打印在log里面，windows看不出。

**Comment by longdanie** [comment]
不好意思，你说的“配置文件里面指定下log”，怎么指定？用哪个参数？

**Comment by baggiogogo** [comment]
.json里面加一行
"log": "/var/log/kcptun.log"
看的时候cat /var/log/kcptun.log

**Comment by longdanie** [comment]
晕，我加的参数是："log":"~/kcptun.log"，结果服务端报错没运行起来。才想起来，我用的是一键安装脚本，脚本自动创建了一个“nobody”用户来执行kcptun，该用户不可能拥有root权限来写入root家目录。

**Comment by longdanie** [comment]
不知道什么情况，一加这个参数，就连接不上服务器，去掉就行。

**Comment by baggiogogo** [comment]
暂且抛开你说的这个问题，检查下逗号空格这些。
如果一切OK，那就先不要用一件脚本，直接下载了解压用，测试完了再用回你原来的就好。
参数是没问题的

**Comment by longdanie** [comment]
多谢，我再测试一下。

**Comment by qwbht** [comment]
baggiogogo  按照你的方法配置。以前 时间段7-10点，跑3000，现在13000。
其他时间，默认都是10000+左右。。非常感谢

**Comment by baggiogogo** [comment]
不客气，有帮助就好。

**Comment by CuminLo** [comment]
@baggiogogo 在log里面并没有看到outsegs和insegs 求赐教

**Comment by baggiogogo** [comment]
kill -SIGUSR1 pid，pid号用ps命令查找。@CuminLo

**Comment by CuminLo** [comment]
@baggiogogo 谢谢，看到了。
