### ISSUE TITLE
有没有参数可以关掉这2个打印

### ISSUE THREAD

**Issue by yjd** [xtaci/kcptun#282]
2016/11/21 09:44:23 stream opened
2016/11/21 09:44:25 stream closed

会有很多这样的打印信息

**Comment by bpplpp** [comment]
为什么要关掉，这个是排除故障的时候很有用的，如果嫌弃日志过大，就设定自动重启kcp就好啦

**Comment by yjd** [comment]
太多这种一直在打印也没什么好看的吧，刷一下一列出来你也不知道什么情况？
话说真正有用设计成打印统计数据是不是更合理？
比如
2016/11/21 09:44:23 stream opened  110
2016/11/21 09:44:25 stream closed   120

**Comment by xtaci** [comment]
通常是用tmux开着的，观测很重要。
