### ISSUE TITLE
kcptun连接失败，stream closed，搬瓦工。

### ISSUE THREAD

**Issue by sammylp** [xtaci/kcptun#283]
配置如下，udp端口用nc可连，server是最新版本kcp，centos，client也是最新客户端，windows8。没有telnet因为server是搬瓦工，直连ok。下面配置敏感信息我做了修改，不过保证配置一致正确。

{
    "localaddr": ":5644",
    "remoteaddr": "104.194.68.182:12345",
    "key": "****",
    "crypt": "salsa20",
    "mode": "fast",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}

client配置：
-l :9527 -r 104.194.68.188:12345 -key "****" -crypt salsa20 -nocomp -datashard 10 -parityshard 3 -sndwnd 512 -rcvwnd 512 -mode fast

特征是刚开始用软件时正常，重启客户端电脑后就连不上了，log是：
2016/11/21 15:41:17 stream closed
2016/11/21 15:41:17 stream opened
2016/11/21 15:41:17 stream opened
2016/11/21 15:41:17 stream opened
2016/11/21 15:41:17 stream closed
2016/11/21 15:41:17 stream closed
2016/11/21 15:41:17 stream closed
2016/11/21 15:41:17 stream closed
2016/11/21 15:41:17 stream closed
2016/11/21 15:41:17 stream closed
2016/11/21 15:41:17 stream opened
2016/11/21 15:41:18 stream closed
2016/11/21 15:41:23 stream opened
2016/11/21 15:41:23 stream closed

**Comment by choicky** [comment]
我客户端上也这样，但不影响使用的样子。

**Comment by sammylp** [comment]
log上好像没什么问题，但是就是ss client没有流量。我直连SS server就可以。

**Comment by choicky** [comment]
@sammylp 可能kcptun服务器端与客户端设置参数不一致；也可能是udp被屏蔽或干扰了。

**Comment by sammylp** [comment]
参数应该是一致的，因为之前已经配置成功了，并且我检查了几遍。至于udp被干扰，我试着用nc命令访问该端口，是OK的。

**Comment by choicky** [comment]
贴kcptun两端的参数看看。
另外检查下两端的防火墙
