### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by Magikarp96** [xtaci/kcptun#284]
KCP能否在IOS上运行，目前shadowrocket好像不行

**Comment by alex43211** [comment]
ios的客户端不支持吧，我是在电脑上开了kcp客户端运行然后在ios的ss客户端指向电脑的ip地址在用

**Comment by flylj999** [comment]
> ios的客户端不支持吧，我是在电脑上开了kcp客户端运行然后在ios的ss客户端指向电脑的ip地址在用

能否用ios的ss客户端指向安卓手机的ip地址，ios的ss客户端的端口应该设置成什么啊
