### ISSUE TITLE
11.18windows64 客户端断流厉害

### ISSUE THREAD

**Issue by ruan11223344** [xtaci/kcptun#287]
半小时就断流........... 参数 D:\soft\KcpTun\client_windows_amd64.exe -l 192.168.31.16:8390 -r ss.33i2.com:7379  -key 123111 -crypt aes -mode fast2

**Comment by cjjdaq** [comment]
最近udp干扰已经越来越严重了。

**Comment by alex43211** [comment]
是啊，现在单纯用shadowsocks都连不上去。

**Comment by ruan11223344** [comment]
现在用v20160922的客户端就正常了。说真的 好邪门，不能用最新版。

**Comment by cjjdaq** [comment]
马上也换0922看看，这会用finalspeed顶着呢。

**Comment by cjjdaq** [comment]
0922也是说断就断，udp已经无解

**Comment by qwbht** [comment]
换端口， 曾经29900端口 也是这样。换443 没出现了~

**Comment by cjjdaq** [comment]
换端口也不行呀，，说断就断

**Comment by baggiogogo** [comment]
改加密方式，降窗口，配置5/5的FEC。
如果以前不这样，先耐心等吧，兴许是线路问题，还有救。

**Comment by dolphinpaopao** [comment]
三大运营商中的电信是常态，况且最近电信的骨干出现故障，过阵子可能会缓解。

**Comment by cjjdaq** [comment]
貌似故障在16后修复了呀。开始使用的时候一直比较稳定，然后渐渐的每天早晨基本就连不上了，重启下两端可以撑个白天，最近是说断就断。重启都没办法。改加密，换密码，换端口，降窗口，改mtu，改fec换服务器ip，能试都试了，特别是这几天基本没安稳使用过。

**Comment by dolphinpaopao** [comment]
电信上海出口继续有问题，高峰BOOM。不过CQ这边走广州出口的一直都能1080P。

**Comment by cjjdaq** [comment]
断掉的时候用iperf3测试发现udp完全不通，封锁3到5分钟后又通了

**Comment by msghost** [comment]
CD这边也是断流非常严重，基本上连续用几分钟就会断掉。

**Comment by msghost** [comment]
客户端参数：client_windows_amd64_20161118.exe" -l :1079 -r x.x.x.x:443 -key "xxxxxx" -crypt salsa20 -datashard 5 -parityshard 5 -mtu 512 -sndwnd 128 -rcvwnd 256 -dscp 46 -mode manual -nodelay 1 -interval 40 -resend 2 -nc 1

**Comment by cjjdaq** [comment]
现在出口直接封锁所有udp，过几分钟就好，但也用不了几分钟。

**Comment by ruan11223344** [comment]
我已经正常了.....server 是最新版的。 客户端是v20160922  话说我是挂在阿里云BGP 和 日本Linode之间

**Comment by cjjdaq** [comment]
从昨晚新换了IP后到现在没有断，用fast测试一般能跑到45M左右，不知道是否还能坚挺多久。

**Comment by linhua55** [comment]
https://github.com/xtaci/kcptun/issues/228#issuecomment-265099479
