### ISSUE TITLE
[提问]KCP为shadowsocks加速，在手机上使用时会消耗更多的手机流量吗？还是只消耗更多的服务器流量？

### ISSUE THREAD

**Issue by chenxiccc** [xtaci/kcptun#288]
请教：

KCP为shadowsocks加速，手机上使用shadowsock并设置KCP加速。
手机上通过代理上网，会消耗更多的流量吗？还是KCP只会消耗更多的服务器的流量，对客户端的使用无明显流量差异？

**Comment by dolphinpaopao** [comment]
试试就知道了啊，哈哈，不会。

**Comment by Faithful-Mind** [comment]
搜过，有传说是至少两倍流量。希望这个传说不是真的，不然就太可怕了

**Comment by kmahyyg** [comment]
真的，两边都会消耗，具体多少倍取决于你的配置。

2016年11月23日 22:28，"Faithful-Mind" <notifications@github.com>写道：

**Comment by chenxiccc** [comment]
在Google上也搜索到了各种说法，所以到此来求证，不知作者 @xtaci 是否可以提供个权威答案呢？
因为常使用手机4G连接，故有此疑问。

**Comment by wxyzh** [comment]
两边都会消耗流量的，应该是服务器上kcptun的上行流量等于你手机上kcptun的下行流量。

**Comment by xtaci** [comment]
速度快了，自然流量就用的多了

**Comment by chenxiccc** [comment]
@xtaci 多谢回复。
我指的是：同样下载一个100KB的图片，使用KCP与不使用KCP，在手机上是否可能会消耗明显大于（比如1倍）100KB的流量？

**Comment by xtaci** [comment]
取决于你的线路品质，在我的线路(UDP丢包30%）的情况下，是会消耗多一倍。

**Comment by chenxiccc** [comment]
@xtaci 多谢。虽然计算公式未能完全理解，不过疑问已closed~😀

**Comment by airborne007** [comment]
先说结论，会大大的消耗手机流量，建议手机在wifi状态使用。
我之前不知道，结果那个月流量超了2G多，而且只用了两天就超了这么多。
亲身经历，希望大家引以为戒！！！

**Comment by dearneo** [comment]
移动网络下的计费是统计手机的上行+下行的流量总和的，只要你手机接收到了KCP服务器发出的udp包，就会被计费。建议专门开个参数温和点的端口专门给手机网络下使用。我在手机上（移动4G）只使用原版ss服务速度就很好了，800KB/s左右，基本不需要用kcp加速

**Comment by chenxiccc** [comment]
@dearneo 请问你的VPS的哪家的哪个地区的服务器？在不开KCP的情况下能达到800KB/s。

**Comment by dearneo** [comment]
@chenxiccc hostus 新加坡机房，移动4G下直连速度的确很好，但电信的网络下就只有60KB/s

**Comment by icymind** [comment]
会. 出门开 kcptun 超了好多, 4G 下还是老实用 ss 就行了

**Comment by weyou** [comment]
流量耗费多还不是重点，ss开了kcp后耗电量实在太大了。

**Comment by wkingfly** [comment]
@chenxiccc 现在有kcptun的iOS客户端了么

**Comment by chenxiccc** [comment]
@wkingfly 安卓的shadowsocks官方客户端支持KCP

**Comment by 1563172697** [comment]
同问ios现在有kcptun的客户端了吗

**Comment by Cye3s** [comment]
我是把家里kcptun加速后的的ss端口开放给手机连（手机上不配置kcptun），不知道是不是也多费流量

**Comment by weyou** [comment]
这种方式肯定不会多耗手机流量了

2016年12月9日 11:36，"Cye3s" <notifications@github.com>写道：

我是把家里kcptun加速后的的ss端口开放给手机连（手机上不配置kcptun），不知道是不是也多费流量

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/xtaci/kcptun/issues/288#issuecomment-265925337>, or mute
the thread

**Comment by chenxiccc** [comment]
@Cye3s 你是在家里架设了一个ss-server，之后把ss-server的监听端口设置为KCP提供代理的端口吗？

**Comment by Roachard** [comment]
开着kcp确实真的太费电了，还好联通移动网络下ss速度堪比电信宽带开着kcp。

**Comment by Cye3s** [comment]
@chenxiccc 路由上没有启动ss-server，只是把kcp加速后的端口开放出来当成ss-server的端口，就像只做了个端口转发

**Comment by chenxiccc** [comment]
@Cye3s 那在手机上直接设置WIFI的Socks代理（或使用Surge等设置socks类型的代理），而不是使用Surge等设置shadowsocks？在外网使用DDNS也能用吗？

**Comment by Cye3s** [comment]
@chenxiccc 没试过，代理服务器地址用路由的ddns的域名么？应该是可以的吧

**Comment by icymind** [comment]
@Cye3s 看来你只是在 WiFi 下用, 那还问什么"我是把家里kcptun加速后的的ss端口开放给手机连（手机上不配置kcptun），不知道是不是也多费流量".... 😳😳😳

**Comment by Cye3s** [comment]
@icymind 不啊，我是Android，有方便的ss客户端，OpenWRT上开放加速后的ss服务端口，设置ddns，手机在4G状态下连接家里的路由，就能享受加速后的ss。在家用 WiFi 就直接路由上dnsmasq-full+ipset+iptables透明ss了啊

**Comment by chenxiccc** [comment]
@Cye3s 能详细说下嘛？Openwrt上ss的提供服务的端口和KCP提供服务的端口分别是啥（KCP监听的ss端口等于ss提供服务的端口，KCP提供服务的端口与ss提供服务的端口不相同）？哪个ss客户端，代理类型是什么呢？

**Comment by icymind** [comment]
@Cye3s 对不起, 我理解错了. 这样不会多消耗流量的, 因为多倍发包的过程是用有限网络完成的. 看来我也要破解下光猫, 在路由器拨号算了. 不知道4g 连路由速度如何

**Comment by chenxiccc** [comment]
@icymind 无需破解光猫，直接打电信电话或者去营业厅，把连接模式改为桥接，即可路由器拨号。

**Comment by Cye3s** [comment]
@icymind 嗯，路由要桥接模式，并且有外网IP最好，我家是100M电信光纤，上行6M，电信4G连接上Play市场下载东西，速度一般在600KB/s-1.2MB/s，一般只是下载东西，完全足够了，也没测试过最快多少。如果宽带只有NAT后的内网IP，速度可能还会受其它服务的影响，比如ngrok

@chenxiccc 
比如，VPS上的ss-server端口是1583，kcptun服务端的端口是29999，然后路由上kcptun客户端连接VPS的29999端口，在路由的1585端口监听，路由上再配置开放1585端口，然后手机上配置ss接连xxxx.ddns.com的1585端口就行了

**Comment by chenxiccc** [comment]
@Cye3s 实验了一下，kcp监听1091端口，使用1091端口和ss的密码和加密方式，没有成功。
路由上只跑一个Kcptun即可，无需再跑一个ss-server做转发？

`start-stop-daemon -S -q -b -m -p /tmp/var/kcp.pid -x /koolshare/bin/client_linux_arm5 -- -l 127.0.0.1:1091 -r $ss_basic_server:$ss_basic_kcp_port $ss_basic_kcp_parameter`

**Comment by chenxiccc** [comment]
@Cye3s 看起来已经解决了，路由上把kcp的监听IP从127.0.0.1改为0.0.0.0就OK了~

**Comment by chenxiccc** [comment]
@Cye3s 额，还是不成。在路由器WiFi下可以。但是用联通4G就不成。请问，你上文中提到的“路由上配置开放1585端口”是指配置端口转发吗？如果是配置端口转发，转发的目的IP是路由IP（比如192.168.1.1）吗？

**Comment by fredricktoy** [comment]
移动4G连新加坡很快，不需要kcptun。为了要解决iPhone客户端的问题，而且宽带是电信的，只能openvpn+ kcptun+ ss。近2个月的使用，效果不错。

**Comment by dearneo** [comment]
@chenxiccc 路由器wan口一般有防火墙限制，配置端口转发一般是没用的，需要手工修改路由器的wan口的防火墙配置开放wan口指定端口的访问限制

**Comment by zwisus** [comment]
而且很耗电，1.5Ghz 4核的CPU 一直保持在5%-10%， KCPTUN进程。

**Comment by PINK-FL0YD** [comment]
多么痛的领悟，刚才发现开着kcp就不到五个小时用了1g流量，日了🐶了

**Comment by anjia0532** [comment]
可以试一下Google的bbr，单边加速。基本能跑满服务带宽。不会存在多倍发包的问题

**Comment by MoeGakuen** [comment]
@anjia0532 挖坟了老铁

**Comment by zxq1002** [comment]
确实耗电比不开kcp多了好几倍。。

**Comment by tom13amy** [comment]
我也是今天才知道！！难怪这几个月流量控制不住！
