### ISSUE TITLE
vps被墙了vultr

### ISSUE THREAD

**Issue by Demired** [xtaci/kcptun#290]
我的vultr挂上kcptun就被墙了，服务器流量用的不到30MB，那几秒钟速度挺快，gmail秒开，我这种情况应该怎么处理？
![filehelper_1479968456930_23](https://cloud.githubusercontent.com/assets/10645595/20588585/45842728-b251-11e6-9f23-ac743fd3c4ca.png)

**Comment by bettermanbao** [comment]
流量太大，被suspend了吧？
