### ISSUE TITLE
question about parameter

### ISSUE THREAD

**Issue by limbo127** [xtaci/kcptun#293]
Hello, 
KCP SNMP:&{BytesSent:4885439 BytesReceived:300639488 MaxConn:329 ActiveOpens:0 PassiveOpens:689 CurrEstab:328 InErrs:0 InCsumErrors:51460 InSegs:620392 OutSegs:252542 OutBytes:41189722 RetransSegs:7577 FastRetransSegs:0 EarlyRetransSegs:2746 LostSegs:4831 RepeatSegs:11580 FECRecovered:35813 FECErrs:0 FECSegs:139565}

kcptun_server --mode normal --mtu 1460 --listen :6082 --target 127.0.0.1:8002 --key test --crypt aes-128 --nocomp

Can you tell me how optimize my kcptun configuration.
In particular, can you explain more precisely kcp snmp information ?

FECErrs:0   ? there's no error detected, so i must delete FEC configuration ? 

Regards, 
Nicolas

**Comment by xtaci** [comment]
fecerrs :0 means:  NO configurations errors has detected.

**Comment by limbo127** [comment]
so can i pass datashard and partityshard to 0 ?
How decrease lostsegs ? / retransSegs ?
Can you explain kcp snmp variable, is's very important for us to do test and progress with our configuration.
regards, 
Nicolas

**Comment by xtaci** [comment]
0 means FEC has disabled;

improve the link quality(buy expensive link) will lower retrans/lost segs.

currently, you can only find definitions in the https://github.com/xtaci/kcp-go/blob/master/snmp.go, i may add some comments later days.

**Comment by limbo127** [comment]
ok,
play with  rcvwnd ,sndwnd and mtu cannot decrease lost segs ?
Regards.
