### ISSUE TITLE
有iphone可以用的客户端吗？求推荐一个

### ISSUE THREAD

**Issue by ayp777** [xtaci/kcptun#294]
有iphone可以用的客户端吗？求推荐一个

**Comment by whour** [comment]
#284 和 #291  都被作者关闭了. Golang的WIKI上是有golang build iOS的文档，需要OSX和Xcode。
[https://github.com/golang/go/wiki/Mobile#user-content-building-and-deploying-to-ios](https://github.com/golang/go/wiki/Mobile#user-content-building-and-deploying-to-ios)
不知道会不会有人用Swift 重造轮子。
@xtaci

**Comment by fnscar** [comment]
把kcptun客户端部署在路由器上是个直接的办法。

**Comment by whour** [comment]
目前没有iOS客户端的情况下这个也是个体验kcptun快感的办法，不是只能是WIFI环境。
这个是OpenWrt的kcptun客户端
[https://github.com/kuoruan/luci-app-kcptun](https://github.com/kuoruan/luci-app-kcptun)

**Comment by xayoung** [comment]
电脑或者路由器跑kcptun，iPhone端的SS指向该IP也是一个方案

**Comment by ayp777** [comment]
这就比较麻烦了，手机还是用SS方便

**Comment by alex43211** [comment]
ios设备出门了是不方便，目前还是按照楼上的办法电脑或者路由器跑kcptun服务端，ios设备指向它靠谱

**Comment by chenxiccc** [comment]
@xayoung @alex43211 这样是可行，不过对路由器或者电脑所在网络的上传带宽要求比较高。如果路由器放在家里，大部分电信只给了4MB/s的上传，比较捉急。

**Comment by 1563172697** [comment]
@xayoung 能否给一个详细的教材，新手学习一下，目前K2路由

**Comment by alex43211** [comment]
@chenxiccc 唉，现实的环境就是如此啊

**Comment by phlips5437** [comment]
我现在家里上行20M，理论上可以在路由器里安装个ss-server，手机通过ip指向家里路由器的外网ip
如果要做的好一点就是再做一个ddns
但是我现在的顾虑是怕这个域名以后会不会被封掉
因为我以前在自家路由器上开过l2tp，通过域名方式拨入vpn，刚开始一段时间用着很满意，但后来就再也无法访问了，不管怎么配置都不行。。。

**Comment by whour** [comment]
![_2017-03-31_11-15-07](https://cloud.githubusercontent.com/assets/4928187/24534933/86b57c90-1603-11e7-85cd-77796fee587b.png)

这个测试版本有了kcptun的支持。
Testfight 申请地址：
https://docs.google.com/forms/d/e/1FAIpQLSdBcIfAZY15BaXMzAq1Rj0kpTJ4xFBqkzwIbxYhAmmse7NXBQ/viewform?c=0&w=1
https://itunes.apple.com/cn/app/a-big-t-a-smart-vpn/id1051326718?l=en&mt=8

**Comment by h3idan** [comment]
A.BIG.T 搞出来就有点酷了。

**Comment by zhouyisu** [comment]
A.BIG.T 现在TF版本就支持了。只是compress目前只能选择none。可以在twitter上向开发者申请测试版。

**Comment by h3idan** [comment]
不用申请。直接 appstore 下载就行了。需要花6块钱买 kcptun 功能。整体买68。

**Comment by hiduoshao** [comment]
@h3idan 买了啊，好像没啥反应

**Comment by h3idan** [comment]
我的还可以，看youtube挺快的


----
Best.
xiaohei.

--------------------------------------

     Twitter：@h3id4n <https://twitter.com/h3id4n>
     GitHub：github.com/h3idan

--------------------------------------

2017-07-27 16:31 GMT+08:00 hiduoshao <notifications@github.com>:
