### ISSUE TITLE
上传超过运营商带宽正常吗？

### ISSUE THREAD

**Issue by ayp777** [xtaci/kcptun#295]
本人联通50m宽带。上传是2M
看视频效果很好，但是一旦打开google相册上传图片。
上传速度就飙到3000k/s左右，远远超出2M带宽了。这个正常吗？

**Comment by bettermanbao** [comment]
魔都电信表示也有这种情况，可能是ISP对UDP限速不精准造成的。

**Comment by think2011** [comment]
+1

**Comment by think2011** [comment]
问题是我的 `Dropbox` 始终都上传不上去某个文件（3M），而且速度一直保持高速上传，直到我去网页版上传才成功。

**Comment by haodong** [comment]
same issue until I closed kcptun.

**Comment by xtaci** [comment]
什么版本？

**Comment by baggiogogo** [comment]
降客户端发送窗口

**Comment by w12928293** [comment]
我这也是，联通100m，上传一般都是1.2左右，现在google photos 稳定3000K/s

**Comment by haodong** [comment]
@xtaci kcptun version 20161118 on server
an earlier version on client (already updated and not using it so forgotten)

**Comment by ayp777** [comment]
@xtaci google photos上传速度显示在3000K/S，但是一直上传失败。
我用的是梅林固件的路由器，安装的shadowsocks 插件。
youtube加速效果明显，就是google photos一直上传失败。。。。

**Comment by haodong** [comment]
The newest version have this problem either (tested on PC)

![dec-15-2016 15-24-33](https://cloud.githubusercontent.com/assets/8103074/21215231/d4e62288-c2da-11e6-8340-2f9262b607b2.gif)

You can try it by yourself at [this page](http://file.mangafox.me/upload.php?series_id=528)

**Comment by choicky** [comment]
在我的经验里，Google Photo电脑板、Google Drive 电脑板、Chromecast升级时，都不兼容ss。手机端倒是兼容。
据说电脑板以及chromecast更新时走的不是ss的网络协议层，而是走vpn所在的那个网络协议层。
