### ISSUE TITLE
想在小米路由2上使用，但是执行后提示 Illegal instruction (core dumped) 

### ISSUE THREAD

**Issue by think2011** [xtaci/kcptun#297]
Illegal instruction (core dumped)  

用的文件是 client_linux_arm7，因为通过 uname -a看到的内容是 `Linux XiaoQiang 2.6.36 #2 SMP PREEMPT Mon Nov 21 15:57:14 CST 2016 armv7l GNU/Linux` 

请问该如何处理呢？

**Comment by pigpigabc123** [comment]
小米的核心太老了

**Comment by think2011** [comment]
那样的话，只能先刷第三方的系统才行了吗？

**Comment by wang20150419** [comment]
https://github.com/bettermanbao/openwrt-kcptun 到这里下载 kcptun-openwrt-ramips-20161118.tar.gz

**Comment by think2011** [comment]
@wang20150419 Hi,我的是原本系统，这个我有试过，记得也是返回错误的。

**Comment by fankangsong** [comment]
在小米开发版上运行：

`root@XiaoQiang:~# /etc/init.d/client_linux_mips32le -c /etc/kcptun.json
/etc/init.d/client_linux_mips32le: line 1: syntax error: unexpected "("`

**Comment by think2011** [comment]
@fankangsong 用了非arm的版本和 @wang20150419 说的版本似乎就是这个提示错误

看来要用到话，得刷个第三方的固件系统了
