### ISSUE TITLE
请教一下客户端的问题

### ISSUE THREAD

**Issue by lxlw1320** [xtaci/kcptun#298]
服务端用的是一键安装的脚本，端口看也有正常监听
{
"listen": ":38989",
"target": "127.0.0.1:28989",
"key": "x",
"crypt": "aes-128",
"mode": "manual",
"mtu": 1400,
"sndwnd": 1024,
"rcvwnd": 1024,
"datashard": 30,
"parityshard": 15,
"dscp": 46,
"nocomp": true,
"acknodelay": false,
"nodelay": 0,
"interval": 20,
"resend": 2,
"nc": 1,
"sockbuf": 4194304,
"keepalive": 10,
"log":"/var/log/kcptun.log"
}

客户端是下的最新版的arm5 放在ddwrt上使用的，每次运行完
{
"localaddr": "127.0.0.1:28989",
"remoteaddr": "x:38989",
"key": "x",
"crypt": "aes-128",
"mode": "manual",
"conn": 1,
"autoexpire": 300,
"mtu": 1400,
"sndwnd": 128,
"rcvwnd": 1024,
"datashard": 30,
"parityshard": 15,
"dscp": 46,
"nocomp": true,
"acknodelay": false,
"nodelay": 0,
"interval": 20,
"resend": 2,
"nc": 1,
"sockbuf": 4194304,
"keepalive": 10,
"log": "/mnt/sda1/kcp/log/kcptun.log"
}
就卡在
2016/11/27 08:53:40 version: 20161118
2016/11/27 08:53:40 listening on: [::]:12948
2016/11/27 08:53:40 encryption: salsa20
2016/11/27 08:53:40 nodelay parameters: 1 20 2 1
2016/11/27 08:53:40 remote address: xx.32.47.xxx:38989
2016/11/27 08:53:40 sndwnd: 128 rcvwnd: 1024
2016/11/27 08:53:40 compression: true
2016/11/27 08:53:40 mtu: 1350
2016/11/27 08:53:40 datashard: 10 parityshard: 3
2016/11/27 08:53:40 acknodelay: false
2016/11/27 08:53:40 dscp: 0
2016/11/27 08:53:40 sockbuf: 4194304
2016/11/27 08:53:40 keepalive: 10
2016/11/27 08:53:40 conn: 1
2016/11/27 08:53:40 autoexpire: 0
2016/11/27 08:53:40 redir: 
不动了， 这样是没成功吧，怎么看问题在哪呢
服务器是cent6 x64 
2016/11/28 01:42:43 version: 20161118
2016/11/28 01:42:43 listening on: [::]:38989
2016/11/28 01:42:43 target: 127.0.0.1:28989
2016/11/28 01:42:43 encryption: aes-128
2016/11/28 01:42:43 nodelay parameters: 0 20 2 1
2016/11/28 01:42:43 sndwnd: 1024 rcvwnd: 1024
2016/11/28 01:42:43 compression: false
2016/11/28 01:42:43 mtu: 1400
2016/11/28 01:42:43 datashard: 30 parityshard: 15
2016/11/28 01:42:43 acknodelay: false
2016/11/28 01:42:43 dscp: 46
2016/11/28 01:42:43 sockbuf: 4194304
2016/11/28 01:42:43 keepalive: 10
2016/11/28 01:42:46 remote address: x:64803
2016/11/28 01:42:51 remote address: x:48918
2016/11/28 01:43:16 broken pipe
2016/11/28 01:43:21 broken pipe

**Comment by liyiecho** [comment]
两端参数必须一致的有:

datashard --前向纠错
parityshard --前向纠错
nocomp --压缩
key --密钥
crypt --加密算法

**Comment by lxlw1320** [comment]
不好意思 之前改过忘记更新了，这几个是一致的
