### ISSUE TITLE
kcptun使用kcp的问题

### ISSUE THREAD

**Issue by lcax200000** [xtaci/kcptun#3]
kcp.ListenEncrypted 找不到？

**Comment by xtaci** [comment]
kcp-go更新了么？

**Comment by lcax200000** [comment]
最新版的八天前的

**Comment by xtaci** [comment]
kcp-go你需要更新，最新的才有ListenEncrypted

**Comment by lcax200000** [comment]
最新版的也没有。。。  有放到github吗

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/blob/master/sess.go#L382

**Comment by lcax200000** [comment]
噢  好吧可以了
