### ISSUE TITLE
multi conn crashing (probably?)

### ISSUE THREAD

**Issue by trivita** [xtaci/kcptun#30]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2444]

goroutine 248 [running]:
panic(0x243de0, 0xc8200100c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.handleClient(0x4c5b10, 0xc82002e000, 0x0, 0x0)
	/Users/trivita/mydev/src/github.com/xtaci/kcptun/client/main.go:28 +0x404
created by main.main.func1
	/Users/trivita/mydev/src/github.com/xtaci/kcptun/client/main.go:228 +0x2009

**Comment by trivita** [comment]
looks like if i have a large file to transfer, it crashes. (latest commit build)

**Comment by xtaci** [comment]
problem fixed.
