### ISSUE TITLE
请教一个rcvwnd sndwnd的问题

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#300]
如果server端sndwnd设置1024，client端rcvwnd设置256。
是否会造成server端按照1024发送数据，client端只按照256接收，导致大量数据浪费被丢弃？
还是client端window满了以后，server端就会等待client端？谢谢！

**Comment by xtaci** [comment]
不会

**Comment by bettermanbao** [comment]
谢谢
