### ISSUE TITLE
OPENWRT版本KCPTUN无法连接

### ISSUE THREAD

**Issue by terrytw** [xtaci/kcptun#302]
服务器端设置应该没有问题，用联通手机4G网络使用SS+KCP可以顺利连上，日志正常，有大量的STREAM OPEN, STREAM CLOSED

在家里装了OPENWRT版本（AR71XX,CHAOSCALMER 1501）（和服务器一样都是1118版本）的KCPTUN
（https://github.com/bettermanbao/openwrt-kcptun）
KCP设置和手机端一样，SS设置如下
![2](https://cloud.githubusercontent.com/assets/24227628/20673856/a741e608-b5c1-11e6-808c-3f6170a9db41.PNG)

但是无法连接

DNS解析是通过SS-TUNNEL直接从VPS进行UDP转发的，解析正常，国内网站都可以打开，外网的流量应该走SS的就全部都打不开
路由器系统信息如下：
![default](https://cloud.githubusercontent.com/assets/24227628/20672950/09dfc46e-b5be-11e6-8c42-fb5781b63283.PNG)

KCPTUN客户端就一行：
![3](https://cloud.githubusercontent.com/assets/24227628/20672998/40dd3b04-b5be-11e6-84fa-883f1172c9bc.PNG)

服务器端是这样的：
2016/11/28 22:37:05 remote address: XX.XX.XXX.X:45834
2016/11/28 22:37:39 stream opened
2016/11/28 22:38:35 broken pipe
2016/11/28 22:38:35 stream closed

请教一下，是怎么回事？不胜感激！
顺便一提家里是上海电信

**Comment by pigpigabc123** [comment]
kcptun不支持ss-tunnel的udp转发，所以dns解析不能用ss-tunel，改用pdnsd或者dnsforwarder等支持tcp  dns解析的转发器就行了

**Comment by bettermanbao** [comment]
***Compression function must be disabled by using --nocomp or "nocomp": true in config file.

**Comment by terrytw** [comment]
@pigpigabc123 我SS-TUNNEL是直接连VPS进行UDP转发的，没有通过KCPTUN转发，和SS-REDIR可以分开单独设置不影响

**Comment by terrytw** [comment]
@bettermanbao 十分感谢，现在好了
我误解了你的说明，以为你的意思是，如果要关闭压缩功能必须要按照你的方法来设置才能关闭
其实你的意思是用OPENWRT版本必须要关闭压缩功能
想想也是路由器的小CPU可能吃不消....
