### ISSUE TITLE
发现20161118版本1个conn可以下载多个文件了

### ISSUE THREAD

**Issue by fiercebead** [xtaci/kcptun#304]
以前的版本在默认1个conn的情况下是不能同时下载多个文件的，如果增加conn，服务端的上传会增加很多倍，而且本地的总下载速度还不如只下载1个文件的速度，完全是浪费，所以增加conn不是个好办法。
今天用了20161118版发现只用1个conn就可以同时下载多个文件，速度很好而且不浪费流量，真是太棒了，希望这个功能可以保持下去。

**Comment by xsharp** [comment]
这是 issue 么？

**Comment by fiercebead** [comment]
@xsharp I just want to know if the author realized this new feature.

**Comment by xtaci** [comment]
这个一直就有。 多conn不实用。

**Comment by fiercebead** [comment]
@xtaci 刚才我试了一下加速SSHTunnel，确实20161111版本也可以同时下载多个文件，我以前从没考虑SSHTunnel，因为一直用SS。
但是如果加速SS（shadowsocks-libev Linux服务端，交叉编译的Win客户端，shadowsocks-android连接局域网内的kcptun），20161111版本就不能同时下载多个文件，20161118版本就可以。
我觉得用SS的人应该不少，所以这应该是kcptun一个很大的进步呢。
