### ISSUE TITLE
感谢发布Support MIPS32版本！

### ISSUE THREAD

**Issue by colalan** [xtaci/kcptun#305]
刚更新了12月2日的Support MIPS32 with go1.8beta1版。
吓死宝宝了，看YB速度爆棚了，又一次回到了最初使用KCUTUN的感觉。
我是电信100M，在极路由1S上使用kcptun-linux-mipsle哦。太稳定了，都不敢相信这是真的。
![0](https://cloud.githubusercontent.com/assets/13914490/20836064/b1b5c22a-b8d8-11e6-80b2-9f78553995e5.JPG)

**Comment by xtaci** [comment]
golang从1.8开始官方支持mips32了，执行效率比之前非官方版本基于go1.4的快很多。 
@kuoruan @bettermanbao

**Comment by bettermanbao** [comment]
@colalan 配置文件发上来看看，这个进步也太大了吧

**Comment by colalan** [comment]
服务器：
{
    "crypt": "aes-128",
    "mode": "manual",
    "conn": 1,
    "autoexpire": 300,
    "mtu": 1400,
    "sndwnd": 128,
    "rcvwnd": 2048,
    "datashard": 30,
    "parityshard": 15,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}
路由：
-crypt aes-128 -mode manual -conn 1 -autoexpire 300 -mtu 1400 -sndwnd 128 -rcvwnd 256 -datashard 30 -parityshard 15 -dscp 46 -nocomp true -acknodelay false -nodelay 0 -interval 20 -resend 2 -nc 1 -sockbuf 4194304 -keepalive 10

**Comment by xtaci** [comment]
https://github.com/xtaci/notes/blob/master/golang/zsys_linux_mips.go
https://github.com/xtaci/notes/blob/master/golang/zsys_linux_mipsle.go

mips和mipsle的ipv4 补丁放到上面的地址了。

**Comment by bettermanbao** [comment]
@colalan 服务器端sndwnd 128，客户端rcvwnd 256。窗口开这么小，速度能这么快？fec还是30:15。请 @xtaci 解释下，我觉得应该是哪里写错了。

**Comment by xtaci** [comment]
速度是   窗口 ／ RTT决定的嘛。

**Comment by testcaoy7** [comment]
@xtaci 也就是说他的VPS延迟小，线路好

**Comment by bettermanbao** [comment]
26Mbps/8/128/1000=25ms，是这样算的吧？
这么小快的延时，肯定是国内的vps，线路条件这么好，还开kcptun。。。

**Comment by xtaci** [comment]
不能这么反推，需要考虑到丢包

**Comment by testcaoy7** [comment]
@bettermanbao 可能是阿里云香港，或者其他CN2线路的香港VPS

**Comment by choicky** [comment]
我的阿里云不用kcptun 就能上30 m
kcptun 只是用在备胎服务器上。

**Comment by wang20150419** [comment]
@xtaci 给大家科普一下呀，常见的 路由器CPU，其对应的 MIPS32 文件。

**Comment by bettermanbao** [comment]
国内90%的路由器不是mips就是mipsle，openwrt中的ar71xx对应mips，ramips对应mipsle。

**Comment by qwbht** [comment]
同样，谢谢作者。 为运营商增加%30出口宽带。。估计他们很开心~

**Comment by xtaci** [comment]
@qwbht 没那么夸张， 全中国都用上才会增加30%。

不用谢我，只是kcp协议的一个简单测试程序而已。

**Comment by qwbht** [comment]
@xtaci  对的，就是个简单测试程序。哈哈哈哈！！

**Comment by geerda123** [comment]
请问固件 用的是Padavan，还是orpenwrt

**Comment by colalan** [comment]
我把发的配置删除了，因为这个讨论起来真没有太大意义，配置因人而异的，没参考价值，同一配置不同的时间段和网络环境下结果也不同。现在的MIPS32版连续使用了2天，很稳定，但速度从昨天开始降下来了，可能电信QoS 作怪，不过缓仍很高。1080p仍秒开流畅。我不是技术控，网格访问体验好就满足了。
另外，因为我不对技术发烧，所以嘛，路由是渣渣的极1S，固件也是官方最新的，没刷第三方的。
![00](https://cloud.githubusercontent.com/assets/13914490/20864438/30f4a304-ba2c-11e6-8525-1d2d1d491dae.jpg)
![11](https://cloud.githubusercontent.com/assets/13914490/20864441/366ce4b8-ba2c-11e6-83c2-bd5371a5b754.jpg)

**Comment by fnscar** [comment]
唉？BWG的线路能跑这么快？

**Comment by fyhong** [comment]
@colalan 能否提供一下你这个SS插件。谢谢

**Comment by choicky** [comment]
最近搞了个斐讯k2路由器玩玩。
刷了华硕的Padavan，用了新出炉的 mips 版

目前觉得mips kcptun  与 网件 R6300 v2上的梅林kcptun差不多，包括速度与稳定性。

但速度比 @colalan 差很远……

**Comment by fnscar** [comment]
@choicky 可否分享一下参数设置？我这边MT7621跟BCM4709速度差不多，7620还是要慢不少。

**Comment by choicky** [comment]
@fnscar 网件R6300 v2 以及斐讯k2 上，我都没有做太多优化。

路由器性能不足，我的经验就是使用sasal20加密、关闭fec、关闭压缩，即：

    -crypt sasal20 -datashard 0 -parityshard 0 -nocomp

我是简单粗暴地使用 `-mode fast2`

据 https://github.com/xtaci/kcptun/issues/251 中 @dearneo  的反馈，`-interval ` 设置较大的值效果也不错，你可试试，要注意，`-mode manual` 的模式下才能设置`-interval `，且该模式下要设置 `-nodelay  -resend  -nc ` 这几个参数的指

**Comment by colalan** [comment]
@fyhong 因大部份代码来自 [stray.love](https://stray.love/) 。出于对博主的尊重，在其公开发布前，本人的修改版不提供分享。

**Comment by vivachencs** [comment]
@colalan 能否私下发下这个ss插件?

**Comment by lijijordan** [comment]
@choicky 
`-crypt sasal20 -datashard 0 -parityshard 0 -nocomp `
这个参数服务器也要设置成一样的么？

**Comment by choicky** [comment]
@lijijordan 这几个参数需要两端设置成一样
