### ISSUE TITLE
为什么我无法添加log到json？能不能开个群，大家一起写个详细教程

### ISSUE THREAD

**Issue by geerda123** [xtaci/kcptun#306]
1，我现在无法添加log到json。我看见有
"localaddr": "127.0.0.1:1080",
"remoteaddr": "SERVERIP:4000",
"log": "/var/log/kcptun.log"

"listen": ":4000",
"target": "127.0.0.1:1080",

这两种方式，我的是第二种。是不是这个原因导致无法添加？

2，能不能建个群，大家一起写个详细的教程。安装有现成的脚本，主要是优化那里，详细的步骤，要不然大家老是问，没有统一的执行标准，出了问题也不知道是哪个步骤。

**Comment by choicky** [comment]
现在的文档已经很详细了。

没有所谓的两种格式，只有服务器端与客户端，并且你要避免端口冲突。

印象中，没有哪个文档用1080端口距离的。

**Comment by geerda123** [comment]
这不是我的参数，是xtaci给出的两个配置单。

我不是通信工程的，有的查了也搞不清楚实际操作，现在issues问了太多基础的操作问题。干脆大家一起写个详细的流程操作，主要是优化那里的，比如加log，分析log数据的方法，iperf操作方法等。

现在的文档只能算个大纲，有很多细节，大部分人都不知道。通过很多人标准化构建的kcptun后，其反馈的结果能更好的完善kcptun。

**Comment by xtaci** [comment]
log 没有问题啊

 -log kcptun.log 就可以了，json是一样的

<img width="287" alt="256b9424-1c61-44b3-8c0a-21ebcc622d6c" src="https://cloud.githubusercontent.com/assets/2346725/20856290/9a85ea12-b946-11e6-91f4-0d563859d3df.png">

**Comment by geerda123** [comment]
sorry，直接copy，少了上一段代码的逗号。我再进一步的摸索，欢迎大家帮助，等我完全搞清楚了优化，我打算自己先写个详细的流程放在issues里，方便以后的小白先阅览

**Comment by geerda123** [comment]
![image](https://cloud.githubusercontent.com/assets/18500636/20856542/36bb4684-b94c-11e6-9a04-5947b0722be7.png)
是这样操作吗，log里面没有outsegs和insegs

**Comment by geerda123** [comment]
我开了一段时间的youtube，和网页。得到了下面的结果。请问怎么详细的优化，我下面的参数是参照别人的，我看了文档还是不够详细
2016/12/02 23:56:48 KCP SNMP:&{BytesSent:935685586 BytesReceived:1367129 MaxConn:1 ActiveOpens:0 PassiveOpens:2 CurrEstab:1 InErrs:0 InCsumErrors:285 KCPInErrors:0 InSegs:36230 OutSegs:873436 InBytes:5384628 OutBytes:1114313367 RetransSegs:108308 FastRetransSegs:0 EarlyRetransSegs:32770 LostSegs:75538 RepeatSegs:110 FECRecovered:0 FECErrs:0 FECSegs:0}
![image](https://cloud.githubusercontent.com/assets/18500636/20856933/72ce2f7c-b958-11e6-8719-a581524557bd.png)
![image](https://cloud.githubusercontent.com/assets/18500636/20856936/8f740e3a-b958-11e6-971b-a002e15b03a0.png)
