### ISSUE TITLE
电信 搬瓦工 kcptun频繁掉线或者连不上

### ISSUE THREAD

**Issue by factoid0** [xtaci/kcptun#307]
已参考过#218楼，及其他楼层。mtu以及提到的三中方案无效。仍然出现频繁连接不上或者掉线的情况基本用不了。
希望大家帮忙看看，谢谢

这是服务器端参数    {
    "listen": ":2333",
    "target": "127.0.0.1:1024",
    "key": "test",
    "crypt": "salsa20",
    "mode": "manual",
    "mtu": 512,
    "sndwnd": 218,
    "rcvwnd": 512,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 1,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10,
    "log": "/root/kcptun/kcptun.log"
    }

**Comment by geerda123** [comment]
客户端呢

**Comment by factoid0** [comment]
--key test --crypt salsa20 --mode manual --mtu 512 --autoexpire 10
不好意思。这是客户端的参数

**Comment by geerda123** [comment]
客户端这些都没有啊
"datashard": 70,
"parityshard": 30,

**Comment by factoid0** [comment]
不是这个原因，之前我全部参数都写上了，能连接上，但是得碰机会，不是每次都连上

**Comment by cjjdaq** [comment]
你是不是上海国际出口

**Comment by geerda123** [comment]
不是，上海要买国际服务包

2016-12-05 0:18 GMT+08:00 cjjdaq <notifications@github.com>:
