### ISSUE TITLE
路由器 wndr4300( cpu ar71xx )运行出错

### ISSUE THREAD

**Issue by wang20150419** [xtaci/kcptun#308]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

最新版(v20161202)，使用 client_linux_mipsle 在路由器上执行，提示：

./client_linux_mipsle: line 1: syntax error: unexpected "("

**Comment by xtaci** [comment]
mipsle 不行就换mips ， mips不行就换mipsle

**Comment by bettermanbao** [comment]
ar71xx用mips

**Comment by wang20150419** [comment]
mipsle 的错误：-ash: ./client_linux_mips: Text file busy

**Comment by wang20150419** [comment]
@bettermanbao  针对openwrt 编译的 可用，但偶尔会自动退出。

**Comment by terrytw** [comment]
mips版的确好像有问题
我这边是illegal instruction

**Comment by xtaci** [comment]
嗯，目前不清楚原因， mips有点复杂。

**Comment by bettermanbao** [comment]
mipsle的测试正常运行，mips的没试过

**Comment by terrytw** [comment]
之前瞎折腾的时候好像有提示错误在第130行左右
（一次提示129一次好像是132）

**Comment by rawrence** [comment]
可以试试这个[client_linux_mips.zip](https://github.com/xtaci/kcptun/files/633041/client_linux_mips.zip)
没有相关硬件，没法测试。

**Comment by terrytw** [comment]
@rawrence 
还是ERROR CODE 132

**Comment by rawrence** [comment]
cat /proc/cpuinfo 
看看是什么 @terrytw

**Comment by terrytw** [comment]
[img]http://i.imgur.com/zOnRgbk.png[/img]

**Comment by rawrence** [comment]
和mt7620 SoC 还有点不一样,mips 感觉好混乱,下图是我的cpuinfo
![image](https://cloud.githubusercontent.com/assets/196507/20921513/70d43a3e-bbdf-11e6-81cc-54a5f0431cfa.png)

**Comment by terrytw** [comment]
@rawrence 是啊
从几个不多的反馈来看mips的都报错，mipsle的似乎都可以用

**Comment by rawrence** [comment]
https://build.golang.org/?branch=master 从这里看,貌似mips坏了很久了,mipsle 基本一直ok

**Comment by rawrence** [comment]
可以找 @bettermanbao 用c帮你编译一下.

**Comment by bettermanbao** [comment]
试试这里的 https://github.com/bettermanbao/openwrt-kcptun/releases
我在ar9341的路由上用过，没有问题。

**Comment by terrytw** [comment]
现在用的就是这个版本
运行良好

**Comment by 333zbj** [comment]
@bettermanbao 你编译的1118版本可以在路由器上跑，但一连接就挂掉怎么回事？使用1111不会挂掉，但不起作用。有空按照最新1222的编译一版呗
