### ISSUE TITLE
PSG1208 openwrt chaos calmer 15.05.1 运行出错

### ISSUE THREAD

**Issue by Biercenter** [xtaci/kcptun#309]
无论是mips还是mipsle都显示错误，无法运行。
但是 bettermanbao 的 20161118版[https://github.com/bettermanbao/openwrt-kcptun/releases/download/v20161118/kcptun-openwrt-ramips-20161118.tar.gz](url)
能运行。
![default](https://cloud.githubusercontent.com/assets/11498308/20856850/e12665fa-b955-11e6-88b1-6e13d18e4b48.PNG)

**Comment by Biercenter** [comment]
root@OpenWrt:~# cat /proc/cpuinfo
system type             : MediaTek MT7620A ver:2 eco:6
machine                 : Phicomm PSG1208
processor               : 0
cpu model               : MIPS 24KEc V5.0
BogoMIPS                : 385.84
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by bettermanbao** [comment]
1202版的mipsle在psg1218上正常运行。

**Comment by tianlichunhong** [comment]
在psg1218上能运行？我在上面运行了，没开压缩能运行几分钟，然后就被路由器杀死了。而且根本没有效果。你们的效果如何？

**Comment by bettermanbao** [comment]
关压缩，关FEC后，效果显著！
