### ISSUE TITLE
kcptun的应用场景

### ISSUE THREAD

**Issue by flyer5200** [xtaci/kcptun#31]
大神你好, 我看了kcptun 的issues大家的讨论, 貌似kcptun是用来做点对点tcp通信加速的?
不知道kcptun能否像shadowsock这样做proxy?

**Comment by xtaci** [comment]
不能，但是貌似有网友把kcptun server转发到3proxy，然后把浏览器proxy到本地的kcptun client 端口就完成了。

https://blog.kuoruan.com/103.html

**Comment by riobard** [comment]
用 kcptun 加速 ssh 然后直接用 ssh 的 SOCKS 代理即可，都不需要装额外的软件。

**Comment by yaleh** [comment]
SSH tunnel 性能应该比 SS 差一些

**Comment by riobard** [comment]
@yaleh benchmark?

**Comment by yaleh** [comment]
SSH 只有一个 TCP 连接，SS 有多个。出现丢包时 SSH tunnel 会全堵住。
