### ISSUE TITLE
请问如何修改server_windows的配置？

### ISSUE THREAD

**Issue by soundghost** [xtaci/kcptun#311]
直接双击server_windows_amd64就出现小黑窗了，如果我希望修改端口、加密方式等信息，是否有配置文件可修改？或者有别的方法呢？

谢谢！

**Comment by lizongzeshunshun** [comment]
cmd运行
先cd到目录然后server_windows_amd64 -h

**Comment by soundghost** [comment]
非常感谢，我输入了个错误的命令后帮助信息就出来了。
然后今天下午找了两个联通Client做测试，一个32位Win7，一个64位Win7。服务器电信网络，分别运行32位和64位的Server程序。
测试成功！
受测试的人员都反映说感觉明显快多了。
我现在让他们每天继续反馈给我使用情况，我想知道高峰期的效果如何。
感谢作者！
感谢lizongzeshunshun的回复！
