### ISSUE TITLE
路由参数无法保存到client_linux_mips上，华硕Padavan。client为1202版

### ISSUE THREAD

**Issue by geerda123** [xtaci/kcptun#312]
现在出现了个奇怪的问题。在路由中设置的kcptun参数，无法保存到client_linux_mips。

运行client_linux_mips，结果如下图。完全不是我的参数。已经给了777权限
![image](https://cloud.githubusercontent.com/assets/18500636/20864779/6f539ca8-ba37-11e6-88a0-7ef0b81b87e8.png)

**Comment by geerda123** [comment]
![image](https://cloud.githubusercontent.com/assets/18500636/20864784/acd40a7c-ba37-11e6-9231-0470836577c9.png)

**Comment by geerda123** [comment]
![image](https://cloud.githubusercontent.com/assets/18500636/20864896/faff0814-ba3c-11e6-982f-b2b486db92b4.png)

**Comment by geerda123** [comment]
我知道了，路由的kcptun密码不是it's a secrect. 而是你的shadowsocks密码

**Comment by YangYunLong** [comment]
@geerda123  我的填写shadowsocks密码 也不行，难道跟加密方式none 有关？？ 还有能给个详细的教程吗？

**Comment by geerda123** [comment]
你多点几次kcptun的重启，固件有些问题。[image: 内嵌图片 1][image: 内嵌图片 2]

2016-12-06 9:54 GMT+08:00 yangyunlong <notifications@github.com>:
