### ISSUE TITLE
连接不上，没有 stream opened 信息

### ISSUE THREAD

**Issue by NikoTung** [xtaci/kcptun#313]
服务器 Centos 6 x86_64 ，用的是搬瓦工一键安装版的ss，监听端口:9043。

kcptun 参数:

服务端

    ./server_linux_amd64 -l ":29900" -t "127.0.0.1:9043" --key "test" --crypt aes-128

客户端

    ./client_darwin_amd64 -l ":8016" -r "serverip:29900" --key "test" --crypt aes-128

在服务器端，telnet 127.0.0.1 9043 可以连上

ss直连可以连上，ss 客户端用的是 GoAgentX,本地端口 8016

版本：20161118

状况:

服务端和客户端启动后，在服务端只有这样的一个log `remote address: 113.87.242.208:55361`,两边均无 stream opened 日志。

网络用的是电信的 20M。

看wiki 说是 *连接客户端程序的端口设置错误。*。我试了9043 和 8016两个端口，都是一样只有 `remote address:xxx.xxx.xxx.xx` 的log。不知道是啥原因呢？

**Comment by NikoTung** [comment]
客户端配置错了

**Comment by Jasonjunsu** [comment]
看不出来你这个怎么错误了？在client端，你先启动的是kcptun 还是SS？
