### ISSUE TITLE
路由器打开客户端，服务器无法连接

### ISSUE THREAD

**Issue by 0njzy0** [xtaci/kcptun#314]
电脑打开客户端连接可以，也能成功翻墙。路由器一打开客户端，不仅不能翻墙，服务器也无法连接。
这是路由器上的日志：
2016/12/04 15:38:30 main.go:299: sndwnd: 128 rcvwnd: 256
2016/12/04 15:38:30 main.go:300: compression: false
2016/12/04 15:38:30 main.go:301: mtu: 1350
2016/12/04 15:38:30 main.go:302: datashard: 10 parityshard: 3
2016/12/04 15:38:30 main.go:303: acknodelay: false
2016/12/04 15:38:30 main.go:304: dscp: 46
2016/12/04 15:38:30 main.go:305: sockbuf: 4194304
2016/12/04 15:38:30 main.go:306: keepalive: 10
2016/12/04 15:38:30 main.go:307: conn: 1
2016/12/04 15:38:30 main.go:308: autoexpire: 60
2016/12/04 15:39:00 main.go:57: stream opened
2016/12/04 15:39:00 main.go:74: stream closed
2016/12/04 15:39:04 main.go:57: stream opened
2016/12/04 15:39:09 main.go:57: stream opened
2016/12/04 15:39:30 main.go:431: session scavenged
2016/12/04 15:39:34 main.go:74: stream closed

**Comment by alex43211** [comment]
路由器上的配置正确么
