### ISSUE TITLE
难道你们在路由器上都运行正常吗？

### ISSUE THREAD

**Issue by Biercenter** [xtaci/kcptun#316]
为什么我在菲讯K1上无法运行
一直都是显示Illegal instruction

Before firing issue, make sure you figured out the following common questions.
PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

**Comment by bettermanbao** [comment]
斐讯K2正常使用

**Comment by YangYunLong** [comment]
@bettermanbao  为什么我的newifi 刷了潘多拉固件参数填了 一直连不上？

**Comment by YangYunLong** [comment]
@bettermanbao  求详细教程

**Comment by bettermanbao** [comment]
检查kcptun参数，我的k2和newifi也是刷的潘多拉，一切正常。

**Comment by smdhz** [comment]
树莓派3，毫无压力

**Comment by icymind** [comment]
@bettermanbao cpu/ 内存使用率等情况如何

**Comment by bettermanbao** [comment]
关FEC后，64M内存剩余8M左右，CPU 70%左右，速度5-6Mbps。

**Comment by dearneo** [comment]
刚在小米路由一代硬盘版弄好，懒得折腾第三方固件，直接用的官方开发版固件开ssh，居然能用！关压缩，关fec，salsa20 加密 ，cpu使用率<20%，内存占用约12M，速度约5Mbps 

Cpu(s):  8.6%us,  4.0%sy,  0.0%ni, 82.9%id,  0.0%wa,  0.0%hi,  4.5%si,  0.0%st
Mem:    255164k total,   134176k used,   120988k free,     6700k buffers
Swap:   262140k total,        0k used,   262140k free,    52604k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
10508 root      20   0  774m  10m 1712 S    15        4.4   2:49.72 client_linux_ar

**Comment by icymind** [comment]
@dearneo 其实服务器更新内核换bbr拥塞算法, 我这里纯粹 ss 速度也能达到5Mbps+, 峰值甚至有8Mbps

**Comment by bettermanbao** [comment]
bbr算法不支持openvz是硬伤。
