### ISSUE TITLE
161202版的mipsle binary没有用upx压缩

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#317]
刚才简单测试了一下，运行没有问题。
同go 1.43版相比，cpu使用率似乎有所下降，内存使用率似乎有所上升。

改天详细测试下，以上结论可能不准确。

**Comment by xtaci** [comment]
upx后来的版本都没有用，有些杀软会误报病毒

**Comment by bettermanbao** [comment]
upx压缩对mips平台非常重要，因为通常路由器可以用来装软件的空间也就1-2M，kcptun不压缩超过3M。捉襟见肘啊。其实杀软也就是windows下的杀软才会误报吧，能否只禁用win版的px？谢谢！

**Comment by bettermanbao** [comment]
@xtaci 看到build-release.sh对mips和mipsle有启用UPX压缩，但是release里文件下载下来看到是没有压缩了，还是3M多。请帮忙检查下哪里出了问题，谢谢！

**Comment by xtaci** [comment]
没有压缩的，已经放弃了。

**Comment by xtaci** [comment]
二进制压缩还是交给用户吧。

**Comment by bettermanbao** [comment]
build-release.sh中有看到UPX呢，怎么放弃了？

#MIPS32LE
env CGO_ENABLED=0 GOOS=linux GOARCH=mipsle go build -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o client_linux_mipsle github.com/xtaci/kcptun/client
env CGO_ENABLED=0 GOOS=linux GOARCH=mipsle go build -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o server_linux_mipsle github.com/xtaci/kcptun/server
env CGO_ENABLED=0 GOOS=linux GOARCH=mips go build -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o client_linux_mips github.com/xtaci/kcptun/client
env CGO_ENABLED=0 GOOS=linux GOARCH=mips go build -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o server_linux_mips github.com/xtaci/kcptun/server

if $UPX; then upx -9 client_linux_mips* server_linux_mips*;fi
tar -zcf kcptun-linux-mipsle-$VERSION.tar.gz client_linux_mipsle server_linux_mipsle
tar -zcf kcptun-linux-mips-$VERSION.tar.gz client_linux_mips server_linux_mips
$MD5 kcptun-linux-mipsle-$VERSION.tar.gz
$MD5 kcptun-linux-mips-$VERSION.tar.gz

**Comment by xtaci** [comment]
就是杀软的问题。会照成很多误解。

**Comment by rampageX** [comment]
freeUPX [http://www.pazera-software.com/products/free-upx/](url) 下载后自己去处理下就OK了。
