### ISSUE TITLE
如何在树莓派上安装客户端？

### ISSUE THREAD

**Issue by polinzhuo** [xtaci/kcptun#319]
RT

**Comment by lizongzeshunshun** [comment]
release的arm版

**Comment by wang20150419** [comment]
用 kcptun-linux-arm-20161202.tar.gz 中的 client_linux_arm7

**Comment by fankangsong** [comment]
uname -a 看下你是第几代的树莓派

**Comment by boatmac** [comment]
树莓派3用client_linux_arm7无问题，只是CPU占用略高，50%左右。

**Comment by alex43211** [comment]
@boatmac 树莓派3的哪个版本系统？原本的树莓派系统么？

**Comment by boatmac** [comment]
@alex43211 是的，Raspbian。

**Comment by whour** [comment]
@boatmac  怎么会那么高呢，我的ArchlinuxARM的，最新的 client_linux_arm7 内存和CPU的占用并不高。

**Comment by boatmac** [comment]
@whour 一直没具体研究什么原因，但并不是一直都很高，但时间长了就会很高，甚至超过90%。

**Comment by whour** [comment]
@boatmac  Pi3 本来CPU本来就会突发高，运行htop的CPU瞬时90%+ 
跑YTB的4K视频4颗CPU占用率平均在60% 
内存占用的少。
我铝制的散热片散热不行，CPU高不怕，就怕温度高。

**Comment by smdhz** [comment]
Pi3+铜散热片
给PS4当代理服务器毫无压力
