### ISSUE TITLE
Milestone [STREAM_ARQ] Discussion!

### ISSUE THREAD

**Issue by xtaci** [xtaci/kcptun#32]
Single connection ARQ will lead to HOL Blocking problem.
https://en.wikipedia.org/wiki/Head-of-line_blocking
[QUIC](https://www.chromium.org/quic) solved this problem by stream based ARQ, not connection based.   

>Multiplexing

>HTTP/2 on TCP suffers from head-of-line blocking in TCP. Since HTTP/2 multiplexes many streams atop TCP's single-bytestream abstraction, a loss of a TCP segment results in blocking of all subsequent segments until a retransmission arrives, irrespective of the HTTP/2 stream that is encapsulated in subsequent segments.

>Because QUIC is designed from the ground up for multiplexed operation, lost packets carrying data for an individual stream generally only impact that specific stream. Each stream frame can be immediately dispatched to that stream on arrival, so streams without loss can continue to be reassembled and make forward progress in the application.

>Caveat: QUIC currently compresses HTTP headers via HTTP/2 HPACK header compression on a dedicated header stream(3), which imposes head-of-line blocking for header frames only.

**Comment by trivita** [comment]
so what do you think

**Comment by xtaci** [comment]
learning QUIC, possible improvements by:
1. TCP Tail Loss Probe
2. Stream ARA & Connection Window
3. Proportional Rate Reduction

**Comment by trivita** [comment]
i knew you're going to implement QUIC someday hihihi.
nice move man but still that's a lot to take in.

**Comment by xtaci** [comment]
oui, it's complexer & harder than i previously thought.

**Comment by jannson** [comment]
几天太忙，来观摩大神。这个确实是好东西！

**Comment by xtaci** [comment]
很难，先学习

**Comment by kuoruan** [comment]
大神，release的时候能不能同时写上中文啊，英语渣。

**Comment by xtaci** [comment]
@kuoruan 明天补上 :smile:

**Comment by xtaci** [comment]
@kuoruan 中文已添加

**Comment by kuoruan** [comment]
@trivita 感谢

**Comment by xtaci** [comment]
@kuoruan 0627更新，中文也加了

**Comment by monkeyyeyy** [comment]
大神，我的VPS是IPV6的，本地也是IPV6的，我尝试了下，貌似不支持IPV6啊。
另外还有一个问题，如果我的SS是多用户，服务器端的start.sh怎么写才能同时加速多个端口呢？

**Comment by xtaci** [comment]
@monkeyyeyy 肯定是支持ipv6的，没有做任何限制，只要你输入的地址是ipv6的。
只能加速一个端口，多端口需要启动多对client/server

**Comment by xtaci** [comment]
@monkeyyeyy 
https://golang.org/src/net/dial.go?s=5682:5730#L181
```
Dial("tcp", "[2001:db8::1]:http")
Dial("tcp", "[fe80::1%lo0]:80")
Dial("tcp", ":80")
```

**Comment by AllenChow** [comment]
mac系统下能用吗？

**Comment by xtaci** [comment]
@AllenChow 当然能啊， release下面有darwin版

**Comment by AllenChow** [comment]
@xtaci 感谢，在windows下和mac下都部署了一下，成功运行，效果不错！

**Comment by kmahyyg** [comment]
@xtaci 回报一些问题：
网络及软件环境： Chrome53+shadowsocks-libev latest  Win7  云南电信
VPS： Bandwagonhost Los Angeles

1. 100Mbps专线下加速效果良好，速度不错。
2. 然而遇到QoS一多的长宽20Mbps就不行了，瞬时加速效果有极端明显，但是连接极其不稳定，基本ytb提速1x，但是连接最多就是连接1s中断1s的节奏，很糟糕。请求建议！
3. 同等网络下Japan Sakura的NTT线路ytb稳定1900kbps+

-sndwnd 1792 -rcvwnd 1792 -mtu 1350 --key "" -dscp 46

**Comment by xtaci** [comment]
对于长宽这种没有任何办法，你只能再通过一台国内服务器做中转。
