### ISSUE TITLE
断流时Client这边连“stream opened”都没打印？

### ISSUE THREAD

**Issue by bash99** [xtaci/kcptun#321]
20161202版本
手动模式，参数如下
--autoexpire 360 --key killfbx --crypt aes --mode manual -sndwnd 8 -rcvwnd 80 --nodelay 1 --interval 20 --resend 2 --nc 1 --mtu 1350 --datashard 85 --parityshard 15 --dscp 0

开始是随机0.5～2个小时后断流，手动重启恢复正常，然后尝试加autoexpire参数，似乎效果不明显。开着log的话，会发现客户端尝试链接时，client连 stream opened都没打印。strace -f -p 只能看见无数的select timeout。仍然是杀掉进程重启正常。

这个是网络问题还是软件问题？

**Comment by xtaci** [comment]
是bug

**Comment by xtaci** [comment]
断流的时候， SYN包都发不出去，就不会有stream open

**Comment by xtaci** [comment]
这个问题我应该会处理

**Comment by bash99** [comment]
回退到某个版本有望正常吗？总之一重启就好给我感觉是可修复的。

**Comment by bash99** [comment]
改mtu到512基本上无效，暂时加了一个25分钟自动重启的脚本

**Comment by xtaci** [comment]
是 keepalive在完全断流情况下，并没有起到重新建立连接的作用。 

已经fix，我会发一个pre-release做测试

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20161207  可以试下这个pre-release对 keepalive的效果。

**Comment by bash99** [comment]
好像解决问题了，多谢

**Comment by bash99** [comment]
第二天早上来，最开始两分钟还是断，但是能看见第一个stream opened，几分钟之后就好了; 算正常现象吗？

**Comment by xtaci** [comment]
正常

**Comment by bash99** [comment]
另外，转发socks时碰上断流和cow配合不好？我试图尝试这种模式，两个kcptun + dante 连两个不同的vps，一个cow跑hash，上级代理设成sock5://localhost:port/ 。
碰上断流的时候，cow似乎无法判断远程出错了，因为可以连上而没有明显的timeout，但是拿不到数据。

虽然同时另外一个kcptun是正常的，但是却无法切换。

这个是修改cow的侦测算法合适还是 kcptun可以在断流时关闭链接？

**Comment by xtaci** [comment]
不知道cow是什么

**Comment by bash99** [comment]
@xtaci https://github.com/cyfdecyf/cow/ 自动socks5转http的代理，支持多个upstream，原生支持ss协议。
