### ISSUE TITLE
客户端和服务器端皆无 stream opened信息。

### ISSUE THREAD

**Issue by Jasonjunsu** [xtaci/kcptun#322]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.

YES
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
YES

“2016/12/09 02:02:52 compression: true
2016/12/09 02:02:52 mtu: 1400
2016/12/09 02:02:52 datashard: 10 parityshard: 3”

3. Did you correctly set the ***-target*** on the server side?

YES  

4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).

can't connect successfully

[root kcptun]# telnet 127.0.0.1:443
telnet: 127.0.0.1:443: Name or service not known
127.0.0.1:443: Unknown host
Exit code: 1

5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)

[root kcptun]# sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

sorry, I don't know how to confirm the ISP Cable-Modem

6. Are you using the **same version** for both client & server
yes

7. Are you using the **latest release**?
maybe no --- 20161118
8. Which **OS** do you use?

server--centos6 / x86  client ubuntu14.04/ x64
9. Which end for this issue related to, **client or server**?
    both sides

-------------------------------------------------------------------------------------------------------------------------
#server side  CentOS release 6.8 (Final) x86

./server_linux_386 -l "my_vps_ip:23333" -t "127.0.0.1:443" --key secret --crypt aes  --mtu 1400 --sndwnd 2048 --rcvwnd 2048 --mode fast2 > kcptun.log 2>&1 &

#cliend side---ubuntu14.04  x86_64

./client_linux_amd64 -l "127.0.0.1:12948"  -r "my_vps_ip:23333"  --key secret --crypt aes --mtu 1400 --sndwnd 128 --rcvwnd 1024 --mode fast2 --dscp 46 > kcptun.log 2>&1

电信50M光纤

版本都是version: 20161118

server端和client端都无法出现 stream opened信息
server端能多打印的是一条client连接日志；
2016/12/08 13:03:01 remote address: **********（客户端IP）

**Comment by hegq1985** [comment]
菜鸟路过，请求大神们帮助，多谢！

**Comment by NikoTung** [comment]
你本地的ss 的连接地址是不是 127.0.0.1:12948？

**Comment by hegq1985** [comment]
不是，client本地设置的ss监听端口是1080。kcptun和ss不能设置同一个端口吧？要不然提示说绑定端口已经被占用，启动失败。

**Comment by liyiecho** [comment]
新建一个SS配置，让SS监听kcptun的本地地址（也就是你写的127.0.0.1:12948），密码加密什么的你随意填写

**Comment by Jasonjunsu** [comment]
@NikoTung @liyiecho  多谢两位前辈的支持！ 一语惊醒梦中人！我从其他网站上看的手册，只顾了Kcptun的设置，就没想这其中的原理，我SS server 还填写的是VPS 的地址，真的是可笑！ 现在才知道kcptun 原理图是什么意思了！多谢！
