### ISSUE TITLE
讨论一下断流的时候现象，分析原因

### ISSUE THREAD

**Issue by hoky** [xtaci/kcptun#323]
我这里是电信，正常的时候Youtube Auto 1080P，但是间歇性断流。

断流的时候客户端 nc 服务器 udp相应端口，succeeded。

但是在服务器上用tcpdump获取不到数据。包括nc的数据。

问题出在哪里？请问怎么进一步用其他方法判断问题出在哪里？

----
另外我两台电脑，一台断流后可自己恢复，另一台不行。config文件两台电脑是同步的。重新开客户端恢复正常。

2016-12-11更新

出问题的时候，我的Android手机用流量连服务器，可以正常使用。说明服务器市正常的。

关键是手机连成功后，马上WiFi电脑端也马上恢复正常了。这是怎么回事？

**Comment by cjjdaq** [comment]
你客户端udp发送不出去。我这里也是这样。

**Comment by wang20150419** [comment]
我碰到过的一种怪异情况，使用 chinadns 做DNS 防污染，就会导致 用 kcptun  加速softether 后的 udp 通不过。停用 chinadns 就OK了。

**Comment by hoky** [comment]
@cjjdaq  发送不出去为什么会得到succeeded的结果呢？

**Comment by CuminLo** [comment]
我用的是长城，情况跟你差不多的。
尝试了很多参数都不行，我观察了一段时间，发现一般而言看YTB10分钟左右会断开一分钟左右，而且一分钟后还不一定能恢复（大部分是可以恢复）。
我现在将过期时间调的比较低，但是也没什么效果。所以很多时候我都是手动重启。。。

**Comment by wkingfly** [comment]
这个目前还是无解么

Cumin Lo <notifications@github.com>于2016年12月12日周一 上午10:04写道：

**Comment by CuminLo** [comment]
@wkingfly 目前我还没找到方法

**Comment by cjjdaq** [comment]
没断之前用nc进行udp链接，等到kcptun断掉的时候发现，从我adsl（client）发送的信息，vps上（server）接收不到，但从vps（nc server端）上nc发送信息，我的adsl（client）端可以接收到。

**Comment by bash99** [comment]
#321 里面prerelease的相对缓解了断流，但是重启仍然更加有效。

**Comment by hoky** [comment]
@bash99 每次更新好麻烦，我还需要重新做Docker。

**Comment by yuexia12** [comment]
如果是长宽的话有个优势，因为不是独享ip地址，所以如果udp被封的时候（在服务端完全看不到kcptun日志有访问更新)，在客户端重启路由器会得到长宽重新动态分配的一个ip地址，再试就行了。
可以在服务器端用tcpdump看客户端连过来的ip地址（还用客户端开个ssh到服务端的访问连接）。可以看到在ip地址更换的同时，udp流量就嗖嗖的进来了。。。 💃

**Comment by linhua55** [comment]
https://github.com/xtaci/kcptun/issues/228#issuecomment-268204440
