### ISSUE TITLE
ubuntu 12.04 服务端启动失败

### ISSUE THREAD

**Issue by s1204** [xtaci/kcptun#324]
系统是Ubuntu12.04 x86-64   ，搭建了ss，执行配置文件.json正常，开机启动无问题
之后下载了kcptun，因为是第二台vps，所以轻车熟路，按上一台操作(上一台是centos)
到了开机启动的时候发现进程中没有server_linux_amd64
Ps: 使用大众脚本，命名start.sh
#!/bin/bash
cd /root/kcptun/
./server_linux_amd64 -c /root/kcptun/server-config.json 2>&1 &
echo "Kcptun started."
执行后……最后的Kcptun started.是显示了，但是进程中查不到
后来在kcptun路径下尝试了  sh  、bash、./start.sh  进程中还是看不到
手动执行  ./server_linux_amd64 -c /root/kcptun/server-config.json 无任何反馈，进程同样没有
 单执行./server_linux_amd64 后进程中就可以看到server_linux_amd64了
套用作者给的快速方式，显示结果如下
root@localhost:~/kcptun# ./server_linux_amd64 -t "127.0.0.1:554" -l ":6001" -mode fast2
2016/12/10 08:05:15 version: 20161207
2016/12/10 08:05:15 listen udp :6001: bind: address already in use
net.ListenUDP
github.com/xtaci/kcp-go.ListenWithOptions
        /Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:856
main.main.func1
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:311
github.com/urfave/cli.HandleAction
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483
github.com/urfave/cli.(*App).Run
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254
main.main
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:355
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2184

所以我就有点懵逼了，翻了很多的教程，也没有发现问题在哪里？
进程就是没有server_linux_amd64
我一直手动搭，没有用过一键脚本

**Comment by lizongzeshunshun** [comment]
**bind: address already in use**

端口已经被占用

**Comment by s1204** [comment]
抱歉，之前改过配置文件，忘记了，还是不够仔细啊
