### ISSUE TITLE
help里面咋没有keepalive呢

### ISSUE THREAD

**Issue by kxmp** [xtaci/kcptun#325]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
Yes
7. Are you using the **latest release**?
v20161202
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

我看了下help 一看没这东西 还以为这个没法设置呢. 我还以为他就是10 没法改...
结果加了下参数 又发现可以用...

**Comment by xtaci** [comment]
用来给路由器的nat表保证不删除的。
