### ISSUE TITLE
断网重连或切换网络后，必须重启客户端服务

### ISSUE THREAD

**Issue by Dukewill** [xtaci/kcptun#326]
amd64 版本客户端，在 win10 上配合 SS 客户端使用。因为网络状况不好和工作需要，需要时不时切换网络（电信和移动）或者重连网络，这时 kcptun 就会断开，必须重启客户端服务才能重建连接。

目前客户端配置如下：
client_windows_amd64.exe -l :12948 -r xxx.xxx.xxx.xxx:29900 -autoexpire 300 -nocomp -mtu 512 -sndwnd 5 -rcvwnd 256 -key ******** -mode fast -dscp 46

请教一下是什么问题，不知道描述是否残缺。
不甚感谢。

**Comment by xtaci** [comment]
要稍等一会儿才能检测到
