### ISSUE TITLE
弱弱的问下windows下的client要怎么配置？客户端服务器都有stream opened，但就是无法通信

### ISSUE THREAD

**Issue by jyanchen** [xtaci/kcptun#327]
**我安卓手机上是可以成功使用kcptun的**
**我的linux系统和windows系统都是，客户端服务器都有stream opened，但就是无法通信**

官方的故障排除：
>Q: 客户端服务器皆有 stream opened信息，但无法通信。
>A: 上层软件的设定错误。

所有的设定我都检查过，最后客户端服务器都有stream opened，但就是无法通信。

#我有些疑问
1. windows kcptun client端是需要同时设置kcptun和ss吗？
2. 如果要同时设置ss，windows kcptun client端的```--localaddr```和ss的代理端口是要一致吗？（如果要一致，端口肯定会冲突的）

#系统环境和配置简要
1. windows 10
2. 防火墙配置udp设置
3. telnet没问题
4. server端和client端的版本都是20161207
5. server端和client端的配置需要一致的都是一致的

```
# windows client
./client_windows_amd64.exe -l ":1080" -r “ssServerIP:29900” -key "it's a secrect" -mode “fast” -crypt “salsa20” -autoexpire 10
```

```
# centos 6 server
{
    "listen": ":29900",
    "target": "127.0.0.1:5800",
    "key": "it's a secrect",
    "crypt": "salsa20",
    "mode": "fast",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}
```

**Comment by whour** [comment]
kcp是外层，你kcptun client连接上后，ss服务器使用kcptun的本地监听端口，其他内容不变，相当于吧ss的报文通过kcp换成了udp包，只靠kcptun是无法直接通讯的。

**Comment by jyanchen** [comment]
@whour ss服务器？指的是ss客户端？

那是这样设置吗？
```
# ss client
服务器IP： ssServerIP
服务器端口：5800
...
代理端口：1080
```

```
# kcptun client
# -l 参数，应该指的是，你说的‘kcptun的本地监听端口’
./client_windows_amd64.exe -l ":1080" -r “ssServerIP:29900” -key "it's a secrect" -mode “fast” -crypt “salsa20” -autoexpire 10
```

那这样的话，会提示端口被占用啊

还是，我要改ss server端吗？可是我安卓上是可以成功使用kcptun，那证明我的ss server配置没错吧？

**Comment by lizongzeshunshun** [comment]
kcptun是用来转发ss的数据的
比如你这个配置，服务器的ss应该监听在0.0.0.0:5800(或者127.0.0.1:5800)
你的kcptun客户端的-l参数是1080，那么ss的服务器应该是127.0.0.1:1080

**Comment by jyanchen** [comment]
谢谢！！！
谢谢指点，原来我一直把kcptun和ss分开配置了。。。
