### ISSUE TITLE
联想newifi y1(MT7620A)无法运行mips版及mipsle版本

### ISSUE THREAD

**Issue by jxr111** [xtaci/kcptun#328]
如题，联想newifi y1（openwrt 15.05.1） 同样的配置运行bettermanbao兄的1118版正常，运行xtaci兄的1202版及1207版的mips及mipsle版均不正常，运行mipsle版提示：”Illegal instruction“，运行mips版提示：“line 1: syntax error: unexpected "("”，烦请协助查找原因，谢谢！

**Comment by bettermanbao** [comment]
newifi 刷潘多拉，我自己编译的ramips和xtaci编译的mipsle都能正常运行。

**Comment by wang20150419** [comment]
@bettermanbao 我用了几天，发现偶尔会退出。不得已弄了一个监视脚本。

**Comment by hong26** [comment]
@wang20150419 老司机可否共享一下你的监视脚本呢？程序退出后是否能自动拉起呢？可以的话麻烦共享下你的脚本和使用方法！我的也是偶尔进程会退出！

**Comment by bettermanbao** [comment]
我现在在用的脚本来了，简单实用，以下脚本设置为随ss启动一起启动，随ss停止一起停止就可以了。

```
#!/bin/sh

while true; do
        sleep 30
        LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")

        wget -s -q http://www.google.com.hk
        if [ "$?" == "0" ]; then
                echo "[$LOGTIME] No problem."
        else
                wget -s -q http://www.baidu.com
                if [ "$?" == "0" ]; then
                        echo "[$LOGTIME] Problem decteted, restart Shadowsocks."
                        /etc/init.d/shadowsocks restart
                else
                        echo "[$LOGTIME] Network problem. Do nothing."
                fi
        fi
done
```

**Comment by jxr111** [comment]
@bettermanbao  我刷的是官网版本不是潘多拉，可能问题就出在这里。是编译时缺少了什么库文件吗？

**Comment by Biercenter** [comment]
跟我的情况一样，我也是官方版，还没解决。openwrt和lede官方版都试了不行，运行不起来，提示跟你一样

**Comment by redblackbst** [comment]
Exactly the same issue, newifi y1 running official OpenWrt Chaos Calmer 15.05.1.
Hopefully the dev would look into it.

**Comment by hybtw** [comment]
我newifi y1，官方版正常，不过我刷的是pandorabox14.09

**Comment by Biercenter** [comment]
发现原因了，可能是go18.1还是beta的原因，openwrt和lede官方固件需要修改内核重新编译，开启FPU模拟器

**Comment by xtaci** [comment]
嗯，是的， 多半和FPU有关
