### ISSUE TITLE
你们默认模式发包是多占用多少流量呢

### ISSUE THREAD

**Issue by kxmp** [xtaci/kcptun#329]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
v20161202
8. Which **OS** do you use?
Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux  on VMware
9. Which end for this issue related to, **client or server**?

默认是1.3 那么说我下载一个1MB的文件 他应该花费1.3MB流量. 在无丢包情况下.
可是我下载了个800k左右的文件 却用了1300k左右流量.  怎么比理论值要高1倍呢..

然后我又把设定改成-datashard 80 -parityshard 1
0丢包环境下面 流量多用了10.4%-12.6%  可是~1/81不是应该是1.23%么~
81/80=1.0125  
=+1.25%

我又不走kcp测了下. 
下个804kb的文件 实际流量多出了4.4% 应该是协议开销...
去掉tcp开销的话 流量还是多了好多啊...
kcp除了fec之外还有其他开销么?

2016-12-12 17:39:47
放个测试, 经供参考. 看起来kcp最怕抖动. 
https://github.com/xtaci/kcptun/issues/329#issuecomment-266375953

**Comment by bettermanbao** [comment]
那么在意流量的话，还是不要用kcp协议了。

**Comment by baggiogogo** [comment]
答案是肯定的，10%-20%。
[https://github.com/skywind3000/kcp](url)

**Comment by kxmp** [comment]
@baggiogogo 
你根本就没看kcptun主页上的说明
默认参数直接就30%. 
而且我测起来 直接就60%..... 奇怪的很.
当然 比当初直接900% 好多了..

**Comment by guliujian** [comment]
这个理论值也涉及到很多因素的影响，比如你的udp丢包率等等，不知道你上面的丢包率是指的icmp的ping的还是udp的

**Comment by kxmp** [comment]
@guliujian  0丢包 没问题的.
直接用vm测试的.

**Comment by baggiogogo** [comment]
这样直接就给别人个向下手势真的好么，你的问题是除了fec还有别的开销吗，我回答了10%-20%有错吗？并且直接给了出除，点不开不可以复制粘贴下吗？

**Comment by kxmp** [comment]
@bettermanbao baggiogogo

**Comment by kxmp** [comment]
不对哇. 既然kcp是低延迟通道. 应该主要给玩游戏用.
那你们那他看视频或者上网这不是自相矛盾么..
传数据应该用数据通道啊.
如果kcptun能把kcp关了 只开fec 这样就完美了!

**Comment by kxmp** [comment]
昨天测的20ms的抖动. 跑出了2.93的流量
去掉0.3的fec
还有164%的流量... 和30-40%差的太远了吧...
这是不是kcp的bug呢....

**Comment by bettermanbao** [comment]
我很好奇，你为什么那么在意流量的使用？
用default模式，就是关了kcp协议的各种功能，剩下的开销应该就是kcp协议本身打包的开销。你可以用vm试试看流量使用。

**Comment by kxmp** [comment]
@bettermanbao 
你真吓着我了 
我以为不知道default是啥东西 所以我昨天就用default测的.
那个用了164%就是default模式的.
我应该没记错的..

**Comment by kxmp** [comment]
@bettermanbao 
我好像想起来了 default卡的要死.... 
用了default fec也自动关了么?!

**Comment by bettermanbao** [comment]
是"-mode default"，不是省略-mode参数。
fec默认开10:3

**Comment by kxmp** [comment]
@bettermanbao
卡爆了....   奇怪.. fec解决不了丢包么...
22.7K/s

**Comment by bettermanbao** [comment]
fec可以恢复部分丢包，但是对于丢包无规律的网络，作用有限。这是我的实际使用经验。

**Comment by bettermanbao** [comment]
另外，你还没回答我，你为什么那么在意流量？

**Comment by kxmp** [comment]
@bettermanbao
我今天测了半天 fec 80 1
照样速度快得很. 难道这个fec对丢包就不管啥作用么
现在速度变成这样了...
36.7K/s

**Comment by kxmp** [comment]
神奇啊. 难道用这个"加速"/加速 网络根本不需要开fec啊!!
我fec 0 0了..
照样
36.7k 变成2.12M/s
太打击人了....

**Comment by kxmp** [comment]
现在负荷变成9%-10%了...
我是不是疯了. 哈哈.
太打击人了...

**Comment by dearneo** [comment]
@kxmp 
KCP不走tcp协议，走的是UDP协议，是在UDP协议上使用算法实现的可靠协议，本身开销是10%~20%。
FEC应该是作者xtaci大神为kcptun加上去的功能，可保证一定丢包率下可以还原数据无需重传，本身也有开销
希望高载荷率的话，可参考下面这组参数，我个人在用，测试有效数据载荷很高，350ms左右rtt 20%左右丢包率的情况载荷率也有60%以上，且速度可以，但速度曲线不够平滑。interval参数可再做调整，我这里选择的大约是1.5倍rtt

-mtu 1300 -sndwnd 2048 -rcvwnd 512 -datashard 0 -parityshard 0 -mode manual -nodelay 1 -resend 0 -nc 1 -interval 500

**Comment by kxmp** [comment]
@dearneo 
只要用tcp就会有tcp开销的.
你kcp通道访问tcp是tcp包在udp里面的.
精确算的话还是把tcp消耗的流量也去掉比较好.
我刚才也测了下 350ms+20%丢包 去除第一次数据传输
多用了20%流量.
我咋比你少这么多...

初次传输用了88%...

**Comment by dearneo** [comment]
@kxmp 
我是在实际环境下测试的，关闭了kcptun的压缩，但并没有很精确的测试，我计算的方式是 下载文件大小 / VPS网卡发出流量，60%也是个比较保守的说法，实际有效载荷略小于70%

感觉你的多用20%流量不太可能吧，本身都有20%左右的丢包了，还只多用20%流量？难道kcp协议完全没开销？

**Comment by kxmp** [comment]
@dearneo  
真是这样的. 我不给你说了第一次多费了88%么
我省去这个之后 然后他就非常小了...

**Comment by dearneo** [comment]
@kxmp 
纯粹按20%丢包率看，要传输1的数据，就要发送1 /（1-20%）=1.25的数据，已经多消耗25%的流量，怎么也想不通怎么只多了20%的流量。。。

**Comment by kxmp** [comment]
@dearneo
我关闭服务端和客户端
然后重新测试
访问一下文件 算一下=96.1%
然后重复访问4次. 计算流量 取均值
然后变成了28.7%
你说这是咋回事.

**Comment by dearneo** [comment]
@kxmp 
我也说不清，应该和墙的各种机制和实时线路质量有关，我的这个参数还是很保守的，你有空的话不妨也测一下

**Comment by kxmp** [comment]
4%丢包 用初次访问的
算来算去是70%了....
然后访问另一个文件.. 突然又变成12%了...
这隧道真是中邪了!!!

**Comment by baggiogogo** [comment]
@kmahyyg @baggiogogo 没想到理论上的证明最大化， 经验是FEC的有效还原率会降低重传。简单的思维游戏：

假如40%的丢包率（比较贴近实际情况）
如果不考虑FEC，那么s->c的PUSH丢包40%，c->s的ACK丢包40%，等于单次为 60% *60% = 36%的有效数据。
如果用FEC 5:5, 那么s->c的PUSH能在40%丢包率下全部还原， 等于单次为 50%的有效数据。
情况2还需要考虑重传的过程中继续的64%丢包。总重复率是
0.64 ^2 + 0.64^4 + 0.64 ^8 ... 0.64^m , m -> ∞

以上是作者以前的描述，所以一定要考虑线路的实际情况来考虑是打开或者关闭FEC，短时测试有盲点，如长时间实际使用统计，不同的情况的最佳选择是不同的。

**Comment by kxmp** [comment]
头都大了..
刚才测了一下 
90+%
100%
200%
全出来了...
环境都一样的...
怪事了.
