### ISSUE TITLE
stream closed

### ISSUE THREAD

**Issue by sunnoy** [xtaci/kcptun#33]
stream closed2016/06/15 21:33:24 stream closed
2016/06/15 21:33:24 [ERR] yamux: keepalive failed: i/o deadline reached
2016/06/15 21:33:24 [ERR] yamux: Failed to read header: broken pipe
2016/06/15 21:33:24 keepalive timeout

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Does your ISP or VPS **blocked UDP**?
5. Does your VPS **firewall** allows UDP pass through?
6. Are you using the **same version** for both client & server

**Comment by sunnoy** [comment]
1. yes
2. centos 6.6 386  windows10 64
3 server
4 i dont known  how to confirm it 
5 yes  i can use short time 
6 yes

**Comment by xtaci** [comment]
1. Which VPS provider do you use?
2. What's your network environment, ADSL/FTTH, 50M or 100M or other?

**Comment by sunnoy** [comment]
现在可以使用了 加速效果明显 只是不是很稳定 vps 版瓦工 电信校园网 100m

**Comment by xtaci** [comment]
congratulations,  try adjust -rcvwnd -sndwnd to see the difference.
