### ISSUE TITLE
About cpu ressources

### ISSUE THREAD

**Issue by limbo127** [xtaci/kcptun#331]
Hello, 
When I do some tests with kcptun on LAN network ( 100Mbit/s) , ~ 500 Kcp clients to one server, 
cpu metric for kcp server is less < 10% 
The same test with Wan network , kcp server is ~ 90% of cpu  , 
is there an explanation ? resend ? error ? 

Regards, 
Nicolas P.

**Comment by xtaci** [comment]
try increase -interval to see if it lowers CPU consumption.

if it does,  the cause is latency.

**Comment by xtaci** [comment]
and also,  try smaller window size,  like 64 or 128

**Comment by limbo127** [comment]
I do not see any -interval option in client nor server ? what is about ?

**Comment by xtaci** [comment]
hidden parameter,   -mode manual  

https://github.com/xtaci/kcptun/issues/137
