### ISSUE TITLE
为什么ios没有支持kcptun的客户端？感觉太不方便了，求大神造个轮子

### ISSUE THREAD

**Issue by 1563172697** [xtaci/kcptun#332]

**Comment by baggiogogo** [comment]
估计要等现有的ios工具添加支持了，目前不是办法的办法，家里或者其他神马地方加个跳板，流量党也适用，C--->S+C--->S。

**Comment by bettermanbao** [comment]
自家路由器上装个kcptun client端，做国内中转就可以了。

**Comment by alex43211** [comment]
我路由器比较弱，我就弄了个树莓派做kcptun client，挺好用的。

**Comment by huadi016** [comment]
@bettermanbao 做中转？我现在在网件r6900搭了ss+kcp，请问一下，我能作什么样的中转？

**Comment by whour** [comment]
![_2017-03-31_11-15-07](https://cloud.githubusercontent.com/assets/4928187/24534933/86b57c90-1603-11e7-85cd-77796fee587b.png)

这个测试版本有了kcptun的支持。
Testfight 申请地址：
https://docs.google.com/forms/d/e/1FAIpQLSdBcIfAZY15BaXMzAq1Rj0kpTJ4xFBqkzwIbxYhAmmse7NXBQ/viewform?c=0&w=1
https://itunes.apple.com/cn/app/a-big-t-a-smart-vpn/id1051326718?l=en&mt=8
