### ISSUE TITLE
问下客户端为何还会打开一个udp端口？

### ISSUE THREAD

**Issue by tenwx** [xtaci/kcptun#333]
使用kcptun-windows-386-20161207.tar.gz里的client，成功运行后观察打开的端口，发现除了打开供ss客户端使用的tcp端口外，还会打开一个udp端口，不知是啥？
贴上参数：
--localaddr "127.0.0.1:32202" --remoteaddr "xxxx:32203" --conn 1 --crypt salsa20 --key "xxxx" --mode manual --nodelay 0 --resend 2 --nc 1 --interval 50 --datashard 80 --parityshard 5 --sndwnd 512 --rcvwnd 128 --mtu 512 --dscp 46 --autoexpire 0 --sockbuf 4194304 --acknodelay true --keepalive 10

![image](https://cloud.githubusercontent.com/assets/3733304/21224206/f1af2768-c305-11e6-83db-8e38d71bbe28.png)

**Comment by lizongzeshunshun** [comment]
连接server的端口吧..

**Comment by tenwx** [comment]
@lizongzeshunshun 这个是udp监听端口

**Comment by xtaci** [comment]
基本原理的嘛，  通信是四元组 < local addr, local port,  remote addr, remote port >

**Comment by wdjwxh** [comment]
@Comaxim 这是windows自带的资源监视器

**Comment by Comaxim** [comment]
@wdjwxh 谢谢。

**Comment by AttufliX** [comment]
这个udp端口是随机的嘛？我想全局udp转发，所以需要return kcptun自己的udp，端口随机的话我应该怎么放行
