### ISSUE TITLE
Requests per second throughput

### ISSUE THREAD

**Issue by jeromegn** [xtaci/kcptun#334]
Hi,

I've been playing with kcptun, curious about the performance and I found out that I would get at most 11-12K requests/per second on a server that can handle 56K requests/sec.

I'm wondering which settings I should try tweaking to achieve better requests per second throughput?

I played with the send/receive window sizes without seeing any significant improvement. I also tried various MTU values, same result.

When I changed the `-conn` flag to `2`, I got lower performance.

server to tunnel:

```
go get github.com/valyala/fasthttp
go run $GOPATH/src/github.com/valyala/fasthttp/examples/fileserver/fileserver.go -dir .
```

kcptun server:

```
-t 127.0.0.1:8080 -mode normal -sndwnd 256 -rcvwnd 2048 --crypt none --nocomp
```

kcptun client:

```
-r :29900 -l :8081 -mode normal -sndwnd 256 -rcvwnd 2048 --crypt none --nocomp
```

**Benchmarks (all local):**

fasthttp server (no tunnel):
```
wrk -c 8 -d 10s http://localhost:8080
Running 10s test @ http://localhost:8080
  2 threads and 8 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   140.08us   23.11us   1.03ms   75.41%
    Req/Sec    27.44k   567.15    29.32k    73.27%
  551323 requests in 10.10s, 1.24GB read
Requests/sec:  54588.06
Transfer/sec:    125.46MB
```

tunnelled:

```
wrk -c 8 -d 10s http://localhost:8081
Running 10s test @ http://localhost:8081
  2 threads and 8 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.96ms    5.48ms 155.27ms   99.63%
    Req/Sec     5.99k   392.90     7.07k    70.30%
  120261 requests in 10.10s, 276.40MB read
Requests/sec:  11907.44
Transfer/sec:     27.37MB
```

The tunnelled version is about 4-5x slower than the original server.

I tried on lower throughput servers (like `gohttp` and I seemed to achieve about 2x lower throughput, which is better.)

Any ideas would be appreciated!

**Comment by xtaci** [comment]
have you tried increasing -sockbuf ?

**Comment by xtaci** [comment]
besides, kcptun is suitable for high loss links (around 30 % packet loss)

**Comment by jeromegn** [comment]
I haven't tried a different sockbuf setting. I'm using the default. Any value to suggest in particular?

I'm interested in kcptun because it has better performance than tcp-over-tcp tunnels (such as ssh tunnels, with are really slow!) kcptun offers pretty good performances.

I would be running kcptun on highly reliable networks though, packet loss should be minimal. Even if it's not suitable for that environment, it still is much faster than a TCP tunnel.

**Comment by xtaci** [comment]
that's true,  tcp is also improving itself , like bbr congestion control : http://blog.cerowrt.org/post/bbrs_basic_beauty/

kcptun multiplexes streams into a single physical UDP connection, I haven't benchmarked the situation of short boost connections.  

I think there maybe someway to improve RPS:
1. do not use -mode normal , try -mode fast2 or mode fast3 or manaul, eg:
`-mode manual -nodelay 1 -resend 2 -nc 1 -interval 10`,  try smaller interval values

2. enlarge -sockbuf, like 16MB ( first you should increase the sockbuf limit by sysctl).

**Comment by jeromegn** [comment]
Thanks @xtaci for the quick response with suggestions!

I tried doubling the sockbuf (from 4MB to 8MB,) but that didn't help in a meaningful way. Do you think 16MB would make a difference? (Worth noting that it was a real pain to change the sysctl settings on my mac. It's very obscure how the max socket buffer is calculated. I had to change `boot-args` with `nvram` following the instructions in this message: https://lists.apple.com/archives/darwin-kernel/2012/Apr/msg00042.html)

I also tried reducing the interval to 10 and 5, still no major improvement.

I've tried using yamux and muxado a few weeks ago and I lost of lot of performance. smux seems to be the fastest multiplexes available. I'll give it another try though.

I've added a buffer pool to use with `io.CopyBuffer` instead of `io.Copy` and I've also created a `net.Conn` pool to the target endpoint. Both of these only improved performances a little bit.

Thanks for the help, really appreciated.

**Comment by xtaci** [comment]
how about the CPU usage in benchmark?

**Comment by jeromegn** [comment]
It looks like my CPU usage is through the roof. That would seem to be the bottleneck.

Any tips on how to decrease CPU usage in kcptun?

**Comment by xtaci** [comment]
increase -interval , reduce -sndwnd -rcvwnd

**Comment by bettermanbao** [comment]
Disable FEC & use crypt salsa20 will reduce CPU usage a lot. 
I'm running kcptun on my home router, which has a very low end CPU. These settings do help a lot on reducing CPU usage.

**Comment by jeromegn** [comment]
If all I'm going to be streaming are http requests over a kcptun, do I need Forward Error Correction? TCP takes care of error correction on its own. The networks I'd be using are pretty reliable, although they may be far away.
