### ISSUE TITLE
client crashes very often in MacOS, 20161207 build

### ISSUE THREAD

**Issue by holywen** [xtaci/kcptun#336]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ccc7e]

goroutine 1 [running]:
main.main.func1(0xc4200a0000, 0x0, 0x0)
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:382 +0x1c4e
github.com/urfave/cli.HandleAction(0x11f9f40, 0x124bdb8, 0xc4200a0000, 0xc42006e240, 0x0)
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483 +0xb9
github.com/urfave/cli.(*App).Run(0xc42009a340, 0xc42000e0b0, 0xb, 0xb, 0x0, 0x0)
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254 +0x61c
main.main()
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:402 +0x115f
2016/12/16 21:05:18 stream opened
2016/12/16 21:05:18 TCP SetReadBuffer: set tcp [::7f00:1]:12948: setsockopt: invalid argument
2016/12/16 21:05:18 stream opened
2016/12/16 21:05:18 TCP SetWriteBuffer: set tcp [::7f00:1]:12948: setsockopt: invalid argument

**Comment by holywen** [comment]
Another example:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ccc7e]

goroutine 1 [panic: running]:
runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violationmain.main.func1 code=(0x10xc4200b8000 addr=, 0x00x0 pc=, 0x11ccc7e0x0]
)

goroutine 1	 [/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.gorunning:]:
382 +0x1c4e
main.main.func1github.com/urfave/cli.HandleAction((0xc4200a00000x11f9f40, , 0x00x124bdb8, , 0x00xc4200b8000)
, 0xc42006e240, 	0x0/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go)
:382	 +/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go0x1c4e:
483github.com/urfave/cli.HandleAction +(0xb90x11f9f40
, github.com/urfave/cli.(*App).Run0x124bdb8(, 0xc42009a3400xc4200a0000, , 0xc42000e0b00xc42006e240, , 0xb0x0, )
0xb, 	0x0/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go, :0x0483)
 +	0xb9/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go
:github.com/urfave/cli.(*App).Run254( +0xc42009a3400x61c, 
0xc42000e0b0main.main, (0xb)

**Comment by yuexia12** [comment]
I use osx 10.12.2 and kcptun works fine.

**Comment by yuexia12** [comment]
my macbook panic a few times before 10.12.2. maybe you try to upgrade to newest sierra first.

**Comment by holywen** [comment]
OK I will try, my Macos Version is  10.12.1 right now.

**Comment by holywen** [comment]
Still get a lot of crashes:
--
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ccc7e]

goroutine 1 [running]:
main.main.func1(0xc4200a0000, 0x0, 0x0)
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:382 +0x1c4e
github.com/urfave/cli.HandleAction(0x11f9f40, 0x124bdb8, 0xc4200a0000, 0xc42006e240, 0x0)
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483 +0xb9
github.com/urfave/cli.(*App).Run(0xc42009a340, 0xc42000e0b0, 0xb, 0xb, 0x0, 0x0)
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254 +0x61c
main.main()
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:402 +0x115f
2016/12/17 11:24:32 TCP SetReadBuffer: set tcp [::7f00:1]:12955: setsockopt: invalid argument
2016/12/17 11:24:32 TCP SetWriteBuffer: set tcp [::7f00:1]:12955: setsockopt: invalid argument
2016/12/17 11:24:32 stream opened
2016/12/17 11:24:32 stream closed
--
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ccc7e]

goroutine 1 [running]:
main.main.func1(0xc4200a0000, 0x0, 0x0)
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:382 +0x1c4e
github.com/urfave/cli.HandleAction(0x11f9f40, 0x124bdb8, 0xc4200a0000, 0xc42006e240, 0x0)
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483 +0xb9
github.com/urfave/cli.(*App).Run(0xc42009a340, 0xc42000e0b0, 0xb, 0xb, 0x0, 0x0)
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254 +0x61c
main.main()
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:402 +0x115f
2016/12/17 11:26:26 stream opened
2016/12/17 11:26:26 stream closed
2016/12/17 11:26:27 TCP SetReadBuffer: set tcp 127.0.0.1:12955: setsockopt: invalid argument
2016/12/17 11:26:27 TCP SetWriteBuffer: set tcp 127.0.0.1:12955: setsockopt: invalid argument
Holys-MacBook-Pro:scripts swen$ uname -a
Darwin Holys-MacBook-Pro.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

**Comment by xtaci** [comment]
maybe it's because of network change

**Comment by xtaci** [comment]
when AcceptTCP() returns error,  p1 is nil , so the panic happens, added code to handle that .

main.go:382

**Comment by holywen** [comment]
my parameters: 
 -sndwnd 64 -rcvwnd 64 --key xxxxxx -l :12951 -r somehost:port

I think your guess is correct, this happens often especially when I open MBP and login again.

**Comment by holywen** [comment]
I will try: -l localhost:12952 and check if it will crash or not.

**Comment by holywen** [comment]
Still crashes when resume from sleep.
--
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ccc7e]

goroutine 1 [running]:
main.main.func1(0xc4200b8000, 0x0, 0x0)
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:382 +0x1c4e
github.com/urfave/cli.HandleAction(0x11f9f40, 0x124bdb8, 0xc4200b8000, 0xc42006e240, 0x0)
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483 +0xb9
github.com/urfave/cli.(*App).Run(0xc42009a340, 0xc42000e0b0, 0xb, 0xb, 0x0, 0x0)
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254 +0x61c
main.main()
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:402 +0x115f

**Comment by xtaci** [comment]
i think NIC is disabled when in sleeping, something related to power managment, never crashed on my mac.

**Comment by holywen** [comment]
Will rebuild the latest code and test again.

**Comment by holywen** [comment]
The latest code make it  not panic and crash any more, 
but when resume from sleep, the kcptun client doesn't work (handling the traffic) any more.
I got connection been reset errors now, a restart of the client make it works again.

**Comment by holywen** [comment]
after several hours:
2016/12/18 22:46:49 accept tcp [::]:12952: accept: too many open files in system
As I checked and set ： 
open files                      (-n) 4096

**Comment by xtaci** [comment]
nice, you've found out why by yourself.
