### ISSUE TITLE
说一下心得，关键在客户端的rcvwnd值要小

### ISSUE THREAD

**Issue by jinwyp** [xtaci/kcptun#337]
之前的一些策略不说了。
服务器端其实fast默认就可以了。

关键是客户端的 	 这两个值sndwnd和rcvwnd  非常重要 

我的值如下：
"sndwnd": 380,
"rcvwnd": 110,

rcvwnd决定了看youtube的最高速度，就是接受峰值。但是更重要的是sndwnd和rcvwnd值的配合， 决定是否稳定度。如果sndwnd太高了就会产生峰值到0波动非常厉害。

测试视频 https://www.youtube.com/watch?v=vlDzYIIOYmM&t=14s

我是从这两个值 sndwnd ：10 和 rcvwnd 10 不断 增加测试。
例如20m带宽 最高下载2.5Mbp， 当 rcvwnd 为100时 峰值在600k左右，基本看720p够了， rcvwnd为200是1.7M 这时候如果稳定基本上1080p非常快了。 那么 20M带宽 rcvwnd 为230左右已经是极限了。

所以建议 rcvwnd 开始设置为100， 然后把sndwnd 逐渐从20开始调高，如果youbute开始下降或波动， 一般根据你网速而定。例如sndwnd 到40就开始不稳定了 那么就把sndwnd 调到30左右。 然后开始调高rcvwnd ，如果到150就开始下降了， 那么rcvwnd在130左右。 sndwnd调的只要有一点过高就会导致峰值下降厉害。同样 rcvwnd 值有一点过高也会导致峰值下降。

rcvwnd + sndwnd 等于你的带宽， 所以 这两个值需要找一个平衡点， 一旦这两个值有一个过高，直接导致不稳定，youtube就非常卡了。

基本上 调整完 youbute 4k 基本不卡了

服务器配置：
{
    "listen": ":10001",
    "target": "127.0.0.1:9001",
    "key": "xxx",
    "crypt": "aes-128",
    "mode": "fast",
    "mtu": 1400,
    "sndwnd": 300,
    "rcvwnd": 2048,
    "datashard": 5,
    "parityshard": 5,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 1,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10,
    "log":"/home/kcptun.log"
}

可使用的客户端配置文件为:
{
    "localaddr": ":9001",
    "remoteaddr": "45.76.159.52:10001",
    "key": "xxx",
    "crypt": "aes-128",
    "mode": "fast",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1400,
    "sndwnd": 250,
    "rcvwnd": 200,
    "datashard": 5,
    "parityshard": 5,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 1,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}

**Comment by wang20150419** [comment]
这个参数超出理解范围，感觉很不合理。我的电信网络，测试无效。

**Comment by ragnaroks** [comment]
server_sndwnd=>client_rcvwnd
client_sndwnd=>server_rcvwnd

**Comment by yuexia12** [comment]
还有一个我自己遇到的，就是看youtube如果720p hd模式10分钟左右就会被断流，限制播放速度240p后，一天都不断，所以个人得出结论是速度快了会被盯上，在不影响网页浏览的流畅的情况下尽量克制youtube播放速度。
我是 ss+kcptun，不加kcptun单独用ss的时候，200多毫秒的延迟看视频或者开网页还是卡的像狗一样。
我的参数就是默认的 客户端 服务端都 fast2,1024,1024，加密模式none.

**Comment by alex43211** [comment]
亲测默认的配置看1080p乃至1440p都可以了，4k卡顿，不过已经满足我的需要了，基本不断流。家里是50M的电信。主要是经常去的几个地方带宽都不同，也懒得改了，再次感谢作者！

**Comment by huadi016** [comment]
我的，20./256，流畅720p
