### ISSUE TITLE
best performance on low latency network

### ISSUE THREAD

**Issue by denadmin** [xtaci/kcptun#338]
I tried to use kcptun over 1GB lan. I turned off encryption, compression, FEC. Used 4096 as snd/rcvwnd, increased buffer up to 40 MB, but only I get is about 70 mbit/s, accoding to iperf.

My question is: which parameters should I use to get best performance on low latency, low packet loss network.

**Comment by bash99** [comment]
why just use scp? 
kcptun is design to speed up high latency, high packet loss network?

**Comment by denadmin** [comment]
It would be much easer to use one utility for all, just tuning params.
