### ISSUE TITLE
想请教一下我是不是理解正确了。。。

### ISSUE THREAD

**Issue by saisunshine** [xtaci/kcptun#339]
ss客户端的监听端口填了1080，然后填了VPS的ip以及远程端口443，kcp客户端的监听端口填了443，然后填了vps的ip以及远程端口29900，VPS上的ss服务器local端口127.0.0.1:29900，kcp服务器的local端口填了127.0.0.1:443。这样的配置是正确的吗。。另外如果是Ipv6的话也是正确的么（ip我应该会填对）

**Comment by icymind** [comment]
ss without kcptun:
ss-client:1080 -> ss-server:29900

ss witch kcptun:
ss-client:1080 -> kcp-client:443 -> kcp-server:443 -> ss-server:29900

**Comment by saisunshine** [comment]
额。。我知道我刚刚那个理解是错的了。。但是楼上说kcp-server也听的443是说我在kcp-client里面服务器地址填kcp-server_ip:443是吗。另外。。那ss_server配置里面的server地址和server_port是不是随便填了。。

**Comment by saisunshine** [comment]
感觉自己好蠢啊。。再仔细问一下。。就是之前没用kcptun的时候。我ss-client里面服务器地址填的是VPS_IP:443,但是ss_server的监听地址却是127:0:0:1:1080。不是443，那确实可以科学上网啊。。这是怎么回事呢。

**Comment by icymind** [comment]
@saisunshine 
1. 是. kcp-server监听什么端口, kcp-client 的 remoteaddr 就写什么端口.
2. 不是. ss-server的server_port才表示监听的端口, 它的local_port应该没什么用. 另外server_host和local_adress我都填了0.0.0.0. 不确定是哪个被用到, 你可以试试.
3. 如2

**Comment by saisunshine** [comment]
@icymind 实在太感谢了！！我刚刚试了试ss-server的server-port是监听端口。终于搞清楚了。。一直没往这想。。因为早上的时候以为成功过（那个时候还不会看日志。。只是测了速的确变快了。）。但是配置完全不一样。然后就想着既然成功过，那就没问题。。没想到是totally wrong。。

**Comment by saisunshine** [comment]
@icymind 貌似ss_server和ss_client用的是同一份配置，就是对于他们各自的含义有点不一样。比如server_port对于server来说是listen_port，对于client来说则是remote_port，至于local_addr和local_port，如果不启用sslocal的话就没什么用。
