### ISSUE TITLE
试了好几次现在根本就连不上了

### ISSUE THREAD

**Issue by sunnoy** [xtaci/kcptun#34]
2016/06/16 14:34:44 [ERR] yamux: keepalive failed: i/o deadline reached
2016/06/16 14:34:44 [ERR] yamux: Failed to read header: broken pipe
2016/06/16 14:34:44 stream closed

**Comment by wxyzh** [comment]
最好分别提供服务端、客户端的参数以及提示的信息

**Comment by sunnoy** [comment]
服务端 ./server_linux_386 -l ":29912" -t "23.83.240.35:8883" --key "123" -mtu 1400 -sndwnd 2048 -rcvwnd 2048 --mode "fast2" > log 2>&1 &
客户端  start /b client_windows_amd64.exe -l ":2000" -r "23.83.240.35:29912" --key "123" -mtu 1400 -sndwnd 2048 -rcvwnd 2048 --mode "fast2" > log 2>&1
服务端  
2016/06/16 02:36:00 stream opened
2016/06/16 02:36:00 stream closed
2016/06/16 02:36:00 [ERR] yamux: keepalive failed: i/o deadline reached
2016/06/16 02:36:00 [ERR] yamux: Failed to read header: broken pipe
2016/06/16 02:36:00 keepalive timeout
2016/06/16 02:36:10 stream closed
2016/06/16 02:37:00 [ERR] yamux: keepalive failed: i/o deadline reached
2016/06/16 02:37:00 [ERR] yamux: Failed to read header: broken pipe
2016/06/16 02:37:00 keepalive timeout
2016/06/16 02:38:00 remote address: 61.157.97.83:42691
2016/06/16 02:38:00 stream opened
2016/06/16 02:38:00 stream opened
2016/06/16 02:38:00 stream closed
2016/06/16 02:38:10 stream closed
2016/06/16 02:39:00 [ERR] yamux: keepalive failed: i/o deadline reached
2016/06/16 02:39:00 [ERR] yamux: Failed to read header: broken pipe
2016/06/16 02:39:00 keepalive timeout
客户端 
2016/06/16 14:37:21 stream closed
2016/06/16 14:37:23 stream closed
2016/06/16 14:37:29 stream closed
2016/06/16 14:37:32 stream opened
2016/06/16 14:37:33 stream opened
2016/06/16 14:37:35 stream opened
2016/06/16 14:37:37 stream closed
2016/06/16 14:37:38 stream opened
2016/06/16 14:37:39 stream opened
2016/06/16 14:37:44 [ERR] yamux: keepalive failed: i/o deadline reached
2016/06/16 14:37:44 [ERR] yamux: Failed to read header: broken pipe
2016/06/16 14:37:44 stream closed
2016/06/16 14:37:44 stream closed
2016/06/16 14:37:44 stream closed
2016/06/16 14:37:44 stream closed
2016/06/16 14:37:44 stream closed
2016/06/16 14:37:44 session shutdown
2016/06/16 14:37:44 stream opened
2016/06/16 14:37:44 stream opened

**Comment by xtaci** [comment]
我只能猜测，校园网对udp非常不友好， 你可以尝试把服务器端口换为8000/4000/53/554/443/80这几个端口试试，另外client的 -sndwnd 256就够了

**Comment by sunnoy** [comment]
都试过了 还是连不上 就刚开始配置好上了一会挺快的  
服务端
2016/06/16 03:05:48 remote address: 61.157.97.83:3015
2016/06/16 03:05:48 stream opened
2016/06/16 03:06:48 [ERR] yamux: keepalive failed: i/o deadline reached
2016/06/16 03:06:48 [ERR] yamux: Failed to read header: broken pipe
2016/06/16 03:06:48 keepalive timeout
2016/06/16 03:06:48 stream closed
看着像是udp 被封了

**Comment by xtaci** [comment]
你先把 -sndwnd -rcvwnd 都降到128

**Comment by voq** [comment]
和你的问题一样，换成SNMP Millstone Version就好了，6月15号的新版本好像有问题。

**Comment by sunnoy** [comment]
SNMP Millstone Version  在哪下载
 换了机房 换了端口 还是不行 已累了

**Comment by D-Bood** [comment]
点开release 最底下那个

**Comment by xtaci** [comment]
校验过md5么？ 是官方release么？

**Comment by D-Bood** [comment]
MD我智障了，忘了校验直接下了
不过的确是从你这下的

**Comment by xtaci** [comment]
嗯，review了一下，确实发现了一个问题，这个问题和-conn参数有关

**Comment by voq** [comment]
对了，xtaci大大，服务器和客户端的版本必须要一致么？

**Comment by xtaci** [comment]
SNMP milestone之后的，都可以兼容， 等下提交新的release

**Comment by voq** [comment]
包括SNMP milestone吧？

**Comment by xtaci** [comment]
包括， 但还是建议两端都更新到最新版本。

**Comment by voq** [comment]
嗯，谢谢你的程序，很好用。

**Comment by sunnoy** [comment]
还是依旧连上不，整了一天该干工作了  等等后面版本再说吧  很期待后面的版本好整  效果还是很好的

**Comment by xtaci** [comment]
@voq 可以试一下我刚修正的0616版本

**Comment by xtaci** [comment]
**thank you all!**

**Comment by LiR1cky** [comment]
试了默认的端口29900,554,1755都用不了，近乎绝望时试了一下443豁然开朗。。。

**Comment by xtaci** [comment]
good story
