### ISSUE TITLE
请问一下使用kcptun后下载速度变得更慢,上传速度爆表是咋回事?

### ISSUE THREAD

**Issue by yy942qq** [xtaci/kcptun#340]
我是使用SSR,裸ssr能有1.5MB左右的下载速度,1MB左右上传.
使用kcptun后,下载速度只有500KB左右了,上传速度10MB以上,都是默认配置,没有修改,咋回事?

**Comment by linhua55** [comment]
试一下这个
https://github.com/xtaci/kcptun#流量控制

**Comment by baggiogogo** [comment]
调整窗口，200ms左右延迟的话，384 384 10/3的FEC，大约是上20M下20M。不配FEC 512 512，也是上20M下20M。128差不多5M，差不多这个比例。
延迟差别太多的话，需要自行观察调整。

**Comment by dorrywhale** [comment]
20170220 在ubuntu 16.04上，上传速度高达30Mbit/s，电信出口也就 10Mbit/s，为什么会这样呢。后来，我先做了个 QoS 限速，不知道会对KCP有什么影响。
