### ISSUE TITLE
关于断流、rtt、以及interval参数

### ISSUE THREAD

**Issue by dearneo** [xtaci/kcptun#343]
之前把server和client的手动参数都改成--mode manual --nodelay 1 --resend 0 --nc 1 --interval 500，发现效果很棒（测速约10-15Mbps，基本无断流，算上线路本身25%左右的丢包在内。有效流量也高达60%以上，对流量小的小主鸡非常友好）

但最近发现小主鸡也时不时发生断流，且发生断流时测试rtt差不多有500+ms，平时正常应该在350ms左右。断流时重启客户端都无法解决问题，然后等上几分钟然后又可以了

又试着把interval 继续增大到800（大约1.5倍rtt），然后惊喜地发现貌似不断流了，连续看720p的youtube直播几个小时也没发现断流

所以我的经验似乎说明了似乎把interval参数设置的略大于rtt可以解决断流？！

**Comment by wulongji2016** [comment]
我使用了30分钟，就断流了？是设置的问题？还是电信干扰的问题？黑龙江电信
