### ISSUE TITLE
希望原作者或者热心人制作一份简单的小白安装和排除故障的教程 

### ISSUE THREAD

**Issue by wulongji2016** [xtaci/kcptun#345]
感谢原作者的共享，分享了开源免费的软件给大家使用。
不过，大部分人没有那么高的水平，甚至连安装vps都不会。对于大神很简单的事情，对小白来说，就是很难的坑。
希望有人能出一个简易使用的教程，方便小白安装和排查故障。这样才能收益更多的人，软件使用的人会更多。当然了，这是站在普通小白的角度看问题。作者或者其他大神或许没有时间，或许这个项目仅仅个人爱好，限于高手圈子内部交流。看问题角度不同，结果不一样。

我想起来Linux的大神，在技术上造诣很深，但是软件推广方便，普通用户更喜欢微软这样的产品，苹果手机风靡到现在，也是简单易用引用了很多用户，用户数量的变化，造就了商业模式的改变。Ubuntu在Linux各个版本里受欢迎，也是易用性方便起了很多作用。

技术，易用性，推广策略，都是不同层面的问题。我们不能苛求一个开源爱好者考虑普通用户的易用性要求，但是一个伟大的技术，需要一个易用性的产品作为载体，来奠定一个更广阔的使用场景和用户数量。
这样技术本身才能发挥和体现更多的力量，造福更多的普通用户。
本人对代码有兴趣，但是技术功底不足，停留在C语言2级的水平上，无法自己贡献更多的力量。
使用了很多服务器端的软件，感受最深的就是，易用性方便是很大的坑和门槛。

只是希望开源界的大神，在完善软件功能的同时，考虑一下易用性。谢谢各位了！

**Comment by bettermanbao** [comment]
小白其实还是建议买个国内中转的SS账号，直接用就好了。

**Comment by xayoung** [comment]
已经有两种选择了：1.直接买账号  2.自己搭建vps+ss+kcptun/fs/锐速.
既然选择了2，作为技术爱好者，那么接下来即将可能遇到的困难则需要通过阅读文档、教程、搜索引擎来一步步解决问题，这应该是基本的能力吧。

**Comment by huadi016** [comment]
哈哈。技术性的东西大神都开发好了，像我这种电脑小白使用这个软件就不要劳烦大神了，自己查查资料，搭建个ss+kcptun。玩一会你就发现，其实就像windows装个qq一样。

**Comment by alex43211** [comment]
这个东西，怎么说呢，有人不是在微信弄了个教程然后账号就被封了么，原因你懂得。
小白去百度贴吧的搬瓦工吧看看，应该就可以装起来了，一个人装了，给身边不懂得小伙伴用，也挺不错的。

**Comment by Joehaivo** [comment]
https://github.com/Joehaivo/onekey-shadowsocks-kcptun   这是我写的一个简易安装教程 可以看看
