### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Dethrail** [xtaci/kcptun#346]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

>1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
>2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
>3. Did you correctly set the ***-target*** on the server side?
>4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
>5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
>6. Are you using the **same version** for both client & server

yes

>7. Are you using the **latest release**?
 
yes

> 8. Which **OS** do you use? 

windows 10 64 bit

>9. Which end for this issue related to, **client or server**?

yes

# github.com/xtaci/kcptun/server
.\main.go:393: kcp.DefaultSnmp.Header undefined (type *kcp.Snmp has no field or method Header)
.\main.go:397: kcp.DefaultSnmp.ToSlice undefined (type *kcp.Snmp has no field or method ToSlice)
.\main.go:400: kcp.DefaultSnmp.Reset undefined (type *kcp.Snmp has no field or method Reset)

# github.com/xtaci/kcptun/client
.\main.go:475: kcp.DefaultSnmp.Header undefined (type *kcp.Snmp has no field or method Header)
.\main.go:479: kcp.DefaultSnmp.ToSlice undefined (type *kcp.Snmp has no field or method ToSlice)
.\main.go:482: kcp.DefaultSnmp.Reset undefined (type *kcp.Snmp has no field or method Reset)

**Comment by xtaci** [comment]
go get -u github.com/xtaci/kcptun/client     to update dependency

**Comment by Dethrail** [comment]
thank fixed
