### ISSUE TITLE
Can someone provide a .json config template?

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [xtaci/kcptun#350]
Thank you in advance...

**Comment by testcaoy7** [comment]
I had found this in the code:

+package main
 +
 +type Config struct {
 +	LocalAddr    string `json:"localaddr"`
 +	RemoteAddr   string `json:"remoteaddr"`
 +	Key          string `json:"key"`
 +	Crypt        string `json:"crypt"`
 +	Mode         string `json:"mode"`
 +	Conn         int    `json:"conn"`
 +	AutoExpire   int    `json:"autoexpire"`
 +	MTU          int    `json:"mtu"`
 +	SndWnd       int    `json:"sndwnd"`
 +	RcvWnd       int    `json:"rcvwnd"`
 +	DataShard    int    `json:"datashard"`
 +	ParityShard  int    `json:"parityshard"`
 +	DSCP         int    `json:"dscp"`
 +	NoComp       bool   `json:"nocomp"`
 +	AckNodelay   bool   `json:"acknodelay"`
 +	NoDelay      int    `json:"nodelay"`
 +	Interval     int    `json:"interval"`
 +	Resend       int    `json:"resend"`
 +	NoCongestion int    `json:"nc"`
 +	SockBuf      int    `json:"sockbuf"`
 +	KeepAlive    int    `json:"keepalive"`
 +}

**Comment by GreatBigWhiteWorld** [comment]
@testcaoy7 This seems not to be the exact template but a clue on how each parameter is named right.
I wonder if the following looks right (server side):
{
    "localaddr": "0.0.0.0:8388",
    "remoteaddr": "0.0.0.0:4000",
    "key": "12321",
    "crypt": "aes-128"
    .....
} 

?

**Comment by xtaci** [comment]
<img width="444" alt="dd6d72f7-6db9-49b7-924c-bb52280356a2" src="https://cloud.githubusercontent.com/assets/2346725/21470559/6aae5bc8-cac9-11e6-9f7b-657d0120a9bf.png">

everything you need is here:
client/config.go   server/config.go

**Comment by GreatBigWhiteWorld** [comment]
So it should be run like

 ./server_linux_amd64 -c PATHTOCONFIG/config.go 

And make a file named config.go, in which the content is

+package main
+
+type Config struct {

LocalAddr string json:"0.0.0.0:8388"
RemoteAddr string json:"0.0.0.0:4000"
Key string json:"password"
Crypt string json:"aes-128"
Mode string json:"fast"
....


Is that right?

**Comment by testcaoy7** [comment]
@GreatBigWhiteWorld  No! You have to write a JSON file! The file name dose not matter.

**Comment by GreatBigWhiteWorld** [comment]
@testcaoy7 That has been my question. What does the json file content look like?
