### ISSUE TITLE
bug  Illegal instruction

### ISSUE THREAD

**Issue by jonwinters** [xtaci/kcptun#351]
Illegal instruction
mips路由器 Openwrt环境

**Comment by xtaci** [comment]
必须要带FPU的mips芯片

**Comment by terrytw** [comment]
请问这个问题在将来有解决的可能性吗？

**Comment by xtaci** [comment]
要看golang官方了，目前就是需要在路由器内核重新编译支持FPU 模拟

**Comment by terrytw** [comment]
哦，明白了，谢谢

另外楼主你可以用这个
https://github.com/bettermanbao/openwrt-kcptun
配合1118版的服务端

**Comment by jonwinters** [comment]
@xtaci 
openwrt无解，貌似没有看到这样的k-mod
@terrytw
一定要配合相同的服务端？我之前用的 每次stream打开的时候，然后Client就崩溃了

**Comment by jonwinters** [comment]
@xtaci
无解了 ，openwrt 09年就关闭了 soft floating simulation了

**Comment by terrytw** [comment]
当然要配合相同的服务端了...
我现在就是两边都是1118，用的很正常
新版的就ILLEGAL INSTRUCTION

如果你实在想用新版可以问问之前BETTERMANDAO是怎么编译的吧

**Comment by xtaci** [comment]
可以试试不用 -c config.json ，直接通过命令行启动，看会不会有illegal instruction, 我印象中，只有json部分才有float运算。

**Comment by terrytw** [comment]
我试过，BETTERMANDAO的版本可用，新版不行...
直接用命令行就是illegal instruction，创建config.json就提示error132

**Comment by xtaci** [comment]
嗯，那就麻烦了。。 只能用bettermanbao的go1.4编译版本，另外， 不同版本都兼容的（除了几个月前早期版本）。
