### ISSUE TITLE
关于断流的分析及解决方法

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#353]
今天分析了一下我这里断流的情况，总结出一些经验和大家分享。

我这边断流最明显的特征就是UDP的丢包率会从正常的<3%，飚升到30%左右，并且丢包率在时间上非常稳定，此时kcptun几乎无法工作。此时更换端口，更换服务器断流都无法恢复。
疑问：想请问一下作者有没有测试过kcp协议在关闭FEC的情况下，可以容忍的最大丢包率？

以上丢包率是通过iperf实测得到的，有兴趣的朋友也可以自己测试一下，看看你那边断流时的情况。
具体命令如下：
服务器端（监听端口替换为实际值）：
iperf -s -u -i 0.5 -p [监听端口] -l 1350
客户端（IP和监听端口替换为实际值）：
iperf -u -c [IP Adress] -p [监听端口] -l 1350  -t 10 -i 0.5 -b 10M
以上命令会从客户端以10Mbps速率向服务器端连续发送10秒数据，并打印出丢包率和网络抖动。

我的解决方法是按照实测的最大丢包率设置FEC，然后断流马上就能恢复。

**Comment by LiR1cky** [comment]
如果对流量不敏感，客户端性能又足够的话建议始终配置FEC。对于时常会抽风的网络情况来说FEC是一贴良药。我现在一般情况下使用FEC(30,15),如果抽风实在严重就改成FEC(5,5).基本上可以非常稳定地使用了。
这几天Youtube能稳定在20000-30000Kbps的状态。

FEC(0,0)在网络情况好的时候确实速度很快且更省流量，但几乎每到晚高峰都得调整，太麻烦了。

**Comment by bettermanbao** [comment]
我现在是FEC(30,10)，rcvwnd sndwnd 256 ，MT7620的路由器，基本跑到7.5Mbps，CPU也接近100%了。

剩下的疑惑就是kcp协议在不开FEC的情况下，可以接受多大丢包率还能正常工作？ @xtaci

**Comment by xtaci** [comment]
默认的kcp协议，丢一次包，退让一次。丢的越多等得越长，这个是必须做的退让。 假如30s超时，rtt*  (1+2 + 4 + 8... ) > 30s就是断线时间。

**Comment by bettermanbao** [comment]
@xtaci 不知道作者是否有条件测试一下kcp协议在固定带宽和延时下，比如10Mbps, 200ms。丢包率对传输速度的影响。很感兴趣kcp在丢包率大于多少后，速度会急剧下降，甚至无法创建连接。

**Comment by linhua55** [comment]
@bettermanbao 
可以先测试一下`断流`是不是ISP的问题。
https://github.com/xtaci/kcptun/issues/228#issuecomment-264730013
https://github.com/xtaci/kcptun/issues/228#issuecomment-266687703

**Comment by bettermanbao** [comment]
我这边其实不是断流，确切的描述应该是全局UDP丢包率突然变大到30%。而且这个变大会影响到所有UDP流量，和目标地址，端口等都没关系。但TCP不受影响。
结论是刚才用iperf在2台VPS上和本地主路由上实测的，猜测可能ISP的路由在处理能力不够时，会按照一定比例对UDP进行丢包。

**Comment by xtaci** [comment]
正常的,UDP本来就是二等公民。比TCP丢包高10倍很正常。

**Comment by baggiogogo** [comment]
介个赶脚是QOS，触及了QOS阈值，要么时间要么空间（带宽），尝试下动态端口或者TC下VPS试试。

**Comment by haruhitamako** [comment]
移动10m宽带，k1用的是你之前的配置，用起来经常断流。总结了一下发现是isp封锁了udp。以前只用ss，通过用dns-forward把upd解析为tcp就能解决断流。用了kcp以后，发现这个办法已经没效果了。最后把mtu改为0后，不再断流，速度在3.5M左右。但是把shdwnd提高到256以上的话，速度最高能7M，可是又会出现断流。重启路由也不能恢复。一段时间后正常

**Comment by bettermanbao** [comment]
@linhua55 我的应该还是附近ISP的路由器出现拥堵的时候，对所有UDP进行30%左右的丢包，造成的断流。这可以理解为QOS的一种。

因为发生30%丢包的时候，我换过VPS，换过端口，丢包率不变。但是TCP流量一切正常。重启kcptun也无法解决，但是把FEC设置为10,3或者30,10以后，立刻能够连上。

**Comment by holywen** [comment]
难怪发现最近用kcptun几乎没法用了。
上海，电信宽带，也 iperf 测试了一下，vps位于sentries
 
直接返回[  4] WARNING: did not receive ack of last datagram after 10 tries.
所有UDP包全部丢失，服务器端iperf -s 无输出。

用tcp模式测试了，是OK。

这种情况怎么处理？

**Comment by xtaci** [comment]
电信就是这样的，重启下光猫就好了 @holywen

**Comment by holywen** [comment]
@xtaci 多谢，回头试试看。
另外搞了一台阿里云的服务器，搭了haproxy+kcptun，也是一样的，udp包被完全封锁。前不久感觉还好的。。。

**Comment by xtaci** [comment]
@holywen 这个事没有办法，就是不想让你用网络。

**Comment by bettermanbao** [comment]
我也是魔都电信+sentris，有点意思。你有没有试过FEC 30,10的配置？
UDP 100%丢包，你哪个区的？

**Comment by holywen** [comment]
@bettermanbao  徐汇的。前几天都还好好的。

**Comment by holywen** [comment]
重启无用啊。。。

**Comment by bettermanbao** [comment]
我这边重启也没用，所以我怀疑是本地的电信的路由遇到流量过大，来不及处理了，所以对所有UDP进行固定比例的丢包。



-------- 原始信息 --------
由： holywen <notifications@github.com>
日期: 17/1/2 18:35 (GMT+08:00)
收件人： xtaci/kcptun <kcptun@noreply.github.com>
抄送： bettermanbao <jackybao_sh@msn.com>, Mention <mention@noreply.github.com>
主题： Re: [xtaci/kcptun] 关于断流的分析及解决方法 (#353)


重启无用啊。。。

―

**Comment by holywen** [comment]
经测试从电信宽带到国内服务器IP的udp包是没有问题的。
就是从国内到国外的udp包被完全丢弃了。

**Comment by lenew** [comment]
魔都电信经常是直接屏蔽UDP一段时间，试验过重新拨号就可以。

**Comment by holywen** [comment]
的确如此。今天再次重启，重新拨号了又可以了

**Comment by JuncoJet** [comment]
楼主妹纸头像好萌啊，求认识

**Comment by xtaci** [comment]
@JuncoJet  IU  https://www.youtube.com/watch?v=_NMQl74qrR8

**Comment by bettermanbao** [comment]
我才是LZ吧。。。哈哈哈哈 @xtaci 

@JuncoJet https://twitter.com/kamisaki_shiori

**Comment by xtaci** [comment]
@bettermanbao 哈哈，尴尬了。

**Comment by klauszou** [comment]
感觉已经可以确定的是中国电信开始大规模的对udp进行屏蔽，目前一台自用在加国的服务器，用GD电信光纤，最近已经基本完全不能使用了，服务器端都是 broken pipe 的log

**Comment by wangyu-** [comment]
针对udp屏蔽和udp qos的方案，把udp流量包装成tcp或者icmp：
https://github.com/wangyu-/udp2raw-tunnel
支持kcptun和finalspeed。openvz可用。

**Comment by blusewang** [comment]
为什么StrongSwanVPN的UDP就不会有这问题？
而KCP就常会断
