### ISSUE TITLE
shadowsocks 安卓版开启kcp后无法解析域名

### ISSUE THREAD

**Issue by waterture** [xtaci/kcptun#354]
vps上运行ss+kcp
家里网络是上海电信，pc上正常工作
魅族mx4，在家用wifi时ss+kcp正常工作。出门用移动4G只开ss不启用kcp正常，启用后无法解析域名
华为p9，无论移动4G还是家里wifi，不启用kcp时ss正常工作，启用kcp后无法解析域名
这是啥问题？有什么解决办法？

**Comment by hyxxsfwy** [comment]
请确认客户端参数是否填写正确

**Comment by whour** [comment]
开启UDP转发，由远程服务器转发UDP解析。检查服务器的DNS设置。

**Comment by TMily** [comment]
KCP不支持UDP包转发 不要开启UDP转发的吧

**Comment by jan4984** [comment]
家里路由器上开一套智能DNS https://github.com/guonaihong/ChinaDNSGo/
