### ISSUE TITLE
mac无法连接，而且日志很奇怪

### ISSUE THREAD

**Issue by saber1024** [xtaci/kcptun#356]
我的配置如下

> {
    "localaddr": ":12949",
    "remoteaddr": "118.193.195.23:8989",
    "key": "122313",
    "crypt": "aes",
    "mode": "fast3",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": true,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}

然后在ss端用了127.0.0.1:12949之后，无法打开网页，但是测试原vps连接可以

我看终端的日志
2016/12/27 16:31:19 stream opened
2016/12/27 16:31:19 stream opened
2016/12/27 16:31:19 stream opened
2016/12/27 16:31:19 stream opened
2016/12/27 16:31:19 stream closed
2016/12/27 16:31:19 stream opened
2016/12/27 16:31:23 stream opened
2016/12/27 16:31:28 stream closed
2016/12/27 16:31:28 stream closed
2016/12/27 16:31:28 stream closed
2016/12/27 16:31:28 stream closed
2016/12/27 16:31:28 stream closed

感觉很奇怪，是哪里配置错误了吗？
version: 20161222
OS:OSX 10.12.2

**Comment by Titzanyic** [comment]
1.检查下服务器版本和客户端版本是否相同。
2.检查服务器端日志，是否收到请求。
3.“测试原 vps 连接可以”，可以理解为使用 shadowsocks 客户端直接连接 vps 的shadowsocks 服务是正常的？如果是这个意思，问题就出现在 kcptun 客户端或者服务端。
4.看到你 shadowsocks 加速端口为 ：8989，本地端口为： 12949，shadowsocks 客户端检查下是否正确。

**Comment by saber1024** [comment]
2016/12/27 16:57:41 version: 20161222
2016/12/27 16:57:41 listening on: 127.0.0.1:12949
2016/12/27 16:57:41 target: 118.193.195.23:8989
2016/12/27 16:57:41 encryption: aes
2016/12/27 16:57:41 nodelay parameters: 1 10 2 1
2016/12/27 16:57:41 sndwnd: 1024 rcvwnd: 1024
2016/12/27 16:57:41 compression: true
2016/12/27 16:57:41 mtu: 1350
2016/12/27 16:57:41 datashard: 10 parityshard: 3
2016/12/27 16:57:41 acknodelay: false
2016/12/27 16:57:41 dscp: 0
2016/12/27 16:57:41 sockbuf: 4194304
2016/12/27 16:57:41 keepalive: 10
2016/12/27 16:57:41 snmplog:
2016/12/27 16:57:41 snmpperiod: 60

服务器端似乎并未收到请求

我的服务器端配置如下

> {
    "listen": "127.0.0.1:12949",
    "target": "118.193.195.23:8989",
    "key": "122313",
    "crypt": "aes",
    "mode": "fast3",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}

而ss的配置是127.0.0.1:12949
所以不太明白问题出在哪里

**Comment by lizongzeshunshun** [comment]
服务端
"listen":"127.0.0.1:12949" 改为
"listen":"0.0.0.0:12949"
target可以改成127.0.0.1（你这样也没错）

**Comment by saber1024** [comment]
> 服务端
"listen":"127.0.0.1:12949" 改为
"listen":"0.0.0.0:12949"
target可以改成127.0.0.1（你这样也没错）

十分感谢您的回复
已经修改可是问题依旧，能否帮忙看看文件的配置呢
https://github.com/saber1024/kcptun-windows-amd64-20161222

**Comment by codingwen** [comment]
服务端配错了，listen是指监听来自kcptun的端口，而target是指发到ss处理

**Comment by saber1024** [comment]
> 服务端配错了，listen是指监听来自kcptun的端口，而target是指发到ss处理

请问您能帮我修改一下吗？十分需要这个
https://github.com/saber1024/kcptun-windows-amd64-20161222

**Comment by guliujian** [comment]
client应该连server的8888啊连8989什么鬼

**Comment by lizongzeshunshun** [comment]
# Client
```
{
"localaddr": ":12949",
"remoteaddr": "118.193.195.23:12949",
"key": "122313",
"crypt": "aes",
"mode": "fast3",
"conn": 1,
"autoexpire": 60,
"mtu": 1350,
"sndwnd": 1024,
"rcvwnd": 1024,
"datashard": 10,
"parityshard": 3,
"dscp": 0,
"nocomp": false,
"acknodelay": true,
"nodelay": 0,
"interval": 20,
"resend": 2,
"nc": 1,
"sockbuf": 4194304,
"keepalive": 10
}
```

# Server
```
{
"listen": "0.0.0.0:12949",
"target": "127.0.0.1:8989",
"key": "122313",
"crypt": "aes",
"mode": "fast3",
"mtu": 1350,
"sndwnd": 1024,
"rcvwnd": 1024,
"datashard": 10,
"parityshard": 3,
"dscp": 0,
"nocomp": false,
"acknodelay": false,
"nodelay": 0,
"interval": 20,
"resend": 2,
"nc": 1,
"sockbuf": 4194304,
"keepalive": 10
}
```

# Shadowsocks(Server)

127.0.0.1:8989

# Shadowsocks(client)

127.0.0.1:12949


以上配置试一下

**Comment by saber1024** [comment]
@lizongzeshunshun  还是不行，我截了2边的图给你看
[归档.zip](https://github.com/xtaci/kcptun/files/675063/default.zip)

**Comment by saber1024** [comment]
@xtaci
求帮助

**Comment by xtaci** [comment]
很简单啊， A连B,B连C, C连D,D连E，每个环节都通了就通了啊。

**Comment by lizongzeshunshun** [comment]
请注意服务器的target

**Comment by codingwen** [comment]
服务端这里
```
"listen": "127.0.0.1:12949",
"target": "118.193.195.23:8989",
```
1. 要确定`118.193.195.23:8989`这个地址的ss运行的是好的
2. kcptun监听配成`"listen": ":12949"`就可以了

客户端这里
```
"localaddr": ":12949",
"remoteaddr": "118.193.195.23:12949",
```

`remoteaddr`没错，
`localaddr`配置的端口确定没被占用

最后要注意的是客户端上的ss配置中的`server`和`server_port`配置成本地kcptun的`localaddr`的值，而ss的`local_port`不必变更

以你现在的配置为例，运行之后，查看一下客户端的`12949`端口使用情况，对应的IP是127.0.0.1还是0.0.0.0之类，对应配置到ss配置文件中去
