### ISSUE TITLE
可否考虑引入Google提交的TCP BBR算法来改善断流问题？

### ISSUE THREAD

**Issue by chwilley** [xtaci/kcptun#357]
如题。
Kcptun的优势很明显，但在实际使用中的断流问题暂时无解，这可能是设计思路和算法层面的问题。
而TCP BBR几乎是不断流的。所以请考虑将两者结合起来应用，能取长补短那是最好。

**Comment by one360** [comment]
两者不是一回事，kcp是对udp的优化，bbr是针对tcp的优化。

**Comment by xtaci** [comment]
还没看bbr算法，算法调整太费时费力了，一个参数可能调一个月才能调好。
慢慢来吧。

**Comment by choicky** [comment]
bbr的确很牛，直连ss的情况下，bbr提速好几倍。但kcptun能提速几十倍……

**Comment by kmahyyg** [comment]
不行，bbr是拥堵算法，kcp是优化发包。
建议详细了解相关资料后再开issue.

2016年12月29日 00:12，"Choicky ZHOU" <notifications@github.com>写道：

**Comment by whour** [comment]
这个服务器内核要在4.9+ 我等OpenVZ就不妄想了。

**Comment by fiercebead** [comment]
用过几天bbr的表示还是kcptun更牛一些，bbr经常出现在某些时段只能跑到1-4mbps的情况，而kcptun具有起步快、爆发力强等多种优点
