### ISSUE TITLE
为啥手机用公司的网络服务端就会broken pipe

### ISSUE THREAD

**Issue by jiawei-zheng** [xtaci/kcptun#359]
用自己的流量可以正常使用，但用公司的wifi就会broken pipe，无法访问，参数如下：

> {
    "listen": ":10241",
    "target": "127.0.0.1:5288",
    "key": "test",
    "crypt": "aes-128",
    "mode": "manual",
    "mtu":1400,
    "sndwnd":2048,
    "rcvwnd": 2048,
    "datashard": 0,
    "parityshard": 0,
    "dscp": 0,
    "nocomp": true,
    "nodelay": 1,
    "interval": 500,
    "resend": 0,
    "nc": 1,
    "acknodelay":false,
    "autoexpire":300
}

客户端参数：
> -mode manual -nodelay 1 -resend 0 -nc 1 -interval 500 -dscp 0 -nocomp -crypt aes-128 -mtu 1400 -datashard 0 -parityshard 0 -key test -sndwnd 256 -rcvwnd 2048 -acknodelay false

**Comment by alex43211** [comment]
你公司wifi什么方式接入的？是不是802.1x的

**Comment by jiawei-zheng** [comment]
@alex43211 不是，就普通的免认证的
