### ISSUE TITLE
Please provide --keyfile option

### ISSUE THREAD

**Issue by starius** [xtaci/kcptun#363]
All users on a system can see a key specified in command line arguments (e.g., by using `ps aux`). I want to create a file accessible to the owner only and to put the key there. Then other users of the system won't steal the key from command line arguments.

Please provide an option to specify the key file instead of key itself. Suggested name for the option: `--keyfile`.

**Comment by lcdtyph** [comment]
You can put the key into the configure file, and use -c to load it.

**Comment by xtaci** [comment]
also , you can specify with environment variable $KCPTUN_KEY

**Comment by starius** [comment]
Environment variable is safer than a command line argument, but it is still not ideal for security, because it is easy to leak it.

I am almost happy with the configure file, but I can't find the description of its schema and the example of it. Can you put the example of config to git, please?

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20160830  examples
