### ISSUE TITLE
客户端和服务器 都是stream opened  closed ，服务器端口异常？

### ISSUE THREAD

**Issue by wulongji2016** [xtaci/kcptun#364]
SS 配置成了服务器地址：0.0.0.0 
但是客户端和服务器，都打开和关闭连接如下，无法打开网页。
1） 如果配合SS使用，目前如何排除问题？
/kcptun# netstat -anp|grep 8088
没有返回任何结果，是不是端口没有打开？

2）请问，如果单独加速使用KCPTUN ，如何设置？
服务器配置完毕：输出日志如下：

2017/01/02 23:07:07 version: 20161222
2017/01/02 23:07:07 listening on: 194.165.3.--:8088
2017/01/02 23:07:07 target: 127.0.0.1:8888
2017/01/02 23:07:07 encryption: aes
2017/01/02 23:07:07 nodelay parameters: 1 20 2 1
2017/01/02 23:07:07 sndwnd: 1024 rcvwnd: 1024
2017/01/02 23:07:07 compression: true
2017/01/02 23:07:07 mtu: 1350
2017/01/02 23:07:07 datashard: 10 parityshard: 3
2017/01/02 23:07:07 acknodelay: false
2017/01/02 23:07:07 dscp: 0
2017/01/02 23:07:07 sockbuf: 4194304
2017/01/02 23:07:07 keepalive: 10
2017/01/02 23:07:07 snmplog: 
2017/01/02 23:07:07 snmpperiod: 60
2017/01/02 23:07:28 remote address: 42.101.0.---:28097
2017/01/02 23:08:07 stream opened
2017/01/02 23:08:07 stream closed
2017/01/02 23:08:24 stream opened
2017/01/02 23:08:24 stream closed
2017/01/02 23:08:24 stream opened

客户端输出日志：
2017/01/02 16:07:21 version: 20161222
2017/01/02 16:07:21 listening on: [::]:12948
2017/01/02 16:07:21 encryption: aes
2017/01/02 16:07:21 nodelay parameters: 0 40 0 0
2017/01/02 16:07:21 remote address: 194.165.3.---:8088
2017/01/02 16:07:21 sndwnd: 128 rcvwnd: 1024
2017/01/02 16:07:21 compression: true
2017/01/02 16:07:21 mtu: 1350
2017/01/02 16:07:21 datashard: 10 parityshard: 3
2017/01/02 16:07:21 acknodelay: false
2017/01/02 16:07:21 dscp: 0
2017/01/02 16:07:21 sockbuf: 4194304
2017/01/02 16:07:21 keepalive: 10
2017/01/02 16:07:21 conn: 1
2017/01/02 16:07:21 autoexpire: 0
2017/01/02 16:07:21 snmplog: 
2017/01/02 16:07:21 snmpperiod: 60
2017/01/02 16:08:11 stream opened
2017/01/02 16:08:11 stream closed

**Comment by lizongzeshunshun** [comment]
1)请确认ss服务器监听在**端口8888**。
2)kcptun无法单独用作代理，它只是一个加速工具。

**Comment by wulongji2016** [comment]
@lizongzeshunshun 

SS 正常可以使用，说明8888端口没有问题吧？ netstat -anp|grep 8888 显示0.0.0.0 在监听8888端口（TCP和UDP）

**Comment by wulongji2016** [comment]
@lizongzeshunshun 

@sasha6050:~# netstat -anp|grep 8888
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      6988/python                         
tcp        0      0 194.165.3.---:8888       42.101.0.230:26444      TIME_WAIT   -                                   
tcp        0      0 194.165.3.---:8888       42.101.0.230:26452      ESTABLISHED 6988/python                         
tcp        0      0 127.0.0.1:8888          127.0.0.1:58645         TIME_WAIT   -                                   
udp        0      0 0.0.0.0:8888            0.0.0.0:*                           6988/python                         
root@sasha6050:~# netstat -anp|grep 8088
udp        0      0 194.165.3.---:8088       0.0.0.0:*                           11784/server  

麻烦看一下，什么问题？
