### ISSUE TITLE
又没的玩了，Linode运营商把youtbe什么屏蔽了

### ISSUE THREAD

**Issue by JuncoJet** [xtaci/kcptun#366]
![](https://pbs.twimg.com/media/C1NVHjmUoAASLaG.jpg)
话说有没人也是这样的问题？

**Comment by JuncoJet** [comment]
![](https://pbs.twimg.com/media/C1NZoXDUAAA1StM.jpg)
好吧 现在又正常了，而且速度更快。

**Comment by JuncoJet** [comment]
不过确实有点问题 需要很长时间才能连上
有大神帮看看么？ ![](https://pbs.twimg.com/media/C1NemIzUkAAJQCh.jpg)

**Comment by xtaci** [comment]
你这是服务器端的问题吧，是不是文件数开的不够

**Comment by JuncoJet** [comment]
好的 我检查下

**Comment by JuncoJet** [comment]
```
Broken pipe产生的原因通常是当管道读端没有在读，而管道的写端继续有线程在写，就会造成管道中断。
```
然后我把默默的运行了3个KCPTun改成了一个，估计就是这个原因

**Comment by xtaci** [comment]
任何时候都不需要开多个

**Comment by JuncoJet** [comment]
嗯 但如果要提供不同的加密算法就存在多开了啊 
```
server->tunnel1(tea)->client1
         ->tunnel2(rc4)->client2
```

**Comment by xtaci** [comment]
多个最好不要同时在一台服务器上用，会互相抢带宽。
