### ISSUE TITLE
默认fast是不是太激进

### ISSUE THREAD

**Issue by Jimmy-Z** [xtaci/kcptun#367]
这帖主要是想讨论, 不是觉得有问题

昨天下午刚发现这东西, 架起来速度好到不敢相信, 默认设置, 服务器是个便宜破VPS, 用3proxy起SOCKS, youtube 4K毫无压力, speedtest.net几乎跑满百兆, 不过fast.com只有30~40M.

晚上速度不行了, 不过youtube 1080p仍然很流畅, Chrome点击下载速度是1MB/s多一点, 比之前我手上最快的线路要快一倍.

但是今早速度还没有恢复就不太好理解了, 感觉是受到了电信的惩罚?

粗略观测了一下, 服务器端放大大约有6~7倍, 默认FEC是10:3, 也就是说放大里面实际上KPC占了大头.

客户端输入到输出是大约两倍多一点, 也就是粗略估计丢包率七成... 我现在主要考虑的反而是调整KPC参数来限制速度避免被惩罚了.

**Comment by xtaci** [comment]
窗口调小一半

**Comment by Jimmy-Z** [comment]
我试了一下连续下载文件, 大约20分钟之后电信完全切换了我的UDP, 而我并没有跑满百兆
![image](https://cloud.githubusercontent.com/assets/85773/21631033/b6c93942-d271-11e6-8c68-1a44de6bb0b9.png)

**Comment by haruhitamako** [comment]
可以尝试mtu调成256以下，移动宽带的只有调成0才不会那么容易被限制udp

**Comment by Jimmy-Z** [comment]
MTU 0是什么玩法？

**Comment by alex43211** [comment]
0肯定不信吧
