### ISSUE TITLE
不同版本kcptun加速效果竟不相同？

### ISSUE THREAD

**Issue by colalan** [xtaci/kcptun#368]
使用了支持MIPS32后发布的三个版本v20161222的，v20161207和v20161202，参数不变情况下，却是v20161207个预发布的版本，加速效果最好。这是什么原因呢？
其他两个版本YT下缓存很不平稳，在0s和4s跳动，而1207个预发布版确能稳定在60s以上，1080p秒开流畅。

**Comment by xtaci** [comment]
嗯，这是权衡， 你可以尝试 -resend 1

**Comment by Jimmy-Z** [comment]
猜: 默认参数不一样了?

**Comment by xtaci** [comment]
为了让各个参数调整更有梯度。
