### ISSUE TITLE
发个友情贴，skeepalive 代理服务器存活检测程序

### ISSUE THREAD

**Issue by JuncoJet** [xtaci/kcptun#369]
针对最近出现断流死掉无法复活的情况，特意写的小代码
能够在指定的时间自动检测，服务器连接超时、服务器获取数据异常等情况监控
并重启（这个比较偷懒写了几个bat自己用，你们看着改吧）
https://github.com/JuncoJet/skeepalive

刚写出来，所以Linux、OS X都还没测试，到时候再调整

**Comment by JuncoJet** [comment]
忘了说，这是各种Web/Proxy服务器通用的，都可以用的上

**Comment by Jimmy-Z** [comment]
明白为什么需要这个东西了, 用了一天kcptun, 遇到了三次代理不通杀了client再开就好的情况.

**Comment by xtaci** [comment]
-autoexpire

**Comment by JuncoJet** [comment]
呃，竟然有自带才知道。。

**Comment by Jimmy-Z** [comment]
这个具体是什么意思？

另外
````
   --conn value                  set num of UDP connections to server (default: 1)
   --autoexpire value            set auto expiration time(in seconds) for a single UDP connection, 0 to disable (default: 0)
````
UDP是个connectionless的协议，这里的UDP connection是指什么？

再另外，我加了--autoexpire 5这样的参数运行客户端，启动时的打印里面仍然是`2017/01/06 08:58:13 autoexpire: 0`，没有生效？

**Comment by xtaci** [comment]
udp虽然是connectionless, 但是session是stateful的啊

**Comment by Jimmy-Z** [comment]
UDP本身没有session, 某些使用UDP应用本身有session, 你可能弄混了. UDP也是stateless的. 再退一万步说, session跟connection不能混为一谈.

就这个具体问题来说, 实际上是指KCP connection吧...

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/blob/master/sess.go#L55

**Comment by bash99** [comment]
明天有时间了分享一个好一点杀程序代码，纯bash脚本。

利用pkill命令cmdline的匹配，可以应对多个server_linux进程的情况。

**Comment by bash99** [comment]
@JuncoJet 
基本上是这个样子，因为我有好几台vps，域名弄成gw1,gw2,gw3这样的，然后启动server_linux64 -r gw1 .... 这么启动，于是可以用 pkill -f 去干掉对应的。
重启时间写在外面，大致是35秒测一次，25秒后重启给10秒建立session时间。然后依靠cow/meow的负载均衡去调配（它们会把挂掉的服务器移出列表，但是会隔段时间重试）。也可以上haproxy这种东西。

#!/bin/bash

for i in 1 2 3 ; do  
        PROXY_OK=`curl --connect-timeout 5 -m 8 --socks5-hostname 127.0.0.1:1294$i -s https://www.google.com/ncr | grep "google.com"`
        if [ "$PROXY_OK" = "" ]
        then
           pkill -f "client_linux_amd64 -r gw$i"
        fi
done

**Comment by lijijordan** [comment]
haproxy 不支持 udp的负载均衡吧
