### ISSUE TITLE
老兄你真的太勤奋了~~ 天天都在更新

### ISSUE THREAD

**Issue by cuteribs** [xtaci/kcptun#37]
当然我不是这么无聊发个issue不是专门来赞你.

而是要顺便问问有没有人转成.Net的kcp-go库和kcptun? 最好是C#的.

最后还是感谢作者的努力, 让我看youtube从900 kbps变成20000kbps.

**Comment by xtaci** [comment]
https://github.com/limpo1989/kcp-csharp  有个这个，但是肯定没有go版本的好，我做了些改动，kcp协议中修正了原有协议对fastack的过激判断，以及增加了fast retransmit. 可以考虑在此基础上修改，或者直接使用go语言的版本。

**Comment by cuteribs** [comment]
go编译出来文件比较大. 以后想在openwrt里跑可能不太容易. 有c#版方便改成比较友好的gui版本.

我现在把kcptun集成到我的docker镜像里跑, 让kcp容器和ss容器协作科学高速上网. 刚才测试发现kcp+dante 要比kcp+ss慢7倍. 不知道是不是dante的性能问题. 我会再试试kcp+v2ray怎么样 :)

**Comment by xtaci** [comment]
dante很弱，可以考虑3proxy

**Comment by cuteribs** [comment]
我之前用hyper-v虚拟ubuntu测试 10g虚拟网速下 v2ray可以跑出8g左右, ss才3g. 不过实际使用中两者差别不大, 而且v2ray不太稳定.

两者加上kcp刚测试 ss比v2ray慢10%不到. 晚上回家用电信200M宽带再试试看.

3proxy我试试看

**Comment by xtaci** [comment]
200M可以适当调大 -sndwnd -rcvwnd

**Comment by cuteribs** [comment]
嗯. 我服务端设的 2048 2048, 客户端设的 256 2048.
按你readme上说的设置的

**Comment by cuteribs** [comment]
kcp-server: Text file busy

在docker里有时候运行报这个错, 再运行一次就可以了. 奇怪

**Comment by bettermanbao** [comment]
@cuteribs openwrt我跑过，结果非常不尽如人意。mt7620的路由，满载也只能跑到2Mbps。
你有兴趣可以试试我编译好的bin。 https://github.com/bettermanbao/openwrt-kcptun/releases

**Comment by cuteribs** [comment]
@bettermanbao 肯定要x64环境下跑才合适, mips/arm能力还是太有限.

**Comment by xtaci** [comment]
@cuteribs 👍    能做个kcptun+xxx +xxx + xxx这种image就很好用了

**Comment by cuteribs** [comment]
@xtaci https://hub.docker.com/r/cuteribs/dsm-ubuntu1604/ 我做的是这个. 最初是给群晖系统里用的, 后来主要用在vps上.

**Comment by cuteribs** [comment]
今天去fast.com测试了下, 我家电信200M, 直连1.9mbps, 单ss连32mbps, kcp+ss连77mbps, kcp(xor)+3proxy连35-50mbps(不稳定), kcp(none)+3proxy连 68mbps也不是很稳定.

**Comment by xtaci** [comment]
一直用的aes

**Comment by cuteribs** [comment]
@xtaci aes太慢了

**Comment by xtaci** [comment]
xor/none都不算加密

**Comment by aghu1979** [comment]
> 
xtaci commented on 21 Jun • edited
@cuteribs :+1: 能做个kcptun+xxx +xxx + xxx这种image就很好用了

PS： https://hub.docker.com/r/xtaci/kcptun/ offical image

> 

@xtaci  @cuteribs  菜鸟请问Docker或者里面如何设置KCP和路由的SS配合使用？目前路由同时加载SS和KCP，经常报错，但是PC端的KCPTUN很稳定，想让黑裙或者PC提供KCP服务，路由提供SS服务。
SS服务器1.2.3.4:123
KCP加速端口999
路由IP 192.168.1.1
SSPC1 IP  192.168.1.2
普通PC2 IP 192.168.1.9


PC1的KCP正常填写，路由的SS地址填写PC的IP和端口不行-_-

临时的解决办法是关闭路由的SS，完全由PC1提供SS和KCPTUN，然后给PC2添加代理，让所有PC2的流量走PC1 192.168.1.2:1080，但是这样所有的流量要先过SSPC1，正常的网站打开就很慢。

**Comment by VNY0920** [comment]
@cuteribs 
能否告知你200M电信宽带的kcptun配置？谢谢！

我的200M宽带，看youtube最多只能18mbps。
目前的配置：
路由器华硕AC88U，VPS是linode北美 一个月10刀的，安装了ssr。
kcptun 服务器端配置如下：
{
    "listen": ":PORT",
    "target": "127.0.0.1:port",
    "key": "KEY",
    "crypt": "aes-128",
    "mode": "fast2",
    "mtu":1400,
    "sndwnd":2048,
    "rcvwnd":2048,
    "nocomp":false,
	"dscp":46
}

客户端路由器配置如下：
--crypt aes-128 --key KEY --mtu 1400 --sndwnd 256 --rcvwnd 2048 --mode fast2 --dscp 46
