### ISSUE TITLE
跨国游戏加速是否可行？降低延迟和网络拥堵的难题

### ISSUE THREAD

**Issue by wulongji2016** [xtaci/kcptun#370]
理论上光纤的传输信号的延迟和距离成正比，还得加上中间节点路由器等的延迟。
一般从大陆到美国西海岸180-200ms延迟。
到日本70-150ms延迟，到香港交近50-100ms之间。
到欧洲英国250-350ms 到德国200-350ms ,
这是直连线路的一般延迟数据。联通 电信 移动宽带数据略有差距。

一般的游戏延迟要求 不超过 80-100ms 左右，超过100ms 卡顿就比较明显了。150-200ms 基本卡的很厉害。
在网络丢包的情况下，TCP三次握手会提高延迟时间，普通TCP的加速，一般多倍发包，在丢包明显情况下，效果应该不错，但是延迟的极限就是物理线路所造成的了。这也是锐速单边加速的原理之一。（另外一个就是就是TCP算法的优化）

我为了连接到俄罗斯比较流畅，搜索了很多服务器提供商，总算是找到俄罗斯和亚洲直连的线路了。但是大陆到俄罗斯欧洲部分的延迟依然在200ms 左右，比通过欧洲绕道的350低了一些，但是离游戏流畅不卡顿的100ms以下还是很大距离。

UDP无需三次握手，理论上可以降低延迟到TCP的一半以上，不知道实际情况如何？ 
Kcptun 有个项目是游戏加速服务器，不知道服务器效果如何？
UDP封堵的很严重，是否有其他方案来实现降低延迟的呢？

网络拥堵情况下，多倍发包有点耍流氓的味道，是否有多线程发包，或者类似的方案，不增加发包总体数据量的情况下，同时多连接发包的方案（类似多线程下载的道理）？

**Comment by wulongji2016** [comment]
木有人感兴趣，或者知道相关情况的么？

**Comment by xtaci** [comment]
光速不可超越。

**Comment by wulongji2016** [comment]
@xtaci 听说国家网络发展规划里面，提到了国际出口宽带提速很多（2020年），不知道是否能实现。提高国际出口带宽才是解决拥堵的根本办法。目前的宽带加速都是有点流氓性质，牺牲了其他不用加速人的带宽。

和其他国家建立直连的光纤才是降低延迟的正解。 UDP加速，网上说，理论上可以降低到50%的延迟，实际是这样么？或者怎么自己检测和对比一下结果？

**Comment by xtaci** [comment]
电信国际访问丢包率40%以上

**Comment by wulongji2016** [comment]
@ 是否能问一下，1）KCPTUN的开发的初衷是什么啊？ 爱好？ 还其他原因？
2）是否有考虑，加入TCP加速的方案到软件中，用户可以在UDP被封地区使用TCP加速 ？

我有几个国外服务器，现在打算再国内也买一个服务器，毕竟目前没有很好的解决跨国延迟和拥堵的办法。

听说，Google的TCP BBR拥塞控制算法 是单边加速的，效果理论上不错。
有什么TCP开源加速方案么？ 单边的或双边的，谢谢各位了

**Comment by xtaci** [comment]
开发的初衷是为了测试kcp协议，提供一个简易的，可以调参数的命令行工具做试验， 最终应用到网络游戏的通信（已经用于我们的游戏）。

**Comment by fiercebead** [comment]
国内奇葩的出国网络质量应该不是纯粹靠技术能解决的，你如果在日本基本上就能稳定的玩美服欧服，但如果在国内就算连香港都无法保证稳定。
我觉得墙的存在造成了人们对国外访问的需求严重下降，你应该明白有很多人是不翻墙的，所以我认为国内的ISP也根本不注重民用网络的出国质量，甚至有可能故意劣化。

**Comment by wulongji2016** [comment]
@fiercebead 故意恶化，这点的确有可能，连接日本和香港都是直线连接的，实际延迟那么大，还不稳定。肯定是有写小动作的的。

**Comment by gyf19** [comment]
@xtaci  游戏端是 libkcp 库吗？     服务端可以压到多少连接数？    有没有开启fec？

**Comment by xtaci** [comment]
@gyf19 服务端最好单独网关处理，cpu耗用主要和队列大小有关，几千个连接没问题。 
libkcp支持fec，但不支持加密和smux

**Comment by Remonli** [comment]
国际链路故意劣化很早就开始了吧

**Comment by wxlg1117** [comment]
电信上海 直连线路的一般延迟数据一般从大陆到美国西海岸130-150ms延迟。
到日本45-65ms延迟;
以前链路没爆炸的时候

**Comment by testcaoy7** [comment]
很多时候线路不是直连的，比如普通电信（非国际精品网）到香港是绕的美国
