### ISSUE TITLE
国内业务系统，一个server 多个不同运营商，宽带或3G4G上网卡，提速方案

### ISSUE THREAD

**Issue by chmis8000** [xtaci/kcptun#372]
标题大了，我想国内加速 C/S应用。
服务端：kcptuns -t "127.0.0.1:7789" -crypt none -key "test1" -l :7790
各个客户端都：kcptunc -r "xxx.xxx.xxx.xxx:7790" -key "test1"  -crypt none -l :7790
不加密，默认的fast方案+压缩，是否能够通用，比不用kcptun有更好的速度，或者保证C端稳定5MB以内速度时充分利用5M带宽？

**Comment by chmis8000** [comment]
假如不丢包 ，不加密，默认的fast方案+压缩，用比不用是否更占用服务器带宽？ FEC默认是有冗余

**Comment by wulongji2016** [comment]
实际情况都是有丢包的，UDP应该在丢包的时候，需要重新发送数据来把丢包的补回来。
另外UDP 是否断流是先考虑的，否则任何配置都是徒劳的。

**Comment by alex43211** [comment]
我电信50M宽带，默认方案时用kcptun的下载速度大概在2MB/s，供你参考

**Comment by chmis8000** [comment]
@alex43211  那速度不行啊，理论应该5MB/s ，是因为默认 10,2的多发了包？ 难道不适合国内用？

**Comment by chmis8000** [comment]
kcptun目前问题还是参数必须手工调整，无法自动化，导致无法充分发挥特性，希望作者适度自动化一下

**Comment by wxyzh** [comment]
我觉得，lz是不是可以试试BBR

**Comment by alex43211** [comment]
@chmis8000 不是啊，国内对国外。国内就是标称50M带宽的速度。下载越6MB/s左右

**Comment by chmis8000** [comment]
@wxyzh  可惜，Linux方案的 都用不了，包括  google bbr 。只用windows系统
