### ISSUE TITLE
动态fec 支持

### ISSUE THREAD

**Issue by notedit** [xtaci/kcptun#376]
对fec 没有太多了解, 看到这篇文章  http://www.ucpaas.com/news/201611/83.html

动态丢包补偿   kcp中的fec 是否可以考虑这种方案

**Comment by xtaci** [comment]
动态fec需要一个独立的信道做控制信号交换， 比较复杂，效果不一定那么明显。

**Comment by notedit** [comment]
我看到webrtc 里是这么做的  需要rctp配合

**Comment by bettermanbao** [comment]
在返回的ack信号中加入一些信息，是否可行？

**Comment by notedit** [comment]
感觉不只是这么简单  还有流量估算一些列东西    

webrtc 引入这个是要适配各种网络    上层的控制逻辑比较多

**Comment by xtaci** [comment]
@bettermanbao https://github.com/xtaci/kcptun/releases/tag/v20170114 试一下这个，观察下repeatsegs

**Comment by bettermanbao** [comment]
@xtaci 看附件，mode fast, fec 10:3。黄色数据是之前的版本，绿色的是新版本。有改善。
[kcptun_snmp_log.xlsx](https://github.com/xtaci/kcptun/files/705879/kcptun_snmp_log.xlsx)

**Comment by xtaci** [comment]
@bettermanbao 麻烦再下载测试一次

**Comment by xtaci** [comment]
@notedit 对，需要单独的控制信道。不是那么简单就能做好的。花一年时间估计行。

**Comment by bettermanbao** [comment]
@xtaxi 最近一次更新导致repeatseg变多，参考附件。黄色的是之前的版本，绿色的是前一次更新，蓝色是最新的更新。

[kcptun_snmp_log.xlsx](https://github.com/xtaci/kcptun/files/705908/kcptun_snmp_log.xlsx)

**Comment by xtaci** [comment]
@bettermanbao 好的，谢谢，看来计时非常重要，会影响重传率。 已上传最新版本，0114版本暂定这样。

**Comment by bettermanbao** [comment]
@xtaci 最新的release你是又改过什么，还是只是撤销了最近一次的更改？
刚测了一下，目前最新的release，repeatsegs/insegs只有8%, fecrecovered/insegs是3.2%。不知道是我网络变好了，还是你又改过什么。

**Comment by xtaci** [comment]
两个同时改动，一个是数据包时钟更加精确（非常重要），一个是初始RTO略微放大了1/8 @bettermanbao

**Comment by baggiogogo** [comment]
低丢包，FEC10/3，约4% 。
![img_0048](https://cloud.githubusercontent.com/assets/21306212/21957955/6e6dfeac-dadd-11e6-8a22-7b76c5aba1b2.PNG)

**Comment by xtaci** [comment]
@baggiogogo 超出预期的效果。

**Comment by notedit** [comment]
我先关掉这个issuse    有计划做的话可以再探讨

**Comment by rufengsuixing** [comment]
如果在kcp包头里加入一个字节的表示本包的fec等级，然后客户端读取这个值进行回包的fec等级设定，SNMP用来进行计算统计fec的等级，是否可行
