### ISSUE TITLE
no such host net.ResolveUDPAddr mac client出现问题？如何解决？

### ISSUE THREAD

**Issue by q673428536** [xtaci/kcptun#377]
2017/01/14 13:19:01 lookup vps on 114.114.114.114:53: no such host
net.ResolveUDPAddr
github.com/xtaci/kcp-go.DialWithOptions
	/Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:916
main.main.func1.1
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:335
main.main.func1
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:387
github.com/urfave/cli.HandleAction
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:259
main.main
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:422
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197
createConn()
main.main.func1.1
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:337
main.main.func1
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:387
github.com/urfave/cli.HandleAction
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:259
main.main
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:422
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197
logout

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/blob/master/.github/ISSUE_TEMPLATE
