### ISSUE TITLE
BufferBloat?RepeatSegs?

### ISSUE THREAD

**Issue by xtaci** [xtaci/kcptun#378]
BufferBloat 问题， RepeatSegs/InSegs 过高，可以在此讨论。
BufferBloat相关资料:
* https://en.wikipedia.org/wiki/Bufferbloat
* http://blog.csdn.net/dog250/article/details/52879457
* http://blog.csdn.net/dog250/article/details/52830576
* http://blog.csdn.net/dog250/article/details/54171687
* http://blog.csdn.net/dog250/article/details/54424751
* http://anagranroberts.blogspot.jp/2011/07/bufferbloat-impact-on-response-time.html

**Comment by bettermanbao** [comment]
响应一下号召，炒鸡慢的罗马尼亚VPS，直连1Mbps左右。

服务器端kcptun开了3个端口，sndwnd都是1024。
内网用4核ARM v7的OrangePi Zero同时连接3个端口，然后做负载均衡。
客户端连到OrangePi，speedtest测速如下。

实际流量消耗大概是2：1，RepeatSegs/InSegs大概在20%。其实我想说的是看着这个速度，已经懒得调整任何参数了，简直碉堡了！感谢作者！

![1543676556](https://cloud.githubusercontent.com/assets/17328315/21972921/e0a69040-dbf7-11e6-937c-d73b846ab608.jpg)

**Comment by xtaci** [comment]
优化了那么久，才发现有效载比不高的真正原因是RTT的抖动，导致误判数据包超时。 在国际链路下，RTT jitter特别明显。

**Comment by bettermanbao** [comment]
那请问BBR算法方面有什么值得借鉴的吗？

**Comment by xtaci** [comment]
没有太多值得借鉴的，实现pacing需要高精度时钟，而这在用户态，而且带GC的语言中，是很难实现的。

**Comment by bettermanbao** [comment]
@wang20150419 用的是最简单的iptables的方法，OrangePi上开3个kcptun，连接服务器上的3个端口，本地监听10085-10087，然后用下面命令把本地10000端口的流量随机分布到10085-10087。内网其他客户端连接OrangePi的10000端口。

iptables -t nat -A PREROUTING -p tcp --dport 10000 -j REDIRECT --to-ports 10085-10087 --random

**Comment by wang20150419** [comment]
@bettermanbao 谢谢！

**Comment by JuncoJet** [comment]
没，最近网络稳了，我最后第三个版本用着都不断= =、
同时小推广一下 https://github.com/JuncoJet/skeepalive 加入负载均衡，当一台服务器不稳是切其他服务器（pac）

**Comment by xtaci** [comment]
@bettermanbao 降低repeatSegs的另一个办法是，增大-interval，比如到40， 非常有效，让其对网络抖动容忍度更高。

**Comment by bettermanbao** [comment]
这么做，丢包重发的间隔就会变大，有比较过对速度影响有多大？




-------- 原始信息 --------
由： xtaci <notifications@github.com>
日期: 17/1/16 18:04 (GMT+08:00)
收件人： xtaci/kcptun <kcptun@noreply.github.com>
抄送： bettermanbao <jackybao_sh@msn.com>, Mention <mention@noreply.github.com>
主题： Re: [xtaci/kcptun] BufferBloat?RepeatSegs? (#378)


@bettermanbao<https://github.com/bettermanbao> 降低repeatSegs的另一个办法是，增大-interval，比如到40， 非常有效，让其对网络抖动容忍度更高。

―

**Comment by xtaci** [comment]
对于视频流，基本没有影响，反而更快。

影响的只是小包，交互式应用。 @bettermanbao

**Comment by notedit** [comment]
计划用你的libkcp 写一个voip的demo 测试一下

**Comment by xtaci** [comment]
@notedit 好，记得反馈体验。

**Comment by bash99** [comment]
Repeat 3648 In 45262 算高吗？
加州vps，ping 大概175ms，丢包率不算高（iperf3 10M，网络好时5%以内）
fast + 12:1 的 data:parity, 窗口256
下载908KB/s左右。

就是还是会碰到上行通，下行全断的情况，触发原因不详，有时连续下载1G也没触发。平均1～2小时一次，时间2～10分钟。

**Comment by xtaci** [comment]
@bash99 8%的repeat率，在高抖动的国际网路下，算好的了。

**Comment by LiR1cky** [comment]
@bash99 你这8%的丢包只是一段时间的统计值，实际网络情况下并非恒定保持这一状态的，会忽高忽低。
12:1宽容度不够，只能应付不到8%的丢包。建议略微提高到8:1或5:1看看还会不会有断流产生。

**Comment by bash99** [comment]
@LiR1cky 断流时似乎下行全断（iperf3 带宽2M测试，服务端有链接信息，但是就卡死了）

@xtaci 另外一个加州vps，ping 230～280之间波动，总体丢包率比上面5%的更好，manual ( 1 80 2 1）+ 19:3 的 data:parity, 窗口256

似乎碰到了最好情况，RepeatSegs:165 -- InSegs:42290，负载率接近74%; 下载速度841KB/s。
而且 FECRecovered:15 FECErrs:0 FECSegs:5768 FECShortShards:143；这时丢包率太低，可能FEC已经没啥意义了。

**Comment by xtaci** [comment]
@bash99 没错，最近才意识到, ping的抖动才是国际带宽慢的关键，低抖动的重传率会低很多。

**Comment by bash99** [comment]
@xtaci 尝试降低 FEC 时到 19:1，（其它仍然是 1 80 2 1），似乎碰到了一个大波动，带宽在下载后期下降到200K
服务器端的  RetransSegs:13859 EarlyRetransSegs:12545 OutSegs:35374 LostSegs:993 ，但是客户端仍然是 RepeatSegs:728 FECRecovered:2 InSegs:21351
这个算是 EarlyRetransSegs 弥补了丢包呢？还是 EarlyRetransSegs 降低了带宽？
因为我是拿本机一个全随机无法压缩的文件做的测试，按说从服务端到再上游没有带宽瓶颈。

**Comment by bettermanbao** [comment]
我用kcptun在路由器上开了个国内中转，然后共享到v2ex上了。
收集几天数据然后跟你们讨论，有人帮忙测一下速吗？
中转地址：https://www.v2ex.com/t/335068

**Comment by xtaci** [comment]
[kcptun-darwin-386-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710271/kcptun-darwin-386-20170117.tar.gz)
[kcptun-darwin-amd64-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710272/kcptun-darwin-amd64-20170117.tar.gz)
[kcptun-freebsd-386-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710273/kcptun-freebsd-386-20170117.tar.gz)
[kcptun-freebsd-amd64-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710274/kcptun-freebsd-amd64-20170117.tar.gz)
[kcptun-linux-386-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710275/kcptun-linux-386-20170117.tar.gz)
[kcptun-linux-amd64-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710276/kcptun-linux-amd64-20170117.tar.gz)
[kcptun-linux-arm-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710277/kcptun-linux-arm-20170117.tar.gz)
[kcptun-linux-mips-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710278/kcptun-linux-mips-20170117.tar.gz)
[kcptun-linux-mipsle-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710279/kcptun-linux-mipsle-20170117.tar.gz)
[kcptun-windows-386-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710281/kcptun-windows-386-20170117.tar.gz)
[kcptun-windows-amd64-20170117.tar.gz](https://github.com/xtaci/kcptun/files/710280/kcptun-windows-amd64-20170117.tar.gz)


@bettermanbao 抽空再测下这个版本，也是对RepeatSegs的优化尝试。

**Comment by bash99** [comment]
@bettermanbao 实测已经被堵爆了，打开google.com/ncr 重定向要 5秒，下载50KB/s。

**Comment by bettermanbao** [comment]
@xtaci 待会儿试试看
@bash99 现在是爆了。。。

**Comment by bash99** [comment]
@bettermanbao 现在又来了一次，下载35秒，384KB/s。（上游是加州vps上某个不可压缩的文件）。

**Comment by bash99** [comment]
@LiR1cky 试了试断流时切到3:3，重启服务端和客户端，仍然连不上。还是被完全断了udp下行啊。

**Comment by linhua55** [comment]
@bash99 
https://github.com/xtaci/kcptun/issues/228#issuecomment-272715363  可以使用TCP，欢迎测试

**Comment by baggiogogo** [comment]
20170117
KCP SNMP:&{BytesSent:293777 BytesReceived:84380867 MaxConn:3 ActiveOpens:4 PassiveOpens:0 CurrEstab:3 InErrs:0 InCsumErrors:119 KCPInErrors:0 InSegs:166625 OutSegs:5177 InBytes:188406703 OutBytes:1161086 RetransSegs:26 FastRetransSegs:0 EarlyRetransSegs:0 LostSegs:26 RepeatSegs:6556 FECRecovered:1062 FECErrs:0 FECSegs:38447 FECShortShards:360}
正常看了两段视频，10/3FEC，interval 30，约4%。

**Comment by xtaci** [comment]
@baggiogogo 终于走对路了。。。。 RTT才是问题的关键啊。。。

**Comment by baggiogogo** [comment]
![img_0049](https://cloud.githubusercontent.com/assets/21306212/22015936/2e323ea8-dcdf-11e6-98e5-5f40c38a8e6a.PNG)
换了一台线路稍差一点的vps，10/3FEC，interval 40，约5%。

**Comment by xtaci** [comment]
不错，我观察到的结果是ping值的稳定性和repeatsegs正相关

**Comment by baggiogogo** [comment]
@bettermanbao
测了差不多就关掉吧，流量是小，万一有人拿去扫爆别人的服务器，收到投诉还是麻烦的。
上回我的ovh莫名其妙直接被删除，问了说我的ip扫爆别人的服务器，申诉了好久，后来查出来是什么ip冒用，给恢复了，但数据全没了。

**Comment by bash99** [comment]
@xtaci 进一步测试了一下，发现我这两台vps都有一个甜区，服务器发包超过这个比例丢包率会从1%上升到5%，这时如果是FEC设高了触发，怎么调整都很难有效。
ping 220～270的德州vps，支持的窗口更大一点，256，最后形成的带宽是840KB左右。
ping 150～170的加州vps，窗口需要设到192，这时各类丢包重传repeat都低到<2%，带宽利用率能到85%，但是总带宽在730KB。

都是最后把FEC设为0了，因为这个窗口下丢包率极低；同时如果设高FEC，造成发包数上升，反而丢包率更高了。

**Comment by xtaci** [comment]
@bash99 感谢各位的测试，如果在低于10%的ping丢包率下，FEC确实可以完全关闭，这样最省流量。
如果需要应对 > 10%的丢包率，建议还是开默认的10，3的FEC

**Comment by bash99** [comment]
@xtaci 忘了说了，德州的interval 是 80，加州的是50，至少在之前的测试下，这个数比缺省值能有效降低 Repeat。

**Comment by notedit** [comment]
@xtaci  quic  这个协议 在一开始有FEC,  在经过很多测试之后 增加FEC并没有带来多大的提升

quic 现在的协议已经把FEC干掉

**Comment by notedit** [comment]
可以借鉴一下 quic,  把kcp 设计成一个更通用的传输协议

**Comment by xtaci** [comment]
@notedit QUIC的FEC是非常简陋的，完全不实用的XOR方式，最多只能应付一个丢包。干掉也好。

**Comment by bettermanbao** [comment]
@baggiogogo 服务器已关
@xtaci 看来新版效果很好，我就不测了哈。另外能否开个tg群，把人心群众拉在一起，也方便讨论。

**Comment by xtaci** [comment]
先在这个贴讨论吧，主要是要控制讨论的质量，不要水了。

**Comment by xtaci** [comment]
我自己测的结果是，基本能控制在10%以内的repeatSegs。至少证明方向是对的。另外在vps的面板上观察到的出入比，更靠近。

**Comment by baggiogogo** [comment]
我的两台，一直都在5%以内，时间从更新一直覆盖到目前，不错。我记得前个版本有一台会到7%。

**Comment by baggiogogo** [comment]
![default](https://cloud.githubusercontent.com/assets/21306212/22025727/8a70acb6-dd09-11e6-827a-5e84657886df.JPG)
正常情况下的CPU负载及内存占用，树2，512/128窗口，10/3FEC，服务器TC到30M。

**Comment by satifanie** [comment]
@baggiogogo 你们都是默认参数吗？为啥我就不能那么彪悍呢，还会断流，
难道人品问题？已升级最新版本，随机端口了。

**Comment by CuminLo** [comment]
@satifanie 端口怎么随机? 我的也没有那么彪悍...

**Comment by bettermanbao** [comment]
@xtaci 测试了17号的版本，反馈一个现象。

Repeat/In的比例在FECShort很低的时候，比如接近0，降低明显，从14%降到4%。但调低ParityShard后，随着FECShort的增加，Repeat/In的比例又会回到10%以上。

应为FECShort的增加就是接收端实际没收到的包变多，发送端必定会重发这些包。但重发包的RTT在算法上是否有bug？会导致重发包重复发送？

**Comment by xtaci** [comment]
rtt计算没有问题，已经滤掉bufferbloat导致的抖动， 只是FEC现在的作用更明显了。
注意，告诉发送方的ACK包也会丢包，这会导致重传，FEC对此也有帮助。

**Comment by baggiogogo** [comment]
@satifanie 
基本是默认参数了，到不是偷懒，是因为这套参数在我的线路ping最低，情况接近理想时整好占用30M带宽，除去连同FEC在内的所有开销，大约20M的有效带宽，而我的上传有20M，搭跳板也整好物尽其用。
先用电脑客户端试试，排除路由性能之类问题，电信线路的话不妨把FEC适当调高点看看能否缓解断流，排查下会否isp有所限制。

**Comment by bettermanbao** [comment]
@xtaci 我有测试了一下，目前强烈感觉Repeat/In的比例和FECShort的正相关性非常强烈。
具体数值你见截图
![repeat](https://cloud.githubusercontent.com/assets/17328315/22051786/a5eb9c22-dd80-11e6-89dd-b82b4d3131bf.png)

**Comment by bettermanbao** [comment]
顺便再问一下，InSegs里面是否包含RepeatSegs?

**Comment by xtaci** [comment]
InSegs是全部，必然包含Repeat

**Comment by bettermanbao** [comment]
@xtaci 另外，我有观察到FEC调低以后，上图绿色的InSegs明显低于黄色的。但是2组数据采集时除了ParityShard从3改到了1，其他参数完全相同。最主要的是Sndwnd都是一样的，是什么造成这种差异的呢？大胆猜测ParityShard是否不占用Sndwnd？？？

**Comment by xtaci** [comment]
没错，ParityShard是独立的，不占用sndwnd

**Comment by bash99** [comment]
@xtaci ParityShard不占用sndwnd我是理解的，但是比如设成5:5的比例，我本来理解是OutSegs会翻倍，但实际情况碰到的是OutSegs翻3～4倍，这是什么原因？
OutSegs变多后，触发更多丢包，于是三种重传发挥作用，占用更多发包（仍然不在窗口内），最后恶性循环？

@baggiogogo 你是联通还是移动线路？我的联通光纤因为要穿承重墙（之前被未知占用），物业通不过而放弃了，被迫用华翼（有线拨号 + 电信网络）。而公司网络上游是二级接入商（主流量仍然是电信）。总之最好也就1M出头，而且浪费严重。倒是另外一个加州的kvm走锐速很快，但是网络不稳定。

**Comment by baggiogogo** [comment]
@bash99
联通的，你这个别挣扎了，肯定是UDP环境恶劣，各种各样的QOS，尝试下上面那个网友的TCP办法。

**Comment by baggiogogo** [comment]
@CuminLo
用iptables，客户端iptable命令翻翻以前的issues，用惯了routeros，命令行实在不记得了。大致思路是客户端出站到kcptun服务端口随机，然后服务端收到这些端口的请求后重定向到kcptun服务端口。
端口改你自己的，autoexpire参数改小，比如10、20、30。这个办法是否有效也完全取决于ISP的策略，只有试试。
服务端命令:iptables -A PREROUTING -p udp -m multiport --dport 18700:19200 -j REDIRECT --to-ports 37372
![default](https://cloud.githubusercontent.com/assets/21306212/22055198/f3da8ee8-dd94-11e6-9a1c-32c03df9e11b.JPG)

**Comment by bash99** [comment]
@xtaci 可能我是昨天晚上调迷糊了记忆有误（也就是为了达到接近带宽，需要OutSegs更多）。

刚才有个典型现象，我把昨天调优完毕的192窗口 关闭FEC的服务端，换成 5:5的FEC，最后带宽从700下降到70KB上下，Repeat/In = 5747/8555，但是看上去FEC还算有效 --- FECRecovered:3425  FECSegs:4295。

@baggiogogo 哎，电信太悲剧了。不过我家里倒是不断流，就是公司老是全断。平均一小时一次。靠自动侦测脚本和meow的fallback机制用另外一台kvm的v2ray顶着。
但是我这个在公司是公开提供的，于是实在忍不住用10T流量的德州vps。

**Comment by satifanie** [comment]
@CuminLo 随机端口也无用。IPtables具体如下：
服务器需要:
iptables -t nat -A PREROUTING -p tcp -m multiport --dport 81:1023 -j REDIRECT --to-ports xxxx
iptables -t nat -A PREROUTING -p udp -m multiport --dport 81:1023 -j REDIRECT --to-ports xxxx

客户端需要：
iptables -t nat -I OUTPUT 1 -d ServerIP -p tcp --dport xxxx -j DNAT --to-destination 104.193.225.91:81-1023 --random
iptables -t nat -I OUTPUT 1 -d ServeriIP -p udp --dport xxxx -j DNAT --to-destination 104.193.225.91:81-1023 --random
实测效果不佳。

**Comment by bettermanbao** [comment]
@hash99 我这边电信UDP断流的时候TCP还是可以连接的，你可以试试2套SS配置文件，一套走kcptun，一套直连。udp断流时自动切换为直连。虽然会慢一些，不过也就是一会时间罢了。这样配置上简单很多。

**Comment by bettermanbao** [comment]
@xtaci 更新一个信息，17号的go 1.8编译的kcptun，在mipsle下已经可以正常开启压缩。不确定是go 1.8的缘故还是snappy的缘故，anyway能用就好了。

顺便请教一下，kcptun在遇到丢包后，会主动降低发送窗口吗？还是发送窗口始终是固定的？

**Comment by xtaci** [comment]
@bettermanbao 只要nc =1 就不会降窗。

**Comment by cjh-github** [comment]
https://github.com/bettermanbao/openwrt-kcptun
有空了更新下openwrt ，最近的几版改进都还没用上呢





在 2017年1月19日 下午2:18，bettermanbao <notifications@github.com>写道：

**Comment by bash99** [comment]
@bettermanbao 我现在脚本级的重启切换倒是基本成熟了，通常用的时候没感觉了。不过现在kcptun越来越火，长期来看怎么防止GFW探测或者QOS还是一个问题。

我这边现在平均40～90秒check一次到google的结果，统计下来，断线应该还是和流量及其特征有关？
晚上只有check流量时不会断，白天单位很多人用时平均30～40分钟断一次。但是如果连续下载，不见得触发断线，能成功下载好几G。

**Comment by bettermanbao** [comment]
@cjh-github 直接这里下载就可以了，mips对应ar71xx，mipsle对应ramips。

**Comment by cjh-github** [comment]
@xtaci @bettermanbao 跑不起来是什么情况

![sp170120_083821](https://cloud.githubusercontent.com/assets/6256701/22131120/e873c292-deeb-11e6-96a2-ad7cf14e5875.png)

**Comment by bettermanbao** [comment]
@cjh-github ar71xx好像是有点问题，我自己用的是ramips的，没有任何问题。
那我来编译一下吧，一会就好。

**Comment by xtaci** [comment]
@bettermanbao  https://github.com/xtaci/kcptun/releases/tag/v20170120 试试

**Comment by bettermanbao** [comment]
晚点试好，告诉你结果。作者你好勤奋呢，给你一个赞！

**Comment by wang20150419** [comment]
-datashard/-parityshard 独立于 mode 吗？

**Comment by baggiogogo** [comment]
简单试了下20170120
KCP SNMP:&{BytesSent:401486 BytesReceived:66977007 MaxConn:3 ActiveOpens:3 PassiveOpens:0 CurrEstab:3 InErrs:0 InCsumErrors:80 KCPInErrors:0 InSegs:148938 OutSegs:4877 InBytes:167543864 OutBytes:1407591 RetransSegs:51 FastRetransSegs:0 EarlyRetransSegs:0 LostSegs:51 RepeatSegs:16392 FECRecovered:103 FECErrs:0 FECSegs:34370 FECShortShards:13}
两台VPS都差不多，都是10%左右，应该是比上一个版本要高一些，但看YOUTUBE感觉很稳，不知是不是目前时段的原因，晚点高峰期再观察观察。

**Comment by xtaci** [comment]
@baggiogogo 是的，平衡了一下

**Comment by wang20150419** [comment]
多一点流量问题不大，关键是要稳定。平时看youtube，会断线。

**Comment by baggiogogo** [comment]
@xtaci 
这就说得通了，辛苦了。

@wang20150419 
排查下瞬时丢包，最简单的办法，看youtube时一直ping主机，当卡或者断线时看看是否ping超时，有时一瞬间会很高很高，甚至超过所设置的FEC能力范围，抽风时很常见，适当调高FEC看看能否缓解。真正遇到丢包丢到一塌糊涂时，切换VPS吧，最好的法子。这还是ISP没有对UDP掣肘的情况。

**Comment by aqaqaqq** [comment]
> 注意，告诉发送方的ACK包也会丢包，这会导致重传，FEC对此也有帮助。

@xtaci V2Ray 使用的 mKCP 有确认包重传的特性，有没有把这个特性合并进来的计划？

**Comment by yydcool** [comment]
> 没有太多值得借鉴的，实现pacing需要高精度时钟，而这在用户态，而且带GC的语言中，是很难实现的。
@xtaci
看起来kcptun现在还没有实现pacing
 为什么不用**tc-fq**实现pacing呢？BBR也是这样做的吧。

> An application can specify a maximum pacing rate using the   SO_MAX_PACING_RATE setsockopt call.  This packet scheduler adds delay  between packets to respect rate limitation set by TCP stack.

所以只要估计出一个socket的throughput，然后调用setsockopt(...,SO_MAX_PACING_RATE,...)

**Comment by ruiruige** [comment]
@bettermanbao

请问您这个多开kcptun 再负载均衡的 是怎么弄的？
能简单说两句吗

**Comment by bettermanbao** [comment]
@ruiruige 
就是开2个kcptun，监听2个本地不同端口。然后用iptables把流量随机分布到这2个端口上。

**Comment by dearneo** [comment]
@bettermanbao 
你的多开是个好方法，不过如果kcptun能直接内部集成就更好了，多开对于没有开发板的人不方便。
最近测试了一下kcptun的--conn参数，发现看视频时流量一般只集中在一个UDP连接上，想了一下可能原因是，针对一个TCP连接，目前的程序是只能跑在一个UDP连接上，而不是随机分布在多个UDP连接上。
如果作者能改进一下就更好了，感觉多个小 流量的 连接会更容易避过某’墙的 ‘审。查/
还有随机化端口等等。。。不过这些功能可能和作者的初衷不太相符，毕竟本项目只是用于加速而非F/Q。
但还是非常感谢作者最近几个版本的优化，感觉目前优化的相当不错了，manual模式 --nodelay 0 --resend 0 --nc 1 --interval 50 参数下服务器重复发包的量已经非常少了，没开FEC的情况下客户端入站的有效载荷率基本在75%以上，但客户端出站始终很高，基本是原始TCP流量的5倍以上，客户端出站的流量应≈原始出站TCP流量+kcp确认包，但5倍感觉还是有点夸张，不知是否还有优化的空间。

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20170301
@bettermanbao 希望测试下这个版本。

**Comment by bettermanbao** [comment]
@xtaci 今天试了下最新版，用几天后再告诉你好坏，谢谢更新。

**Comment by xtaci** [comment]
@bettermanbao 这个版本是发的最纠结的一个，很难说有进步，甚至也许有退步，开始碰到些深层次的平衡问题。。。

**Comment by bettermanbao** [comment]
@xtaci 建议我观察哪些snmp参数来反馈问题？

**Comment by xtaci** [comment]
@bettermanbao 现在暂时还说不上，先直观体验下吧，这个版本不是很有把握。

**Comment by baggiogogo** [comment]
怪不得两天之内如此频繁，辛苦啦。

**Comment by bettermanbao** [comment]
@xtaci 直观体验，0303的版本存在一个缓启动的现象。
speedtest.net测速开始3秒钟，速度只有4Mbps，然后加速到正常值。试了2个不同的vps，client arm和mipsle的版本，都有这个现象。目前不确定是否我的isp有新的qos策略，还是这就是新版的kcptun造成的。

不知道其他人有没有类似情况。

**Comment by baggiogogo** [comment]
@bettermanbao 
没有，或许说没有你说的那么明显，比如总10M，起始7M然后攀升到10M。
换个测速服务器试试？

**Comment by everfly** [comment]
反馈一个可能的BUG，目前不是太确定是否是kcptun的问题，但是替换之后确实不存在对应问题了
使用版本：`kcptun-linux-amd64-20170303.tar.gz`
BUG表现：在bandwagonhost openvz vps上面，内存占用大，尤其表现在播放2k分辨率以上的视频，内存占用由平时的280M上升到400+M，换回`kcptun-linux-amd64-20170221.tar.gz`这个版本之后，内存使用回到正常值

**Comment by bettermanbao** [comment]
有没有人对比过BBR和kcptun？
现在openvz的vps也可以开bbr了，于是试了一下。speedtest测出的极速比kcptun快，但是实际使用中稳定性还是不如kcptun。

**Comment by ruiruige** [comment]
@bettermanbao  openvz的BBR能指导一下吗。。。 不是要升级内核吗

**Comment by bettermanbao** [comment]
@ruiruige 
用user mode linux在openvz下再虚拟一个4.9内核的linux，并启动。
https://www.91yun.org/archives/4996

**Comment by baggiogogo** [comment]
TCP是为流量设计的（每秒内可以传输多少KB的数据），讲究的是充分利用带宽。而 KCP是为流速设计的（单个数据包从一端发送到一端需要多少时间），以10%-20%带宽浪费的代价换取了比 TCP快30%-40%的传输速度。TCP信道是一条流速很慢，但每秒流量很大的大运河，而KCP是水流湍急的小激流。
以上引用自skywind3000

已下载为目的的话可能bbr更适合，但YouTube或者游戏...........
开vps之前一般都会去拉拉test.bin，好些个服务器速度很牛，但真到看个视频那就两说了，这个经历可能好多人有，这个我想还是一定程度说明两者区别。

**Comment by xtaci** [comment]
@bettermanbao 太正常了，只要不丢包，低抖动，tcp的基本随便那个算法都好过kcp。 可惜现实世界是高丢包，高抖动。

**Comment by LiR1cky** [comment]
确实，如果是看视频为主的话，用fast.com的参考更为准确，或许因为它是由netflix推出的有关。
具体可参考下文：
http://techblog.netflix.com/2016/08/building-fastcom.html

**Comment by baggiogogo** [comment]
这几天开了那个著名的2.5玩，因为流量少后面关了FEC，发现现在优化的真的可以，进出比很接近了，以前我记得FEC关闭并且很温柔的参数下，怎么着也得1.3倍左右。
![default](https://cloud.githubusercontent.com/assets/21306212/23802073/2b9961da-05ed-11e7-9026-34d65cd19531.JPG)
前两天10/3的FEC,后两天是关闭的。

**Comment by dearneo** [comment]
@bettermanbao 
这几天测试了一下你之前说的多开客户端方案，实测速度和用单个客户端的multiple connections没什么区别，唯一的区别就是从服务器发过来udp包的端口从一个变成了多个。
对于单个的TCP连接，比如yt的视频流，速度上限依然是由单个客户端设置的rcvwnd决定，无法叠加成rcvwnd*客户端个数 这样的速度，只有开多个yt视频速度才叠加。可能和iptables的转发机制有关？这和单个客户端多开UDP连接然后一个TCP连接只能跑在一个UDP连接上速度上没区别。
感觉目前没法叠加的情况下多开客户端或多开UDP连接都没太好的适用场景，还不如直接一个连接的rcvwnd直接设置成需要的速度。

**Comment by bettermanbao** [comment]
请教 @xtaci 一个问题，rcvwnd 512，conn参数设为2，是每个connection 512，还是所有connection共享512？另外多开connection的实际应用场景是什么？谢谢！

**Comment by xtaci** [comment]
@bettermanbao 每个conn是独立的，不是共享的，有带宽竞争，多conn没有太大的实际价值。

**Comment by bettermanbao** [comment]
@xtaci 但是我试了很多次，1个conn wnd 2048，明显比2个conn wnd 1024要慢。可能是是qos引起的？

**Comment by xtaci** [comment]
@bettermanbao 这个问题就是HOL，为什么QUIC要按照内部的stream做ARQ，就是这个道理。
