### ISSUE TITLE
是否支持Reverse Tunneling?

### ISSUE THREAD

**Issue by amosbird** [xtaci/kcptun#379]
kcptun目前能否实现`ssh -R 19999:localhost:22 user@public-vpn.com`的功能？

**Comment by linhua55** [comment]
直接用ssh就行了

ssh client <---> kcptun client <---> kcptun server <----> ssh server

**Comment by amosbird** [comment]
@linhua55 那岂不是TCP over TCP over UDP了

**Comment by linhua55** [comment]
就是这样用的呀       多层tunnel嵌套，像 多层的 电线皮，里面的 导线就是要传输的 用户数据（有效数据）

2017-01-19 12:30 GMT+08:00 Amos Bird <notifications@github.com>:

**Comment by amosbird** [comment]
hmm, 我打算尝试kcptun的目的就是为了避免ssh tunnel的性能问题

**Comment by linhua55** [comment]
瓶颈一般不是ssh tunnel程序的执行性能，而是ssh流量被GFW干扰或者因为ssh是基于TCP的（需要三次握手），导致ssh连接不稳定。但如果在外面套上一层kcptun，连接的稳定性会好一些，速度会快一些。建议先实际测试一下，再做出判断。

**Comment by amosbird** [comment]
我稍微想了一下，好像UDP压根就不能做反向隧道:smile:

**Comment by linhua55** [comment]
UDP可以做反向隧道呀。
 主要是因为Server端在内网中（NAT下），所长需要反向隧道。所以需要维护一个NAT长连接。自己用python就可以简单的实现一个。不过纯UDP是不可靠的，发生丢包时不会重传，造成数据损失。

2017-01-19 15:56 GMT+08:00 Amos Bird <notifications@github.com>:

**Comment by wangyu-** [comment]
@amosbird 
```
ssh client <---> kcptun client <---> kcptun server <----> ssh server
```
这个不叫tcp over tcp，这只是tcp的简单转发，可以尽管使用。通常说tcp over tcp有性能问题是用tcp模式的openvpn产生的，会把高层tcp封装在低层tcp，有双倍重传的问题。
