### ISSUE TITLE
Abnormal output in SNMP log

### ISSUE THREAD

**Issue by Contextualist** [xtaci/kcptun#380]
![img_4151](https://cloud.githubusercontent.com/assets/16000021/22096426/6419f074-de56-11e6-8886-0e14b5a14106.JPG)
![img_4152](https://cloud.githubusercontent.com/assets/16000021/22096427/646d5b56-de56-11e6-9a69-7d76205fa029.JPG)

SNMP log from kcptun server (amd64, v20170117),
params: fast2, sndwnd 1024 rcvwun 256, mtu 1350, ps&ds (0,0)

Issues:
1) CurrEstab seems to overflow
2) The second to last RepeatSegs is larger than the corresponding InSegs

**Comment by xtaci** [comment]
show me the raw  .csv file content .

**Comment by Contextualist** [comment]
[kcptun_snmp.txt](https://github.com/xtaci/kcptun/files/718901/kcptun_snmp.txt)

**Comment by xtaci** [comment]
seems ok to me ... maybe it's a problem about excel parsing csv, close for now.

**Comment by Contextualist** [comment]
Really? Isn't `18446744073709551615` 2^64-1, namely -1 for unsigned int64? Shouldn't MaxConn, PassiveOpen, and CurrentEstab stay to be 1 all way through, since I set the connection to 1 and keep connected throughout the test?

It seems to me that it is a problem when CurrentEstab falls to 0 then to -1.

**Comment by xtaci** [comment]
@Contextualist， it's possible, snmp may overflow， but , we don't need 100% acuraccy, it has some costs.

**Comment by Contextualist** [comment]
Fine, then. 

BTW, could you please explain why my CurrentEstab fell to 0 in the sencond interval though I kept the connection. (In the last interval, 0 to -1 is reasonable because I killed client before server)

Also, how can the second to last RepeatSegs (1900) be larger than the corresponding InSegs (522) ? Or I mistaken the meaning of them?

**Comment by xtaci** [comment]
you can stop snmp, and use kill -SIGUSR1 to find consistent result
