### ISSUE TITLE
GO1.8编译的MIPS二进制文件出现ILLEGAL INSTRUCTION的确是FPU的原因

### ISSUE THREAD

**Issue by terrytw** [xtaci/kcptun#381]
编译了一个内核开启FPU模拟的OPENWRT CC，就可以正常使用GO1.8编译的MIPS版本KCPTUN了
速度的确有明显的提升（比GO1.4编译的翻倍了，在不开启FEC的情况下可以达到差不多10m）
路由器CPU的性能目前来看似乎是瓶颈

**Comment by bettermanbao** [comment]
再给你一个小tips，路由器上开2个256窗口的kcptun进程，速度远大于开一个512窗口的。

然后以下iptables命令可以简单对2个进程做负载均衡。
iptables -t nat -A PREROUTING -p tcp --dport 10099 -j REDIRECT --to-ports 10097-10098 --random
10099是下游实际连接的端口，2个kcptun进程监听10097和10098端口。

**Comment by bettermanbao** [comment]
以上现象 @xtaci 怎么看？肯定是哪里出瓶颈了，因为我试过在电脑上不存在这种情况。

以上现象在mt7620的路由器上可以重现，一个512窗口最多8Mbps，2个256窗口合并可以到14M。
FEC我是开着得10,3。

**Comment by xtaci** [comment]
就是cpu瓶颈， 接收->解密->校验，导致单管线堵塞丢包，多管线可以并行接收，内核丢包少一些。

**Comment by terrytw** [comment]
@bettermanbao 
谢谢你的提示，但是我试了一下似乎这个IPTABLES的写法在我的路由器上不能正常运行
就算是不做负载分配只做端口转发都不行，比如说
iptables -t nat -A PREROUTING -p tcp --dport 10099 -j REDIRECT --to-ports 10097
SS-redir的服务器地址是127.0.0.1:10099，kcptun监听本地10097端口，也走不通

**Comment by wshsj0413** [comment]
换个7621的路由器，youtube 4K最高50%负载

**Comment by bettermanbao** [comment]
命令不要放在rc.local文件里，要写在firewall.user里，这个iptables我现在正在用，潘多拉的固件

**Comment by baggiogogo** [comment]
透明代理，试试OUTPUT。

**Comment by terrytw** [comment]
@bettermanbao @baggiogogo 
的确是写成OUTPUT就走得通了....
试了一下双开KCPTUN，不如单独开效果好
环境不同很多东西的确不能复制

**Comment by terrytw** [comment]
谢谢楼上诸位

**Comment by bettermanbao** [comment]
双开单线程肯定没有单开好，比如开个y2b看视频，但在多用户同时使用时，总的峰值带宽，我这边测下来明显好于单开。顺便问下你的路由器是什么cpu?

**Comment by terrytw** [comment]
ar7161 原来双开是为了多用户，这个我倒是没想到... 明天试一下 在2017年01月22日 00:58 ，bettermanbao写道： 双开单线程肯定没有单开好，比如开个y2b看视频，但在多用户同时使用时，总的峰值带宽，我这边测下来明显好于单开。顺便问下你的路由器是什么cpu? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bettermanbao** [comment]
ar7161好老的cpu啊，现在mt7620那么便宜，升级吧。
mt7620配合pandora固件，完全兼容openwrt bb，还有hardware nat。Release里的mipsle版可以直接使用。

**Comment by terrytw** [comment]
当时买的时候觉得ar71xx系列的CPU支持性特别好，各种固件软件包都有预编译好的可以直接用
现在看来的确需要升级，不过暂时没那个动力折腾...
MT7620好像国产的各种路由器都在用，我个人对于国产的产品，有一种长期积累的不信任...

**Comment by terrytw** [comment]
不管怎么说还是谢谢你的热心指导啦

**Comment by daiaji** [comment]
看你们这么说 我甚至想丢了RT3052的HG255D
@bettermanbao K1 pandora固件带hardware nat吗？
然后pandora兼容openwrt BB的ipk？那我拿rt288x的SDK就能编译可用的KCPTUN？
还是直接拿Release的mipsle包就OK了吗？
然后hardware nat会让iptables失效吧？那么服务端的KCPTUN shadowsocks openVPN还能用吗？

@terrytw 大兄弟要MT7620的路由吗？K1 K2 JD自营 用垃圾佬的话说是免费路由吧

**Comment by terrytw** [comment]
@daiaji 
呃，不太愿意为了一个百来块的东西卖自己的信息

**Comment by daiaji** [comment]
@terrytw 你这不都要刷奇奇怪怪的固件了吗 后门早就不起作用了吧？总不至于定制个芯片专门用来发送数据吧
倒是要身份证才能把钱弄回来就是了

**Comment by terrytw** [comment]
身份证，手机号，什么的。

2017年2月20日 20:02，"daiaji" <notifications@github.com>写道：

**Comment by daiaji** [comment]
@terrytw 是啊 把钱搞出来要身份证和手机号 记得解绑银行卡还要手持本人身份证的照片
总感觉……

**Comment by terrytw** [comment]
是啊，我觉得这点钱，不值得出卖自己

2017年2月20日 20:51，"daiaji" <notifications@github.com>写道：

**Comment by daiaji** [comment]
@terrytw 问题就来了 除了这个之外的mt7620没什么太多值得买的路由（虽然K1 K2很菜 硬件拙计 缩水 但是用hardware nat似乎也能刚刚好）
mt7620怎么说的吧 没太多买的价值 没有原生的千兆有线口 单核 如你所见的cpu性能拙计 再怎么也要100 左右 二手买个这玩意也要50 感觉没卵用 大概还真是 送我就还行这种程度吧（万一hardware nat开了也不能拯救这可悲的性能那差不多就是废铁了）
mt7621就是299起步了 听说可玩的固件少 但是性能也是好很多 原生千兆有线 双核带来的牛逼性能
但是也还是不疼不痒 干脆来个ASUS AC5300 八爪鱼就是好 一步到位 因为cpu性能影响kcptun的速率的日子再见吧！ 其它更是爽 差不多就是能买到的最棒消费级路由了吧
好像忘了些什么 但是没所谓 买东西嘛 图的就是一个开心！

**Comment by Biercenter** [comment]
怎么全部聊优化和硬件啦！到目前还是需要重新编译固件开FPU吗？特别是现在LEDE正式版出来了，有点不想再编译了

**Comment by bettermanbao** [comment]
@Biercenter
不想编译固件可以用我编译的kcptun，不需要开fpu模拟，当然速度肯定会慢一些。

**Comment by Biercenter** [comment]
你的好久没更新了啊

**Comment by bettermanbao** [comment]
没有很久吧。



-------- 原始信息 --------
由： Biercenter <notifications@github.com>
日期: 17/2/21 21:05 (GMT+08:00)
收件人： xtaci/kcptun <kcptun@noreply.github.com>
抄送： bettermanbao <jackybao_sh@msn.com>, Mention <mention@noreply.github.com>
主题： Re: [xtaci/kcptun] GO1.8编译的MIPS二进制文件出现ILLEGAL INSTRUCTION的确是FPU的原因 (#381)


你的好久没更新了啊

―

**Comment by terrytw** [comment]
最新版本有一个很重要的更新就是网络不通的时候不会自动退出了:)
虽然可以写sleep 10 && 但是我就是喜欢用LUCI界面啊！
人果然都是懒的
感谢更新！两位都是！

**Comment by xtaci** [comment]
呃，不退出就改了一行。

**Comment by terrytw** [comment]
嘿嘿，有些功能虽然技术上很简单，但是有时候比一些实现很复杂的功能更有用呢

**Comment by Biercenter** [comment]
谢谢 @bettermanbao

**Comment by daiaji** [comment]
不说跑kcp了……RT3052这鬼东西呢 只跑个rc4-md5加密的ss就他喵的cpu负载99% 2Mb/s 开了kcp 直接掉到400kb/s 感觉这几天搞这破玩意一点卵用都没用
我还是试试MT7620吧……

**Comment by bettermanbao** [comment]
我现在是2个mt7620的路由，副路由跑kcptun，主路由跑ss。轻松上3MByte/s，此时kcptun的副路由满载，ss的主路由30%。

**Comment by bettermanbao** [comment]
这里真的要感谢 @xtaci 的不断优化，我记得最早的时候mt7620上跑kcptun内存经常不够，而且速度绝对超不过3Mbit/s，到现在可以跑到3MByte/s。膜拜大神！

**Comment by daiaji** [comment]
@bettermanbao 这难道就是传闻中极其先进的分布式计算？

**Comment by terrytw** [comment]
xtaci从12月开始增加了MIPS芯片的预编译文件，全都是用GO1.8编译的
BETTERMANBAO全是用GO1.4编译的

**Comment by terrytw** [comment]
顺便一提我用树莓派3B做路由，CORTEX A53的CPU,最多也就跑15-20m，cpu已经占用80%以上了
所以用ARM来跑KCPTUN未必有很大提升

**Comment by bettermanbao** [comment]
@terrytw
你遇到的可能是线路瓶颈，我用orange pi one，同样arm v7 4核，转发到50Mbps，cpu大概在60%，我用的是salsa20 fec 10:3。20Mbps，我用mt7620的路由器都不止这速度。

@daiaji
为了5G全覆盖，相信家里放2个以上的路由器人不在少数。主要现在电信力推200M宽带，2G肯定跑不满。

**Comment by liyiecho** [comment]
@daiaji 我用upx压缩后得到1M多，怀疑@xtaci 的upx没压缩好

**Comment by bettermanbao** [comment]
@xtaci 你编译的机器是不是没装upx?我看build-release.sh文件里应该是会压缩的，但实际release里的文件并没有被压缩。

**Comment by baggiogogo** [comment]
@terrytw 
是不是刷的openwrt或者lede？树3肯定不止这点能力。

**Comment by terrytw** [comment]
@baggiogogo 
就是raspbian啊

**Comment by xtaci** [comment]
没有压缩的，UPX压缩的包，windows下的杀毒软件会误报 upx病毒。

**Comment by daiaji** [comment]
@xtaci 为什么kcp的二进制文件这么大呢？体积能小一点吗

**Comment by xtaci** [comment]
用upx自己压缩一下吧，误报病毒始终是不好的。

**Comment by daiaji** [comment]
@xtaci 老实说这个体积和go本身对嵌入式设备不太友好

**Comment by xtaci** [comment]
@daiaji 没有办法，功能确实有那么多。upx能压到1MB左右

**Comment by daiaji** [comment]
@xtaci 是不是依赖太多了？upx倒是不用 openwrt可以运行在squashfs这种压缩只读文件系统上体积和用upx差不多

**Comment by xtaci** [comment]
@daiaji 已经非常省了。

**Comment by xtaci** [comment]
建议还是用高性能的ARM CPU跑，低端CPU会非常影响传输。

**Comment by daiaji** [comment]
@xtaci 我去捡一个没人要的机顶盒吧

**Comment by baggiogogo** [comment]
@terrytw 
我明白了，树三应该也是四核吧，cpu占用会显示超过100%，不严谨的算法，80/4，每个核心约20%。
我的树2，30Mbps是我个人加以限制的保守数值，10/5的FEC。
排查下是否被限速了。

**Comment by bettermanbao** [comment]
@xtaci 
build-release.sh里mips&mipsle是压缩的吧？有个upx -9，编译的机器装upx就应该会自动压缩的。
'''
#MIPS32LE
env CGO_ENABLED=0 GOOS=linux GOARCH=mipsle go build -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o client_linux_mipsle github.com/xtaci/kcptun/client
env CGO_ENABLED=0 GOOS=linux GOARCH=mipsle go build -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o server_linux_mipsle github.com/xtaci/kcptun/server
env CGO_ENABLED=0 GOOS=linux GOARCH=mips go build -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o client_linux_mips github.com/xtaci/kcptun/client
env CGO_ENABLED=0 GOOS=linux GOARCH=mips go build -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o server_linux_mips github.com/xtaci/kcptun/server

if $UPX; then upx -9 client_linux_mips* server_linux_mips*;fi
tar -zcf kcptun-linux-mipsle-$VERSION.tar.gz client_linux_mipsle server_linux_mipsle
tar -zcf kcptun-linux-mips-$VERSION.tar.gz client_linux_mips server_linux_mips
$sum kcptun-linux-mipsle-$VERSION.tar.gz
$sum kcptun-linux-mips-$VERSION.tar.gz
'''

**Comment by bettermanbao** [comment]
@daiaji

编译后3M，压缩后1M。这么大是因为go编译器的问题。另外不建议把kcptun打包进固件，更新太频繁了。

**Comment by bettermanbao** [comment]
@baggiogogo
关于CPU，难道你们都不用htop，还是用top的吗？

![htop](https://cloud.githubusercontent.com/assets/17328315/23295265/95141c52-faaa-11e6-96fa-46702bf6516f.png)

**Comment by baggiogogo** [comment]
@bettermanbao 
很少关心CPU，回头我装个。

**Comment by daiaji** [comment]
@bettermanbao openwrt文档上说是推荐编译到固件里
更新……
其实我是用解包器解包bin
然后再重行封装的

**Comment by terrytw** [comment]
@baggiogogo 
你说的很对！原来是TOP计算不准确的原因...
那么CPU占用的确不高，就是线路问题

**Comment by daiaji** [comment]
@xtaci 
/usr/bin/kcp-server -t 192.168.2.239:8388 -l 0.0.0.0:4000 -mode fast2 --crypt xor --nocomp
这是我在路由器上的设置（这台上只有KCP IP是192.168.2.236）
kcp在转发192.168.2.239上的流量（192.168.2.239是SS服务器） 我PC的IP地址是192.168.2.104 
为什么我在PC上用
client_windows_amd64.exe -r "192.168.2.236:4000" -l ":8388" -mode fast2 --crypt "xor" --nocomp
会没法用？
但是把PC插在KCP服务器的lan口上就能用

**Comment by terrytw** [comment]
@bettermanbao 突然想到一个问题
请问你用的路由方案，目前内网传输的速率大概有多少？
比如一个连5G的和一个连2.4G的WINDOWS电脑之间通过网上邻居拷贝单个大文件的速度

**Comment by bettermanbao** [comment]
内网我没传过文件，5G下载反正200M外网轻松跑满。



-------- 原始信息 --------
由： terrytw <notifications@github.com>
日期: 17/3/12 12:44 (GMT+08:00)
收件人： xtaci/kcptun <kcptun@noreply.github.com>
抄送： bettermanbao <jackybao_sh@msn.com>, Mention <mention@noreply.github.com>
主题： Re: [xtaci/kcptun] GO1.8编译的MIPS二进制文件出现ILLEGAL INSTRUCTION的确是FPU的原因 (#381)


@bettermanbao<https://github.com/bettermanbao> 突然想到一个问题
请问你用的路由方案，目前内网传输的速率大概有多少？
比如一个连5G的和一个连2.4G的WINDOWS电脑之间通过网上邻居拷贝单个大文件的速度

―

**Comment by terrytw** [comment]
@bettermanbao 那就是理论上来说内网传文件至少会有25MB/s的速度？

**Comment by bettermanbao** [comment]
有线跑满1000M应该没问题，瓶颈主要在无线加密上，全靠cpu算。


-------- 原始信息 --------
由： terrytw <notifications@github.com>
日期: 17/3/12 13:04 (GMT+08:00)
收件人： xtaci/kcptun <kcptun@noreply.github.com>
抄送： bettermanbao <jackybao_sh@msn.com>, Mention <mention@noreply.github.com>
主题： Re: [xtaci/kcptun] GO1.8编译的MIPS二进制文件出现ILLEGAL INSTRUCTION的确是FPU的原因 (#381)


@bettermanbao<https://github.com/bettermanbao> 那就是理论上来说内网传文件至少会有25MB/s的速度？

―

**Comment by terrytw** [comment]
@bettermanbao 是啊，就是因为无线传文件太慢了而烦躁

**Comment by daiaji** [comment]
@terrytw 你还在用你的ar7161？
现在最强的路由器soc方案是ipq8064 BCM4709 wp7吧的测评上说BCM4709的1.4G A9 *2更强
7621人家讲单核是两倍7620 总算力是四倍7620 那么就是rc4-md5加密的ss-server跑到4*4=16Mb/s
这只是跑rc4-md5加密的ss-server 还没有上kcp 16/5=3.2Mb/s 然而还是不能跑满百兆……
只能上ARM方案了

**Comment by dearneo** [comment]
BCM4908已经发布很久了，4*A53架构，有AES指令加速，却一直不见成品路由上市。。
现在在用BCM4709的路由，1G*2的，salsa20关FEC情况下大约能跑到50Mbps，感觉性能还可以。

**Comment by daiaji** [comment]
@dearneo 用AES加密 是不是会更快一点？毕竟有专用指令集

**Comment by dearneo** [comment]
@daiaji 
路由只跑kcptun，ss在电脑或手机上跑的，也没经过很严密的测试，但50Mbps是没问题的。
ss上用了aes加密，电脑和手机有aes指令加速基本不耗费什么计算资源，速度基本是没aes加速指令的十几倍。
查了一下，BCM4908似乎已经有成品路由上市了，但基本都是天价。。。

**Comment by daiaji** [comment]
@dearneo 全丢路由器上跑试试？可能会是40Mbps 这样计算也误差不大？
妈卖批 bcm搞个双核多好 非得四核…… 
联发科不也在搞arm 为啥不出几个……
MIPS药丸的
