### ISSUE TITLE
enhancement?

### ISSUE THREAD

**Issue by Immueggpain** [xtaci/kcptun#382]
我在寻求一个tcp加速的工具，发现了这个挺好的，不过还没到我理想的期望，所以特地来问一下作者。
主要2个问题：
1、可以加入缓冲机制吗？我的意思是把低延时的包缓存一段时间，再交给tcp。
需要这功能是因为我主要使用tcp大流量而不是太在意时延，比如看视频之类的。
而缓冲功能可以使得有足够的时间重传，毕竟重传一次在上层TCP看来就是至少3倍时延。
而tcp实际上是个很老很破旧的东西，受不了刺激，RTT一抖动多半就要掉速度。
2、对于不在意流量只在意时延的情况下，是否可以支持动态的基于时间间隔的FEC？Reed Solomon是很不错的选择，不过还是可能遇到突发错误超过长度的时候。我还没做高峰时刻国际出口udp掉包的特征测试的说，不过就经验来说突发的连续drop好像是会发生的，不知道作者有没有这方面数据？跨国的时候时延都有100ms，再考虑到掉一个包就是3倍时延，FEC导致的时延完全可以接受了。
我知道这2个特性貌似工作量都挺大，而且也不是很合kcp。。。所以也是很想知道作者的想法，因为我也在考虑是自己写一个UDP Tunnel还是支持kcptun。

**Comment by bettermanbao** [comment]
我来替作者回答一下吧，回答的不到位的地方还请作者补充。
第一个问题，可以通过调大interval做到。第二个问题可以建立2条udp隧道，1条高fec，1条低fec，然后用iptables根据系统时间选择不同的隧道。

**Comment by Immueggpain** [comment]
@bettermanbao 刚扫了一眼kcp-go的代码，interval只是简单一个call之间的最小间隔，做不到我所说的缓存功能。至于2条FEC也不行，比如我一次过50个包，我就希望50个数据块后接效验校验块，下次过了10个包，我当然希望10个数据块后就效验，不然等50个包？这和流量相关，和时间无关。另外这个和iptables有什么关系？

**Comment by xtaci** [comment]
@Immueggpain 
1. 你说的很对，RTT抖动是TCP的硬伤，直接导致tcp有个最大传输距离，即最大jitter容忍。kcp-go做了很多事以避免抖动，包括处理管线，定时器精度，BufferBloat等问题。你需要的是Bulk Transfer，这个不是kcp的初衷，做这种事，最佳的方案就是前向纠错，根本不ack，属于完全不同的一个领域，编码鼻祖高通的RaptorQ编码，用于做影院视频卫星传输的，可能是你需要的。

2. 动态FEC会非常复杂，我觉得可以配合多端口，多参数FEC， 加上独立的控制通道，动态切换，这是一个整套的解决方案，会把kcptun从一个 tool，变成一个system, 已经背离初衷了。

**Comment by Immueggpain** [comment]
@xtaci 
非常感谢作者的回答啊
我又仔细想了一遍整个kcptun的流程，以下是一些想法：
1. 是彻底解决的方法，就是用pcap抓包获取数据，然后延时返回ACK给TCP，这样抖动小，加速减速都可以很平缓。
2. 就是你说的Bulk Transfer（如果我没理解错的话），但一次bulk完，TCP又要慢慢加速才行。。。还是比较纠结，另外一不小心timeout就前功尽弃。。。
3. 只用FEC的话也无法保证都传到啊，到时候TCP就说了，诶你给了我ACK怎么现在又说没收到，你这有毒啊
4. 用RaptorQ实现动态FEC怎么样呢？不需要独立通道，只需要增加标志位。
最后，我发现对于kcptun的定位来说，能做的只有快速重传和RaptorQ，RaptorQ用于降低误码率，快速重传作为后手。至于大流量的情况，kcptun本身就不适用。
不知道大家觉得我说的有没有错误？

**Comment by xtaci** [comment]
@Immueggpain bulk transfer的逻辑完全不同，没有深入思考过这方面。

另外，对于kcptun的论断是正确的：

先FEC，再RTO，RTO是保底手段。

**Comment by Immueggpain** [comment]
@xtaci 我说的大，意思是指需要传输的数据永远大于实际的带宽的情况，就比如下载的时候，越快越好。我也有些地方没想清楚，不过大致我是想说kcptun+tcp这样不好流控。

**Comment by xtaci** [comment]
@Immueggpain 如果bps不高（>1gbps)，我认为kcp-go就完全满足需求。单纯基于rtt的，随着网络接入的提速，且骨干网络升级慢于用户接入带宽升级的情况下，一定会傻。 唯一的办法，就是FEC。我想不出更好的办法。

**Comment by Immueggpain** [comment]
@xtaci AQM的话是理想情况，或者说按道理来说的情况。但是我觉得如果你作为出口节点带宽紧张，不大可能任由一个IP占用大量资源，所以应该会对各IP限速吧？一但超过它设定的限速，就不是随机丢包了。不然的话现在各家都是100M带宽，大家都满带宽发。。。电信这不是要作死？

**Comment by xtaci** [comment]
@Immueggpain 网络的理论基础就是突发性和随机性，平时都没有问题，不可能同时压入一个管道。但是各家的带宽，都压入铁道部抢票，那才是作死。不过目前各家的带宽，99%的时间的流量，因为CDN和P2P都不可能出省。

**Comment by Immueggpain** [comment]
@bettermanbao 
看了你在其他Issue发的才明白你说的iptables是啥意思。。。不过你可能误解我了，我讨论的都是1条TCP连接的情况，已经连接上的tcp连接就无法简单通过iptables切换了。就像作者说的，除非加上独立的控制通道，动态切换，这是一个整套的解决方案。
我把OpenVPN去掉了加密套在kcptun上了2333，这样玩游戏比较方便，但是看4K视频有问题。
其实gaming的时候FEC冗余个几倍我也不在乎啊，你别丢包就好2333。
不过我考虑了下，多条TCP链路会是什么效果我也搞不清，值得试一试。

我开始2个问题到现在也解释清楚了，貌似是超出了kcptun这个项目的范围了。
@xtaci 最后还想问下作者，下一步kcptun打算做什么呢？增加特性？优化FEC？

**Comment by bettermanbao** [comment]
我们用kcptun来做的事不同吧，感觉对你来说在 @xtaci 加入动态fec前，最方便也就是用iptables根据不同需求，自动切换不同的kcp tunnel，然后为不同的kcp tunnel设置不同的传输参数。可以根据时间切换，不同端口切换，或者其他很多判断条件。其实我很想 @xtaci 把kcptun做的和ss-redir一样，可以同时转发tcp和udp数据。

**Comment by xtaci** [comment]
@Immueggpain feature基本不会增加了。我会贯彻do one thing and do it well到底。

**Comment by notedit** [comment]
动态fec   最好在应用层做 引入的东西太多

**Comment by Immueggpain** [comment]
@xtaci OK，我没有其它问题了。也感谢大家的讨论，我受益匪浅。closing the issue.
