### ISSUE TITLE
如何防止UDP的封堵？

### ISSUE THREAD

**Issue by wulongji2016** [xtaci/kcptun#383]
不知道各位在使用的时候，如何避免运营商的封堵和断流？

UDP和TCP本质上都是以数据包的形式发送文件，区别在于发包确认和重传机制不同。是否可以修改UDP协议头标识，让运营商以为是TCP，避免断流和封堵？ 
或者采用其他方案，使得运行商识别不出来是UDP下的KCP协议？

**Comment by jairwen** [comment]
看下网络七层模型

**Comment by wulongji2016** [comment]
@jairwen 我看过网络七层模型 ，我觉得有实现的可能性，当然了，我也是小白。 请懂的人指点一下。

**Comment by lizongzeshunshun** [comment]
你可以看看这个https://github.com/linhua55/some_kcptun_tools/tree/master/relayRawSocket

**Comment by nxtreaming** [comment]
一个是stream，一个是message, 没法修改简单的修改协议头就实数据伪装。

**Comment by wangyu-** [comment]
看一下这个，https://github.com/wangyu-/udp2raw-tunnel。这个就是像楼主说所的，修改UDP协议头标识，把UDP伪装成TCP。还可以伪装成ICMP。OpenVZ可用。
