### ISSUE TITLE
关于网络丢包参数设置,可否做一些设置事例?

### ISSUE THREAD

**Issue by mir3000** [xtaci/kcptun#385]
关于网络丢包参数设置,可否做一些设置事例?
比如 丢包 5% 10% 20% 之类的参数事例.

**Comment by TMily** [comment]
目前的情况下跨境的通道基本上都是丢包相对较高的吧，这块需要调的参数基本上就是FEC比例而已，快速重传什么的打开就好，另外就是根据实际应用调节一下FEC块大小。比如20丢包率的时候是用20 80 还是用1 4之类的了
