### ISSUE TITLE
macOS 版，今天出现一次域名解析失败导致的自动退出

### ISSUE THREAD

**Issue by kenpingliu** [xtaci/kcptun#387]
如题，20170120 版本，看日志信息是域名解析失败了，日志信息如下：

2017/01/22 20:53:09 lookup vps on 61.139.2.69:53: no such host
net.ResolveUDPAddr
github.com/xtaci/kcp-go.DialWithOptions
        /Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:914
main.main.func1.1
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:335
main.main.func1
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:387
  thub.com/urfave/cli.HandleAction
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:259
main.main
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:422
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2197
createConn()
main.main.func1.1
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:337
main.main.func1
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:387
github.com/urfave/cli.HandleAction
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:259
main.main
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/client/main.go:422
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2197

**Comment by StepOverFlow** [comment]
一样，同楼上。我贴下config文件？
{	
    "localaddr": ":xxxx",
    "remoteaddr": "xx.xx.x.xxx:29900",
    "key": "xxxxxxxxxx",
    "crypt": "none",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}

**Comment by kenpingliu** [comment]
补充一下，后面发现一旦出这个错后会连续出现，歇一会儿后再启动又对了

**Comment by xtaci** [comment]
use IP
