### ISSUE TITLE
kcptun相同配置，联通和电信的速度差好大

### ISSUE THREAD

**Issue by octww** [xtaci/kcptun#389]
之前用江苏联通50M宽带，非高峰期看yt速度随随便便都在20000Kbps-30000Kbps，过年回老家用电信60M，非高峰期速度只有2000-6000Kbps，差距明显。

下面是我的参数，因为我不是很懂，所以基本用默认，希望大家可以给点建议，看看怎么调整速度会快一点。

服务器端：
    "crypt": "aes",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10

客户端 
   "crypt": "aes",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 512,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10

**Comment by alex43211** [comment]
crypt改成salsa试试

**Comment by leepoi** [comment]
联通的人均出口带宽高于电信，仅次于移动，所以这很正常

**Comment by xtaci** [comment]
用最新版

**Comment by bash99** [comment]
电信那边，关闭FEC，降低窗口开始试试？
从160开始慢慢上升，看看能否好点，我大概能在高峰稳定到4000-6000K，自动1080p并且一直流畅。
