### ISSUE TITLE
kcptun go客户端适用于安卓手机吗？

### ISSUE THREAD

**Issue by sosmygirl** [xtaci/kcptun#39]
golang 1.5可以在安卓上运行，不知可以实现安卓运行不？

**Comment by xtaci** [comment]
try linux arm

**Comment by trivita** [comment]
cross compile it, it might work. with great probability

**Comment by xtaci** [comment]
https://godoc.org/golang.org/x/mobile
maybe you can add a GUI to android app.

**Comment by shutup** [comment]
i am working on this,once the warper apk is done, i will open source it.

**Comment by bubbless** [comment]
shadowsocks releases 3.0.1 is support kcptun.
[https://github.com/shadowsocks/shadowsocks-android/releases](https://github.com/shadowsocks/shadowsocks-android/releases)

**Comment by liyue80** [comment]
@shutup @bubbless SS自带的Kcptun功能还不稳定，希望有一个更好的可替代品。
