### ISSUE TITLE
kcptun感觉挺容易被GFW识别出来

### ISSUE THREAD

**Issue by Nehalem-Lf** [xtaci/kcptun#391]
用了大概一天左右吧，搭配的SSR，用着用着端口直接被封掉，无奈

**Comment by lizongzeshunshun** [comment]
那是ISP对UDP的封锁，应该和GFW没多大关系

**Comment by Nehalem-Lf** [comment]
唔..是因为udp流量太大吗？

**Comment by lizongzeshunshun** [comment]
有的地区的运营商喜欢封UDP（流量一大直接切断），很多issues已经反映了这个问题

**Comment by Nehalem-Lf** [comment]
那请问有什么解决方案吗？MTU改成512依然是被ban掉

**Comment by lizongzeshunshun** [comment]
看看#228

**Comment by Nehalem-Lf** [comment]
好的，感谢，打算先装BBR挂原版SSR试试了

**Comment by wangyu-** [comment]
针对udp屏蔽和udp qos的方案，把udp流量包装成tcp或者icmp：
https://github.com/wangyu-/udp2raw-tunnel
支持kcptun和finalspeed。openvz可用。

**Comment by BH1SCW** [comment]
感谢大神出手！

**Comment by sway913** [comment]
搭车求问，SSR的Android客户端如何使用kcptun
