### ISSUE TITLE
License for image files

### ISSUE THREAD

**Issue by rogers0** [xtaci/kcptun#393]
Hi there,

Thanks for working on this project.
I'm going to package this to Debian. However, according to rule of Debian, every file should be cleared in license.
So I'm writing to you to double confirm the following file:
fast.png kcptun.png layeredparams.png logo-small.png logo.png rs.png

Are you created the above 6 files by yourself? If so, we can safely treat it same as the code you wrote, so it's MIT/Expat license.
But if you borrow some files from other project, please let me know. So I can trace the license of each image file.
Thank you!

Cheers,
Roger

**Comment by xtaci** [comment]
rs.png comes from https://www.backblaze.com/blog/reed-solomon/
others are created by myself.
