### ISSUE TITLE
Short introduction for kcptun

### ISSUE THREAD

**Issue by rogers0** [xtaci/kcptun#394]
I only find a title as "A Simple UDP Tunnel Based On KCP"
but there's no short introduction for this project.

For smux and kcp-go, there's introduction in README.md for both projects.

Could you provide a short description for kcptun?
Such as,
 kcptun is blah blah
 it has server and client, blah blah

Thank you!

Cheers,
Roger

**Comment by xtaci** [comment]
how about:

> kcptun is a remote port forwarding tool by converting TCP stream into UDP stream in KCP protocol, in order to achieve higher throughput or lower latency with rich tuneable options.

**Comment by rogers0** [comment]
@xtaci Thanks. I'll use it to package.
