### ISSUE TITLE
kcptun加速后单文件下载会被截断

### ISSUE THREAD

**Issue by milkice233** [xtaci/kcptun#395]
用kcptun加速之后
Youtube 1440p无压力
但是似乎单线程文件下载的时候文件会被截断
比如100M的文件用chrome自带下载器下载下了10M就提示下载完毕
同理Google play在下了1、2M后就断流
有什么解决方法么

**Comment by janvier-ninja** [comment]
有可能是中间isp干的，检查下

**Comment by cokll** [comment]
同样的问题,下载任何文件都是,感觉不是干扰

**Comment by xtaci** [comment]
-autoexpire?

**Comment by milkice233** [comment]
我之前尝试过一个一个排查
到最后排插到的是datashared和parityshared
如果不指定这两个参数的值而用kcptun默认的值的话就不会出现单文件被截断的问题
但是还是很好奇原因啊
因为我之前指定的是--ds 70 --ps 30，我记得这也是官方推荐的设置吧
然后就出现单文件被截断的问题
使用kcptun默认值--ds 10 --ps 3则不会
0.0
P.S.:应该不是ISP的问题，因为我之前跑过朋友家去测试，他的是联通我是电信都有这个问题

**Comment by xtaci** [comment]
这么奇怪？ 两端都是一样的ds ps么？

**Comment by cokll** [comment]
@xtaci 
server
`{
    "listen": ":29900",
    "target": "********:50806",
    "key": "czxczx3q4casd",
    "crypt": "salsa20",
    "mode": "fast3",
    "mtu": 1400,
    "sndwnd": 512,
    "rcvwnd": 512,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10,
    "autoexpire": 60
}`
client
`{
    "localaddr": ":12450",
    "remoteaddr": "*******:29900",
    "key": "czxczx3q4casd",
    "crypt": "salsa20",
    "mode": "fast3",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1400,
    "sndwnd": 512,
    "rcvwnd": 512,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}`

**Comment by xtaci** [comment]
没什么特殊的，我看能否重现

**Comment by xtaci** [comment]
无法重现，不妨试试aes-128，如果带宽很小，不要强行开大窗口

**Comment by cokll** [comment]
带宽1G出口,试过其他的sndwnd组合都一样,两台vps 一台版瓦工一台hostus都是此情况

**Comment by xtaci** [comment]
哦，看到了，你的keepalive，太短了，10秒就断。

**Comment by cokll** [comment]
需要加大吗

**Comment by xtaci** [comment]
autoexpire 太短了

**Comment by xtaci** [comment]
60s强行断。

**Comment by cokll** [comment]
目前是下3-10秒就断

**Comment by cokll** [comment]
需要改为多少

**Comment by xtaci** [comment]
是的，60s是最大，如果你是想保持永远不断，那就设置为0 ，单位是秒。

**Comment by cokll** [comment]
好的,我试试

**Comment by cokll** [comment]
改成0之后真的不断了,谢谢 @xtaci
