### ISSUE TITLE
请问armv5 v6 v7这几个版本对于运行效率有什么影响吗？

### ISSUE THREAD

**Issue by terrytw** [xtaci/kcptun#396]
手上有一个树莓派3B，用的ARMV8的架构，用这几个版本都可以运行，试了一下似乎都差不多
不知道哪个版本更合适一些，也许不是作者你的专业领域范围内的，但也实在不知道去哪里问更合适
如果有人知道的话请赐教

**Comment by dfdragon** [comment]
arm架构是向后兼容的，所以针对v5、v6、v7的编译版本在v8上都可以正常运行，兼容性见下图([出处](https://www.arm.com/zh/products/processors/instruction-set-architectures/index.php))：
![v5_to_v8_architecture](https://cloud.githubusercontent.com/assets/9766935/22411483/512e18aa-e6df-11e6-92ff-a3182ffda9b5.jpg)
**一般来说**，用高版本可能更合适一些，可能会使用到新的特性以提高运行效率(依赖编译器)。

**Comment by terrytw** [comment]
明白了，非常感谢！
