### ISSUE TITLE
Kcptun的安卓连接方式有开源计划吗?

### ISSUE THREAD

**Issue by mir3000** [xtaci/kcptun#397]
Kcptun的 安卓连接方式有开源计划吗?
目前比较流行的是SS+KCPTUN, 如果不用SS呢?
希望增加一个安卓的客户端开源版本啊///让更多的软件可以尝试对接并用.

**Comment by terrytw** [comment]
ARM架构的手机可以直接用ARM的那个
其他的你可以自己编译，源码都是公开的，还要怎么开源...

**Comment by wxyzh** [comment]
try [termux]( https://termux.com/)
