### ISSUE TITLE
建议在连接失败时不要直接退出

### ISSUE THREAD

**Issue by libertas** [xtaci/kcptun#399]
我现在遇到一个问题。
我想让kcptun的client自动启动，但是我发现在还没有连接互联网之前，kcptun运行之后会自动退出。
这样如果我让它自动启动的话，在联网之前它就已经退出了。
参考shadowsocks，它是不会直接退出的，如果我让它自动启动，它就可以在我联网之后工作。
所以我建议在连接失败时不要直接退出

环境：Linux Mint 18
自动启动：通过systemd的service实现

**Comment by cokll** [comment]
我现在也很烦,长连接改成0后经常自动退出,设置的话又会断流,无奈

**Comment by maddie** [comment]
You can use `Restart=always` in systemd service file

**Comment by cokll** [comment]
@maddie My use Synology Nas run kcptun ,No systemd

**Comment by xtaci** [comment]
下个版本加， 心急的可以自己编译一下，已提交。
