### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by ElvizLai** [xtaci/kcptun#4]
digitalocean vps: 512MB with 512MB swap

In client side, using wget to fetch a big file(~500MB), the server killed because OOM.

**Comment by xtaci** [comment]
I suggest at least 1G memory for kcptun, never crashed on my box for 1G.
I'll look into OOM problem later.

**Comment by ElvizLai** [comment]
using 1024MB swap, it works now.
<img width="552" alt="dingtalk20160407103737" src="https://cloud.githubusercontent.com/assets/501861/14338864/d70e09f8-fcac-11e5-846c-80e09363b017.png">

**Comment by ElvizLai** [comment]
It interrupted, and never backed again.
<img width="1130" alt="dingtalk20160407103943" src="https://cloud.githubusercontent.com/assets/501861/14338899/322ccff4-fcad-11e5-8afc-660130a6e942.png">
<img width="692" alt="dingtalk20160407103958" src="https://cloud.githubusercontent.com/assets/501861/14338904/36f46326-fcad-11e5-99d8-740c7ca2f0bf.png">

**Comment by xtaci** [comment]
try kill & restart

**Comment by xtaci** [comment]
for you information:  https://github.com/xtaci/kcptun/issues/2

> 请问：发生use of closed network connection的原因是什么，如何解决？（我之前加了连接池，可以避免这个错误的发生，但觉得不是最好的解决方案）；

首先，kcptun的这种多client的使用方式，我并不推荐，请注意README中的一段:
**openvpn client -> kcptun client -> kcptun server -> openvpn server (最佳实践)
ssh tunnel client -> kcptun client -> kcptun server -> sshd (推荐应用)
browser socks5 -> kcptun client -> kcptun server -> ssh -D socks5 server (简易)**

你的用法属于简易方式，即短链接为主的连接，这个是方便个人用户使用的，必然会出现很多close消息，我的推荐是单链接，即ssh -D 在client端执行，**一对kcptun c/s最好只承载一条tcp连接**。

> 在这样的网络环境下，kcp的一些参数比如像窗口size的大小，怎样设置比较合理，依据是什么；

窗口大小的设置，以fast模式来说，主要的依据是，上行流量带宽和下行流量带宽。
比如上行128KB/s带宽，单个数据包平均大小1000B， 那么上行窗口大小为128即可占满所有带宽。
下行同理。

>  正常发送的数据大小大约是211924（测试时的4倍）字节，这样的数据大小kcp调整参数后，是否可以发送？（我尝试过2倍，发送不成功，卡住了。具体原因还没查）

kcp-go 的 sess.go处理过 大数据包的分隔，详见Write函数， 原则上，接收端的窗口大小必须大于单个数据包的大小，否则极可能出现分片无法整合，无法接收完整数据而卡住。
