### ISSUE TITLE
sndwnd:  rcvwnd: !?如何计算的？

### ISSUE THREAD

**Issue by lbbboy** [xtaci/kcptun#40]
这两个值是怎么计算的？谢谢。

**Comment by xtaci** [comment]
假如sndwnd = 1024， 平均包大小1K, RTT = 300ms
那么网络上总共有 1K * 1K / 300ms = 3.33MB 在流动，这个是最大值。也就是占用了33Mbps的带宽。

**Comment by lbbboy** [comment]
用了一会，然后就不能用了什么情况！！！

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Does your ISP or VPS **blocked UDP**?
5. Does your VPS **firewall** allows UDP pass through?
6. Are you using the **same version** for both client & server
7. Did you correctly set the ```-target value, -t value	target server address (default: "127.0.0.1:12948")``` on the server side?
