### ISSUE TITLE
请问dockerhub上的xtaci/kcptun 是你维护的吗？

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#400]
最近撸了个arukas.io的免费docker，准备玩玩docker。

请问dockerhub上的xtaci/kcptun 是你维护的吗？会同步更新吗？

谢谢！！！

**Comment by xtaci** [comment]
自动的，每次提交自动编译。

**Comment by bettermanbao** [comment]
谢谢！

**Comment by bettermanbao** [comment]
发觉你的docker repo体积有112MB，这个集成ss和kcptun的repo才17MB。
有空的时候麻烦看下，谢谢！

**Comment by xtaci** [comment]
是的，没怎么关心这个，用的golang基础image，在容器内编译，肯定大，还是建议用其他的image。

**Comment by xtaci** [comment]
建议你自己做docker image单独分享到hub.docker.com， 特别是如果你想整合ss等其他软件。

这个image不会整合其他软件，只做概念验证用，你懂的。

**Comment by bettermanbao** [comment]
老大，记得你说过 do one thing, do it well.
研究一下嘛，这几精简的image里的内容在这里。
https://microbadger.com/images/mritd/shadowsocks

**Comment by bettermanbao** [comment]
其实我也只要一个单纯的kcptun，你懂的。

**Comment by xtaci** [comment]
嗯，我考虑下，小的image很容易，就是用alpine做基， 然后抓最新的release并解压出来就可以了。主要是脚本怎么写。

**Comment by bettermanbao** [comment]
他的dockerfile源码在这里，直接下载你release里的文件。模仿一下？
https://github.com/mritd/docker/blob/master/shadowsocks/Dockerfile

**Comment by bettermanbao** [comment]
每次发布release的时候更新一下dockerfile里面的release tag变量？

**Comment by xtaci** [comment]
要做小很简单啊，关键是自动化。

git push之后，hub.docker.com立即产生新的image。

手动改dockerfile不能流程化。

**Comment by xtaci** [comment]
如果你不在乎容器大小，目前的就是最佳的方案。

**Comment by bettermanbao** [comment]
好吧，你成功说服了我。
