### ISSUE TITLE
Error starting mipsle kcptun server on router

### ISSUE THREAD

**Issue by shounak-de** [xtaci/kcptun#401]
**admin@RT-AC66R-D700:/tmp/home/root# server_linux_mipsle -v**
kcptun version 20170120

**admin@RT-AC66R-D700:/tmp/home/root# server_linux_mipsle -l :37777 -t 127.0.0.1:7777 --crypt xor --key xxxxx --mtu 1400 --sndwnd 2048 --rcvwnd 2048 --mode fast2**
2017/02/08 01:00:17 version: 20170120
2017/02/08 01:00:17 listen udp :37777: errno -9
net.ListenUDP
github.com/xtaci/kcp-go.ListenWithOptions
        /Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:856
main.main.func1
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:325
github.com/urfave/cli.HandleAction
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:259
main.main
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:373
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_mipsx.s:944

**admin@RT-AC66R-D700:/tmp/home/root# server_linux_mipsle**
2017/02/08 01:03:47 version: 20170120
2017/02/08 01:03:47 listen udp :29900: errno -9
net.ListenUDP
github.com/xtaci/kcp-go.ListenWithOptions
        /Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:856
main.main.func1
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:325
github.com/urfave/cli.HandleAction
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:485
github.com/urfave/cli.(*App).Run
        /Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:259
main.main
        /Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:373
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_mipsx.s:944

**Comment by xtaci** [comment]
why are you running server on your router?

**Comment by bettermanbao** [comment]
server_linux_mipsle is ok.

see below log on my mt7620 router:
/tmp # ./server_linux_mipsle
2017/02/08 03:21:30 version: 20170120
2017/02/08 03:21:31 listening on: [::]:29900
2017/02/08 03:21:31 target: 127.0.0.1:12948
2017/02/08 03:21:31 encryption: aes
2017/02/08 03:21:31 nodelay parameters: 0 20 2 1
2017/02/08 03:21:31 sndwnd: 1024 rcvwnd: 1024
2017/02/08 03:21:31 compression: true
2017/02/08 03:21:31 mtu: 1350
2017/02/08 03:21:31 datashard: 10 parityshard: 3
2017/02/08 03:21:31 acknodelay: false
2017/02/08 03:21:31 dscp: 0
2017/02/08 03:21:31 sockbuf: 4194304
2017/02/08 03:21:31 keepalive: 10
2017/02/08 03:21:31 snmplog:
2017/02/08 03:21:31 snmpperiod: 60

**Comment by bettermanbao** [comment]
Known issue, kcptun can not run on kernel 2.x which merlin firmware use. 

See this post, same issue:
https://github.com/xtaci/kcptun/issues/57

**Comment by shounak-de** [comment]
> why are you running server on your router?
I use ss-server on my asus merlin router (shadowsocks-libev-polarssl) and then [shadowsocks-android](https://play.google.com/store/apps/details?id=com.github.shadowsocks) on my phone to have a secure sonnection to my home network

> Known issue, kcptun can not run on kernel 2.x which merlin firmware use.
Is there a workaround or alternate solution?

Here are the details of the firmware:
''admin@RT-AC66R-D700:/tmp/home/root# uname -a
Linux RT-AC66R-D700 2.6.22.19 #1 Fri Feb 3 00:20:05 EST 2017 mips ASUSWRT-Merlin**


>

**Comment by shounak-de** [comment]
Just saw the translation of #57 

Its okay to close this. I will wait till merlin uses a 3.x kernel or use a different firmware, if I choose to go that route.

Thank you
