### ISSUE TITLE
怎么限制 kcptun 服务器的 udp connections 数量？

### ISSUE THREAD

**Issue by qiang-yu** [xtaci/kcptun#402]
今天我的 vps 被 suspended 了，原因是  connection 太多了

这是 vps 服务商的回复

Your VPS is getting more connection on the hostnode.

=====
Thu Feb 9 00:08:17 2017; UDP; eth1; 540 bytes; from 58.79.225.220:42208 to 203.44.93.147:179
Thu Feb 9 00:08:17 2017; UDP; eth1; 540 bytes; from 58.79.225.220:42208 to 203.44.93.147:179
Thu Feb 9 00:08:17 2017; UDP; eth1; 540 bytes; from 58.79.225.220:42208 to 203.44.93.147:179
Thu Feb 9 00:08:17 2017; UDP; eth1; 540 bytes; from 58.79.225.220:42208 to 203.44.93.147:179
Thu Feb 9 00:08:17 2017; UDP; eth1; 540 bytes; from 58.79.225.220:42208 to 203.44.93.147:179
Thu Feb 9 00:08:17 2017; UDP; eth1; 80 bytes; from 203.44.93.147:179 to 58.79.225.220:42208 
.......  下面还有很多

问一下，有什么办法可以限制 kcptun 服务器端的 udp 链接数量吗？  限制一个最大数量多少，这样 vps 就不会被触发 suspend 了

急问，谢谢

**Comment by xtaci** [comment]
kcptun默认只有一个连接

**Comment by qiang-yu** [comment]
You can only use 100 conntrack per minute. 

这是 vps 提供商给的回复限制， 这个我在 debian x64 中可以怎么做限制呢？  kcptun 有设置吗？

kcptun 只有一个 udp 连接，那对应的 conntrack 消耗也是 1 吗？ 不懂这个，问一下哈

**Comment by qiang-yu** [comment]
======== 这是 kcptun server 设置
{
	"listen": ":162",
	"target": "127.0.0.1:443",
	"key": ".......",
	"crypt": "aes-128",
	"mode": "normal",
	"mtu": 512,
	"sndwnd": 640,
	"rcvwnd": 1024,
	"datashard": 30,
	"parityshard": 15,
	"dscp": 0,
	"nocomp": true
}

====   这是 kcptun client 设置，跑在 OpenWrt x64 的软路由上

{
  "localaddr": ":4443",
  "remoteaddr": ".......",
  "key": ".....",
  "crypt": "aes-128",
  "mode": "normal",
  "conn": 2,
  "autoexpire": 60,
  "mtu": 512,
  "sndwnd": 64,
  "rcvwnd": 1024,
  "datashard": 30,
  "parityshard": 15,
  "dscp": 0,
  "nocomp": true,
  "sockbuf": 4194304,
  "keepalive": 10
}

我这个配置会有什么问题导致   You can only use 100 conntrack per minute  超过限制吗？ 

谢谢

**Comment by qiang-yu** [comment]
我知道原因了， 我查了下，kcptun 一个 conn 会建立 2个 udp connection，客户端有 autoexpire 设置，当时服务器没有 autoexpire

在网络状况不好的时候，client 连接服务器老有问题，于是 client 就不断建立新的 udp connection 去连接 server，结果就是 server 有一堆 udp connection ，最后导致 vps 被 suspend 了

server 的 udp connection 可以加入 expire  设置吗？  这样 client 放弃的 udp connection 在 server 端也会自动超时关闭，防止超过 vps 的限制

**Comment by linhua55** [comment]
@qiang-yu  跟iptables有关，conntrack是iptables中的一个功能 模块
https://www.redhat.com/archives/rhl-list/2008-April/msg00365.html

**Comment by jack338c** [comment]
@qiang-yu 
hi qiang-yu
Could you update your repository--ShadowsocksVPN-openwrt later

It looks awesome
but I got "cannot  stat /home....ShadowsocksVPN/2.5.6/ssr-redir no such file or directory while compiling to my lede tree

after copy ssr-redir to the directory,it works

the tcp works ok, but udp is now working 
I try use udp_tcp instead of tcp_only in pdsnd.conf, NatTypeTester always shows "udp blocked"

Your help will be appericated
thank you qiang-yu
