### ISSUE TITLE
windows10客户端连接不正常

### ISSUE THREAD

**Issue by qyidc** [xtaci/kcptun#403]
已经试了好几个win10的电脑，不同的人，不同的地区，电脑都是win10，什么都正常，没有任何错误提示，就连shadowsocks的日志也没有任何错误提示，就是没有数据，同样配置，到win7就没有任何问题，有没有同样的情况的！

**Comment by lizongzeshunshun** [comment]
win10正常
能提供启动配置和Log吗

**Comment by MoeGakuen** [comment]
win10正常

**Comment by qiang-yu** [comment]
检查你的 win 10 的防火墙设置，应该是你的防火墙把 kcptun 的包拦截了，所以其实压根没有发出去或者收到任何包，所以 shadowsocks的日志 没有任何提示，因为它压根什么包都没收到
