### ISSUE TITLE
UDP 的 autoexpire 工作不正常

### ISSUE THREAD

**Issue by qiang-yu** [xtaci/kcptun#404]
版本 20170120 

client 的配置

{
  "localaddr": ":4443",
  "remoteaddr": ".......:162 ",
  "key": "..........",
  "crypt": "aes-128",
  "mode": "normal",
  "conn": 1,
  "autoexpire": 300,
  "mtu": 512,
  "sndwnd": 64,
  "rcvwnd": 1024,
  "datashard": 30,
  "parityshard": 15,
  "dscp": 0,
  "nocomp": true,
  "sockbuf": 4194304,
  "keepalive": 20
}

这里 autoexpire  300， 检查方式

cat /proc/net/nf_conntrack | grep udp | grep dport=162

由于 conn=1, autoexpire=300

我测试，kcp 会每隔 300 秒重新建立一个 udp 连接， 路由器设置的 udp timeout 是 180 秒

但是从 nf_conntrack  里面的数据看到， kcp 建立新链接之后， 旧的 udp 连接本来应该 180秒 倒计时慢慢结束，但是事实上，旧的 udp连接 的倒计时一直不断 reset 回到 180秒， 大概要等好几分钟才正真的进入 180秒 倒计时

导致的结果是， kcp 每次  autoexpire 之后就建立一个新的 udp 链接，但是旧的 udp链接 长时间都没有释放，一直保持着， 会保持很久，不知道是不是虽然 client 已经不用这个旧链接了，但是 sever 依然在不断往旧链接发包，导致旧链接始终没有释放，直到 server 的某种逻辑认为 client 已经挂掉了，才停止往 旧链接发包， 然后旧链接才真正的进入 udp timeout 的 180秒 倒计时

结论： autoexpire 参数如果不为 0， 会导致 kcp不断建立新链接，而旧的链接很长时间都不会释放，最终 conntrack 数量达到一定程度，VPS那边会触发 suspend

**Comment by xtaci** [comment]
不是你说的那样， udp本身是无连接的， 你可以尝试吧conntrack的180秒降低到30s

**Comment by xtaci** [comment]
而且我觉得这个问题和conntrack好像没关系，就是你的服务商误判。

**Comment by linhua55** [comment]
@qiang-yu 
应该可以用iptables限制一下吧
10. Block Network Flood on Apache Port with IPtables
Sometimes IP addresses may requests too many connections towards web ports on your website. This can cause number of issues and to prevent such problems, you can use the following rule:

# iptables -A INPUT -p tcp --dport 80 -m limit --limit 100/minute --limit-burst 200 -j ACCEPT
The above command limits the incoming connections from per minute to 100 and sets a limit burst to 200. You can edit the limit and limit-burst to your own specific requirements.

http://www.tecmint.com/linux-iptables-firewall-rules-examples-commands/
https://securedragon.net/clients/knowledgebase/177/What-is-conntrack-and-how-can-I-check-how-many-sessions-I-am-using.html

**Comment by qiang-yu** [comment]
我弄明白情况了

kcptun 的 autoexpire 设置 300， 所以每 300秒 会重新建立一个 udp session ，也就是 udp链接

之前的 udp session 只要之前走那个的 tcp 还在 (比如用户在看 youtube 电影，1个小时)，这个 udp session 就不会释放，会一直工作着，直到 tcp 结束位置

所以，我之前设置的 autoexpire 是 60秒， 每1分钟就重新建立一个新的 udp session，之前的旧 udp session 在看 youtube 电影，所以一直不会释放，这么算一下，一个小时会重新建立60个 udp session，如果之前的一直都被 youtube 看电影，那么一个小时就会同时有 60 个 udp 连接在工作， 这就是导致 conntrack 超出了

所以，要么 autoexpire 设置为 0，要么 autoexpire 不能设置太低，设置 300 或者更大，减少 udp session 的新建

问下，有可能让旧的 tcp 连接的数据全部走 新建立的 udp session 吗？ 而不是 旧的 tcp 始终在旧的 udp session 上跑，如果看了1个小时电影，那旧的 udp session 就会1个小时都不释放

**Comment by xtaci** [comment]
当然不是，expire后10分钟，强制掐断。

**Comment by qiang-yu** [comment]
哦哦，能改成 expire 之后立即掐断吗？ 或者 1分钟后 掐断？  不确定 10分钟 这个有没有特殊的考虑

**Comment by xtaci** [comment]
就是期待10分钟内，连接能自己关闭，而不是超过autoexpire就立即强制掐断。

**Comment by bettermanbao** [comment]
10分钟强制掐断，这么狠？
那我如果下载一个不支持断点续传的大文件，岂不是悲剧？

**Comment by xtaci** [comment]
哈哈，所以你们两位就代表了两个不同的需求，一个是希望立即掐断，一个是希望永不掐断。

**Comment by bettermanbao** [comment]
我只是认为已经建立的连接不应该被强制掐断。auto expire只需要针对新连接就可以了。

**Comment by xtaci** [comment]
@bettermanbao https://github.com/xtaci/kcptun/blob/master/client/main.go#L430
问题出在这里， 矛盾你已经看到了。

**Comment by xtaci** [comment]
@bettermanbao @qiang-yu 
https://github.com/xtaci/kcptun/commit/bf543cfd63ba63134c087220b6955004965faaa9

**Comment by bettermanbao** [comment]
perfect!!!

**Comment by bettermanbao** [comment]
0和-1一样？

**Comment by bettermanbao** [comment]
还是0是立即掐断，-1是永不掐断？

**Comment by xtaci** [comment]
对，-1用不掐断

**Comment by CuminLo** [comment]
@xtaci 平常看视频较多,是掐断好 还是不掐断?

**Comment by xtaci** [comment]
@CuminLo 90%的都应该掐断，几乎都会自动重连。

**Comment by theratlesnake** [comment]
@xtaci 那就是下载东西的时候，把autoexpire设置为-1吗？老大

**Comment by xtaci** [comment]
@theratlesnake scavengettl 设置为-1，新版本才有

**Comment by theratlesnake** [comment]
@xtaci   噢噢！感谢
