### ISSUE TITLE
是不是和3.0.1的shadowsocks-libev不兼容？

### ISSUE THREAD

**Issue by lingbaoboy** [xtaci/kcptun#405]
我使用2.5.*的shadowsocks-libev可以正常使用kcptun加速，今天蛋疼升级到了3.0.1的shadowsocks-libev，ss的配置没变使用的是chacha20加速，结果ss可以正常使用，kcptun却不能加速了kcptun的配置没变。
kcptun老版本和最新版本都试过了，使用kcptun加速打开网页会出现

```
此网站无法提供安全连接
www.google.com 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**Comment by CuminLo** [comment]
其实是SS的问题

**Comment by flynaj** [comment]
用kcptun就不需要ss。后端用的tinyproxy就行了。
