### ISSUE TITLE
最新版本仍会自动退出

### ISSUE THREAD

**Issue by cokll** [xtaci/kcptun#406]
我自己编译了一个最新的版本,但是客户端扔几小时自动退出
是否需要参数开启这项特性,我只更新了客户端服务端是否也要更新

**Comment by cokll** [comment]
`2017/02/18 01:08:23 stream closed
2017/02/18 01:08:23 stream closed
2017/02/18 01:08:23 stream opened
2017/02/18 01:08:24 stream opened
2017/02/18 01:08:24 stream opened
2017/02/18 01:08:24 stream opened
2017/02/18 01:13:42 accept tcp [::]:12450: accept4: too many open files`

我抓取的日志显示是打开的文件太多,并且我设置最大文件数8192似乎并没有什么改善
怎么解决这个问题

**Comment by xtaci** [comment]
ulimit -n

**Comment by cokll** [comment]
NAS> ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kb)             unlimited
stack(kb)            8192
coredump(blocks)     unlimited
memory(kb)           unlimited
locked memory(kb)    64
process              2737
nofiles              1024
vmemory(kb)          unlimited
locks                unlimited
NAS> ulimit -n 51200
NAS> ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kb)             unlimited
stack(kb)            8192
coredump(blocks)     unlimited
memory(kb)           unlimited
locked memory(kb)    64
process              2737
nofiles              51200
vmemory(kb)          unlimited
locks                unlimited

**Comment by xtaci** [comment]
执行这个后，在同一个shell下，启动程序。

**Comment by cokll** [comment]
我试试

**Comment by cokll** [comment]
还是一样的,目前我使用check脚本1分钟检查一次进程解决
