### ISSUE TITLE
PC端正常，手机端不能连接  Kcptun 版本为: 20170120

### ISSUE THREAD

**Issue by oscarbat** [xtaci/kcptun#407]
这个是我PC客户端数据：
"client_windows_amd64.exe" -l :9527 -r 23.105.213.110:883 -key "xxxxx" -crypt aes -datashard 10 -parityshard 3 -conn 5 -mtu 1024 -sndwnd 1024 -rcvwnd 1024 -dscp 0 -autoexpire 20 -acknodelay -keepalive 10 -sockbuf 4194304 -mode fast
PC端能够正常使用，但是手机端上面参数写上
--key xxxxx --crypt ses --mode fast --datashard 10 --parityshard 3  --dscp 0
后就不能上网了。哪里写错了吗？还是格式不对？
我是上面正常输入SS数据，只是在"Plguin"点"disable"的"Configure"填写kcp的参数。对吗？

**Comment by whour** [comment]
你手机客户端和你PC端的配置一样吗？对照自己的参数。

**Comment by terrytw** [comment]
手机端crypt ses?
顺便你的服务器ip地址已经暴露

**Comment by oscarbat** [comment]
问题貌似解决了~只是还不会按照自己的网速优化~设置都是默认。
