### ISSUE TITLE
一个端口只能对应一个客户端吗

### ISSUE THREAD

**Issue by komite** [xtaci/kcptun#408]
如题，一个端口只能对应一个客户端吗，我启用多个客户端就频繁断开

**Comment by waeart** [comment]
请修改连接参数
--conn value                     set num of UDP connections to server (default: 1)

**Comment by xtaci** [comment]
N:M的 ， -conn最好为1,   N:1

**Comment by Anikilulala** [comment]
@xtaci 抱歉，能否劳烦解释一下，比如我现有一个WIN CLIENT和一个手机端，是否需要设定不同的端口，或者是如上所说修改参数，或者是可以直接使用？

**Comment by xtaci** [comment]
直接用

**Comment by Anikilulala** [comment]
了解，TY
