### ISSUE TITLE
关于rcvwnd和sndwnd参数

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#409]
目前遇到一个问题，server和client之间的ping值白天稳定在40ms左右，晚上会上升到100ms。

这样使用固定的sndwnd/rcvwnd就会发生白天速度比晚上快很多的情况。

能否考虑增加snd bandwidth/rcv bandwidth的参数，转为限制带宽，而不是限制发包数？

我看公式只涉及到rtt的运算，kcptun内部应该是知道实时的rtt的，不知实现起来是否复杂？谢谢！

**Comment by bettermanbao** [comment]
为了参数兼容，可以保留目前的sndwnd/rcvwnd作为最大发包窗口，如果用户设置了snd bandwidth/rcv bandwidth，则kcptun可以根据rtt动态调整实时窗口。

**Comment by xtaci** [comment]
想了下，其实不用增加参数， 以当前的  mtu*wnd/srtt 作为内部值，只要程序不重启，就可以尝试保持带宽。

**Comment by xtaci** [comment]
第二个问题是，合理性，保持带宽的方式是不是正确的。rtt延迟通常反映了拥塞，保持wnd不变是比较利他的方式。

**Comment by bettermanbao** [comment]
在应用层面，网络程序本身希望的肯定是一个稳定的带宽，所以我觉得保持带宽还是很有必要的。
并且rtt在某些isp下，可能遇到人为(Q)恶(O)化(S)。

**Comment by xtaci** [comment]
我先思考下，完全刚性的带宽始终感觉姿势不对。 

激进 和 保守之间的平衡点难以掌控。

**Comment by bettermanbao** [comment]
rcvbdw/sndbdw默认值是0，这样不触发保持带宽。如果用户设置了值，就尝试动态调整rcvwnd/sndwnd，保持带宽。但是动态调整的值不大于参数里设置的rcvwnd/sndwnd。做到相对公平。动态调整功能仅在客户端实现，但是实时rtt如何取平均值，需要思考一下。

**Comment by xtaci** [comment]
嗯，先讨论下吧，如果这个程序一开，就把内网的其他手机，下载之类的带宽抢完了，也不太好是吧。

**Comment by bettermanbao** [comment]
还有一点，我相信目前很多用户为了追求带宽，肯定会计算在rtt最大时需要的最小window。这样在凌晨这种rtt相对较低的情况下，反而是在浪费带宽。所以我觉得如果可以控制带宽，反而是一种公平使用带宽。

**Comment by bettermanbao** [comment]
你提到的带宽抢完，我认为实际情况不是这样的。比如我需要稳定观看4K视频，那我只要设置保持20M带宽。原来的情况肯定需要把窗口调大到最小带宽是20M。

**Comment by xtaci** [comment]
主要是解决这个“刚性”

**Comment by notedit** [comment]
感觉你们考虑的都是c端的情况,   我这边的场景是服务端   比如流媒体服务器  有没有在这个方向上有一些优化

**Comment by bettermanbao** [comment]
刚性可以理解为动态sndwnd最大刚到用户设置的sndwnd，这样就不会刚过头了。

**Comment by yydcool** [comment]
你们讨论的时候是否忽略了在kcptun两侧的tcp连接已经有窗口控制了？我认为窗口控制不应该归kcptun管，也不应有抢带宽的问题，上层tcp会自行退让的。

**Comment by xtaci** [comment]
@yydcool 不一样， 两侧的tcp是属于API流控(buffer控制），不是拥控(cwnd)。通常假设buffer永远不会填满(producer < consumer)
