### ISSUE TITLE
Does KCPTUN support IPv6

### ISSUE THREAD

**Issue by nicedayever** [xtaci/kcptun#41]
if not, pls add the ipv6 support.
if so, pls tell me how to config the client when ipv6 addr is used.

**Comment by jannson** [comment]
应该支持的吧。golang 默认都绑定的 ipv6 的地址。直接把各个地址填写为 ipv6 就可以了阿？

**Comment by caidaoli** [comment]
亲测可以支持的
client_darwin_amd64 -l :4440 -r v6域名:29900 -key 密码 -mtu 1400 -sndwnd 256 -rcvwnd 2048 -mode fast2 -conn 4

**Comment by nicedayever** [comment]
@caidaoli 用最新版的亲测不可以，按照你这种方式写好了，连接不上，通过netstat -an 查询，也没有看到与远程端口建立连接

**Comment by nicedayever** [comment]
@caidaoli 用最新版的亲测不可以，按照你这种方式写好了，连接不上，通过netstat -an 查询，也没有看到与远程端口建立连接

**Comment by caidaoli** [comment]
我是osx，完全没有问题的。2016/06/22 20:13:43 version: 20160620
2016/06/22 20:13:43 listening on: [::]:4440
2016/06/22 20:13:43 encryption: aes
2016/06/22 20:13:43 nodelay parameters: 1 20 2 1
2016/06/22 20:13:43 remote address: [2400:8900::f03c:91ff:fe50:5f30]:29900
2016/06/22 20:13:43 sndwnd: 256 rcvwnd: 2048
2016/06/22 20:13:43 mtu: 1400
2016/06/22 20:13:43 fec: 4
2016/06/22 20:13:43 acknodelay: false
2016/06/22 20:13:43 dscp: 0
2016/06/22 20:13:43 conn: 4

**Comment by xtaci** [comment]
各位，测试下0623的版本

**Comment by nicedayever** [comment]
@xtaci i forgot to tell u my info:
WIN10 X64, SSR 3.7.4 CLIENT,  NATIVE IPV6 addr from CERNET.

**Comment by caidaoli** [comment]
2016/06/23 22:10:52 listening on: [::]:4440
2016/06/23 22:10:52 encryption: aes
2016/06/23 22:10:52 nodelay parameters: 1 20 2 1
2016/06/23 22:10:52 remote address: [马赛克]:29900
2016/06/23 22:10:52 sndwnd: 256 rcvwnd: 2048
2016/06/23 22:10:52 mtu: 1400
2016/06/23 22:10:52 datashard: 10 parityshard: 3
2016/06/23 22:10:52 acknodelay: false

osx 系统，完全没问题
2016/06/23 22:10:52 dscp: 0
2016/06/23 22:10:52 conn: 4

**Comment by xtaci** [comment]
@nicedayever  程序对 ipv6没有做任何限制，你只能自己排查问题了。
