### ISSUE TITLE
关于Windows 系统下无法连接的问题

### ISSUE THREAD

**Issue by crazyxhz** [xtaci/kcptun#410]
问题如下。kcptun 版本，客户端服务器端都是最新的`20170221`
服务器端操作系统，`debian8 `
服务器命令行参数：
```
./server_linux_amd64 -t "vpsip:8888" -l ":4000" -mode fast2 -mtu 1350 -sndwnd 1024 -rcvwnd 1024 -key aaabbb -crypt aes 
```
Windows 客户端参数：
```
client_windows_386 -mode fast2 -mtu 1350 -sndwnd 128 -rcvwnd 1024 -key aaabbb -crypt aes -r "vpsip:4000" -l ":1082"
```
然后Windows SS客户端开启Forward Proxy，选择Socks5代理，1082端口，客户端服务器端的输出都提示stream opened，但是无法连接![](https://ooo.0o0.ooo/2017/02/23/58ae4d8dba982.jpg)

**然后问题的关键来了**，使用同样的客户端参数，在ac68u小宝固件Shadowsocks中设置同样的KCP参数，可以正常连接，网络环境都一致，唯一不同的一个是 arm客户端，一个是Windows客户端（32,64的都试过）

**Comment by Ghost-Zhou** [comment]
我也碰到了和楼上一样的问题，在一台win7 32位的系统下运行正常，换到win10 64位系统下无法使用，看日志出现了session normally closed

**Comment by yyjdelete** [comment]
kcp本来就不是选Forward Proxy的, 而是直接连本地的1082端口

**Comment by dearneo** [comment]
楼上正解，应该是ss客户端设置错了
