### ISSUE TITLE
卡在snmpperiod: 60处 不能连接

### ISSUE THREAD

**Issue by glolionline** [xtaci/kcptun#411]
去年9月份设置好了一直用的没问题(当时用的20160922版本)
过年期间突然无法使用了。
现在我更新了服务端和客户端的版本(都是20170221),然后发现还是有问题。

我更新版本的时候是直接用的去年配置好的文件，只是替换了server_linux_amd64文件。
这是配置:
{
    "listen": ":29900",
    "target": "127.0.0.1:443",
    "key": "gloli",
    "crypt": "salsa20",
    "mode": "fast2",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}
客户端用的界面配置管理工具，输出信息
*************************** begin ***************************
2017/02/24 09:16:07 version: 20170221
2017/02/24 09:16:07 listening on: [::]:12948
2017/02/24 09:16:07 encryption: salsa20
2017/02/24 09:16:07 nodelay parameters: 1 20 2 1
2017/02/24 09:16:07 remote address: vpsIP:29900
2017/02/24 09:16:07 sndwnd: 1024 rcvwnd: 1024
2017/02/24 09:16:07 compression: true
2017/02/24 09:16:07 mtu: 1350
2017/02/24 09:16:07 datashard: 70 parityshard: 30
2017/02/24 09:16:07 acknodelay: false
2017/02/24 09:16:07 dscp: 46
2017/02/24 09:16:07 sockbuf: 4194304
2017/02/24 09:16:07 keepalive: 10
2017/02/24 09:16:07 conn: 1
2017/02/24 09:16:07 autoexpire: 0
2017/02/24 09:16:07 scavengettl: 600
2017/02/24 09:16:07 snmplog: 
2017/02/24 09:16:07 snmpperiod: 60

只是这时候我查询发现服务端没有输出log信息，我又使用了一个自动配置的脚本，采用合之前一样的配置，发现服务端log信息也是卡在了snmpperiod这儿，如下:
2017/02/23 20:07:54 version: 20170221
2017/02/23 20:07:54 listening on: [::]:29900
2017/02/23 20:07:54 target: 127.0.0.1:443
2017/02/23 20:07:54 encryption: salsa20
2017/02/23 20:07:54 nodelay parameters: 1 20 2 1
2017/02/23 20:07:54 sndwnd: 1024 rcvwnd: 1024
2017/02/23 20:07:54 compression: true
2017/02/23 20:07:54 mtu: 1350
2017/02/23 20:07:54 datashard: 70 parityshard: 30
2017/02/23 20:07:54 acknodelay: false
2017/02/23 20:07:54 dscp: 46
2017/02/23 20:07:54 sockbuf: 4194304
2017/02/23 20:07:54 keepalive: 10
2017/02/23 20:07:54 snmplog:
2017/02/23 20:07:54 snmpperiod: 60

都是卡在了snmpperiod: 60这儿，不知道是什么原因呢?在之前的问题里找了找也没找到相似的情况。

**Comment by xtaci** [comment]
换个端口试试，比如listen到 443

**Comment by glolionline** [comment]
可是ss用的443呀，listen能同时用443么?

**Comment by wxyzh** [comment]
@glolionline ss关掉UDP试试呢
