### ISSUE TITLE
客户端无法监听同一ip的不同端口

### ISSUE THREAD

**Issue by juyfchn** [xtaci/kcptun#413]
参数
/Applications/client_darwin_amd64_2 -r “173.254.232.*:29901” -l ":16666” -mode fast2 -crypt salsa20 -key “*” -autoexpire 60 -datashard 5 -parityshard 5 -rcvwnd 600 -sndwnd 200 -dscp 46 -mtu 512
结果
2017/03/01 13:40:15 listen tcp :12948: bind: address already in use
但是，对于同一个vps，另一个却可以监听。参数如下
/Applications/client_darwin_amd64_1 -r “173.254.232.*:29900" -l ":12948" -mode fast2 -crypt salsa20 -key “*" -autoexpire 60 -datashard 5 -parityshard 1 -rcvwnd 300 -sndwnd 256 -dscp 46。
感觉同一台电脑不能同时监听同一vps的多个端口。然后我用手机试了一下，发现手机可以监听16666端口。

然后我试着退出监听12948的客户端，运行监听16666的客户端，参数如下
2017/03/01 13:50:53 version: 20170301
2017/03/01 13:50:53 listening on: **[::]:12948**
2017/03/01 13:50:53 encryption: salsa20
2017/03/01 13:50:53 nodelay parameters: 1 40 2 1
2017/03/01 13:50:53 remote address: **173.254.232.22:29901” -l :16666”**
2017/03/01 13:50:53 sndwnd: 200 rcvwnd: 600
2017/03/01 13:50:53 compression: true
2017/03/01 13:50:53 mtu: 512
2017/03/01 13:50:53 datashard: 5 parityshard: 5
2017/03/01 13:50:53 acknodelay: false
2017/03/01 13:50:53 dscp: 46
2017/03/01 13:50:53 sockbuf: 4194304
2017/03/01 13:50:53 keepalive: 10
2017/03/01 13:50:53 conn: 1
2017/03/01 13:50:53 autoexpire: 60
2017/03/01 13:50:53 scavengettl: 600
2017/03/01 13:50:53 snmplog:
2017/03/01 13:50:53 snmpperiod: 60
竟然无法识别监听参数参数了。

**Comment by dearneo** [comment]
明显是参数填写的问题，参数里面的双引号“”和""不要混着用
