### ISSUE TITLE
好像有内存泄漏

### ISSUE THREAD

**Issue by liaoyangyang** [xtaci/kcptun#415]
3月的服务器版本好像都有内存泄漏（用过3月1号，2号，3号），我用的是linux_amd64（client 和server都是），2月份的好像没有，我现在换成2月的试试，配置什么的都没有改过，还是说新版本有新策略？？？
![qq 20170308102428](https://cloud.githubusercontent.com/assets/10610029/23687438/6d6dcd2c-03e9-11e7-805f-916c4b574ac3.png)

图片中很急的拐点都是我重启的时候，我的vps本来每天5点左右就会重启

**Comment by everfly** [comment]
有类似同样问题，不过没这么严重，之前本来想发个issue，后来不是太确定就删了。
![tim 20170308103701](https://cloud.githubusercontent.com/assets/7139571/23687788/4506f37a-03eb-11e7-8e4e-0ff1412604c0.png)
服务器内存占用在4、5、6这几天比较严重，然后就换回二月版本了，后面就没有类似问题了。

**Comment by xtaci** [comment]
哦？ 确实有内存使用方面的调整，检查一下。

**Comment by xtaci** [comment]
这个版本改动比较大，可能会有些问题。

**Comment by dearneo** [comment]
内存的确比之前的版本高些，但似乎没你们的严重。每天6点定时重启kcptun服务

![20170308104213](https://cloud.githubusercontent.com/assets/1540179/23687950/3cb1e788-03ec-11e7-8956-e54e8a130c64.png)

**Comment by xtaci** [comment]
试下我刚编译的版本， 另外，设置GOGC=20 ./server_xx 启动可以提高垃圾回收频率

[kcptun-darwin-386-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826484/kcptun-darwin-386-20170308.tar.gz)
[kcptun-darwin-amd64-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826482/kcptun-darwin-amd64-20170308.tar.gz)
[kcptun-freebsd-386-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826481/kcptun-freebsd-386-20170308.tar.gz)
[kcptun-freebsd-amd64-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826483/kcptun-freebsd-amd64-20170308.tar.gz)
[kcptun-linux-386-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826486/kcptun-linux-386-20170308.tar.gz)
[kcptun-linux-amd64-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826485/kcptun-linux-amd64-20170308.tar.gz)
[kcptun-linux-arm-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826487/kcptun-linux-arm-20170308.tar.gz)
[kcptun-linux-mips-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826489/kcptun-linux-mips-20170308.tar.gz)
[kcptun-linux-mipsle-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826488/kcptun-linux-mipsle-20170308.tar.gz)
[kcptun-windows-386-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826490/kcptun-windows-386-20170308.tar.gz)
[kcptun-windows-amd64-20170308.tar.gz](https://github.com/xtaci/kcptun/files/826491/kcptun-windows-amd64-20170308.tar.gz)

**Comment by liaoyangyang** [comment]
嗯，我试试，不过我的服务器好几个人再用，估计得一两天才能大致看出是否改善

**Comment by everfly** [comment]
@xtaci 经过两个小时左右的连续播放测试，使用版本`kcptun-linux-amd64-20170308.tar.gz`，状况如下：内存使用率上升趋势变缓，但是最终使用率还是很高，
这个是连续两小时左右播放后的内存使用率:
![1](https://cloud.githubusercontent.com/assets/7139571/23690737/f0e13b98-03fe-11e7-9430-56b230ca8c54.png)
然后结束掉kcptun进程后的内存使用率:
![4](https://cloud.githubusercontent.com/assets/7139571/23690843/a6b1ac00-03ff-11e7-9eb8-bae1274e2d66.png)
服务器后台统计如下：
![3](https://cloud.githubusercontent.com/assets/7139571/23690783/4467f36a-03ff-11e7-9890-7db6bba82642.png)
其中10点的时候内存占用率为：
`2017/03/08 10:00:02: Allocated MB: 714 Used MB: 319`
12：55时占用率：
`2017/03/08 12:55:02: Allocated MB: 813 Used MB: 414`
这期间其它进程和平时一样，只多开了一个kcptun进程

**Comment by xtaci** [comment]
确实很奇怪，我的vultr平时也就最多70MB

**Comment by xtaci** [comment]
@everfly 用我最新的release测试吧，设计上确实会多用内存，但不至于会这么夸张。

**Comment by everfly** [comment]
好的，我用最新版本试试看

**Comment by bettermanbao** [comment]
我也观察到这个现象了，只有一个人在用。
刚才看了下内存飙到200多M，以前100多M都很少见。

麻烦 @xtaci 大神看看吧，谢谢！

**Comment by xtaci** [comment]
@bettermanbao 客户端还是服务器

**Comment by bettermanbao** [comment]
服务器 @xtaci

**Comment by bettermanbao** [comment]
刚换了0308版，等我看看是否改善。

**Comment by liaoyangyang** [comment]
今天的release服务器版本应该还有内存泄漏，启动时设置了GOGC=20 
今天下午2点使用release版本，播了大概45分钟youtube 视频，之后轻度使用
![screenshot from 2017-03-08 16-41-45](https://cloud.githubusercontent.com/assets/10610029/23696333/2c828a2a-041e-11e7-9811-88a2d6b1124e.png)

**Comment by xtaci** [comment]
[kcptun-linux-386-20170308.tar.gz](https://github.com/xtaci/kcptun/files/827081/kcptun-linux-386-20170308.tar.gz)
[kcptun-linux-amd64-20170308.tar.gz](https://github.com/xtaci/kcptun/files/827082/kcptun-linux-amd64-20170308.tar.gz)

这个是之前的内存控制／发送队列方式。

**Comment by liaoyangyang** [comment]
@xtaci  client和server 不需要版本一致吧

**Comment by xtaci** [comment]
不需要一致

**Comment by xtaci** [comment]
3月的版本结构上优化比较大，肯定会有不少问题，感谢各位的测试。

**Comment by bettermanbao** [comment]
负优化吗？哈哈哈哈哈。。。。

**Comment by xtaci** [comment]
主要是针对服务器的优化，大量连接 > 5K 的优化措施，针对游戏的。

**Comment by bettermanbao** [comment]
你还把kcptun用在生产环境啊？？？

**Comment by xtaci** [comment]
@bettermanbao 好多把kcp-go用于生产环境的啊， 生产环境远没有kcptun的用法那么高要求。游戏的话甚至不需要FEC，窗口32就足够了。

**Comment by liaoyangyang** [comment]
![qq 20170309085228](https://cloud.githubusercontent.com/assets/10610029/23730984/cb2235e0-04a5-11e7-8374-f5dfadb1872d.png)
@xtaci 使用你在最近回复的版本（之前的内存控制），没有使用GOGC变量，从昨天下午5点左右开始启动，今天早上5点定时重启，几乎没有使用vps

**Comment by xtaci** [comment]
是问题解决了？

**Comment by liaoyangyang** [comment]
额，没有吧，内存还是缓慢的增长，你看看趋势，从昨天17：00 到今天5:00 ，从今天5:00重启之后还在增长

**Comment by nylqd** [comment]
![image](https://cloud.githubusercontent.com/assets/3632490/23733366/8051011e-04b3-11e7-9f4a-2e91eb511a1d.png)
同样发现这个问题，虽然没有这么严重，内存占用在缓慢上升

**Comment by xtaci** [comment]
<img width="736" alt="2017-03-09 10 45 56" src="https://cloud.githubusercontent.com/assets/2346725/23733751/97ee7fca-04b5-11e7-8487-26b47241028f.png">


这是我跑了12个小时的结果， 26M 服务器，差别这么大。

**Comment by liaoyangyang** [comment]
我的可能是有好几个人在使用的缘故，内存上升的比较快，并且我在服务端运行了3个server程序，不过一个空跑，一个几乎不用，这两个没什么变化，一个正常使用，可以不怎么使用的一个5M内存，一个11M左右，正常使用的增长快

```bash
[root@localhost ~]# 
[root@localhost ~]# ps aux|grep server_
root       131  0.4 23.1 190644 121584 ?       Sl   16:00   1:42 ./server_linux_amd64 -c /opt/kcptun/server-config.json
root       132  0.0  0.2   5428  1192 ?        Sl   16:00   0:00 ./server_linux_amd64 -c /opt/kcptun/server-config29905.json
root       133  0.0  0.8  11192  4688 ?        Sl   16:00   0:13 ./server_linux_amd64 -c /opt/kcptun/server-config29910.json
root       600  0.0  0.1 112600  1032 pts/0    S+   21:51   0:00 grep --color=auto server_
[root@localhost ~]# 
[root@localhost ~]# 
```

**Comment by xtaci** [comment]
[kcptun-linux-386-20170309.tar.gz](https://github.com/xtaci/kcptun/files/829611/kcptun-linux-386-20170309.tar.gz)
[kcptun-linux-amd64-20170309.tar.gz](https://github.com/xtaci/kcptun/files/829612/kcptun-linux-amd64-20170309.tar.gz)

试下这个吧，有个地方确实可能会延迟回收，但不清楚是不是这个原因。

**Comment by nylqd** [comment]
![image](https://cloud.githubusercontent.com/assets/3632490/23738303/0812057a-04d3-11e7-84ec-b6b8134bf5ee.png)
目前看来有改善

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/commit/947067cce2e8874efac6a89aa82273378a591617

**Comment by xtaci** [comment]
已经更新到最新的release，一行代码变更。

**Comment by bettermanbao** [comment]
我上午刚conrtab里加了个每天自动重启，你就修好了。。。。。。
真不知道该高兴还是。。。。。。

anyway, thanks!

**Comment by liaoyangyang** [comment]
额，我的还没改善啊，用的是上面说的3月9号版本
从15点开始看，之前client全部关闭，因此内存没涨，之后正常使用，早上5点自动重启

![screenshot from 2017-03-10 08-47-36](https://cloud.githubusercontent.com/assets/10610029/23777317/c9010880-056e-11e7-9a79-cb34d3e24c53.png)
![screenshot from 2017-03-10 08-54-07](https://cloud.githubusercontent.com/assets/10610029/23777380/25f0880e-056f-11e7-80e6-e3f88a4ed366.png)

**Comment by bettermanbao** [comment]
昨天下午更新的最新版，目前84M内存。继续观察中。。。

**Comment by everfly** [comment]
<img width="981" alt="qq20170310-095550 2x" src="https://cloud.githubusercontent.com/assets/7139571/23778858/c7de9d56-0577-11e7-822e-559f8f414b9b.png">
图中：20:50之前用的是最新编译版本，之后换回的20170221版本，内存变化却实存在非常大的差异。最新的编译版本似乎并未解决内存占用问题

**Comment by xtaci** [comment]
目前来说, 0221和0308没有功能上的差异，只是针对服务器端的大量连接的优化措施（主要针对游戏服务器的需求>5K connections)，内存问题会持续优化。

看@everfly的图来说，20:50之前和之后，基本在同一条水平线上啊。

@liaoyangyang 的图确实比较奇怪，建议测试下GOGC=20后启动server并观察。

**Comment by everfly** [comment]
不是的，18:00-20:50这个期间差不多是更换最新编译版本的期间，之前仍然用的是0221版本，更换最新版本后内存上升较快，而20:50之后更换回0221版本，内存使用就占有很小了，

**Comment by xtaci** [comment]
大概有多少用户，窗口多大，fec参数如何

**Comment by everfly** [comment]
自用的，期间播放时间较长。fec（0，0），之前用的（10，3），都能流畅1080p，2k，窗口1024，128

**Comment by everfly** [comment]
<img width="980" alt="qq20170310-103152 2x" src="https://cloud.githubusercontent.com/assets/7139571/23779678/d0d093e2-057c-11e7-863f-797d0567fe4b.png">
一周内存使用图，缓慢爬上至峰值出用的是3月版本，平滑出用的是二月版本，小波动出为使用二月版本播放长时间的内存占用，峰值为3月版本长时间播放内存占用

**Comment by xtaci** [comment]
@everfly 嗯，内存会继续优化，虽然手游服务器接入肯定是4C／8G的配置，但长期的内存稳定性依然很重要。

**Comment by xtaci** [comment]
[kcptun-linux-386-20170310.tar.gz](https://github.com/xtaci/kcptun/files/832998/kcptun-linux-386-20170310.tar.gz)
[kcptun-linux-amd64-20170310.tar.gz](https://github.com/xtaci/kcptun/files/832999/kcptun-linux-amd64-20170310.tar.gz)

@everfly 试下这个

**Comment by xtaci** [comment]
[kcptun-linux-386-20170310.tar.gz](https://github.com/xtaci/kcptun/files/833149/kcptun-linux-386-20170310.tar.gz)
[kcptun-linux-amd64-20170310.tar.gz](https://github.com/xtaci/kcptun/files/833150/kcptun-linux-amd64-20170310.tar.gz)


这个应该是控制到极限的内存。

**Comment by xtaci** [comment]
一样

**Comment by everfly** [comment]
UPDATE一下LINODE上面的内存使用情况：
![1](https://cloud.githubusercontent.com/assets/7139571/23819639/fbbfe72a-0643-11e7-9db2-98f231546ca5.png)
网络使用情况：(GMT时间）
![network](https://cloud.githubusercontent.com/assets/7139571/23819684/7b8c7cac-0644-11e7-9ba8-3c0302445a56.png)

server_linux_amd64进程内存使用情况：
![2](https://cloud.githubusercontent.com/assets/7139571/23819718/f43622fc-0644-11e7-8cb8-db94676fddf9.png)

一长段直线这期间内存占用是60M
由于免费版只能监控过去12小时的使用情况，这段时间使用kcp时间并不长，不过目前来看，不知道为什么内存占用只要开始使用就是在一直上升

**Comment by xtaci** [comment]
@everfly ps的结果是kcptun占用了80m是吧，但你的系统总体占用了170mb?

**Comment by everfly** [comment]
@xtaci ps的结果并不是最新的，只是为了显示开了两个进程，下面的内存图片是kcp server进程占用的内存，不是系统的，linode可以监控单独进程内存占用

**Comment by xtaci** [comment]
[kcptun-linux-386-20170311.tar.gz](https://github.com/xtaci/kcptun/files/835508/kcptun-linux-386-20170311.tar.gz)
[kcptun-linux-amd64-20170311.tar.gz](https://github.com/xtaci/kcptun/files/835509/kcptun-linux-amd64-20170311.tar.gz)

@everfly 试下这个。

**Comment by fanwz** [comment]
@xtaci 今天刚用上0310的版本，测试没多久VPS的内存就满了。现在0311这个是不是解了那个问题的？

**Comment by fanwz** [comment]
@xtaci 刚才测试了0311的版本，SERVER端的内存还是会一直涨，断开CLIENT端后内存还是不会减下来。

**Comment by everfly** [comment]
@xtaci 测试0311版本，确实并没有改善的样子
`root@ubuntu:~# ps aux|grep server_linux_amd64 
root     23657  4.4 14.1 166060 143644 pts/2   Sl+  07:27  11:27 ./server_linux_amd64 -c config101.json
root     23736  1.0  1.3  24188 14008 pts/5    Sl+  07:28   2:50 ./server_linux_amd64 -c config505.json
root     28691  0.0  0.0  14224   964 pts/1    S+   11:47   0:00 grep --color=auto server_linux_amd64
`
![1111](https://cloud.githubusercontent.com/assets/7139571/23823011/c1b042f0-0693-11e7-9ca0-5d8ddac52bac.png)

**Comment by xtaci** [comment]
非常好奇是什么场景导致的， 我这里的内存使用，也就14MB而已。

**Comment by everfly** [comment]
使用场景很简单。。。比如看sky news live，直接就长时间开着的而已，比如连续一小时1080p，期间第二台电脑也可能同时看看其他视频而已，目前在监控0221版本，同样的播放目前内存占用在40M然后就稳定在这了，暂时观测到是这样的内存占用，以前也没仔细看过

**Comment by xtaci** [comment]
开sky news看了几十分钟，内存27MB

**Comment by everfly** [comment]
配置文件（各个测试版本配置都是这个，有的时候会改为"datashard": 10,"parityshard": 3；客户端"rcvwnd": 1024,"sndwnd": 64,"autoexpire": 60,"dscp": 46,其他相同）：
![2017-03-11_215340](https://cloud.githubusercontent.com/assets/7139571/23823798/47c7cdca-06a5-11e7-89d8-a06dd9021217.png)
下面是刚刚使用0221版本的效果：
![2017-03-11_215157](https://cloud.githubusercontent.com/assets/7139571/23823806/70bf2304-06a5-11e7-94bb-ac51beb33a25.png)
流量图只是为了表示不同版本播放期间流量是大致差不多的
![2017-03-11_214555](https://cloud.githubusercontent.com/assets/7139571/23823809/77d6d2fe-06a5-11e7-8126-456902d92608.png)

**Comment by xtaci** [comment]
@everfly 怪得是我无法重现， 你开了压缩么？我的内存用量也就25MB

**Comment by everfly** [comment]
@xtaci "nocomp": true

**Comment by BH4WHN** [comment]
同样的问题3月的所有版本连接时间一长vps都直接跪，严重到会宕机，且看视频启动带宽明显降低，速度上不来。C/S端同样的配置退回2月版本就正常了。

**Comment by huawuxin** [comment]
我这里也是3月3日开始最大内存占用大涨。所以应该是3月3日版本某个还没被怀疑到的改动引起的。

我的服务器端系统CentOS 6，同时运行了5个服务端（常用其中两个），kcptun参数基本都是默认设置：server_linux_amd64 --listen :290 --target 127.0.0.1:300 --key XXX --mode fast2 >/dev/null 2>&1 &，5个都是类似的。

![snag-0000](https://cloud.githubusercontent.com/assets/2068446/23830307/b0b5126e-0742-11e7-9604-b131646c111f.png)

**Comment by xtaci** [comment]
好的， 那就一个个排查。
[kcptun-linux-386-20170312.tar.gz](https://github.com/xtaci/kcptun/files/836409/kcptun-linux-386-20170312.tar.gz)
[kcptun-linux-amd64-20170312.tar.gz](https://github.com/xtaci/kcptun/files/836410/kcptun-linux-amd64-20170312.tar.gz)

这是回滚的第一个变动，https://github.com/xtaci/kcp-go/blob/c40f2d6e1ae6c1f7d793a97b6009568e6ebc5b97/kcp.go

看下内存情况

**Comment by xtaci** [comment]
主要是我这里无法成功重现，靠你们的测试来排查问题了。
@everfly @huawuxin @BH4WHN @bettermanbao

**Comment by huawuxin** [comment]
我服务端已换0312，明天报告结果。

**Comment by xtaci** [comment]
[kcptun-linux-386-20170312.tar.gz](https://github.com/xtaci/kcptun/files/836431/kcptun-linux-386-20170312.tar.gz)
[kcptun-linux-amd64-20170312.tar.gz](https://github.com/xtaci/kcptun/files/836432/kcptun-linux-amd64-20170312.tar.gz)

这个是改动会降低ack分配的内存。

@huawuxin 不会影响服务器

**Comment by everfly** [comment]
>好的， 那就一个个排查。
kcptun-linux-386-20170312.tar.gz
kcptun-linux-amd64-20170312.tar.gz
这是回滚的第一个变动，https://github.com/xtaci/kcp-go/blob/c40f2d6e1ae6c1f7d793a97b6009568e6ebc5b97/kcp.go
看下内存情况

短时测试了下这个版本，应该同样的是有内存泄漏；时间不太长，只能看个趋势：
![2017-03-12_201326](https://cloud.githubusercontent.com/assets/7139571/23831641/b03a2e8c-0760-11e7-8439-0575b287c83e.png)
![2017-03-12_201901](https://cloud.githubusercontent.com/assets/7139571/23831672/5907bd2c-0761-11e7-8602-4f0970b96dc2.png)
![2017-03-12_201647](https://cloud.githubusercontent.com/assets/7139571/23831650/e81fcfdc-0760-11e7-9d65-dbd6d6dcea93.png)

**Comment by xtaci** [comment]
<img width="674" alt="2017-03-12 8 32 45" src="https://cloud.githubusercontent.com/assets/2346725/23831795/13edc23e-0763-11e7-8336-f10afbff6773.png">

这个是我运行了一个多小时的server, 客户端300s autoexpire, 差别太大。

**Comment by everfly** [comment]
我这边是Linode $5，运行0221版本的话，使用率和你这个差不多。整天连续使用也基本不会超过50MB，或则说0221之前的版本都没有此问题，第一次注意到这个问题是有一次banwagon后台发现内存占用变红了，平时从来都没出现过这个现象的，kill掉kcptun进程就恢复正常了，当时使用的是3月版本，但是看issue里面没人提出这个问题，以为是个人原因就没提，后来来回折腾发觉3月版本一直有问题，换回2月版本就好了，看这个issue里面有同样问题的也挺多的，应该不是个例了。搞不清楚作者你那边为什么不能重复这个问题。。。

**Comment by huawuxin** [comment]
@xtaci  一个稍微有点跑题的问题：
--crypt value                    aes, aes-128, aes-192……
这里不带数字（同时也是默认值）的aes，实际对应的是aes-256吗？

**Comment by xtaci** [comment]
[kcptun-linux-386-20170312.tar.gz](https://github.com/xtaci/kcptun/files/836514/kcptun-linux-386-20170312.tar.gz)
[kcptun-linux-amd64-20170312.tar.gz](https://github.com/xtaci/kcptun/files/836515/kcptun-linux-amd64-20170312.tar.gz)

@huawuxin 对，默认aes-256

@everfly 那就只能出杀手锏了， 这个增加了一个选项 -pprof 开启后，会监听 :6060端口，通过
http://IP:6060/debug/pprof/ 可以看到所有的内存使用情况。 我需要这个信息。

**Comment by baggiogogo** [comment]
我这里也无法重现，观察了三天，连续剧十集1080连续看，vultr $2.5顶多16%内存占用，树莓派客户端就更少了，始终2%左右。

**Comment by everfly** [comment]
@xtaci 配置文件里面添加`“pprof”: true`选项后，任然无法访问http://VPS_IP:6060/debug/pprof/,是需要安装其他什么嘛？nginx之类的？

**Comment by xtaci** [comment]
@everfly 更新下，json配置刚才没有启用。

**Comment by everfly** [comment]
![2017-03-12_211510](https://cloud.githubusercontent.com/assets/7139571/23832082/1c22145e-0769-11e7-8708-c9750a32ad6b.png)
是重新启动的，无法访问

**Comment by xtaci** [comment]
@everfly 重现下载一下https://github.com/xtaci/kcptun/issues/415#issuecomment-285942871

**Comment by everfly** [comment]
@xtaci 内容太多，[debug info](http://45.79.82.142:6060/debug/pprof/)，你直接访问查看吧，不过这会儿才重开的kcptun，内存占用还很少。

**Comment by xtaci** [comment]
```
# HeapAlloc = 6719968
# HeapSys = 12648448
# HeapIdle = 4194304
# HeapInuse = 8454144
```

目前看上去很正常，12M

**Comment by everfly** [comment]
内存是缓慢上升的，需要播放个一个多小时后才能比较明显，好像是；
然后就是这个版本速度比较慢，不知道怎么的，管他的，反正测试，让它播放着吧

**Comment by xtaci** [comment]
嗯，我一个小时后看heap信息

**Comment by xtaci** [comment]
观察到明天，看内存用量能否稳定。

**Comment by everfly** [comment]
@xtaci 
<img width="443" alt="qq20170313-100733 2x" src="https://cloud.githubusercontent.com/assets/7139571/23838892/f1b129dc-07d4-11e7-8ade-17f850250581.png">
不是稳定在139MB,而是因为后来一直没有流量所以内存没有继续增加了，早上播放了一会儿就在继续往上走了。只要一直播放就会一直往上增加内存

**Comment by xtaci** [comment]
@everfly 嗯，可以先替换到0313

**Comment by everfly** [comment]
@xtaci 
```
root@ubuntu:~# cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
stepping	: 2
microcode	: 0x1
cpu MHz		: 2499.996
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
bugs		:
bogomips	: 4999.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

root@ubuntu:~# cat /proc/meminfo 
MemTotal:        1013796 kB
MemFree:          206144 kB
MemAvailable:     559952 kB
Buffers:           31788 kB
Cached:           441984 kB
SwapCached:           36 kB
Active:           473220 kB
Inactive:         262360 kB
Active(anon):     248944 kB
Inactive(anon):    23852 kB
Active(file):     224276 kB
Inactive(file):   238508 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:        262140 kB
SwapFree:         262008 kB
Dirty:                40 kB
Writeback:             0 kB
AnonPages:        193088 kB
Mapped:            30320 kB
Shmem:             10988 kB
Slab:              58052 kB
SReclaimable:      37388 kB
SUnreclaim:        20664 kB
KernelStack:        1932 kB
PageTables:         2956 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      769036 kB
Committed_AS:     347904 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     32768 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       46968 kB
DirectMap2M:     1001472 kB
DirectMap1G:           0 kB
```

**Comment by xtaci** [comment]
@everfly 好的，非常感谢，一个小时后观察。

**Comment by xtaci** [comment]
```
# HeapSys = 14974976
# HeapIdle = 5824512
# HeapInuse = 9150464
```

目前看来正常,15MB

**Comment by xtaci** [comment]
```
# HeapAlloc = 34002096
# HeapSys = 46465024
# HeapIdle = 10805248
# HeapInuse = 35659776
```

目前消耗 46MB @everfly  是否正常，一个小时过去了。

**Comment by everfly** [comment]
暂时不在电脑前，中午看看，这个内存是慢慢增加的，所以这个是需要看趋势的。。。

**Comment by xtaci** [comment]
[kcptun-linux-386-20170313.tar.gz](https://github.com/xtaci/kcptun/files/837282/kcptun-linux-386-20170313.tar.gz)
[kcptun-linux-amd64-20170313.tar.gz](https://github.com/xtaci/kcptun/files/837281/kcptun-linux-amd64-20170313.tar.gz)

这个是做过队列优化的，可以减少内存分配。可以试下。

之前版本的目前状况是:
```
# HeapAlloc = 55918056
# HeapSys = 77955072
# HeapIdle = 19046400
# HeapInuse = 58908672
# HeapReleased = 0
```

78MB

**Comment by xtaci** [comment]
@everfly @huawuxin @BH4WHN @bettermanbao

最近的累积优化已经整理发布到0313 Release

如果还无法解决，可以通过设定GOGC有效的缓解。之前稳定在40MB的只是一种偶然的平衡，GC频率目前很低。

```
# NumGC = 175
```

提高GC频率，可以有效降低内存用量。

**Comment by huawuxin** [comment]
0303版开始的编译环境，跟0221版严格一致吗？有没有升级过编译器、或者修改过相关设置？

**Comment by xtaci** [comment]
@huawuxin 一致的，golang 1.8 darwin/amd64，第三方依赖都是一致的。

**Comment by colalan** [comment]
3月后的各版确实有BUG,我的是Bandwagon主机Centos 6 x86_64,1个G内存.
使用3月后的版本,128MB的SWAP经常性满占用.
另外还有个问题,用3月后的版本,在公司时Dropbox无法同步,以前是以为是公司网络封堵了UPD,没在意.
今天换回2月最后一版,马上就可以同步了,希望是个案.

**Comment by xtaci** [comment]
@colalan 以0313版本为基础测试。

**Comment by xtaci** [comment]
<img width="917" alt="2017-03-13 5 35 23" src="https://cloud.githubusercontent.com/assets/2346725/23848714/792113ee-0813-11e7-8f6a-e42e67033c55.png">

这个是运行了5个小时的server端, 0313 Release, 内存25MB

**Comment by xtaci** [comment]
此贴先关，以0313版本为观察基础讨论此贴：https://github.com/xtaci/kcptun/issues/417

**Comment by xtaci** [comment]
经过5天排查，真正内存泄漏原因疑似发现。 
#417
