### ISSUE TITLE
多拨情况下频繁断线

### ISSUE THREAD

**Issue by travison** [xtaci/kcptun#418]
如题，路由多拨并启用kcptun一段时间后会断线无响应，只有重启server端才可以重新连接。看了 #408 ,一个server端口似乎是只能对应一个client ip，于是做了如下尝试，但仍然失败：
1.在路由器负载均衡设置规则排除server ip及kcp端口，选择ip协议，使其走同一wan口。无效
2.设置server端conn参数为多拨数，并再次尝试，依旧无效
请问还有解决办法么？直连ss无掉线情况

**Comment by cjjdaq** [comment]
在路由上用ip route add指定服务器ip固定网关即可。

**Comment by cjjdaq** [comment]
#!/bin/sh
wanport=1  #1表示线路1   2表示线路2
routeip=服务器ip
cleanfile=清除设置文件名
ips=`ip route show|grep $routeip | grep -c via`
if [ $wanport -gt 0 ];then
  gateway=$(/usr/sbin/ip route show|grep default|awk -F " " '{print $3}'|sed -n $wanport"p")
  devname=$(/usr/sbin/ip route show|grep default|awk -F " " '{print $5}'|sed -n $wanport"p")
  if [ -n $gateway ] && [ -n $devname ];then
    /usr/sbin/ip route add $routeip via $gateway dev $devname >/dev/null 2>&1 &
    echo "$(date): 设置指定IP：$routeip 出口为$devname"
  if [ ! -f $cleanfile ];then
    cat > $cleanfile <<EOF
#!/bin/sh
EOF
  fi
  if [ ! -x $cleanfile ];then
    chmod a+x $cleanfile
  fi
    echo "ip route del $routeip via $gateway dev $devname" >> $cleanfile
  fi
fi

**Comment by travison** [comment]
@cjjdaq 谢谢，但使用后观察了一段时间后还是老样子。
我这边是移动内网，日志里显示的remote address里除了移动的出口ip外，还会夹杂出现移动分配给我的内网ip。两个不同ip出现后，客户端就断线连不上了。但是日志里stream open/closed还是会继续出现，很奇怪。

**Comment by cjjdaq** [comment]
网关指定对了应该不会有此问题。

**Comment by travison** [comment]
更新一下：尝试停用多拨后使用kcp+ss，使用一段时间后也会断线（ss直连无问题），这样看来是isp的锅。
线路：移动内网

**Comment by cjjdaq** [comment]
那可能是udp被咔擦了
