### ISSUE TITLE
youtube，关于浏览器的问题.

### ISSUE THREAD

**Issue by baggiogogo** [xtaci/kcptun#419]
此问题应该和KCPTUN无关，因为习惯了每天来逛逛，所以发出来看看，不妥即关。

因为今天网络稍许不稳、ping略有丢包（vultr JP），所以折腾了下FEC，原FEC0/0，今设置10/3无改善，体现为下载测速正常，但youtube速度上不去，以往无论何时不会低于10000，有点郁闷，奇怪的是发现IPAD好像没受神马影响速度仍然刷刷的，于是排查无线换有线，问题依旧。排查网关DNSMASQ设置（网关透明代理），问题依旧。升级Chrome为最新版，问题依旧。

最后想到换浏览器试试，看见桌面上Edge，点了进去，播放和Chrome同样的视频，怪事情发生了，差别如图所示，Edge平时谁也不会想到去用它。

问题来了，是否真为Chrome的问题？亦或者我设置问题？（都是默认无插件，有些书签）再或者该如何优化？（该现象目前在我这可随时重现  win10 64）

也许，真小瞧Edge了?

![default](https://cloud.githubusercontent.com/assets/21306212/24044187/3a4a15d6-0b55-11e7-8ba4-add0549747bf.JPG)

![1](https://cloud.githubusercontent.com/assets/21306212/24044192/41847c42-0b55-11e7-8d99-ccdcb07a627e.JPG)

update
这会儿网络相对稳了，相同条件下再对比，Edge确实要友好的多，原因不明。

![1](https://cloud.githubusercontent.com/assets/21306212/24057142/520b8a20-0b81-11e7-9b12-430a5293741d.JPG)

![default](https://cloud.githubusercontent.com/assets/21306212/24057157/5a44c012-0b81-11e7-95a7-4ef7ab15e4ec.JPG)

遇到相同问题的朋友可以尝试下换个浏览器试试，不占用资源，帖子先关。

**Comment by lizongzeshunshun** [comment]
youtube的连接速度有时候不准，要用Buffer Health对比
