### ISSUE TITLE
请问如何在树莓派3上装客户端

### ISSUE THREAD

**Issue by jaoyina** [xtaci/kcptun#420]
我现在已经在vps上装好kcptun和shadowsocksr的服务端，在windows上完美使用，现在想在树莓派使用，但是下载下来的文件怎么用也不行，麻烦指点迷津。我尝试了各个版本，但得到的是各种错误，下面是控制台日志， config.json是我在windows下正常使用的配置文件。

pi@raspberrypi:~/kcptun $ ./client_darwin_amd64 -c config.json &
[2] 18491
[1]   Exit 127                client_darwin_amd64 -c config.json
pi@raspberrypi:~/kcptun $ -bash: ./client_darwin_amd64: cannot execute binary file: Exec format error
ls
client_darwin_amd64  client_linux_amd64  config.json  kcptun-linux-386-20170315.tar.gz  server_darwin_amd64  server_linux_amd64
[2]+  Exit 126                ./client_darwin_amd64 -c config.json
pi@raspberrypi:~/kcptun $ ls
client_darwin_amd64  client_linux_amd64  config.json  kcptun-linux-386-20170315.tar.gz  server_darwin_amd64  server_linux_amd64
pi@raspberrypi:~/kcptun $ tar -xvf kcptun-linux-386-20170315.tar.gz 
client_linux_386
server_linux_386
pi@raspberrypi:~/kcptun $ ls
client_darwin_amd64  client_linux_386  client_linux_amd64  config.json  kcptun-linux-386-20170315.tar.gz  server_darwin_amd64  server_linux_386  server_linux_amd64
pi@raspberrypi:~/kcptun $ ./client_linux_386 -c config.json &
[1] 19230
pi@raspberrypi:~/kcptun $ -bash: ./client_linux_386: cannot execute binary file: Exec format error
^C
[1]+  Exit 126                ./client_linux_386 -c config.json
pi@raspberrypi:~/kcptun $ sudo ./client_linux_386 -c config.json
./client_linux_386: 1: ./client_linux_386: Syntax error: "(" unexpected

**Comment by baggiogogo** [comment]
先解压，tar -zxf 文件名，下载arm版，用里面arm v7那个，剩下既然能配服务器那应该没神马问题呀。

**Comment by jaoyina** [comment]
＠baggiogogo 太感谢了，原来我一直下的linux－ａｍｄ６４版，脑子糊涂了，用了ａｒｍ版，瞬间各种便秘都通了。
