### ISSUE TITLE
Issue configuring over OpenWRT

### ISSUE THREAD

**Issue by m4niacjp** [xtaci/kcptun#421]
I'm having a problem while configuring KCPTUN over shadowsocks server on a OpenWrt router

According to the shadowsocks-libev Readme on the client side i have to configure with the ss-local command. But as i'm on the router i have the ss-redir available and i'm not able to manage the connection. Can someone help?

**Comment by m4niacjp** [comment]
On the OpenWrt Router

ss-redir -c /var/etc/shadowsocks.json -l 1080 --mtu 1200 -f /var/run/ss-redir.pid
ss-redir -c /var/etc/shadowsocks.json -U -l 1080 --mtu 1200 -f /var/run/ss-redir-udp.pid 

redir-udp has target to <VPSIP:ssport> while the redir has target 127.0.0.1 port 1090
Kcptun server target <VPSIP:21> localhost 127.0.0.1 port 1090

On the VPS 

server_linux_amd64 -l :21 -t 127.0.0.1:443 --crypt none --mtu 1200 --nocomp --mode normal --dscp 46 &
ss-server -s 0.0.0.0 -p 443 -k passwd -m chacha20 -u

**Comment by jaoyina** [comment]
i guess you can't use ss-redir and ss-local at the same time?

**Comment by bettermanbao** [comment]
first, disable kcptun, make sure everything works.
Then, enable kcptun for ss-redir tcp.

**Comment by daiaji** [comment]
I want to know if your country shadowsocks can help you avoid the Internet censorship?
Thank you
