### ISSUE TITLE
给网络游戏加速,什么样的参数更好呢?

### ISSUE THREAD

**Issue by TmdLife** [xtaci/kcptun#427]
1. 当然要选用低时延的 VPS , 我玩台服, 选择的是 香港的 VPS.
2. 使用了 KCPTUN + SSR 的方案

下面是我使用的参数:
-crypt salsa20 
-nocomp 
-datashard 10 
-parityshard 10 
-conn 1 
-mtu 256 
-sndwnd 256 
-rcvwnd 1024 
-dscp 0 
-mode fast3

虽然能用,但是效果还不满意.
还想请教大神给一些修改的建议, 感谢 :  )

**Comment by cjjdaq** [comment]
不能给游戏加速吧

**Comment by xtaci** [comment]
其他参数都不错，dscp尝试46

**Comment by TmdLife** [comment]
好的. 感谢! 我试试看.  不知道 数据块 和 校验块 能否更低呢?  我的网络是电信100M 例如 5 5 呢?  : )

**Comment by TmdLife** [comment]
@cjjdaq  为什么不能呢? SSR 可以传输 UDP . 所以是可以的吧? 如果不能. 我想我是连不上游戏的. 因为这个游戏在大陆是访问不了的.

**Comment by TmdLife** [comment]
@xtaci  看了作者的一些回复. 现在改成了如下参数, 是否对游戏 更有针对性呢? 感谢 : )
-crypt salsa20 
-nocomp 
-datashard 10 
-parityshard 10 
-conn 1 
-mtu 256 
-sndwnd 256 
-rcvwnd 1024 
-dscp 46 
-mode manual 
-nodelay 1 
-interval 10 
-resend 1 
-nc 1

**Comment by xtaci** [comment]
可以降低到5:5 甚至更低 如果实时性要求高的游戏

**Comment by TmdLife** [comment]
@xtaci 好的,感谢! 我试试看

**Comment by MoeGakuen** [comment]
@xtaci 其实我一直不是很懂 FEC ，假设我 VPS 低丢包想降低延迟，我是设置为 5:5 或更低好，还是完全关闭 FEC 好？

**Comment by xtaci** [comment]
@MoeGakuen 对于游戏而言，大部分是低带宽+快速小流量，这样通过FEC确保100%不丢包，是最佳的选择。

对于大流量的音视频而言，我想你是说的这个场景，FEC需要的额外带宽会导致如果本来就丢包严重的传输更恶劣，特别是IDC做了出口带宽限制，需要更佳小心控制窗口大小。最好别动默认值，调窗。

**Comment by TmdLife** [comment]
@xtaci  很用心的解答, 感谢 :+1:

**Comment by GameorNothing** [comment]
@TmdLife 能说一下你最终的设置吗？ 对游戏加速效果提升大吗？

**Comment by TmdLife** [comment]
@GameorNothing 好的.
-crypt salsa20
-nocomp 
-datashard 5 
-parityshard 5 
-conn 1 
-mtu 256 
-sndwnd 256 
-rcvwnd 1024 
-dscp 46 
-mode manual 
-nodelay 1 
-interval 10
-resend 1 
-nc 1

具体的游戏案例是台服的 黑色沙漠. 使用的是阿里云香港.
高峰时期, 用市面上的加速器, 打怪明显感觉有延迟, 怪物的血量并非实时下降.
但是使用自己的 SSR + KCP 设置之后, 感觉十分顺畅.

**Comment by GameorNothing** [comment]
@TmdLife  非常感谢！

还想请教， 你用的SSR是哪种模式？  是游戏模式 还是大陆白名单模式？

我在路由上用 游戏模式，再开KCPTUN的话，SS会出错，翻不出去， GWlist模式和白名单模式都没有问题

**Comment by ccsil** [comment]
@TmdLife 请教下你是怎么实现用ssr+kcp实现代理游戏的？ 我用梅林固件ss白名单模式+kcp协议只能加速网页浏览 无法代理游戏

**Comment by GameorNothing** [comment]
@TmdLife  还行请教一下， 你贴的参数，是服务器端的设置参数，还是设置好后显示的客户端的？ 先谢谢了！

**Comment by ACG-MM** [comment]
大佬能整个加速器么
