### ISSUE TITLE
vps是linux系统, 本机是macbook pro, 应该怎样挑选版本?

### ISSUE THREAD

**Issue by biggbuddy** [xtaci/kcptun#428]
我的vps是linux主机(64位), 本地机器是macbook pro, 请问选择版本是否应该如下:

vps: kcptun-linux-amd64-20170322.tar.gz
macbook pro: kcptun-darwin-amd64-20170322.tar.gz

谢谢~

**Comment by xtaci** [comment]
对

**Comment by biggbuddy** [comment]
谢老板
