### ISSUE TITLE
为了给游戏加速，如果把 udp 封装在 kcptun 的 conn 会加快游戏体验么？

### ISSUE THREAD

**Issue by jannson** [xtaci/kcptun#43]
1、游戏可以丢包，加到 kcptun 里会不会因为重传导致延迟变大，游戏画面抖动？
2、但是 kcptun 的优点也是明显的，会保证数据延迟会很小，快速的重传数据！

总之，把游戏数据封装在 kcptun 里会让 PS4 这样的游戏体验更好么？ 应该怎么办？

**Comment by xtaci** [comment]
很难评估，游戏的udp策略差别很大，如果流量本身不是很大的情况下，可以尝试用kcptun转发试试，比如通过ovpn
