### ISSUE TITLE
希望服务端可以添加输出pid选项

### ISSUE THREAD

**Issue by xuan880** [xtaci/kcptun#431]
服务器上我开启了两个进程，一个是有向前校验，一个是没有向前校验功能的，现在问了方便管理只好把服务端复制成两份，并启用不同的进程名来进行管理，这样的话如果需要更新服务端的话需要重新把新版本的服务端复制一份，如果经常更新的话非常麻烦，如果支持打印进程pid的话就可以通过pid进行操作，这样只需要不同的配置文件就可以进行管理了。

**Comment by dearneo** [comment]
为什么不用link命令？

**Comment by flynaj** [comment]
你的需求应该是多端口支持，这个应该是很多人的需求希望增加！

**Comment by xuan880** [comment]
@dearneo 原来创建软连接也可以，太感谢了。

**Comment by xuan880** [comment]
@flynaj 是呀如果kcptun也可以和ss一样支持多端口就好了。
