### ISSUE TITLE
kcptun-linux-arm包里没有armv8啊 

### ISSUE THREAD

**Issue by daiaji** [xtaci/kcptun#432]
这样性能会下降很多吧……armv8 64位cpu还有AES指令集呢
顺便说一下
我买了块nanopi-t3
A53\*8 我该怎么编译kali linux啊

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/blob/master/build-release.sh#L31
编译就一行了， 指定好前面三个个CGO_ENABLED=0 GOOS=$os GOARCH=$arch 就可以交叉编译。
装好go1.8后运行即可

**Comment by xtaci** [comment]
golang 目前应该是只支持AES-NI 只有intel的cpu有

**Comment by daiaji** [comment]
@xtaci 果然是go的编译器有毛病
哎 AES指令集不能用真是蛋疼啊 也说是八核 性能不虚就是了

**Comment by xtaci** [comment]
```
$ go tool dist list
android/386
android/amd64
android/arm
android/arm64
darwin/386
darwin/amd64
darwin/arm
darwin/arm64
dragonfly/amd64
freebsd/386
freebsd/amd64
freebsd/arm
linux/386
linux/amd64
linux/arm
linux/arm64
linux/mips
linux/mips64
linux/mips64le
linux/mipsle
linux/ppc64
linux/ppc64le
linux/s390x
nacl/386
nacl/amd64p32
nacl/arm
netbsd/386
netbsd/amd64
netbsd/arm
openbsd/386
openbsd/amd64
openbsd/arm
plan9/386
plan9/amd64
plan9/arm
solaris/amd64
windows/386
windows/amd64
```

**Comment by daiaji** [comment]
@xtaci AMD也不能用AES加速？ 未来amd嵌入板那就有点惨了

**Comment by xtaci** [comment]
这个并不是很清楚，可选的还有salsa20

**Comment by daiaji** [comment]
@xtaci 
注意: 默认加密方法table速度很快，但很不安全。如果CPU支持AES硬件加速的话，推荐使用aes-128-ctr。如果是旧CPU（不支持AES硬件加速），ChaCha20是占用最小速度最快的一种方式。请不要使用rc4，它不安全。
我一直以为rc4-md5比较快 看来是时候换成chacha20了 arm的aes指令集毕竟不知道什么时候才能用

**Comment by daiaji** [comment]
倒是也不需要了
nanopc-t3虽然是A53 但是WIKI上只提供了32位armv7系统
直接就能用armv7的可执行文件 真开心啊
不知道怎么编译kali arm64
说起来树莓派自家的系统也没适配64位吧 怕不是要明年才能换系统了

**Comment by dearneo** [comment]
哎，我的路由器CPU是BCM4709，双核A9，因为不支持vfp只能用armv5的执行文件，真伤心。。

**Comment by linhua55** [comment]
可以用 gccgo 编译， 不过内存占用可能较高

**Comment by daiaji** [comment]
@dearneo LEDE也没正常内核吗？

**Comment by dearneo** [comment]
@daiaji 嗯，和系统内核无关，是BCM4709的A9阉割了FPU，导致无法运行golang的armv7的程序。
