### ISSUE TITLE
linux4.9的bbr和kcp比如何？

### ISSUE THREAD

**Issue by daiaji** [xtaci/kcptun#433]
不可靠消息称kcp略胜一筹
不过ISP QOS UDP的话还是bbr更好？

**Comment by flynaj** [comment]
这个没有可比性。bbr是tcp,探测带宽。 ，kcp是udp通过多发包.

**Comment by daiaji** [comment]
@flynaj 搬瓦工家的便宜VPS都是OPENVZ的不能升级内核……我现在用的还是2.几的内核
所以这时候就只能用KCP了吧
锐速好像也是替换内核 也用不了
我幻想着有一天KCP能加到linux内核里 或者下一代的网络协议里
不过QOS UDP还是讨厌

**Comment by linhua55** [comment]
@daiaji 
OPENVZ可以使用BBR了，原理是在用户态实现TCP/IP协议栈
用的技术是 UML（user mode linux）  或  LKL (linux kernel library)
用LKL实现的更简单

**Comment by daiaji** [comment]
@linhua55 我已经在vultr冲了25美元了😭
