### ISSUE TITLE
K2路由器架设KCPTUN 加速问题

### ISSUE THREAD

**Issue by jxmlingyun** [xtaci/kcptun#434]
先说下我的情况：K2路由器，搬瓦工centos，之前我用的参数是服务器端的sndwnd和rcvwnd调成256，客户端的设为128和256，YOUTUBE可以上720P，用了不到十天，就只能最低画质了。

参数难道还需要动态调整？

**Comment by daiaji** [comment]
你不要用kcp反而速度会更快一点
https://github.com/xtaci/kcptun/issues/381
这里讨论过
K2的CPU是MT7620
在上面架SS服务端跑满大概是4Mb/s
加上kcp好像是800kb/s
看起来好像是800KB看个720P也没问题
但是路由100%负载你还有没有物理NAT的情况下会死机的

总之K2上不管是跑kcp还是SS 速度都不是特别理想
KCP还更吃运算力一点
搬瓦工的线路也挺菜的
vultr现在新用户冲多少送多少 充十五美元的话2.5美元一个月的KVM VPS可以用一年
手贱多冲了10美元……

**Comment by xtaci** [comment]
@daiaji mode 有所谓，建议服务器设置为fast2以上， mode决定“丢包判定”的激进性。

**Comment by daiaji** [comment]
@xtaci 干脆服务器mode设成fast3

**Comment by xtaci** [comment]
@daiaji 可以设置为fast3，  CPU的优化已经足够好了， fast3完全没问题。

**Comment by daiaji** [comment]
@xtaci 也比较迷 不管哪个加密方式在mips上跑速率都差不多 x86倒是没问题

**Comment by baggiogogo** [comment]
换换不同的系统试试，树莓派做过些比较，还是4.4内核的RASPBIAN JESSIE LITE给力，估计官方优化的好，同样参数和WIN下差不多。LEDE最新稳定版没试过，以前的不给力，centos也差强人意。
不过我都是拿了做透明代理，只是socks5的话不知怎样。

**Comment by msghost** [comment]
@xtaci 看到上面你说服务端的mode有所谓。正好请教一下，服务端和客户端的mode可以不匹配吗，例如服务端fast3，客户端选择fast或者fasts2。
按我之前的理解，必须服务端与客户端对应，但看到你上面的回复中隐含的意思又有点不确定了。
谢谢！

**Comment by xtaci** [comment]
@msghost 可以不匹配，-mode只影响所在端的重传策略。

**Comment by bettermanbao** [comment]
K2用户飘过，上kcptun和ss，优化后极限速度在10Mbps左右，不能再快了。
单纯ss可以到40Mbps。
关键字salsa20 nocomp rc4-md5，rcvwnd 512, sndwnd 256。

**Comment by daiaji** [comment]
@bettermanbao 我这边单纯ss rc4-md5服务端最多只能跑到4M/s 一般是3Mb/s 可能还是服务端更吃力一些
加上kcp直接到800kb/s
然后老哥能帮我编译一下https://github.com/esdeathlove/shadowsocks-libev debian二进制文件吗
这个客户端只要一跑流量就报错
```
 2017-04-02 20:04:07 INFO: protocol origin
 2017-04-02 20:04:07 INFO: protocol_param (null)
 2017-04-02 20:04:07 INFO: method chacha20-ietf
 2017-04-02 20:04:07 INFO: obfs http_simple
 2017-04-02 20:04:07 INFO: obfs_param (null)
 2017-04-02 20:04:07 INFO: initializing ciphers... chacha20-ietf
 2017-04-02 20:04:07 INFO: tcp port reuse enabled
 2017-04-02 20:04:07 INFO: listening at 0.0.0.0:18388
 2017-04-02 20:04:09 INFO: accept a connection
[1]    3203 segmentation fault 
```

**Comment by liudf0716** [comment]
小路由器上可以试试xkcptun, c语言实现，专为openwrt，lede平台开发
https://github.com/liudf0716/xkcptun

**Comment by bettermanbao** [comment]
@liudf0716 
看好你

**Comment by shNanChen** [comment]
@liudf0716 是否服务器端用 xtaci 的，客户端用你的？这样混搭，好用吗？

**Comment by liudf0716** [comment]
@bettermanbao 可以编译，我已经在线上测试了
@shNanChen 我当时是这么考虑的，后来发现调试成本很高，加上我对go不熟悉，所以就自己实现了server

**Comment by liudf0716** [comment]
@shNanChen 后面我对xtaci大神的项目深入了解后，会跟kcptun兼容的。

**Comment by daiaji** [comment]
@liudf0716 xkcptun能效怎么样？有测试吗？

**Comment by bettermanbao** [comment]
@daiaji @liudf0716 
我试过了，发现xkcptun和kcptun并不兼容。
K2上试的，kcptun最高可以跑到10-12Mbps，xkcptun可以到14-15Mbps。xkxptun的数据没有严格，可能存在偏差。编译好的ramips binary见附件，一起试试吧。

[xkcptun_0.4.266-1_ramips_24kec.zip](https://github.com/xtaci/kcptun/files/927407/xkcptun_0.4.266-1_ramips_24kec.zip)

**Comment by liudf0716** [comment]
@bettermanbao 是的，是不兼容。感谢测试，xkcptun刚出来，我还在调试，目前还没到性能优化的地步，后面会努力搞的。

**Comment by bettermanbao** [comment]
@liudf0716 
加油，我看好你。kcptun刚出来的时候K2上运行2Mbps都跑不到，现在可以跑到10Mbps。

**Comment by xtaci** [comment]
@liudf0716 如果要兼容, smux和fec是难点。

**Comment by liudf0716** [comment]
@xtaci  后面有空琢磨一下kcptun的代码，c做东西太tm费劲了，现在还在调试中。

**Comment by notedit** [comment]
看xkcptun并没有用到fec

**Comment by xtaci** [comment]
@liudf0716 https://github.com/xtaci/libkcp/ 这里有FEC可以参考，但SMUX是阻塞模型，依然很难。特别是API流控（内存控制）。

**Comment by liudf0716** [comment]
@xtaci  是，xkcptun没有用到fec及加密，目前使用的是异步模型，调试起来颇为艰难，都是摸着石头过河。

**Comment by bettermanbao** [comment]
@liudf0716 
可以参考一下shadowsock-libev的源码，工作原理类似。

**Comment by liudf0716** [comment]
@bettermanbao 好，有空我研究研究，谢谢!

**Comment by szwifi** [comment]
@xtaci , 我按照建议的配置去设定了kcptun的参数，服务器是美国洛杉矶VPS，kcptun使用前后感觉变化不明显，您有空的时候方便帮我看看吗？感谢！

**Comment by w12928293** [comment]
@bettermanbao 

确实，应该是K2的CPU达到瓶颈了，我试着调了好几种参数，最高速度依然只能1.2M/S
