### ISSUE TITLE
Listen to UDP port.

### ISSUE THREAD

**Issue by heri16** [xtaci/kcptun#435]
client should listen to udp port also for forwarding over kcp tunnel.

**Comment by terrytw** [comment]
xtaci said he has no plan for this. 
"you could always find a workaround for it, so it's unnecessary" are his words.

**Comment by xtaci** [comment]
such as :

udp->ovpn ->tcp -> kcptun -> tcp -> ovpn ->udp

**Comment by heri16** [comment]
ok, I was thinking of suing this to encapsulate and proxy the Microsoft RDP protocol which uses both tcp and udp. xtaci thinks this feature is not useful but the alternatives are way overkill. A full vpn just degrades performance and latency.

**Comment by linhua55** [comment]
@heri16 
Maybe socat can forward UDP through TCP.

**Comment by pmorch** [comment]
Indeed, socat is good at this: [Forwarding SNMP ports over SSH using socat](http://www.morch.com/2011/07/05/forwarding-snmp-ports-over-ssh-using-socat/) (Disclaimer: on my own blog...)

**Comment by wangyu-** [comment]
udp speed-up solution. Can work together with kcptun ,speed-up tcp and udp at same time.
https://github.com/wangyu-/UDPspeeder
