### ISSUE TITLE
kcp能不能走TCP协议?

### ISSUE THREAD

**Issue by yuhuan21** [xtaci/kcptun#436]
我的服务商不支持UDP转发,只支持TCP,可以用KCP吗?谢谢

**Comment by xtaci** [comment]
不可以，不越界。

**Comment by cjjdaq** [comment]
@xtaci 什么时候支持一下udp吧，就剩它了

**Comment by daiaji** [comment]
你可以试试linux 4.9的BBR

**Comment by wangyu-** [comment]
我的这个程序可以把UDP流量包装成TCP，用raw socket的方式。测试过，可以配合kcptun使用。
https://github.com/wangyu-/udp2raw-tunnel

**Comment by ccsexyz** [comment]
感觉这个想法被实现了好多遍了

**Comment by wangyu-** [comment]
确实被实现了很多遍了，现有的让kcptun支持tcp的项目貌似有3个：
https://github.com/linhua55/some_kcptun_tools/tree/master/relayRawSocket 。这个是最早的，ptyhon写的，没有模拟3次握手。在我这里的NAT环境用不了。
https://github.com/Chion82/kcptun-raw  。这个是简化版的kcp，支持TCP的同时简化掉了FEC之类的功能。
https://github.com/ccsexyz/kcpraw 。这个fork了原版，但是xtaci并不打算把新加的功能merge进去。时间长了以后，这个分支会落后于xtaci的版本很多。

所以我写了我的那个udp2raw-tunnel，优点是，可以一直兼容最新版的kcptun。缺点是，相当于给kcptun包了一层额外的tunnel，有额外性能开销。侧重点不一样，根据自己的需求决定使用哪个吧。

**Comment by ccsexyz** [comment]
关于“时间长了会落后很多”我持保留意见。

**Comment by wangyu-** [comment]
@ccsexyz 更改了相关表述 。。

**Comment by xtaci** [comment]
@ccsexyz 师弟毕业了么

**Comment by ccsexyz** [comment]
其实 kcptun 的主要实现是在 kcp-go 和 smux 这两个库里的，kcptun 本身的代码并不算多，所以 copy 起来工作量也不会很大。
实在担心跟不上上游，还可以用 https://github.com/ccsexyz/tunnel 啊。

**Comment by yjd** [comment]
才看到@ccsexyz
之前测试了下udp2raw-tunnel，win客户端需要跑在虚拟机麻烦了点。
