### ISSUE TITLE
关于udp优化

### ISSUE THREAD

**Issue by baggiogogo** [xtaci/kcptun#437]
近日折腾了好些树莓派系统，发现好些在默认设置下udp丢包严重，现象是内网占用很高带宽但是速度上不去。简单的按照SS教程优化了下就能改善很多，遇到同样问题的同学用记得netstat -su排查下，一目了然。
如有可能，@xtaci 能否空闲时出个简单的udp优化教程，感谢。
![default](https://cloud.githubusercontent.com/assets/21306212/24913167/e0f6b6f8-1f02-11e7-9451-178bc0248104.PNG)

**Comment by masrickcheng** [comment]
是在用NanoPi NEO也需要优化，netstat -su后 unknow port recieved 和 recieve errors分别什么意思？

**Comment by baggiogogo** [comment]
unknow port recieved不是太多的话应该是正常的，recieve errors应该是丢包了。
先把/etc/sysctl.conf文件加入以下：
# max read buffer
net.core.rmem_max = 67108864
# max write buffer
net.core.wmem_max = 67108864
# default read buffer
net.core.rmem_default = 65536
# default write buffer
net.core.wmem_default = 65536
# max processor input queue
net.core.netdev_max_backlog = 4096
# max backlog
net.core.somaxconn = 4096
保存重启后观察，应该能改善了，对于udp部分不懂，没动。

**Comment by xtaci** [comment]
只有一个原则，调大rmem , 让RcvbufErrors =0

**Comment by baggiogogo** [comment]
好的，先关。
