### ISSUE TITLE
反复的 stream opend closed 是什么原因

### ISSUE THREAD

**Issue by flypighd** [xtaci/kcptun#439]
参数核对一致，一连就是  stream opend     stream closed 
2017/04/12 22:44:56 version: 20170329
2017/04/12 22:44:56 listening on: [::]:8888
2017/04/12 22:44:56 target: 127.0.0.1:10128
2017/04/12 22:44:56 encryption: salsa20
2017/04/12 22:44:56 nodelay parameters: 1 20 2 1
2017/04/12 22:44:56 sndwnd: 1024 rcvwnd: 1024
2017/04/12 22:44:56 compression: false
2017/04/12 22:44:56 mtu: 1350
2017/04/12 22:44:56 datashard: 10 parityshard: 3
2017/04/12 22:44:56 acknodelay: false
2017/04/12 22:44:56 dscp: 0
2017/04/12 22:44:56 sockbuf: 4194304
2017/04/12 22:44:56 keepalive: 10
2017/04/12 22:44:56 snmplog: 
2017/04/12 22:44:56 snmpperiod: 60
2017/04/12 22:44:56 pprof: false
2017/04/12 22:44:56 remote address: 183.129.---.--:43894
2017/04/12 22:44:56 stream opened
2017/04/12 22:44:56 stream opened
2017/04/12 22:44:57 stream closed
2017/04/12 22:44:57 stream closed
2017/04/12 22:44:57 stream opened
2017/04/12 22:44:57 stream closed
2017/04/12 22:45:00 stream opened
2017/04/12 22:45:00 stream closed
2017/04/12 22:45:00 stream opened
2017/04/12 22:45:00 stream closed
2017/04/12 22:45:07 stream opened
2017/04/12 22:45:07 stream closed
2017/04/12 22:45:07 stream opened
2017/04/12 22:45:07 stream closed
2017/04/12 22:47:19 broken pipe

**Comment by JackieSung4ev** [comment]
正常现象 都这样的。

**Comment by arvinpan** [comment]
简单的讲，网络连接开始--stream opened，网络连接断开--stream closed

不过经你这么一说倒确实不太清楚这个日志存在的意义，毕竟重复信息刷屏了
可以优化下问题表述，改成日志优化建议/讨论

**Comment by xtaci** [comment]
normal input
