### ISSUE TITLE
加大conn导致多线程下载效果很糟

### ISSUE THREAD

**Issue by noti0na1** [xtaci/kcptun#44]
环境：
服务器：西雅图ubuntu16.04(64) kcptun + 3proxy (socks5)
-mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2
客户端：win10(64) IDM + kcptun，100M宽带 (因为电脑用的无线，实测下载大概有70M)
-conn 4 -mtu 1400 -sndwnd 256 -rcvwnd 2048 -mode fast2
测试用的都是最新的23号的版本

当我把conn设置为1时，下载可以稳定到2~3MB/s，任务管理器里显示大概用了40M的带宽
然而随着conn设置增大，下载效果越来越糟糕，看上去一卡一卡的，根本下不动
理论上调大点应该效果更好吧？不知道瓶颈在哪里，会不会在cpu运算上？

顺便还有一个问题，chrome上代理看网页，用的还是相同的设置。当载入图片很多的网页时，其它网页根本打不开，全部卡住。不知道这是kcptun的锅还是3proxy的？

谢谢

**Comment by xtaci** [comment]
conn超过核心数是没有意义的，另外虚拟机很难评估，另外我在review下代码有没有问题。

**Comment by noti0na1** [comment]
嗯，我的cpu是coreM5y10c，双核四线程，所以我在担心我的瓶颈在cpu上

**Comment by xtaci** [comment]
多线程下载，如果超过物理带宽最大值，只会让情况变的更糟，丢包！
-conn的本意是，避免因为一条链路丢包，导致所有请求都卡住，是针对小数据请求的。

**Comment by noti0na1** [comment]
哦，反正我现在conn1开下载没什么问题
