### ISSUE TITLE
KCP可以和BBR一起用么?

### ISSUE THREAD

**Issue by CuminLo** [xtaci/kcptun#440]
在V2上看到低端VPS开启BBR的方法　[地址](https://www.v2ex.com/t/353778)

于是开启成功之后直连确实比之前快3-4倍左右. 但是比KCP还是要差一点.

所以就想问这两个能整合一起用么? 怎么配置呢?

**Comment by baggiogogo** [comment]
服务器上可以一起用，没发现什么副作用，也没发现两者一起效果有什么加成，主要还是方便偶尔会单独使用下TCP连接。

**Comment by bettermanbao** [comment]
2个一起用，没意义。

**Comment by terrytw** [comment]
那个大概就是楼上发的吧哈哈
KCP是UDP流量，BBR是TCP，无关的

**Comment by elfive1992** [comment]
ssserver和kcptun server之间是系统内回路，不存在加速不加速的问题啊，这个带宽这么着也比kcptun server与kcptun client之间的带宽和速度高吧。
要知道影响你科学浏览的瓶颈是在两个kcp之间。。。BBR可以部署，只是对kcp无效。

**Comment by CuminLo** [comment]
对这个不太了解，
感谢各位解答。

**Comment by sosmygirl** [comment]
没有叠加效果tcp 和 udp不一样。。但一起用互不影响额

**Comment by JXC543** [comment]
怎么会没有用。bbr是对kcp没没有用，但访问请求发到服务端后，服务端再访问你所请求的，而这访问就是tcp等，因此bbr对kcp的加速在广义上是有用的
