### ISSUE TITLE
Minimizing overhead

### ISSUE THREAD

**Issue by eliezedeck** [xtaci/kcptun#441]
I have been testing kcptun on my setup. It works fine. I don't have any problem on the setup.

But, I'd like to reduce the overhead incurred by the tunneling. For instance, when I use it, it makes use of about 1024 KB/s of traffic, but the actual data/speed that is reported by the underlying application (the TCP part) is just about 400 KB/s. That's about 60% of waste, which I think is **too much**.

I have tested many application, they all see just about 400 KB/s of speed out of 1 MB/s of traffic. I have tried `-mode normal` and `-mode fast2`, as well as `-mode fast3`. They all get the same result of huge waste.

How do I achieve lower overhead? I know there has to be some amount of waste, but 60% is incredibly too much. I'm sure it's just a setting that I'm not getting right, and I don't really understand the inner-working of the core KCP library.

I'm looking, at a maximum, a 20% waste. Most VPN and tunnels will stay in these range as well.

My usecase is:

- 300 - 400 milliseconds of RTT
- MTU is 400 bytes. I would like to use it as an exfiltration, that's why. But I have tested it in normal 1500 MTU line, and whether I use 400 / 1500 MTU, it yields about the same result.
- About 10% packet loss

**Comment by xtaci** [comment]
well， you can try manual mode, such as :
`-mode manual -nodelay 1 -interval 40 -resend 0 -nc 1`

https://github.com/skywind3000/kcp/blob/master/README.en.md#protocol-configuration

**Comment by dearneo** [comment]
Well, I have the same issue before and I've tested different kind of configurations. here is my manual mode on server side and client side.

**server**
`-mode manual -nodelay 1 -resend 0 -nc 1 -interval 100`
**client**
`-mode manual -nodelay 0 -resend 0 -nc 1 -interval 20`

According to my test result, the ratio of actual data and data received by client and data sent by server is about 0.75 : 0.86 : 1, which is quite good IMO. Video stream runs smoothly on it.

**Comment by bettermanbao** [comment]
disable fec maybe helpful.

**Comment by eliezedeck** [comment]
Thanks guys.
