### ISSUE TITLE
PC端可用，路由器端无法使用

### ISSUE THREAD

**Issue by RyougiARIA** [xtaci/kcptun#442]
路由器为斐讯K2，刷入padavan，客户端和服务器端版本皆为20170329
服务器端提示：
2017/04/27 03:39:23 broken pipe
2017/04/27 03:39:23 remote address: 39.129.248.157:2374
2017/04/27 03:39:25 broken pipe
2017/04/27 03:39:25 remote address: 39.129.248.157:2374
2017/04/27 03:39:36 remote address: 39.129.248.157:2387
2017/04/27 03:39:36 broken pipe
2017/04/27 03:39:36 remote address: 39.129.248.157:2387
2017/04/27 03:39:36 broken pipe
2017/04/27 03:39:41 broken pipe
2017/04/27 03:39:41 remote address: 39.129.248.157:2387
2017/04/27 03:39:51 remote address: 39.129.248.157:2398
2017/04/27 03:39:51 broken pipe
2017/04/27 03:39:51 remote address: 39.129.248.157:2398
2017/04/27 03:39:55 broken pipe
2017/04/27 03:39:56 broken pipe
2017/04/27 03:39:57 remote address: 39.129.248.157:2398
2017/04/27 03:40:11 broken pipe
2017/04/27 03:40:27 broken pipe
2017/04/27 03:49:27 remote address: 39.129.248.157:3563
2017/04/27 03:54:57 broken pipe
2017/04/27 04:19:36 remote address: 39.129.248.157:2238
2017/04/27 04:19:36 broken pipe
2017/04/27 04:19:46 remote address: 39.129.248.157:2238
2017/04/27 04:20:16 broken pipe

其中remote address为路由所在外网地址，其余客户端所有配置与服务器端相同，检查了N遍未果
PC端验证可用，断开PC客户端换用路由器的客户端，服务器就有以上提示

**Comment by JackieSung4ev** [comment]
Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your -key xxx for at least 3 times, MAKE SURE both sides share the same secret.
2. -nocomp, -datashard, -parityshard, -key, -crypt must be the same on both side.
3. Did you correctly set the -target on the server side?
4. MAKE SURE telnet target port on your server successful(don't ask me why couldn't).
5. Does your firewall allows UDP communications? (including your ISP Cable-Modem)
6. Are you using the same version for both client & server
7. Are you using the latest release?
8. Which OS do you use?
9. Which end for this issue related to, client or server?

**Comment by XiaoMuIns** [comment]
哥们，我和你一毛一样的问题，请问你解决了吗
![](http://ww1.sinaimg.cn/large/d3ccf415ly1fft3gknp8ej20i10a275a.jpg)
