### ISSUE TITLE
mt7621路由器，在lede运行kcptun提示illegal instruction

### ISSUE THREAD

**Issue by hybtw** [xtaci/kcptun#443]
mt7621路由器，在lede运行kcptun提示illegal instruction

**Comment by ekenchan** [comment]
跟你有一样的问题，在mt7628上提示illegal instruction

**Comment by ekenchan** [comment]
查了一下，应该是lede的内核默认没有启用FPU emulator的原因，而go需要依赖FPU，打开FPU emulator的选项重新编译lede的内核即可。

**Comment by hybtw** [comment]
不会编译lede，只能等go支持soft floating point了

**Comment by daiaji** [comment]
@hybtw 你也可以等固件编译者把FPU emulator开启
说起来你用的应该不是K2P吧
我记得LEDE官方提供的固件似乎跑不起来

**Comment by zhanhb** [comment]
https://github.com/zhanhb/kcptun-soft-floating
