### ISSUE TITLE
请问这个客户端能支持mac吗 

### ISSUE THREAD

**Issue by h605290713** [xtaci/kcptun#445]
请问这个客户端能支持mac吗 
我在mac上面 777 权限 root 运行报错
chmod 777 client_linux_amd64 
Macbook:Downloads root# ./client_linux_amd64 -r "xxxxxxxxxx -l ":8790" -mode fast3  -sndwnd 4096 -rcvwnd 4096  -nocomp -crypt none  -conn 3  -dscp 46
-sh: ./client_linux_amd64: cannot execute binary file
能开发支持mac端的客户端吗

**Comment by xayoung** [comment]
mac需要下kcptun-darwin-amd64

**Comment by xfyrgn** [comment]
您好  请问kcptun-darwin-amd64在哪里下载？

**Comment by xfyrgn** [comment]
@xayoung 您好 请问kcptun-darwin-amd64在哪里下载？

**Comment by alex43211** [comment]
@xfyrgn 这里
https://github.com/xtaci/kcptun/releases/download/v20170329/kcptun-darwin-amd64-20170329.tar.gz

**Comment by paradiseduo** [comment]
可以下载这个图形化界面的[客户端](https://github.com/paradiseduo/Kcptun)
