### ISSUE TITLE
客户端与服务端无法建立连接

### ISSUE THREAD

**Issue by caicy1991** [xtaci/kcptun#446]
奇怪，客户端和服务端连接不起来，无论在VPS与本地，还是VPS与VPS，还是本地与本地，都无法连接，版本是最新版的20170329
附上本地win客户端与服务端尝试连接的截图，都没有任何数据发送的日志提示。服务端也没有显示有来自客户端的连接。这是怎么了，有大神帮忙看下嘛？
![qq20170509135246](https://cloud.githubusercontent.com/assets/18752665/25837382/31ce47bc-34c0-11e7-88bb-07188330e49d.png)

**Comment by caicy1991** [comment]
经测试，好像从3月份开始所有的版本都无法使用，同样的配置，用20170221的版本就正常了，好奇怪啊？

**Comment by linkerlin** [comment]
./client --remoteaddr 127.0.0.1:29900

用这个是可以的

**Comment by xtaci** [comment]
看你的图，貌似根本没有任何客户端连接client啊。

**Comment by caicy1991** [comment]
@linkerlin @xtaci 感谢你们的回复，我跟你们说明一下情况。
@linkerlin 我这个是在本地电脑直接尝试建立连接，本地电脑直接运行KCPTUN服务端，监听地址是127.0.0.1:29900、目标地址是我的SS服务器地址:8388，然后在本地也运行KCPTUN客户端，监听地址是127.0.0.1:8388、远程地址是127.0.0.1:29900，也就是KCPTUN直接在本地建立连接，本地还有SS客户端做连接测试，我截图的可以看出本地的KCPTUN客户端都没有建立连接。因为正常来说那个日志窗口应该会打印一条连接成功的信息，我稍后把正常情况的截图附上。
@xtaci 有客户端的，我在SS上设置了一个127.0.0.1:8388的服务器，并尝试发起连接，实际上可以看到SS有上行的标识，但没有任何下行数据，也就是本地的KCP之间没有形成连接。
截图中的版本是20170329，同样的命令在20170221下就正常，我直接把20170221的版本替换之前的20170329，就可以成功建立连接，两端的窗口会有正常的传输信息。我下面附上截图。

**Comment by caicy1991** [comment]
![qq 20170511101608](https://cloud.githubusercontent.com/assets/18752665/25929134/df0eafac-3632-11e7-8dea-a2ffc2ffdb4f.png)
这是20170221的版本，同样的配置命令，可以看出KCPTUN两端会打印连接信息
客户端打印：connection: 127.0.0.1:52700 -> 127.0.0.1:29900
服务端打印：remote address: 127.0.0.1:52700
这时如果实际产生数据流，两端都会打印stream opened、stream closed
我从最新版往前测试，测试了3月份的所有版本都无法使用，到20170221的时候才可以正常使用。不知道为啥会出现这种情况

**Comment by xtaci** [comment]
你这个有啥意义。。。。 本机到本机， 你确定你看懂了那个图么？

**Comment by caicy1991** [comment]
@xtaci 因为我之前在服务器上部署后，本地就是连不上服务端，所以就把服务端放到本地来测试连接啊，都放在本地只是为了测试。

**Comment by smdhz** [comment]
你服务器不是监听127.0.0.1:8388了吧，改成0.0.0.0:8388

**Comment by caicy1991** [comment]
@smdhz 你好，你说的是哪一个服务器？8388是KCPTUN客户端的监听，127.0.0.1就行了，如果是0.0.0.0，那KCPTUN客户端等于是监听所有地址，这个无关紧要，主要是KCPTUN客户端与KCPTUN服务端之间的连接无法建立，看下截图，正常建立是有信息打印出来的，如connection:、remote address:

**Comment by caicy1991** [comment]
没人了嘛

**Comment by dearneo** [comment]
如果是你部署在本地测试的kcptun server，从你的本地telnet一下要target的tcp端口是否通，建议把target也在设为本地的端口进行测试
如果是部署在vps的kcptun server，确认一下本地到vps的网络没问题，即互相可收到udp包
如果还是有问题，建议先不要改动除ip端口外的任何默认参数，看是否能跑起来

**Comment by caicy1991** [comment]
@dearneo 谢谢回复，我的两个截图可以看到参数是一样的，20170329的无法建立连接，而20170221的确可以，所以才觉得很奇怪

**Comment by buutuud** [comment]
不要纠结了,自己搭建
