### ISSUE TITLE
不要使用kcptun登录谷歌学术

### ISSUE THREAD

**Issue by google9002** [xtaci/kcptun#447]
按照默认规则，*.google.com都被加入翻墙规则，但是kcptun的原理毕竟是多倍发包，使用这玩意儿连谷歌学术的结果就是，它会提醒你你的电脑或者你的网络运营商在不停发送重复请求，为了不影响我们的用户，只好暂时屏蔽你了=。=
尤幸现在谷歌学术不需要翻墙似乎也能上，所以请把scholar.google.com从翻墙列表里拿掉。
以上

**Comment by cs8425** [comment]
kcptun只有在kcptun client跟kcptun server之間才走kcp(也不是"多倍發包"這麼簡單),
除此之外的連線都是標準tcp
所以你在scholar.google.com架了kcptun server/client嗎?
不然你所謂的"發送重複請求"與kcptun無關啊

**Comment by xtaci** [comment]
好像走错场地了

**Comment by daiaji** [comment]
翻墙就会这样
很谜

**Comment by shNanChen** [comment]
和你server 的IP有关系

2017年5月12日 11:41，"daiaji" <notifications@github.com>写道：

**Comment by lizongzeshunshun** [comment]
@cs8425 是正确的。

![Kcptun](https://raw.githubusercontent.com/xtaci/kcptun/master/kcptun.png)

KcpTun只是在**客户端和你用来翻墙的服务器**之间进行加速（即“多倍发包”），至于你用来翻墙的服务器和谷歌的服务器之间，kcptun不会加速也没必要加速，是标准的tcp的连接，相当于正常访问

**Comment by jmydurant** [comment]
虽然理论上是这样。。但是我把scholar变成direct之后就能上了。。之前一直是说“... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.”   。。。这就很气。。。

**Comment by vonhezhou** [comment]
问题是，似乎多发的包，在服务端转发的时候，并没有去除重复的包。所以连google的搜素的时候（是的,google搜索也会），偶尔会要求你输入验证码确认你不是机器人什么的。

**Comment by vonhezhou** [comment]
而且最近用kcp的话，https的google会比较容易碰到说目标信息无法验证的情况。使用ss直连没有问题

**Comment by 178220709** [comment]
同样发现这个问题了.
我的一个vps既有ss直连端口,也有kcp端口,用kcp则经常需要做机器人验证(同jmydurant)
用ss直连则一切正常,就是速度慢一点.

**Comment by cs8425** [comment]
@jmydurant @vonhezhou @178220709 
可否提供一下SS用的加密方法、kcp的fec設定、kcp的加密方法?
咱們來一個一個來排除看看
先確定不是SS之後也不是client端的問題
再試著關掉fec看看有沒有解決?

**Comment by vonhezhou** [comment]
ss使用aes-256-cfb加密，
kcp使用aes加密。
fec没有调，不知道是多少。使用的是fast2模式

**Comment by cs8425** [comment]
@vonhezhou 
fec預設是10:3
可以透過這2個參數設定
任何一個設為0就是關掉fec
```
   --datashard value, --ds value    set reed-solomon erasure coding - datashard (default: 10)
   --parityshard value, --ps value  set reed-solomon erasure coding - parityshard (default: 3)
```

**Comment by 178220709** [comment]
@cs8425  我之前除了密码 全部默认
现在我关了 parityshard  (设置为0),

然后我再用看看  再来反馈

**Comment by vonhezhou** [comment]
我的是因为多个人公用同一个kcp-server导致的。
昨天给每个人分配了一个kcptunl-server就没怎么看到了,先用几天看看再来反馈。
只是kcp好像会断流。不过那是别的问题了。

**Comment by daiaji** [comment]
这个Issues 我硬是读出了迷信的味道

**Comment by vonhezhou** [comment]
我这边已经确认了，是多人共用同一个kcp导致的。给共用的几个人各自使用一个kcp服务端就ok了。

**Comment by JsonSong89** [comment]
@vonhezhou 
然而我这边是kcp只有我一个人用,ss才是多人使用,
哈哈哈,还真是玄学了.

@cs8425  关掉parityshard 后,没有再出现这个问题了.

**Comment by plmsuper8** [comment]
然而，scholar.google.com不能直接访问

**Comment by HongdaWang** [comment]
兄弟是不是感觉很晕？不要误导人啊？

**Comment by liufengsoft** [comment]
这兄弟到底懂不懂啊，多发包和应用层收到多业务请求没有一毛钱关系，不要误人子弟了。

**Comment by Originalimoc** [comment]
挖个坟，我看来确实是IP有问题，通常是IP段被灰名单。
