### ISSUE TITLE
诡异的情况，路由器上海电信居然达6w

### ISSUE THREAD

**Issue by mengzhihoing** [xtaci/kcptun#449]
7620 cpu的路由器，按以下配置，路由器端是0329的kcptun，不知道为什么突然达u2b达62000，而且cpu居然占用不高。我拖动进度条都是可以正常缓冲的，但是一旦换个视频，马上无响应了，也不能翻q了。
很是奇怪，有没有遇到同样情况的？
路由器配置
<pre>
{
    "localaddr": ":8388",
    "remoteaddr": "IP:999",
    "key": "shenfu1991",
    "crypt": "aes-128",
    "mode": "fast3",
    "conn": 1,
    "autoexpire": 300,
    "mtu": 1400,
    "sndwnd": 256,
    "rcvwnd": 256,
    "datashard": 0,
    "parityshard": 0,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}
</pre>

服务器设置：
<pre>
{
    "localaddr": ":8388",
    "remoteaddr": "vps:999",
    "key": "it's a secrect",
    "crypt": "aes-128",
    "mode": "fast3",
    "conn": 1,
    "autoexpire": 300,
    "mtu": 1400,
    "sndwnd": 256,
    "rcvwnd": 256,
    "datashard": 0,
    "parityshard": 0,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}
</pre>

![image](https://github.com/mengzhihoing/vps/raw/master/IMG_0856.JPG)  
![image](https://github.com/mengzhihoing/vps/raw/master/IMG_0855.JPG)

**Comment by cs8425** [comment]
懷疑你遇到smux的這個問題: [issue #18](https://github.com/xtaci/smux/issues/18)
試著把`sockbuf`加大到32MB以上看看(2邊都加大)
不然就是用我patch過的版本重編一次kcptun: https://github.com/cs8425/smux/tree/move-token-to-stream
副作用是可能會稍微降速
不會編的話我可以幫你編(如果你願意)
client是linux-mipsle、server是?

**Comment by mengzhihoing** [comment]
@cs8425 server是ubuntu14.04 86_64

**Comment by cs8425** [comment]
你試試看能不能用,
多了幾個參數要設:
```
"streambuf-en": true, // 預設不啟用, 不啟用相容原版但是沒效果
"streambuf": 1048576, // 單位byte, 每個stream最大可以使用多少buffer, 愈大愈不影響速度, 要小於"sockbuf"才不會有卡死現象
"streamboost": 10000, // 單位ms, 允許連線超過buffer限制多久, 愈大愈不影響速度, 但是愈吃RAM
```

[kcptun-smux-patch.zip](https://github.com/xtaci/kcptun/files/999515/kcptun-smux-patch.zip)
sha1sum:
8381e81790d093f2fcb932ed9d0a0acc5b3a07c4  kcptun-smux-patch.zip

**Comment by mengzhihoing** [comment]
@cs8425 确实不会编，还得麻烦您帮忙编译一下，谢谢。

**Comment by cs8425** [comment]
@mengzhihoing 
發現一個bug
所以重編了一下
設定選項沒變
client跟server都有: armv7、armv8、mipsle、x86_64

編譯完的檔案: [kcptun-smux-patch.zip](https://github.com/xtaci/kcptun/files/1011754/kcptun-smux-patch.zip)
sha1sum: 7a42808438ebc79092dfe39a116c818e0d0f84d7

**Comment by mengzhihoing** [comment]
@cs8425 试了一下，无法重现当时的情况，现在正常是7000左右，cpu 80以上。

**Comment by mengzhihoing** [comment]
#473 应该和这里一样的情况
