### ISSUE TITLE
感觉文字说明有些费解。

### ISSUE THREAD

**Issue by metalwood** [xtaci/kcptun#45]
“tcp网络程序的传输承载”，这个怎么理解？是说用kcptun可以代替标准tcp达到更好的效果，还是说其他？如果是我估计的这个意思，建议直接说“是标准TCP的更好替代品”。

**Comment by xtaci** [comment]
不可能， 只能说，在高丢包环境下，传输效果略有改善

**Comment by cuteribs** [comment]
@metalwood 从作者写的说明和更新日志来看就知道是面向有点IP网络基础的人用的. 

“tcp网络程序的传输承载”你就理解成, 原来"TCP"默认是邮政负责的, KCP就是顺丰; 顺丰比邮政贵, KCP比普通TCP流量多; 同城收发邮政和顺丰都是次日达, 就是两端有稳定低延迟的连接, 用KCP不会比普通TCP快, 却更费流量, 实际效果可能反而更慢; 跨省跨国收发邮政可能要3-7天, 顺丰只要1-2天, 就是两端连接不稳定或延迟高, 用KCP就可能比普通TCP快.

以上是我个人的理解. 你也可以简单理解为KCP是个网络代理工具, 但与一般的代理不同, KCP很可能让你的实际网速变快!
