### ISSUE TITLE
内存占用极高，路由器无法运行，型号网件3800

### ISSUE THREAD

**Issue by XiaoMuIns** [xtaci/kcptun#453]
![image](https://cloud.githubusercontent.com/assets/24638429/26294101/e8947e16-3ef3-11e7-9b5a-552c39d7fa78.png)

固件是openwrt 15.05

**Comment by dearneo** [comment]
golang就是这么分配虚拟内存的，实际使用内存要看常驻内存，首行的内存信息很清楚了，已用47106K，可用79124K，要是真用了773m，内存早就爆了

**Comment by XiaoMuIns** [comment]
@dearneo 今天捣鼓了一天，愣是没找到原因。我怀疑是固件问题，那我把这个issue关了吧
