### ISSUE TITLE
希望程序内置一个socks代理服务.

### ISSUE THREAD

**Issue by flynaj** [xtaci/kcptun#456]
这个可以少一个程序.也简单方便多了.

**Comment by xtaci** [comment]
你可以自己加，应该就是一两行代码的事。 

https://github.com/armon/go-socks5 用ServeConn

这个库不加，因为主要用于调试。

**Comment by cs8425** [comment]
自己加+1
如果只要socks5 + CONNECT指令
可以不用另外引入庫
參考這個: http://www.golangnote.com/topic/141.html
在server端加個function就行了
