### ISSUE TITLE
mac上，Safari一段时间（大概半个小时）没用进行搜索，再次搜索的时候不能翻墙

### ISSUE THREAD

**Issue by plumhly** [xtaci/kcptun#457]
mac上，Safari一段时间（大概半个小时）没用进行搜索，再次搜索的时候不能翻墙，大概需要5分钟左右才能翻墙，期间server和client进程都在运行。

**Comment by MysteryAngle** [comment]
有可能与网络有关，因为某些地区运营商会检测这个东西，然后暂时给你封掉。

**Comment by dengshenkk** [comment]
你的mac客户端闪退吗?

**Comment by MysteryAngle** [comment]
闪退没有出现，但是有几个点需要注意一下，首先就是C/S版本一定要匹配得上，避免版本不一致出现奇怪的问题。其次就是自身网络提供商，我自身的感受就是好像把UDP给封掉了一样，估计是检测到了波值。
