### ISSUE TITLE
Add connection status check between client and server

### ISSUE THREAD

**Issue by holywen** [xtaci/kcptun#459]
Can we add a mechanism to check the connection status between the client and server, for example:
   in client:  local listen address (default: ":12948") and  kcp server address (default: "vps:29900"),
How can we know that the connection between the client and the server is good?

Can we add one status check address in the client side, like :"12949", which will returns http status code like 503 service unavailable,500 internal error,200 OK when we try to access http://localhost:12949/status ?  

This will enable us to using program to check the connection status automatically, and add recover mechanism (send email or restart the service), will make it much easier to maintain.

Br.
Holy

**Comment by wangyu-** [comment]
so,i assume your are using kcptun to tunnel some server directly?such as:
actual client---->kcp client---->kcp server  ---->actuall server.
to implement a connection status check,you can use kcptun to tunnel a socks5 proxy. and access your server via the tunnelled socks5:
actual client---->kcp client---->kcp server  ---->socks5---->actuall server.
then, do custom connection check with a echo server.
connection_check_program---->kcp client---->kcp server  ---->socks5---->echo server
if you can get echo message ,then your connection is good.
