### ISSUE TITLE
20160623 conn=4 时 Dropbox 上传失败

### ISSUE THREAD

**Issue by yaleh** [xtaci/kcptun#46]
很高兴看见 conn 的实现，对于大上行阻塞其它连接流量有帮助。但今天的测试中，使用 conn=4 在Chrome中向 dropbox.com 上传 10MB 文件始终失败。换成 20160605 SNMP 版本上传成功。所以我现在还是退回到自己用 20160605 SNMP 4进程加 pen 做负载均衡，近两周在小型办公场景中运行稳定，只是内存吃得比较厉害。

**Comment by xtaci** [comment]
@yaleh 你确认下md5sum
上行带宽本来就很低， 0623的版本对FEC 和内存有巨大优化，建议在0623的基础上做负载均衡

**Comment by yaleh** [comment]
估计 0623 + pen 的表现会更好。

也希望 conn 的实现能继续改进，如果足够好我就可以不用 pen 了。

**Comment by xtaci** [comment]
STREAM-ARQ就是想解决这个问题，很难，只能慢慢来。

**Comment by xtaci** [comment]
@yaleh 试过在client端加参数  ``` -dscp 46``` 没？
