### ISSUE TITLE
厉害了，好像不会断流了

### ISSUE THREAD

**Issue by outoftheloopxa** [xtaci/kcptun#460]
不知从哪个版本起就再没断过流，感觉很爽

**Comment by smdhz** [comment]
不，这个真的只看运营商心情

**Comment by outoftheloopxa** [comment]
我还发现要想得到最快最稳定的速度的关键不是设置一个合适的sndwnd和rcvwnd, 而是用tc限速.
sndwnd和rcvwnd过低的话速度慢, 过高的话vps上传爆表而客户端下载速度却依然很慢, 而且sndwnd和rcvwnd还会受到ping的影响

我得到快速稳定的速度的方法就是把sndwnd和rcvwnd设置到一个充足的数值上, 然后用tc把速度限制到比家里的宽带的极限速度稍微小一点的速度上.

比如我的宽带下载速度的上限大概在24.9mbps, sndwnd和rcvwnd在400的时候下载速度大概有15-19mbps, 于是我把sndwnd和rcvwnd设置为1000, 这就很充足了, 但没必要过分充足, 然后用在vps用tc限速24mbit, 这样得到的下载速度非常稳定.

这样有一个弊端就是需要同时上传和下载大文件的时候速度会受到限制, 不过我觉得利还是远远大于弊的.

附上一个很简单的tc限速的方法, 这里网卡是ens3
```
tc qdisc del dev ens3 root
tc qdisc add dev ens3 root handle 1: htb default 1
tc class add dev ens3 parent 1: classid 1:1 htb rate 24mbit
```

**Comment by hhding** [comment]
很正常啊，只要上行或者下行打爆了，所有连接都会卡顿的。

**Comment by vipsbpig** [comment]
想问一下openvz如何做限速？outoftheloopxa的方法并不能用

**Comment by outoftheloopxa** [comment]
openvz没法用tc吧，好像linux也没什么其他的限速工具，openvz没人权啊:joy:
