### ISSUE TITLE
ar71xx openwrt "not a Kcptun executable file" 

### ISSUE THREAD

**Issue by gongmingwei** [xtaci/kcptun#462]
Hi All

I updated both my vps server and all the client side with the latest version 20170525. Both clients on raspberry pi and windows work like charms, however, I failed to run the client on my openwrt netgear with luci interface from (https://github.com/kuoruan/luci-app-kcptun) . 

It always reminders me that "not a Kcptun executable file" no matter the mips and mipsle version...

Does anybody meet the similar issue or not?

Thanks

**Comment by terrytw** [comment]
#381

**Comment by kuoruan** [comment]
"MIPS FPU Emulator" is disabled by default, you need enable it in ```make kernel_menuconfig```
Or you can try https://github.com/bettermanbao/openwrt-kcptun/releases

**Comment by jackyshan** [comment]
@kuoruan 4300用了你的这个openwrt-kcptun，一直断开又连接，断开又连接，不稳定，kcp服务器版本是kcptun version 20170525

**Comment by kuoruan** [comment]
@jackyshan  请 @bettermanbao 问问，可能是版本的问题。

**Comment by bettermanbao** [comment]
client端先放在电脑上运行，全部调通没问题后再放到路由上。
kcptun在ar71xx和ramips的路由上我都试过，完美运行。

**Comment by jackyshan** [comment]
好的，谢谢

**Comment by jackyshan** [comment]
@bettermanbao 

![2017-07-16 16 58 39](https://user-images.githubusercontent.com/9671825/28246261-5eda0670-6a48-11e7-822f-7a72a31a60bd.png)

一直在session marked as expired，session normally closed，没连上过

执行命令是
kcptun -r "xx:xx" -l ":12948" -key test -crypt aes -mode fast3 -mtu 1350 -sndwnd 512 -rcvwnd 512 -datashard 10 -parityshard 3 -dscp 0 -nocomp false

**Comment by jackyshan** [comment]
@bettermanbao @kuoruan 解决了
https://github.com/xtaci/kcptun/issues/302
关闭压缩可以了

**Comment by jackyshan** [comment]
kcptun -r "xxxx:1338" -l ":18848" -key "xxx" -crypt aes -mode fast3 -mtu 1350 -sndwnd 512 -rcvw
nd 512 -datashard 10 -parityshard 3 -dscp 0 -nocomp true
