### ISSUE TITLE
用搬瓦工看youtube视频无法正常开始

### ISSUE THREAD

**Issue by islercn** [xtaci/kcptun#463]
最近又入了一个搬瓦工，洛杉矶KVM，各种配置和之前的一致，然后发现一个问题：

用搬瓦工ss+kcptun的时候，拿chrome看视频无法正常开始，一直缓冲（有速度）。如果先用ss直连让视频开始播放，再切到ss+kcptun，则可以正常播放，而且速度很快，4K不卡。看日志也没什么奇怪的内容，除了连接关闭外也只是个别的“session reached scavenge ttl”、“session marked as expired”。期间网页都是正常访问，无断流。

用其他几个vps都无此问题（都可以正常开始），本地网络为联通50M，路由器为openwrt x86，用的最新的ss和kcptun，客户端配置如下（服务器sndwnd也为2048）：

{
    "localaddr": ":555",
    "remoteaddr": ":666",
    "key": "777",
    "crypt": "none",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 300,
    "mtu": 1350,
    "sndwnd": 512,
    "rcvwnd": 2048,
    "datashard": 30,
    "parityshard": 15,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 10,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10,
    "log": "/var/log/kcptunclient.log"
}

**Comment by islercn** [comment]
这个应该是guo某在youtube直播时被D导致的，和kcptun无关

**Comment by wxjeacen** [comment]
我也遇到了同样的问题， 没法播放视频，但是网页可以打开youtube.

你后来是怎么解决的？

**Comment by islercn** [comment]
v2ex上有人给的方法，ipset单独标记googlevideo.com，tcp流量走ss+kcp，udp流量drop掉

**Comment by socgerlia** [comment]
这个问题，貌似是最近开始youtube会用udp传输，而kcptun不支持udp
有个解决方法是：
打开chrome://flags，找到实验性 QUIC 协议，选禁用

**Comment by islercn** [comment]
楼上给出的是chrome浏览器的解决办法，如果平时只用chrome看，那目前也可以算是解决了

**Comment by socgerlia** [comment]
话说kcptun有没有考虑支持udp啊，不然遇到这种问题还是挺蛋疼的

**Comment by shNanChen** [comment]
我说这两天怎么youtube网站开，视频怎么也不能播，原来是视频流走QUIC了。
luci-app-shadowsocks 可以设备TCP 和 UDP走不通服务器，
现在设置TCP是走kcp+shadowsocks，而UDP直接走shadowsocks，
最近网络丢包情况还可以，5%以内的，速度还可以接受。

[Google’s QUIC protocol: moving the web from TCP to UDP](https://ma.ttias.be/googles-quic-protocol-moving-web-tcp-udp/)

**Comment by genics** [comment]
我靠,板瓦工都中招....

**Comment by trivita** [comment]
@socgerlia sockscap就好了吧

**Comment by outoftheloopxa** [comment]
看来都是用ss-redir的人遇到问题啊, 话说youtube早就开始用quic了.
如果是给浏览器用socks或者http代理, udp自然而然就被阻断了, 安卓的ss现在不是除了dns以外udp都强制转发么, 如果想禁用udp只能ss服务端不开udp.
不过我现在都不用ss了, 直接kcptun+squid, 直接用http代理, 安卓上啥都不用装了, 不过只能在家用, 不过出门我也不翻墙, 无所谓.

**Comment by hdstar2009** [comment]
现在来看，说udp不转发，youtube不能正常的说法是不对的。
只有那几天（就是大家开始讨论什么quic的那几天，看这贴是jun）才出现问题，之后都没问题，我都是在电脑上用ssr的客户端不用设置任何udp转发都正常看y2b
