### ISSUE TITLE
Windows Timer Resolution locked to 1ms

### ISSUE THREAD

**Issue by RadarNyan** [xtaci/kcptun#464]
1. Check current timer interval with https://technet.microsoft.com/en-us/sysinternals/bb897568.aspx
2. Start kcptun (client_windows_amd64.exe)
3. Check again, timer interval is set to 1ms

Is this behavior really necessary?

**Comment by xtaci** [comment]
cannot understand your question

**Comment by defia** [comment]
https://github.com/golang/go/issues/8687
