### ISSUE TITLE
aes instruction support

### ISSUE THREAD

**Issue by PtDragon** [xtaci/kcptun#465]
Hello! Is it possible to add support for aes hardware instructions like AES-NI? 
I'm asking because for same traffic app with support of AES-NI(based on openssl) spends 3-4% of CPU time while kcptun spends 95-100% of CPU time.

**Comment by cs8425** [comment]
kcptun use golang's built-in [aes package](https://golang.org/pkg/crypto/aes/) which support AES-NI.
So it should be support AES-NI.
Try `salsa20`, and see how much CPU time?

**Comment by PtDragon** [comment]
salsa20 is just a bit faster than aes-256
Should i test if no encryption will improve speed much?
