### ISSUE TITLE
请问有人试过用ipv6的地址吗

### ISSUE THREAD

**Issue by LukeLu0415** [xtaci/kcptun#468]
使用vps的ipv4可以正常科学上网，但是试了ipv6，总是访问不了，请问有人成功过吗

**Comment by wlzjit** [comment]
同IPV6，飞一样。反而IPV4经常断流。
`d:/kcptun/client_windows_amd64 -l [::]:2000 -r [ipv6address]:port -key "key" -crypt "aes-128" -mode fast2 -mtu 512 -sndwnd 4000 -rcvwnd 4000 -conn 8 -autoexpire 3 -dscp 46`

**Comment by daiaji** [comment]
嗯……
据我所知大陆的运营商都没有开放ipv6吧……
而且ipv6貌似强制加密
部署的话流量审查就基本报废了吧
所以很有可能是你的运营商没开ipv6

**Comment by YunyanDeng** [comment]
我用教育网的ipv6可以
