### ISSUE TITLE
求docker中下载最新版的办法

### ISSUE THREAD

**Issue by listenfree** [xtaci/kcptun#469]
准备部署到docker中，能否提供一个类似
wget ......../release/realase_arm.gz，的办法，而不用每次看最新版是多少，
再改下载地址，小白一枚，见谅！

**Comment by xtaci** [comment]
docker pull xtaci/kcptun

**Comment by listenfree** [comment]
arm cpu，docker golang 环境不是很完美，只能直接下载编译后的版本，上面的办法好象不好使

**Comment by daiaji** [comment]
@listenfree docker在安卓上有客户端吗？kcp好像都没有
