### ISSUE TITLE
翻资料时看到一个挺不错的RaptorQ

### ISSUE THREAD

**Issue by wlzjit** [xtaci/kcptun#47]
大神们要不要考虑一下~

这种FEC是用不着重传的！

而且有现成的库
https://github.com/LucaFulchir/libRaptorQ

**Comment by xtaci** [comment]
看了一下，重传在需要保证顺序的传输上，是必不可少的。  
比如100%丢包，怎么可能不重传呢？
RaptorQ说的不重传，只是说在一定的丢包率下，纠错后音视频不受影响而已。

**Comment by wlzjit** [comment]
关了吧，也没个人会。。。
