### ISSUE TITLE
OSX客户端使用终端启动总是在connection阶段卡住

### ISSUE THREAD

**Issue by orangeinsc** [xtaci/kcptun#471]
服务器端设置完成后将参数保存为.json格式的文件，使用bash敲入client_darwin_amd64 -c config.json这个命令后本机的输出日志总是卡在connection这个步骤上。请问各位大神有解决的办法么？万分感谢！！
      服务端与客户端版本号都是20170525. 服务器设置除密码外均是默认设置。服务器是搬瓦工的centos6 x86。 iptables开启了默认的29900UDP端口。ss端口为443.
https://github.com/orangeinsc/datasharing/blob/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-06-27%20%E4%B8%8B%E5%8D%8811.14.42.png

**Comment by whxjf** [comment]
从日志上看443没有权限，是否其他应用占用。
1、检查os x防火墙
2、本地侦听端口换一个试试，比如88888

**Comment by orangeinsc** [comment]
@whxjf 十分感谢您的回复，我现在就去试试，我还有一个疑问就是会不会是本地电信屏蔽了UDP的上行下行流量？

**Comment by whxjf** [comment]
@orangeinsc 电信没这么变态吧，服务端的json文件与客户端的json文件有些许不同，但key、crypt、datashard、parityshard要保持一致，可以仔细检查。另外既然用ss，为什么还要用命令行的kcptun，新的ShadowsocksX-NG已经内置支持kcptun了。

**Comment by orangeinsc** [comment]
@whxjf 请问您是在linux服务器上使用go-get安装的服务端吗？我使用的扩软的一键脚本，我在想1.会不会是脚本的问题。2.我还在我的bwg上安装了ipsec，会不会是vps的iptables的问题？如果都不是的话我打算重新安装OSX了，也许是什么地方设置出问题了但是查不出来233333.........最后还是谢谢你的回复😄

**Comment by whxjf** [comment]
我也是bwg上用扩软的脚本安装，版本v18，ipsec vpn?没装过，iptables也只放行了29900端口，希望你能找到解决办法:muscle:

**Comment by orangeinsc** [comment]
@蟹蟹😄

**Comment by orangeinsc** [comment]
我卸载了qq for mac后使用ss－NG后连接成功，然而我也不知道具体为什么。谢谢你前几天的鼓励！ @whxjf
