### ISSUE TITLE
惊奇的现象，一个极烂的vps（youtube直连ss速度200Kbps）,使用kcptun能达到70000Kpbs？！以前只有1万左右

### ISSUE THREAD

**Issue by kangshoo** [xtaci/kcptun#473]
惊奇的现象，一个极烂的vps（youtube直连ss速度200Kbps）,最近kcptun能达到70000Kpbs？！
这不是重点，重点是我的kcptun客户端（路由器），居然没有什么cpu占用，之前，我也是这个烂服务器，使用kcptun之后，youtube最多达到12000Kpbs，而且路由的7260cpu占用40%左右，现在这么高速度，反而没有cpu占用，这是为什么？
服务器端使用top查看，cpu用也非常低。
我也没做什么特别优化，究竟是咋了。。。。

**Comment by kangshoo** [comment]
补充说明一些情况：
烂vps ping平均300  丢包7%左右
服务器端配置
{
"listen": ":439",
"target": "127.0.0.1:440",
"key": "***",
"crypt": "salsa20",
"mode": "manual",
"mtu": 1400,
"sndwnd": 256,
"rcvwnd": 1024,
"datashard": 0,
"parityshard": 0,
"dscp": 46,
"nocomp": true,
"acknodelay": false,
"nodelay": 1,
"interval": 40,
"resend": 0,
"nc": 1,
"sockbuf": 4194304,
"keepalive": 10
}

**Comment by mixool** [comment]
我看作者最近的更新都集中在CPU的占用问题上，应该是这个的效果。

**Comment by terrytw** [comment]
你大概用的是chrome，然后没有开UDP转发
然后QUIC导致你直连了
https://github.com/shadowsocks/shadowsocks-libev/issues/970
https://www.v2ex.com/t/370189

**Comment by wangmingg** [comment]
应该是直连了， 发自网易邮箱大师 在2017年07月13日 20:49，terrytw 写道： 你大概用的是chrome，然后没有开UDP转发 然后QUIC导致你直连了 shadowsocks/shadowsocks-libev#970 https://www.v2ex.com/t/370189 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kangshoo** [comment]
@terrytw @wangmingg 
应该是这样的，你们确实厉害。
