### ISSUE TITLE
作者你好,我是菜鸟,实在是搞不懂LINUX一类的,能否请教win下的问题?

### ISSUE THREAD

**Issue by itiszg** [xtaci/kcptun#474]
我用的是SS(付费用户),没有自己搭建任何服务,就是windows10系统下下载了个Shadowsocks,导入网站给的配置文件gui-config.json,然后启用代理,用全局就可以翻了.
但是延迟有点大,以前用过FS,好用,看youtube无压力. 现在没有了FS,有点慢,缓冲太频繁了,我也没有资源搭建kcptun服务器,请问我能用这个kcptun加速吗?(纯windwos)

**Comment by kangshoo** [comment]
不行。。。你只是ss付费用户是不行的

**Comment by recall704** [comment]
需要有自己的 服务器 才行。

**Comment by itiszg** [comment]
那就是说,我需要在家庭宽带出口搭建一个服务器? 并且架好SS的服务才可以了?

**Comment by PiaoL** [comment]
你得购买一个vps服务器搭建自己的ss，在这个服务器上安装kcptun-server端，在win上安装kcptun-client端才能使用kcptun加速。关于搭建自己的ss，搜一下，很多教程。

**Comment by shNanChen** [comment]
既然你是付费用户，可以买个速度快点的SS服务，香港日本的速度不挺快，不需要+KCPTUN

**Comment by brainwashing** [comment]
https://doub.io/   去这个网站自己学着去搭建

**Comment by shawhu** [comment]
怕麻烦的去买服务，香港的服务器不用kcptun，直连速度超过100mbps
kcptun用于把<5美金一个月的三流vpc利用起来达到>20mbps的速度，问题是你要a)有一个烂vpc，b)要花半天时间来搞

**Comment by liangrena** [comment]
这是不想花多余的钱，又喜欢折腾的人玩的，你都花钱买了SS付费服务了，不如买个更好的比如上面推荐的香港的付费SS岂不是爽死.
我就是不想花多余的钱所以买个11元每月的烂vps，然后走上了不归路.
搭建ss其实很简单(网上有个叫"秋水逸冰"写了很多一键安装包)，搭建kcptun服务的也很简单(blog.kuoruan.com这个博客的作者就写了一键安装包)，复杂的在于低配VPS的优化与安全问题和kcptun的优化问题，我花了更多时间在这些个上面
