### ISSUE TITLE
server端流量流出异常

### ISSUE THREAD

**Issue by geligaoli** [xtaci/kcptun#477]
使用的是 0525 的最新版本，系统是debian 8.8
Sever端的配置
{
"listen": ":2549",
"target": "127.0.0.1:1080",
"key": "××××××××××××××××",
"crypt": "aes",
"mode": "fast2",
"mtu": 1360,
"sndwnd": 1024,
"rcvwnd": 1024,
"datashard": 70,
"parityshard": 30,
"dscp": 46,
"acknodelay": false,
"nodelay": 0,
"interval": 40,
"resend": 0,
"nc": 0,
"sockbuf": 2097152,
"keepalive": 10
}
因为是收到了服务商的报警才发现的。从6月底开始，始终的以4-5M左右的速度对外发包。导致7月份入口流量3G，出口流量430G。这个服务器只是个人用于备用的代理，平时用的很少。而且在server一直发包的情况下，看client的流量是0，并没有使用。
这种情况，是配置参数有问题，还是程序可能有bug？

**Comment by shNanChen** [comment]
和kcptun应该是没关系的，是不是服务器被入侵了？
我之前被服务商停用主机理由是发垃圾邮件，查了很久，都重装系统了还乱发邮件，凌乱了都，
后面才搞清楚，我在client端有开自己不怎么用的socks端口，被别人扫描后利用了，
所以还是找找自己的原因

**Comment by geligaoli** [comment]
为什么说“和kcptun应该是没关系的” ？ 服务器检查过了没有被入侵，而且停止了kcptun的server端程序，流量就正常了，所以怀疑是kcptun程序有bug。

**Comment by ywqwancbx** [comment]
UDPFlood 设置一下防火墙规则,应该能解决.
