### ISSUE TITLE
what is the minimum performance of a home Router to run kcptun?

### ISSUE THREAD

**Issue by sammychiang** [xtaci/kcptun#478]
minimum cpu and RAM requirement?

**Comment by terrytw** [comment]
I believe you can run kcptun on most routers that support third-party firmware. It's just that the performance may suffer. Kcptun is not made for routers, it's optimized against AMD64 platform.

**Comment by vampirehime** [comment]
It works fine on my Netgear R6220 which has a MT7621ST (880 MHz) CPU and 128MB RAM.
