### ISSUE TITLE
最低的路由器配置是多少才能使用kcptun？

### ISSUE THREAD

**Issue by sammychiang** [xtaci/kcptun#479]
比如内存，cpu

**Comment by kangshoo** [comment]
合理配置 7620a 就可以

**Comment by daiaji** [comment]
7620的k2上挂KCP和SS速率好像是800kb/s
7621会好一点？

**Comment by ccsexyz** [comment]
小米路由器3上我印象中大约能跑到20Mbps

**Comment by daiaji** [comment]
MT7621的K2P上大概是跑到2.8mb/s
KCP+SSR 
具体就没测了 加密是salsa20和chacha20-ietf

**Comment by chilejiang1024** [comment]
@ccsexyz 小米路由器3上能装kcptun? 3c 可以么?

**Comment by laikitleung** [comment]
小米系列路由，直接下载mipsle版复制进去加参数文件运行就可以，就是R3以下的型号CPU有可能爆满

**Comment by dvquest** [comment]
@daiaji 可否提供一下你在K2P上使用的Kcptun客户端，我网上的下遍了，没一个能用的，LUCI界面显示客户端未运行，日志都提示Client file validation failed. 邮箱fans1804@outlook.com
