### ISSUE TITLE
配置问题,小白求助

### ISSUE THREAD

**Issue by tonyGitHubRunoob** [xtaci/kcptun#48]
### 客户端错误:
**2016/06/25 20:51:58 version: 20160623
2016/06/25 20:51:59 listening on: [::]:12948
2016/06/25 20:51:59 encryption: aes
2016/06/25 20:51:59 nodelay parameters: 1 20 2 1
2016/06/25 20:51:59 remote address: 23.105.214.29:29900
2016/06/25 20:51:59 sndwnd: 256 rcvwnd: 2048
2016/06/25 20:51:59 mtu: 1400
2016/06/25 20:51:59 datashard: 10 parityshard: 3
2016/06/25 20:51:59 acknodelay: false
2016/06/25 20:51:59 dscp: 0
2016/06/25 20:51:59 conn: 4
2016/06/25 20:52:05 stream opened
2016/06/25 20:52:05 stream opened
...**

### 服务端错误:
**2016/06/25 08:49:17 version: 20160623
2016/06/25 08:49:17 listening on  [::]:29900
2016/06/25 08:49:17 encryption: aes
2016/06/25 08:49:17 nodelay parameters: 1 20 2 1
2016/06/25 08:49:17 sndwnd: 2048 rcvwnd: 2048
2016/06/25 08:49:17 mtu: 1400
2016/06/25 08:49:17 datashard: 10 parityshard: 3
2016/06/25 08:49:17 acknodelay: false
2016/06/25 08:49:17 dscp: 0
2016/06/25 08:52:02 remote address: 113.251.58.186:16169
2016/06/25 08:52:02 stream opened
2016/06/25 08:52:02 stream closed
2016/06/25 08:52:02 remote address: 113.251.58.186:16170
2016/06/25 08:52:02 stream opened
2016/06/25 08:52:02 stream closed
2016/06/25 08:52:02 remote address: 113.251.58.186:16171
2016/06/25 08:52:02 stream opened
2016/06/25 08:52:02 stream closed
2016/06/25 08:52:02 remote address: 113.251.58.186:16172
2016/06/25 08:52:02 stream opened
2016/06/25 08:52:02 stream closed
2016/06/25 08:52:02 stream opened
2016/06/25 08:52:02 stream closed
2016/06/25 08:52:02 stream opened
2016/06/25 08:52:02 stream closed
2016/06/25 08:52:02 stream opened
...**

### 客户端配置:
**Dim RunKcptun
Set fso = CreateObject("Scripting.FileSystemObject")
Set WshShell = WScript.CreateObject("WScript.Shell")
'获取文件路径
currentPath = fso.GetFile(Wscript.ScriptFullName).ParentFolder.Path & "\"
'软件运行参数
exeConfig = "client_windows_amd64.exe -l :12948 -r 23.105.214.29:29900 -key test -mtu 1400 -sndwnd 256 -rcvwnd 2048 -mode fast2 -conn 4"
'日志文件
logFile = "kcptun.log"
'拼接命令行
cmdLine = "cmd /c " & currentPath & exeConfig  & " > " & currentPath & logFile & " 2>&1"
'启动软件
WshShell.Run cmdLine, 0, False
'等待1秒
'WScript.Sleep 1000
'打印运行命令
'Wscript.echo cmdLine
Set WshShell = Nothing
Set fso = Nothing
'退出脚本
WScript.quit**

### 服务端配置:
**./server_linux_amd64 -l :29900 -t 127.0.0.1:443 -key test -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2 > kcptun.log 2>&1 &**

服务器OS: Centos 6 x86_64 RAM:256
客户端OS: windows7 64
重庆电信光纤100M

我在用shadowsocks,参考的此教程:[https://blog.kuoruan.com/102.html](url)

**Comment by D-Bood** [comment]
你可以试试两边同时-encryption none
p.s. 如果你用ss的话推荐你用这个教程：http://www.fanyueciyuan.info/fq/kcptun_ss.html

**Comment by tonyGitHubRunoob** [comment]
@D-Bood  我看看,O(∩_∩)O~,谢谢你的回复

**Comment by tonyGitHubRunoob** [comment]
@D-Bood http://www.fanyueciyuan.info/fq/kcptun_ss.html, 用chrome访问是:ERR_CONNECTION_RESET  /(ㄒoㄒ)/~~

**Comment by xtaci** [comment]
没有看到错误啊，不是都正常stream open close了么

**Comment by D-Bood** [comment]
我也觉得应该没错，，，不过我怀疑是那个教程的问题，，，虽然404了
不过我看的教程竟然被那啥了，，，明明前几天还可以上的

**Comment by tonyGitHubRunoob** [comment]
@xtaci  我是按我给的那个教程来配置的,我不清楚是不是错误,我用shadowsocks通过kcptun访问不上YouTube,感谢指点

**Comment by xtaci** [comment]
不清楚，我不用ss, 如果只是y2b不行，那么多半是dns污染

**Comment by xtaci** [comment]
另外，服务器端口号建议554/1755这种udp流媒体端口

**Comment by tonyGitHubRunoob** [comment]
@xtaci 我是打不开YouTube, /(ㄒoㄒ)/~~, 我小白一只,说的白话一点最好

**Comment by xtaci** [comment]
这个问题不在此软件范围之类，请自行google dns污染

**Comment by tonyGitHubRunoob** [comment]
@D-Bood 我不只是youtube访问不起,还有google,我只是声明一下我的情况,可以不用回 O(∩_∩)O~

**Comment by xtaci** [comment]
嗯，可以咨询相关专业人士。 kcptun只解决速度问题。

**Comment by tonyGitHubRunoob** [comment]
问题解决了,我在shadowsocks客户端上把密码搞混了,(⊙﹏⊙)
