### ISSUE TITLE
Balancing and delays

### ISSUE THREAD

**Issue by PtDragon** [xtaci/kcptun#480]
In normal config with several connections it looks like kcptun uses only one at a time which is not enough for sure for filling several ISP pipes.
Hope there will be support to use all connections in parallel to acieve bigger speed for those who have multiple ISP links ;)
Could not see it before as previous VPS had jut one CPU core and CPU bas a big bottleneck there.

**Comment by xtaci** [comment]
i think it's the duty for the router,  kcptun can establish 2 connections to the server, and the router should disperse the connections into different ISP link.

**Comment by xtaci** [comment]
a completely dispersion of packets into random physical path sounds exciting, that's what other famous software like T*R or L***N  does. 

but the performance is not a concern.

actually, the overall speed will mostly limited to the slowest link.
