### ISSUE TITLE
aes over salsa20?

### ISSUE THREAD

**Issue by casparpoon** [xtaci/kcptun#481]
Hi Xtaci. I read your comment under issue #264 regarding why salsa20 is not the default method for encryption even it provides better performance than aes, and the reason is the IP may be blocked if salsa20 is used. Just wonder if there is any characteristic for the traffic with salsa20 that the Chinese government can identify on-the-fly?

**Comment by xtaci** [comment]
aes256 has proven security , i.e battle-tested, while salsa20 is not. 
so the default encryption method will always be AES-256
