### ISSUE TITLE
如果使用了kcptun，那么SSR的混淆和加密对于防检测和封IP来说还有没有意义？

### ISSUE THREAD

**Issue by zvit1** [xtaci/kcptun#482]
X大好，我有一个问题哈，当我同时使用kcptun和SSR时，SSR的混淆和加密对于防检测和封IP来说还有没有意义？
因为我理解的是，对于墙来说，只检测到了kcptun的客户端和服务端之间的通信，SSR客户端和服务端之间的通信是没有暴露给墙的，所以SSR的加密和混淆对于防检测和防封来说没有意义，想问一下我这种理解正确吗？

**Comment by Demired** [comment]
不正确

**Comment by zvit1** [comment]
@Demired 请问能稍微解释一下吗，我是小白额……

**Comment by zxbiao** [comment]
先理解并区分tco udp之间的区别，然后理解一下kcptun是工作在什么协议上。kcp只是传输，不带代理功能的。可以简单一点理解就是ss和ssr等破墙软件是货物，托运在tcp/udp这辆车上。由于tcp安全而容易被关注，而udp不安全，先到先得。为了整合这两个，kcp就应运而生。ss等是osi七层中的应用层，tcp udp是传输层，kcp也是传输层，跑在udp上而又能实现tcp的特性。

**Comment by zvit1** [comment]
@zxbiao 懂了您的意思了！谢谢！不是科班的，只听说过什么七层额……就是说kcp是一辆结合了tcp/udp优点的车。没用kcp的时候，tcp/udp是负责拉货的车辆，SSR负责生产货物，是货物的来源。现在走了kcp来拉货了，车上的货物还是那些货物，只是车变了，货还是那些货，交警(墙)想看货的话，就换辆车拦下来验货，是这样理解吗？

**Comment by zvit1** [comment]
感谢楼上大佬们的解答！

**Comment by wangyu-** [comment]
部分正确。
混淆是没有用了的，或者说作用降低到接近零。SSR本来是把tcp流量混淆成tcp http或者tcp ssl，以骗过QOS，用SSR+tcptun相当于在SSR的流量上又包了一层，混淆后的TCP流量现在变成了UDP流量，也就起不到骗过QOS的作用了，QOS可能会更严重。
加密仍然有用。
