### ISSUE TITLE
国内中转服务器改怎么操作？

### ISSUE THREAD

**Issue by amao000765** [xtaci/kcptun#486]
各位大神，本人菜鸟中，有一台国内有一台服务器centos7，准备做kcptun中转，其他手机电脑等通过中转服务器上网，请问各路大神，该如何操作，拜谢！

**Comment by wxlg1117** [comment]
kcptun只是个tcp加速软件,没有代理功能

**Comment by baggiogogo** [comment]
介个很简单的
服务器(国外)ss-server+kcptun-server--->服务器(国内)ss-redir+kcptun-client+ss-server--->客户(国内)ss-redir or ss-local
注意其中服务器(国内)上的iptables设置即可，参照ss WIKI。

**Comment by jizusun** [comment]
@baggiogogo  求问大神具体如何操作~
