### ISSUE TITLE
为什么需要smux来进行多路复用

### ISSUE THREAD

**Issue by icexin** [xtaci/kcptun#487]
RT.

想知道这么做的意图，谢谢！

**Comment by xtaci** [comment]
可以做到整体的流控

**Comment by icexin** [comment]
没太明白，是流量限制吗？

**Comment by xtaci** [comment]
流控

**Comment by icexin** [comment]
对流量的哪些控制，作用是啥

**Comment by xtaci** [comment]
if we don't do multiplexing, different connections will compete with each other for bandwidth,and finally leads to more packet loses
