### ISSUE TITLE
用了一段时间，发现磁盘空间被占满

### ISSUE THREAD

**Issue by xiasummer** [xtaci/kcptun#488]
您好，不知道为什么，用一段时间之后发现磁盘空间(总共20G左右)全部被占满，不知道到底是哪里出问题了。这个Kcptun+Shadowsocks的组合，其转发的数据在哪里呢？哪些文件夹是我可以删除的呢？

**Comment by xiasummer** [comment]
![image](https://user-images.githubusercontent.com/8190676/28992101-6a6ab1b8-7959-11e7-963b-a85c29ed2fac.png)

找了一下，发现了在 /var/discouse/shared文件夹中的庞大的压缩包，其拥有者是kcptun，这个就是kcptun的使用数据吗？为什么这个大压缩包会在discouse的文件夹下呢？

**Comment by xtaci** [comment]
你是从官方下载的么， kcptun不会输出任何压缩包.

**Comment by xiasummer** [comment]
那么，我想直接问一下怎么删除kcptun服务吧，因为我在 rebuild discourse服务的时候，发现127.0.0.1 被占用了，这个应该就是被kcptun的占用的。


IDEKIQS=1 -e RUBY_GLOBAL_METHOD_CACHE_SIZE=131072 -e RUBY_GC_HEAP_GROWTH_MAX_SLOTS=40000 -e RUBY_GC_HEAP_INIT_SLOTS=400000 -e RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.5 -e DISCOURSE_DB_SOCKET=/var/run/postgresql -e DISCOURSE_DB_HOST= -e DISCOURSE_DB_PORT= -e LETSENCRYPT_DIR=/shared/letsencrypt -e DISCOURSE_HOSTNAME=forum2.xiafamily.win -e DISCOURSE_DEVELOPER_EMAILS=xiasummer001@gmail.com -e DISCOURSE_SMTP_ADDRESS=smtp.mailgun.org -e DISCOURSE_SMTP_PORT=587 -e DISCOURSE_SMTP_USER_NAME=postmaster@xiafamily.win -e DISCOURSE_SMTP_PASSWORD=019c2424341fc8686a22137f780e3a38 -e DISCOURSE_SMTP_ENABLE_START_TLS=true -e LETSENCRYPT_ACCOUNT_EMAIL=xiasummer001@gmail.com -h xiafamily-app -e DOCKER_HOST_IP=172.17.0.1 --name app -t -p 80:80 -p 443:443 -v /var/discourse/shared/standalone:/shared -v /var/discourse/shared/standalone/log/var-log:/var/log --mac-address 02:34:05:ab:88:5c local_discourse/app /sbin/boot
7d8be95ab1448e2c3531a4726f52bf196a93f869e02e19529a07592323500244
/usr/bin/docker: Error response from daemon: driver failed programming external connectivity on endpoint app (d2f0c28d1b3ec0c1977fdd0d8d22185e97558b8ced40b23cda03bb4dd4ad56ec): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

**Comment by xiasummer** [comment]
我使用的是一键安装kcptun的教程

https://blog.kuoruan.com/110.html

**Comment by xtaci** [comment]
kcptun没有任何形式的服务， 启动脚本。只有可执行文件。其他第三方的封装请咨询创建者。

**Comment by xiasummer** [comment]
我刚下载下来并打开了kcptun的压缩包之后，发现里面的内容就是discourse中的内容。经过随后的修复过程，我认为该机制如下：

kcptun使用的端口为 127.0.0.1:80 与 discourse 使用相同的127.0.0.1:80
这可能导致了所有discourse中的内容都被kcptun作为内容打包起来了，从而每天会形成一个与discourse内容等大的压缩包，从而迅速将服务器空间占满。 

关于为什么kcptun会每天制作一个数据压缩包，可能是因为我使用的是一键安装模板 https://github.com/kuoruan/shell-scripts/issues/8 ，这个.sh文件中应该包含了每天将相关资料打包存储的命令，不过脚本相当长，我并没有深入阅读。

**Comment by cs8425** [comment]
@xiasummer 
怎看都像是你設定的定時備份discourse script造成的啊
你是用`kcptun`這個帳號跑discourse的吧...至少"定時備份"是用這個帳號

至於佔用, 
用`sudo netstat -ltunp`查是哪支程式佔用80 port
