### ISSUE TITLE
最新的代码会导致kcptun报错

### ISSUE THREAD

**Issue by linkerlin** [xtaci/kcptun#489]
./server -t *:8877 -mode fast3 -l ":8879"  --key 123456 --nocomp
2017/08/08 03:05:56 main.go:297: version: SELFBUILD
2017/08/08 03:05:56 main.go:110: lookup udp/8879 : Servname not supported for ai_socktype
net.ResolveUDPAddr
github.com/xtaci/kcp-go.ListenWithOptions
	/root/go/src/github.com/xtaci/kcp-go/sess.go:873
main.main.func1
	/root/go/src/github.com/xtaci/kcptun/server/main.go:328
github.com/urfave/cli.HandleAction
	/root/go/src/github.com/urfave/cli/app.go:490
github.com/urfave/cli.(*App).Run
	/root/go/src/github.com/urfave/cli/app.go:264
main.main
	/root/go/src/github.com/xtaci/kcptun/server/main.go:381
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197

**Comment by linkerlin** [comment]
-t 127.0.0.1:8877 也是一样的。

**Comment by linkerlin** [comment]
-t 127.0.0.1:8877 也是一样的。

**Comment by linkerlin** [comment]
前几天的版本还可以。

**Comment by linkerlin** [comment]
-l 127.0.0.1:8879 一样报错

**Comment by linkerlin** [comment]
使用默认端口，删去-l参数是可以的。

**Comment by linkerlin** [comment]
./server -t 127.0.0.1:8877 -mode fast3 -l ":22990"  --key 123456 --nocomp
-----------Listen::22990 
2017/08/08 03:35:33 main.go:298: version: SELFBUILD
2017/08/08 03:35:33 main.go:110: lookup udp/22990 : Servname not supported for ai_socktype
net.ResolveUDPAddr
github.com/xtaci/kcp-go.ListenWithOptions
	/root/go/src/github.com/xtaci/kcp-go/sess.go:873
main.main.func1
	/root/go/src/github.com/xtaci/kcptun/server/main.go:329
github.com/urfave/cli.HandleAction
	/root/go/src/github.com/urfave/cli/app.go:490
github.com/urfave/cli.(*App).Run
	/root/go/src/github.com/urfave/cli/app.go:264
main.main
	/root/go/src/github.com/xtaci/kcptun/server/main.go:382
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197

**Comment by linkerlin** [comment]
把端口设置成默认的29900也不行。

**Comment by linkerlin** [comment]
go version
go version go1.8.3 linux/amd64

**Comment by linkerlin** [comment]
问题找到了，应该做如下修改
func ListenWithOptions(laddr string, block BlockCrypt, dataShards, parityShards int) (*Listener, error) {
        udpaddr, err := net.ResolveUDPAddr("udp"**, strings.Split(laddr,":")[0])**

**Comment by linkerlin** [comment]
我提交了一个[PR](https://github.com/xtaci/kcp-go/pull/53)

**Comment by linkerlin** [comment]
我用配置文件就绕过了这个问题。
我想，问题出在命令行参数处理的库上，":" 这个符号被处理成UTF-8了。

我可以跑的JSON如下：
{
"listen":":8879",
"key":"123456",
"mode":"fast3",
"nocomp":true,
"target":"127.0.0.1:8877"
}

**Comment by linkerlin** [comment]
证据如下：
./server -t 127.0.0.1:8877 -mode fast3 -l ":29900"  --key 123456 --nocomp
-----------Listen::29900 
2017/08/08 13:19:39 main.go:298: version: SELFBUILD
2017/08/08 13:19:39 sess.go:874: laddr::29900 
2017/08/08 13:19:39 sess.go:875: len(laddr):8

**Comment by linkerlin** [comment]
从命令行参数传入的 ":"符号长度为 8-5=3，是一个UTF-8字符。
太坑了~

**Comment by linkerlin** [comment]
2017/08/08 13:30:28 sess.go:874: laddr::29900 
2017/08/08 13:30:28 sess.go:876: ladder[ 0 ] 58
2017/08/08 13:30:28 sess.go:876: ladder[ 1 ] 50
2017/08/08 13:30:28 sess.go:876: ladder[ 2 ] 57
2017/08/08 13:30:28 sess.go:876: ladder[ 3 ] 57
2017/08/08 13:30:28 sess.go:876: ladder[ 4 ] 48
2017/08/08 13:30:28 sess.go:876: ladder[ 5 ] 48
2017/08/08 13:30:28 sess.go:876: ladder[ 6 ] 160
2017/08/08 13:30:28 sess.go:878: len(laddr):8

**Comment by linkerlin** [comment]
2017/08/08 13:30:50 sess.go:874: laddr::29900
2017/08/08 13:30:50 sess.go:876: ladder[ 0 ] 58
2017/08/08 13:30:50 sess.go:876: ladder[ 1 ] 50
2017/08/08 13:30:50 sess.go:876: ladder[ 2 ] 57
2017/08/08 13:30:50 sess.go:876: ladder[ 3 ] 57
2017/08/08 13:30:50 sess.go:876: ladder[ 4 ] 48
2017/08/08 13:30:50 sess.go:876: ladder[ 5 ] 48
2017/08/08 13:30:50 sess.go:878: len(laddr):6

**Comment by linkerlin** [comment]
上面两个，第一个是异常情况，从命令行指定-l参数后的laddr的内容。
第二个是没有指定-l参数，正常运行的情况。

**Comment by linkerlin** [comment]
对比上述两个输出，可以看到，从命令行指定-l参数，多了3个字节，也就是多了一个字符 160。

**Comment by linkerlin** [comment]
160是一个Unicode字符，也就是HTML空格。
我把-l参数放在命令行的最后一个就可以正常运行了。
应该是 命令行参数处理库的问题。

**Comment by linkerlin** [comment]
最终可运行的命令 
./server -t 127.0.0.1:8877 -mode fast3  --key 123456 --nocomp  -l :8879
不过，感觉，一定要把-l放在最后一个参数比较不雅。

**Comment by phpstudyer** [comment]
👎   😄   🎉   😕
