### ISSUE TITLE
客户端DNS解析问题

### ISSUE THREAD

**Issue by wxyzh** [xtaci/kcptun#49]
客户端的-r参数使用域名时会出现dns无法解析，报错信息如下
2016/06/27 14:56:28 lookup xxx.xxx on 223.5.5.5:53: dial udp 223.5.5.5:53: i/o timeout.
ping 该域名能ping通，并且能解析到正确的ip地址

**Comment by xtaci** [comment]
cat /etc/resolv.conf

**Comment by wxyzh** [comment]
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 221.131.143.69
nameserver 112.4.0.55
nameserver 223.5.5.5

**Comment by xtaci** [comment]
223.5.5.5 不通

**Comment by wxyzh** [comment]
223.5.5.5部分地区ping不通，但是能解析
