### ISSUE TITLE
关于FEC请教

### ISSUE THREAD

**Issue by baggiogogo** [xtaci/kcptun#490]
是否同等条件下，使用5/5的FEC比使用10/3的FEC，CPU负担更重？

**Comment by wangyu-** [comment]
我觉得这个除了实现了这个RS code库的作者以外，别人不做测试或者仔细研究代码都不好下结论。

这个库的原始发布者 ： https://github.com/Backblaze/JavaReedSolomon

如果联系不上作者，还是以自己测试为准吧。

**Comment by baggiogogo** [comment]
好的！先关。
