### ISSUE TITLE
kcptun 只能依附于别的代理工具（SS）下使用还是独立就可以使用

### ISSUE THREAD

**Issue by channingbox** [xtaci/kcptun#493]
如题

**Comment by wangyu-** [comment]
独立就能用。但是独立用只能对一个端口加速。套上ss之后才能用得方便。

**Comment by wangyu-** [comment]
独立就能用。但是独立用只能对一个端口加速。套上ss或者其他socks5代理之后才能用得方便。

**Comment by channingbox** [comment]
什么意思 只能加速一个端口是什么意思

**Comment by wangyu-** [comment]
比如你配了一个kcptun加速 44.55.66.77:22，你要是想加速44.55.66.77:80，你还得再配一个kcptun。

**Comment by channingbox** [comment]
加速多个端口只需要配置服务器端吧？有几个常见的应用场景，浏览网页，下载，访问应用软件商店，在服务器端和客户端都怎么配置端口，详细说说呗。

**Comment by liangrena** [comment]
我也是刚玩这个，个人理解为(可能不正确，哈哈)：kcptun是可以独立使用的，但是这个意义不大啊，你只加速他一个端口不配套其他代理软件有啥意义呢，一个简单的例子：(你家在天朝，你有一个美国VPS)你只加速一个端口比如只加速22端口，用kcptun来加速可以把你用ssh连接VPS的速度加快，结果是VPS与你的PC相互上传下载文件的速度加快很多，但是你也就只能干这事了，又不能用来加快你家里PC看油管视频，要是没有其他搭梯子的工具你连google都打不开，因为你家pc只能与你的VPS里面的文件数据有联系，而不能与你vps所在地的其他被墙了的数据有所联系了，这时候你配套一个S.S的server你家里配套一个客户端就可以通过s.s代理访问你vps所在地的其他被墙了的数据了，其实用其他代理软件也是可以的，只是S.S名气打啊，小强一样坚强啊

**Comment by testcaoy7** [comment]
KCPTUN is a tunnel. You can use it towork with any type of TCP connection.
