### ISSUE TITLE
kcptun 和 Google BBR 加速 矛盾吗，可以同时使用吗

### ISSUE THREAD

**Issue by channingbox** [xtaci/kcptun#494]
如题

**Comment by wangyu-** [comment]
不矛盾。但是没有叠加效果。你不用kcp中转的tcp流量是会被BBR加速的。用kcp中转的还是会被kcp加速，但是BBR基本没有任何作用（因为你用kcp中转后的tcp连接是本地的）。

**Comment by daiaji** [comment]
@wangyu- BBR只作为服务端有用吗？
对客户端作业时没卵用？

**Comment by wangyu-** [comment]
BBR装在哪边，哪边的数据发送就被加强了，对数据接收貌似是没有用。

**Comment by h2y** [comment]
有轻微的叠加效果，但是 1+1<2

**Comment by xieranmaya** [comment]
我理解kcptun是用的udp
而bbr是调整了tcp的发包策略，是在给tcp加速，哪来的叠加效果？

**Comment by progamer71** [comment]
I don't know kcptun use which congestion control (cubic?) between client and server.
It is more exciting to see if kcptun use BBR (or selectable congestion control in the parameter).

Sorry I don't understand chinese.

**Comment by ZevAlain** [comment]
@progamer71 
look that : ![id](https://github.com/xtaci/kcptun/blob/master/kcptun.png?raw=true)

what is ![KCP](https://github.com/skywind3000/kcp/blob/master/README.en.md) .

**Comment by kxmp** [comment]
你在bbr后面加个tcp就明白了.
bbr tcp
