### ISSUE TITLE
开启kcptun后，ssh无法远程登录搬瓦工的vps。

### ISSUE THREAD

**Issue by LyonUp** [xtaci/kcptun#495]
我使用的搬瓦工vps 系统Centos 7 x86_64 bbr kvm架构，客户端是windows系统。

在使用kcptun后，youtube可以秒看1080。但是存在一个问题：使用ssh username@ip -p port，连接不到我远程的vps了，显示connection timed out（这个时候ssr、kcptun_gclient都是开着的，代理模式是PAC）。
 
直接ping IP 可以ping通，在搬瓦工自带的控制面板也可以连上，只是自己在cmder、xShell这类工具中ssh连接不上。是需要我在cmder、xShell配置什么吗？

**Comment by RoyalCavalry** [comment]
你应该是需要重启下vps

**Comment by liyialiyia** [comment]
我的也出现了这种情况，不知道楼主解决没有？

**Comment by LyonUp** [comment]
我重启下VPS就好了

**Comment by KennyQiao** [comment]
重启 VPS 有效+1

**Comment by ghoshorn** [comment]
我也出现了这种情况，重启了几次vps也还是一样

**Comment by dswybs** [comment]
有同样问题+1，重启才能解决+1，不知道有没有完美解决方案

**Comment by zekunyan** [comment]
刚重启vps还是可以的，等一段时间就不行了
