### ISSUE TITLE
kcptun是不是能被检测出来了

### ISSUE THREAD

**Issue by 1102163785** [xtaci/kcptun#497]
刚买的服务器，kcp挂上一会就不通了。已经俩了，不敢再用了。听说obfs4还是不能被检测呢。

**Comment by chilejiang1024** [comment]
用了这么久(半年多) 也没问题.

**Comment by Globl** [comment]
用了三小时。。没问题。。你说的一会是多久？

**Comment by 1102163785** [comment]
半个小时吧。。。
可能是我电脑有问题，和kcp没什么关系，流量一大就不通了，手机还能通。真奇怪

**Comment by Amankwah** [comment]
这看起来咋像是被QoS了？？

**Comment by daiaji** [comment]
有传言是SS能被识别了……
KCp就是能被识别也不奇怪吧
毕竟目的是用来加速网络又不是用来混淆流量的

**Comment by ohsorry** [comment]
你用的哪种加密？他的aes用的块加密，看 #503

**Comment by xtaci** [comment]
no discussions on sensitive topics
