### ISSUE TITLE
memory leak in server code

### ISSUE THREAD

**Issue by PtDragon** [xtaci/kcptun#498]
After running server for days i found memory leak on it.
Most likely it appears when multiple requests occur at same time. 
More requests = more memory occupied but never freed.
Hehe is my server config(not substituting key here as it does not matter)
./server_linux_amd64 -l :3777 -t 127.0.0.1:3128 --key "$kkey" --crypt aes-256 --mode fast3 --sndwnd 16384 --rcvwnd 16384 --nocomp
After some thousands requests(i use it to secure and optimize traffic from squid) over few days it got to over 1500MB or RAM.
P.S. I noticed that more connections happen more memory leaks. Will do more testing and see exactly.

**Comment by PtDragon** [comment]
Update: It is not connection spawning code, it is somewhere else.
At local tests(inside gigabit VM(no latency and no loss)) no problem appeared.

**Comment by PtDragon** [comment]
Update2:
Looks like i found it - after KCP UDP connections closes memory does not get freed.
Configs for the test:
./server_linux_amd64 -l :81 -t 127.0.0.1:80 --key "MyTestKey" --crypt aes-256 --mode fast3 --sndwnd 8192 --rcvwnd 8192 --nocomp
./client_linux_amd64 -l :90 -r 192.168.4.177:81 --key "MyTestKey" --crypt aes-256 --mode fast3 --conn 64  --sndwnd 8192 --rcvwnd 8192 --nocomp --autoexpire 1
(Yeah, i did explicitely set connections to expire as fast as possible for testing only, i know it impacts speed badly but it was to find bug).
At port 80 i have default nginx(to have something that will not be bottleneck buring testing).
ab -n 100000 -c 512 http://127.0.0.1:90/
During test it quickly reached over 1Gbyte of RAM.
ps aux output(i did cut out sensitive parts not related to problem): https://filebin.ca/3Y0K8uEhdZnb/ps.txt

**Comment by cs8425** [comment]
@PtDragon You should look at `RSS` not `VSZ`.
[Why does my Go process use so much virtual memory?](https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory)
[Understanding Go Lang Memory Usage](https://deferpanic.com/blog/understanding-golang-memory-usage/)

**Comment by PtDragon** [comment]
VIRT after few tests 1147M, RES 950M.

**Comment by PtDragon** [comment]
PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
10087 root       20   0 1147M  950M  5768 S  1.3 24.0 45:04.48 ./server_linux_amd64 -l :81 -t 127.0.0.1:80 --key MyTestKey --crypt aes-256 --mode fast3 --sndwnd 8192 --rcvwnd 8192 --nocomp

**Comment by ohsorry** [comment]
@xtaci

**Comment by sheepbao** [comment]
you can use golang pprof to ensure where memory leak.

**Comment by sheepbao** [comment]
I think it is about bytes.Buffer

**Comment by s1socks** [comment]
实际使用了几天，个人加速，一单网络状况不好了，查看客户端和服务端内存都增加了几兆，并且网络卡住，手动重启两端后网络就恢复了。服务端内存从运行开始好像就没减少过，一直在增加。 @xtaci

**Comment by templexxx** [comment]
@s1socks 用的 kcptun 是哪个版本

**Comment by s1socks** [comment]
最新版的
#./server_linux_amd64 -v
kcptun version 20170525
服务器debian8

X:\Programs\kcptun20170525>client_windows_386.exe -v
kcptun version 20170525

**Comment by templexxx** [comment]
@s1socks 最新版是 0904 吧。 不过我最近要对 ec 部分做一些改动，你可以不着急升级。

从你的情况看，我目测是 0525 中使用的 rs 库的逆矩阵缓存导致的

不过在 datashards + parityshards 比较小的情况下，逆矩阵缓存应该也大不了多少。你说增加几兆，差不多就是这个水平

**Comment by s1socks** [comment]
向前纠错没开
{
  "mode": "normal",
  "mtu": 1350,
  "sndwnd": 128,
  "rcvwnd": 128,
  "datashard": 0,
  "parityshard": 0,
  "dscp": 0,
  "nocomp": false
}

**Comment by s1socks** [comment]
额，刚才运行了下server_linux_amd64 -v 内存从2.1变成1.8了。最卡的时候到3.几。一般启动了都是2.0。服务器512M内存。

**Comment by templexxx** [comment]
@s1socks 那我猜错了，还有情代码的作者
