### ISSUE TITLE
当Server端退出后，丢包重发对网络链路的影响

### ISSUE THREAD

**Issue by zwb-ict** [xtaci/kcptun#5]
我在一次测试时，kcptun的server端忘记打开了，发现kcptun client端出口流量从正常的20Mbps增加到
400~500Mbps甚至会达到1Gbps，我的理解是client端丢包重发引起的。

@xtaci 想请教几个问题
1. udp 是无连接的，即使server端挂了，还会一直向server发送，那么引入丢包重传后，是否会对链路产生严重影响；
2. 这种情况下udp的包最终会发到何处？会截止在server前一跳的路由吗（路由有这种探测机制吗）？还是会到server的网卡中？到达server网卡中，对server机器的UDP接收缓冲区的影响是什么？ 如果占用接收缓冲区，那么我开一个新的端口，接收缓冲区中的数据会一直占用在缓冲区中吗？什么时候会被丢掉？

**Comment by xtaci** [comment]
>  @xtaci 想请教几个问题
> 1. udp 是无连接的，即使server端挂了，还会一直向server发送，那么引入丢包重传后，是否会对链路产生严重影响
这个带宽看上去只有局域网才能达到1Gbps，公网的上行不到1Mbps，FAST 模式下，server挂掉的情况下，确实会占用大量带宽做重发，这个带宽占用量，取决于发送窗口大小，可以尝试调整WndSize的第一个参数观察带宽占用。

> 2. 这种情况下udp的包最终会发到何处？会截止在server前一跳的路由吗（路由有这种探测机制吗）？还是会到server的网卡中？到达server网卡中，对server机器的UDP接收缓冲区的影响是什么？ 如果占用接收缓冲区，那么我开一个新的端口，接收缓冲区中的数据会一直占用在缓冲区中吗？什么时候会被丢掉？

server只要服务器能ping通，一定会投递到到目标服务器。内核接收到后，没有对应的程序监听端口，就会直接丢弃数据包。

**Comment by zwb-ict** [comment]
@xtaci 好的，明白了。谢谢！
