### ISSUE TITLE
2016/06/27

### ISSUE THREAD

**Issue by JogFeelingVI** [xtaci/kcptun#50]
2016/06/27 02:57:02 remote address: *************:28429
2016/06/27 02:57:02 [ERR] yamux: Failed to read header: snappy: corrupt input
2016/06/27 02:57:02 snappy: corrupt input
这个是上面原因造成的~

**Comment by xtaci** [comment]
@JogFeelingVI Client/Server需要同时更新都最新版

**Comment by JogFeelingVI** [comment]
@xtaci 哇直接在线啊 可是AR7XXX版本的还没有更新，怎么办！

**Comment by xtaci** [comment]
路由器编译我不懂

**Comment by JogFeelingVI** [comment]
@xtaci 你能不能直接提供 便宜好的AR7XXX系列的文件

**Comment by JogFeelingVI** [comment]
哦。我也不懂哎，早上下载好了文件准备编译的，一看有人编译了。就直接那过来用了。
