### ISSUE TITLE
关于群晖中用docker安装最新版的kcptun客户端

### ISSUE THREAD

**Issue by shawnzhou1120** [xtaci/kcptun#500]
我在板瓦工的vps上按照好了服务器端（自动安装了最新版20170525版），本来想用梅林自带的ss客户端来开启kcptun，但是设置半天都发现不能连接，研究后认为问题应该主要是路由器的kcptun客户端版本和服务器不匹配导致的，所以现在想曲线救国，把kcptun客户端安装到群晖里。群晖安装了docker，在docker也找

到xtaci/kcptun中的最新版本（不知道是客户端还是服务器端），并安装到容器里，但是请教一下。这个如何配置客户端的参数呢？找了半天也没有教程和方法，请各位大大指教。如何在群晖的docker中来安装和配置kcptun客户端，越详细越好。我是小白。

**Comment by NangenX** [comment]
kcptun 服务端和客户端这块，群晖docker肯定是用的客户端，至于用什么架构的客户端（client），根据你群晖CPU不一样来判断，设置成跟你服务端一样的参数就行，**建议**你可以先用Windows版本的先熟悉下，再上docker这样会容易。以上来就docker，估计有点作死的感觉。

**Comment by shawnzhou1120** [comment]
我大概知道win下的客户端该怎么配置。群晖docker中已经安装了对应版本的kcptun客户端。名字为xtaci/kcptun（x86版本），现在的问题是，不知道在哪里输入对应的服务器配置？是在终端机里像win下一样输入命令么？

**Comment by xtaci** [comment]
docker run -d --restart=always --name kcptun -p 12948:12948 xtaci/kcptun **client  -r "IP:554" -key "xxxxxx" -mode fast2 -nocomp -crypt aes-128 -autoexpire 300 -dscp 46**
