### ISSUE TITLE
从20170901下午开始一直broken pipe

### ISSUE THREAD

**Issue by StLym** [xtaci/kcptun#501]
2017/09/01 04:36:38 remote address: 171.216.193.105:36358
2017/09/01 04:36:41 remote address: 125.71.229.21:5524
2017/09/01 04:36:43 remote address: 171.216.193.105:36382
2017/09/01 04:36:43 broken pipe
2017/09/01 04:36:43 remote address: 171.216.193.105:36382
2017/09/01 04:36:43 broken pipe
2017/09/01 04:36:43 remote address: 171.216.193.105:36382
2017/09/01 04:36:48 broken pipe
2017/09/01 04:36:49 remote address: 171.216.193.105:36382
2017/09/01 04:36:59 remote address: 171.216.193.105:36405
2017/09/01 04:36:59 broken pipe
2017/09/01 04:37:00 remote address: 171.216.193.105:36405
2017/09/01 04:37:00 broken pipe
2017/09/01 04:37:03 remote address: 171.216.193.105:36405
2017/09/01 04:37:08 broken pipe
2017/09/01 04:37:11 broken pipe
2017/09/01 04:37:19 broken pipe
2017/09/01 04:37:33 broken pipe
2017/09/01 04:41:41 broken pipe
2017/09/01 04:50:43 remote address: 125.71.229.21:8510
2017/09/01 04:53:16 remote address: 125.71.229.21:8921
2017/09/01 04:53:43 broken pipe
2017/09/01 04:58:16 broken pipe

今天突然发现ss开启kcp就连接不上了，用xshell5进去看了一下，一直都在报broken pipe。
然后想着会不会是版本太久了，就把本地和服务器的kcp都从20170329更新到20170525了，
更新完之后依旧broken pipe，小白希望大神们能给指点一下问题在哪儿。

**Comment by linhua55** [comment]
https://github.com/wangyu-/udp2raw-tunnel

**Comment by PHCSJC** [comment]
你的线路被Qos了，楼上是个好方法，我目前正在用，你可以尝试下。

**Comment by jaoyina** [comment]
Qos是什么意思？ 楼上那个怎么用呢？

**Comment by xtaci** [comment]
-autoexpire 900

**Comment by zhi259** [comment]
> -autoexpire 900

300 更有效
