### ISSUE TITLE
请教一下，我这个情况，使用kcptun有效果吗

### ISSUE THREAD

**Issue by leedstyh** [xtaci/kcptun#502]
我的工作软件需要连接美国的若干个IP和端口，但是网络很不稳定，丢包/延迟高，我需要改善一下，这种情况用kcptun有效果吗，我不是太了解，请教一下。

另外我看使用方法，一次只能链接一个IP和端口，如果我想连接多个IP和端口，该怎么做？

**Comment by alienwaredream** [comment]
你可以弄一个美国VPS作为中转代理节点呀
