### ISSUE TITLE
新版本出现问题。

### ISSUE THREAD

**Issue by yjd** [xtaci/kcptun#506]
原来用旧版一切正常。今天升级服务端。客户端下了新版， 如果手动cmd加参数运行正常。但是用CreateProcess启动会这样：看 样子像是监听到了ipv6
![2017-09-12_185913](https://user-images.githubusercontent.com/6856740/30323306-3b26024a-97ef-11e7-9a87-9ae0ac7be80b.png)

上2个旧版本则是正常。

![2017-09-12_190328](https://user-images.githubusercontent.com/6856740/30323295-31c418e0-97ef-11e7-9869-35bd4c0e98eb.png)
![2017-09-12_190613](https://user-images.githubusercontent.com/6856740/30323301-36c5be66-97ef-11e7-8a26-b8e27fe6f857.png)

**Comment by xtaci** [comment]
check your startup parameters
