### ISSUE TITLE
只用 kcptun 多端口转发配置教程（抛砖等玉）

### ISSUE THREAD

**Issue by channingbox** [xtaci/kcptun#507]
无

**Comment by PtDragon** [comment]
@channingbox 
There is no multiport currently.
If you need to forward several ports - just use porocess for each port.

**Comment by eromoe** [comment]
porocess ???  Multiple kcptun instance ?

**Comment by PtDragon** [comment]
Yeah. Its how i do for game ports i need  - one for 10000 one for 30000 and so on.
I did check options and ther is no option to put several ports.
If you arent running tons of small short cinnections you wint face too much memory leak.

**Comment by xtaci** [comment]
just tunnel a socks server
