### ISSUE TITLE
ubuntu 16.04的服务器端 snappy: corrupt input 错误

### ISSUE THREAD

**Issue by sosmygirl** [xtaci/kcptun#51]
2016/06/27 15:28:24 version: 20160627
2016/06/27 15:28:24 listening on  [::]:29900
2016/06/27 15:28:24 encryption: aes
2016/06/27 15:28:24 nodelay parameters: 1 20 2 1
2016/06/27 15:28:24 sndwnd: 2048 rcvwnd: 2048
2016/06/27 15:28:24 compression: true
2016/06/27 15:28:24 mtu: 1400
2016/06/27 15:28:24 datashard: 10 parityshard: 3
2016/06/27 15:28:24 acknodelay: false
2016/06/27 15:28:24 dscp: 0
2016/06/27 15:28:58 remote address: 2xx.x.2x.41:37849
2016/06/27 15:28:58 [ERR] yamux: Failed to read header: snappy: corrupt input
2016/06/27 15:28:58 snappy: corrupt input
2016/06/27 15:28:58 remote address: 2xx.x.2x.41:37849
2016/06/27 15:28:58 [ERR] yamux: Failed to read header: snappy: corrupt input
2016/06/27 15:28:58 snappy: corrupt input
2016/06/27 15:28:58 remote address: 2xx.x.2x.41:37849
2016/06/27 15:28:58 [ERR] yamux: Failed to read header: snappy: corrupt input
2016/06/27 15:28:58 snappy: corrupt input
2016/06/27 15:28:58 remote address: 2xx.x.2x.41:37849
2016/06/27 15:28:58 [ERR] yamux: Failed to read header: snappy: corrupt input
2016/06/27 15:28:58 snappy: corrupt input
 
 vps 为 ubuntu 16.04的系统，之前用cetos6.4 就没有问题

**Comment by JogFeelingVI** [comment]
@sosmygirl 什么牌子的VPS？

**Comment by xtaci** [comment]
client/server的版本必须一致

**Comment by sosmygirl** [comment]
忘了更新客户端
