### ISSUE TITLE
游戏的UDP流量可否经过KCPTUN？

### ISSUE THREAD

**Issue by QiXianPu** [xtaci/kcptun#513]
只想确认一下，可以还是不可以呢？(๑• . •๑)

**Comment by PtDragon** [comment]
No changes last month so it sill cannot.
I use dog-tunnel lite for UDP(until kcptun will have this functionality).

**Comment by QiXianPu** [comment]
谢谢

**Comment by odkrys** [comment]
I don't playing the game so I can't test this.

Proxifier + ss-local + kcptun on router or pc will work with gaming packet.
