### ISSUE TITLE
这两天是不是封udp了？

### ISSUE THREAD

**Issue by s1socks** [xtaci/kcptun#515]
你们的都还好用吗？

**Comment by s1socks** [comment]
我的搬瓦工服务器都收不到包了

**Comment by tzyqq191** [comment]
我显示的是：re-connecting: createConn(): net.DialUDP: dial udp X.X.X.X:38989: socket: A system call has failed

**Comment by daiaji** [comment]
这就是斯巴达！
。。。。。。。。。。。。。。。。。。
梦回前朝了

**Comment by zxhaxdr** [comment]
我的还能用，成都移动，但干扰严重，估计和@KwokMiles有关吧

**Comment by xtaci** [comment]
no discussion on this
