### ISSUE TITLE
亲测无效

### ISSUE THREAD

**Issue by wushuyu** [xtaci/kcptun#516]
今天新买的搬瓦工，最便宜的 $19.99/年 的那个.
+ 未开启BBR，下载速度为50KB/s
+ 启用BBR后，下载速度为150KB/s。
+ 使用kcptun，速度是100~180KB/s之间波动，大部分时间低于150KB/s

所以大家还是去使用BBR吧，配置非常简单，只需要向sysctl.conf中写一行`net.ipv4.tcp_congestion_control=bbr`。

贴一下我的配置过程：
```
KCPPORT=4000 
TARGETPORT=50261 #server上的shadowsocks
TARGETIP=127.0.0.1
./kcptun_server -t "$TARGETIP:$TARGETPORT" -l ":$KCPPORT" -mode fast2 

KCPPORT=4000 
SERVERIP=104.225.235.23
LOCALTCPPORT=8388
kcptun_client -r "$SERVERIP:$KCPPORT" -l ":$LOCALTCPPORT" -mode fast2 

SSHSOCKSPORT=2222
LOCALTCPPORT=8388
ssh -D $SSHSOCKSPORT -p $LOCALTCPPORT root@localhost -N -vvv #开启一个ssh socks到本地的2222端口
```

**Comment by tzyqq191** [comment]
问题在于这几天KCPTUN 都崩了  你怎么用的KCP加的速

**Comment by Skura23** [comment]
放假回来发现没法用了

**Comment by Skura23** [comment]
收回我的话, 仍可用

**Comment by mixool** [comment]
亲测，不开KCPTUN 速度200，开了上万。

**Comment by wantsjean** [comment]
长城宽带表示这几天开kcptun都没用了，但是电信网可以用

**Comment by linhua55** [comment]
@wushuyu @wantsjean 
可以加个 https://github.com/wangyu-/udp2raw-tunnel 试试

**Comment by s1socks** [comment]
@linhua55 
姿势越来越丑，丑的不能看了 - -！
速度来个神完成 ss+kcp+rawsocket合一。

**Comment by eromoe** [comment]
@wantsjean 
我也是啊，我就觉得奇怪了，怎么突然不行了。
今天用电信，一开始可以，结果突然也不行了。ss 和ssr 直接连到是可以。

**Comment by mixool** [comment]
kcpraw集成了代理功能，可以直接使用。gost也可以。

2017年10月10日 上午4:38，"s1socks" <notifications@github.com>写道：

**Comment by xtaci** [comment]
encryption in kcptun is extremely important,  i don't know why people think encryption is trivial in packet layer.

**Comment by ohsorry** [comment]
@xtaci 因为我们tunnel里走的就是加密的数据。
@mixool 你学的哪个kcpraw?

**Comment by mixool** [comment]
https://github.com/ccsexyz/kcpraw/issues/19

**Comment by ohsorry** [comment]
这姿势看起来不错！

**Comment by eromoe** [comment]
@xtaci  除了保证一致性还能做什么? 目前来说GFW 也不至于针对kcptun 伪造数据包吧，毕竟传输内容他也不知道， 以后发现有影响了再开起来呗。毕竟ss 那里也讨论了一大堆安全问题，到ssr 死了的现在好像 还没什么事，反正真出来了再把这功能启用就好了。

**Comment by xtaci** [comment]
it's nothing related to forging packets, it's about the signature of packets.

**Comment by ohsorry** [comment]
signature of kcp packets? MLGB，nan dao kcp yi jing bei zhu yi le? guai bu de bei qiang le.

**Comment by eromoe** [comment]
@xtaci 
signature   不加密就是那个key 吧，不加密也就是key是明文嘛。然后别人可以方便伪造包， 这不算forging么？
我主要是不理解 这里加密的好处。

目前的情况是
1. 不加密，速度更快
2. ss已经加密，内容不怕检测，要是ss 特征能检测，那就换ssr咯，只是现在好像gfw也没把这功能上线
3. 并没有收到 针对 “kcptun没加密” 的干扰，破坏工作  （当然将来可能有）

PS:  一会一会连不上是因为udp 上行问题， 用nc 试出来了

so, no encryption is fine for this case, I think. If not , please explain detailedly.

**Comment by ohsorry** [comment]
@eromoe 不加密就是包头特征明显的kcp udp包，一下就被墙探测到了。
当初计划自己写的时候还考虑了，结果直接用的kcptun，然后就忘了这事了。

**Comment by eromoe** [comment]
问题是，gfw 现在没做这个事把， 做了的话再加上加密就行了。
我就是这个意思啊。。。

**Comment by Beastea3** [comment]
@mixool gost咋使用？可以把服务器udp转为tcp？然后在用在tcp上用kcp协议？就是个udp2raw的功能？？

**Comment by mixool** [comment]
@Beastea3 gost是集成了kcptun的功能，没有转换。我也不怎么会玩gost,去看项目说明吧.

**Comment by summer-wu** [comment]
我是楼主。收回我的话，是我没有仔细测试就乱发言。

今天发现是运营商把UDP协议禁掉了，我发到server的udp包，server可以收到；server发给我的udp包，都被运营商丢弃了，我根本收不到！

我在两台外国机器之间测试，是可以正常使用的。
看来国内环境使用必须结合udp2raw-tunnel
