### ISSUE TITLE
【mac】20170904客户端被请求连接

### ISSUE THREAD

**Issue by eleganceZf** [xtaci/kcptun#517]
今天刚开机就收到了系统报警说kcptun的客户端被主动请求连接，请问这个是什么回事？

**Comment by eleganceZf** [comment]
![_20171010152722](https://user-images.githubusercontent.com/12109523/31374199-8c269d62-adcf-11e7-9f50-7c565668e23d.jpg)

**Comment by xtaci** [comment]
client的作用不就是接受传入的网络链接，并转发到server端么

**Comment by eleganceZf** [comment]
您的意思是本机把请求发给client端口这个过程的接入么，我理解为外部的网络主动请求接入而非本机之间的端口通讯，可能我理解错了吧？

**Comment by xtaci** [comment]
listen到127.0.0.1应该就不会提示了

**Comment by eleganceZf** [comment]
额，我就是转发到127.0.0.1的。：(

**Comment by xtaci** [comment]
那就是都会提示吧。

**Comment by eleganceZf** [comment]
欸，好的，谢谢，打扰了
