### ISSUE TITLE
问个和动态fec有点关系的问题吧

### ISSUE THREAD

**Issue by daiaji** [xtaci/kcptun#518]
@DarienRaymond 在在[V2Ray中支持利用UDP特性传输UDP数据包的功能](https://github.com/v2ray/v2ray-core/issues/578#issuecomment-334828158)指出

> c版的kcp有类似的选项（效果不明），但是go版的kcp加入fec之后使得这个选项变得无效了。

所以说这个功能是被fec替代了还是单纯没写或者BUG了

动态fec能取代楼主说的那个吗？动态fec还有希望吗？

@xtaci 

>  add encryption support for sm4 

邪恶的双KPI国密有什么支持的必要吗？

还是说只是SMS4加密算法？

**Comment by xtaci** [comment]
1. SM4 is just an option.
2. I don't know which option you mean in KCP, have no impression on that.

**Comment by daiaji** [comment]
@xtaci @DarienRaymond先森嗦有的……
我哪知道
我一开始就是用的kcptun啊
