### ISSUE TITLE
使用后chrome看油管崩溃

### ISSUE THREAD

**Issue by NIGHT-CORE** [xtaci/kcptun#52]
具体表现是，chrome看油管有一定几率（网页崩溃），使用kcptun后才有的，频率大概是一小时1~2次

关于平台：
openwrt x86
kcp-linux 386

关于配置：
推荐配置出现问题
模式更改为normal也出现。

小问题，小忧伤
@-@

**Comment by xtaci** [comment]
嗯，这个是浏览的bug，正常的，重启，多留点内存就没问题。

**Comment by NIGHT-CORE** [comment]
谢谢，你真的是太友好了。
顺便说一下，fast【2/3】只能跑到5MB.normal可以跑满100M

**Comment by xtaci** [comment]
@NIGHT-CORE 是的，这取决于线路质量，自己实践出最佳配置
