### ISSUE TITLE
同样的配置，家里的电脑使用一直正常，公司电脑经常断掉

### ISSUE THREAD

**Issue by Morphin3** [xtaci/kcptun#521]
现象是刚连上kcptun的配置是可以联网的，过一会就会断掉不能用（有的时候一开始也不行）
同样的配置，
家里的 MAC 是 15寸低配，14年9月份之后的款，16G 内存
公司的 MAC 是 13寸不知道什么配置，应该是15年或者之后的款，8G内存
求大神解释，是我的配置不对吗
---
实例 kcptun 的配置信息如下:
服务器IP:  XXXX
端口:  29900
加速地址:  127.0.0.1:8388
key:  XXXXXX
crypt:  salsa20
mode:  manual
mtu:  1400
sndwnd:  128
rcvwnd:  1024
datashard:  30
parityshard:  15
dscp:  46
nocomp:  true
nodelay:  0
interval:  20
resend:  2
nc:  1
acknodelay:  false
sockbuf:  4194304
keepalive:  10

当前安装的 Kcptun 版本为: 20170525

可使用的客户端配置文件为:
{
  "localaddr": ":8388",
  "remoteaddr": "XXXX:29900",
  "key": "XXXXXX",
  "crypt": "salsa20",
  "mode": "manual",
  "mtu": 1400,
  "sndwnd": 1024,
  "rcvwnd": 128,
  "datashard": 30,
  "parityshard": 15,
  "dscp": 46,
  "nocomp": true,
  "nodelay": 0,
  "interval": 20,
  "resend": 2,
  "nc": 1,
  "acknodelay": false,
  "sockbuf": 4194304,
  "keepalive": 10
}

**Comment by xtaci** [comment]
depends on the ISP

**Comment by Morphin3** [comment]
@xtaci 
问了下网管说没有针对UDP的限制，公司是电信，家里是移动

**Comment by jemyzhang** [comment]
最近发现家里用kcptun就是不行，换端口也不行，但是4G可以，不知道是不是现在家里被关照过了？

**Comment by wangyu-** [comment]
>问了下网管说没有针对UDP的限制，公司是电信，家里是移动

有可能公司的网管没做限制，但是上级的ISP有限制。

**Comment by Morphin3** [comment]
@wangyu- 大侠，意思是电信会有限制吗？
这个问题是有解吗？
比如改成合适的配置什么的？

**Comment by Morphin3** [comment]
@xtaci 大神，这个问题有什么方法可以规避吗

**Comment by wangyu-** [comment]
>mtu: 1400

这个MTU貌似有点大，可能会造成不稳定，建议你调到1200试试。

>意思是电信会有限制吗？

电信的我不确定。不过我们这边的移动线路确实是对udp做了限制的。

>这个问题是有解吗？

这个工具可以帮助kcptun绕过udp限制：

https://github.com/wangyu-/udp2raw-tunnel

**Comment by Morphin3** [comment]
@wangyu- 多谢大侠的解答，试了 1200 ，问题继续存在
我家里的移动倒是正常
公司电信不正常不知道原因了，可能是公司别的限制导致了这个问题
还有你介绍的帮助绕过 udp 限制的，我等确认是 udp 限制导致后有空试验一下
多谢！

**Comment by jemyzhang** [comment]
@wangyu- udp2raw有效，非常感谢！

**Comment by JBlazingSun** [comment]
电信会有限制, 会断流
