### ISSUE TITLE
这几天不能用了，还会恢复吗？

### ISSUE THREAD

**Issue by jaoyina** [xtaci/kcptun#522]
好像是从前天开始的，发现连不上了，去掉直接连ssr服务器是可以的，已经更新到最新版，谁知道是什么原因？

**Comment by cmdlet1** [comment]
我用的正常

**Comment by fifman** [comment]
我也有同样的问题，直连ss没问题，加了kcptun就不稳

**Comment by matood** [comment]
听说UDP流量会被封杀，参考 https://www.v2ex.com/t/382261

**Comment by zxbiao** [comment]
这些天据闻墙发展出端口白名单制度了，反正我的kcptun已经死了。。。

**Comment by wantsjean** [comment]
kcpraw好使

**Comment by fcying** [comment]
我也有这个问题. 直接ss可以, 用kcptun 能用一会, 然后就连不上了.

**Comment by fcying** [comment]
@wantsjean  kcpraw是什么?

**Comment by wwxs972** [comment]
**_``_**

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
