### ISSUE TITLE
Provide an option to hide `conn open` and `conn close` messages

### ISSUE THREAD

**Issue by t123yh** [xtaci/kcptun#523]
I'm using this on OpenWrt. Although it runs greatly, there're still times that it doesn't work. I want to consult the log for details, but the logs are flooded with `conn open` and `conn close` messages. I wonder if you can add an option to hide these messages, or put them to `stdout` instead of `stderr`?

**Comment by wangyu-** [comment]
You can use `2>&1` to redirect stderr to stdout, then use `|grep -v "conn open"|grep -v "conn close"`to filter those message out.

**Comment by xtaci** [comment]
option added
