### ISSUE TITLE
kcptun和net-speeder一起用

### ISSUE THREAD

**Issue by octww** [xtaci/kcptun#526]
竟然有双倍加速效果，而且流量也是双倍。

我有一台ovz主机，一直在用kcptun加速，但因为kcptun要安装客户端，所以无法给我的iOS设备加速。
最近我在主机上又装了net-speeder，速度当然不如kcptun，但用来给iOS设备加速还是不错用。
本来我打算在笔记本上用kcptun，手机上用net-speeder，但我发现开了net-speeder后，用kcptun的流量会暴增：

比如用笔记本下载一个100M的文件，50M宽带：
用kcptun，杀掉net-speeder，用时约1分40秒，下行流量约150M；
用kcptun，同时运行net-speeder，用时约1分20秒，下行流量约300M；
用net-speeder，用时约1分40秒，下行流量约200M。

请教大家为什么net-speeder和kcptun同时运行时，使用kcptun流量会加倍呢？
有办法让net-speeder和kcptun同时运行又互不影响吗？

**Comment by wwqgtxx** [comment]
不要开启net-speeder的udp加速，只开启他的Tcp加速即可

**Comment by octww** [comment]
@wwqgtxx 谢谢。考虑到在电脑上使用ns效果不佳，我已经放弃了。
