### ISSUE TITLE
今天不能用了，求教怎么升级最新版本？

### ISSUE THREAD

**Issue by Chadwick97** [xtaci/kcptun#53]
楼主，我用的是23号版。但是我是小白，根据扩软博客里的一篇教程一步步弄好的。今天早上的时候突然用不了了，日志显示这样
2016/06/28 10:56:48 [ERR] yamux: keepalive failed: i/o deadline reached
2016/06/28 10:56:48 [ERR] yamux: Failed to read header: broken pipe
其它的回复里面说要升级最新27号的版本，但是我不会升级，楼主能说说怎么升级，或者给一篇相关教程的链接吗？
谢谢

**Comment by xtaci** [comment]
你可以尝试换一个端口

**Comment by Chadwick97** [comment]
换端口是换服务器的端口还是ss的端口？升级除了替换两个文件，还需要在运行vbs里添加相应的命令吗？

**Comment by xtaci** [comment]
更换 kcp server -l 端口 以及对应的kcp client -r 端口， 其他什么都不变

**Comment by Chadwick97** [comment]
已经解决问题可以使用了，谢谢楼主
