### ISSUE TITLE
关于FEC和MTU

### ISSUE THREAD

**Issue by testcaoy7** [xtaci/kcptun#530]
请问在大MTU情况下，UDP分片，FEC是会针对每一个分片的UDP包进行恢复还是对整个完整的大UDP包进行丢包恢复？
比如，MTU = 9000，分7个标准UDP包发送，FEC是在7个包基础上增添额外信息，还是说就针对MTU=9000的大包，视作一个包（先进行包组装），来增加额外信息？

**Comment by xxxman2008** [comment]
FEC 的 原理，就好像是 硬盘的 Raid 。。通过增加额外的 冗余纠错数据，达到 “不重传，也能恢复数据”的功能。  但是，正如  Raid 盘的数量是可变的一样。。FEC 里面，具体多少个包 作为一个组，是可调的。

以你的例子，到底是 每7个包  加一组冗余数据，还是  每3个包 加一组。。这没法告诉你。

另外，这种问题，最好是不要在 ISSUE 里面讨论，这属于基础知识普及，你自己网上搜索一下，看看资料就可以了。不要占用他人的宝贵时间。

**Comment by testcaoy7** [comment]
@xxxman2008 我知道FEC的工作原理……我问的是巨帧情况下，是先组装数据包还是直接对数据包碎片进行恢复

**Comment by xxxman2008** [comment]
巨帧是一个非常特殊的 情况。需要用户侧硬件支持。而且，对程序员来说，是透明的。所以，如果这个问题真的对你非常重要，你一定知道答案。

如果这个问题对你并不重要，不会成为你工作里面的致命难点，那就不要浪费 开源工作者宝贵的时间。去QQ群天南海北的开脑洞吧。

**Comment by wangyu-** [comment]
>请问在大MTU情况下，UDP分片，FEC是会针对每一个分片的UDP包进行恢复还是对整个完整的大UDP包进行丢包恢复？
比如，MTU = 9000，分7个标准UDP包发送，FEC是在7个包基础上增添额外信息，还是说就针对MTU=9000的大包，视作一个包（先进行包组装），来增加额外信息？

我假设你说的MTU=9000的意思是给kcptun加上`--mtu 9000`参数。假设你的网络接口MTU是标准的1500，减去28个字节的包头，一次只能发1472个数据，所以需要分7个包发送。

但是这9000字节的数据，在应用层看来还是1个UDP包；`分7个包`发送是在IP层面发生的，由内核拆分、内核重组；对kcptun来说不可见。所以是第二种情况，`针对MTU=9000的大包，视作一个包（先进行包组装），来增加额外信息`。

(仅看过少量代码，凭经验猜测)

**Comment by ccsexyz** [comment]
https://github.com/xtaci/kcp-go/blob/master/sess.go#L780
https://github.com/xtaci/kcp-go/blob/master/sess.go#L36

**Comment by wangyu-** [comment]
```
mtuLimit = 1500
...
// SetMtu sets the maximum transmission unit(not including UDP header)
func (s *UDPSession) SetMtu(mtu int) bool {
	if mtu > mtuLimit {
		return false
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	s.kcp.SetMtu(mtu - s.headerSize)
	return true
}
```

**Comment by testcaoy7** [comment]
@wangyu- "2个分片是作为1个包来做FEC的"，明白了，谢谢
