### ISSUE TITLE
kcptun在极路由1s上卡顿，不能使用

### ISSUE THREAD

**Issue by DaPangR** [xtaci/kcptun#531]
在极路由1s上使用命令./client_linux_mipsle -v之后，程序卡住不能输出任何信息，CPU占用率达到90%左右。
![1](https://user-images.githubusercontent.com/7512488/32283163-917a739c-bf5e-11e7-9475-87a82287cd70.png)

使用top命令
![2](https://user-images.githubusercontent.com/7512488/32283166-928e6914-bf5e-11e7-8c31-a94dbc3a7aea.png)

系统信息
![3](https://user-images.githubusercontent.com/7512488/32283174-978f3e0c-bf5e-11e7-860a-aefe5169d8b9.png)

还没有正式的使用ss+kcp，但是感觉kcp这个状态用不了呀

**Comment by xtaci** [comment]
the boot process is slow because of pbkdf2 key generation. just be patient

**Comment by hxhxd** [comment]
@xtaci  运行小半天了，仍然没有任何反应呀。
路由器是E4200刷的dd-wrt，请问有办法查出确切问题所在吗？ 谢谢：）
