### ISSUE TITLE
关于ASUS AC66U B1 (armv7l)上Merlin固件 kcptun 客户端 illegal instructions 报错

### ISSUE THREAD

**Issue by 0x6d3f9c** [xtaci/kcptun#533]
昨天刷了merlin官方编译的固件，kcptun client无法运行直接报错 illegal instructions.

查了下资料，得知是FPU的问题。这款路由器和大多数家用路由器一样没有fpu硬件浮点运算单元（cat /proc/cpuinfo 没有fpu），需要开启浮点模拟。

特意自己编译固件，内核中开启了FPE_NWFPE后重新编译。

但是还是不行。

但刚才试了一下，client_linux_arm5 可以使用，6,7都不行。

我是漏掉了什么嘛？

**Comment by templexxx** [comment]
@0x6d3f9c 是哪条指令报错了？

**Comment by 0x6d3f9c** [comment]
@templexxx 不带选项，直接输入命令就错了

**Comment by templexxx** [comment]
@0x6d3f9c 嗯嗯。我指的是具体的报错信息，应该会有具体是那条指令非法的

**Comment by 0x6d3f9c** [comment]
client_linux_arm5 可以用，我看效果还真不错，我在一代B树莓派上，用client_linux_arm6，看1080P，CPU一直100%，load平均3～4。AC66U 的CPU双核，load在0.6～0.9波动。

树莓派可是有fpu硬件浮点单元的，竟然还没路由器的CPU给力，呵呵。

**Comment by 0x6d3f9c** [comment]
templexxx 没有任何报错信息。就一句illegal instructions。

路由器日志里没有信息，而且路由器也没有dump吧，请问我在哪里看报错信息呢？

我用下ldd client_client_arm5，结果这样了:

moon@IROUTER:/jffs/bin# ldd client_linux_arm5 
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x2048e5, 0x16)
        /usr/local/go/src/runtime/panic.go:605 +0x70 fp=0xbeaa0b88 sp=0xbeaa0b7c pc=0x3aa78
runtime.sysMap(0xf5a0000, 0x1060000, 0x1ee01, 0x32d798)
        /usr/local/go/src/runtime/mem_linux.go:227 +0x104 fp=0xbeaa0bac sp=0xbeaa0b88 pc=0x246b0
runtime.(*mheap).mapBits(0x320da8, 0x10600000)
        /usr/local/go/src/runtime/mbitmap.go:160 +0x8c fp=0xbeaa0bc4 sp=0xbeaa0bac pc=0x212cc
runtime.(*mheap).setArenaUsed(0x320da8, 0x10600000, 0x0)
        /usr/local/go/src/runtime/mheap.go:525 +0x24 fp=0xbeaa0bd0 sp=0xbeaa0bc4 pc=0x32128
runtime.(*mheap).init(0x320da8, 0x400000, 0x200000)
        /usr/local/go/src/runtime/mheap.go:510 +0x414 fp=0xbeaa0be4 sp=0xbeaa0bd0 pc=0x31dc4
runtime.mallocinit()
        /usr/local/go/src/runtime/malloc.go:392 +0x1f4 fp=0xbeaa0c2c sp=0xbeaa0be4 pc=0x1f008
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:471 +0x30 fp=0xbeaa0c48 sp=0xbeaa0c2c pc=0x3d124
runtime.rt0_go(0xbeaa0c94, 0x1, 0xbeaa0da6, 0x0, 0xbeaa0db8, 0xbeaa0dd8, 0xbeaa0de2, 0xbeaa0e08, 0xbeaa0e10, 0xbeaa0e2d, ...)
        /usr/local/go/src/runtime/asm_arm.s:61 +0x84 fp=0xbeaa0c88 sp=0xbeaa0c48 pc=0x683f4

**Comment by 0x6d3f9c** [comment]
我重新刷了梅林发布的官方固件，还是只有client_client_arm5可以用。即使自己编译内核加入VFP支持，也不行，用arm5吧

**Comment by tenwx** [comment]
我的ac68u也是这样，只能用arm5，如此一来感觉速度上不去，最多只能跑到13Mb/s，并且单核cpu跑满。而在我的笔记本上相同参数和服务器可以跑到50Mb/s，应该就是某些优化指令没有使用导致效率过低， @xtaci 大神麻烦看看是否可以调整编译参数？

**Comment by zj299792458** [comment]
+1 同样问题，原来还能用arm5……求大神编译arm7l
