### ISSUE TITLE
怎么样才能避免被封杀呢?

### ISSUE THREAD

**Issue by JaydenFish** [xtaci/kcptun#536]
我是电信的网络+美国VPS,用于翻墙.
前不久刚办的电信宽带,KCPTUN+SSR,翻墙很好用.服务器监听的是53端口.
用几天就不能用了,被封了.
后来换了个--key,又能用了.
现在又不行了,换key也不行.换--crypt换端口也都不行.
有办法么?

**Comment by flipphos** [comment]
kcptun后面套上udp2raw（vps和本地都需要）试试看能否改善。

**Comment by wantsjean** [comment]
用kcpraw

**Comment by yjd** [comment]
用kcpraw
转tcp

**Comment by fcying** [comment]
@wantsjean  kcpraw 那个项目也停止更新了?

**Comment by ccsexyz** [comment]
当然不是了

**Comment by fcying** [comment]
@ccsexyz  已经用上了 很赞 用了半天 一切正常..

**Comment by iceonsun** [comment]
我也来安利一发 https://github.com/iceonsun/rsock

**Comment by iceonsun** [comment]
我也来安利一发
https://github.com/iceonsun/rsock

**Comment by xtaci** [comment]
-autoexpire 900

**Comment by xiaorong61** [comment]
Hysteria2 自动跳端口
