### ISSUE TITLE
kcptun如何配合PPTP使用

### ISSUE THREAD

**Issue by chengshiding** [xtaci/kcptun#54]
开启kcptun服务端和客户端后，要不要开PPTP的服务端和客户端呢。

**Comment by xtaci** [comment]
kcptun只是端口到端口的转发(TCP)，看你怎么用哈。README很清楚的。pptp貌似不是走的tcp协议

**Comment by shenliuyang** [comment]
加速pptpd的1723端口，  vpn链接不上～！～！。  好像不是走tcp协议

**Comment by kx001001** [comment]
> 

pptp协议tcp/1723只是控制通道，数据流跑在gre协议上。kcptun无能为力
