### ISSUE TITLE
mac可以后台运行吗?

### ISSUE THREAD

**Issue by smartisanyyh** [xtaci/kcptun#540]
这个命令行可以后台吗?

**Comment by windirt** [comment]
可以使用launchhd或者launchagent来启动

cat ~/Library/LaunchAgents/随便你的域.kcptun.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>Label</key>
    <string>随便你的域.kcptun</string>
    <key>ProgramArguments</key>
    <array>
        <string>/Users/你的用户名/client_darwin_amd64</string>
        <string>-c</string>
        <string>/Users/你的用户名/你的设置文件.json</string>
    </array>
    <key>WorkingDirectory</key>
    <string>/Users/你的用户名/</string>
</dict>
</plist>

大概如此

**Comment by smartisanyyh** [comment]
Thanks  It's  work

**Comment by paradiseduo** [comment]
Mac上可以使用这个[客户端](https://github.com/paradiseduo/Kcptun)
