### ISSUE TITLE
snmp log file name issue

### ISSUE THREAD

**Issue by ghost** [xtaci/kcptun#541]
Version 20170930 and 20171113:
When using some number in snmp log filename, actual log file name changes.

example:
```
server_linux_amd64 ... --snmplog <path>/snmp_22  ...
```
The log files will be 
...
snmp1717
snmp1818
snmp1919
snmp2020
snmp2121
snmp2222

It seems the program is using day-of-month replaced '2' in filename .

**Comment by TerranceH** [comment]
Further test
```
server_linux_amd64 ... --snmplog /home/sssshh/kcptun/snmp_0.1.2.3.4.5.6.7.8.9 ...
```
writes log file(s)
```
snmp_0.11.22.5.13.27.6.7.8.3
snmp_0.11.22.5.14.27.6.7.8.3
snmp_0.11.22.5.15.27.6.7.8.3
```

so
 1 -> month
 2 -> day-of-month
 3 -> clock hour
 4 -> clock minute
 5 -> clock second
 9 -> day-of-week

**Comment by TerranceH** [comment]
Ok, just found out it's golang date format, but what if I have numbers in my log path?

**Comment by Pancongwen** [comment]
hi,
I have the same problem with version : 20180316

* Requirement
I have started four pairs of kcp clients and servers, and I would like to analyze the snmp logs of those clients and servers. 
I would like to identify each pair of snmp log. For example, the configuration of kcp client and server is written as follow,
```
# client
{
	"localaddr": "127.0.0.1:2001",
	"remoteaddr": "123.45.67.89:4001",
	"mode": "fast2",
	"snmplog": "/home/kcplog/2001/123.45.67.89-4001/snmp-20180507.log"
}
```
```
# server
{
	"listen": "0.0.0.0:4001",
	"target": "127.0.0.1:8001",
	"mode": "fast2",
	"snmplog": "/home/kcplog/4001/123.45.67.89-8001/snmp-20180507.log"
}
```
In this case, I can identify the logs by their paths when I have multiple clients and servers in use.

----
I have glanced at the source code of `20180316`.
I find the function `snmpLogger` in file `main.go`,on line 479 as follow. 
```
  func snmpLogger(path string, interval int) {
...
			f, err := os.OpenFile(time.Now().Format(path), os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
...
}
``` 
In which it converts the path string to golang date format. 

----
@xtaci 
It would be very nice to just convert the filename in date format, leaving the path flexible. 

----
@TerranceH 
In our case, we've made a detour, encode the ip-port from `0-9`  to `a-j` by plus `48`, then decode that when we need to analyze the log in pair(client-server).

**Comment by xtaci** [comment]
@Pancongwen good suggestion, we can trade differently for filename & path prefix

**Comment by xtaci** [comment]
@Pancongwen https://golang.org/pkg/path/filepath/#Split
will you PR this to me ?

**Comment by Pancongwen** [comment]
@xtaci 
Thanks for the trust! I'll try this week.

**Comment by mateomartin1998** [comment]
@xtaci 
I have made a [PR](https://github.com/xtaci/kcptun/pull/600) about this issue. Thanks in advance for your time to do the code review.
