### ISSUE TITLE
kcp感觉降低游戏延迟效果不佳……

### ISSUE THREAD

**Issue by daiaji** [xtaci/kcptun#542]
` -nocomp -mode manual -nodelay 1 -resend 1 -nc 1 -interval 10`
似乎是没啥效果
ping 150ms左右
延迟还是比较明显
和没开kcp差不多

**Comment by mukaiu** [comment]
kcp的目的是提高质量

**Comment by daiaji** [comment]
那么有办法抗掉线吗？

**Comment by WilllllChen** [comment]
延迟跟掉线是两回事吧。
KCPTUN处理的是TCP包，现在的网游大部分是UDP，应该不会有效果...

**Comment by daiaji** [comment]
@WilllllChen  Terraria这倒霉游戏就是用TCP连接的……

**Comment by ljyloo** [comment]
kcptun+v2ray就可以代理udp流量了
