### ISSUE TITLE
请问小米路由器3应该选哪个Releasas版本

### ISSUE THREAD

**Issue by liuzhaoming5954** [xtaci/kcptun#544]
uname -a显示信息
Linux XiaoQiang 2.6.36 #1 MiWiFi-R3-2.21.190 Tue Oct 17 20:53:26 CST 2017 mips GNU/Linux
于是选择了mips版本，但是运行出现错误：**./client_linux_mips: line 1: syntax error: unexpected "("**
于是又选择尝试mipsle版本，运行出现错误：**Bus error (core dumped)**
处于懵逼状态了，请大家指点一二

**Comment by hdstar2009** [comment]
小米3是mtk的芯片？用mipsle那个。

**Comment by shuishihan** [comment]
试试arm5

**Comment by EXSERENS** [comment]
@shuishihan MT7620是MIPS24KEc，不用乱试
