### ISSUE TITLE
提供一个Windows下面的命令行托盘工具

### ISSUE THREAD

**Issue by rexdf** [xtaci/kcptun#545]
项目主页在这里 https://github.com/rexdf/CommandTrayHost ，二进制在[这里](https://github.com/rexdf/CommandTrayHost/releases)

![example2](https://user-images.githubusercontent.com/4038241/33545013-d1e3c62c-d917-11e7-924a-e88349517c4a.png)

**Comment by hdstar2009** [comment]
提供一个kcptun 客户端的client.json文件例子：
{
"remoteaddr": "44..55.66.77:18000",
"localaddr": ":4000",
"key": "VwAABhG",
"crypt": "aes-128",
"mode": "fast",
"conn": 1,
"mtu": 1350,
"sndwnd": 512,
"rcvwnd": 1024,
"quiet":true,
"nocomp": true
}

**Comment by xtaci** [comment]
是否有mac下的托盘

**Comment by rexdf** [comment]
哇op主！

我是参考的 [phuslu/taskbar](/phuslu/taskbar)，里面倒是有一个OSX的command。

https://github.com/phuslu/taskbar/blob/master/macos/goproxy-macos.command

**Comment by ccsexyz** [comment]
Mac 下没必要搞托盘程序吧，用 launchd 或者 supervisor 就好了

**Comment by xtaci** [comment]
需要一个类似的，可以切换配置的，不只是daemon

**Comment by tangkv** [comment]
从 https://www.v2ex.com/t/410279 跟过来的 👍

**Comment by yjd** [comment]
![default](https://user-images.githubusercontent.com/6856740/33863861-d3b6ff88-df24-11e7-8bcb-462b5144f7db.png)

**Comment by hdstar2009** [comment]
@yjd 楼上那个是什么？

**Comment by yfhmmx** [comment]
@yjd 同求，你这个是什么工具？这么溜

**Comment by wxlg1117** [comment]
@yjd 大佬，你这图片上的这个SSR客户端求分享啊!
![image](https://user-images.githubusercontent.com/9752596/49530473-40a38600-f8f3-11e8-81f7-fa7cb9000711.png)
