### ISSUE TITLE
波兰VPS10gb口,电信200m(10M上传),高峰期平均450ping,丢包不超过5%,应该怎么配置, 求各位大佬指导！

### ISSUE THREAD

**Issue by hx801217** [xtaci/kcptun#547]
目前是这样配置，请各位大佬指导下！
路由器也不能配置 manual模式，我现在是这样配置的

服务端：
crypt:  none 
mode:  fast2 
mtu:  1400 
sndwnd:  4096 
rcvwnd:  4096 
datashard:  0 
parityshard:  0 
dscp:  0 
nocomp:  true 
quiet:  false 

客户端：
crypt:  none 
mode:  fast2 
mtu:  1400 
sndwnd:  640
rcvwnd:  4096 
datashard:  0 
parityshard:  0 
dscp:  0 
nocomp:  true 
quiet:  false

**Comment by hx801217** [comment]
忘记说了，VPS不限流量，求大神指导高速配置

**Comment by PtDragon** [comment]
Try 
datashard: 14
parityshard: 2
on both sides. 
Also use interval a bit above your latency to resend only when needed.
