### ISSUE TITLE
(问题更正，是ssr的问题，ss是ok的)神了奇了，kcptun+ssr，树莓派+router怎么也不行，单独router就可以

### ISSUE THREAD

**Issue by vongoethe** [xtaci/kcptun#549]
Update:
更正一下，SS是没问题的，是SSR有问题

本人BWH的VPS，配置了ssr+kcptun的server端
然后在本地router上kcptun+ssr，用的highhigh的，但是发现kcptun会造成router负载过大，于是想把kcptun单独装到树莓派3上，router是netgear的R8000，刷的openwrt CC 15.15.1
然后，我把kcptun client装到树莓派后，启动没问题，在router上把原来的127.0.0.1地址改成树莓派的地址192.168.1.10，然后。。。怎么也不行啊，树莓派的log是不停的open close，但是无法上网
同样的配置，都用router就可以，把kcptun分出来到树莓派就不行
百思不得其解
求高人指点
谢谢了！！！

**Comment by vongoethe** [comment]
![untitled](https://user-images.githubusercontent.com/3502184/34119097-e779efbc-e45b-11e7-86b0-68eeea771529.jpeg)

这是kcptun client在树莓派上的log

**Comment by vongoethe** [comment]
![untitled](https://user-images.githubusercontent.com/3502184/34119283-8a43218c-e45c-11e7-8b72-a58d46cd3829.jpeg)
![untitled2](https://user-images.githubusercontent.com/3502184/34119325-aeaebfd6-e45c-11e7-8d28-61225aaa547a.jpeg)

树莓派就一直这样的反应 但是浏览器端无法访问网站 国内的可以 用到转发到这里的就不行

**Comment by NangenX** [comment]
我是X64 LEDE 1.9 update 11版本SSR配合树莓派2B KCPTUN做分享，你树莓派192.168.1.10做KCPTUN搬运的话，那么你R8000的SS服务器地址指向就应该是192.168.1.10，然后其他设置默认你BWH的SS配置。能够open和closed应该是你SS的具体设置没有对。KPCTUN通讯是没有问题了。

**Comment by vongoethe** [comment]
R8000的openwrt的指向确实已经改成192.168.1.10了，而且配置肯定是没有问题的，因为不连kcptun之前是能直接用的，我只是改了ip地址。
不过现在倒是可以确认kcptun没问题，因为我用另一台windows的机器可以连接kcptun正常使用，貌似问题确实出在openwrt了，难道是openwrt防火墙的问题么，我试试看
