### ISSUE TITLE
路由器上跑出现的问题

### ISSUE THREAD

**Issue by ligf** [xtaci/kcptun#55]
用的是6300v2  arm5 版本
配置 -mtu 1400 -sndwnd 128 -rcvwnd 2048 -mode fast2
错误内容
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x21112f, 0x16)
        /usr/local/go/src/runtime/panic.go:566 +0x78
runtime.sysMap(0x11b00000, 0x100000, 0x1, 0x2f0c90)
        /usr/local/go/src/runtime/mem_linux.go:224 +0x15c
runtime.(*mheap).sysAlloc(0x2e3928, 0x100000, 0x0)
        /usr/local/go/src/runtime/malloc.go:407 +0x144
runtime.(*mheap).grow(0x2e3928, 0x8, 0x0)
        /usr/local/go/src/runtime/mheap.go:721 +0x68
runtime.(*mheap).allocSpanLocked(0x2e3928, 0x7, 0x71898)
        /usr/local/go/src/runtime/mheap.go:625 +0x634
runtime.(*mheap).alloc_m(0x2e3928, 0x7, 0x41, 0x26fa00, 0x26faa8)
        /usr/local/go/src/runtime/mheap.go:510 +0x138
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:574 +0x40
runtime.systemstack(0x10693f18)
        /usr/local/go/src/runtime/asm_arm.s:261 +0xa8

**Comment by xtaci** [comment]
低端路由器无法运行

**Comment by ligf** [comment]
我观察内存的使用并没有达到100%  只有60%左右 程序运行起来之后 几秒钟就出现了错误

**Comment by xtaci** [comment]
@ligf 路由器我不熟悉，我也没有看到在路由器上成功运行的案例。

**Comment by ligf** [comment]
@xtaci 那可能还是不适合路由器吧

**Comment by xtaci** [comment]
@ligf kcptun是针对amd64架构优化的,arm的速度可能会慢几十倍。不建议在arm路由器跑，你可以考虑intel系列处理器，比如ATOM

**Comment by ligf** [comment]
@xtaci 我是看有人弄了arm的 才试了一下 看来还是不适合

**Comment by xtaci** [comment]
嗯，速度太慢，不能发挥出最佳效果
