### ISSUE TITLE
新手学习kcptun代码中的一点疑问

### ISSUE THREAD

**Issue by AntiverX** [xtaci/kcptun#550]
不知道这里能不能问代码的问题。。。实在找不到其他地方问kcptun的问题了

为了了解kcptun_server main.go中的handleClient是怎么工作的，我加了个全局变量c，并增加了几行log

![1](https://user-images.githubusercontent.com/22369960/34194160-43cd0330-e592-11e7-8058-e5fa733d5eeb.png)

编译后进行测试
![2](https://user-images.githubusercontent.com/22369960/34194188-67327166-e592-11e7-9930-4948cfd842d3.jpg)

log输出p2die 21之后，证明已经执行到select处了，这个函数不应该就退出了么，为什么后面还会继续出现steam to server 21和steam to client 21呢？

谢谢

**Comment by xtaci** [comment]
任何一个方向的退出p?die，会导致p1.Close p2.Close, 进而导致另一个方向的io.Copy返回，输出stream to...

**Comment by AntiverX** [comment]
p1.Close p2.Close发生之后，handleClient不就退出了么,但相同序号的handleClient重复了好几次下面的log
stream to server
p2die
stream to client

**Comment by xtaci** [comment]
handclient 退出了，可是 go func()是独立的啊

**Comment by AntiverX** [comment]
输出p?die的部分不是在handleClient中么，既然handleClient退出了，后续为什么还能输出p?die

抱歉之前进行的并发编程不多，初步的概念都懂，不过实际看代码的时候还是会有些疑惑= =

**Comment by AntiverX** [comment]
我的错，我不该把计数用的变量在handleClient里改变值的。。。我把c放在handleMux的最后自加，然后输出的log就比较正常了，我的疑问主要在同一个序号的stream to server 和 stream to client出现的次数太多了，看来是我的序号错了，这个貌似是线程不太安全 @xtaci
