### ISSUE TITLE
Does kcptun require client have a external ip ?

### ISSUE THREAD

**Issue by eromoe** [xtaci/kcptun#551]
Hello, 

I am trying to bundle ss + kcptun in a docker image ,  but it can't connect .

```
2018/01/03 01:40:21 session marked as expired
2018/01/03 01:40:21 connection: 172.17.0.16:52502 ->  xxxx
2018/01/03 01:40:22 session normally closed
2018/01/03 01:41:04 session marked as expired
2018/01/03 01:41:04 connection: 172.17.0.16:49097 ->  xxxx
2018/01/03 01:41:05 session normally closed
2018/01/03 01:41:57 session marked as expired
2018/01/03 01:41:57 connection: 172.17.0.16:52951 ->  xxxx
2018/01/03 01:41:58 session normally closed
```
`172.17.0.16`  is docker internal IP,  so I come up this question.

**Comment by flipphos** [comment]
I tried ss + kcptun in a vm on LEDE 17.01.x and it worked fine.

**Comment by eromoe** [comment]
it's client， not server

**Comment by wangyu-** [comment]
No, its not necessary to have an external/public ip.

I suggest you to do some test with netcat's udp mode, make sure your udp is not broken inside the docker.
