### ISSUE TITLE
kcptun会阻塞其他程序的下载进程？

### ISSUE THREAD

**Issue by owcc** [xtaci/kcptun#552]
mac平台。当kcptun_client进程与office自动跟新程序(microsoft autoupdate)同时启动时，kcptun和microsoft autoupdate均非常慢(千兆网均下降到30+kb)，如果关掉其中一个，则网络恢复正常。还未测试其他app是否也会出现这样的情况。

**Comment by iceonsun** [comment]
不影响

**Comment by owcc** [comment]
但kcptun_client进程与office自动跟新程序同時進行的時候確實相互阻塞，在我電腦上100%出現。不過不影響正常使用，管理可以關掉這個issue了
