### ISSUE TITLE
reduce memory when many connections and requests

### ISSUE THREAD

**Issue by zyf0330** [xtaci/kcptun#558]
I use kcptun forward http request from HongKong via ShenZhen to Beijing.
At peak period time when concurrent connections is 18K and QPS is 7500, kcp-client always is killed by kernel because it uses too much memory. Is there any way to improve this problem?
Server memory is 4G.

**Comment by xtaci** [comment]
try adjusting env variable GOGC

**Comment by zyf0330** [comment]
Thanks, I will try set it 80 first

**Comment by zyf0330** [comment]
It doesn't work, and I test 60 too.
Incoming connections are all http/1.0, and I put nginx before kcp-client to change them to http/1.1. 
In this situation, is there other way?

**Comment by PtDragon** [comment]
@zyf0330 Hello! Try to use GOGC at 10, if it's not enough try to balance to several instances of kcptun(i personally use 8 instances to avoid too much memory allocation).

**Comment by zyf0330** [comment]
What do you mean balance to several instances of kcptun? Is it running multi kcptun in one server?

**Comment by PtDragon** [comment]
@zyf0330 Yeah, I have 8 instances of kcptun for handling http requests. (for example ports 3001-3008 each having kcptun instance)
Also at client side I have 8 instances too and nginx to balance between them.

**Comment by zyf0330** [comment]
Why use multi instances of kcptun? I just don't know.

**Comment by PtDragon** [comment]
@zyf0330 Because of some reasones:
1) RAM usage under load with multiple instances is usually lower
2) Each instance can use around 1.2 CPU cores.
3) When many connections it simply works better(for me at least) with multiple instances(less hiccups).

**Comment by zyf0330** [comment]
These reasons are not convincing.
1. what article supports **usually**?
2. I don't think this is a reason, and why 1.2 CPU, so you have 1.2 * 8 = 9.6 cpus cores totally?
3. Maybe this is your situation, not mine. It is just an experience. I have three server, every affords 40Mbps incoming and outgoing bandwidth.

**Comment by PtDragon** [comment]
@zyf0330 
1) It comes from my tests under real load. Usually means "in most situations". If you have thousands of long-living TCP connections in your tunnel there would be no difference or even multiple instances can take more RAM in total. But for short connections for me it takes less RAM if I use multiple instances. Short for me is under 5 minutes. I suspect it is tied to how garbage collector works in GO itself.
2) I actually have 2 CPU cores but single instance is unable to take more than 1.2 cores(it shows like 120% of single core load in htop) under any load.
3) Sure, it is my situation, for yours it can work differently but it never hurts to try and see if it makes things better or worse for you(and share your experience with others).
