### ISSUE TITLE
too many colons in address

### ISSUE THREAD

**Issue by xau0at** [xtaci/kcptun#56]
无法使用ipv6吗？用ipv6就提示太多冒号。
`2016/07/12 09:47:05 version: 20160701
2016/07/12 09:47:05 listening on: [::]:12948
2016/07/12 09:47:05 encryption: aes
2016/07/12 09:47:05 nodelay parameters: 1 20 2 1
2016/07/12 09:47:05 remote address:  [::]:29900
2016/07/12 09:47:05 sndwnd: 256 rcvwnd: 2048
2016/07/12 09:47:05 compression: true
2016/07/12 09:47:05 mtu: 1400
2016/07/12 09:47:05 datashard: 10 parityshard: 3
2016/07/12 09:47:05 acknodelay: false
2016/07/12 09:47:05 dscp: 46
2016/07/12 09:47:05 conn: 1
2016/07/12 09:47:05 too many colons in address  [::]:29900
`

**Comment by xtaci** [comment]
地址写错了

**Comment by xau0at** [comment]
？？？没有啊 地址应该怎么填？

**Comment by xtaci** [comment]
你这个不相当于 连接到 0.0.0.0:29900么，空地址啊

**Comment by xau0at** [comment]
晕 我肯定要把我的地址遮挡住啊

**Comment by xtaci** [comment]
```
Dial("tcp", "12.34.56.78:80")
Dial("tcp", "google.com:http")
Dial("tcp", "[2001:db8::1]:http")
Dial("tcp", "[fe80::1%lo0]:80")
Dial("tcp", ":80")
```
以上是合法的地址格式

**Comment by xau0at** [comment]
谢谢 我再试试

**Comment by UesugiErii** [comment]
我也遇到了,解决方法如下

在任何基于kcptun的客户端的ipv6地址旁加上中括号[]

**Comment by syanle** [comment]
同楼上，有个bug，不能填一个只有AAAA记录的域名，否则域名自动转换成ip地址后不会加上括号[]

**Comment by ddzx** [comment]
你想干嘛？
