### ISSUE TITLE
低延时游戏场景broken pipe

### ISSUE THREAD

**Issue by AlfredZuo** [xtaci/kcptun#560]
![image](https://user-images.githubusercontent.com/22234543/35870516-d72d9984-0b9c-11e8-9880-6d5279302e6e.png)

场景描述：
1）深圳移动光纤入户，通过kcptun连到德国AWS服务器，同服使用$$作为代理跳转。
2）开启游戏后（使用TCP连接），一开始都是正常的，通过系统网卡查看流量正常情况流量都是上图天蓝色的线（小于100K，服务器端07:50启动的，客户端15:51启动的），20多分钟后，网络流量突然增加，实际应用的流量，平均280K，高峰超过500K，然后服务器就broken pipe了（服务器侧08:14，客户端未提示）
![image](https://user-images.githubusercontent.com/22234543/35775798-d271b0a2-09ca-11e8-8fff-4cc1ba181a87.png)
3）原来尝试过DSCP46，更加容易broken pipe；mtu设置到256与512似乎没啥差别，也是容易bp。
4）参数如下：

服务器，kcptun version 20171201：
{
  "listen": ":443",
  "target": "127.0.0.1:13333",
  "key": "xxxxx",
  "crypt": "aes",
  "mode": "manual",
  "mtu": 512,
  "sndwnd": 256,
  "rcvwnd": 256,
  "datashard": 5,
  "parityshard": 5,
  "dscp": 0,
  "nocomp": true,
  "quiet": false,
  "pprof": false,
  "nodelay": 1,
  "interval": 10,
  "resend": 1,
  "nc": 1
}

客户端，20171201的版本：
{
  "localaddr": ":13338",
  "remoteaddr": "xxxxxxxxxx:443",
  "key": "xxxxx",
  "crypt": "aes",
  "mode": "manual",
  "conn": 1,
  "autoexpire": 0,
  "scavengettl": -1,
  "mtu": 512,
  "sndwnd": 256,
  "rcvwnd": 256,
  "datashard": 5,
  "parityshard": 5,
  "dscp": 0,
  "nocomp": true,
  "quiet": false,
  "nodelay": 1,
  "interval": 10,
  "resend": 1,
  "nc": 1
}

**Comment by AlfredZuo** [comment]
又试了调整几个参数，如MTU1300，无效，同样20多分钟后会broken pipe；还有模式改为fast3，同样如此

**Comment by AlfredZuo** [comment]
原来是使用长宽的，这些问题都没有；2周前换了移动宽带，这个问题就一直存在了
此外，我还尝试使用了ccsexyz的kcpraw，现象与kcptun一样

**Comment by sglfree** [comment]
以前有别的issue反馈好像移动宽带一定时间会断开udp长连接，要是这个原因lz可以试试这个：https://github.com/wangyu-/udp2raw-tunnel 要是能解决说明就是移动限制UDP了。

**Comment by AlfredZuo** [comment]
kcpraw和kcptun+udp2raw两者有什么区别？我理解两者达到的目的是一个，只不过一个软件和两个软件的区别。那问题来了，为什么kcpraw依然无效呢？

**Comment by sglfree** [comment]
区别可能是在Raw socket实现上有些不同（没仔细看过代码），如果尝试kcptun+udp2raw同样还是有断流可以再给作者提issue。

**Comment by AlfredZuo** [comment]
ok，我晚上回去试试udp2raw，有进展反馈

**Comment by lixingcong** [comment]
shadowvpn(一款基于UDP的tun代理)也是在移动环境下经常broken pipe

**Comment by AlfredZuo** [comment]
经过时延，udp2raw可以规避QoS问题，谢谢大家，问题可以关闭了

**Comment by sgf** [comment]
我不太明白 QoS 会让kcp断流 那么 QoS 难道不会让QQ之类的 UDP包 断流吗？那么腾讯QQ 之类的应用又是如何处理的呢？

**Comment by mickeyandkaka** [comment]
北京移动+1  ss-libev + kcptun 在大流量情况下会被间歇性断开。

**Comment by iceonsun** [comment]
我来安利一个kcptun伴侣
https://github.com/iceonsun/rsock
