### ISSUE TITLE
我下载的WIN客户端文件中，server_windows_amd64是干什么用的？

### ISSUE THREAD

**Issue by zjbr** [xtaci/kcptun#562]
我还是有点懵，请过来人教教小白。

**Comment by Javalover93** [comment]
应该是服务器端的软件，windows 个人电脑端使用 client 就可以了。

**Comment by wxlg1117** [comment]
作者提供的几乎所有平台都 有server和client,意味着你在所有可以跑的平台度可以作为服务器或者客户端呀
