### ISSUE TITLE
无法ssh；电脑连接正常，手机前几次正常，之后连不上

### ISSUE THREAD

**Issue by ghoshorn** [xtaci/kcptun#564]
服务器是搬瓦工的，电脑mac，手机Android

issue 1：配置了kcptun之后，在terminal里ssh失败，输过密码之后，提示packet_write_wait: Connection to XXX: Broken pipe。看有issue说重启vps可以，但是重启了n次，问题依旧。

issue 2：配置了kcptun后，mac端连接没有问题，Android前两次连接也没有问题，速度确实提升了好多。在服务器和客户端都没有改参数的情况下，之后Android上就连接不了了，mac上可以。Android连接不带kcptun的也是可以正常工作的。手机端提示为无法连接，server端日志是broken pipeline。

请问这是什么问题 ？

**Comment by Rouzip** [comment]
手机一开始正常，后来也是经常中断。我发现如果ss非正常关闭会大概率导致该问题，晚上12点左右也有时候出现这个问题。一般等待一段时间之后恢复正常。手机MIUI9.5.6.0稳定版，移动
