### ISSUE TITLE
请问有支持SIP003的计划吗？

### ISSUE THREAD

**Issue by tenwx** [xtaci/kcptun#567]
shadowsocks-libev，shadowsocks-windows都遵循了SIP003协议的plugin，这样就可以在一个客户端内实现支持kcptun的ss，现在的情况是我们必须要启动一个独立的kcptun进程，然后再使用ss客户端连接kcptun监听在本地的端口从而实现连接，这么做终究不太优雅。目前shadowsockes-android自己开发了kcptun plugin，但只能支持android平台，希望能通过kcptun原作者来开发一个通用的支持SIP003协议的kcptun plugin，谢谢！

**Comment by wangyu-** [comment]
Linux上已经有了：

https://github.com/w1ndy/kcptun-plugins

**Comment by bro0k** [comment]
https://github.com/shadowsocks/kcptun

**Comment by alexlee728** [comment]
@bro0k https://github.com/shadowsocks/kcptun 这个版本很久不更新了。

**Comment by zhanhb** [comment]
补个windows版的，https://github.com/zhanhb/kcptun-sip003-wrapper/blob/master/src/kcptun.cmd

**Comment by muyinliu** [comment]
ShadowsocksX-NG use a bash script as an adaptor: [https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ShadowsocksX-NG/kcptun/kcptun.sh](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ShadowsocksX-NG/kcptun/kcptun.sh)
