### ISSUE TITLE
mips softfloat 版本请求

### ISSUE THREAD

**Issue by bitching** [xtaci/kcptun#568]
很多常见路由器的CPU都是 MIPS xxx Kc 系列，Mips 的文档有提到 Kc 系列的 CPU 都没有 FPU，包括一众mt7620a/7621a。
而且 OpenWRT/LEDE 的官方固件均未开启 Kernel -> MIPS FPU Emulator ，跟那边提过 issue ，让自己编译固件。。。。
2018/2/16新发布的 Golang 1.10 支持软件模拟浮点计算， Release Note 提到唯一需要做的就是设置环境变量 GOMIPS=softfloat 。
以后发布时可否增加一个 softfloat 的版本，造福广大 Kc 系列，同时也不耽误CPU有FPU的高端路由器？

**Comment by xtaci** [comment]
可以，能PR 到build-release.sh是最好的

**Comment by xtaci** [comment]
已加
