### ISSUE TITLE
在mips路由器上编译成功，但无法运行

### ISSUE THREAD

**Issue by xinghusp** [xtaci/kcptun#57]
我尝试在RT-N66U上运行自行编译的kcptun，总是一启动就报错退出。
经定位是调用ListenTCP的时候就挂了，但是返回了-9这种奇怪的错误代码。

尝试了论坛里@bettermanbao 大神之前编译的For Openwrt的MIPS版本，也是一样的错误。

我尝试刷了Tomato和Merlin的固件，都是一样的问题。

求各位指教。
![qq 20160713131430](https://cloud.githubusercontent.com/assets/18201606/16795484/1fd9313a-4910-11e6-9801-89872bb83206.jpg)

**Comment by xtaci** [comment]
我也不知道啊，可以指定一下地址+端口试试。 mips即使跑起来也很慢的。

**Comment by xinghusp** [comment]
@xtaci 尝试过了。。我自己写了个小helloworld，即便只是调用ListenTCP，都会返回这个错误。
我估计是MIPS的内核和go有不兼容的地方，只是想发出来问问大家的意见。。

我另一个ARM的路由器，倒是可以跑到10Mbps的带宽，无加密的情况。RT-AC56U，用着挺棒的

**Comment by xtaci** [comment]
mips32编译器不是官方的，编译出来的代码执行效率没有保障，可以说，肯定很慢。 ARM无论如何都会快，因为有官方编译器，但是，kcptun的代码主要是针对amd64做的汇编优化，即使是i386，也比amd64慢一倍，更何况mips了。

**Comment by xinghusp** [comment]
了解了，谢谢
当初想着弄这个主要还是有两台要求不太高的场合打算部署这个，不过如果确实有问题，也就算了。。
看看其他的网友有啥编译建议呗

**Comment by bettermanbao** [comment]
你的编译器的问题吧？mips32虽然慢了点，但是肯定是能运行的。不过snappy压缩好像是有问题

**Comment by bettermanbao** [comment]
你找我的repo，有编译好的bin。

**Comment by xinghusp** [comment]
@bettermanbao 我下了你的kcptun_client_openwrt的，也是一样的错误，非常奇葩
在tomato和merlin上都这样，我怀疑是不是内核太老导致的
openwrt的无线据说有问题，没法用在这个路由上

**Comment by xinghusp** [comment]
![image](https://cloud.githubusercontent.com/assets/18201606/16798304/fa443aec-491d-11e6-9287-c42a42b3d718.png)

在openwrt下运行正常， 看来是内核问题？openwrt用的是3.x的内核，tomato和merlin都是2.6的内核

**Comment by xinghusp** [comment]
![image](https://cloud.githubusercontent.com/assets/18201606/16799092/b7dec86c-4921-11e6-888f-7837d3af0f8a.png)

@xtaci MIPS下性能似乎还行？ 也能稳定在10多Mbps了，我想对于很多人而言足够用了。
--crypt none --mode fast2 --nocomp

**Comment by xtaci** [comment]
嗯， 不错

**Comment by bettermanbao** [comment]
你的mips路由用的什么cpu？

**Comment by xinghusp** [comment]
@bettermanbao 按照说明，应该是BCM4706的，不过cpuinfo显示的结果有点不同。。
![image](https://cloud.githubusercontent.com/assets/18201606/16799225/53a494ac-4922-11e6-82a3-68014a4153ea.png)

**Comment by wang20150419** [comment]
我也想把它放 NETGEAR WNDR4300 路由器里，用了 @bettermanbao  的版本，可以跑起来，但上网的过程中出了大量的错误。今天，把办公室的 树莓派2拿来当 kcptun 客户端，然后在路由器里用 redsocks2连接树莓派2，看youtube，速度可以在 1000Kbps左右，好的时候 2000Kbps，ping丢失15%，还行。VPS上跑的是kcptun+danted，看视频是比SS强多了。

**Comment by xinghusp** [comment]
@wang20150419 羡慕你们能跑起来的，尝试关掉压缩和加密，可能就好了……
