### ISSUE TITLE
accept4: too many open files

### ISSUE THREAD

**Issue by supercatexpert** [xtaci/kcptun#571]
System: Debian Stretch/9.x
Go version: 1.8.1

Hello, I use this program with shadowsocks-libev.
After updated the server and client part to latest version, the client will crash with error 'accept4: too many open files'. And I also detected many connections with 'CLOSE_WAIT' on local TCP port of client part in netstat. After I rollback the server part to previous version, this problem solved. It seems that the latest changes on server part occur this problem.

**Comment by xtaci** [comment]
yes, it's true, passive mode takes up more file handlers,  you can adjust open files limit by `ulimit -n 65535` or more.

**Comment by supercatexpert** [comment]
Maybe it's better to make a option for user to select between active mode and passive mode? I don't want to see so many unused socket connections.

**Comment by xtaci** [comment]
It's not just about passive or active, it's actually a question of how to close an established tunnel properly.

A <--> tunnel <--> B

situations including:
1. A closes first, but B doesn't close immediately
2. B closes first, but A doesn't close immediately

the active mode closes both A & B if any one of them closes(may cause incomplete sending), the passive mode waits until both A&B closes.

i'm trying to find way to balance
