### ISSUE TITLE
kcptun部署多进程&核心问题

### ISSUE THREAD

**Issue by ifooth** [xtaci/kcptun#575]
### 背景
SS+KCPTUN已经运行了快一年了，被KCPTUN的加速效果惊艳到了，简单部署如下

电视/电脑/手机 -> 小米WIFI  -> `树莓派3B(双网卡做Router)` - > Linode(东京节点)

树莓派3B(双网卡做Router):
- ss-tunnel 代理8.8.8.8:53端口
- ChinaDNS 配合dnsmasq做DNS服务器
- ss-redir 配合ss-nat做透明代理
- KCPTUN 做加速

目前配合接近完美，fast.com测试可以达到23Mbps，但是CPU负载已经100%

![image](https://user-images.githubusercontent.com/1853121/37551135-090e45d8-29d5-11e8-8d5a-f4d6f8c596e2.png)

### 问题：
现在整个瓶颈貌似在KCPTUN CPU使用率上，那么问题来了？
- kcptun能利用多核心么？
- 是否需要启动多进程部署，然后负载均衡。

PS：已经尝试过nginx做udp代理，使用不是很稳定，效果提升也一般。

也求各位大神分享下部署方式，学习学习。

**Comment by zzlinwq** [comment]
ss-redir 配合ss-nat做透明代理 具体在树莓派在怎么配置的呢?我是树莓派2.  PS：vps要相应配置吗？

**Comment by ifooth** [comment]
VPS正常配置即可

**Comment by zzlinwq** [comment]
请问你的树莓派装的是什么系统？

**Comment by ifooth** [comment]
RASPBIAN LITE

**Comment by wxlg1117** [comment]
舒梅派推荐DietPi,基于官方的RASPBIAN ,但部署方便多了

**Comment by zzlinwq** [comment]
DietPi怎么部署更方便呢？

**Comment by living42** [comment]
我也遇到了同样的问题，硬件跟你一样，速度只能到15Mpbs左右， 这个时候进程的CPU使用率是100-130%左右，一个核心满负载，剩下的三个核心都是空闲的。

其实我对这个速度已经非常满意了， 但是还是有一个比较在意的地方， 我发现VPS这边的发包速率已经到50Mbps， 甚至能达到80Mbps， 但是路由器这边只有处理15Mbps的能力。如果我在性能比较高的PC上面， 这个时候处理能力比较高， VPS这边以50Mbps的速率发包， 在PC上也能达到同等的速率。

**Comment by BH4WHN** [comment]
我也是只工作在一个内核上，后面换了nanopi-m3单核1.6Ghz基本能把宽带跑满了，另外我一直在用v20170221的版本，其余新的版本速度一直不如这个版本，你可以试试。
