### ISSUE TITLE
kcptun 的 TCP 端口无法进行 health-check.

### ISSUE THREAD

**Issue by david9991** [xtaci/kcptun#576]
kcptun 的 TCP 端口无法进行 health-check.
无论连接是否正常，health-check 永远 0ms。因为  tcp 的 health-check 通常通过 syn/ack 的时间检测是否连接正常，而 kcptun 在本地直接就返回 ack 了，这样 health-check 检测的是 client 到 kcptun 的连接健康情况而不是 kcptun-client & kcptun-server 之间 UDP 连接的健康情况。是否可以新加一个专门用来 healthcheck 的端口，并通过 UDP 包的发送和应答情况来返回 ack？

**Comment by ccsexyz** [comment]
可以通过应用层探测来进行健康检查

**Comment by david9991** [comment]
已通过修改 ss 在应用层解决。
