### ISSUE TITLE
关于ipv6环境下使用ss-r与kcptun产生的若干问题

### ISSUE THREAD

**Issue by nightmare2153** [xtaci/kcptun#577]
首先安装ssr时选择protocol 为auth_sha1_v4，Obfs为tls1.2_ticket_fastauth不清楚两者有没有干扰。暂时先写上。
在安装kcptun后更改服务端配置为：
{
  "listen": "127.0.0.1:1234",
  "target": "[vps--ipv6 address]:2233",
  "key": "key",
  "crypt": "aes",
  "mode": "fast2",
  "mtu": 1350,
  "sndwnd": 2048,
  "rcvwnd": 2048,
  "datashard": 70,
  "parityshard": 30,
  "dscp": 46,
  "nocomp": false,
  "quiet": false,
  "pprof": false
  "sockbuf": 4194304
  "keepalive": 10
}
然后根据服务端配置设置客户端配置。但是产生错误“2018/03/23 23:11:18 re-connecting: createConn(): net.ResolveUDPAddr: address vps--ipv6 address]:1234: too many colons in address”
ss客户端配置ip为127.0.0.1 端口为1234. 
开启时无法连接网络

**Comment by nightmare2153** [comment]
设置更正为"listen": "[::]:2233",
"target": "[本地ipv6 address]:1234",

客户端"client_windows_amd64.exe" -l :2233 -r [本地ipv6]:1234 -key "2153" -crypt aes -datashard 70 -parityshard 30 -mtu 1350 -sndwnd 2048 -rcvwnd 2048 -dscp 46 -keepalive 10 -sockbuf 4194304 -mode fast2
日志问题解决
2018/03/24 12:50:58 version: 20170904
2018/03/24 12:50:58 listening on: [::]:2233
2018/03/24 12:50:58 encryption: aes
2018/03/24 12:50:58 nodelay parameters: 1 20 2 1
2018/03/24 12:50:58 remote address: [本地v6]:1234
2018/03/24 12:50:58 sndwnd: 2048 rcvwnd: 2048
2018/03/24 12:50:58 compression: true
2018/03/24 12:50:58 mtu: 1350
2018/03/24 12:50:58 datashard: 70 parityshard: 30
2018/03/24 12:50:58 acknodelay: false
2018/03/24 12:50:58 dscp: 46
2018/03/24 12:50:58 sockbuf: 4194304
2018/03/24 12:50:58 keepalive: 10
2018/03/24 12:50:58 conn: 1
2018/03/24 12:50:58 autoexpire: 0
2018/03/24 12:50:58 scavengettl: 600
2018/03/24 12:50:58 snmplog: 
2018/03/24 12:50:58 snmpperiod: 60
2018/03/24 12:50:58 connection: [本地v6]:64538 -> [本地v6]:1234
2018/03/24 12:50:58 stream opened
2018/03/24 12:51:02 stream opened
2018/03/24 12:51:05 stream opened
2018/03/24 12:51:06 stream opened
2018/03/24 12:51:09 stream opened
2018/03/24 12:51:20 stream opened
2018/03/24 12:51:28 stream closed
2018/03/24 12:51:28 stream closed
2018/03/24 12:51:28 stream closed
2018/03/24 12:51:28 stream closed
2018/03/24 12:51:28 stream closed
2018/03/24 12:51:28 stream closed
2018/03/24 12:51:29 session marked as expired
2018/03/24 12:51:29 connection: [本地v6]:50230 -> [本地v6]:1234
2018/03/24 12:51:29 stream opened
2018/03/24 12:51:29 stream opened
2018/03/24 12:51:29 session normally closed
2018/03/24 12:51:30 stream opened
2018/03/24 12:51:30 stream opened
2018/03/24 12:51:31 stream closed
2018/03/24 12:51:31 stream closed
2018/03/24 12:51:31 stream closed
2018/03/24 12:51:31 stream closed
同时ss设置ip为本地v6及1234
但是无法联网

**Comment by mountainguan** [comment]
印象中kcptun是不能加混淆的
