### ISSUE TITLE
在Mac上跑相当有效果，但上路由报错了

### ISSUE THREAD

**Issue by Kinghack** [xtaci/kcptun#58]
使用了release里下载的client_linux_arm7，在R7000里跑，R7000的CPU是

`
Processor	: ARMv7 Processor rev 0 (v7l)
processor	: 0
BogoMIPS	: 1998.84

processor	: 1
BogoMIPS	: 1998.84

Features	: swp half thumb fastmult edsp
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0
`

一跑就报，
`Illegal instruction`

怀疑是release用的golang beta版本的问题，于是自己也build了下，
我这边是stable的1.6
`go version go1.6 darwin/amd64`

依然同样的错误。

甚至build一个hello world也是一样的错误。

R7000是刷了梅林固件的。

有啥建议不？

**Comment by xtaci** [comment]
参考 #57

**Comment by Kinghack** [comment]
@xtaci 

伤心，果然是 
`2.6.36.4brcmarm`

那我再研究下。。

**Comment by wang20150419** [comment]
没玩过go的编译。希望有对应的 “fix urfave deprecated action signature” 执行程序更新。

**Comment by xtaci** [comment]
等go1.7正式版发布后再更新，这个小fix没关系的

**Comment by xinghusp** [comment]
@Kinghack 用arm5的版本

**Comment by Kinghack** [comment]
@xinghusp 感觉，arm5的版本确实能跑；

但跑了一会儿就崩了。

![screen shot 2016-07-14 at 16 11 22](https://cloud.githubusercontent.com/assets/1154775/16832619/a5d121c6-49dd-11e6-927e-d6931bc4e5a1.png)

**Comment by xinghusp** [comment]
@Kinghack --crypt none --nocomp 试试咯 
对了 如果是一大版错误的，有可能是内存不足溢出了，尝试开虚拟内存吧
我在AC56U上跑了两天了，非常顺利，流量还蛮大的，没坏过

**Comment by wang20150419** [comment]
不知道 kcptun 有没有特征 能够被 GFW 抓住。如果没有的话，一些传统的VPN技术就可借尸还魂，如：openvpn, softether等，在避开GFW的同时还提升了速度！SS，SSR，V2ray等，就可以退役了。

**Comment by xinghusp** [comment]
@wang20150419 这个适用范围还很小，估计还没被注意。不过我现在的方案是kcptun不加密，下面封装ss chacha20

**Comment by trivita** [comment]
用的人多了以后一样会麻烦，而且UDP随便粗暴干扰就好了

**Comment by Kinghack** [comment]
@xinghusp Ok.
我明天到办公室再看看。

**Comment by Kinghack** [comment]
后来发现似乎是路由器的DNS配得有问题，有个配置一直没生效，但我以为生效了，但那个IP应该已经都没了。

现在换上去中午到现在2个小时没崩，就让办公室的4台电脑一起开youtube的时候崩了一次。。。
CPU看路由界面是跑到了80%，没仔细看了。只要大概能稳定就Ok了。

周末准备回家试试ac66u，这货又不是arm了。。不知道能不能折腾。。

**Comment by xinghusp** [comment]
@Kinghack AC66u 也是MIPS的吧，估计悬；我在merlin和tomato的mips平台上还没跑成功……内核太老了

**Comment by Kinghack** [comment]
@xinghusp 这样啊？那感觉很玄。。。

**Comment by xinghusp** [comment]
@Kinghack 祝你成功。。

**Comment by Kinghack** [comment]
r7000上加了--crypt none --nocomp，依然还是会挂掉；
看了下报错的信息，应该就是OOM。

我尝试了下改一处代码，加入某个超时机制，能干掉过多的groutine，但还没验证；

以及，今天晚上我应该能拿到个树莓派3，我应该会把kcptun的程序移到那里去跑，如果稳定就不折腾了。。。

**Comment by wang20150419** [comment]
我在树莓派2上跑，效果非常好，用pi3，就更没问题了。路由器通过树莓派做透明路由（redsocks2）
