### ISSUE TITLE
Kcptun服务端只能配置在linux上运行么? 

### ISSUE THREAD

**Issue by shibage** [xtaci/kcptun#581]
Kcptun服务端只能配置在linux上运行么?  能够在Windows系统配置服务端么？
找了一圈也没找到教程。如果不行的话我也死心了。

**Comment by xtaci** [comment]
全平台支持， google一下

**Comment by shibage** [comment]
google 不到诶，能否指一下路呢？ 拜

**Comment by shibage** [comment]
就是 server_windows_amd64.exe 不知道怎么用，打开来就是已经是一串默认的设置？

**Comment by wxlg1117** [comment]
win和linux配置参数一模一样的呀

**Comment by cs8425** [comment]
@shibage 
寫個bat檔, 把參數(全平台一樣)加在後面就行

**Comment by iceonsun** [comment]
我也建议稍微写一下windows怎么运行。我刚开始也是直接点了exe，运行不起来才用的cmd。普通用户可能不知道怎么弄

**Comment by alex43211** [comment]
windows上有个kcptun-gui可以用
