### ISSUE TITLE
Youtube APP只要打开中间的订阅内容一定会断流

### ISSUE THREAD

**Issue by keeno1982** [xtaci/kcptun#582]
是因为我订阅的频道太多，数据量大就挂掉吗，刷Tumblr也很容易断流
是配置问题吗，防QOS已经挂了udp2raw了

服务器配置
{
  "localaddr": ":443",
  "remoteaddr": "x.x.x.x:113",
  "key": "88888888",
  "crypt": "none",
  "mode": "fast",
  "mtu": 600,
  "sndwnd": 1024,
  "rcvwnd": 1024,
  "datashard": 10,
  "parityshard": 3,
  "dscp": 0,
  "nocomp": true,
  "quiet": false
}

客户端配置
./client_linux_arm7 -l ":9527" -r "127.0.0.1:113" --key 88888888 --crypt none --mode fast --nocomp --mtu 600 --sndwnd 512 --rcvwnd 512 --dscp 0 > /kcptun.log 2 >&1

就是图最下面中间那个鬼东西
![img_3151](https://user-images.githubusercontent.com/13664097/38665968-5cc8539e-3e70-11e8-83fc-43b0129cefc4.PNG)

**Comment by imess** [comment]
No such problem. Maybe an issue caused by QUIC, block udp443/80 outgoing traffic to see how things go.

**Comment by iceonsun** [comment]
首先建议把断流前后的kcptun和udp2raw的日志帖上来。

> 数据量大就挂掉吗

你首先要自己确定一下，是哪种情况:

- 流量跑了很多就会断
- 还是跑了很多流量，点击其他地放（比如“活动”）不会断，只有点击“订阅内容”才会断
- 还是即使跑很少流量，一点击“订阅内容”就断。

如果是udp2raw的问题，不大清楚udp2raw收到rst等中断会不会造成kcptun的close stream。

如果是udp2raw的问题，那么我推荐rsock。rsock和udp2raw类似。没有iptables操作。
https://github.com/iceonsun/rsock

**Comment by xtaci** [comment]
-autoexpire 900
