### ISSUE TITLE
How to redirect all traffic through the tunnel.

### ISSUE THREAD

**Issue by OneOfOne** [xtaci/kcptun#584]
How to redirect all my system (linux)'s traffic through the tunnel?

I'm not sure sure.

**Comment by iceonsun** [comment]
You can't. kcptun only listens on a single port

**Comment by imess** [comment]
Only tcp traffic can be tunnelled through kcptun. To tunnelled all traffic, I suggest you use a udp-based vpn as a frontend (maybe openvpn or ss redir mode if you don't care about icmp traffic for the latter) concatenating to kcptun and udpspeeder (both listen on the "same" port but one for tcp and the other for udp). By using policies-based routing, you can easily route all traffic to the frontend and tunnel them through the two speeders. Currently I combine the two frontends to implement transparent proxy and benefits speed and stability.
