### ISSUE TITLE
内存使用量随时间逐渐增长，不会释放

### ISSUE THREAD

**Issue by mukaiu** [xtaci/kcptun#585]
两边都是CentOS7 Docker 运行 xtaci/kcptun:v20180316。

服务端随时间增长内存使用量逐渐上升直到内存不足，这个过程比较缓慢。运行2天左右内存使用量可达1G。
另外通过pprof注意到大量goroutine未停止，是否是smux的问题？正在看相关代码～

![image](https://user-images.githubusercontent.com/7746790/39057148-23d5b960-44eb-11e8-9d3e-283caa7f9033.png)

![image](https://user-images.githubusercontent.com/7746790/39057246-5447964a-44eb-11e8-82ef-664c4af13202.png)

**Comment by mukaiu** [comment]
client 和 server 都只有 stream opened 没有 stream closed
![image](https://user-images.githubusercontent.com/7746790/39063459-ca14efb4-44fd-11e8-8ede-560ee0d0b958.png)

**Comment by mukaiu** [comment]
v20171201 版无此问题

**Comment by iceonsun** [comment]
首先帖一下参数?

这个问题是必现的，还是偶然的？

如果是必现的可以看看不用docker会出现这个问题么。我用的也是这个版本，没有出现这个问题。

**Comment by mukaiu** [comment]
必然出现 参数如下
```
{ 
    "target": "shadowsocks:8388",
    "listen": ":51413",
    "mode": "fast2",
    "datashard": 10,
    "parityshard": 1,
    "nocomp": true,
    "dscp": 46,
    "key": "V0uRhAlUzJ5yXi1VqzVv",
    "crypt": "aes-256",
    "pprof": true,
    "quiet": false
}
```

**Comment by iceonsun** [comment]
客户端是哪个版本，哪个OS。如果是shadowsocksX-NG中自带的kcptun，那个版本是旧的版本。

为了定为问题, 先拷贝把ssX-NG中的kcptun拷贝出来，再用新的client替换，看结果如何。

**Comment by mukaiu** [comment]
![image](https://user-images.githubusercontent.com/7746790/39065358-2c6800ba-4504-11e8-8a21-bc96f80c2bc3.png)
是smux此部分代码的问题

**Comment by mukaiu** [comment]
两边同时使用v20171201以上版本才会出现此问题，如有一边使用v20171201或更低版本，不会触发此问题

**Comment by iceonsun** [comment]
https://github.com/xtaci/smux/blame/e28719eede1ac5714cf0b06ba2f403125864ebe0/stream.go#L50

这个函数的确是在4个月以前引入的

**Comment by xtaci** [comment]
不确定原因，是不是用了老的docker image，建议docker pull一下最新image，中间有个临时版本有leak问题。

**Comment by mukaiu** [comment]
已pull到最新，server端确实用了老镜像

**Comment by mukaiu** [comment]
服务端pull最新镜像解决，难怪重新build的没问题～
