### ISSUE TITLE
kcptun 没有任何访问的时候为什么 CPU 占用还是比较高

### ISSUE THREAD

**Issue by osdu** [xtaci/kcptun#587]
kcptun 没有任何访问的时候为什么 CPU 占用还是比较高，在 1% ~20% 之间浮动

这个是普遍存在的问题，还是受配置参数影响？

![qq 20180423004450](https://user-images.githubusercontent.com/2067880/39097499-94d8f122-468f-11e8-9f6c-4ceddb9e3124.png)

**Comment by osdu** [comment]
@imess 不使用 kcptun 的时候也会占用一部分CPU，不会想其他进程那样完全休眠？

**Comment by imess** [comment]
既然打开了，肯定就会跑流量，这玩意本来就吃资源，难以兼顾，除非握手失败，比如远程ip故意填错，这时cpu占用自然就会低了，那么在意这个，建议做个alias，秒开秒关。其实更多是跟cpu体质有关，如果是普通路由器的cpu，多倍发包又要兼顾加密减密，自然很吃力，树莓派3b跑这玩意儿空闲占用也要在1.5-2.7之间浮动，你整个i5的intel nuc，跑起来保证爽
