### ISSUE TITLE
关于最大速度方面的疑问

### ISSUE THREAD

**Issue by i258559** [xtaci/kcptun#588]
各位大佬好，有个疑问：在软路由上跑kcp速度反而不如vmess的tcp，同一个服务器差不多时间内测同样的土鳖视频，kcp最大下载速度1M左右/s，而tcp可以去到2M+/s，难道是电信udp限速？（但测试过，套了udp2raw和没套速度是差不多的）

PS：
1、mtu本地和服务器都支持；
2、客户端 sndwnd / rcvwnd调整过，但没明显区别。

服务器设置
{
    "crypt": "aes-128",
    "mode": "fast2",
    "mtu": 1472,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "nocomp": true
}

客户端设置
{
    "crypt": "aes-128",
    "mode": "fast2",
    "mtu": 1472,
    "sndwnd": 384,
    "rcvwnd": 1024,
    "nocomp": true
}

**Comment by keeno1982** [comment]
我也是遇到这个情况，KCP通常速度最高只能到1.1M撑死，但是BBR却经常能达到3-4M的速度，我也是不太理解

**Comment by wangyu-** [comment]
关注一下CPU占用。

>1、mtu本地和服务器都支持；

mtu 用1200，不要用接近1500的值。就算本地和服务器都支持，中间路径也不一定支持，可能会导致分片。 不能保证用1200就没问题，但是用1200能极大降低遇到疑难杂症的几率（在几乎不影响性能的情况下）。

**Comment by i258559** [comment]
多谢大佬回复，调整mtu是试过的，mtu最低试过1024，速度比1472慢不少，在我这边，mtu越大效果越好，cpu没压力，4核心3.5/单核3.6，跑满时占用突发最高也才20，应该可排除cpu效率的影响。
ps. 就是因为想到可能参数都尝试过调整，才觉得比较奇怪：在没qos的情况下，应该不至于和tcp差这么多

**Comment by keeno1982** [comment]
原来是跟MTU有关，我之前设置的是600，回头试一下看看调高会不会快一点

**Comment by wangyu-** [comment]
@i258559 
你可以尝试kcptun的同类软件对比一下，看到底是kcptun(参数)的问题还是网络问题。

**Comment by iceonsun** [comment]
我这边电信100M宽带，kcptun最大速度能达到1.8M-2M，套rsock能达到1.6M。

kcptun的确在速度上还不够给力，我在墙外两个vps上测试，最大速度是2M。通过iperf测试tcp，能达到10+M

**Comment by i258559** [comment]
@ wangyu- 嗯，等周末折腾下；
@iceonsun 我去了解下rsock。
PS . 手上没多余的小鸡的，到时开个vultr看看是不是和线路机房也有关系

**Comment by keeno1982** [comment]
@wangyu- 20M的宽带，用KCPTUN下载，下载速度达到900K-1M时观察路由器的下载速度却将近占满带宽了，差不多是真实下载速度的两倍，这是不是用KCPTUN跑不满带宽的原因？
我的配置是这样：./client_linux_arm7 -l ":9527" -r "127.0.0.1:123" --key 1444666 --crypt none --mode fast --nocomp --mtu 1200 --sndwnd 204 --rcvwnd 409 --dscp 46 > /kcptun.log 2 >&1

**Comment by wangyu-** [comment]
>20M的宽带，用KCPTUN下载，下载速度达到900K-1M时观察路由器的下载速度却将近占满带宽了，差不多是真实下载速度的两倍，这是不是用KCPTUN跑不满带宽的原因？

是，这个是直接的原因。因为你传输1M/s的数据时就已经把带宽打满了，自然就无法以更快的速率传输了。

深层的原因可能有：1. cpu不够用，数据处理不过来，造成数据丢失。 2. sndwnd rcvwnd设置不合理，发送速率超过了你的网络运输能力，造成网络拥堵和数据丢失。 3. 网络本身的丢包确实很高，接近一半的包丢了。

对于2，`min(一端的sndwnd,另一端的recvwnd)*MTU*fec倍数/延迟` 应该稍小于`网络带宽`，你检查下你的设置是否满足这个条件。(个人理解，如果说得不对请见谅)(参考Issue: https://github.com/xtaci/kcptun/issues/185 )  (默认的fec倍数貌似是1.3)

具体是哪种情况自己追查一下吧，3的可能性比较小。

**Comment by iceonsun** [comment]
出海带宽小很多。这个值是正常的

**Comment by i258559** [comment]
@wangyu- 测试了下，初步结论是估计和机房线路有关系，Vultr跑可以突破2M+。原因可能是速率超过网络运输能力，因为之前测试的线路是100M总带宽，至于mtu sndwnd rcvwnd设置会继续尝试下。从目前的测试来看，可以得出Kcptun对网路的利用效率是低于tcp。但如果网络环境不好情况下（例如丢包多），kcptun更提供更稳定的速度

**Comment by wangyu-** [comment]
>至于mtu sndwnd rcvwnd设置会继续尝试下

这个非常重要，必须得调好。

>可以得出Kcptun对网路的利用效率是低于tcp

```
		switch config.Mode {
		case "normal":
			config.NoDelay, config.Interval, config.Resend, config.NoCongestion = 0, 40, 2, 1
		case "fast":
			config.NoDelay, config.Interval, config.Resend, config.NoCongestion = 0, 30, 2, 1
		case "fast2":
			config.NoDelay, config.Interval, config.Resend, config.NoCongestion = 1, 20, 2, 1
		case "fast3":
			config.NoDelay, config.Interval, config.Resend, config.NoCongestion = 1, 10, 2, 1
		}
```

kcptun不管是 normal fast fast2 fast3默认都是关闭流控的(要打开流控得用mode manual)。 关闭流控意味着你要靠自己调整好参数来控制发送速率。  tcp的参数是自适应的，不需要你调。 拿没调好参数的kcptun和tcp比，意义不大。

**Comment by i258559** [comment]
@wangyu- 多谢大佬给了新的思路，关于mode manual这部分，我去学习下，再尝试0.0

**Comment by i258559** [comment]
使用mode manual参数测试了下，在LEDE上断流十分严重，连接一会就断了
1、--datashard 30 --parityshard 15 --dscp 46 --nodelay 0 --interval 20 --resend 2 --sockbuf 4194304 --keepalive 10
2、--datashard 30 --parityshard 15 --dscp 46 --nodelay 0 --interval 20 --resend 0 --sockbuf 4194304 --keepalive 10
3、2、--datashard 45 --parityshard 15 --dscp 00 --nodelay 0 --interval 50 --resend 0 --sockbuf 4194304 --keepalive 10

切换 fast 系列，速度正常了- -b，难道这些参数太激进了？mtu sndwnd rcvwnd参数相同的情况

**Comment by kxmp** [comment]
这个我也很郁闷
16年末我就测试过. 虚拟环境.. 不存在网络问题... kcp速度就是上不去...
怪事了!!!
而且默认的1000窗口 就算是200多ms rtt 速度应该也是3.5MBps啊!!!

今天换了新版本 无论怎么弄 速度也是上不去 撑死2-3.xMBps

直接vm跑的 (难道vm兼容性不好么?)

**Comment by kxmp** [comment]
2018-06-15 22:21:34

rtt 50ms kcptun 10MBps
rtt 100ms 6 MBps
rtt 150ms 5MBps 不到
发送端 sndwnd翻倍 速度还一个样

**Comment by kxmp** [comment]
还那样
![2019-01-05_005653](https://user-images.githubusercontent.com/6483602/50700234-0578ac00-1085-11e9-9055-cf253c28507d.png)
这是0ms和200ms的区别
