### ISSUE TITLE
使用后大部分站点都不能打开，google首页偶尔能打开

### ISSUE THREAD

**Issue by doomzhou** [xtaci/kcptun#59]
服务端客户端都报了下面的错误.不知道是不是我参数调整的不对。

2016/07/15 09:05:03 [ERR] yamux: keepalive failed: i/o deadline reached             
2016/07/15 09:05:03 [ERR] yamux: Failed to read header: broken pipe                 

同时ss-client 有部分

2016-07-15 09:09:31 ERROR    [Errno 32] Broken pipe

**Comment by doomzhou** [comment]
看了别人的issue, 把端口改到443, 把sndwnd rcvwnd 都调小,还是同样问题，一个站点，只有 部分请求能响应，其它都会超时。

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Does your ISP or VPS **blocked UDP**?
5. Does your VPS **firewall** allows UDP pass through?
6. Are you using the **same version** for both client & server
7. Did you correctly set the ```-target value, -t value	target server address (default: "127.0.0.1:12948")``` on the server side?

**Comment by doomzhou** [comment]
thanks buddy. all of info list below, if u want more comment it .thakns again .
1. i download from [release](https://github.com/xtaci/kcptun/releases) 07.01 version
2. the **OS** of both side is *Archlinux* with laster kernel
3. both **client and server** have error log .
4. i think  **长城宽带**  should be blocked UDP.
5. VPS side donnot have anything Firewall serveices.
6. Both **client and server** using *kcptun-linux-amd64-20160701.tar.gz*
7. i set the both c and s below , i think itis correctly.
in VPS
 my ssserver:

        listen-bind: 0.0.0.0:18888  
 kcptun-start.sh:

        ./server_linux_amd64 -l :443 -t 127.0.0.1:18888 -key mcd -mtu 1400 -sndwnd 256 -rcvwnd 256 -mode fast2 > kcptun.log 2>&1 &

    in client:

kcptun-start.sh:

        ./client_linux_amd64 -l :12948 -r MY_VPS_IP4:443 -key test -mtu 1400 -sndwnd 128 -rcvwnd 128 -mode fast2 -dscp 46 > kcptun.log 2>&1 &

my sslocal:

      server: 127.0.0.1,
      server_port: 12948

**Comment by xtaci** [comment]
嗯，长宽是不行的。

**Comment by doomzhou** [comment]
这样呀, 那我应该可以把kcptun-client 搬到aliyun主机上
,然后ss-clinet --> kcptun-client(aliyun)。

thanks .

**Comment by xtaci** [comment]
是的，你可以这样做
