### ISSUE TITLE
下载的时候，几秒就断流一次

### ISSUE THREAD

**Issue by pear28** [xtaci/kcptun#593]
2018/05/11 15:12:29 connection: 192.168.1.43:59866 -> x.x.x.x:xxx
2018/05/11 15:12:29 stream opened
2018/05/11 15:12:29 session marked as expired
2018/05/11 15:12:29 session normally closed
2018/05/11 15:12:33 session marked as expired
2018/05/11 15:12:33 connection: 192.168.1.43:59871 -> x.x.x.x:xxx
2018/05/11 15:12:34 session normally closed
2018/05/11 15:12:35 connection: 192.168.1.43:59873 -> x.x.x.x:xxx
2018/05/11 15:12:35 session marked as expired
2018/05/11 15:12:35 session normally closed
2018/05/11 15:12:41 session marked as expired
2018/05/11 15:12:41 connection: 192.168.1.43:57910 -> x.x.x.x:xxx
2018/05/11 15:12:41 session normally closed

是因为GFW  UDP的QOS？
用的是20180316的版本

**Comment by iceonsun** [comment]
QoS时间一般为几分钟

**Comment by KuuDS** [comment]
请不要暴露自己的服务器ip

**Comment by MelanPrince** [comment]
kcptun 下载 Google Drive 文件 和 UFI 下载的时候2-3秒 断流一次 调低   
  "sndwnd": 300,
 "rcvwnd": 400,  下载小文件 有可能能下载下来。

  "autoexpire": 0  依旧。

很久以前的版本 记得调低了 发送和接受 就好了 最近重新 布置  按照以前的配置 依旧断流。 youtube 视频 速度快  但是像 twitter tumblr 很大几率 加载不上整个网页。

**Comment by siwind** [comment]
我用的最新版本: 20181114. 问题仍然有时出现，很让人抓狂。
提示的消息是：
session normally closed
session marked as expired

然后必须要重启kcptun的客户端，不然代理不上。看来程序的稳定性还不够~~

**Comment by xtaci** [comment]
-autoexpire 900
