### ISSUE TITLE
关于负载均衡的一些疑问

### ISSUE THREAD

**Issue by dreamren** [xtaci/kcptun#594]
请问是否有加入负载均衡功能的打算？准确说是防止服务端单点故障的模块？如果没有支持计划，那是否可以用Nginx等工具对多个服务端进行udp负载均衡？我尝试在客户端和服务端之间增加了一个Nginx（部署在客户端机器）对单个服务端进行udp反代，但是却发现不能正常工作，服务端多次出现`broken pipe`，客户端多次出现`session marked as expired`、`session normally closed`等信息，Nginx会出现`110: Connection timed out`错误日志，那么有没有更合适的防止服务端单点故障的方案呢？
另外，希望能加入模拟DNS的混淆加密方式，某些网络下udp53端口下的DNS流量有特殊的用法，实现类似iodine的效果。

**Comment by xtaci** [comment]
packet的lb都有问题，数据包到达顺序会对协议有影响。结构上，应该对tcp层做lb。

**Comment by dreamren** [comment]
我是使用nginx的stream模块做的第四层lb
