### ISSUE TITLE
高RTT速度上不去是为什么呢

### ISSUE THREAD

**Issue by kxmp** [xtaci/kcptun#598]
不知道这个是BUG 还是设计缺陷.

我VM里面跑了 反正到了200ms的rtt 速度就卡的2-3M差不多了.
然而就算把RTT加到400ms. 速度却不会再掉了 是2MBps差不多速度

**Comment by xtaci** [comment]
几个原因
1. 内核drop packet， 调大rmem, mem，看主页
2. cpu速度不行，sendto没法很快，表现为cpu满载

**Comment by kxmp** [comment]
缓存起码都6m起步 不可能不够用吧....
cpu倒是没注意 等会看看去...

**Comment by kxmp** [comment]
我现在用的是 4.9.0-6-amd64这个版本
以前好像是4代内核还没出来 记不清了
就是bbr还没普及的时候 老内核...
估计是那个版本出问题了.

具体也记不太清楚了 后来见到bbr都冒出来了
但是时候还是有bug
具体哪个版本有问题不太清楚 不过肯定是前几个版本.
系统bug真是坑死人啊!!! 或者
net.core我都是手工指定的 默认和最大都是...
绝对不是缓存的问题 也不是cpu问题 
所以一定是内核自己冒了bug!!!

**Comment by kxmp** [comment]
是用vm测的 这软件对vm支持不好么?

**Comment by xtaci** [comment]
vm的 nic adapter driver不是很高效

**Comment by xtaci** [comment]
试下最新版本，修正了一些问题。

**Comment by xtaci** [comment]
窗开大，两端

**Comment by kxmp** [comment]
服务器 snd4096  客户端rcv4096还不够么
和1024一个速度

**Comment by xtaci** [comment]
丢包率测过么

**Comment by xtaci** [comment]
vultr jp在凌晨跑9MB都可以的

**Comment by kxmp** [comment]
你这通道不是抗丢包的么!!!!!
内网能有个什么丢包

**Comment by kxmp** [comment]
> vultr jp在凌晨跑9MB都可以的

你延时多大 tc加到200 和280什么情况.
有速度的话就是vm不行.................
以前vm也出过离奇问题 简直离奇到不可说.

**Comment by jason2000915** [comment]
> > vultr jp在凌晨跑9MB都可以的
> 
> 你延时多大 tc加到200 和280什么情况.
> 有速度的话就是vm不行.................
> 以前vm也出过离奇问题 简直离奇到不可说.

tc的话....把netem的limit调大点好像就行了……不过 还是最好在真实环境下测试 因为qdisc的选择也与速度和重发率有关联
fq模式下丢包（非网络原因）比pfifo_fast下要厉害

**Comment by kxmp** [comment]
> > > vultr jp在凌晨跑9MB都可以的
> > 
> > 
> > 你延时多大 tc加到200 和280什么情况.
> > 有速度的话就是vm不行.................
> > 以前vm也出过离奇问题 简直离奇到不可说.
> 
> tc的话....把netem的limit调大点好像就行了……不过 还是最好在真实环境下测试 因为qdisc的选择也与速度和重发率有关联
> fq模式下丢包（非网络原因）比pfifo_fast下要厉害

limit翻了10倍还是没区别

**Comment by k79e** [comment]
哎呀 现在kvm同样遇到问题了
是1000的rcvwnd 竟然速度只有几百kb!!!! 奇怪的不行 不应该不够用吧.
