### ISSUE TITLE
手动模式能开启公平退让么?

### ISSUE THREAD

**Issue by kxmp** [xtaci/kcptun#599]
> KCP正常模式同TCP一样使用公平退让法则 ......

那我能不能 在开手动模式的时候 也启用这个特性呢?

**Comment by wangyu-** [comment]
应该是`-mode manual -nc 0`

**Comment by kxmp** [comment]
@wangyu- 流控就是公平退让么?
我关了之后感觉kcp快速重传也失效了 根本就不发包.. 跟没用kcp没啥差别..
