### ISSUE TITLE
proxy or not?

### ISSUE THREAD

**Issue by daxiaoming** [xtaci/kcptun#6]

**Comment by xtaci** [comment]
第一，第二是正确姿势，如果是单一tcp connection， 是肯定能连接上的。

短期内不会支持socks，因为目前的socks软件太多了，并且这个功能很敏感。

**Comment by daxiaoming** [comment]
不太明白“如果是单一tcp connection， 是肯定能连接上的，无论什么客户端”？

**Comment by xtaci** [comment]
很简单， 在本地执行ssh -D，kcptun就是承载一条tcp连接
ovpn也是

**Comment by xtaci** [comment]
我再说详细一点:
服务器端:
server -t 127.0.0.1:22 

本地:
client -r "xxx.xxx.xxx.xxx:29900"
ssh -D 8080 ubuntu@127.0.0.1

这样明白？

**Comment by daxiaoming** [comment]
明白了，谢谢

**Comment by xtaci** [comment]
本地的ssh -D 换成你用的Bitvise，连接本地的 kcptun client， 效果是一样的

**Comment by xtaci** [comment]
建议的openvpn配置如下:
$cat /etc/openvpn/client
> remote 127.0.0.1 12948
> dev tun
> ifconfig 172.7.7.2 172.7.7.1
> ;proto udp
> proto tcp-client
> secret /etc/openvpn/static.key
> auth none
> persist-key
> persist-tun
> comp-lzo
> ping 15
> ping-restart 120
> up "/etc/openvpn/up.sh"


$cat /etc/openvpn/server.conf

> dev tun
> local 127.0.0.1
> port 12948
> ifconfig 172.7.7.1 172.7.7.2
> proto  tcp-server
> secret /etc/openvpn/static.key
> auth none
> persist-key
> persist-tun
> comp-lzo
> up "/etc/openvpn/up.sh"
> ping 10
> ping-restart 120

**Comment by jannson** [comment]
首先很羡慕大神，以及大神的项目！
嫌弃配置服务器还得弄个 socks5 代理，所以自己实现了一个自动带有socks5 server 的版本，过来看 issue 发现大神好像愿意接收，所以我也不 pull request 的。仅供大神与其它兄弟参考：
https://github.com/jannson/kcptun/commit/7e4483afa52b2c0657ccf08e190fca3c3bc2e016

没有其它的项目依赖。

**Comment by xtaci** [comment]
嗯，太敏感，我做好加速器就够了，其他自由发挥吧。

**Comment by jannson** [comment]
确实。有道理。

**Comment by xtaci** [comment]
@jannson  -mtu 已经提出

**Comment by jannson** [comment]
谢谢。又回到这里讨论问题了。如果我再支持一个路由器端的透明代理，项目会不会因为火而被 Kill 啊？
路由器上开启，路由器下面的都自动代理了。

**Comment by xtaci** [comment]
good luck
