### ISSUE TITLE
请问-sndwnd -rcvwnd 各代表什么意思？

### ISSUE THREAD

**Issue by Chadwick97** [xtaci/kcptun#60]
你好，由于我的带宽很小，电信下行才8M，使用你的教程搭建后效果反而比直接ss代理更慢。请问-sndwnd -rcvwnd这两项具体代表什么意思？我按照教程说的根据100M等比例缩小client端-sndwnd -rcvwnd数值效果依然不行。将来会换带宽，那么按等比例调节真的有效么？谢谢

**Comment by xtaci** [comment]
8M下行，除掉丢包重传，前向纠错包，是根本不可能支持高清的。
这个窗口表示，在***不丢包的情况下***，有最大-rcvwnd 个数据包在网络上正在往你的ADSL传输
最大-sndwnd往外发送，平均数据包大小可以按照1K一个来算，也就是说，在任意时刻，有 rcvwnd*1K数据流向你。假设rcvwnd = 1024  ，也就是1MB。

这个值在除以ping值(rtt)， 假如400ms， 也就是你想达到的下行带宽是 1MB/0.4s = 2.5MB/s，也就是25Mbps左右。

**Comment by Chadwick97** [comment]
明白了，谢谢

在 2016年7月15日 下午8:00，Daniel Fu <notifications@github.com>写道：

**Comment by mrggbond** [comment]
上传下载都是100M的光纤,感觉两参数1024 2048 3072都差不多,没明显区别

**Comment by xtaci** [comment]
这种情况，一般是服务器到达带宽瓶颈了。

**Comment by wang20150419** [comment]
要是有一个工具，用于优化配置参数就好了。

**Comment by xtaci** [comment]
链路品质（丢包率）是未知数。
