### ISSUE TITLE
安卓版tumblr导致服务器kcptun断流后内存飙升

### ISSUE THREAD

**Issue by sqwwqw5** [xtaci/kcptun#602]
最新版20180316版本
参数-mode fast2 -sndwnd 1024 -rcvwnd 1024(client,server相同)
只有从Play store安装的安卓版tumblr有此问题，网页版和ios版均无此问题。
表现为tumblr使用到一半突然断流，任何连上此kcptun的设备都无法使用代理，服务器Kcptun的此时内存用量正常。半分钟后断流恢复，但是从此时起任何流量会导致服务器Kcptun内存上升直到进程被杀掉。

所有设备使用任何其他服务（youtube,网页浏览,twitch）均不会导致这个问题，内存稳定在20M使用。

已尝试关闭FEC,更换mode模式,调整窗口大小,均未能解决此问题。
再次说明一下,只有安卓版tumblr（从playstore下载的最新版）会导致此问题。

PS:版本为11.0.0.00
PS2:问题肯定是出在tumblr的app上，既然其他应用都没问题。只是shadowsocksr的内存并没有因此升高，而只出现在kcptun上...
PS3:已在两台VPS上测试过，一台只有64MB,另一台有768MB和768SWAP空间。两台均出现断流和内存上升问题，64MB的VPS会内存上升直到KCPTUN崩溃。768MB的VPS虽然不会崩溃，但是内存还是会随着断流上升，且不会变小。

**Comment by keeno1982** [comment]
@sqwwqw5 我也是一样的，应该是安卓没法关闭视频自动播放导致，如果IOS没有关闭视频自动播放也是一样的，可能是同时请求的数据太多，这个跟Youtube APP点中间的订阅内容一样，订阅的东西太多，一点开，Kcptun马上断流，只是这个问题不知道怎么解决
