### ISSUE TITLE
有小伙伴遇到间歇性broken pipe的么？

### ISSUE THREAD

**Issue by alienwaredream** [xtaci/kcptun#603]
客户端与服务端没有任何变化，近期突然出现闲置一段时间突然使用或者用着用着突然断流。
查看服务端会有broken pipe日志，并在1-2min后重连
2018/06/28 03:22:59 stream closed
2018/06/28 03:23:53 stream opened
2018/06/28 03:25:20 broken pipe
2018/06/28 03:25:20 stream closed
2018/06/28 03:25:20 stream closed
2018/06/28 03:25:20 stream closed
2018/06/28 03:27:34 remote address: XXXXXX:45436
2018/06/28 03:27:35 stream opened
2018/06/28 03:27:35 stream opened

客户端日志
2018/06/28 10:56:04 stream opened
2018/06/28 10:56:04 stream closed
2018/06/28 11:00:10 session marked as expired
2018/06/28 11:00:10 connection: 10.10.XXXX:47862 -> XXXXX:5020
2018/06/28 11:00:10 stream opened
2018/06/28 11:00:10 stream closed
2018/06/28 11:00:10 session normally closed
2018/06/28 11:00:54 stream opened
2018/06/28 11:00:54 stream closed

请问各位有遇到同样情况么？是配置问题、程序问题、还是ISP问题？？ 谢谢~

**Comment by iceonsun** [comment]
有可能是udp被封。断的时候，看看还能不能Telnet或者ping。如果不能，就可以肯定是被封

如果是udp被封，可以给kcptun再套一层皮。https://github.com/iceonsun/rsock

**Comment by wangyu-** [comment]
《低延时游戏场景broken pipe》https://github.com/xtaci/kcptun/issues/560

**Comment by xtaci** [comment]
-autoexpire 900
