### ISSUE TITLE
RT5350 使用 MIPSLE 无法运行?

### ISSUE THREAD

**Issue by nickfox-taterli** [xtaci/kcptun#605]
root@OrayPh:~# ./client_linux_mipsle -h

[没有任何输出]

root@OrayPh:~# cat /proc/cpuinfo 
system type		: Ralink RT5350 id:1 rev:3
machine			: Oray PhStick v1(16M)
processor		: 0
cpu model		: MIPS 24KEc V4.12
BogoMIPS		: 239.61
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp
shadow register sets	: 1
kscratch registers	: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

root@OrayPh:~#

**Comment by xtaci** [comment]
fixed softfloat
