### ISSUE TITLE
求问为什么日志里都是 stream opened 和 stream closed

### ISSUE THREAD

**Issue by wyfang** [xtaci/kcptun#607]
只有在连接的一瞬间有不一样的信息，然后都是stream opened 和 stream closed，如果都是这两个信息，完全没必要刷屏啊，再有就是这个日志可以修改最大记录量吗？记录好几天，这会不会对硬盘还是内存不好呢？

**Comment by iMocW** [comment]
1、你艹不坏内存。
2、仔细看用法可以禁用。
3、请关闭这个issue。

**Comment by wxjeacen** [comment]
哈哈哈，这回复精辟。
