### ISSUE TITLE
使用kcp后，流入与流出量差3倍..参数应该如何调整？

### ISSUE THREAD

**Issue by JMVoid** [xtaci/kcptun#609]
我在aliyun hk架的ssr , 后来加了kcptun. 使用的模式是fast2
服务端使用：./server_linux_amd64 -t 47.52.**.***:6800 -l :7000 -mode fast2
客户端使用：client_windows_amd64.exe -r "47.52.**.***:7000" -l ":7000" -mode fast2
去测试下载一个270M的文件前, 用vnstat -d 查看,
         day         rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     07/24/2018   329.19 MiB |  841.15 MiB |    1.14 GiB |  110.97 kbit/s
     07/25/2018   316.05 MiB |  976.59 MiB |    1.26 GiB |  302.93 kbit/s
     ------------------------+-------------+-------------+---------------
下载后，用vnstat -d查看:
         day         rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     07/24/2018   329.19 MiB |  841.15 MiB |    1.14 GiB |  110.97 kbit/s
     07/25/2018   531.32 MiB |    1.64 GiB |    2.16 GiB |  514.16 kbit/s
     ------------------------+-------------+-------------+---------------
流入约为220M, 比下载的文件小40M
但是流出量达700M. 比原来数据大小大了三倍。感觉这个数据浪费跟理论值差距有点大。请问应该怎么调整参数？

**Comment by nxtreaming** [comment]
阿里云香港大陆访问是CN2，速度比较稳定（30ms, 丢包率极低），建议直接访问，不要用KCP。
-----------------------------------------
Productive. Reliable. Fast.

**Comment by JMVoid** [comment]
已翻看前面的issue.感觉3倍还是合理的。我使用kcptun是因为该机已经被tcp干扰。udp还是正常的。因此转用kcptun来使用。多谢了。该issue关闭
