### ISSUE TITLE
发现一款号称比KCP协议更高效的UDP传输协议

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#610]
@xtaci 一起研究研究？

https://github.com/dragonite-network/dragonite-java

![image](https://user-images.githubusercontent.com/17328315/43534645-7ae9f7b6-95ea-11e8-8057-dfd92dd53eae.png)

**Comment by openertech** [comment]
从它的协议pdf看，比起kcp来，基本没有什么本质性的提高。
它的协议优势应该是更加简洁了，基本抓住了长距离传输中丢包与检测丢包的核心问题。
它砍去了kcp中很多没用的东西，毕竟kcp出现的早，当年应该也是加了很多实验性的东西，所以参数特别多。

总之，整个协议，应该不会有比kcp更强的地方。不过使用的人应该更加一目了然，更明白核心问题在哪里！


bettermanbao <notifications@github.com> 于2018年8月2日周四 上午12:25写道：

**Comment by zhanhb** [comment]
Java的，内存占用太多

**Comment by xtaci** [comment]
@bettermanbao 文档没看到什么创新啊，只是一个ARQ， FEC没有看到。

**Comment by birdofprey** [comment]
JAVA已死

**Comment by bettermanbao** [comment]
@xtaci 
用户层面来说，dragonite有一点做的还是比kcp人性化的。就是dragonite设定的是最大带宽，kcp设定的是最大窗口。设定带宽明显比设定窗口更人性化啊。

**Comment by xtaci** [comment]
@bettermanbao 这个就是帮用户计算一下wnd*mtu，我为了保持参数的兼容而已。

**Comment by wangyu-** [comment]
@bettermanbao 

>用户层面来说，dragonite有一点做的还是比kcp人性化的。就是dragonite设定的是最大带宽，kcp设定的是最大窗口。设定带宽明显比设定窗口更人性化啊。

我也感觉设定最大带宽更人性化一些。

@xtaci  

>@bettermanbao 这个就是帮用户计算一下wnd*mtu，我为了保持参数的兼容而已。

貌似实际上是帮用户算一下wnd*mtu/rtt (参考：https://github.com/xtaci/kcptun/issues/185 )。 在国际网络上rtt会变，感觉还是设定最大带宽适用性更强一些呀。

比如在一个中国到美西的网络上rtt 200ms，我算出了一个合适的sndwnd和rcvwnd一直用着。突然遇到线路抽风，rtt变成了350ms(感觉挺常见的，可能会持续很久)，之前算好的sndwnd和rcvwnd就不再适用了。

**Comment by bettermanbao** [comment]
期待 @xtaci 增加sndbw和rcvbw参数，默认为0，即不生效，仍然以sndwnd和rcvwnd为准。如果不为0，则以sndbw和rcvbw实时控制窗口。

**Comment by xtaci** [comment]
@bettermanbao 很难

**Comment by Remonli** [comment]
Java 要装JRE,占内存太多, 还没办法进路由器.

**Comment by xtaci** [comment]
用最新版，速度我觉得不会慢
