### ISSUE TITLE
How to multiplex?

### ISSUE THREAD

**Issue by syadnom** [xtaci/kcptun#612]
I'm not able to find the documentation on how to use kcptun's multiplexing capabilities.  I would like to use multiple WAN connections.

**Comment by xtaci** [comment]
-conn N

**Comment by n-zhang-hp** [comment]
@xtaci is there anyway to set which interfaces to use for multiple WAN connections? For example, if I have eth0 and eth1, can I specify 2 UDP connections with one on eth0 and the other on eth1 to combine bandwidth of both?

**Comment by xtaci** [comment]
@n-zhang-hp this scenario is simple, just run 2 instance of kcptun, and listen to eth0 and eth1 address.

**Comment by xtaci** [comment]
and using a haproxy to do a round-robin
