### ISSUE TITLE
kcp的20180810版本windows客户端上行流量异常

### ISSUE THREAD

**Issue by usister** [xtaci/kcptun#613]
windows10下kcp 20180810版本存在异常上载，使用一段时间后会有数兆的上行流量。这是在关掉所有浏览器，且shadowsocks客户端没有流量通过的情况下，确认为kcp客户端自己产生的流量。
发现过程是后台开着chrome，视频是暂停状态，游戏里非常卡。然调出流量监测软件看到kcp有数M的上行流量，该现象很敏感，请重视。

**Comment by xtaci** [comment]
这是不可能的哈

**Comment by myGod0rz** [comment]
我遇到过类似的下行异常，4G差点跑飞。。重启都不行。。待我再次遇到后仔细观测下。
