### ISSUE TITLE
Performance regression on latest build

### ISSUE THREAD

**Issue by erpalma** [xtaci/kcptun#618]
I noticed a major performance reduction starting from `561ee05`. In particular up to this commit (included) I get about 7.8 MB/s of actual bandwidth with about 0.9 MB/s of overhead. On latest version instead, I get about 3,5/4 MB/s bandwidth with about 4.5 MB/s overhead. The settings, hosts and the benchmark (http file download) are the same among tests.

This is my client config, the server one is almost identical: 
`--crypt salsa20 --key xxx -l 0.0.0.0:8080 --rcvwnd 8192 --mode normal --conn 3 --dscp 0 --nocomp --ds 0 --ps 0`

**Comment by xtaci** [comment]
try lower the sndwnd & rcvwnd, it seems too big.

**Comment by erpalma** [comment]
Actually I've experimented a bit and these are the best settings for my connection. Lowering the rcvwnd (client) below 4096 (and sndwnd below 8192 on server) drastically reduce the performance.

**Comment by xtaci** [comment]
it looks too big to me, my wnd never exceeds 1024

**Comment by xtaci** [comment]
and you should try to set ds & ps

**Comment by erpalma** [comment]
I agree, it seems high also to me but with a 512/1024 window I get only about 5/6 MB/s. Similarly with ds/ps I get much higher overhead. Notice that my link is not lossy, I use kcptun to overcome some network congestion issues I get in the evening in my area.
