### ISSUE TITLE
使用的是一键安装，还是错误 yamux: keepalive failed: i/o deadline reached

### ISSUE THREAD

**Issue by vipxlm** [xtaci/kcptun#62]
服务端应该是正常的
[root@localhost ~]# /etc/init.d/kcp-server status
kcp-server (pid 1628) is running...
udp        0      0 127.0.0.1:20588             0.0.0.0:*                               1628/kcp-server 

客户端用的是
client_windows_amd64.exe -c client.json

但是还是报错

2016/07/16 21:35:21 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/16 21:35:21 [ERR] yamux: Failed to read header: broken pipe

**Comment by vipxlm** [comment]
用的是搬瓦工的服务器

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Does your ISP or VPS **blocked UDP**?
5. Does your VPS **firewall** allows UDP pass through?
6. Are you using the **same version** for both client & server
7. Did you correctly set the ```-target value, -t value	target server address (default: "127.0.0.1:12948")``` on the server side?

**Comment by vipxlm** [comment]
1. Are you using the latest release?
yes
2. Which OS do you use?
CentOS 6.5  64位
3. Which end for this issue related to, client or server?
client报错
4. Does your ISP or VPS blocked UDP?
我不知道是否支持UDP，用的是搬瓦工
5. Does your VPS firewall allows UDP pass through?
我不知道是否支持UDP，用的是搬瓦工
6. Are you using the same version for both client & server
是最新的
7. Did you correctly set the -target value, -t value target server address (default: "127.0.0.1:12948") on the server side
地址和端口没有问题

**Comment by xtaci** [comment]
你使用的哪家的网络？电信，联通？

**Comment by vipxlm** [comment]
上海联通的网络

**Comment by xtaci** [comment]
我不清楚这个一键安装的脚本是否正确，你可以尝试问问作者， 联通肯定能通。

**Comment by vipxlm** [comment]
谢谢，我是根据这篇帖子来设置的：http://koolshare.cn/thread-45462-1-1.html

**Comment by fcymk2** [comment]
我也有这个问题, 有时候出现, 过一段时间又恢复了
出问题的时候 直接连接ss是能正常工作的

**Comment by hardfish82** [comment]
+1，我也是类似的情况。我是电信的宽带。
