### ISSUE TITLE
加速不明显

### ISSUE THREAD

**Issue by jnxyatmjx** [xtaci/kcptun#620]
问问题前先搜索ISSUE，并搞清楚下面的问题:

1. 检查 ```-key xxx``` 至少三遍, ***保证***两边一致。
2. 保证```-nocomp, -datashard, -parityshard,  -key, -crypt```两边一致。
3. 是否在服务器端，正确设定了转发的目标服务器地址 ***--target***。
4. 如果第3条不确定，尝试在服务器上telnet target port试试。
5. 防火墙是否关闭了UDP通信。
6. 两端的版本是否一致？
7. 是不是最新版本？
8. 两端分别是什么操作系统？
9. 两端的输出日志是什么？

Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

服务端是用Goole云的Debain 9。客户端用Win 10 64位。版本号都是 20181002 。按照网上配置好后，已联通，但是通过YouTube测速发现，网络速度不但没有提升反而降速不少？是我哪里配置的不对吗？
{
  "listen": ":10888",
  "target": "127.0.0.1:10777",
  "key": "密码",
  "crypt": "none",
  "mode": "fast3",
  "mtu": 1350,
  "sndwnd": 512,
  "rcvwnd": 512,
  "datashard": 10,
  "parityshard": 3,
  "dscp": 0,
  "nocomp": false,
  "quiet": false,
  "pprof": false
}

**Comment by bpplpp** [comment]
mode fast2 -nocomp -dscp 46 -mtu 1350 -crypt salsa20 -sndwnd 204 -rcvwnd 1024 -datashard 0 -parityshard 0 这个试试，我用了1年多

**Comment by bpplpp** [comment]
"quiet": false,
"pprof": false

这两个没用过。

**Comment by jnxyatmjx** [comment]
> 个试试，我用了1年多
好的 我试试

**Comment by jnxyatmjx** [comment]
> mode fast2 -nocomp -dscp 46 -mtu 1350 -crypt salsa20 -sndwnd 204 -rcvwnd 1024 -datashard 0 -parityshard 0 这个试试，我用了1年多

用这个加速效果真的很明显嘛？网速能提高多少倍？

**Comment by bpplpp** [comment]
个人感觉：保守加速提高了一倍。

**Comment by jnxyatmjx** [comment]
> 个人感觉：保守加速提高了一倍。

你用的网络分别是哪家ISP ？？

**Comment by keeno1982** [comment]
@bpplpp parityshard这个值默认是3，改成0有什么好处吗？

**Comment by bpplpp** [comment]
@jnxyatmjx 
BWG

@keeno1982 
![image](https://user-images.githubusercontent.com/15948273/46794715-026a6a00-cd7b-11e8-8fb3-11a659066177.png)

你去看看前向纠错哪里吧，具体没研究太多。

**Comment by hktalent** [comment]
> > mode fast2 -nocomp -dscp 46 -mtu 1350 -crypt salsa20 -sndwnd 204 -rcvwnd 1024 -datashard 0 -parityshard 0 这个试试，我用了1年多
> 
> 用这个加速效果真的很明显嘛？网速能提高多少倍？

没效果
