### ISSUE TITLE
请问低丢包网络，是否需要使用 kcptun 呢？只考虑响应时间，不考虑带宽

### ISSUE THREAD

**Issue by hq5544** [xtaci/kcptun#622]
我目前使用的搬瓦工，用本地和在线的 ping 工具看，都是 0 丢包，请问我测试的方式对吗？

如果真的是 0 丢包，那么请问我需要使用 kcptun 吗？只考虑使用 google 搜索能快点，部考虑 YouTube 看高清视频。

**Comment by bpplpp** [comment]
普通搜索足够用了

**Comment by PonyTang3** [comment]
延迟还是会改善很多。最关键是速度加速很多，网页秒开

**Comment by PonyTang3** [comment]
> 我用的是某国内比较火的vps，美国机房，本地电信没有丢包，因为G口带宽足够所以我发包加得比较大，打开视频加速非常明显。但是问题是我本地200M的带宽如果不加kcptun下载可以跑满带宽，按我的配置下载只能达到100M，不知道是我参数配置的问题还是达到低延迟必须付出的代价。。。不过还是用得很爽。。。

这个就是用超发了改善延迟的，所以实际速度会是带宽的一半
