### ISSUE TITLE
关于不同系统版本的问题

### ISSUE THREAD

**Issue by xiebruce** [xtaci/kcptun#623]
其实绝大多数人，都是用mac/win客户端+linux服务器端，而你发布的版本，都是服务器端与客户端一起的，比如kcptun-darwin-amd64-20170718.tar.gz，客户端和服务器端都是darwin，我感觉服务器端的darwin应该是用不到的吧？
<img width="247" alt="xnip2018-10-13_00-06-04" src="https://user-images.githubusercontent.com/13575500/46880709-fdd9aa80-ce7b-11e8-8b9f-9ad209639d14.png">
而如果我下载linux版本，两个都是linux，但事实上，一般人用不到linux版的客户端(当然肯定也有不是一般人会用到)，可能你打包的时候确实是只能这么打的，但是我现在有点不太明白，比如我是mac，然后服务器是centos，都是64位，那我就选client_darwin_amd64+server_linux_amd64 这样么？这两个版本是否是最佳对应的呢？可是我下载的[shadowsocks-NG](https://github.com/shadowsocks/ShadowsocksX-NG/releases)又自带一个kcp，有点不是很明白，我是该用这个client_darwin_amd64去替换掉shadowsocks-NG自带的那个么？

**Comment by Originalimoc** [comment]
This is not an issue. Don't use issue section as forum.
