### ISSUE TITLE
源码问题：KCPTUN封装tcp时不需要解析吗？是直接把tcp封装到了kcp的包头里面吗？

### ISSUE THREAD

**Issue by littlezho** [xtaci/kcptun#626]
由于对go语言不是很精通，所以读了源码之后还是不理解KCP是如何用udp来封装TCP的，据我所理解的代码，KCP是用了24字节的头来封装的，但这24字节中并没有真正的dest ip与dest port，但我们发到远程服务器后，远程服务器解包KCP，并能把这个tcp包发到正确的dest ip主机。
所以我想这里面应该不止24字节的KCP头才对，有人能告知一下KCP封装tcp的包结构在哪看吗？
非常感谢！！！

**Comment by xtaci** [comment]
不是封装的tcp protocol， 是封装的流， 流式的都能传输，比如socks协议

**Comment by littlezho** [comment]
> 不是封装的tcp protocol， 是封装的流， 流式的都能传输，比如socks协议，在这个特定用法下，有dest ip, dest port

非常感谢您的回复，对我很有帮助！

**Comment by littlezho** [comment]
> 不是封装的tcp protocol， 是封装的流， 流式的都能传输，比如socks协议，在这个特定用法下，有dest ip, dest port
