### ISSUE TITLE
如何用kcptun对ss多个端口同时进行加速？

### ISSUE THREAD

**Issue by BeepWalker** [xtaci/kcptun#629]
自己的VPS上用shadowsocks给多人分别配置了不同端口，如何配置可以实现多端口分别kcptun加速？

**Comment by weichao234** [comment]
兄弟我也遇到这个问题了 我的问题是不同端口不同IP 目前没办法解决.
多端口的话你创建了以后,用./kcptun.sh add 增加一个实例 然后KCP的端口不要和你设置的第一个端口一样就行了,我试过可以的,但是要是不同的IP就不行了.
