### ISSUE TITLE
不定时断流，必须重启后才能恢复

### ISSUE THREAD

**Issue by pigpigabc123** [xtaci/kcptun#632]
OpenWrt 18.06.1 ，kcp版本：20181002 ，现象：不定时（几个小时）断流，必须重启kcptun或路由才能恢复。
client日志：
只有“ stream opened”。
重启后 “stream opened”、“stream closed”都有，恢复正常。

**Comment by amosbird** [comment]
同样的问题，必须重启server才能重连上

**Comment by actg** [comment]
同样的问题，最新的版本，经常自动崩溃，没有任何log信息，很是郁闷，go写的代码这么烂？

**Comment by bpplpp** [comment]
去年就遇到过，也许是udp封锁的问题？

**Comment by actg** [comment]
最新版本经常莫名其妙崩溃，无声无息，也不想费劲研究他代码细节了，显然是go写的东西不怎么稳定，最后弄了个monit自动监控自动重启好了，supervisor的Python太烂，耗费内存flash

**Comment by c2h2** [comment]
ubuntu 也有这问题，有没有办法做个watchdog？

**Comment by c2h2** [comment]
https://gist.github.com/c2h2/fd4729b7d33972bad24949d2bf741265 写个script, 目前自动每小时重启下。。

**Comment by xtaci** [comment]
-autoexpire 300

**Comment by c2h2** [comment]
> -autoexpire 300

好的

**Comment by ykfq** [comment]
断流不是 kcptun 的锅，是运营商封锁较大的 udp 流量。
因为我在家里正常用，在公司就5分钟断开，后来使用 udp2raw 转换后，就能愉快的上网了。

**Comment by Skura23** [comment]
我的也经常断流, 不知道为什么
