### ISSUE TITLE
EarlyRetransSegs(30%~40%)高是怎么回事?

### ISSUE THREAD

**Issue by timrobins2018** [xtaci/kcptun#633]
最近在看一些参数优化方面的帖子并作测试,发现客户端的RepeatSegs很高,服务端RetransSegs和EarlyRetransSegs都很高,LostSegs稍高,其中EarlyRetransSegs/OutSegs基本上在30%左右,高的时候40+%,看了下相关的issues好像都没这么高.
   测试环境是gcp的虚机+树莓派:不管是看视频还是拉文件都是差不多的情况.
   下面是服务端的配置,客户端基本相同
    "crypt": "salsa20",
    "mode": "manual",
    "conn": 1,
    "autoexpire": 300,
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 256,
    "datashard": 0,
    "parityshard": 0,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 50,
    "resend": 0,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
     看了下代码,早重传的引发是由fastack>0 且 newSegsCount == 0造成的,而newSegsCount == 0 只有在length(snd_queue) == 0的情况下发生,也就是服务端已经没有data数据可发的情况,这种情况对于文件传输似乎只有的文件传输完成的时候才会发生,而视频由于是分次缓存,就我的理解似乎也只有在每一次结束缓存的时候才可能发生,但占比肯定没这么高.于是我对为何造成这么多的早重传有点想不通了.我对网络传输只是一知半解,不知我这样的理解对不对?希望能共同探讨. 感谢~

**Comment by timrobins2018** [comment]
自己补充下:看了下代码,发现忘了窗口限制的问题,造成上述情况应该是接收端窗口已经满了造成,此时如果开启拥塞控制(nc=1),实际测速会比不开nc下降约九成!看来是很高的丢包率/拥塞造成的,个人推测在这种情况下(尤其是在看视频的时候),让发送端超时重传可能会比早重传能耗费更低的RepeatSegs,待有空测试下.
   另外,使用https://github.com/wangyu-/UDPping测试了下udp丢包率,并不高(个位数),很奇怪.

**Comment by jason2000915** [comment]
nc =1 好像是关闭拥塞 我测试的开启快速重传（resend = 2）总共重传的包的数量反而比不开快速重传的包要少，而且响应速度也更快

似乎Repeat Segs主要是因为延迟抖动造成的 觉得这种情况下调低interval让kcp loop快一点可能有改善（直接上fast3也成）？（也看到过调高interval的说法，让kcp对抖动不敏感，具体测试下吧？）

**Comment by timrobins2018** [comment]
是的,nc=1代表关闭拥塞控制,原文已修改. 今天测试设置:resend = 2,EarlyRetransSegs略有减少,FastRetrans:EarlyRetransSegs=1:3左右,总体上RepeatSegs并没怎么减少,这也符合逻辑.看来只要关闭拥塞窗口,重复包就会蹭蹭往上窜.
另外:今天调整了interval:20,50,100都试过,对重复包占比的影响不大,但interval过高(100时)会影响视频传输速率.
总体而言:在抖动明显的情况下,fastRetrans/FEC/EarlyRetrans是三种不同的解决机制,个人感觉EarlyRetrans最激进,FEC一旦设定好无法根据网络状况自适应.fastRetrans似乎相对最智能些.当然,以上仅仅是个人感受.

**Comment by jason2000915** [comment]
> 是的,nc=1代表关闭拥塞控制,原文已修改. 今天测试设置:resend = 2,EarlyRetransSegs略有减少,FastRetrans:EarlyRetransSegs=1:3左右,总体上RepeatSegs并没怎么减少,这也符合逻辑.看来只要关闭拥塞窗口,重复包就会蹭蹭往上窜.
> 另外:今天调整了interval:20,50,100都试过,对重复包占比的影响不大,但interval过高(100时)会影响视频传输速率.
> 总体而言:在抖动明显的情况下,fastRetrans/FEC/EarlyRetrans是三种不同的解决机制,个人感觉EarlyRetrans最激进,FEC一旦设定好无法根据网络状况自适应.fastRetrans似乎相对最智能些.当然,以上仅仅是个人感受.
> 
> 另外,请教@jason2000915 用iperf3 测丢包的具体参数,谢谢.
> 
> 附上一个命令,方便查看重复包的具体状况:
> 使用方法:开启snmp log功能,然后在snmp(假定log名为snmp.log)日志所在目录运行即可.
> cat snmp.log|awk -F "," '{printf ("OutSegs: %6d |RetransSegs: %6d |FastSegs: %6d |EarlySegs: %6d |LostSegs: %6d |RepeatSegs: %3d |(FastSegs/OutSegs): %0.2f |(EarlySegs/OutSegs): %0.2f |(LostSegs/OutSegs): %0.2f \n",$14, $17, $18,$19,$20,$21,$18/$14,$19/$14,$20/$14)}'

谈不上请教hhhhh

iperf3应该是
iperf3 -c 服务器ip -p 端口 -R -u -b 50M(换为你想要的服务端发包带宽大小)

如果想测上传-R去掉就成 必要时候可以用 -l 参数限制包长度 单位为byte

**Comment by jason2000915** [comment]
> > 是的,nc=1代表关闭拥塞控制,原文已修改. 今天测试设置:resend = 2,EarlyRetransSegs略有减少,FastRetrans:EarlyRetransSegs=1:3左右,总体上RepeatSegs并没怎么减少,这也符合逻辑.看来只要关闭拥塞窗口,重复包就会蹭蹭往上窜.
> > 另外:今天调整了interval:20,50,100都试过,对重复包占比的影响不大,但interval过高(100时)会影响视频传输速率.
> > 总体而言:在抖动明显的情况下,fastRetrans/FEC/EarlyRetrans是三种不同的解决机制,个人感觉EarlyRetrans最激进,FEC一旦设定好无法根据网络状况自适应.fastRetrans似乎相对最智能些.当然,以上仅仅是个人感受.
> > 另外,请教@jason2000915 用iperf3 测丢包的具体参数,谢谢.
> > 附上一个命令,方便查看重复包的具体状况:
> > 使用方法:开启snmp log功能,然后在snmp(假定log名为snmp.log)日志所在目录运行即可.
> > cat snmp.log|awk -F "," '{printf ("OutSegs: %6d |RetransSegs: %6d |FastSegs: %6d |EarlySegs: %6d |LostSegs: %6d |RepeatSegs: %3d |(FastSegs/OutSegs): %0.2f |(EarlySegs/OutSegs): %0.2f |(LostSegs/OutSegs): %0.2f \n",$14, $17, $18,$19,$20,$21,$18/$14,$19/$14,$20/$14)}'
> 
> 谈不上请教hhhhh
> 
> iperf3应该是
> iperf3 -c 服务器ip -p 端口 -R -u -b 50M(换为你想要的服务端发包带宽大小)
> 
> 如果想测上传-R去掉就成 必要时候可以用 -l 参数限制包长度 单位为byte

其实给kcptun发送一个USR1信号也能dump SNMP信息噢 而且带标识的hhhhhh（没有打脸的意思23333）

**Comment by jason2000915** [comment]
> 是的,nc=1代表关闭拥塞控制,原文已修改. 今天测试设置:resend = 2,EarlyRetransSegs略有减少,FastRetrans:EarlyRetransSegs=1:3左右,总体上RepeatSegs并没怎么减少,这也符合逻辑.看来只要关闭拥塞窗口,重复包就会蹭蹭往上窜.
> 另外:今天调整了interval:20,50,100都试过,对重复包占比的影响不大,但interval过高(100时)会影响视频传输速率.
> 总体而言:在抖动明显的情况下,fastRetrans/FEC/EarlyRetrans是三种不同的解决机制,个人感觉EarlyRetrans最激进,FEC一旦设定好无法根据网络状况自适应.fastRetrans似乎相对最智能些.当然,以上仅仅是个人感受.
> 
> 另外,请教@jason2000915 用iperf3 测丢包的具体参数,谢谢.
> 
> 附上一个命令,方便查看重复包的具体状况:
> 使用方法:开启snmp log功能,然后在snmp(假定log名为snmp.log)日志所在目录运行即可.
> cat snmp.log|awk -F "," '{printf ("OutSegs: %6d |RetransSegs: %6d |FastSegs: %6d |EarlySegs: %6d |LostSegs: %6d |RepeatSegs: %3d |(FastSegs/OutSegs): %0.2f |(EarlySegs/OutSegs): %0.2f |(LostSegs/OutSegs): %0.2f \n",$14, $17, $18,$19,$20,$21,$18/$14,$19/$14,$20/$14)}'

作者关于interval和rtt的说法：
https://github.com/xtaci/kcptun/issues/251#issuecomment-266653433
可能在你的环境下不是因为抖动而造成的误判 我加大interval有一点效果 不过很难找平衡点 速度慢是肯定的

**Comment by jason2000915** [comment]
你可以试试减小sockbuf

我在最新的版本（1124）把buffer大小减小到1782580 byte错误重传几乎没有了（4w个segs里就400重传） 速度能稳定在40Mbits/sec左右 20%的overhead
感觉是bufferbloat的问题 减小socket buffer大小以后kcp内部rto也正常了，不修改默认4MB rto会出奇的高 
 retransSegs也飙升（开了acknodelay 为了减小rtt获取误差）

sockbuf和sndwnd需要配合起来调 观察内部rto值为参考（BBR自动干的活现在手动干了=_=）

我再增加buffer或者窗口都会导致重复包和重传率飙升 怀疑是其他地方（send或者recv效率）有性能问题
也希望xtaci大大帮忙看下？

**Comment by timrobins2018** [comment]
@jason2000915 按照你的建议修改了buffsize=1782580 以及作者建议的:
net.core.rmem_max=26214400
net.core.rmem_default=26214400
net.core.wmem_max=26214400
net.core.wmem_default=26214400
net.core.netdev_max_backlog=2048
重传没有明显减少,总共约50%的RetransSegs,FastSegs:EarlySegs=1:3的样子.

**Comment by xtaci** [comment]
用最新的版本试试，消除了一些程序抖动
