### ISSUE TITLE
Feature request: TCP/UDP port reuse

### ISSUE THREAD

**Issue by PantherJohn** [xtaci/kcptun#636]
I spot this repo on GitHub. https://github.com/libp2p/go-reuseport

It’s quite possible that `SO_REUSEPORT` can be used in golang.

**Comment by xtaci** [comment]
what is this good for?

**Comment by PantherJohn** [comment]
@xtaci This is particularly useful if users have multiple backend servers. Allowing multiple processes to bind to the same port/addr this is basically kernel-level load balancing. Note that `haproxy` is not an option here since I need not just TCP but also UDP, and anyway it’s still a bit sketchy adding a proxy intercepting loopback traffic.

**Comment by PantherJohn** [comment]
#631

**Comment by PantherJohn** [comment]
@xtaci any ideas?

**Comment by xtaci** [comment]
no idea how to use that
