### ISSUE TITLE
Feature request: JSON config parser before argument parser!

### ISSUE THREAD

**Issue by PantherJohn** [xtaci/kcptun#638]
@xtaci It's quite illogical to implement command line argument parsing before calling config parsing func and especially annoying when it comes to SIP003 (shadowsocks plugin) scripting. For flexibility I suggest you change the config parsing sequence a bit. Client impl ([`arg`](https://github.com/xtaci/kcptun/blob/master/client/main.go#L243)|[`conf`](https://github.com/xtaci/kcptun/blob/master/client/main.go#L271)), for instance, should be like this in case `parseJSONConfig()` would not overwrite all arguments passed to the main program
```
// ... lines of code .... (Line 243)
		config := Config{}
		if c.String("c") != "" {
			err := parseJSONConfig(&config, c.String("c"))
			checkError(err)
		}

		config.LocalAddr = c.String("localaddr")
		config.RemoteAddr = c.String("remoteaddr")
		config.Key = c.String("key")
		config.Crypt = c.String("crypt")
		config.Mode = c.String("mode")
		config.Conn = c.Int("conn")
		config.AutoExpire = c.Int("autoexpire")
		config.ScavengeTTL = c.Int("scavengettl")
		config.MTU = c.Int("mtu")
		config.SndWnd = c.Int("sndwnd")
		config.RcvWnd = c.Int("rcvwnd")
		config.DataShard = c.Int("datashard")
		config.ParityShard = c.Int("parityshard")
		config.DSCP = c.Int("dscp")
		config.NoComp = c.Bool("nocomp")
		config.AckNodelay = c.Bool("acknodelay")
		config.NoDelay = c.Int("nodelay")
		config.Interval = c.Int("interval")
		config.Resend = c.Int("resend")
		config.NoCongestion = c.Int("nc")
		config.SockBuf = c.Int("sockbuf")
		config.KeepAlive = c.Int("keepalive")
		config.Log = c.String("log")
		config.SnmpLog = c.String("snmplog")
		config.SnmpPeriod = c.Int("snmpperiod")
		config.Quiet = c.Bool("quiet")
// ... lines of code .... (Line 274)
```
I don't know if you've noticed the difference, but the one I proposed obviously follows more logic.

**Comment by PantherJohn** [comment]
Those are the projects we are working on

https://github.com/w1ndy/kcptun-plugins
https://github.com/PantherJohn/kcptun-plugins

**Comment by PantherJohn** [comment]
https://github.com/xtaci/kcp-go/issues/107

**Comment by PantherJohn** [comment]
@xtaci

**Comment by xtaci** [comment]
i think you can just give up specifying `-c`  or specifying an empty json file

**Comment by PantherJohn** [comment]
@xtaci Thanks. You made my day.
