### ISSUE TITLE
Bandwagon Trace/breakpoint trap？

### ISSUE THREAD

**Issue by ferristale** [xtaci/kcptun#64]
Starting kcp-server.../etc/init.d/kcp-server: line 63:   651 Trace/breakpoint tr   ap   ${BIN} -c ${CONFIGFILE} > ${LOGFILE} 2>&1

centos6.8 x32

好像说搬瓦工的centos6都会这样，但是有的人成功了诶
不懂我为啥不行==
GO环境已经装好了

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/latest  

这里是官方编译

**Comment by ferristale** [comment]
意思是说用官方自行编译就不会有这个问题吗



朝蒸藜藿幕烹葵


2016年7月18日 星期一 +0800 上午10:11 发件人 hushuangpu  <notifications@github.com>:

**Comment by xtaci** [comment]
意思是： 我并不知道kcpserver用的什么编译选项，你可以试试官方编译的。

**Comment by ferristale** [comment]
只是，这似乎是不用编译的吧
好像只有一个二进制文件




2016年7月18日 星期一 +0800 上午10:19 发件人 hushuangpu  <notifications@github.com>:

**Comment by xtaci** [comment]
是的，解压即用

**Comment by ferristale** [comment]
所以说还是我服务器的问题，不知道别人的搬瓦工怎么弄的

2016年7月18日 星期一 +0800 上午10:33 发件人 hushuangpu  <notifications@github.com>:

**Comment by xtaci** [comment]
检查下是32位还是64位系统，自己编译也很简单
```
git clone https://github.com/xtaci/kcptun/
cd kcptun
./build-release.sh
```

**Comment by ferristale** [comment]
原来官方还给出了一键安装脚本，谢谢，晚上回去试试

2016年7月18日 星期一 +0800 上午10:38 发件人 hushuangpu  <notifications@github.com>:
>检查下是32位还是64位系统，自己编译也很简单
>git clone https://github.com/xtaci/kcptun/
cd kcptun
./build-release.sh
