### ISSUE TITLE
国际线路重传率（RetransSegs / OutSegs）高，达到OutSegs总量一半多,且重复率很高 （RepeatSegs / 发送端RetransSegs）

### ISSUE THREAD

**Issue by jason2000915** [xtaci/kcptun#640]
实际速度平均22Mbits/sec ， 实际消耗60+Mbits的带宽
重复率达到总重传数量的一半

发送端VULTR德国法兰，接收端上海电信
延迟平均260ms 但是有50ms的mdev

发送端Centos 7
接收端Ubuntu 16.04

测试用的iperf3 TCP模式 (均为客户端运行)
参数 iperf3 -c xxx.xxx.xxx.xxx -p xxxx -V -R

Iperf3 3.6 UDP模式测量下来70M的带宽大概丢包率在5%以内 速度平均69.7MBits/sec 而且没有乱序情况(未显示)
参数 iperf3 -c xxx.xxx.xxx.xxx -p xxxx -u -b 70M -V -R

![2018-12-16 20-07-22](https://user-images.githubusercontent.com/34935565/50053453-452c3200-0170-11e9-8848-17ea358e9df6.png)

服务端qdisc为fq 拥塞算法BBR

kcptun参数：
Server ：
![2018-12-16 20-15-30](https://user-images.githubusercontent.com/34935565/50053395-66405300-016f-11e9-9fcd-9d0dcaebf0d8.png)

Client：
![2018-12-16 20-16-14](https://user-images.githubusercontent.com/34935565/50053398-7bb57d00-016f-11e9-9ba3-2d777ef81545.png)

Client端rcvwnd Server端rcvwnd都设置极大值，便于调试
模式Fast ～ Fast3都试过，重传率依旧高

kcptun SNMP信息：
Server：
![2018-12-16 20-02-50](https://user-images.githubusercontent.com/34935565/50053435-ebc40300-016f-11e9-9f6e-4fb8f142d133.png)

Client:
![2018-12-16 20-03-07](https://user-images.githubusercontent.com/34935565/50053436-f1214d80-016f-11e9-81ec-e3171aab242e.png)

主要追求数据载荷比

阅读过重传部分代码 觉得（理论情况下）只有高掉包/高乱序度才会导致大量重传 且是无效（重复）重传
试过增加interval稍有改善，但是想研究到底是什么根源（其他参数都试过 开启fec要到5/5才有效 recoveredSegs才上去 但是载荷比太低了）

不太确定是不是网络本身的问题 

想请问下各位大大是什么原因导致的？

**Comment by jason2000915** [comment]
好吧 没看见 是有18000多个包乱序 但是相比9w的重传还是只占一小部分

**Comment by xtaci** [comment]
用最新的版本试试，消除了一些程序抖动

**Comment by t123yh** [comment]
可以按照 https://cizixs.com/2018/01/13/linux-udp-packet-drop-debug/ 这篇文章的思路诊断一下
