### ISSUE TITLE
关于mips和mipsle版本可执行文件的尺寸

### ISSUE THREAD

**Issue by jeffpeng78** [xtaci/kcptun#641]
当前mips和mipsle版本Release的可执行文件大约都在4M以上。
而[openwrt-kcptun](https://github.com/bettermanbao/openwrt-kcptun/releases)这个项目的可执行文件大约只有1.2M。
对于运行在嵌入式设备上的程序来说，文件尺寸的差别还是很明显的。
请问咱们官方的Release文件尺寸是否也能缩小到1M左右？谢谢！

**Comment by jeffpeng78** [comment]
upx直接压缩到了1.1M!

**Comment by a94821** [comment]
可以试试这个https://github.com/liudf0716/xkcptun.
