### ISSUE TITLE
kcptun does not handle interface changes

### ISSUE THREAD

**Issue by Mygod** [xtaci/kcptun#642]
7. Are you using the **latest release**?
v20190104

8. Which **OS** do you use?
Linux 4.18.0-13-generic #14~18.04.1-Ubuntu SMP Thu Dec 6 14:09:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

9. Which end for this issue related to, **client or server**?
client only

Steps to reproduce:

1. Start kcptun without autoexpire
2. Connect to it to ensure a session is started and active
3. Bring down the interface it is using and bring up another interface

Expected: kcptun switch to using the new interface.

Actual: kcptun still attempts to send packets using the old local address.

**Comment by Mygod** [comment]
It does so very implicitly. When a UDP connection is established, it will
bind to a default address at a random port and keep using it.

**Comment by xtaci** [comment]
so the problem relates to error handling in kcp-go, I think

**Comment by xtaci** [comment]
if you are listening on 0.0.0.0 , I still don't know why the underlying link change has anything to do with  IP routing

**Comment by xtaci** [comment]
I wonder how other apps handle this situation

**Comment by Mygod** [comment]
https://github.com/xtaci/kcp-go/blob/2e93812c29ae191850083a4fe637df226826e460/sess.go#L919

I think when you call `net.DialUDP`, the underlying syscall is `connect` instead of `bind`. And that syscall will assign you a real local address and port (from which your UDP packets will be sent) instead of `INADDR_ANY (0.0.0.0)`.

According to [this](https://stackoverflow.com/a/1075420/2245107), I think the trick is to call `sendTo` directly instead of `connect` (not sure how to do that in go, lol).

In QUIC, they use connection migration by having a session ID methinks.

**Comment by Mygod** [comment]
BTW, I think connection migration is useful (if not essential), especially in the context of multiplexing. I see KCP is also used by mobile games. Without connection migration, KCP will always try to use the link it was bound to when the UDP connection was created. This is especially problematic in the mobile settings.

**Comment by xtaci** [comment]
no time for doing that

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/tree/writeTo

**Comment by xtaci** [comment]
any updates?

**Comment by Mygod** [comment]
Nope. Still not working. (I mean it's not hard to reproduce this, just make sure autoexpire=0)

**Comment by xtaci** [comment]
can android be notified about the network change , and try restarting the kcptun client?

**Comment by Mygod** [comment]
Yes, but we simply set autoexpire=10 as default as a hack.

**Comment by xtaci** [comment]
How other apps detect network change , in general?
