### ISSUE TITLE
虚拟内存VSZ占用过大？

### ISSUE THREAD

**Issue by a94821** [xtaci/kcptun#648]
mt7620     64M内存   client
dscp=0;parityshard=0;mode=fast;nocomp;mtu=1320;rcvwnd=750;datashard=0;sndwnd=300;crypt=none
VSZ=650m   ss服务才2.2m

**Comment by cs8425** [comment]
golang設計上會用到大量虛擬記憶體, 是正常現象
實際用量請觀察RES欄位
詳情可參考官方FAQ: https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory
