### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by ferristale** [xtaci/kcptun#65]
server log
2016/07/18 14:16:48 version: 20160716
2016/07/18 14:16:48 communication mode: fast2
2016/07/18 14:16:48 encryption: aes
2016/07/18 14:16:48 nodelay parameters: 1 20 2 1
2016/07/18 14:16:48 sndwnd: 2048 rcvwnd: 2048
2016/07/18 14:16:48 acknodelay: false
2016/07/18 14:16:48 dscp: 0
2016/07/18 14:16:48 compression: true
2016/07/18 14:16:48 datashard: 10 parityshard: 3
2016/07/18 14:16:48 listening at 0.0.0.0:29900
2016/07/18 14:18:07 remote address: IP:15885
2016/07/18 14:19:07 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/18 14:19:07 mux: keepalive timeout
2016/07/18 14:19:07 [ERR] yamux: Failed to read header: broken pipe
2016/07/18 14:20:31 remote address: IP:46726
2016/07/18 14:20:33 connecting to 
2016/07/18 14:20:33 closed 
2016/07/18 14:20:33 connecting to 
2016/07/18 14:20:33 closed 
2016/07/18 14:20:33 connecting to 
2016/07/18 14:20:33 closed 

client log
2016/07/19 02:17:37 version: 20160701
2016/07/19 02:17:37 listening on: [::]:12948
2016/07/19 02:17:37 encryption: aes
2016/07/19 02:17:37 nodelay parameters: 1 20 2 1
2016/07/19 02:17:37 remote address: IP:29900
2016/07/19 02:17:37 sndwnd: 25 rcvwnd: 204
2016/07/19 02:17:37 compression: true
2016/07/19 02:17:37 mtu: 1350
2016/07/19 02:17:37 datashard: 10 parityshard: 3
2016/07/19 02:17:37 acknodelay: false
2016/07/19 02:17:37 dscp: 46
2016/07/19 02:17:37 conn: 1
2016/07/19 02:19:04 stream opened
2016/07/19 02:19:04 stream opened
2016/07/19 02:19:12 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/19 02:19:12 [ERR] yamux: Failed to read header: broken pipe
2016/07/19 02:19:12 stream closed
2016/07/19 02:19:12 stream closed
2016/07/19 02:19:16 session shutdown
2016/07/19 02:20:00 connection write timeout
2016/07/19 02:20:00 [ERR] yamux: Failed to write header: broken pipe
2016/07/19 02:20:00 [ERR] yamux: Failed to read header: broken pipe

**Comment by ferristale** [comment]
看了前面几个issue但还是没懂，SS服务端应该是连接成功了
服务器是centos6.8 x64

**Comment by yuyongji1987** [comment]
我是偶尔可以连接，偶尔会和楼上一样；20M联通无问题，200K电信有问题。

**Comment by ferristale** [comment]
我的是10M铁通

2016-07-19 9:09 GMT+08:00 yuyongji1987 <notifications@github.com>:

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Does your ISP or VPS **blocked UDP**?
5. Does your VPS **firewall** allows UDP pass through?
6. Are you using the **same version** for both client & server
7. Did you correctly set the ```-target value, -t value	target server address (default: "127.0.0.1:12948")``` on the server side?


铁通，长宽等就不要用这个了。

**Comment by ferristale** [comment]
1. 2016.7.1
2. centos6.8 x64
3.
等等。铁通会封UDP的意思吗==

2016-07-19 10:26 GMT+08:00 Daniel Fu <notifications@github.com>:

**Comment by xtaci** [comment]
是的，山寨的网络都会有各种限制。

**Comment by ferristale** [comment]
山…寨…而我用了三年了…虽然是不是大姨妈…哭



朝蒸藜藿幕烹葵


2016年7月19日 星期二 +0800 上午10:29 发件人 hushuangpu  <notifications@github.com>:

**Comment by xtaci** [comment]
你可以咨询下你身边的专业人士了
