### ISSUE TITLE
能否用ios的ss客户端指向安卓手机的ip地址，ios的ss客户端的端口应该设置成什么啊

### ISSUE THREAD

**Issue by flylj999** [xtaci/kcptun#650]
ios的ss客户端指向开有kcptun的电脑ip可以使用，手机的kcptun也可以正常使用，现在想通过连接手机，只是不知道ios的ss客户端的端口该设置成哪个呢？试了好几个都不行

**Comment by xtaci** [comment]
当然可以啊，client_linux_amd64 listen参数那个地址啊

**Comment by flylj999** [comment]
> 当然可以啊，client_linux_amd64 listen参数那个地址啊

ios的ss客户端服务器是填同局域网的android手机的ip地址 对吗，然后端口是填哪个

**Comment by xtaci** [comment]
-l 那个端口
