### ISSUE TITLE
校园网无法使用kcptun，经常断流

### ISSUE THREAD

**Issue by NinelieAimer** [xtaci/kcptun#654]
平时家里用wifi，手机热点从来没有出现这种情况，参数绝对正确，学校校园网就会出现，会话过期，关闭
日志如下：
2019/02/22 10:26:36 connection: 0.0.0.0:62815 -> xxx.xxx.xx.xxx:29900
2019/02/22 10:26:36 stream opened
2019/02/22 10:26:36 session normally closed
2019/02/22 10:27:06 stream opened
2019/02/22 10:27:06 stream closed
2019/02/22 10:27:06 stream closed
2019/02/22 10:27:06 session marked as expired
2019/02/22 10:27:06 connection: 0.0.0.0:62822 -> xxx.xxx.xx.xxx:29900
2019/02/22 10:27:06 stream opened
2019/02/22 10:27:07 session normally closed
2019/02/22 10:27:36 stream closed
2019/02/22 10:27:36 session marked as expired
2019/02/22 10:27:36 connection: 0.0.0.0:61265 -> xxx.xxx.xx.xxx:29900
2019/02/22 10:27:36 stream opened
2019/02/22 10:27:37 session normally closed
2019/02/22 10:28:06 stream opened
2019/02/22 10:28:06 stream closed
2019/02/22 10:28:06 stream closed
2019/02/22 10:28:06 session marked as expired
2019/02/22 10:28:06 connection: 0.0.0.0:61267 -> xxx.xxx.xx.xxx:29900

**Comment by JimLee1996** [comment]
今天遇到了同样的问题。很难受

**Comment by zhanhb** [comment]
记得把IP隐藏一下

**Comment by NinelieAimer** [comment]
@zhanhb 谢谢提醒

**Comment by HiGarfield** [comment]
教育网完全没法用了。教育网加了一道墙，UDP白名单模式。

**Comment by ljyloo** [comment]
你可以加一层udp2raw把udp包伪装成tcp包来发，可以绕过一些ISP的限制
