### ISSUE TITLE
kcptun是不能用了吗?

### ISSUE THREAD

**Issue by mouaibaka** [xtaci/kcptun#655]
检查了很多遍 
![3ccko es1tnbu8 d hpq6o](https://user-images.githubusercontent.com/30500022/53683274-c6d83880-3d39-11e9-9a2c-c3a809ab599a.png)
这里看着也一切正常 但是就是不能用了 单开ss还可以 配合kcptun就是不行

**Comment by Comah** [comment]
我的一切正常 最新版
