### ISSUE TITLE
kcptun server 会对shadowsocks server进行负载均衡吗

### ISSUE THREAD

**Issue by hkshawn** [xtaci/kcptun#657]
如果没有 请问会对kcptun增加这个功能吗？

**Comment by xtaci** [comment]
理论上可以在server端 -》haproxy -》 ss server吧

**Comment by PantherJohn** [comment]
@xtaci @hkshawn`haproxy` is an overkill. Simply enabling `SO_REUSEPORT`(`ss-server` option `reuse_port`) for listening sockets of the shadowsocks server can save a large amount of time messing around with config files and struggling with degraded performance.
