### ISSUE TITLE
找不出产生"Text file busy"问题的原因

### ISSUE THREAD

**Issue by verniyb** [xtaci/kcptun#658]
执行
```
/home/user/bin/kcptun_amd64 -t "[::1]:458" -l ":3443" -key "password" --mode normal --sndwnd 1390 --rcvwnd 1390 --ds 10 --ps 3 --sockbuf 16777217 --nocomp --quiet
```
报错
```
-bash: /home/user/bin/kcptun_amd64: Text file busy
```
检查没有端口占用，文件执行权限也是正确的，也没有程序调用kcptun。

这句命令原先写在自己的supervisor的command里的，一直都正常工作。今天重新建了一个服务器（VPS），把原先的文件拷进去，发现supervisor启动不起来，也不报什么信息，百思不得其解，把所有program排查了一遍才发现是kcptun这里卡住了。

不知道怎么入手，折腾了很久，没能解决，浪费了很多时间。希望能得到帮助。

**Comment by xtaci** [comment]
chmod +x?

**Comment by PantherJohn** [comment]
@verniyb Try
`pkill kcptun_amd64` or `killall kcptun_amd64`.
