### ISSUE TITLE
kcptun 转发tcp包原理上是否真的能提速？

### ISSUE THREAD

**Issue by ZezhongWang** [xtaci/kcptun#659]
近期在学习kcp代码的时候遇到了一些疑问，就是对kcptun转发tcp包这种形式是否能真正起作用产生了疑问。

kcp本身性能优于tcp主要基于以下两个方面的改变

- 超时策略， RTO X 2 -> RTO X 1.5
- 重传逻辑,    3 Duplicated ACK -> 2 Duplicated ACK & Early resend & Selective Resend

其他方面并没有明显区别，依旧维护了snd_wnd, rcv_wnd等，挺标准的ARQ协议。对于官方所说的 “平均延迟降低30%-40%” 应该只有在极其恶劣的网络的情况下才能达到这个效果。
而 kcp-go 在原来的基础上加了 FEC，采取了 ARQ & FEC 混合的方式来加速， 原理上是行得通的。

下面是我进行测试的数据：

## 无kcptun, 纯ss
![无kcp](https://user-images.githubusercontent.com/28833999/54520043-b7482900-49a2-11e9-83f7-3799c86fe082.png)

## 有kcptun, fast3

![fast3](https://user-images.githubusercontent.com/28833999/54520333-6e44a480-49a3-11e9-8a73-938494cb4c3c.png)

参数

`{
  "localaddr":":80",
  "remoteaddr":"104.224.137.244:29900",
  "key":"123456",
  "crypt":"none",
  "nocomp":true,
  "quiet":true,
  "mode":"fast3",
  "nodelay":1,
  "interval":50,
  "resend":0,
  "nc":1,
  "acknodelay":false
}`

## 有kcptun, 关fec

![fast3withoutFEC](https://user-images.githubusercontent.com/28833999/54520384-8fa59080-49a3-11e9-9684-9d25c4047607.png)

## 对于测试数据的一些疑问

有fec的情况下由于冗余发包造成带宽利用率降低我可以理解。
但是，我有几个问题想请教一下：

- 延迟在 Loaded 情况下为什么会上升到秒级别？ 
- 在关闭 FEC 之后的 Unloaded 为什么延迟翻了一倍？
- 在udp基础上实现了 ARQ 之后，原本 udp 速度快的优势（本身就建立在无拥塞窗口）就没有了，通过修改部分参数如何达到所说的 **30% - 40% 延迟的降低**？
- 另外， kcptun 的主要作用应该是用来降低丢包率和时延，按理是不能提高带宽利用率的，不知道 README 中 Performance 部分是如何得到的？

嘻嘻，本人还是个大学生，有些疑问望解答，感谢！

**Comment by jeffpeng78** [comment]
kcptun只有在丢包率比较高或者比较拥堵的网络环境下才有速度优势，一般在国际线路上体现明显。
准确地讲，kcptun对提高线路的throughput有帮助，讲latency就比较复杂了。
你的测试环境过于复杂，用FAST做性能测试因为涉及到两段线路(Client <==> Server <==> Fast.com)，所以并不合适。

建议使用iperf3等专业工具只测试一端线路(Client <==> Server)。
具体方法可以参考 https://cn.jetapple.com/how-to/speed-test/
你也可以参考JetApple的测试命令，在自己的服务器上构建iperf和kcptun的测试环境。

个人理解，仅供参考。

**Comment by xtaci** [comment]
试试长距通信，再来问

**Comment by xtaci** [comment]
注意一点哈，时延是不能改善的

**Comment by xtaci** [comment]
其他部分你说的基本没问题，ARQ部分和reno基本一样的，能改善的方法:
1.  窗口恒定
2. 窗口恒定下更优的fast retransmit，同时保持基本的退让
3. FEC，长距+高噪通信最为关键的改善

**Comment by ZezhongWang** [comment]
既然对时延的提升并没有帮助的话，那么kcptun/kcp的作用就主要是降低丢包率，提升网络稳定性吗？因为Throughput实际上也是无法提升的，开启FEC加上了冗余包会导致带宽利用率降低

**Comment by ZezhongWang** [comment]
还有就是如果时延无法提升为什么 KCP 的 README 里面写 “能以比 TCP浪费10%-20%的带宽的代价，换取平均延迟降低 30%-40%，且最大延迟降低三倍的传输效果”. 非常有误导性

**Comment by cs8425** [comment]
@ZezhongWang 
Loaded情況下會造成延遲大幅上升有2個可能:
1. 頻寬用盡, 自然會上升
2. smux的實作特性, `--sockbuf`這個參數不夠大, "伺服 -> kcprun"速度遠大於"kcprun -> 使用者"時會把buffer用盡影響到其他的流, 造成而外的延遲

如果是2的話
試試看把`--sockbuf`設大一點(32MB 64MB 128MB之類的)
或者嘗試看看我改過的版本: https://github.com/cs8425/kcptunB
有實作每個stream的流控
**注意: 伺服端跟客戶端都要更新此版本**

**Comment by Immueggpain** [comment]
@ZezhongWang 其实TCP更大大的问题是连接握手，TLS就更是，所以会慢。如果0-RTT就会很快，比如我这个，https://github.com/Immueggpain/smartproxy

**Comment by kxmp** [comment]
能扛得住丢包肯定利用率就大了.
你自己给模拟环境来个1%丢包 2%丢包就知道了.
rtt必须>200ms以上 这时候就很明显了. 一个1%丢包把你卡到解放前.
百兆瞬间变成1-2mbps 或者可能还不到.
