### ISSUE TITLE
双网卡时KCPTUN的BUG

### ISSUE THREAD

**Issue by wuqifeng1988** [xtaci/kcptun#661]
今天在服务器上部署KCPTUN的时候，发现客户端只能收到极少的回应，怎么改参数都没用，查了很久最终发现，是因为服务器上有2块网卡，分别绑定了不同网段的IP，客户端向A网卡的IP发送请求，KCPTUN用B网卡的IP发回数据，导致UDP包无法穿过防火墙被丢弃。

希望可以修正这个BUG。

**Comment by xtaci** [comment]
这和应用层没关系，你自己服务器的路由表配置错了

**Comment by wuqifeng1988** [comment]
因为这台服务器还跑了很多其它基于UDP的应用，包括我自己开发的一套基于UDP的流媒体系统，双网卡工作一直都正常，路由表基本可以确定没有配错，同一台服务器上部署得UDP2RAW工作也是正常的。

**Comment by xtaci** [comment]
无从改起，没有和网卡相关的设计，这只和你的路由，listen ip这些有关，本质就是和路由有关系

**Comment by Immueggpain** [comment]
你这么一说，我倒想到，kcptun支持多个客户端同时连接吗？
