### ISSUE TITLE
能否编译arm64 包？ 

### ISSUE THREAD

**Issue by Remonli** [xtaci/kcptun#662]
现在很多盒子都跑在A53,A72 这类 arm64架构的cpu， 是不是考虑编译arm64的二进制包？ 

谢谢。

**Comment by xtaci** [comment]
量大就可以

**Comment by keeno1982** [comment]
顶，现在64位的板子开始成主流了

**Comment by xtaci** [comment]
看有多少人关注这个issue吧

**Comment by wgedu** [comment]
支持编译arm64包

**Comment by Remonli** [comment]
其实用arm5, arm6 设备跑这个的应该很少了,  可以直接考虑就arm7, arm64 两个架构就可以了.

**Comment by xtaci** [comment]
先留着吧，有下载量说明有人用

**Comment by sky92682** [comment]
> 其实用arm5, arm6 设备跑这个的应该很少了, 可以直接考虑就arm7, arm64 两个架构就可以了.

其实还有不少路由器是用arm5和6的
