### ISSUE TITLE
参数设置请教

### ISSUE THREAD

**Issue by sqliuchang** [xtaci/kcptun#663]
因为mtproxy被精准识别了，所以在服务端用kcptun封装了一下，并且在国内服务器上部署kcptun客户端作为中转。
所以想请教一下，国内服务器是 1M 的带宽，经过多次iperf测试，连接国外服务器双向1M跑满，udp丢包率为0，延迟稳定在140ms。
设置--rcvwnd 32 --sndwnd 32 --mtu 600 --mode fast 3，其他为默认参数
根据公式计算32*600/1024/0.14=134KB/s略大于128。
请问这个设置合理吗？默认的datashard parityshard在丢包率为0的情况下是否还需要调整？
同样在家里路由器iperf udp测速，客户端上行24M 下行114M 都有5%以内的丢包率，设置--rcvwnd 1024 --sndwnd 256 --mode normal，datashard parityshard默认是否合理？

**Comment by xtaci** [comment]
建议fast3, rcvwnd看你了，-ds,-ps最好不动， 256是个足够小的数字,

**Comment by sqliuchang** [comment]
> 建议fast3, rcvwnd看你了，-ds,-ps最好不动， 256是个足够小的数字,

好的，多谢了。
路由器用normal主要是因为fast3的cpu负载太高。
