### ISSUE TITLE
手机客户端连接良好,但是windows客户端连接就断开

### ISSUE THREAD

**Issue by herokillerJ** [xtaci/kcptun#668]
![image](https://user-images.githubusercontent.com/24591046/56465486-ab7fd480-6430-11e9-9502-7905b9b430f9.png)
如图,无限open close

**Comment by xtaci** [comment]
参数不对呗，只有这个原因

**Comment by herokillerJ** [comment]
> 参数不对呗，只有这个原因

我手机上和PC上参数完全一样的,手机和电脑也连的同一个路由器
