### ISSUE TITLE
新版本无法上网

### ISSUE THREAD

**Issue by EstFoxs** [xtaci/kcptun#669]
使用版本：kcptun-windows-amd64-20190423.tar.gz
windows端：https://github.com/dfdragon/kcptun_gclient/releases
无法出墙，现替换kcptun-windows-amd64-20190104.tar.gz 正常使用。。
没搞明白哪里问题。

**Comment by xtaci** [comment]
能贴一下日志么

**Comment by xtaci** [comment]
另外这是一个pre-release，stable release是在0418

**Comment by xtaci** [comment]
正在处理这个问题

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20190424
@EstFoxs 麻烦使用下新版本，解决了windows兼容性问题

**Comment by EstFoxs** [comment]
> https://github.com/xtaci/kcptun/releases/tag/v20190424
> @EstFoxs 麻烦使用下新版本，解决了windows兼容性问题

可以了，多谢。。
