### ISSUE TITLE
BROKEN PIPE

### ISSUE THREAD

**Issue by lizongzeshunshun** [xtaci/kcptun#67]
服务器：

> root@Kvmla-20151225:~/01# ./server_linux_amd64 -t "127.0.0.1:1080" -l ":9875" -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2
2016/07/21 00:03:50 version: 20160719
2016/07/21 00:03:50 listening on  [::]:9875
2016/07/21 00:03:50 encryption: aes
2016/07/21 00:03:50 nodelay parameters: 1 20 2 1
2016/07/21 00:03:50 sndwnd: 2048 rcvwnd: 2048
2016/07/21 00:03:50 compression: true
2016/07/21 00:03:50 mtu: 1400
2016/07/21 00:03:50 datashard: 10 parityshard: 3
2016/07/21 00:03:50 acknodelay: false
2016/07/21 00:03:50 dscp: 0
2016/07/21 00:05:19 remote address: 113.90.59.86:42150
2016/07/21 00:05:19 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:05:19 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:05:19 remote address: 113.90.59.86:42150
2016/07/21 00:05:19 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:05:19 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:05:19 remote address: 113.90.59.86:42150
2016/07/21 00:05:19 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:05:19 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:05:20 remote address: 113.90.59.86:42150
2016/07/21 00:05:55 remote address: 113.90.59.86:44598
2016/07/21 00:05:55 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:05:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:05:55 remote address: 113.90.59.86:44598
2016/07/21 00:05:55 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:05:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:05:55 remote address: 113.90.59.86:44598
2016/07/21 00:05:55 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:05:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:05:56 remote address: 113.90.59.86:44598
2016/07/21 00:05:56 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:05:56 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:05:56 remote address: 113.90.59.86:44598
2016/07/21 00:05:56 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:05:56 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:05:56 remote address: 113.90.59.86:44598
2016/07/21 00:06:20 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/21 00:06:20 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:20 keepalive timeout
2016/07/21 00:06:54 remote address: 113.90.59.86:39892
2016/07/21 00:06:54 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:54 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:54 remote address: 113.90.59.86:39892
2016/07/21 00:06:55 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:55 remote address: 113.90.59.86:39892
2016/07/21 00:06:55 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:55 remote address: 113.90.59.86:39892
2016/07/21 00:06:55 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:56 remote address: 113.90.59.86:39892
2016/07/21 00:06:56 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:56 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:56 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/21 00:06:56 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:56 keepalive timeout
2016/07/21 00:06:56 remote address: 113.90.59.86:39892
2016/07/21 00:06:56 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:56 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:57 remote address: 113.90.59.86:39892
2016/07/21 00:06:57 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:57 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:58 remote address: 113.90.59.86:39892
2016/07/21 00:06:58 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:58 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:06:59 remote address: 113.90.59.86:39892
2016/07/21 00:06:59 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:06:59 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:00 remote address: 113.90.59.86:39892
2016/07/21 00:07:00 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:00 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:01 remote address: 113.90.59.86:39892
2016/07/21 00:07:01 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:01 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:02 remote address: 113.90.59.86:39892
2016/07/21 00:07:02 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:02 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:03 remote address: 113.90.59.86:39892
2016/07/21 00:07:03 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:03 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:05 remote address: 113.90.59.86:39892
2016/07/21 00:07:05 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:05 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:06 remote address: 113.90.59.86:39892
2016/07/21 00:07:06 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:06 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:08 remote address: 113.90.59.86:39892
2016/07/21 00:07:08 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:08 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:09 remote address: 113.90.59.86:39892
2016/07/21 00:07:09 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:09 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:11 remote address: 113.90.59.86:39892
2016/07/21 00:07:11 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:11 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:13 remote address: 113.90.59.86:39892
2016/07/21 00:07:13 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:13 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:14 remote address: 113.90.59.86:39892
2016/07/21 00:07:14 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:14 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:16 remote address: 113.90.59.86:39892
2016/07/21 00:07:16 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:16 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:17 remote address: 113.90.59.86:39892
2016/07/21 00:07:17 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:17 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:19 remote address: 113.90.59.86:39892
2016/07/21 00:07:19 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:19 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:21 remote address: 113.90.59.86:39892
2016/07/21 00:07:21 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:21 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:22 remote address: 113.90.59.86:39892
2016/07/21 00:07:22 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:22 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:24 remote address: 113.90.59.86:39892
2016/07/21 00:07:24 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:24 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:24 remote address: 113.90.59.86:39892
2016/07/21 00:07:24 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:24 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:25 remote address: 113.90.59.86:39892
2016/07/21 00:07:54 remote address: 113.90.59.86:37401
2016/07/21 00:07:54 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:54 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:54 remote address: 113.90.59.86:37401
2016/07/21 00:07:55 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:55 remote address: 113.90.59.86:37401
2016/07/21 00:07:55 dial tcp 127.0.0.1:1080: getsockopt: connection refused
2016/07/21 00:07:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:07:55 remote address: 113.90.59.86:37401
2016/07/21 00:08:25 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/21 00:08:25 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:08:25 keepalive timeout
2016/07/21 00:08:55 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/21 00:08:55 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 00:08:55 keepalive timeout
2016/07/21 00:08:55 remote address: 113.90.59.86:27074

本地：

> jack@jack-Lenovo-Product:~$ ./client_linux_amd64 -r "107.189.153.123:9875" -l ":1080" -mtu 1400 -sndwnd 256 -rcvwnd 2048 -mode fast2 -dscp 46
2016/07/21 12:04:53 version: 20160719
2016/07/21 12:04:53 listening on: [::]:1080
2016/07/21 12:04:53 encryption: aes
2016/07/21 12:04:53 nodelay parameters: 1 20 2 1
2016/07/21 12:04:53 remote address: 107.189.153.123:9875
2016/07/21 12:04:53 sndwnd: 256 rcvwnd: 2048
2016/07/21 12:04:53 compression: true
2016/07/21 12:04:53 mtu: 1400
2016/07/21 12:04:53 datashard: 10 parityshard: 3
2016/07/21 12:04:53 acknodelay: false
2016/07/21 12:04:53 dscp: 46
2016/07/21 12:04:53 conn: 1
2016/07/21 12:05:19 stream opened
2016/07/21 12:05:50 [ERR] yamux: Failed to read header: snappy: corrupt input
2016/07/21 12:05:50 [ERR] yamux: keepalive failed: session shutdown
2016/07/21 12:05:50 stream closed
2016/07/21 12:05:54 session shutdown
2016/07/21 12:05:55 stream opened
2016/07/21 12:05:55 stream opened
2016/07/21 12:05:56 stream opened
2016/07/21 12:05:58 stream opened
2016/07/21 12:06:54 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/21 12:06:54 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 12:06:54 stream closed
2016/07/21 12:06:54 stream closed
2016/07/21 12:06:54 stream closed
2016/07/21 12:06:54 stream closed
2016/07/21 12:06:54 session shutdown
2016/07/21 12:06:54 stream opened
2016/07/21 12:07:54 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/21 12:07:54 [ERR] yamux: Failed to read header: broken pipe
2016/07/21 12:07:54 stream closed
2016/07/21 12:07:54 write udp [::]:39892->107.189.153.123:9875: use of closed network connection 0
2016/07/21 12:07:54 session shutdown
2016/07/21 12:07:54 stream opened
2016/07/21 12:08:25 [ERR] yamux: Failed to read header: snappy: corrupt input
2016/07/21 12:08:25 stream closed
2016/07/21 12:08:25 [ERR] yamux: keepalive failed: session shutdown
2016/07/21 12:08:25 session shutdown
2016/07/21 12:12:39 stream opened

服务器系统Ubuntu14.04
本地Ubuntu16.04
服务器提供：Kvmla的256MB(OpenVZ)

**Comment by lizongzeshunshun** [comment]
ISP是中国电信

**Comment by xtaci** [comment]
dial tcp 127.0.0.1:1080: getsockopt: connection refused  你1080没起服务。

**Comment by lizongzeshunshun** [comment]
可以了，谢谢
