### ISSUE TITLE
关于datashard和parityshard参数请教一下

### ISSUE THREAD

**Issue by maxwellzh** [xtaci/kcptun#672]
在`datashard=parityshard`条件下，我分别设置了`datashard=10, 30, 50, 70, 120`测试，结果显示`datashard`越大下行速率越大（梯度在10%左右），之前一直以为是没什么区别的，想请教一下有什么可能的原因。

测试网络环境：client安卓设备无线连接，且网络本身比较拥堵。
server版本是最新的，client用的是kcp-ss plugin（很久以前的版本了，作者一直没编译新版我也懒得自己编译）
ps. 此前似乎在某个issue里也见过类似的讨论，但是没找到

**Comment by maxwellzh** [comment]
等会用最新版windows客户端再测试一下看看（虽然我觉得没什么关系，毕竟FEC相关的代码一直没变动

**Comment by maxwellzh** [comment]
> 等会用最新版windows客户端再测试一下看看（虽然我觉得没什么关系，毕竟FEC相关的代码一直没变动

windows上也有这个问题

**Comment by maxwellzh** [comment]
难以复现，可能为测试问题

**Comment by kxmp** [comment]
计算频次有关系吧
想象一下你每10k要计算一次 和100k计算一次的区别.

**Comment by maxwellzh** [comment]
> 计算频次有关系吧
> 想象一下你每10k要计算一次 和100k计算一次的区别.

应该不是吧，尽管每10k计算一次频次比100k计算一次高，但是每10k算一次RS解码时间更短，而且RS码解码复杂度应该是O(n^2)或以上了（猜的，毕竟涉及矩阵运算），这样想甚至小块的shard总时间更少。

另外无论顶楼结论是否正确，建议看到这个issue的人不要用太大的datashard和parityshard。会导致内存溢出（至少在windows10上会的），具体可以看#677
