### ISSUE TITLE
两天流量超过183G，求优化参数

### ISSUE THREAD

**Issue by hktalent** [xtaci/kcptun#673]
两天流量超过183G，求优化参数
![DC7389A77F1C53291886275848C6848E](https://user-images.githubusercontent.com/18223385/56937134-afe17700-6b2d-11e9-81a9-825adf99f022.jpg)

<img width="630" alt="image" src="https://user-images.githubusercontent.com/18223385/56937130-aa842c80-6b2d-11e9-8580-ff8109dd0458.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/18223385/56937127-a6580f00-6b2d-11e9-990a-bf1e68e240be.png">

程序：最新源码自己编译

server配置：
```
{
"listen": ":110",
"target": "127.0.0.1:443",
"key": 'xxxxxxx",
"crypt": "aes-128",
"mode": "manual",
"mtu": 1400,
"sndwnd": 1024,
"rcvwnd": 1024,
"datashard": 30,
"parityshard": 15,
"dscp": 46,
"nocomp": true,
"acknodelay": false,
"nodelay": 0,
"interval": 20,
"resend": 2,
"nc": 1,
"sockbuf": 4194304,
"keepalive": 10
}

```
client配置
```
{
"localaddr": "127.0.0.1:1099",
"remoteaddr": "xxxxx:110",
"key": "xxxxxxx",
"crypt": "aes-128",
"mode": "manual",
"conn": 1,
"autoexpire": 300,
"mtu": 1400,
"sndwnd": 128,
"rcvwnd": 1024,
"datashard": 30,
"parityshard": 15,
"dscp": 46,
"nocomp": true,
"acknodelay": false,
"nodelay": 0,
"interval": 20,
"resend": 2,
"nc": 1,
"sockbuf": 4194304,
"keepalive": 10
}


```

**Comment by xtaci** [comment]
没问题啊，少看点视频就可以了

**Comment by hktalent** [comment]
@xtaci 大哥，我没有看视频啊

**Comment by kxmp** [comment]
你可能是被攻击了 要不然就是被滥用了 比如公布了什么账号
datashard 100 paritysahrd 用1 这样就够了.
或者都用0也没什么.
你的配置是多用50% 这光是fec的 kcp自己还要多用一些流量.

**Comment by hktalent** [comment]
@kxmp  谢谢了哈

**Comment by jack3014** [comment]
我也遇到过这个问题，流量突然耗尽，而且那段时间我并没有看视频啥的。无法分辨到底是啥问题。

**Comment by PantherJohn** [comment]
Same here. My three servers were attacked almost 10 times within ONE month at night without me noticing it. Then I was forced to pay the $100 bandwidth fee that shouldn’t be paid by myself but those Chinese hackers working for the government.

The duration of each attack is typically one hour, and attack will become more frequent if you don’t take action.
