### ISSUE TITLE
客户端疑似内存泄漏

### ISSUE THREAD

**Issue by maxwellzh** [xtaci/kcptun#677]
偶然发现，只要一直在进行负载较大的传输（视频流、下载等），客户端的内存占用就会一直增加，今天我无意间看到客户端内存占用高达`2000MB`才注意到这个问题
![downloading](https://user-images.githubusercontent.com/32546978/57450785-fd7a8400-7291-11e9-9603-c8a55c2cd2c5.jpg)

用windows自带的工具检测了内存变化数据。这个工具似乎不能输出数据，只能截个图了
\*y轴为内存使用量相对坐标\*
![2](https://user-images.githubusercontent.com/32546978/57450810-12571780-7292-11e9-9bda-e05cd749c774.jpg)

#### 总的来说就是

1. 内存会一直增加，大体的规律是指数增加-平坦-指数增加。
2. 内存不会释放，即使传输任务结束后内存占用也会一直维持，只能重启客户端
3. 服务器内存情况正常

|        | 操作系统       | build |
| ------ | -------------- | ----- |
| server | ubuntu18.04    | 0428  |
| client | Windows10 1903 | 0428  |

kcptun参数设置（client）

```
listening on: [::]:9527
encryption: aes-128
nodelay parameters: 1 10 2 1
remote address: [2400:xxxx::1001]:9500
sndwnd: 128 rcvwnd: 512
compression: true
mtu: 1350
datashard: 130 parityshard: 125
acknodelay: false
dscp: 0
sockbuf: 4194304
smuxbuf: 4194304
keepalive: 10
conn: 1
autoexpire: 0
scavengettl: 600
snmplog:
snmpperiod: 60
quiet: true
```

**Comment by xtaci** [comment]
这么奇怪，我试下windows版本

**Comment by xtaci** [comment]
你试下让compression =false(nocomp=true)，我试过windows版本，无法重现此现象，就这个参数不同。

**Comment by maxwellzh** [comment]
修改`nocomp=true`后问题仍然存在。
@xtaci 你在测试时尝试一下将速率保持在client--server带宽上限，因为我发现低负载（不跑满时）似乎内存占用不会增加
![low](https://user-images.githubusercontent.com/32546978/57457561-55b98200-72a2-11e9-8dff-144cbceba933.jpg)

**Comment by xtaci** [comment]
fec参数呢

**Comment by maxwellzh** [comment]
#### server配置
```
"listen": ":9500",
"target": "127.0.0.1:9001",
"key": "huahuan",
"crypt": "aes-128",
"mode": "fast3",
"mtu": 1350,
"sndwnd": 1024,
"rcvwnd": 512,
"datashard": 130,
"parityshard": 125,
"dscp": 46,
"nocomp": false,
"acknodelay": false,
"sockbuf": 4194304,
"keepalive": 10
```
@xtaci 另外我的server配置中`sndwnd`和`rcvwnd`设置都比client的大，不知道是不是这个原因，我稍后测试一下

**Comment by xtaci** [comment]
不是这个原因，我是说**把-datashard -parityshard调小**

**Comment by maxwellzh** [comment]
抱歉之前只看到了nocomp参数，稍等片刻，测试需要点时间

**Comment by maxwellzh** [comment]
按照你的思路测试了几组不同的fec参数，
第一组`datashard=parityshard=50`，第二第三组分别为`10`和`100`
明显可以从图中看到值越大内存占用增长速率越大
横轴是时间，每格长度为1min
![comp](https://user-images.githubusercontent.com/32546978/57460084-0cb7fc80-72a7-11e9-87bc-bbf0d05ea3d2.jpg)

**Comment by xtaci** [comment]
嗯，那就是这个原因了，标准的 10,3，内存超过30M,通常在15M左右

**Comment by xtaci** [comment]
而且根据你提供的测试数据，ReedSolomon解码过程会消耗大量内存，且来不及释放， 你可以向
https://github.com/klauspost/reedsolomon 提出issue，暂时的解决方法就是降低绝对值，比如130：125是明显可以规约到26:25的。

**Comment by xtaci** [comment]
另一个方法是，你可以试图设置一个环境变量，例如在windows的环境变量设置一个GOGC=30，让GC更激进一些，越小越激进

**Comment by maxwellzh** [comment]
好的，这个问题我关了
