### ISSUE TITLE
v0418和v0428 发行文件相差好大，服务器更新，客户端使用0418是否有问题

### ISSUE THREAD

**Issue by hongwenjun** [xtaci/kcptun#678]
kcptun-linux-amd64-20190418.tar.gz

kcptun-linux-amd64-20190428.tar.gz

![0418](https://user-images.githubusercontent.com/1762909/57507690-0fabff00-7332-11e9-8e03-567ee7832590.png)

**Comment by xtaci** [comment]
你缺这几MB空间？

只有0418是经过upx压缩的，但后来发现有兼容性问题，所以还是提供原版不压缩的，你可以自己用upx压缩。

**Comment by hongwenjun** [comment]
谢谢回答。
主要是我有个项目WinKcp_启动器项目，项目里打包的是windows版kcp二进制文件，方便小白使用
https://github.com/hongwenjun/WinKcp_Launcher
服务器安装和更新脚本，是从你的项目下载的，提供升级脚本的。
如果版本差异不大，我就只更新服务器脚本好了

**Comment by xtaci** [comment]
应该始终检测并使用最新版本啊， 每个版本都有更新，比如0428会大量减少内存使用和CPU使用
应该是每次安装都从这里获取：https://github.com/xtaci/kcptun/releases/latest

**Comment by hongwenjun** [comment]
服务端更新脚本给用的到的朋友
```
# 下载更新 KCPTUN
kcp_ver=$(wget --no-check-certificate -qO- https://api.github.com/repos/xtaci/kcptun/releases/latest | grep 'tag_name' | cut -d\" -f4)
kcp_gz_ver=${kcp_ver:1:8}

kcptun_tar_gz=kcptun-linux-amd64-${kcp_gz_ver}.tar.gz
wget https://github.com/xtaci/kcptun/releases/download/${kcp_ver}/$kcptun_tar_gz
tar xf $kcptun_tar_gz
mv server_linux_amd64 /usr/bin/kcp-server
rm $kcptun_tar_gz
rm client_linux_amd64
```
