### ISSUE TITLE
说明有明显的误导性

### ISSUE THREAD

**Issue by 404neko** [xtaci/kcptun#68]
由于Shadowsocks 的传统1080 端口多用于在客户端提供服务

服务器: ./server_linux_amd64 -t "服务器IP:8838" -l ":554" -mode fast2  // 转发到服务器的本地1080端口
客户端: ./client_darwin_amd64 -r "服务器IP地址:554" -l ":1080" -mode fast2    // 监听客户端的本地1080端口

注: 服务器端需要有服务监听8838端口

这样更好一点

**Comment by wxyzh** [comment]
-t是目标 -l是监听 -r是远端，并没错误啊
至于是客户端还是服务器没必要分这这么清楚

**Comment by bao3** [comment]
这个建议修改一下，1080这个端口确实有误导性。建议改为任意非常规端口或者 shadowsocks server 常用的默认端口。

二楼的回答，绝对正确，单看几个 t,l,r 没有任何问题；可是本例的问题在于 “1080”，跟那三个字母没有任何关系。
