### ISSUE TITLE
添加会话平滑转移

### ISSUE THREAD

**Issue by f4nff** [xtaci/kcptun#680]
quic协议就支持会话平滑转移，也就是在切换网络的时候感觉不出来，tcp也不会断开连接。
比如有两个wifi，切换wifi不会断开，两个网络切换…

**Comment by maxwellzh** [comment]
#642 可以尝试修改`autoexpired`

**Comment by CensorKao** [comment]
我在android上使用kcptun的时候也遇到了这个问题：手动关闭网络后，再次打开网络。kcptun就发不出去数据了，必须强杀app再次进入才能用，当然本地的随机端口号也换了。所以能不能平滑迁移这个对于App来说很重要，设置autoexpire也只能临时解决问题，也不知道失效重连会不会很销毁时间和资源。 @xtaci

**Comment by xtaci** [comment]
android的app是可以感知网络变化，并立即重连kcptun的啊，如果你采用的app没有做到这点，请联系app开发者。这是最基本的。

**Comment by CensorKao** [comment]
> android的app是可以感知网络变化，并立即重连kcptun的啊，如果你采用的app没有做到这点，请联系app开发者。这是最基本的。

我是基于你的client用gomobile编译的，我不会go语音，你那边也没有提供重连的方法，所以我android这边也不知道怎么重启kcptun。只是按网上的步骤改了下main成Run。
