### ISSUE TITLE
关于当前客户端连接数的问题

### ISSUE THREAD

**Issue by jeffpeng78** [xtaci/kcptun#683]
请教一个基本问题：
kcptun的server程序是否可以知道当前与其连接的kcptun的client数？在哪儿可以得到这个当前连接client数的信息呢？
另一个相关问题是，kcptun的server程序能否限制同时连接的client数？该在哪儿设置？

谢谢！

**Comment by jeffpeng78** [comment]
发现当前连接数了，在SNMP里
CurrEstab        uint64 // current number of established connections
但CurrEstab的数值在用--snmplog参数输出成log时有问题，只有当建立连接的那一刻变为1，之后会恢复为0；而当连接断开时，CurrEstab会变为-1的正整数形式。如下：
`
1558484663,48,48,0,0,0,0,0,0,0,15,14,12,12,552,824,0,0,0,0,0,3,0,0,0
1558484723,562,398,1,0,1,1,0,0,0,23,71,18,58,1512,4822,41,0,0,41,0,6,0,0,0
1558484783,72,48,0,0,0,18446744073709551615,0,0,0,15,109,12,87,552,8098,72,0,0,72,0,3,0,0,0
`
此问题可以理解，因为用--snmplog参数输出的SNMP里的其他数值都是--snmpperiod内的变化量，而只有CurrEstab的定义是当前值。
希望修复CurrEstab这一问题，谢谢！

**Comment by xtaci** [comment]
嗯，思考一下怎么修正

**Comment by xtaci** [comment]
snmpperoid不reset应该就可以了

**Comment by xtaci** [comment]
限制连接数这种事，交给iptables就好了
