### ISSUE TITLE
20190515版本在小米路由器上报错: sendmmsg: function not implemented

### ISSUE THREAD

**Issue by abcfy2** [xtaci/kcptun#686]
升级最新版本发现连不上服务器，于是检查日志，发现了大量的这样的日志:

```
2019/06/10 08:02:55 write udp 0.0.0.0:14419: sendmmsg: function not implemented
2019/06/10 08:02:55 write udp 0.0.0.0:51326: sendmmsg: function not implemented
2019/06/10 08:02:56 write udp 0.0.0.0:8218: sendmmsg: function not implemented
2019/06/10 08:02:58 write udp 0.0.0.0:18089: sendmmsg: function not implemented
2019/06/10 08:03:02 write udp 0.0.0.0:62325: sendmmsg: function not implemented
2019/06/10 08:03:06 write udp 0.0.0.0:11922: sendmmsg: function not implemented
2019/06/10 08:03:06 write udp 0.0.0.0:36391: sendmmsg: function not implemented
2019/06/10 08:03:07 write udp 0.0.0.0:38266: sendmmsg: function not implemented
2019/06/10 08:03:09 write udp 0.0.0.0:1098: sendmmsg: function not implemented
2019/06/10 08:03:09 write udp 0.0.0.0:17658: sendmmsg: function not implemented
2019/06/10 08:03:09 write udp 0.0.0.0:14419: sendmmsg: function not implemented
```

是否这个`sendmmsg`函数跟内核版本相关？如果是的话，是否考虑在启用这个参数之前检测一下依赖环境呢？降级回20190428这个版本的客户端就正常了

**Comment by xtaci** [comment]
可以升级内核么， 2011年的linux内核就支持这个函数了，或者查阅下相关sendmmsg的补丁，向下兼容性后面再补充检测一下。

**Comment by abcfy2** [comment]
路由器的内核没那么好升级吧。小米路由器用的内核还是`2.6.32`的。主要是很多arm嵌入式设备的内核版本普遍偏低，因为硬件更新缓慢的原因

**Comment by xtaci** [comment]
2.6.33就支持了

**Comment by abcfy2** [comment]
主要是RHEL这个毒瘤在，硬生生把`2.6.32`这个版本搞成了LTS时间最长的内核了。现在kernel.org官网终于把`2.6.32`这个版本从LTS列表移除了

**Comment by xtaci** [comment]
这个问题先留在这里吧，很多打了sendmmsg补丁的2.6.32也能支持sendmmsg，看碰到这个问题的多不多

**Comment by xtaci** [comment]
[kcptun-linux-amd64-20190611.tar.gz](https://github.com/xtaci/kcptun/files/3275001/kcptun-linux-amd64-20190611.tar.gz)
可以试下这个fix

**Comment by abcfy2** [comment]
我的是小米路由器的kcptun客户端报错，需要一个arm5版本的

**Comment by xtaci** [comment]
[kcptun-linux-arm5-20190611.tar.gz](https://github.com/xtaci/kcptun/files/3275119/kcptun-linux-arm5-20190611.tar.gz)
[kcptun-linux-arm6-20190611.tar.gz](https://github.com/xtaci/kcptun/files/3275120/kcptun-linux-arm6-20190611.tar.gz)
[kcptun-linux-arm7-20190611.tar.gz](https://github.com/xtaci/kcptun/files/3275121/kcptun-linux-arm7-20190611.tar.gz)

**Comment by abcfy2** [comment]
运行直接报错:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1f0570]

goroutine 15 [running]:
github.com/xtaci/kcp-go.(*UDPSession).readLoop(0x8d40f0)
	/Users/xtaci/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.1+incompatible/readloop_linux.go:31 +0x2c8
created by github.com/xtaci/kcp-go.newUDPSession
	/Users/xtaci/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.1+incompatible/sess.go:178 +0x548

```

**Comment by xtaci** [comment]
[kcptun-linux-arm5-20190611.tar.gz](https://github.com/xtaci/kcptun/files/3275215/kcptun-linux-arm5-20190611.tar.gz)
[kcptun-linux-arm6-20190611.tar.gz](https://github.com/xtaci/kcptun/files/3275216/kcptun-linux-arm6-20190611.tar.gz)
[kcptun-linux-arm7-20190611.tar.gz](https://github.com/xtaci/kcptun/files/3275217/kcptun-linux-arm7-20190611.tar.gz)

可能是一个race问题，fix了下，试试

**Comment by abcfy2** [comment]
嗯，可以运行

**Comment by xtaci** [comment]
小米的固件太恶心了。。。

**Comment by abcfy2** [comment]
小米R2D用的还是openwrt的魔改版，连官方仓库都没法加，用的自带仓库都无法访问了

**Comment by abcfy2** [comment]
我记错了，小米路由器R2D用的内核还不是`2.6.32`的，而是`2.6.36`的:

```
root@XiaoQiang:~# uname -a
Linux XiaoQiang 2.6.36 #3 MiWiFi-R2D-2.25.209 SMP PREEMPT Tue Oct 16 11:45:02 UTC 2018 armv7l GNU/Linux
root@XiaoQiang:~# 
```

这个版本连LTS都不是

**Comment by xtaci** [comment]
我是通过试错来fix的，和版本无关了

**Comment by abcfy2** [comment]
OK，这个issue我就先关了
