### ISSUE TITLE
Hi，解密查看

### ISSUE THREAD

**Issue by RootPeter** [xtaci/kcptun#690]
code 64

JXU0RjVDJXU4MDA1JXU3NTU5JXU0RTBCJXU0RjYwJXU3Njg0YnRjJTIwJXU1NzMwJXU1NzQwJXVGRjBDJXU2MTFGJXU4QzIyJXU0RjYwJXU3Njg0JXU1RjAwJXU2RTkwJXVGRjBDJXU0RTNBJXU0RTg2JXU4QkE5R29vZ2xlJTIwYm90JTIwJXU5MUM3JXU5NkM2JXVGRjBDJXU2MjExJXU0RjdGJXU3NTI4JXU0RTg2JXU4RkQ5JXU3OUNEJXU2NUI5JXU1RjBGJXU3NTU5JXU4QTAwJXVGRjBDJXU2MjExJXU4QkY3JXU0RjYwJXU1NTlEJXU1MUUwJXU2NzZGJXU1NDk2JXU1NTYxJXU0RUU1JXU4ODY4JXU1QzBBJXU2NTZDJXUzMDAy

**Comment by RootPeter** [comment]
base64

**Comment by xtaci** [comment]
1PYa8LWFPGbHP3mcYDhVLYCiEXsSJcqbNm

thanks, it's a new address
