### ISSUE TITLE
问个比较愚蠢的问题

### ISSUE THREAD

**Issue by kxmp** [xtaci/kcptun#691]
服务器和客户端用的mode不一样
那生效的是哪个mode??!

啊.... 刚才用了手动模式 应该是死慢才对 看起来是服务器生效的....

**Comment by jason2000915** [comment]
都生效 都是发送mod 客户端设置就是上传 相对的服务端是你的下载

**Comment by kxmp** [comment]
就是都是对发包的设置是吧.
