### ISSUE TITLE
dscp设定没有用啊

### ISSUE THREAD

**Issue by kxmp** [xtaci/kcptun#692]
刚才客户端设置了一下 发现客户端发送出去的包 dscp是0
然后我又服务端改了下 还是那样

软件都显示的是dscp 46. 就是流量没有dscp标记啊. (封包里面都是0)

![image](https://user-images.githubusercontent.com/6483602/60610894-8aa40a00-9df7-11e9-8021-057dcc125c10.png)
发送和接收的都一样. 都是cs0.

**Comment by kxmp** [comment]
我用了0809最新版客户端 服务端没更新
看了下客户端发送的数据包 dscp还是0  不知道为啥.
是我抓包软件太老了 识别不行么!!!?
![image](https://user-images.githubusercontent.com/6483602/63646161-a0231980-c740-11e9-9644-338d3e5866c5.png)

**Comment by kxmp** [comment]
原来是我使用姿势不对!!

**Comment by mzh741** [comment]
> 原来是我使用姿势不对!!

同样的问题，问下是哪儿不对？

**Comment by k79e** [comment]
这个东西意义不大 是本机走流量的程序多了 用qos就会开启优先级的意思.
> 1. Go to HKLM\System\CurrentControlSet\Services\Tcpip\QoS. If "QoS" folder doesn't exist there - create it.
> 2. Add a DWORD parameter named "Do not use NLA" and assign "1" as its value.
> 3. Reboot.

然后系统有个qos管理器 组策略里面 可以给所有程序的流量打标记.
