### ISSUE TITLE
Dockerfile returned a non-zero code: 2

### ISSUE THREAD

**Issue by P0529** [xtaci/kcptun#693]
The command '/bin/sh -c go get -ldflags "-X main.VERSION=$(date -u +%Y%m%d) -s -w" github.com/xtaci/kcptun/client && go get -ldflags "-X main.VERSION=$(date -u +%Y%m%d) -s -w" github.com/xtaci/kcptun/server' returned a non-zero code: 2

**Comment by xtaci** [comment]
fixed
