### ISSUE TITLE
-TCP模式不通

### ISSUE THREAD

**Issue by PHCSJC** [xtaci/kcptun#695]
KCP版本是20190709

服务器debian9 amd64，客户端arm64，没有问题。
服务器debian9 amd64，客户端debian9，不通。

服务器端命令：
server_linux_amd64 -t 127.0.0.1:443 -l :888 --mode fast2 --mtu 1300 --sndwnd 2048 --nocomp --keepalive 8 --crypt aes --key ******** -tcp

客户端命令：
client_linux_amd64 -r ********:888 -l :889 -mode fast2 --mtu 1300 --rcvwnd 1024 --nocomp --keepalive 8 --crypt aes --key ******** -tcp

不通的错误提示：
2019/07/09 16:54:29 version: 20190709
2019/07/09 16:54:29 initiating key derivation
2019/07/09 16:54:29 listening on: [::]:889
2019/07/09 16:54:29 encryption: aes
2019/07/09 16:54:29 nodelay parameters: 1 20 2 1
2019/07/09 16:54:29 remote address: **********
2019/07/09 16:54:29 sndwnd: 128 rcvwnd: 1024
2019/07/09 16:54:29 compression: false
2019/07/09 16:54:29 mtu: 1300
2019/07/09 16:54:29 datashard: 10 parityshard: 3
2019/07/09 16:54:29 acknodelay: false
2019/07/09 16:54:29 dscp: 0
2019/07/09 16:54:29 sockbuf: 4194304
2019/07/09 16:54:29 smuxbuf: 4194304
2019/07/09 16:54:29 keepalive: 8
2019/07/09 16:54:29 conn: 1
2019/07/09 16:54:29 autoexpire: 0
2019/07/09 16:54:29 scavengettl: 600
2019/07/09 16:54:29 snmplog:
2019/07/09 16:54:29 snmpperiod: 60
2019/07/09 16:54:29 quiet: false
2019/07/09 16:54:29 tcp: true
2019/07/09 16:54:29 SetDSCP: invalid operation
2019/07/09 16:54:29 SetReadBuffer: invalid operation
2019/07/09 16:54:29 SetWriteBuffer: invalid operation
2019/07/09 16:54:29 connection: ****** -> ******
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:01 io: read/write on closed pipe
2019/07/09 16:55:02 session marked as expired ******
2019/07/09 16:55:03 session normally closed ******

**Comment by xtaci** [comment]
expired too fast?

**Comment by PHCSJC** [comment]
> expired too fast?

应该修改什么呢？试了今天的版本还是一样的错误

**Comment by PHCSJC** [comment]
Hi,version 20190711 have same issue,I have tested.and I found kcp-server don't receive any data from client.

**Comment by xtaci** [comment]
在这个thread 谈论， https://github.com/xtaci/kcptun/issues/696
