### ISSUE TITLE
最新版本的mipsle版本无法运行，提示Illegal instruction

### ISSUE THREAD

**Issue by zyworkshop** [xtaci/kcptun#698]
newifi 3 路由，Openwrt系统：
root@Newifi3:~# ./client_linux_mipsle 
Illegal instruction

**Comment by xtaci** [comment]
pre-release的么？

**Comment by zyworkshop** [comment]
是pre-release的。

**Comment by xtaci** [comment]
try again

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/696
