### ISSUE TITLE
最新release的包存放路径不对

### ISSUE THREAD

**Issue by YuXiaoCoder** [xtaci/kcptun#699]
问问题前先搜索ISSUE，并搞清楚下面的问题:

https://github.com/xtaci/kcptun/releases/download/v20170711/kcptun-linux-amd64-20190711.tar.gz
前面是 v20170711，后面是 20190711

**Comment by zhanhb** [comment]
哈哈，一不小心，穿越到两年前了

**Comment by YuXiaoCoder** [comment]
哈哈哈，是的，我是用脚本拼接下载链接，发现问题的

**Comment by zhanhb** [comment]
我的脚本是抓最后的release，我的脚本下载不了pre-release的，手工下载发现不了这个问题

**Comment by zhanhb** [comment]
作者手工打tag辛苦了，可以参考一下这个
[shadowsocks/ChinaDNS/packaging/release.sh#L14-L19](/shadowsocks/ChinaDNS/blob/9e4261c78e911851f76a9b9113d48fcdc44ce32e/packaging/release.sh#L14-L19)

**Comment by xtaci** [comment]
哈哈， 晕了

**Comment by xtaci** [comment]
> 作者手工打tag辛苦了，可以参考一下这个
> [shadowsocks/ChinaDNS/packaging/release.sh#L14-L20](/shadowsocks/ChinaDNS/blob/9e4261c78e911851f76a9b9113d48fcdc44ce32e/packaging/release.sh#L14-L20)

嗯，研究下， assets很多个
