### ISSUE TITLE
UDP over KCPTUN

### ISSUE THREAD

**Issue by bettermanbao** [xtaci/kcptun#70]
请教一下，目前的kcptun是否只支持TCP over UDP？
未来能否实现UDP over KCPTUN？谢谢！

**Comment by xtaci** [comment]
对，可能会支持，目前可以用ovpn承载udp

**Comment by xtaci** [comment]
最好的方式，还是用一个udp转换为tcp的工具，服务器端再tcp转换为udp，相当于承载一个服务。

**Comment by bettermanbao** [comment]
希望新版本能够支持UDP over Kcptun，我主要是用于承载SS的UDP协议。
我之前使用ss-redir在路由器上做TCP和UDP的透明代理，ss-tunnel配合dnsmasq做DNS的UDP转发。
现在新增加了一台orange pi，运行kcptun。因为担心kcptun的稳定性，所以我在路由器上的设置是默认通过orange pi的kcptun中转，如果连接失败，就切换回直连VPS的配置文件。

所以遇到了kcptun不能转发udp数据的问题，我目前的workaround就是udp数据永远直连，反正UDP流量本身不大，TCP默认通过kcptun中转，如果失败则切换回直连。

**Comment by xtaci** [comment]
因为现在的模式是， 一对一端口转发，可能不是UDP那种多个地址的路由。有些冲突，所以还是建议用ovpn over kcptun的模式做UDP转发，多开一对kcptun。
稳定性不用担心，这里都是7x24的。

**Comment by bettermanbao** [comment]
今天改了一下路由器上的设置，把dns请求换成了TCP协议，然后直接走SS的TCP代理。这样至少不影响浏览网页了。于是UDP over KCPTUN的需求也就没有那么强烈了。

**Comment by xtaci** [comment]
是的，你总能找到一个简单的办法就能解决，所以一直没有修改的欲望。

**Comment by nxtreaming** [comment]
尽量用tcp, 别闲着没事就用udp， UDP存在很多不可控因素（不同的运营商对UDP的丢包策略不同，有的运营商会在高峰时段对UDP强制丢包50%以上来给TCP让路）， 只有在很特殊的情况下用UDP才有意义，比如 网络游戏中。

**Comment by pigpigabc123** [comment]
"把dns请求换成了TCP协议"如何实现的，使用ss-redir在路由器上做TCP和UDP的透明代理，ss-tunnel配合dnsmasq做DNS的UDP转发，装上kcptun后ss  fanq失败，不知如何配置

**Comment by bettermanbao** [comment]
@pigpigabc123 把ss-tunnel换成pdnsd

**Comment by pigpigabc123** [comment]
@bettermanbao 不好意思再请教下：原方案是ss-tunnel接收到dnsmasq的dns（udp）请求后通过ss-redir转发给8.8.8.8，如果换成pdnsd后是不是把dnsmasq的dns请求转给pdnsd，那pdnsd的上游dns是直接填8.8.8.8  or 还是需要在vps上搭建dns服务提供给pdnsd

**Comment by bettermanbao** [comment]
直接填8.8.8.8就可以了，8.8.8.8支持tcp查询。

**Comment by pigpigabc123** [comment]
@bettermanbao 已解决，将8.8.8.8 ipset add gfwlis，这样dns请求走ss流量，kcptun加速可以正常使用

**Comment by YihaoPeng** [comment]
可以使用UDPspeeder来加速UDP：
https://github.com/wangyu-/UDPspeeder

**Comment by maxwellzh** [comment]
@YihaoPeng 现在的kcptun已经包含FEC了
