### ISSUE TITLE
OS NOT SUPPORT

### ISSUE THREAD

**Issue by Just-Keep** [xtaci/kcptun#700]
VPS端使用Debian 10，客户端使用win7，版本20190711，分别下载kcptun-linux-amd64-20190711.tar.gz
和kcptun-windows-amd64-20190711.tar.gz，设置参数使用TCP模式。在客户端运行时显示不支持的系统（OS NOT SUPPORT）。

**Comment by maxwellzh** [comment]
看说明，-tcp只支持linux

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/696
