### ISSUE TITLE
在单位上外网需要设置内网代理，kcptun有没有设置代理的选项？

### ISSUE THREAD

**Issue by BenzLeung** [xtaci/kcptun#702]
单位的电脑是 Win10 的，在单位，系统需要设置个 172.18.x.x 的代理服务器才能连上外网，否则连 baidu 也打不开。

kcptun 似乎并不会自动走系统代理，我仔细看了好几遍 kcptun 的参数列表，也没找到代理设置的选项。

同样的配置，同样是 Win10，家里电脑就正常。

请问我该如何在单位用上 kcptun？

**Comment by maxwellzh** [comment]
kcptun就是个端口转发工具

**Comment by zhanhb** [comment]
默认的系统代理只有http代理吧？kcptun默认是udp传输的，理论上应该穿透不了http的

**Comment by zhanhb** [comment]
如果公司的代理支持socks5的话，我想到的最简单的方案是三级跳，中间需要一台国内的服务器做支撑。
