### ISSUE TITLE
-tcp not support mac os with client mode

### ISSUE THREAD

**Issue by AlbertZhao** [xtaci/kcptun#703]
server side is : Centos7
client side is: Mac OS

when run the below command on Mac OS got errors:
./client_darwin_amd64 -tcp -c conf.json

2019/07/13 19:52:48 dscp: 46
2019/07/13 19:52:48 sockbuf: 4194304
2019/07/13 19:52:48 smuxbuf: 4194304
2019/07/13 19:52:48 keepalive: 10
2019/07/13 19:52:48 conn: 1
2019/07/13 19:52:48 autoexpire: 0
2019/07/13 19:52:48 scavengettl: 600
2019/07/13 19:52:48 snmplog: 
2019/07/13 19:52:48 snmpperiod: 60
2019/07/13 19:52:48 quiet: false
2019/07/13 19:52:48 tcp: true
2019/07/13 19:52:48 re-connecting: dial(): tcpraw.Dial(): os not supported
2019/07/13 19:52:49 re-connecting: dial(): tcpraw.Dial(): os not supported
2019/07/13 19:52:50 re-connecting: dial(): tcpraw.Dial(): os not supported
2019/07/13 19:52:51 re-connecting: dial(): tcpraw.Dial(): os not supported
2019/07/13 19:52:52 re-connecting: dial(): tcpraw.Dial(): os not supported
2019/07/13 19:52:53 re-connecting: dial(): tcpraw.Dial(): os not supported
2019/07/13 19:52:54 re-connecting: dial(): tcpraw.Dial(): os not supported

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/696

**Comment by AlbertZhao** [comment]
> #696

This issue also happens on tag/v20190713.  The server side works fine and only happens on client side. Can you hep check this?

**Comment by AlbertZhao** [comment]
oh, ic. just checked your source code, you used iptables. It is not support OSX

**Comment by maxwellzh** [comment]
xtaci wrote it clearly at release notes
> -tcp only supports Linux OS.
