### ISSUE TITLE
同样的服务器，协议kcptun不稳定，改成tcp后基本稳定。谢谢作者辛苦了

### ISSUE THREAD

**Issue by becapital** [xtaci/kcptun#707]
问问题前先搜索ISSUE，并搞清楚下面的问题:

1. 检查 ```-key xxx``` 至少三遍, ***保证***两边一致。
2. 保证```-nocomp, -datashard, -parityshard,  -key, -crypt```两边一致。
3. 是否在服务器端，正确设定了转发的目标服务器地址 ***--target***。
4. 如果第3条不确定，尝试在服务器上telnet target port试试。
5. 防火墙是否关闭了UDP通信。
6. 两端的版本是否一致？
7. 是不是最新版本？
8. 两端分别是什么操作系统？
9. 两端的输出日志是什么？

Before firing issue, make sure you figured out the following common questions.

PLEASE DO SEARCH FIRST.

1. Check your ```-key xxx``` for at least 3 times, ***MAKE SURE*** both sides share the same secret.
2. ```-nocomp, -datashard, -parityshard,  -key, -crypt``` ***must be the same*** on both side.
3. Did you correctly set the ***-target*** on the server side?
4. ***MAKE SURE*** ```telnet target port``` on your server successful(don't ask me why couldn't).
5. Does your ***firewall allows UDP*** communications? (including your ISP Cable-Modem)
6. Are you using the **same version** for both client & server
7. Are you using the **latest release**?
8. Which **OS** do you use?
9. Which end for this issue related to, **client or server**?

**Comment by xtaci** [comment]
欢迎捐赠

**Comment by keeno1982** [comment]
@becapital 请问一下你是直接在配置加--tcp就能工作了吗？加tcp的好处是不是可以避免被Qos？

**Comment by testcaoy7** [comment]
@xtaci 很久没来了，刚刚看到加了TCP，请问TCP只能用于Linux吗？Windows和BSD不受支持？

**Comment by xtaci** [comment]
@testcaoy7 对，只适用于linux。mips/arm都可以，不是很愿意去支持windows 和bsd系列，这类平台可以考虑用docker方式运行。

**Comment by testcaoy7** [comment]
@xtaci 刚刚试用了TCP模式，表现非常不错，很容易就稳定了。请问这个TCP是伪装吧，实质还是UDP？

**Comment by xtaci** [comment]
> @xtaci 刚刚试用了TCP模式，表现非常不错，很容易就稳定了。请问这个TCP是伪装吧，实质还是UDP？

是的，告诉IP层的是TCP流，而不是UDP。

**Comment by zxlhhyccc** [comment]
> > @xtaci 刚刚试用了TCP模式，表现非常不错，很容易就稳定了。请问这个TCP是伪装吧，实质还是UDP？
> 
> 是的，告诉IP层的是TCP流，而不是UDP。

我用tcp根本不工作，难道你们在服务端不开启tcp？

**Comment by sxml** [comment]
大佬 求教要开启tcp 服务端 客户端 要添加什么参数？
