### ISSUE TITLE
dial tcp: lookup ip on ***:53: no such host

### ISSUE THREAD

**Issue by xx5ll** [xtaci/kcptun#710]
服务端日志
2019/08/12 00:26:01 initiating key derivation
2019/08/12 00:26:01 listening on: [::]:9999
2019/08/12 00:26:01 target: ip:8848
2019/08/12 00:26:01 encryption: none
2019/08/12 00:26:01 nodelay parameters: 1 20 2 0
2019/08/12 00:26:01 sndwnd: 512 rcvwnd: 512
2019/08/12 00:26:01 compression: true
2019/08/12 00:26:01 mtu: 1350
2019/08/12 00:26:01 datashard: 10 parityshard: 3
2019/08/12 00:26:01 acknodelay: false
2019/08/12 00:26:01 dscp: 0
2019/08/12 00:26:01 sockbuf: 4194304
2019/08/12 00:26:01 smuxbuf: 4194304
2019/08/12 00:26:01 keepalive: 10
2019/08/12 00:26:01 snmplog: /var/log/kcptun/snmplog.log
2019/08/12 00:26:01 snmpperiod: 60
2019/08/12 00:26:01 pprof: false
2019/08/12 00:26:01 quiet: false
2019/08/12 00:26:01 tcp: false
2019/08/12 00:26:03 remote address: ****:64060
2019/08/12 00:26:32 remote address: ****:64121
2019/08/12 00:26:33 io: read/write on closed pipe
2019/08/12 00:26:34 dial tcp: lookup ip on 192.168.41.1:53: no such host
2019/08/12 00:26:34 dial tcp: lookup ip on 192.168.41.1:53: no such host
2019/08/12 00:26:34 dial tcp: lookup ip on 192.168.41.1:53: no such host
2019/08/12 00:26:34 dial tcp: lookup ip on 192.168.41.1:53: no such host

客户端日志：
2019/08/11 23:00:41 version: 20190809
2019/08/11 23:00:41 initiating key derivation
2019/08/11 23:00:41 listening on: [::]:8848
2019/08/11 23:00:41 encryption: none
2019/08/11 23:00:41 nodelay parameters: 1 20 2 0
2019/08/11 23:00:41 remote address: ****:9999
2019/08/11 23:00:41 sndwnd: 512 rcvwnd: 512
2019/08/11 23:00:41 compression: true
2019/08/11 23:00:41 mtu: 1350
2019/08/11 23:00:41 datashard: 10 parityshard: 3
2019/08/11 23:00:41 acknodelay: false
2019/08/11 23:00:41 dscp: 0
2019/08/11 23:00:41 sockbuf: 4194304
2019/08/11 23:00:41 smuxbuf: 4194304
2019/08/11 23:00:41 keepalive: 10
2019/08/11 23:00:41 conn: 1
2019/08/11 23:00:41 autoexpire: 0
2019/08/11 23:00:41 scavengettl: 600
2019/08/11 23:00:41 snmplog:
2019/08/11 23:00:41 snmpperiod: 60
2019/08/11 23:00:41 quiet: false
2019/08/11 23:00:41 tcp: false
2019/08/11 23:00:41 connection: 0.0.0.0:59287 -> ****:9999
2019/08/11 23:00:56 stream opened in: 127.0.0.1:59857 out: ****:9999(3)
2019/08/11 23:00:59 stream opened in: 127.0.0.1:59863 out: ****:9999(5)
2019/08/11 23:01:02 stream closed in: 127.0.0.1:59863 out: ****:9999(5)
2019/08/11 23:01:02 stream closed in: 127.0.0.1:59857 out: ****:9999(3)
2019/08/11 23:01:02 stream opened in: 127.0.0.1:59876 out: ****:9999(7)
2019/08/11 23:01:02 stream opened in: 127.0.0.1:59877 out: ****:9999(9)
2019/08/11 23:01:07 stream closed in: 127.0.0.1:59876 out: ****:9999(7)
客户端是Win10，服务端是CentOs7

服务端总是报错
2019/08/12 00:26:34 dial tcp: lookup ip on 192.168.41.1:53: no such host

服务端是虚拟机，用了NAT，192.168.41.1为服务端物理机的IP。修改 /etc/resolv.conf也没有用，依然是53端口报错。没找到相关的issues

**Comment by sweetweapen** [comment]
检查下你服务器端执行的程序是“server”端么，别一时失误，启动的也是客户端程序

**Comment by xtaci** [comment]
自己检查dns
