### ISSUE TITLE
KCPTUN 报错

### ISSUE THREAD

**Issue by sifksky** [xtaci/kcptun#713]
近期HK问题严重，翻墙屡次被封。SS服务器在香港，过不了多久KCPTUN 客户端和服务器就会报：
2019/08/21 02:31:08 io: read/write on closed pipe
2019/08/21 02:46:14 io: read/write on closed pipe

导致翻墙被中断，重启kcptun 客户端后又能正常工作一段时间，请问如何解决此问题，谢谢。

**Comment by sifksky** [comment]
kcptun 服务器客户端均使用  kcptun version 20190809

**Comment by xtaci** [comment]
试试两端加上 `-tcp`
