### ISSUE TITLE
macOS Mojave 10.14.6 出错无法运行

### ISSUE THREAD

**Issue by uax** [xtaci/kcptun#716]
macOS Mojave 10.14.6
直连ss不经过kcptun，正常。
通过kcptun：
最新的kcptun-darwin-amd64-20190809无法运行：
**re-connecting: dial(): tcpraw.Dial(): os not supported**
服务端/客户端版本一直，参数无误。
客户端版本切换回挨个试了一遍：
kcptun-darwin-amd64-20190424： 
**stream closed
2019/08/31 18:07:56 session marked as expired**

kcptun-darwin-amd64-20190611：
**019/08/31 18:09:32 stream opened in: 127.0.0.1:61472 out: <nil>(3)
2019/08/31 18:09:32 stream opened in: 127.0.0.1:61473 out: <nil>(5)
2019/08/31 18:09:32 stream opened in: 127.0.0.1:61474 out: <nil>(7)
2019/08/31 18:09:32 stream opened in: 127.0.0.1:61475 out: <nil>(9)
2019/08/31 18:09:32 stream opened in: 127.0.0.1:61476 out: <nil>(11)
2019/08/31 18:09:39 stream opened in: 127.0.0.1:61479 out: <nil>(13)
2019/08/31 18:09:39 stream opened in: 127.0.0.1:61481 out: <nil>(15)
2019/08/31 18:09:48 stream closed in: 127.0.0.1:61481 out: <nil>(15)
2019/08/31 18:09:48 stream closed in: 127.0.0.1:61474 out: <nil>(7)
2019/08/31 18:09:48 stream closed in: 127.0.0.1:61476 out: <nil>(11)
2019/08/31 18:09:48 stream closed in: 127.0.0.1:61472 out: <nil>(3)
2019/08/31 18:09:48 stream closed in: 127.0.0.1:61479 out: <nil>(13)
2019/08/31 18:09:48 stream closed in: 127.0.0.1:61473 out: <nil>(5)
2019/08/31 18:09:48 stream closed in: 127.0.0.1:61475 out: <nil>(9)
2019/08/31 18:09:48 session marked as expired <nil>**

**Comment by xtaci** [comment]
-tcp 只支持linux

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/696
