### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by LZS535261548** [xtaci/kcptun#718]
大牛
支持iOS吗
如果不支持,能不能帮忙说明下原因

**Comment by xtaci** [comment]
不支持，因为我不会写swift

**Comment by BH4WHN** [comment]
我也想要ios，现在靠家里的宽带中转kcp，被查水表风险太大了

**Comment by GTGraphics3** [comment]
iOS有软件，需要用美区ID下载
Shadowrocket，要几刀

**Comment by Henry586** [comment]
> iOS有软件，需要用美区ID下载 Shadowrocket，要几刀

去万能的T宝购买 ShadowRocket (小火箭) ，几个人民币就可以搞定了，记得kcptun插件mode选择normal, 我尝试过fast3无法连接server，换成normal就好了。

**Comment by ddzx** [comment]
你想干嘛？

**Comment by sylvan99** [comment]
> > iOS有软件，需要用美区ID下载 Shadowrocket，要几刀
> 
> 去万能的T宝购买 ShadowRocket (小火箭) ，几个人民币就可以搞定了，记得kcptun插件mode选择normal, 我尝试过fast3无法连接server，换成normal就好了。

kcptun的插件在哪买

**Comment by Liloker** [comment]
> > iOS有软件，需要用美区ID下载 Shadowrocket，要几刀
> 
> 去万能的T宝购买 ShadowRocket (小火箭) ，几个人民币就可以搞定了，记得kcptun插件mode选择normal, 我尝试过fast3无法连接server，换成normal就好了。

可以看下你小火箭里关于kcptun的配置吗？normal，fast，fast2，fast3都试过了不行。

我小火箭里配置Trojan+kcptun插件服务端日志显示总是连上又断开(如图)
![image](https://github.com/xtaci/kcptun/assets/55574496/55e0b3a4-f1bd-4757-92dd-48a971ab3c4e)
，单独用trojan可以，win11上用kcptun客户端+trojan也正常(pc上用的v2ray客户端)

另外mac使用最新版2.2.46小火箭也一样情况。
