### ISSUE TITLE
一个在windows上使用-tcp参数的想法

### ISSUE THREAD

**Issue by maxwellzh** [xtaci/kcptun#719]
有没有人试过在WSL上运行kcptun然后为windows端的软件转发流量呢？我印象中WSL的本地端口和windows是互通的，理论上感觉可行。
等我有空会尝试一下同步上来

**Comment by xtaci** [comment]
WSL2可能可以，1是阉割了的。你可以用 docker运行

**Comment by maxwellzh** [comment]
> WSL2可能可以，1是阉割了的。你可以用 docker运行

WSL2目前只有预览版有……实在不想用bug一堆的预览版。docker for windows需要hyper-V，我的家庭版不支持
看来依然没有很好的解决办法，等明年windows更新吧

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/696

**Comment by xtaci** [comment]
另外我并不喜欢-tcp，因为tcp的控制信号能直接让路由器的nat表RST。
