### ISSUE TITLE
需要一个完整的编译脚本

### ISSUE THREAD

**Issue by wang20150419** [xtaci/kcptun#72]
没玩过go语言，想自己编译一下这个项目，运行 build-release.sh 不成功。
我的想法：如果能自己编译的话，就想改造一下 key，让它动态化（这个是私有的，
如果kcptun本身含这样的代码，是不是容易被识别？），这样就可以完全避免GFW
的特征检测，提高VPS的成活率。
    当然了，我对kcptun的内部原理、加密等，完全不清楚，纯粹是一个想法。

**Comment by xtaci** [comment]
所有的release就是这个脚本编译出来的，如果不熟悉go，建议先熟悉基本结构。
