### ISSUE TITLE
installation with command 'go get' failure

### ISSUE THREAD

**Issue by Amankwah** [xtaci/kcptun#727]
9. Which **OS** do you use?
CentOS 7.7/Gentoo
10. Which end for this issue related to, **client or server**?
Both

I have tried to install kcptun with command 'go get' from github.com. However, just got an error message below:

package github.com/xtaci/smux/v2: cannot find package "github.com/xtaci/smux/v2" in any of:
	$GOROOT/src/github.com/xtaci/smux/v2 (from $GOROOT)
	$GOPATH/src/github.com/xtaci/smux/v2 (from $GOPATH)

My command was: got get -u -v github.com/xtaci/kcptun/server

I've tried the go binary from golang site with version 1.12.9/1.12.10/1.13.1

**Comment by xtaci** [comment]
export GO111MODULE=on

**Comment by Amankwah** [comment]
> export GO111MODULE=on

It works!
Great thanks to you!
