### ISSUE TITLE
疑似内存泄露

### ISSUE THREAD

**Issue by de-conf** [xtaci/kcptun#728]
客户端为openwrt,kcptun版本为关于20190924版本
出现内存泄露,问题严重,大约3-4天占满500M内存,重启kcptun进程可解决!
未启用最新参数--smuxver

**Comment by xtaci** [comment]
截图内存使用量, 如果不启用-smuxver2，只修正了几个参数bug而已

**Comment by maxwellzh** [comment]
是不是`datashard`和`parityshard`太大了，参考#677

**Comment by de-conf** [comment]
> 截图内存使用量, 如果不启用-smuxver2，只修正了几个参数bug而已

![image](https://user-images.githubusercontent.com/26062629/65827833-01518600-e2c7-11e9-81e4-4967999167ff.png)

**Comment by de-conf** [comment]
客户端使用参数如下:
```
{
        "remoteaddr": "server_ip",
        "localaddr": "127.0.0.1:2048",
        "key": "password",
        "crypt": "aes-128",
        "mode": "fast3",
        "conn": 6,
        "autoexpire": 180,
        "mtu": 1350,
        "sndwnd": 512,
        "rcvwnd": 1024,
        "datashard": 30,
        "parityshard": 15,
        "dscp": 46,
        "sockbuf": 4194304,
        "keepalive": 10,
        "snmpperiod": 60,
        "nocomp": true,
        "acknodelay": false,
        "quiet": true,
        "tcp": false
}
```

**Comment by xtaci** [comment]
负载有多大

**Comment by de-conf** [comment]
一个小时过去了
![image](https://user-images.githubusercontent.com/26062629/65828602-2c3fd800-e2cf-11e9-9bcc-233feb3d4154.png)

**Comment by xtaci** [comment]
GOGC=30 client_linux_xxxxx 这样， 我运行了一周，大概在30MB RES

**Comment by de-conf** [comment]
> 负载有多大，切回以前的版本就没有问题么？你试试在启动脚本中，设置GOGC=30环境变量。
> x86环境我无法重现此问题。

以前环境也是有这个问题的!我这个好像的是从v20190809开始的,
` GOGC ` 直接expoer到环境变量吗?
另外我这个不是 x86是armV7
```
processor       : 0
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 1600.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

processor       : 1
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 1600.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

Hardware        : Marvell Armada 380/385 (Device Tree)
Revision        : 0000
Serial          : 0000000000000000
````

**Comment by xtaci** [comment]
你先试试在启动时  GOGC=30 ./client_linuxxxxxx

**Comment by de-conf** [comment]
> 你先试试在启动时 GOGC=30 ./client_linuxxxxxx

ok,我先试试

**Comment by de-conf** [comment]
> 你先试试在启动时 GOGC=30 ./client_linuxxxxxx

![image](https://user-images.githubusercontent.com/26062629/65828682-11219800-e2d0-11e9-82b1-77985d48777b.png)
貌似有效,待我测试下

**Comment by de-conf** [comment]
> 你先试试在启动时 GOGC=30 ./client_linuxxxxxx
> 如果还不行，调整 -datashard parityshard 到 10:5或者 2:1

好的,感谢!

**Comment by de-conf** [comment]
> 你先试试在启动时 GOGC=30 ./client_linuxxxxxx
> 如果还不行，调整 -datashard parityshard 到 10:5或者 2:1

![image](https://user-images.githubusercontent.com/26062629/65828737-9311c100-e2d0-11e9-8fab-c56a004ac9c5.png)
貌似在缓慢上升中
RES 21548----->30744 (最新

**Comment by xtaci** [comment]
等稳定， 如果有效，可以调至更低，例如 GOGC=20， 不过首先建议尝试降低FEC比值

**Comment by xtaci** [comment]
低速CPU如果来不及垃圾回收，会出现这个情况，这个参数会增加回收频率。

**Comment by de-conf** [comment]
好的,感谢说明,但是CPU占有率并不高啊,Go是立即回收的吗?

**Comment by xtaci** [comment]
内存本来就不多，调低你也感觉不到CPU的变化。不是立即回收。

**Comment by xtaci** [comment]
问题解决了么？

**Comment by laikitleung** [comment]
在NanoPi R1S-H5上同樣出現這種情況，RES緩慢增長
CPU: Allwinner H5, Quad-core 64-bit high-performance Cortex A53
DDR3 RAM: 512MB
固件Openwrt 4.14.111
