### ISSUE TITLE
20191104版本无法兼容旧版本（smuxver=1）

### ISSUE THREAD

**Issue by shell12345** [xtaci/kcptun#736]
服务端升级20191104后，服务器端设置为smuxver=1
客服端低版本 20190924 显示，
smux invalid version error
客服端同为smuxver=1
客服端更新20191104后错误消除，连接正常。
其实电脑端可以同时更新版本，但是手机端依赖
https://github.com/shadowsocks/kcptun-android/releases
新版本20191104能不能兼容旧版本？主要是兼容Android kcptun 插件。

**Comment by xtaci** [comment]
默认smuxver=1，兼容的， 如果出现错误，可能是其它原因引起的，比如parity datashard设置的不一致。

**Comment by maxwellzh** [comment]
我遇到了同样的问题，感觉是安卓ss插件的问题，其他平台是兼容的。
暂时的解决方法是server开两个版本的kcptun，一个0924专门给安卓端用，另一个同步最新kcptun的release给其他平台。kcptun-android项目好像挺久没更新了，只能暂时这样

**Comment by xtaci** [comment]
非官方编译版本就不太清楚了

**Comment by asypost** [comment]
我也遇到了同样的问题。

**Comment by cool168** [comment]
遇到同样的问题，官方版本兼容，android的插件不兼容。

**Comment by xtaci** [comment]
https://github.com/shadowsocks/kcptun-android/issues
可以和作者一起讨论下

**Comment by cdb0y511** [comment]
@xtaci  I have posted the issue.
I really hope you can solve it. I think a lot of Android users heavily depend on it.
thanks.

**Comment by xtaci** [comment]
```
    github.com/xtaci/smux v1.4.4
    github.com/xtaci/smux/v2 v2.0.11
```
smux 
v1 依赖 v1.4.4
v2 依赖 v2.0.11 

比较奇怪为什么不兼容

**Comment by xtaci** [comment]
> @xtaci I have posted the issue.
> I really hope you can solve it. I think a lot of Android users heavily depend on it.
> thanks.

good

**Comment by maxwellzh** [comment]
> ```
>   github.com/xtaci/smux v1.4.4
>   github.com/xtaci/smux/v2 v2.0.11
> ```
> 
> smux
> v1 依赖 v1.4.4
> v2 依赖 v2.0.11
> 
> 比较奇怪为什么不兼容

0924的兼容，1107不兼容，和#737问题一样，应该是中间的commit改变了什么

**Comment by xtaci** [comment]
0924之后,smux没有任何commit

**Comment by xtaci** [comment]
我曾经出现过smux invalid version error的唯一原因是：
FEC参数两头不一致导致的。调整为一致后消失。

**Comment by lzfmars** [comment]
同样的问题，先升了服务器端的kcptun 1107，然后客户端（0924）就不通了，然后把客户端也升级为1107才可以上网

**Comment by xtaci** [comment]
如果是android我不清楚怎么回事， 如果是之前0924和1107不通， 检查启动时候输出的smux version是否一致。

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20191109
清理了下环境，重编译了下提交，暂时想不到为什么

**Comment by maxwellzh** [comment]
> https://github.com/xtaci/kcptun/releases/tag/v20191109
> 清理了下环境，重编译了下提交，暂时想不到为什么

没有windows版本

**Comment by maxwellzh** [comment]
实测`server0924Ubuntu---client1109macOS`可用

**Comment by xtaci** [comment]
那可能是编译的时候没有注意去设置GO111MODULE=on， 恰好我本地又有临时的smux v2。。。所以导致的这个问题。
针对这个问题，build-releash.sh会强行设置GO111MODULE=on了。
