### ISSUE TITLE
20191107 smuxver=1/2速度明显差异

### ISSUE THREAD

**Issue by maxwellzh** [xtaci/kcptun#737]
```
server=20191107, os=Ubuntu18.04
client=20191107, os=macOS10.15.1
```
smux=1时速度
<img width="541" alt="截屏2019-11-08上午2 08 18" src="https://user-images.githubusercontent.com/32546978/68415420-483b7100-01cd-11ea-8796-f8f2493439c4.png">
<img width="558" alt="截屏2019-11-08上午2 07 57" src="https://user-images.githubusercontent.com/32546978/68415426-4b366180-01cd-11ea-92c3-8425450e0ac3.png">
<img width="561" alt="截屏2019-11-08上午2 07 31" src="https://user-images.githubusercontent.com/32546978/68415433-4e315200-01cd-11ea-8d19-883e3fc01f9b.png">

smux=2（测了三次都一样）
<img width="480" alt="截屏2019-11-08上午2 10 22" src="https://user-images.githubusercontent.com/32546978/68415464-63a67c00-01cd-11ea-9733-f45c03af7a6a.png">

感觉挺奇怪的，似乎是11月份的build才有这个问题，之前我一直用的是smux=1，但是更新了最新的1107后发现smux=1速度明显变慢；改成smux=2就能达到正常速度

**Comment by maxwellzh** [comment]
configuration（都基本是默认，应该没什么关系）
```
client_darwin_amd64 -l :port0 -r [ipv6 addr]:port1 --key mypassword --crypt none --mode fast3 --quiet --autoexpire 60 --rcvwnd 1024 
```

**Comment by PHCSJC** [comment]
smuxver，这个好像是和内存有关吧？你的内存太小了？

**Comment by xtaci** [comment]
有点意思啊

**Comment by xtaci** [comment]
smuxver的流量更平衡，平衡会影响测速么，很有趣

**Comment by maxwellzh** [comment]
@xtaci 应该不是smuxver的问题，用0924测试无论smuxver=1还是2速度都基本一致。
这样的情况只发生在1107上（中间的build没尝试过），所以我推断是中间的某个commit导致了这个问题

**Comment by xtaci** [comment]
需要观察下，应该没有改动

**Comment by malagebidi** [comment]
这次升级了过后，youtube实测是慢了很多，改smuxver=2速度又回来了。

**Comment by xtaci** [comment]
相当诡异了

**Comment by yjd** [comment]
刚更新支持smuxver的版本（最近20190611旧版掉速严重）。正好相反。1的速度和旧版差不多还比较稳。2的慢一半

**Comment by xtaci** [comment]
moved to https://github.com/xtaci/kcptun/issues/736
