### ISSUE TITLE
有没有大佬能帮助解答下这些参数的关系：sockbuf smuxbuf streambuf 

### ISSUE THREAD

**Issue by gitrootid** [xtaci/kcptun#738]
有没有大佬能帮助解答下这些参数的关系：
sockbuf smuxbuf streambuf 
看了文档还是有点云里雾里的，不知道怎么配置这几个参数是最好的

**Comment by xtaci** [comment]
sockbuf增大，防止内核的socket buffer填满后被内核丢弃
streambuf，单条流的最大内存临时占用量
smuxbuf，所有流总共的最大内存临时暂用量，streambuf*N条流 <=smuxbuf

**Comment by gitrootid** [comment]
感谢大神的回复 ！！
