### ISSUE TITLE
建议kcp的tcp模式可以再伪装成http或tls

### ISSUE THREAD

**Issue by PHCSJC** [xtaci/kcptun#745]
原因是，当地联通从9月份开始Qos，只要是加密流量，全部不定时断流，不管是TCP,UDP还是KCP，目前只有一个方法可以避免被断流，就是伪装成http或https，现在也有软件可以伪装成http或https，但伪装后又不能多倍发包，速度又上不去了。

最近发现大佬的kcptun支持TCP模式了，比之前更稳了，速度也有保障，如果能在这个基础上再伪装成http或https就更完美了，不知道大佬能否考虑下？

**Comment by xtaci** [comment]
这就不考虑了，此类功能会膨胀到未知领域了。

**Comment by xtaci** [comment]
连socks5这种只需要3行代码就可以引入的功能，我都不会支持，http就更不考虑了。

**Comment by PHCSJC** [comment]
好的，谢谢

**Comment by sxml** [comment]
哪位大佬可以弄 小鸡没kcp用不了
