### ISSUE TITLE
iperf3来测试kcptun的速度（带宽）是否有说服力

### ISSUE THREAD

**Issue by maxwellzh** [xtaci/kcptun#746]
我写了一个kcptun自动测速的[小脚本](https://github.com/maxwellzh/TestKCPTUN)，使用了iperf3作为端测速工具，想问一下如果我想模拟文件下载的话，iperf3的`interval`, `time`, `windows`这些参数会不会带来测试偏差。

**Comment by xtaci** [comment]
不错啊，iperf3我没用过，原则上是对端从收到第一个byte开始，收到已知长度size的数据，除以时间t。这种比较准确。  
测速的主要问题还是波动，国际链路丢包率在 30%～1%波动都有可能。

**Comment by maxwellzh** [comment]
> 不错啊，iperf3我没用过，原则上是对端从收到第一个byte开始，收到已知长度size的数据，除以时间t。这种比较准确。
> 测速的主要问题还是波动，国际链路丢包率在 30%～1%波动都有可能。

是的，理论上我希望得到的是某个瞬时（或者短时间内）的网络情况，但是因为
1. 测速时间范围内网络波动
2. 测速和实际使用中网络波动
就会导致测速的结果并不能完美反映网络情况，最多说是作为一个参考了

**Comment by xtaci** [comment]
如果能用逼近的方式得到一个最大值，也是不错的。可以辅助设定参数。

**Comment by maxwellzh** [comment]
> 如果能用逼近的方式得到一个最大值，也是不错的。可以辅助设定参数。

目前写的都是把参数离散化然后遍历的，之后看看怎么把几个buffer参数和改成连续逼近方式搜索。
btw, happy new year.
