### ISSUE TITLE
openwrt mipsle 不能读取配置文件

### ISSUE THREAD

**Issue by yiguihai** [xtaci/kcptun#747]
root@OpenWrt:/tmp/ss#kcptun -c /tmp/ss/conf/kcptun.json
2020/01/04 13:48:45 version: 20200103
2020/01/04 13:48:45 smux version: 2
2020/01/04 13:48:45 listening on: [::]:12948
2020/01/04 13:48:45 encryption: none
2020/01/04 13:48:45 nodelay parameters: 1 20 2 1
2020/01/04 13:48:45 remote address: vps:29900
2020/01/04 13:48:45 sndwnd: 87 rcvwnd: 87
2020/01/04 13:48:45 compression: false
2020/01/04 13:48:45 mtu: 512
2020/01/04 13:48:45 datashard: 10 parityshard: 3
2020/01/04 13:48:45 acknodelay: false
2020/01/04 13:48:45 dscp: 0
2020/01/04 13:48:45 sockbuf: 16777217
2020/01/04 13:48:45 smuxbuf: 16777217
2020/01/04 13:48:45 streambuf: 2097152
2020/01/04 13:48:45 keepalive: 10
2020/01/04 13:48:45 conn: 1
2020/01/04 13:48:45 autoexpire: 0
2020/01/04 13:48:45 scavengettl: 600
2020/01/04 13:48:45 snmplog:
2020/01/04 13:48:45 snmpperiod: 60
2020/01/04 13:48:45 quiet: false
2020/01/04 13:48:45 tcp: false
2020/01/04 13:48:45 initiating key derivation
2020/01/04 13:48:45 key derivation done
2020/01/04 13:48:45 re-connecting: dial(): lookup vps on 127.0.0.1:53: no such host
2020/01/04 13:48:46 re-connecting: dial(): lookup vps on 127.0.0.1:53: no such host
2020/01/04 13:48:47 re-connecting: dial(): lookup vps on 127.0.0.1:53: no such host
2020/01/04 13:48:48 re-connecting: dial(): lookup vps on 127.0.0.1:53: no such host
2020/01/04 13:48:49 re-connecting: dial(): lookup vps on 127.0.0.1:53: no such host
^C
root@OpenWrt:/tmp/ss# ls
bin       conf      start.sh
root@OpenWrt:/tmp/ss# cat /tmp/ss/conf/kcptun.json
{
    "listen": "127.0.0.1:1027",
    "target": "xxx:2",
    "key": "xxx",
    "crypt": "none",
    "mode": "manual",
    "mtu": 512,
    "sndwnd": 87,
    "rcvwnd": 87,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 1,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 16777217,
    "smuxver": 2,
    "smuxbuf": 16777217,
    "streambuf": 2097152,
    "keepalive": 10,
    "pprof":false,
    "quiet":false,
    "tcp":false
root@OpenWrt:/tmp/ss#

目前只能用命令行参数了

**Comment by xtaci** [comment]
检查下json格式是否正确
https://jsonlint.com/
