### ISSUE TITLE
win10 的子系统 ubuntu 18.04 下运行 kcp 外加 tcp 连接

### ISSUE THREAD

**Issue by wmjlxl** [xtaci/kcptun#752]
大佬， win10 的下的子系统 ubuntu 18.04 下运行 kcp 外加 tcp 连接。

出现 " socket: protocol not supported" 的错误提示。 同一套文件，在 mac 下的虚拟机 ubuntu 是可以执行的。

请问该如何设置 才可以用 tcp 连接？

谢谢。

**Comment by xtaci** [comment]
WSL 是不支持raw socket的，没有办法， WSL2可以

**Comment by wmjlxl** [comment]
明白了，谢谢 大神。
