### ISSUE TITLE
关于老mips内核的新进展

### ISSUE THREAD

**Issue by xinghusp** [xtaci/kcptun#76]
#57 这里描述了我遇到的问题
近期重新尝试了一下，如果使用gccgo编译，能够成功在老内核上跑ListenTCP的代码
但是kcp-go却无法通过gccgo的编译
错误如图
![image](https://cloud.githubusercontent.com/assets/18201606/17215450/79515854-550f-11e6-81e4-be2bfe503843.png)

求大大指个方向，如何处理？

**Comment by xtaci** [comment]
#79
