### ISSUE TITLE
最新版使用有降速现象

### ISSUE THREAD

**Issue by yjd** [xtaci/kcptun#761]
环境：windows  kcptun-windows-amd64-20200226.tar.gz

前几天更新到最新版，使用一段时间后看y2b的速度会降到很低800-2000浮动
然后把客户端重新启动一下就恢复到以前的速度1-2万的水平。
这个现象就这样一直循环。
不过有一点好处是这几天用下来再也没被QOS或GFW截断。

上一个版本或之前的版本大概已经有一年时间如果满速看y2b久点经常会被QOS或GFW截断。
然后切换到走tcp的ss用一段时间，等过了再切回UDP。（这段时间长期没开iptables）

配置一直没动过，但最近把vps的iptables开起来了，只开放监听端口，不知道这个有没有影响。

**Comment by xtaci** [comment]
一年前的版本应该是有个bug的，所以是不正常的，这个版本你可以适当的调大-rcvwnd 来提速

**Comment by xtaci** [comment]
iptables只要没有限制ratelimit就不会有影响

**Comment by yjd** [comment]
> 一年前的版本应该是有个bug的，所以是不正常的，这个版本你可以适当的调大-rcvwnd 来提速

是20200226之前的版本都和这个版本不同。不是我一直用一年前的版本。每个版本一更新我都同时跟进。
刚开始速度和以前任何版本是一样的，然后用一段时间速度就会慢慢降速。然后重启后就又恢复最高的速度，过一段时间又会慢慢降速，时间长短不固定（有时候也可能跟国际线路拥堵有关，持续时间长短不固定）。

回头我调整-rcvwnd看看有没有变化。再观察一段时间
这个参数和整个配置文件从用kcp一直没变过（除中间改过几次密码），vps也一直同一台好几年了

**Comment by yjd** [comment]
前天重启了vps，这两天用下来恢复正常了。看来跟程序无关。
