### ISSUE TITLE
某些平台上，空载时平均负载就极高

### ISSUE THREAD

**Issue by forever8938** [xtaci/kcptun#762]
硬件：mipsle平台路由器（新路由3），MT7621芯片，512MB内存，双核880MHz的CPU
系统：原版openwrt

运行kcptun之前，LA=0
<img width="1166" alt="Screen Shot 2020-03-11 at 10 25 19" src="https://user-images.githubusercontent.com/44494377/76377682-7f41af00-6386-11ea-893f-86c962774633.png">

运行kcptun并静置15分钟后，LA>2，且居高不下，放了一晚上白天起来一看还是一样。但使用时不觉得卡。
<img width="1166" alt="Screen Shot 2020-03-11 at 10 40 04" src="https://user-images.githubusercontent.com/44494377/76377977-32120d00-6387-11ea-9706-93287688084e.png">

**这不是因为路由器的配置太低**。以下机器配置更差，却没有这个问题

硬件：mipsle平台路由器，MT7620芯片，64M内存，单核580MHz。
系统：原版openwrt

运行kcptun之前，LA=0
<img width="1166" alt="Screen Shot 2020-03-11 at 10 26 34" src="https://user-images.githubusercontent.com/44494377/76377804-d0ea3980-6386-11ea-8119-4b6bb17fa725.png">

运行kcptun并静置15分钟后，LA=0
<img width="1166" alt="Screen Shot 2020-03-11 at 10 39 44" src="https://user-images.githubusercontent.com/44494377/76377872-f70fd980-6386-11ea-8029-f693579730aa.png">

以上kcptun客户端版本均为20200226。我试过20200201也是一样。
配置均为：
```
./client_linux_mipsle -r "$server:$port" -l ":1080" -crypt salsa20 -mode fast3 -nocomp -autoexpire 900 -sockbuf 16777217 -dscp 46
```

**Comment by xtaci** [comment]
用-mode manual ，并调高-interval 可能会缓解， 有定时器任务负责数据重传。

**Comment by forever8938** [comment]
> 用-mode manual ，并调高-interval 可能会缓解， 有定时器任务负责数据重传。

谢大佬。经测试interval=20则LA=1.5，interval=50则LA<1。使用参数是主页上能找到的
```
-mode manual -nodelay 1 -interval 20 -resend 2 -nc 1
```

有几个问题望解答。
1. 另一台更差的机器直接用默认配置，一直正常，这个大概是什么原因呢？
2. 预定义的模式fast3, fast2, fast, normal，对应的参数分别是？
3. interval调高对速度有影响吗？

**Comment by xtaci** [comment]
1. timer的golang1.14之前的效率不是很高，也许有平台差异，但go1.14 mipsle 有bug，等golang1.14.1的fix
2. 看源码https://github.com/xtaci/kcptun/blob/master/client/main.go#L288 启动也会输出
3. 有，影响实时性，交互应用更慢
4.  没有数据，但有会话存在，只要连接在，就会有定时器周期性检查。

**Comment by dolphinpaopao** [comment]
> 1. timer的golang1.14之前的效率不是很高，也许有平台差异，但go1.14 mipsle 有bug，等golang1.14.1的fix
> 2. 看源码https://github.com/xtaci/kcptun/blob/master/client/main.go#L288 启动也会输出
> 3. 有，影响实时性，交互应用更慢
> 4. 没有数据，但有会话存在，只要连接在，就会有定时器周期性检查。

作者你好，刚发现golang 1.14.1已经released了。

**Comment by xtaci** [comment]
嗯，好，现在就重新编译

**Comment by dolphinpaopao** [comment]
> 嗯，好，现在就重新编译

谢谢你。

**Comment by forever8938** [comment]
20200321问题依旧，CPU 0%，LA>2

**Comment by jyy5206** [comment]
问题解决了么？

我同样MT7621，红米AC2100.
2020.10.01编译的的固件： https://github.com/Lienol/openwrt
集成了Passwall。使用了分流+Haproxy。
哪怕在持续静置情况下，LA也会在0.4到1.5之间持续波动。

另外一台软路由，持续静置后，LA就3个都是零了。
