### ISSUE TITLE
请教TCP 传输怎么开启?服务端true 客服端一设置true 就不通?

### ISSUE THREAD

**Issue by sxml** [xtaci/kcptun#766]
1. 检查 ```-key xxx``` 至少三遍, ***保证***两边一致。
一致
2. 保证```-nocomp, -datashard, -parityshard,  -key, -crypt, -smuxver```两边一致。
一致
7. 两端的版本是否一致
一致
8. 是不是最新版本？
最新
9. 两端分别是什么操作系统？
Linux centos7  linux Openwrt

服务端"tcp": true 
客服端 "tcp": true 不通 false 关闭才通?

TCP传输 两边都需要开启吗 ?

**Comment by pigpigabc123** [comment]
解决了吗？我也是同样的问题，无论服务端"tcp"选项开还是不开，客户端只要开了tcp就不通了

**Comment by sxml** [comment]
> 解决了吗？我也是同样的问题，无论服务端“ tcp”选项开还是不开，客户端只要开了tcp就不通了

解决了  防火墙开kcptun tcp端口
