### ISSUE TITLE
client ipv6 support improve 

### ISSUE THREAD

**Issue by networkextension** [xtaci/kcptun#767]
user@i9-2 kcp % ./client_darwin_amd64 -r "2001:19f0::0:6000" -l ":10088" -mode fast2 --crypt none --nocomp
2020/03/18 11:04:46 version: 20200201
2020/03/18 11:04:46 smux version: 1
2020/03/18 11:04:46 listening on: [::]:10088
2020/03/18 11:04:46 encryption: none
2020/03/18 11:04:46 nodelay parameters: 1 20 2 1
2020/03/18 11:04:46 remote address: raddripv6:6000
2020/03/18 11:04:46 sndwnd: 128 rcvwnd: 512
2020/03/18 11:04:46 compression: false
2020/03/18 11:04:46 mtu: 1350
2020/03/18 11:04:46 datashard: 10 parityshard: 3
2020/03/18 11:04:46 acknodelay: false
2020/03/18 11:04:46 dscp: 0
2020/03/18 11:04:46 sockbuf: 4194304
2020/03/18 11:04:46 smuxbuf: 4194304
2020/03/18 11:04:46 streambuf: 2097152
2020/03/18 11:04:46 keepalive: 10
2020/03/18 11:04:46 conn: 1
2020/03/18 11:04:46 autoexpire: 0
2020/03/18 11:04:46 scavengettl: 600
2020/03/18 11:04:46 snmplog: 
2020/03/18 11:04:46 snmpperiod: 60
2020/03/18 11:04:46 quiet: false
2020/03/18 11:04:46 tcp: false
2020/03/18 11:04:46 initiating key derivation
2020/03/18 11:04:46 key derivation done
2020/03/18 11:04:46 re-connecting: dial(): address 2001:19f0:7402:393:5400:ff:fe58:783a:6000: too many colons in address
2020/03/18 11:04:47 re-connecting: dial(): address 2001:19f0:7402:393:5400:ff:fe58:783a:6000: too many colons in address
2020/03/18 11:04:48 re-connecting: dial(): address 2001:19f0:7402:393:5400:ff:fe58:783a:6000: too many colons in address
2020/03/18 11:04:49 re-connecting: dial(): address 2001:19f0:7402:393:5400:ff:fe58:783a:6000: too many colons in address
2020/03/18 11:04:50 re-connecting: dial(): address 2001:19f0:7402:393:5400:ff:fe58:783a:6000: too many colons in address

OS:Mac OS X 10.15.3

**Comment by xtaci** [comment]
[xxx.xx.xx]:6000

**Comment by networkextension** [comment]
cool , why add [], not use ":" direct split ?

**Comment by xtaci** [comment]
```
Dial("tcp", "golang.org:http")
Dial("tcp", "192.0.2.1:http")
Dial("tcp", "198.51.100.1:80")
Dial("udp", "[2001:db8::1]:domain")
Dial("udp", "[fe80::1%lo0]:53")
Dial("tcp", ":80")
```
it's in standard library
https://golang.org/pkg/net/

**Comment by Yifei0727** [comment]
it seems that kcp(go) perfer IPv4 over IPv6 if a domain support **both IPv6 and IPv4**.


> on windows verson (17763.1098, win10 1809,x64)
> x64 client version  20190409

* use windows ping cmd, Ping use IPv6 default
```
cmd shell>ping  domain.tld
正在 Ping domain.tld [2001:xxxx:xxxx:xxxx::xxxx] 具有 32 字节的数据:
来自 2001:xxxx:xxxx:xxxx::xxxx 的回复: 时间=n ms
来自 2001:xxxx:xxxx:xxxx::xxxx的回复: 时间=n ms
```
* use kcp with domain, but kcp use IPv4 default
```
cmd shell>client_windows_amd64.exe -l [::]:60666 -r DOMAIN.TLD:PORT
2020/03/19 12:33:07 version: 20190409
2020/03/19 12:33:07 initiating key derivation
2020/03/19 12:33:07 listening on: [::]:60666
2020/03/19 12:33:07 encryption: aes
2020/03/19 12:33:07 nodelay parameters: 0 30 2 1
2020/03/19 12:33:07 remote address: DOMAIN.TLD:PORT
2020/03/19 12:33:07 sndwnd: 128 rcvwnd: 512
2020/03/19 12:33:07 compression: true
2020/03/19 12:33:07 mtu: 1350
2020/03/19 12:33:07 datashard: 10 parityshard: 3
2020/03/19 12:33:07 acknodelay: false
2020/03/19 12:33:07 dscp: 0
2020/03/19 12:33:07 sockbuf: 4194304
2020/03/19 12:33:07 smuxbuf: 4194304
2020/03/19 12:33:07 keepalive: 10
2020/03/19 12:33:07 conn: 1
2020/03/19 12:33:07 autoexpire: 0
2020/03/19 12:33:07 scavengettl: 600
2020/03/19 12:33:07 snmplog:
2020/03/19 12:33:07 snmpperiod: 60
2020/03/19 12:33:07 quiet: false
2020/03/19 12:33:07 connection: 0.0.0.0:63459 -> IPv4Addr:PORT
```
So I have to set DOMAIN.TLD to record `AAAA` only for IPv6 support.

**Comment by kz08w8r** [comment]
dscp改46试试
