### ISSUE TITLE
Should we provide FreeBSD aarch64 build ?

### ISSUE THREAD

**Issue by networkextension** [xtaci/kcptun#768]
Go go-bootstrap on FreeBSD
https://github.com/dmgk/go-bootstrap/releases

I have success  run kcptun on FreeBSD aarch64 RPI 3B+.

**Comment by xtaci** [comment]
I'll consider make a /port directory to add scripts to build for these minor platform?
what do you think?

**Comment by xtaci** [comment]
eg: /ports/build-freebsd-aarch64.sh ?

**Comment by networkextension** [comment]
FreeBSD style:
write a FreeBSD ports support, if system provider Go ,it's easy 
project style:
write a  script,eg: /ports/build-freebsd-aarch64.sh 

any way , now kcptun run on FreeBSD very easy .
