### ISSUE TITLE
最新版(20200321)的TCP模式好像有点问题

### ISSUE THREAD

**Issue by syuez** [xtaci/kcptun#769]
两台服务器(TCP模式)运行一段时间(时间无规律，1小时或者几小时，但不会超过一天)后就无法通信了，一台以UDP模式运行的服务器则正常。重启服务端进程后又能恢复正常通信了。20200226版本没有遇到这样的问题，目前已经切换到该版本。
PS.使用的时linux-amd64版本

**Comment by maxwellzh** [comment]
0321服务端（Linux64）用起来好像经常会断流（我没用tcp选项）,目前已经切回0226了

**Comment by xtaci** [comment]
golang1.14.1应该还有问题！

**Comment by pokedo0** [comment]
![8IbVxJ.png](https://s1.ax1x.com/2020/03/22/8IbVxJ.png)

![8IbOdx.png](https://s1.ax1x.com/2020/03/22/8IbOdx.png)

好像会经常卡死

**Comment by xtaci** [comment]
是的，go1.14貌似对timer做了改动，可能行为上有差别，我在检查

**Comment by xtaci** [comment]
https://github.com/golang/go/issues/6239
应该和这个改动相关

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/771

**Comment by xtaci** [comment]
在771 issue 讨论

**Comment by xtaci** [comment]
我在 https://github.com/xtaci/kcptun/issues/771 放了一个更严格的时钟测试一下： @maxwellzh @pokedo0
