### ISSUE TITLE
更新为0725版后一直报错

### ISSUE THREAD

**Issue by frank0521** [xtaci/kcptun#77]
Server上的配置(仅直接使用KCP，未与Shadowsocks配合使用)：
./server_linux_amd64 -l ":9233" -t "0.0.0.0:0" -key "password" -mtu 1350 -sndwnd 2048 -rcvwnd 2048 -mode "fast2" > kcptun.log 2>&1 &
客户端配置：
client_windows_amd64.exe -l ":443" -r "serverIP:9233" -key "password" -mtu 1350 -sndwnd 256 -rcvwnd 1024 -mode "fast2"

打开后，server上报错如下：
2016/07/28 22:56:02 version: 20160725
2016/07/28 22:56:02 listen udp :9233: bind: address already in use
2016/07/28 22:56:29 remote address: 58.229.23.100:19987
2016/07/28 22:56:29 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:56:29 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:56:29 remote address: 58.229.23.100:19987
2016/07/28 22:56:30 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:56:30 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:56:30 remote address: 58.229.23.100:19987
2016/07/28 22:56:30 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:56:30 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:56:30 remote address: 58.229.23.100:19987
2016/07/28 22:57:20 remote address: 58.229.23.100:3392
2016/07/28 22:57:20 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:20 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:20 remote address: 58.229.23.100:3392
2016/07/28 22:57:20 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:20 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:21 remote address: 58.229.23.100:3392
2016/07/28 22:57:21 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:21 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:21 remote address: 58.229.23.100:3392
2016/07/28 22:57:21 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:21 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:22 remote address: 58.229.23.100:3392
2016/07/28 22:57:22 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:22 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:22 remote address: 58.229.23.100:3392
2016/07/28 22:57:22 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:22 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:23 remote address: 58.229.23.100:3392
2016/07/28 22:57:23 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:23 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:24 remote address: 58.229.23.100:3392
2016/07/28 22:57:24 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:24 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:25 remote address: 58.229.23.100:3392
2016/07/28 22:57:25 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:25 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:26 remote address: 58.229.23.100:3392
2016/07/28 22:57:26 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:26 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:27 remote address: 58.229.23.100:3392
2016/07/28 22:57:27 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:27 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:28 remote address: 58.229.23.100:3392
2016/07/28 22:57:28 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:28 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:29 remote address: 58.229.23.100:3392
2016/07/28 22:57:29 dial tcp 0.0.0.0:0: getsockopt: connection refused
2016/07/28 22:57:29 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:30 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/28 22:57:30 [ERR] yamux: Failed to read header: broken pipe
2016/07/28 22:57:30 keepalive timeout

客户端报错如下：
2016/07/29 10:56:20 version: 20160725
2016/07/29 10:56:20 listening on: [::]:443
2016/07/29 10:56:20 encryption: aes
2016/07/29 10:56:20 nodelay parameters: 1 20 2 1
2016/07/29 10:56:20 remote address: ServerIP:9233
2016/07/29 10:56:20 sndwnd: 256 rcvwnd: 1024
2016/07/29 10:56:20 compression: true
2016/07/29 10:56:20 mtu: 1350
2016/07/29 10:56:20 datashard: 10 parityshard: 3
2016/07/29 10:56:20 acknodelay: false
2016/07/29 10:56:20 dscp: 0
2016/07/29 10:56:20 conn: 1
2016/07/29 10:56:29 stream opened
2016/07/29 10:56:34 stream opened
2016/07/29 10:56:44 stream opened
2016/07/29 10:56:44 stream opened
2016/07/29 10:56:44 stream opened
2016/07/29 10:56:44 stream opened
2016/07/29 10:56:45 stream opened
2016/07/29 10:56:53 stream opened
2016/07/29 10:56:59 stream closed
2016/07/29 10:57:04 stream closed
2016/07/29 10:57:04 stream opened
2016/07/29 10:57:14 stream closed
2016/07/29 10:57:14 stream opened
2016/07/29 10:57:14 stream closed
2016/07/29 10:57:14 stream closed
2016/07/29 10:57:14 stream closed
2016/07/29 10:57:15 stream closed
2016/07/29 10:57:15 stream opened
2016/07/29 10:57:20 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/29 10:57:20 [ERR] yamux: Failed to read header: broken pipe

**Comment by xtaci** [comment]
kcptun只是一个通路，必须接后端
