### ISSUE TITLE
googleplay下载每次20M左右，然后等30s再下载20M

### ISSUE THREAD

**Issue by txdywy** [xtaci/kcptun#778]
尝试调整了各种参数，都没有改变30s的效果。

现象就是googleplay下载每下载20M会断流，然后等待30s又下20M.参考了之前感觉是算法决定的，尝试调了各种参数都没有改变20M和30s.

**Comment by maxwellzh** [comment]
贴一下配置看看

**Comment by txdywy** [comment]
--mtu 1300 --mode fast2
最原始配置

maxwellzh <notifications@github.com> 于 2020年4月12日周日 上午1:26写道：

**Comment by maxwellzh** [comment]
配置都差不多，是ss吗？我刚试了没复现，server是最新的

**Comment by txdywy** [comment]
是ss

maxwellzh <notifications@github.com> 于 2020年4月12日周日 上午1:45写道：

**Comment by pokedo0** [comment]
google play 下载时候经常会分段下载文件的 FYI

**Comment by txdywy** [comment]
解决了。。。是第三方ss实现的原因。换成ss-libev解决了
