### ISSUE TITLE
为什么会经常删除预构建的二进制文件？

### ISSUE THREAD

**Issue by mritd** [xtaci/kcptun#779]
目前我的 Dockerfile 会采用 release 版本号来下载 kcptun 预构建二进制文件，但是频繁的删除预构建文件会导致 Dockerfile 不可重复构建。

refs mritd/dockerfile#103

**Comment by xtaci** [comment]
主要是golang的bug，以免误下载

**Comment by mritd** [comment]
好吧，这个很尴尬；能不能搞个 latest 的 tag，然后一直下载 latest 就行了 😂
