### ISSUE TITLE
试验手机部署无法使用

### ISSUE THREAD

**Issue by lxdlam** [xtaci/kcptun#78]
手机是1+3，骁龙820。
使用Linux Deploy安装的armhf版Debian 8。
客户端使用client_linux_arm7，后端使用手机版ss
使用同参数启动windows版可以正常使用。

以下报错信息
2016/07/29 22:21:17 version: 20160725
2016/07/29 22:21:17 listening on: [::]:10000
2016/07/29 22:21:17 encryption: aes
2016/07/29 22:21:17 nodelay parameters: 1 20 2 1
2016/07/29 22:21:17 remote address: ss.lxdlam.site:5000
2016/07/29 22:21:17 sndwnd: 128 rcvwnd: 1024
2016/07/29 22:21:17 compression: true
2016/07/29 22:21:17 mtu: 1350
2016/07/29 22:21:17 datashard: 10 parityshard: 3
2016/07/29 22:21:17 acknodelay: false
2016/07/29 22:21:17 dscp: 0
2016/07/29 22:21:17 conn: 1
2016/07/29 22:21:20 stream opened
2016/07/29 22:21:24 stream opened
2016/07/29 22:21:25 stream opened
2016/07/29 22:21:29 stream opened
2016/07/29 22:21:30 stream opened
2016/07/29 22:21:30 stream closed
2016/07/29 22:21:30 stream opened
2016/07/29 22:21:33 stream opened
2016/07/29 22:21:34 stream closed
2016/07/29 22:21:34 stream opened
2016/07/29 22:21:35 stream opened
2016/07/29 22:21:35 stream closed
2016/07/29 22:21:37 stream opened
2016/07/29 22:21:38 stream opened
2016/07/29 22:21:39 stream opened
2016/07/29 22:21:39 stream closed
2016/07/29 22:21:40 stream opened
2016/07/29 22:21:40 stream closed
2016/07/29 22:21:40 stream closed
2016/07/29 22:21:40 stream opened
2016/07/29 22:21:41 stream opened
2016/07/29 22:21:43 stream closed
2016/07/29 22:21:43 stream opened
2016/07/29 22:21:44 stream closed
2016/07/29 22:21:44 stream opened
2016/07/29 22:21:45 stream closed
2016/07/29 22:21:45 stream opened
2016/07/29 22:21:45 stream closed
2016/07/29 22:21:45 stream opened
2016/07/29 22:21:47 stream closed
2016/07/29 22:21:48 stream closed
2016/07/29 22:21:48 stream opened
2016/07/29 22:21:49 stream closed
2016/07/29 22:21:49 stream opened
2016/07/29 22:21:50 stream closed
2016/07/29 22:21:50 stream opened
2016/07/29 22:21:50 stream closed
2016/07/29 22:21:50 stream opened
2016/07/29 22:21:51 stream closed
2016/07/29 22:21:53 stream closed
2016/07/29 22:21:53 stream opened
2016/07/29 22:21:54 stream opened
2016/07/29 22:21:54 stream closed
2016/07/29 22:21:55 stream opened
2016/07/29 22:21:55 stream closed
2016/07/29 22:21:55 stream opened
2016/07/29 22:21:58 stream closed
2016/07/29 22:21:58 stream opened
2016/07/29 22:21:59 stream closed
2016/07/29 22:21:59 stream opened
2016/07/29 22:22:00 stream closed
2016/07/29 22:22:00 stream opened
2016/07/29 22:22:00 stream closed
2016/07/29 22:22:00 stream opened
2016/07/29 22:22:03 stream closed
2016/07/29 22:22:03 stream opened
2016/07/29 22:22:04 stream closed
2016/07/29 22:22:05 stream closed
2016/07/29 22:22:05 stream closed
2016/07/29 22:22:08 stream opened
2016/07/29 22:22:08 stream closed
2016/07/29 22:22:09 stream opened
2016/07/29 22:22:09 stream closed
2016/07/29 22:22:09 stream opened
2016/07/29 22:22:10 stream closed
2016/07/29 22:22:10 stream closed
2016/07/29 22:22:10 stream opened
2016/07/29 22:22:13 stream closed
2016/07/29 22:22:14 stream opened
2016/07/29 22:22:17 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/29 22:22:17 [ERR] yamux: Failed to read header: broken pipe
2016/07/29 22:22:17 stream closed
2016/07/29 22:22:17 stream closed
2016/07/29 22:22:17 stream closed
2016/07/29 22:22:17 stream closed
2016/07/29 22:22:17 stream closed
2016/07/29 22:22:17 session shutdown
2016/07/29 22:22:22 lookup ss.lxdlam.site on 114.114.115.115:53: dial udp 114.114.115.115:53: i/o timeout

**Comment by xtaci** [comment]
试下 v5

**Comment by lxdlam** [comment]
sorry，才看到
试验也无法使用，报错信息相同

**Comment by wxyzh** [comment]
直接用ip地址呢 
看下issue#49

**Comment by lxdlam** [comment]
感谢comment
无法使用，关键问题应该出在i/o deadline上

**Comment by xtaci** [comment]
Hi:
1. Are you using the **latest release**?
2. Which **OS** do you use?
3. Which end for this issue related to, **client or server**?
4. Does your ISP or VPS **blocked UDP**?
5. Does your VPS **firewall** allows UDP pass through?
6. Are you using the **same version** for both client & server
7. Did you correctly set the ```-target value, -t value	target server address (default: "127.0.0.1:12948")``` on the server side?
