### ISSUE TITLE
UDP over KCPTUN！

### ISSUE THREAD

**Issue by GTGraphics3** [xtaci/kcptun#784]
有很多线上视频、语音都走udp流量（还有游戏），长距离（中国--美国）丢包严重，如果UDP 能over KCPTUN，可以完美解决udp丢包问题。其他的解决方法成本太大了，比如udp封tcp……已经ss+kcptun+udp2raw了，再套个udp封tcp o(╥﹏╥)o 。Mac其实下也没找到合适udp封tcp。

希望能加这个功能！Thanks♪(･ω･)ﾉ

**Comment by krrr** [comment]
不会加的：https://github.com/xtaci/kcptun/issues/458

**Comment by ws826402696** [comment]
自己写就行了，加UDP不难啊，用个全局UDP代理完事
