### ISSUE TITLE
能否添加自定义ip包头协议号的功能？

### ISSUE THREAD

**Issue by mzh741** [xtaci/kcptun#788]
模拟tcp的不同系统兼容性好像不怎么好，能否添加自定义ip包头协议号的功能，比如模拟sctp等协议，应该也能绕开运营商udp限制，又不需要使用iptables截拦内核生成的rst数据包。

**Comment by xtaci** [comment]
这种都不好弄，firewall过滤规则不简单是protocol

**Comment by k79e** [comment]
这不好说 今天我发送了个畸形数据包 dscp>63的  反而效果很好
防火墙是否只干扰 tcp/udp协议 也没有数据证明. 不试试咋能行呢?

@xtaci

**Comment by Cwek** [comment]
应该是考虑到自定义ip协议号对NAT设备的影响，有可能过不了NAT。

**Comment by k79e** [comment]
对哦 直接报废了就

**Comment by Cwek** [comment]
你说不如直接用sctp？虽然这可能也过不了nat，除非双端都是公网。

**Comment by k79e** [comment]
那不清楚了 得看运营商设备是咋弄的了

**Comment by Cwek** [comment]
理论上，运营商只要能负载IP网，上面挂什么协议号不影响，毕竟像BGP就是有自己的IP协议号。主要问题是家用的NAT设备。所以我才说要双端公网。

**Comment by k79e** [comment]
小路由的内核没那么弱吧 否则nat的人就没法用vpn了 什么gre ipsec这些的

**Comment by Cwek** [comment]
> 小路由的内核没那么弱吧 否则nat的人就没法用vpn了 什么gre ipsec这些的

看NAT设备（例如家用的网关）的设计。只要保证NAT设备能保留任意协议号上下游双向联通和保留会话，而且改地址不影响上层协议，就没问题。好像ipsec在dd-wrt上还要打开一个应用层网关。

或者试下在内网建用HE的TB一条6in4能不能，6in4是有协议号41，如果NAT能 不做特别配置就能联通的话，就是可以。

**Comment by adcen0107** [comment]
NAT的设备都有保持会话的能力，改底层协议一般不会影响到上层。@k79e 你的测试要充分，偶尔一次的数据不能说明问题。自定义ip包头协议号是简单的，但是有几个问题：
1、有的协议是有信令过程的，你直接模仿数据面的包，没有信令过程，会被防火墙直接丢了的；
2、改成其它协议的意义不是很大，因为你并不了解外面防火墙对哪种协议的优先级比UDP高，那就只能尝试去多实现几种，而结合第1条要求，项目会变得很复杂。

**Comment by k79e** [comment]
所以还不如研究研究 已知丢包率 fec参数到底设定多少才好
其他人有测试过么 fec什么时候会扛不住?
