### ISSUE TITLE
为啥不原生支持一个socks5?

### ISSUE THREAD

**Issue by TommyJerryMairo** [xtaci/kcptun#8]
明明可以不用ssh的……

**Comment by xtaci** [comment]
这样已经很方便了，你懂的。

**Comment by TommyJerryMairo** [comment]
以前练手写的一个[socks5 server](https://git.io/vwRoc) ……可以加进去么……？可以的话窝pr了啊……

**Comment by xtaci** [comment]
谢谢，你可以fork一个，然后在自己的分支上做，太敏感。

**Comment by TommyJerryMairo** [comment]
好吧……可是窝不会GO……
