### ISSUE TITLE
kcptun client consume 2~5% CPU power when idle

### ISSUE THREAD

**Issue by mitnk** [xtaci/kcptun#802]
Kcptun version: latest in release page,
platform: Raspberry Pi4

![image](https://user-images.githubusercontent.com/177049/89159193-c16fc500-d5a1-11ea-9e81-f4d83f50c4a5.png)

command line:
```
kcptun-client --quiet --conn 4 --scavengettl 300 --autoexpire 120 -mode fast --nocomp --key xxx -r a.b.c.d:11080 -l 127.0.0.1:12345 --log /tmp/kcptun-client.log
```

Is this CPU usage normal?  
What kcptun-client is doing when idle? (when there is no active connections (traffics) going through)

Is there a way (config) to make kcptun(client) less aggressive (when idle)?  

Thanks!

**Comment by xtaci** [comment]
absolutely normal for Pi4

**Comment by mitnk** [comment]
.. 5% of power of Pi4 is still a lot (for idle). It's not peaks, it's stable 3~5% of CPU. Empty loops etc things should not consume that much?

**Comment by mitnk** [comment]
@xtaci I found kcptun-client does not take 0% of CPU time in idle time is because the UPD connection does not get closed when timeout (I tested it out with options: `--conn 1 --scavengettl 10 --autoexpire 10`). The UPD connection 1 won't close until a second request (after a timeout time period) comes to `kcptun-client`, which then close the connection 1 and open a new UPD connection 2 for the new request.

If I kill the process of the `kcptun-server` side, which force the client side UPD connection close. The CPU usage of the client to drop to 0%.

**Comment by xtaci** [comment]
> @xtaci I found kcptun-client does not take 0% of CPU time in idle time is because the UPD connection does not get closed when timeout (I tested it out with options: `--conn 1 --scavengettl 10 --autoexpire 10`). The UPD connection 1 won't close until a second request (after a timeout time period) comes to `kcptun-client`, which then close the connection 1 and open a new UPD connection 2 for the new request.
> 
> If I kill the process of the `kcptun-server` on remote side, which force the client side UPD connection close. The CPU usage of the client would drop to 0%.

That's true.

**Comment by mitnk** [comment]
@xtaci Which means? The connection should be closed or it keeps in open on purpose? Am I misunderstood of usage of `--scavengettl` and `--autoexpire`?

**Comment by xtaci** [comment]
It's about programming:
https://github.com/xtaci/kcptun/blob/master/client/main.go#L448

maybe we can work a way out to the problem

**Comment by mitnk** [comment]
Thanks, I'll check it out when I got some time.

**Comment by xtaci** [comment]
[kcptun-darwin-amd64-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718852/kcptun-darwin-amd64-20201219.tar.gz)
[kcptun-freebsd-amd64-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718853/kcptun-freebsd-amd64-20201219.tar.gz)
[kcptun-linux-386-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718854/kcptun-linux-386-20201219.tar.gz)
[kcptun-linux-amd64-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718855/kcptun-linux-amd64-20201219.tar.gz)
[kcptun-linux-arm5-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718856/kcptun-linux-arm5-20201219.tar.gz)
[kcptun-linux-arm6-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718857/kcptun-linux-arm6-20201219.tar.gz)
[kcptun-linux-arm7-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718859/kcptun-linux-arm7-20201219.tar.gz)
[kcptun-linux-arm64-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718870/kcptun-linux-arm64-20201219.tar.gz)
[kcptun-windows-386-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718871/kcptun-windows-386-20201219.tar.gz)
[kcptun-windows-amd64-20201219.tar.gz](https://github.com/xtaci/kcptun/files/5718872/kcptun-windows-amd64-20201219.tar.gz)

@mitnk would you plz try this build for testing?

**Comment by mitnk** [comment]
@xtaci Tested a bit on the mac version. The CPU usage decreased a lot, but the UDP ports opening behavior is still a little strange - When idle, it periodically open & close UDP ports regularly (which take 0.0x% of CPU). When it open a new UDP port, it would show a log like below:

```
2020/12/19 12:16:55 smux version: 1 on connection: 0.0.0.0:56808 -> x.x.x.x:12345
```

What I'd expect is that the client won't bother to open new UPD connections if there is no requests come.

**Comment by mitnk** [comment]
If the changes only happens in kcptun (not in deps like kcp-go), you can only give me a branch or a git-hash, I can built & test it myself. No need to have binaries built.

**Comment by xtaci** [comment]
the master branch of kcptun @mitnk

**Comment by mitnk** [comment]
@xtaci I just created a PR #825 which make some minor changes, please help to check whether the direction is correct.

**Comment by mitnk** [comment]
Update: re-tested a bit the binary from above comment https://github.com/xtaci/kcptun/issues/802#issuecomment-748413876 . The comment I added previously (https://github.com/xtaci/kcptun/issues/802#issuecomment-748416528) is not true.

UPD connection is not spawning "strangely". I assume it was the anti-virus domain pinging this TCP port which make tcptun create new UPD connections.

So the PR 825 is not a fix, it's only a minor improvement.
