### ISSUE TITLE
about streamCopy 

### ISSUE THREAD

**Issue by toanqng** [xtaci/kcptun#804]
**Q1**: At example client: **client/main.go**
```
        defer p2.Close()
	streamCopy := func(dst io.Writer, src io.ReadCloser) {
               ....
		p1.Close()
		p2.Close()
	}
```
**p2.Close()** twice, can't i remove **p2.Close()** at func **streamCopy** ?

**Q2**: I have 2 data sent to the server tunnel: 
- metadata (small size)
- data (large size)
At the server, can't i link metadata and data?. ( i using **p.ID()** but it's not unique )

Thanks for best Tunnel.

**Comment by xtaci** [comment]
Close is an idempotent function
