### ISSUE TITLE
setting different dataShard/parityShard on client and server

### ISSUE THREAD

**Issue by acc557** [xtaci/kcptun#809]
Currently, kcptun requires dataShard/parityShard to be the same on client and server. 

I want to disable FEC only on the transmitted packet from client to server, and keep the FEC on the other direction, as there is 0% packet loss on the up link and 50% loss on the down link. 

I tired setting different values to server and client, and they seem to talk to each other for a second, then the connection died.

It seems that the kcp-go protocol sends the dataShard/parityShard with every packet. I would like to know if there is any particular reason why FEC are required on both links, and if there is a way to disable one of them.

**Comment by koolca** [comment]
期待能分别指定client/server端的upload/download 的ds/ps，支持只开server2client的FEC，能单独关闭client2server的FEC

**Comment by xtaci** [comment]
it's difficult to seperate, the reason is because kcptun has no handshake procedure.
then, there's no way to exchange parameters.

---
BUT, there may be some possiblility to deduct parameters from previous received packets.

**Comment by xtaci** [comment]
the main concern for adding 'remote data shard' or 'parity data shard' parameters is compatibility issue.

**Comment by koolca** [comment]
我理解的是，client或server端只是在FEC解码和编码使用了不同的ds/ps参数，例如client的编码与server的解码一套参数，client的解码与server的编码一套参数。
我不懂网络编程，如有错误请见谅。

**Comment by acc557** [comment]
> the main concern for adding 'remote data shard' or 'parity data shard' parameters is compatibility issue.

Just wanted to ask if user can configure ds/ps for both uplink and downlink on both server and clients. Maybe the uplink ds/ps can be set to downlink as default.

There shouldn't be any protocol modification, or I missed something?

**Comment by xtaci** [comment]
yes <ds, ps, rds, rps> , four parameters to set FEC, and we need to handle config file compabitility issue for routers etc...

**Comment by xtaci** [comment]
only API extension, no protocol modification.

**Comment by xtaci** [comment]
I mean, the BEST way to handle this is some kind of  auto-tunning FEC parameters algorithm regarding incoming packets sequence from the other peer.

**Comment by acc557** [comment]
Auto-tunning FEC is exactly what I am trying at the moment. I wrote some scripts to send UDP packets for measuring bi-directional losses on both uplink and downlink, and I sent those information via a TCP connection over smux to the other end and restarts the server and client.

This dirty hack kind of works, but the problem is that if the client accidentally restarts, it will try to use a wrong FEC setting to connect to the server. Also, the server takes the same FEC param for all incoming clients, which is not an ideal solution if the network condition of the client varies.

**Comment by acc557** [comment]
In [UDPspeeder](https://github.com/wangyu-/UDPspeeder) the FEC configuration is written in every UDP packet, and different groups of packets can have different ds/ps. This makes auto-tuning FEC a lot easier, but it will send a lot of redundant information as the tuning shouldn't be performed very frequently.

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/tree/autotune
can you review the commits of this branch ?

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/commit/105bfec567d4756e22619f3d781f8f4c4b063d58
to
https://github.com/xtaci/kcp-go/commit/ff34f7683f9faefd185e1afdc873c112e4343fde

**Comment by xtaci** [comment]
[kcptun-darwin-amd64-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354329/kcptun-darwin-amd64-20201009.tar.gz)
[kcptun-freebsd-amd64-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354330/kcptun-freebsd-amd64-20201009.tar.gz)
[kcptun-linux-386-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354331/kcptun-linux-386-20201009.tar.gz)
[kcptun-linux-amd64-20201004.tar.gz](https://github.com/xtaci/kcptun/files/5354332/kcptun-linux-amd64-20201004.tar.gz)
[kcptun-linux-amd64-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354334/kcptun-linux-amd64-20201009.tar.gz)
[kcptun-linux-arm5-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354335/kcptun-linux-arm5-20201009.tar.gz)
[kcptun-linux-arm6-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354336/kcptun-linux-arm6-20201009.tar.gz)
[kcptun-linux-arm7-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354339/kcptun-linux-arm7-20201009.tar.gz)
[kcptun-linux-arm64-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354340/kcptun-linux-arm64-20201009.tar.gz)
[kcptun-linux-mips-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354341/kcptun-linux-mips-20201009.tar.gz)
[kcptun-linux-mipsle-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354342/kcptun-linux-mipsle-20201009.tar.gz)
[kcptun-windows-386-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354345/kcptun-windows-386-20201009.tar.gz)
[kcptun-windows-amd64-20201009.tar.gz](https://github.com/xtaci/kcptun/files/5354350/kcptun-windows-amd64-20201009.tar.gz)

try this one for auto FEC

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20201010

**Comment by keeno1982** [comment]
借问一下，20201010这个版本意思是可以不用配置服务端和客户端的dataShard，parityShard这两个参数了吗？程序会自己动态调整？

**Comment by xtaci** [comment]
不是，是两头可以设置不同参数

**Comment by keeno1982** [comment]
期待有自动调整的版本，这两个数值的设置太复杂了，国际线路环境一直在变化，用哪组值都觉得不够好

**Comment by wangyu-** [comment]
>yes <ds, ps, rds, rps> , four parameters to set FEC, and we need to handle config file compabitility issue for routers etc...

In UDPspeeder there is no `rds` and `rps`, the receiving-end is just a decoder that decodes anything the sending-end sends, the receiving-end doesn't know any info of sending-end in advance.  To achieve this, `<ds,ps,idx>` is written in every packet,  for example <10,5,3> means for this FEC group we have 10 original packets with 5 redundant packets,  and the current packet is the 3-rd packet in the group.

In addition, there is a group ID to help identify which FEC group the packet belongs to when out of order delivery happens. Finally it becomes like `<group_id,ds,ps,idx>`
