### ISSUE TITLE
Windows客户端的具体输出是怎么样的?

### ISSUE THREAD

**Issue by ragnaroks** [xtaci/kcptun#81]
因为使用参数较为不方便,我写了一个[Windows用户界面](https://git.oschina.net/ragnaroks/KcptunGUI),
发现只有使用cmd.exe运行如"c:\client_windows_386.exe -r "server.tcpun.com:27015" -l "0.0.0.0:8989" -mode fast2"这样的命令行才会有输出日志,我希望能获得回显写入GUI中.

**Comment by xtaci** [comment]
stderr 输出

**Comment by ragnaroks** [comment]
所有输出都是stderr?没有stdout?

**Comment by xtaci** [comment]
That logger writes to standard error and prints the date and time of each logged message. 
https://golang.org/pkg/log/
是的！

**Comment by ragnaroks** [comment]
Thanks!
