### ISSUE TITLE
用着用着就自动的降低50%的速度

### ISSUE THREAD

**Issue by lovexiaofan123** [xtaci/kcptun#817]
用着用着就自动的降低50%的速度，每次都是晚上睡觉后触发，早上醒来就被降低了50%速率，重启客户端就好了，客户参数和服务端一致。调过autoexpire conn tcp mtu各大参数，能调的基本都调了，调低调高都无果。这是isp qos的后果吗？还是配置不正确合理？现在用10.10的最新版本试试，客户端与服务端都更新

**Comment by lovexiaofan123** [comment]
贴个参数吧，反正我调参数无果，我就索性的调高。--key xxxxxx --mtu 1500 --sndwnd 1024 --rcvwnd 4096 --mode fast3  --crypt none --nocomp true  --datashard 0 --parityshard 0

**Comment by lovexiaofan123** [comment]
> 用着用着就自动的降低50%的速度，每次都是晚上睡觉后触发，早上醒来就被降低了50%速率，重启客户端就好了，客户参数和服务端一致。调过autoexpire conn tcp mtu各大参数，能调的基本都调了，调低调高都无果。这是isp qos的后果吗？还是配置不正确合理？现在用10.10的最新版本试试，客户端与服务端都更新

**Comment by luii2020** [comment]
客户端调高效果不好的，客户端低于服务端效果较好，我移动200m用vultr，无论什么时段油管4k开无压力

**Comment by lovexiaofan123** [comment]
> 客户端调高效果不好的，客户端低于服务端效果较好，我移动200m用vultr，无论什么时段油管4k开无压力

恰恰相反好吗？我这里客户端参数低于服务端就变得很慢，我都是客户端和服务端一直，我电信bwg随时油管可跑30-40W，speedtest能跑500M，就只是晚上会突然掉速，重启客户端就好了，很奇怪的wen t

**Comment by xtaci** [comment]
-autoexpire 3600

**Comment by lovexiaofan123** [comment]
> -autoexpire 3600

这个参数好像作用不大，我设置过最高为900，3600我再试试看

**Comment by mailsex** [comment]
> > 客户端调高效果不好的，客户端低于服务端效果较好，我移动200m用vultr，无论什么时段油管4k开无压力
> 
> 恰恰相反好吗？我这里客户端参数低于服务端就变得很慢，我都是客户端和服务端一直，我电信bwg随时油管可跑30-40W，speedtest能跑500M，就只是晚上会突然掉速，重启客户端就好了，很奇怪的wen t

搬瓦工哪个机房啊什么线路啊？服务器参数怎么样的？我的只能跑2w、、、、、
