### ISSUE TITLE
无法连接本机Linux armv7 cilient

### ISSUE THREAD

**Issue by oyrx** [xtaci/kcptun#82]
手机终端su运行/system/bin/kcptun正常，同一局域网设备可以通过手机的KCPTUN进行高速连接，但是手机本机的shadowsocks无法连接 = = 怎么回事。。。

root没问题，kcptun权限755也没问题，console输出正常，Ss是play最新版，但就是无法连接。。。

**Comment by oyrx** [comment]
找到原因了，与Shadowsocks-Android的VPN模式不兼容，需要使用NAT连接模式

**Comment by oyrx** [comment]
希望作者做一下 linux-arm与vpn模式的兼容，辛苦了 ^_^

**Comment by joopdorresteijn** [comment]
Has a armv7 client been made yet? I would like to install on openwrt
