### ISSUE TITLE
build for Apple M1

### ISSUE THREAD

**Issue by networkextension** [xtaci/kcptun#822]
just work
` $mkdir sdk
  $cd sdk
  $git clone https://go.googlesource.com/go
  $cd go
  $git fetch https://go.googlesource.com/go refs/changes/58/272258/1 && git checkout FETCH_HEAD
  $cd src
  $GOOS=darwin GOARCH=arm64 ./bootstrap.bash`

then compile kcptun

`env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -mod=vendor -ldflags "$LDFLAGS" -gcflags "$GCFLAGS" -o client_darwin_arm64  github.com/xtaci/kcptun/client
`

**Comment by xtaci** [comment]
create a PR to build-release.sh

**Comment by networkextension** [comment]
not  stable, waiting Go 1.16 release
