### ISSUE TITLE
增加UDP支持和TCP单连接分包

### ISSUE THREAD

**Issue by koolca** [xtaci/kcptun#824]
首先感谢作者提供如此优秀的网络加速工具
目前KCPTUN只支持加速TCP，未来有没有可能加速UDP？我通过gost将UDP转成TCP再经过KCPTUN，网络延迟增加不少，没有实际使用意义
此外，-conn >1的情况下，可否支持单连接TCP传入也能分成多个UDP连接？这对ISP的QOS非常有帮助

**Comment by xtaci** [comment]
UDP可以用 https://github.com/wangyu-/UDPspeeder 这个方案。

UDP的核心问题是，你无法下沉流控算法。流控算法无法改变，那么唯一能改善的就是链路质量。

改善链路质量有两个途径：

1. 降低丢包率，比如UDPSpeeder
2. 对于延迟不敏感的应用，拉长管道，增加延迟，以降低抖动，来欺骗/适应 UDP应用的流控算法。

**Comment by xtaci** [comment]
对于多个UDP链接分担的问题，不同链路的抖动不同，延迟不同，也同样会影响流控算法。往往结果就是总速度只有最差的那一条的线路的速度。

**Comment by koolca** [comment]
谢谢 @xtaci 详细解答
UDPspeeder可以满足大部分需求，但不支持单向（client to server)关闭FEC（我测到的丢包几乎都来自于server to client)

**Comment by koolca** [comment]
我测到如果某一个链接长时间大流量，此链接会被限速，如果多链接分担的话，就相当于用延迟换稳定性

**Comment by xtaci** [comment]
> 我测到如果某一个链接长时间大流量，此链接会被限速，如果多链接分担的话，就相当于用延迟换稳定性

如果你的猜想是对的，我早就做了。

**Comment by koolca** [comment]
好吧，基于我现在的网络状况，KCPTUN仍然是最优秀的网络加速方案，再次感谢 @xtaci

**Comment by xtaci** [comment]
主要是不同链接的jitter问题，可以提高throughput，但会增加latency。

**Comment by wangyu-** [comment]
>UDPspeeder可以满足大部分需求，但不支持单向（client to server)关闭FEC（我测到的丢包几乎都来自于server to client)

没问题的，UDPspeeder两边可以设置不同的参数，把不需要FEC的那一个方向设置成`--mode 1 -f1:0` 就相当于关了

**Comment by koolca** [comment]
> > UDPspeeder可以满足大部分需求，但不支持单向（client to server)关闭FEC（我测到的丢包几乎都来自于server to client)
> 
> 没问题的，UDPspeeder两边可以设置不同的参数，把不需要FEC的那一个方向设置成`--mode 1 -f1:0` 就相当于关了

确实是这样，后来我也试出来了，多谢作者：）

**Comment by ieeegeee** [comment]
TCP单连接多路conn是否可以接缓解游戏偶尔切断连接的问题？晚高峰经常遇到连接秒断的问题，大概4、5次会趋于稳定，如果分散到多路的话是否可以减少被切断的几率？
