### ISSUE TITLE
TCP 模式下，很多失效连接永远都不关闭的问题

### ISSUE THREAD

**Issue by k-ykl** [xtaci/kcptun#827]
arm openwrt 客户端启动：
2021/01/26 00:48:31 version: 20210103
2021/01/26 00:48:31 smux version: 1
2021/01/26 00:48:31 listening on: [::]:3333
2021/01/26 00:48:31 encryption: none
2021/01/26 00:48:31 nodelay parameters: 1 20 2 1
2021/01/26 00:48:31 remote address: host:3000
2021/01/26 00:48:31 sndwnd: 128 rcvwnd: 512
2021/01/26 00:48:31 compression: false
2021/01/26 00:48:31 mtu: 1350
2021/01/26 00:48:31 datashard: 10 parityshard: 3
2021/01/26 00:48:31 acknodelay: false
2021/01/26 00:48:31 dscp: 46
2021/01/26 00:48:31 sockbuf: 16777217
2021/01/26 00:48:31 smuxbuf: 4194304
2021/01/26 00:48:31 streambuf: 2097152
2021/01/26 00:48:31 keepalive: 10
2021/01/26 00:48:31 conn: 1
2021/01/26 00:48:31 autoexpire: 600
2021/01/26 00:48:31 scavengettl: 600
2021/01/26 00:48:31 snmplog:
2021/01/26 00:48:31 snmpperiod: 60
2021/01/26 00:48:31 quiet: false
2021/01/26 00:48:31 tcp: true
2021/01/26 00:48:31 initiating key derivation
2021/01/26 00:48:31 key derivation done

使用一段时间后，

# netstat -na|grep 3000
tcp        0      0 192.168.1.3:52804       104.168.21.155:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52298       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52682       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52612       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52372       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52638       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52764       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52888       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52724       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52482       102.153.201.85:3000     ESTABLISHED
tcp        0      0 192.168.1.3:52852       102.153.201.85:3000     ESTABLISHED

有11个建立的连接，实际上只有一个是真实有效的连接，跟服务器端能对上号，其他都是无效的，而且永远不会关闭。

**Comment by ddk2222-luck** [comment]
我也遇到了这样的问题，然后kcptun,的CPU直线上升

**Comment by ChainZeaxion** [comment]
> 

最近姬儿udp被鈤了，发现低流量无负载也被鈤，只能走tcp，怕一直搞udp封所有
也就发现了这个问题，怎么调参数都没用
而且，同样conn4的情况下，udp速度只有tcp模式的一半，丢包倒是不丢，我总带宽设的小，不超过50Mbps
现在只能先拆了kcp，让tcp裸奔grpc了

主要是现在发现裸奔tcp，且流量看起来正常http https的情况下
高带宽一定时间之后，容易被鈤，先拉成三倍延迟，再丢包tcp65% udp45%，总带宽强制在2Mbps以内
严重遭受暴击

目前临时方法是server上的前置nginx限速，爆发8000k然后限死5000k总带宽，估计还能勉强苟活一段时间

但是如果kcp修复了这个tcp模式链接ESTABLISHED不关闭的情况
理论上用kcp tcp多conn模式，来规避应该更好

单链接速度超过比如50Mbps，时间长达30秒，总带宽速度超过比如100Mbps，时间长达60秒
就会被拉延迟，而且比如半小时内发现这个情况多次出现，就开始丢包
如果还发现继续尝试跑高带宽，就会强制限速，惨不忍睹

所以如果kcp修复了tcp模式，就可以很好的规避单链速度和总线速度不过红线
