### ISSUE TITLE
请求添加 Linux_arm_client 对 VPN 的兼容

### ISSUE THREAD

**Issue by oyrx** [xtaci/kcptun#83]
手机上运行client_arm7的时候，只能使用Shadowsocks的NAT模式（VPN模式无法连接到本机KCPTUN），估计没考虑到对VPN网卡的兼容，希望作者添加一下，辛苦了。

**Comment by xtaci** [comment]
这个我不会，看有没有会的

**Comment by Yangleis** [comment]
同样是client_arm7,我也用的shadowsocks，VPN模式一直正常连接，建议更新shadowsocks，并检查配置是否正确。

**Comment by oyrx** [comment]
Nexus 5X, Android 6.01, client_arm7, Shadowsocks Play 最新版, Iptables 全部放行， VPN模式无法连接，NAT完美使用，配置正确无误。不知道楼上正常使用的的是什么手机和系统？

感觉没有比我手机更标准的环境了。。。

**Comment by codexss** [comment]
已经修复了，下载3.0.2版本。
https://github.com/shadowsocks/shadowsocks-android/issues/795

**Comment by oyrx** [comment]
感谢两位作者
