### ISSUE TITLE
为何压缩在sess而不是fec

### ISSUE THREAD

**Issue by LLRukia** [xtaci/kcptun#832]
看起来fec有自己的header，compress也有，如果把压缩挪到fec层是不是可以顺便把kcpheader和fec header一起压缩了呢？

**Comment by xtaci** [comment]
当然不行啊，压缩有自己的header，这个header要放到fec层那就是IP包内，1500字节。payload就更小了啊。

**Comment by LLRukia** [comment]
emm，在下不才没有听明白您的意思，在下的想法是这样的：
ipheader fecheader [encrypted](kcpheader compheader [compressed](palyload))
vs.
ipheader compheader [compressed](fecheader encrypted(kcpheader palyload))
扩大了compressed的范围，但是缺陷大概是deencrypt也许是很快的 但是decompress可能很慢，如果发生较多重传(重复sn的包较多)，会浪费很多cpu在decompress上。但是这样对丢包、乱序不高的场景来说，流量是最好的

**Comment by LLRukia** [comment]
或者说我的疑问是为什么现在的方案是这样的：fec层在kcp以下 udp以上。
或者换个思路，能不能是：
`ipheader kcpheader fecheader [encrypted](compheader [compressed](palyload))`

**Comment by xtaci** [comment]
> 感谢回复！
> emm，在下不才没有听明白您的意思，在下的想法是这样的：
> 
> ```
> ipheader fecheader [encrypted](kcpheader compheader [compressed](palyload))
> vs.
> ipheader compheader [compressed](fecheader encrypted(kcpheader palyload))
> ```
> 
> 扩大了compressed的范围，但是缺陷大概是decrypt也许是很快的 但是decompress可能很慢，如果发生较多重传(重复sn的包较多)，会浪费很多cpu在decompress上。但是这样对丢包、乱序不高的场景来说，流量是最好的

不行啊, compress 也有自己的固定头部。

**Comment by xtaci** [comment]
> 或者说我的疑问是为什么现在的方案是这样的：fec层在kcp以下 udp以上。
> 或者换个思路，能不能是：
> `ipheader kcpheader fecheader [encrypted](compheader [compressed](palyload))`

你都encrypt了，那么compress有什么用呢？ information entropy

**Comment by LLRukia** [comment]
再次感谢回复！

我觉得可能您没有理解我的意思：

现在的做法：`ipheader fecheader [encrypted](kcpheader compheader [compressed](palyload))`
做法1：`ipheader compheader [compressed](fecheader encrypted(kcpheader palyload))`
=> compress的头部在最前
收益：把kcp header和fec header一起压缩了（您的意思是header压缩完全没有收益吗）
坏处：在kcp层input之前一定需要decompress，重传或乱序的包有性能损失

做法2：`ipheader kcpheader fecheader [encrypted](compheader [compressed](palyload))`
收益：避免了kcp input之前的decrypt，重复包可以直接丢弃而不需要解密，在发送加工时，fec层处理的buffer长度也会变短
坏处：

**Comment by xtaci** [comment]
> 再次感谢回复！
> 
> 我觉得可能我没有表达清楚：
> 
> 现在的做法：`ipheader+udpheader fecheader [encrypted](kcpheader compheader [compressed](palyload))`
> 做法1：`ipheader+udpheader compheader [compressed](fecheader encrypted(kcpheader palyload))`
> => compress的头部在最前
> 收益：把kcp header和fec header一起压缩了（您的意思是header压缩完全没有收益吗）**(回答：对）**
> 坏处：在kcp层input之前一定需要decompress，重传或乱序的包有性能损失
> 

> 做法2：`ipheader+udpheader kcpheader fecheader [encrypted](compheader [compressed](palyload))`
> 收益：避免了kcp input之前的decrypt，重复包可以直接丢弃而不需要解密，在发送加工时，fec层处理的buffer长度也会变短
> 坏处：**（回答：那kcp header, fecheader的包特征岂不是特别明显？很容易被MITM攻击啊）**

**Comment by adcen0107** [comment]
那为什么不将fec头也加密呢？

**Comment by adcen0107** [comment]
@LLRukia ，@xtaci说的“你都加密了压缩还有什么用”，我感觉是这个意思：
你选定了一个payload，这个payload的长度是根据mtu和各个头的计算得出来的最大payload，然后对这一整块进行整体加密（不知道是否有加密和完整性计算在里面？），封包……
如果你先加密、再压缩，这个时候这个payload块大小已经在前面选定了，你再压缩，即使把1400字节压缩到500字节，你此时不可能再去拿另外一个数据块，加密，压缩，然后续到当前的payload后面，组成同一个包发出去吧。
所以你先加密，再压缩，从工程上来看不会这样实施的。
PS ：我一直关注KCP相关的，但还没有时间看KCPTUN源码，理解也不一定对，请指正！

**Comment by LLRukia** [comment]
> > 再次感谢回复！
> > 我觉得可能我没有表达清楚：
> > 现在的做法：`ipheader+udpheader fecheader [encrypted](kcpheader compheader [compressed](palyload))`
> > 做法1：`ipheader+udpheader compheader [compressed](fecheader encrypted(kcpheader palyload))`
> > => compress的头部在最前
> > 收益：把kcp header和fec header一起压缩了（您的意思是header压缩完全没有收益吗）**(回答：对）**
> > 坏处：在kcp层input之前一定需要decompress，重传或乱序的包有性能损失
> 
> > 做法2：`ipheader+udpheader kcpheader fecheader [encrypted](compheader [compressed](palyload))`
> > 收益：避免了kcp input之前的decrypt，重复包可以直接丢弃而不需要解密，在发送加工时，fec层处理的buffer长度也会变短
> > 坏处：**（回答：那kcp header, fecheader的包特征岂不是特别明显？很容易被MITM攻击啊）**

明白，感谢您

**Comment by LLRukia** [comment]
> @LLRukia ，@xtaci说的“你都加密了压缩还有什么用”，我感觉是这个意思：
> 你选定了一个payload，这个payload的长度是根据mtu和各个头的计算得出来的最大payload，然后对这一整块进行整体加密（不知道是否有加密和完整性计算在里面？），封包……
> 如果你先加密、再压缩，这个时候这个payload块大小已经在前面选定了，你再压缩，即使把1400字节压缩到500字节，你此时不可能再去拿另外一个数据块，加密，压缩，然后续到当前的payload后面，组成同一个包发出去吧。
> 所以你先加密，再压缩，从追求快速发包的目的来看，不会实现这种流式传输，所以不会那种实现的。且不安全。
> 
> PS ：我一直关注KCP相关的，但还没有时间看KCPTUN源码，理解也不一定对，请指正！

大师的回复是：information entropy
你说的完全可以实现啊，应用层加密压缩完了kcp_send即可，kcp->stream==1 or 0都可以，并不一定要在kcp_output后压缩的

**Comment by LLRukia** [comment]
补充一下，因为应用场景不一样，我们(游戏场景)用kcp都是小包，追求低延迟，kcptun我理解应该追求高带宽。所以对于小包来说，压缩header我理解也有不错的收益，但对于每个都达到MTU才发出去的场景显然没有收益。并且我们跑在移动端，对多余的算力流失比较敏感，kcptun并不在乎这点算力。
加上kcpheader + fecheader的特征很明显对我们来说也没有关系，因为场景不一样。

**Comment by adcen0107** [comment]
information entropy，这个我没懂是什么意思呢。。
技术上我没说不能实现，我说的是，先加密再压缩成小包，然后一个payload里面有包含多个压缩包，这样在弱网下并不能实现快速传输，不能高吞吐，所以不会那样做。

**Comment by LLRukia** [comment]
> information entropy，这个我没懂是什么意思呢。。
> 技术上我没说不能实现，我说的是，先加密再压缩成小包，然后一个payload里面有包含多个压缩包，这样在弱网下并不能实现快速传输，不能高吞吐，所以不会那样做。

emm 你说的没错，但这和这里讨论的问题没关系，这个issue讨论的是压缩和加密和fec的先后次序以及包括范围，你说的那个问题不管压缩在哪一层哪一步都会有。

我的意思就是：弱网下重传效率和如何组织合包有关系，没错；但和如何组织单个包没太大关系

**Comment by adcen0107** [comment]
是的，但最重要的前提还是安全。所以加密一定是在kcp的外面的。我只是在想，似乎也应该把fec加密进去
