### ISSUE TITLE
如何根据rcvwnd直接计算出速度

### ISSUE THREAD

**Issue by k79e** [xtaci/kcptun#837]
为啥1000的rcvwnd 在280ms下是3.5MBps左右速度 这个速度能计算出来么

他是1000个包的意思么? 如果是那样 应该是5MB速度啊
然后我又用了2000个 发现速度变成7MBps了.....

我开始郁闷了 主页也没讲清楚具体到底咋回事啊. 那个写的犹如计算bdp一样....

2021-04-07 14:02:22
为什么1000/280=3.571!?? 和3.5正好一样!!! 这是怎么回事
可能是vm就有些问题 但是kvm也是那样 我换了个列队算法就变快了 不知道为啥
默认fifo还跑不上去速度么!??

**Comment by duzefu** [comment]
MTU*rcvwnd/ttl  =  1400*1000/0.28 = 5MB/S
就是不知道FEC的包是不是算在里面，是的话，还要扣除FEC报文的比例，如果FEC占20%的话，那就得扣除20%。。。大概

**Comment by nilfei** [comment]
mtu官方建议是1350
正常情况下路由设置是1480
因为adsl拨号原因，携带的头这样设置会友好一点
至于计算带宽的方式

**Comment by k79e** [comment]
丢包一样的情况下为什么把那个改大 速度还上去了 真是奇怪 难以理解....

**Comment by k79e** [comment]
1500rwnd 1.4kmtu 220-280ms 怎么能跑满100m 这又是为啥

**Comment by nilfei** [comment]
> 丢包一样的情况下为什么把那个改大 速度还上去了 真是奇怪 难以理解....
> 
> 

你是指的接收窗口吗，这个属于暴力发包，当然会变大吧

**Comment by nilfei** [comment]
窗口不是越大越好的

**Comment by k79e** [comment]
是不是那样相当于fec也变大了
e.g 1000*0.1fec 1500*0.1fec
