### ISSUE TITLE
程序执行获取系统时间问题

### ISSUE THREAD

**Issue by stuxnet** [xtaci/kcptun#839]
程序执行日志输出的是UTC时间
date -R 获取的是CST-8时间
![image](https://user-images.githubusercontent.com/2310075/115819849-481b4980-a432-11eb-8e8d-b39e60fa04e5.png)
![image](https://user-images.githubusercontent.com/2310075/115820113-c8da4580-a432-11eb-945d-ddf326091afd.png)

**Comment by stuxnet** [comment]
![image](https://user-images.githubusercontent.com/2310075/115819962-7bf66f00-a432-11eb-883d-8efd439c7a6c.png)

**Comment by stuxnet** [comment]
可能是时差原因，出现 io: read/write on closed pipe

**Comment by lj7711622** [comment]
时差一样了 还是会这样
