### ISSUE TITLE
在fast和fast3模式下，保持sndwnd相同，降低interval参数是否间接地提高了sndwnd

### ISSUE THREAD

**Issue by raphael008** [xtaci/kcptun#856]
问题背景：
使用kcptun多年，总体效果优秀，但近期经常性断流，5-10分钟自动恢复，怀疑被运营商QoS，宽带为包邮区电信300M。
使用iperf进行对双边实际带宽进行测试，分别于早晚（对应网络情况良好与拥堵的场景）进行多次不同参数测试，测试发现
1. 单个udp datagram大小为1024bytes时，丢包率几乎为0。
2. 单个udp datagram大小为2048bytes时，丢包率为11%，偶尔触发QoS导致断流。
3. 单个udp datagram大小为4096bytes时，丢包率为30-50%，经常性触发QoS导致断流。

实际测得local <-> vps的带宽在3MBytes并且单个 udp datagram=1024bytes是比较稳定的。
因此猜想是否可以在保持降低kcptun sndwnd参数不变或降低kcptun sndwnd参数的同时，降低interval参数来保证带宽的利用率。举个不恰当的例子，本来6车道最高时速100的高速公路，调整成2车道最高时速150的高速公路。

Mode中提供的fast, fast3预设了interval值，分别为10，30。kcp的doc对于interval参数一笔带过了，_**Protocol internal work interval, in milliseconds, such as 10 ms or 20 ms.**_，正如作者所说，巭孬嫑乱改参数，不太了解更改interval参数会对kcptun实际传输带来什么影响，遂来提问。是否可以理解为在sndwnd以及其他参数相同的情况下，fast3(interval 10)的理论带宽传输速度上限是fast(interval 30)的3倍？

**文档中关于如何达到最大带宽的部分，wnd * mtu / rtt的单位是byte吗**，假设local<->vps的实际带宽为3MBytes(3145728 bytes/sec)，1024bytes(wnd) * 1400bytes(mtu) / 180(ms) = 7964(bytes? Kbytes?)

理解错误的地方请帮忙指出，望各位予以解惑，感谢！

**Comment by xtaci** [comment]
> 问题背景： 使用kcptun多年，总体效果优秀，但近期经常性断流，5-10分钟自动恢复，怀疑被运营商QoS，宽带为包邮区电信300M。 使用iperf进行对双边实际带宽进行测试，分别于早晚（对应网络情况良好与拥堵的场景）进行多次不同参数测试，测试发现
> 
> 1. 单个udp datagram大小为1024bytes时，丢包率几乎为0。
> 2. 单个udp datagram大小为2048bytes时，丢包率为11%，偶尔触发QoS导致断流。
> 3. 单个udp datagram大小为4096bytes时，丢包率为30-50%，经常性触发QoS导致断流。
> 
> 实际测得local <-> vps的带宽在3MBytes并且单个 udp datagram=1024bytes是比较稳定的。 因此猜想是否可以在保持降低kcptun sndwnd参数不变或降低kcptun sndwnd参数的同时，降低interval参数来保证带宽的利用率。举个不恰当的例子，本来6车道最高时速100的高速公路，调整成2车道最高时速150的高速公路。
> 
> Mode中提供的fast, fast3预设了interval值，分别为10，30。kcp的doc对于interval参数一笔带过了，_**Protocol internal work interval, in milliseconds, such as 10 ms or 20 ms.**_，正如作者所说，巭孬嫑乱改参数，不太了解更改interval参数会对kcptun实际传输带来什么影响，遂来提问。是否可以理解为在sndwnd以及其他参数相同的情况下，fast3(interval 10)的理论带宽传输速度上限是fast(interval 30)的3倍？

**不能这么理解，主要是超时重传给对方的敏感度，比如20ms前已经超时了，30ms的interval可能会延迟10ms再发送给对方**

> 
> **文档中关于如何达到最大带宽的部分，wnd * mtu / rtt的单位是byte吗**，假设local<->vps的实际带宽为3MBytes(3145728 bytes/sec)，1024bytes(wnd) * 1400bytes(mtu) / 180(ms) = 7964(bytes? Kbytes?)
> 
> 理解错误的地方请帮忙指出，望各位予以解惑，感谢！

**Comment by raphael008** [comment]
@xtaci 感谢作者解答，看来interval的作用是我理解错了。
这样看来，似乎没有办法让kcptun保持一个较小的sndwnd充分利用实际带宽，还是需要一个合理的sndwnd配合FEC来跑满带宽。
UDP被QoS应该不是kcptun处理的范畴了，再次感谢！
