### ISSUE TITLE
手机使用 Client 需要注意的三点问题，可收录 Wiki

### ISSUE THREAD

**Issue by oyrx** [xtaci/kcptun#86]
1. 其他客户端只能使用 `NAT模式 `连接本机 Kcptun， `VPN模式` 无法连接
2. 权限别忘了 `chmod +x`
3. 终端直接运行的话，退出终端后 Kcptun 会被内存管理终止，可以使用 `nohup` 不输出日志（输出日志会read only错误，因为目录不可读）

实测 `Kcptun armv7 client` 官方预编译在 `Nexus 5x` 上完美运行。

**Comment by Yangleis** [comment]
一直用的VPN模式，可以连接。不能连接可能是个例。

**Comment by wxyzh** [comment]
路由模式，udp协议

**Comment by oyrx** [comment]
你们可以连接的是什么手机系统？我 Nexus5x Android6.01, iptables全部放行，Shadowsocks play最新版不能连。切换nat一切正常，并且不止我一个人出现无法连接的情况。

**Comment by shutup** [comment]
@oyrx 我写了一个简单的wrapper [Kcptun_android](https://github.com/shutup/Kcptun_android)，我在测试的时候发现vpn是不可以的，nat我也没有成功，可以把你的nat操作步骤发出来吗？我再试试。

**Comment by shutup** [comment]
@oyrx 你好，我刚才又测试了一下，nat模式确实是可行的。
@Yangleis 您好，您的使用场景是同一个设备吗？在使用VPN模式的时候？

**Comment by oyrx** [comment]
@shutup 嗯只有NAT可以
@Yangleis 我认识的人都没法用VPN，请问你是怎么连得？
