### ISSUE TITLE
kcptun不支持shadowsocks+v2ray-plugin?

### ISSUE THREAD

**Issue by xiedeacc** [xtaci/kcptun#874]
我aws ec2 ubuntu服务器shadowsocks使用v2ray-plugin配置了tls，不使用kcptun情况下，能正常科学上网，加了kcptun转发后，客户端就不能科学上网了，是shadowsocks加了v2ray-plugin后，kcptun没法转发正确端口吗？

FYI:
服务器端和客户端版本一致，最新版本

kcptun server和client都连接到了正确端口，-key  -nocomp, -datashard, -parityshard,  -key, -crypt, -smuxver一致

kcp_tun_server.json，
```
{
    "listen ": ":29900",
    "target ": "127.0.0.1:1080",
    "crypt": "none",
    "mode": "fast",
    "mtu": 1350,
    "sndwnd": 512,
    "rcvwnd": 512,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": true
}
```
cat /etc/kcp_tun_client.json
```
{
    "localaddr": ":12948",
    "remoteaddr": "[2406:da1e:ac0:9210:2480:df34:f00e:bd10]:29900",
    "crypt": "none",
    "mode": "fast",
    "mtu": 1350,
    "sndwnd": 512,
    "rcvwnd": 512,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": true,
    "quiet": true
}
```

**Comment by xiedeacc** [comment]
ps：防火墙是否关闭了UDP通信，或者设置了UDP的最大发包速率？这个怎么check？google了没找到方式

**Comment by cupen** [comment]
kcptun 只是流量隧道 ，并不关心你 tcp 之上是什么协议。
检查下端口是否配错，但也不排除  https 流量经 kcp 包装后被墙探测到了。
也许你可以先本机或内网测试下，先排除掉一些错误。
