### ISSUE TITLE
Build error on  v20220627

### ISSUE THREAD

**Issue by HiGarfield** [xtaci/kcptun#879]
./build-release.sh 
Setting GO111MODULE to on
../vendor/github.com/klauspost/reedsolomon/options.go:6:2: cannot find package "." in:
	/home/higarfield/v20220627/kcptun-20220627/vendor/github.com/klauspost/cpuid/v2
../vendor/github.com/klauspost/reedsolomon/options.go:6:2: cannot find package "." in:
	/home/higarfield/v20220627/kcptun-20220627/vendor/github.com/klauspost/cpuid/v2

**Comment by HiGarfield** [comment]
It seems that the dependency cpuid is missing.

**Comment by chenrui333** [comment]
Seen the same issue, update vendor files would be good.

**Comment by xtaci** [comment]
fixed

**Comment by chenrui333** [comment]
how did you make a release, when it has a compilation issue? I am a bit confused.

**Comment by xtaci** [comment]
forgot to git add .
there are new files in vendor

**Comment by xtaci** [comment]
./build-release.sh
