### ISSUE TITLE
遇到DNS查询失败，可能会导致程序退出。

### ISSUE THREAD

**Issue by openertech** [xtaci/kcptun#88]
错误日志：
2016/07/29 13:10:36 session shutdown
2016/07/29 13:10:46 lookup j4.xxxx.xxx on 192.168.3.133:53: dial udp 192.168.3.133:53: i/o timeout

其他错误还有：
2016/07/29 04:02:54 [ERR] yamux: keepalive failed: i/o deadline reached
2016/07/29 04:02:54 [ERR] yamux: Failed to read header: broken pipe
长时间运行后会遇到上述错误，但不影响程序运行

**Comment by xtaci** [comment]
都连不上server，不退出还能干什么？

**Comment by openertech** [comment]
这个问题是由于，我们使用域名的方式来连接。我们服务器没有出错，只是域名查询暂时不返回结果导致的错误。

没有具体看代码，但是说明查询域名比较多，才导致了这个问题。而 DNS查询失败是个普遍可能发生的事情。
这个问题在我们运行了2天左右的时候就发生，已经重复发生过了几次。 希望能改进一下。例如将服务器地址先缓存一下，不用去多次查询。这样应该也可以提高程序的效率。

**Comment by xtaci** [comment]
域名查询和kcp没有任何关系， client只会在启动的时候会Dial***解析一次***服务器的域名。

yamux错误是通信故障，原因很多，但和dns没有关系。

**Comment by openertech** [comment]
2016/07/29 13:10:46 lookup j4.xxxx.xxx on 192.168.3.133:53: dial udp 192.168.3.133:53: i/o timeout
这个错误 应该是DNS查询出错吧？

这个错误出现在运行了1天以后。 有需要再次重新连接的情况吗？

**Comment by xtaci** [comment]
如果通信中断，client会尝试重新连接， 这个时候会解析一次服务器域名，如同刚启动一样。

**Comment by openertech** [comment]
具体看了一下代码，这个错误是yamux 里面的keepalive ping的时候出的。与kcptun自身没有太多关系。

我还需要再具体分析一下，为什么会退出程序。谢谢你的答复。
