### ISSUE TITLE
10月份GFW更新后，kcptun被墙？

### ISSUE THREAD

**Issue by jnxyatmjx** [xtaci/kcptun#887]
服务端：-t "0.0.0.0:12345" -l ":8388" --mode fast3 --nocomp --sockbuf 16777216 --smuxbuf 16777216  --smuxver 2 --streambuf=4194304 --dscp 46 --crypt none --sndwnd 2048 --rcvwnd 1024 --quiet

客户端：-r "IP地址:8388" -l ":10888" --mode fast3 --nocomp --sockbuf 16777216 --smuxbuf 16777216 --smuxver 2 --streambuf=4194304 --dscp 46 --crypt none --sndwnd 1024 --rcvwnd 2048 --quiet --conn 7  --autoexpire 3600

采用ss+gost+kcptun的方式，最后由kcptun进行服务端和客户端的通讯，GFW更新后无法正常使用了。

**Comment by yjd** [comment]
换端口和密码

**Comment by HiGarfield** [comment]
--crypt none 这个不合适吧？

**Comment by nagae-memooff** [comment]
我觉得不是crypt none导致的问题。我从10月6号开始，也几乎每天被封一个kcptun的端口。加密方法用默认的aes，key是一个非默认的、字母数字混合的短字符串。

参数类似于： -t "xxx:447" -l ":4000" -mode fast3 -nocomp -sockbuf 16777217 -dscp 46 --quiet  --mtu 1200 --sndwnd 2048 --rcvwnd 2048 --keepalive 30 --key xxxx(非默认)

当“网络不通”时，双方抓包看现象，服务端能收到客户端发来的udp包，但服务器到客户端方向的udp被丢包了。换个端口就能临时继续用，但一天或几个小时之后，又会被封，现象一样。而且被封后，宽带、移动和联通的4G都会无法连接，不会出现以前有些运营商自己限制udp，如果重新拨号宽带，换了ip地址就能继续用的情况。

除此之外，我的linux客户端机器上，在kcptun之外多套了一层udp2raw，这个端口目前一直正常没有被封（手机由于没有root，不能用udp2raw）。

我推断是kcptun的协议特征已经能够被gfw精准识别。

**Comment by HiGarfield** [comment]
> crypt

那就是无差别封大流量udp吧。那只能再用udp2raw封回tcp了。

另外，你可以考虑直接在路由器上搞个udp2raw，这样就不用手机上运行这玩意儿了。

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20221008

**Comment by jnxyatmjx** [comment]
> https://github.com/xtaci/kcptun/releases/tag/v20221008

立马试下看看效果

**Comment by jnxyatmjx** [comment]
> [](https://github.com/xtaci/kcptun/releases/tag/v20221008)
在公司电信网络下一段时间后也不能使用。在家的移动网络下目前看还能正常使用

**Comment by xtaci** [comment]
maybe you can set up a port range + autoexpire to do round robin

**Comment by Goooooooooood** [comment]
我也是使用ss+kcptun，加密方式和密码都很简单。用了一年多，一切正常。

iPhone和VPS通讯 使用ss+kcptun；
PC和VPS通讯 使用ss+kcptun；
路由器和VPS通讯 使用udp2raw+ss+kcptun。

VPS使用IPv4+IPv6。
ss-server只监听来自127.0.0.1:端口的访问，而不是监听0.0.0.0:端口的访问，因为会被探测到。

感觉不太像是楼上说的被精准识别，ss直连秒封端口，那才叫精准识别吧？

**Comment by yuchu01** [comment]
@xtaci win10 download it reminder "Virus detected", before version not

**Comment by xtaci** [comment]
> @xtaci win10 download it reminder "Virus detected", before version not

strange, try compile by yourself.

**Comment by zyf0330** [comment]
在我这儿的现象是，往国外服务器建立一个 udp 连接，开始的几秒可以传输，过了几秒就双向阻断了。

北京移动宽带

**Comment by krrr** [comment]
我的套了udp2raw，一直没被封过，可以试试

**Comment by nagae-memooff** [comment]
反馈新情况： 家中路由器套了udp2raw，近期一直能用；
手机端由于没有root不能使用伪tcp机制，所以只能在外层直接使用kcptun。保险起见，我的手机端和家中路由器使用的不是同一台服务器。
服务端更新后支持端口范围，但由于安卓的kcptun还没有更新最新版，所以还是只能写一个端口，被封了就换端口。我发现的情况是： 如果被封→换端口这个行为持续过几次，就会整个服务器IP被封。

**Comment by zyf0330** [comment]
shadowsocks-kcptun 看起来是不会再更新了，自己编译吧。
倒是手机上看来也没有使用 cap_net_raw 的办法，除了 root 没办法用 tcp 模式.

要么就直接用脚本跑 kcptun 的 armv7 build.

**Comment by semigodking** [comment]
一模一样的情况。现在的情况是，不知道这些端口多少天才会被放出来。现在正在用最新版，每半小时换端口。看看几万个端口会不会都被封完。
挺神奇的，居然这么好心，per 来封，一个ip就六万条记录，数据库挺大的

**Comment by mailsex** [comment]
在kcptun 20221015版本出来之前，我一直在服务器和客户端用NAT实现的UDP动态端口，没有遇到过被运营商Qos UDP连接的情况

**Comment by mailsex** [comment]
> > 
> 
> 能说下，具体实现吗

现在最新的kcptun自带动态端口了。我之前实现的方法局限性很高。没有新版kcptun灵活，建议用新版kcptun实现即可。

**Comment by wyfang** [comment]
> 我觉得不是crypt none导致的问题。我从10月6号开始，也几乎每天被封一个kcptun的端口。加密方法用默认的aes，key是一个非默认的、字母数字混合的短字符串。
> 
> 参数类似于： -t "xxx:447" -l ":4000" -mode fast3 -nocomp -sockbuf 16777217 -dscp 46 --quiet --mtu 1200 --sndwnd 2048 --rcvwnd 2048 --keepalive 30 --key xxxx(非默认)
> 
> 当“网络不通”时，双方抓包看现象，服务端能收到客户端发来的udp包，但服务器到客户端方向的udp被丢包了。换个端口就能临时继续用，但一天或几个小时之后，又会被封，现象一样。而且被封后，宽带、移动和联通的4G都会无法连接，不会出现以前有些运营商自己限制udp，如果重新拨号宽带，换了ip地址就能继续用的情况。
> 
> 除此之外，我的linux客户端机器上，在kcptun之外多套了一层udp2raw，这个端口目前一直正常没有被封（手机由于没有root，不能用udp2raw）。
> 
> 我推断是kcptun的协议特征已经能够被gfw精准识别。

如何判断是端口被封？

**Comment by zyf0330** [comment]
现在，我之前被封的端口还无法使用。不过新的端口没有再被封了。

> 我觉得不是crypt none导致的问题。我从10月6号开始，也几乎每天被封一个kcptun的端口。加密方法用默认的aes，key是一个非默认的、字母数字混合的短字符串。
> 
> 参数类似于： -t "xxx:447" -l ":4000" -mode fast3 -nocomp -sockbuf 16777217 -dscp 46 --quiet --mtu 1200 --sndwnd 2048 --rcvwnd 2048 --keepalive 30 --key xxxx(非默认)
> 
> 当“网络不通”时，双方抓包看现象，服务端能收到客户端发来的udp包，但服务器到客户端方向的udp被丢包了。换个端口就能临时继续用，但一天或几个小时之后，又会被封，现象一样。而且被封后，宽带、移动和联通的4G都会无法连接，不会出现以前有些运营商自己限制udp，如果重新拨号宽带，换了ip地址就能继续用的情况。
> 
> 除此之外，我的linux客户端机器上，在kcptun之外多套了一层udp2raw，这个端口目前一直正常没有被封（手机由于没有root，不能用udp2raw）。
> 
> 我推断是kcptun的协议特征已经能够被gfw精准识别。

**Comment by wyfang** [comment]
我尝试把29900端口换成29901，瞬间恢复正常了。有什么办法可以检测我的29900什么时候恢复？还是必须得换会来才能试。

**Comment by zyf0330** [comment]
> 现在，我之前被封的端口还无法使用。不过新的端口没有再被封了。 而且还有个现象是，我抓包看到，服务端上下行都有包，客户端没有下行的。另外，我用 `nc` 在同一个端口上发送 udp 包，并没有被阻断。
> 
> > 我觉得不是crypt none导致的问题。我从10月6号开始，也几乎每天被封一个kcptun的端口。加密方法用默认的aes，key是一个非默认的、字母数字混合的短字符串。
> > 参数类似于： -t "xxx:447" -l ":4000" -mode fast3 -nocomp -sockbuf 16777217 -dscp 46 --quiet --mtu 1200 --sndwnd 2048 --rcvwnd 2048 --keepalive 30 --key xxxx(非默认)
> > 当“网络不通”时，双方抓包看现象，服务端能收到客户端发来的udp包，但服务器到客户端方向的udp被丢包了。换个端口就能临时继续用，但一天或几个小时之后，又会被封，现象一样。而且被封后，宽带、移动和联通的4G都会无法连接，不会出现以前有些运营商自己限制udp，如果重新拨号宽带，换了ip地址就能继续用的情况。
> > 除此之外，我的linux客户端机器上，在kcptun之外多套了一层udp2raw，这个端口目前一直正常没有被封（手机由于没有root，不能用udp2raw）。
> > 我推断是kcptun的协议特征已经能够被gfw精准识别。

我纠正一下，使用 `nc` 测试，下行的 udp 包也被阻断了。所以我推断还是端口封禁，而不是协议被识别。

**Comment by semigodking** [comment]
感觉最新版本有内存泄露。我开200个端口，过一段时间会OOM

**Comment by zplzpl** [comment]
> 

可以说，是一模一样了

**Comment by vinograd-cyber** [comment]
> 我的套了udp2raw，一直没被封过，可以试试

udp2raw的伪造tcp协议流已经被墙识别为可疑流量了， 只有最新版的kcptun的动态udp端口在20大期间没被墙

**Comment by DizzyPPP** [comment]
> > 我的套了udp2raw，一直没被封过，可以试试
> 
> udp2raw的伪造tcp协议流已经被墙识别为可疑流量了， 只有最新版的kcptun的动态udp端口在20大期间没被墙

windows不支持动态udp端口是不是意味着告别kcptun了？

**Comment by Hervey424** [comment]
> 感觉最新版本有内存泄露。我开200个端口，过一段时间会OOM

本来只是被封端口了, 套上udp2raw后ip封了

**Comment by krrr** [comment]
> > 我的套了udp2raw，一直没被封过，可以试试
> 
> udp2raw的伪造tcp协议流已经被墙识别为可疑流量了， 只有最新版的kcptun的动态udp端口在20大期间没被墙

我现在用的还好得很。确定不是你的ip段被墙盯上了？

**Comment by wzjwhtur** [comment]
> 

这个容易ip被封

**Comment by jnxyatmjx** [comment]
影响已经知晓

**Comment by ddzx** [comment]
你想干嘛？

**Comment by ddzx** [comment]
现在的默认不自己二开处理的全部被识别
