### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by terryxuwen** [xtaci/kcptun#899]

**Comment by swxk521** [comment]
关键没大佬更新

**Comment by laikitleung** [comment]
其實我倒覺得這個端口範圍沒有必要，設置filter時一條命令就能設置好端口範圍轉發了。如果設置了這個範圍比如1000個端口，查看的時候很恐怖，1000個端口都會顯示出來。

**Comment by mbicc** [comment]
> 

直接用记事本编辑kcptun_gclient的客户端列表配置文件就可以设置端口范围
