### ISSUE TITLE
最新的5月6日编译包i386 linux版本有问题，运行时显示trace/breakpoint trap，无法执行。

### ISSUE THREAD

**Issue by appleatiger** [xtaci/kcptun#9]
最新的5月6日编译包i386 linux版本有问题，运行时显示trace/breakpoint trap，无法执行。

**Comment by xtaci** [comment]
解决了?

**Comment by appleatiger** [comment]
并没有解决，但是我认为是我服务器本身有问题，上个版本之前好好的，换了新的，然后就搞不定了，再换回去也不行了。

**Comment by xtaci** [comment]
这个错误我查了下，貌似是gdb调试中才会出现的，我没有i386 linux的环境，麻烦帮忙确认下问题。amd64/darwin64 都是可以的，可执行文件都是同一批次交叉编译的。

**Comment by appleatiger** [comment]
ok，我会继续看是怎么回事。

**Comment by appleatiger** [comment]
我在环境中进行go get github.com/xtaci/kcptun/server，然后报错以下：
go build github.com/codegangsta/cli: /usr/lib/golang/pkg/tool/linux_386/compile: signal: trace/breakpoint trap
go build github.com/hashicorp/yamux: /usr/lib/golang/pkg/tool/linux_386/compile: signal: trace/breakpoint trap
go build github.com/xtaci/kcp-go: /usr/lib/golang/pkg/tool/linux_386/compile: signal: trace/breakpoint trap

**Comment by appleatiger** [comment]
明天重装环境再试试吧

**Comment by xtaci** [comment]
估计是go语言安装包损坏，重新安装下 go

**Comment by appleatiger** [comment]
嗯，我把go安装包给去除了，然后就正常了。

**Comment by YaleHuang** [comment]
这问题没解决啊
