### ISSUE TITLE
关于手机上应用问题

### ISSUE THREAD

**Issue by say2say** [xtaci/kcptun#90]
你好，我在手机上测试使用kcptun发现一个现象：
我的环境是：手机ss连接kcp客户端--->服务端kcp
手机发起连接，服务端无任何消息提示，
当断开ss时候，服务端收到一大串：
stream opened
stream closed
貌似只有当断开ss时候客户端才发消息到服务端？
这是什么问题引起的呢？
服务端和客户端都是最新的0725版本
谢谢

**Comment by xtaci** [comment]
我并不清楚手机的使用，你可以问下做手机port的人

**Comment by oyrx** [comment]
@say2say 
可能你的手机SS用的VPN模式，根本没法链接到KCPTUN。。。所以没有连接提示。
切换成NAT模式应该就可以了。

**Comment by say2say** [comment]
@oyrx 让我碰到你了。。欧阳。。
用NAT模式后的确可以了，thx
