### ISSUE TITLE
kcptun到底怎么工作的呢

### ISSUE THREAD

**Issue by jnxyatmjx** [xtaci/kcptun#902]
从去年10月份被墙阻断后，就尝试使用自定义kcp协议、修改加密算法。但一直被墙阻断，到底怎么甄别拿出是kcptun的呢？
单纯的 kcp-go却能正常使用。真是太奇怪了

**Comment by alongL** [comment]
单纯的 kcp-go却能正常使用. 这个可以展开说说吗？怎么用的？

**Comment by jnxyatmjx** [comment]
> 单纯的 kcp-go却能正常使用. 这个可以展开说说吗？怎么用的？

比如kcp-go里的例子程序可以正常使用，同时gost里的 kcp协议也是可以正常用的。

**Comment by jnxyatmjx** [comment]
现在看单独运行kcp-go里的 例子，长事件也不行了。

**Comment by woodlyer** [comment]
现在都在用tuic

**Comment by jnxyatmjx** [comment]
被墙的原因 跟协议用加密组件有关

**Comment by jnxyatmjx** [comment]
最近花时间对比了了主流的几个方法。不得不说kcp这个协议在网络拥挤vps低速环境下的优异表现。单纯测速确实不高。但是用网高峰期多开几个4k视频，表现高下立判

**Comment by jnxyatmjx** [comment]
透明路由还是要要一层kcp啊
