### ISSUE TITLE
关于AES等对称加密被识别的看法

### ISSUE THREAD

**Issue by fannwong001** [xtaci/kcptun#905]
最近使用crypto的aes，发现是固定源数据流加密出来的数据流是相同的，当然这是对称加密的原因。
但我的意思是想跟ss-libev那样，一个stream一个加密始末，比如某几个字节在stream中的offset固定的话，加密出来的数据才是相同的，就是构造的key在加密完一个数据包后要保存状态，下一个包继续从刚才的状态继续，这样从单包来看，加密后的数据就可能是不相同的了。但是这要依据tcp的顺序保证，udp的话无法保证，只能单包为单位，而这样单包的头部经常是固定的，容易被识别。（如果把固定信息放到尾部应该会有帮助）。
比较奇怪的是，为什么go语言的crypto/aes没有提供保存构造key状态的用法。

**Comment by xtaci** [comment]
![image](https://user-images.githubusercontent.com/2346725/218366952-3622180f-4088-4e95-ab34-b3210b2bf41b.png)

**Comment by fannwong001** [comment]
ok谢谢，我只是参考官方例子用的，没有详细看你的使用，没有抓kcp的包。
