### ISSUE TITLE
一天，甚至几小时就被封端口

### ISSUE THREAD

**Issue by kanelau** [xtaci/kcptun#907]
请问大家有什么解决办法了吗？谢谢

**Comment by xtaci** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/2346725/218399579-2ed7a25c-6e0e-4c43-af25-4cd39743c04b.png">

**Comment by kanelau** [comment]
Thanks, but there is no method to input a port range in android device.

**Comment by alongL** [comment]
https://github.com/segfault-bilibili/ShadowsocksGostPlugin  maybe you can try this gost plugin on Android.  
gost support kcp  and is safe for now.
server version: https://github.com/ginuerzh/gost

**Comment by kanelau** [comment]
> https://github.com/segfault-bilibili/ShadowsocksGostPlugin maybe you can try this gost plugin on Android. gost support kcp and is safe for now. server version: https://github.com/ginuerzh/gost

Many thanks. I have downloaded the plugin and sucessfully installed. But I don't know how config it at Android and server.
take my need as example:
1. SS is working with server 333.333.333.333 port 33333
2. KCPTUN is working at port 33334 and accelerating port 33333
3. If I installed gost at server, should I stop the KCPTUN? If I want to use the kcptun config for gost, the server side config looks like__**gost -L ss+kcp://AES-256-GCM:PASSWORD@33333?c=/path/to/conf/file_**_ right?
4. What the android plugin config looks like? same ? **gost -L ss+kcp://AES-256-GCM:PASSWORD@33333_**
5. what to input in SS for remote part/password/encrypt method? leave password blank and encrypt none?

**Comment by mbicc** [comment]
双方已经开了1000个端口....
可惜出门SS只能设置一个端口

**Comment by jnxyatmjx** [comment]
> https://github.com/segfault-bilibili/ShadowsocksGostPlugin maybe you can try this gost plugin on Android. gost support kcp and is safe for now. server version: https://github.com/ginuerzh/gost

from now on，gost‘s kcp have been blocked out

**Comment by woodlyer** [comment]
> > https://github.com/segfault-bilibili/ShadowsocksGostPlugin maybe you can try this gost plugin on Android. gost support kcp and is safe for now. server version: https://github.com/ginuerzh/gost
> 
> from now on，gost‘s kcp have been blocked out

I don't think gost's kcp is blocked.  If you think so, use this mod for kcptun.  
 https://github.com/woodlyer/kcptunMod

**Comment by zzlinwq** [comment]
现在，kcptun 无法使用。 总是被封锁。

**Comment by woodlyer** [comment]
本发明已经部分部署在边境监控审查系统平台中，具有对大量数据的分析能力，且检全率和准确率均在90％以上。

[一种KCP协议加密流量检测方法.pdf](https://github.com/xtaci/kcptun/files/13915565/KCP.pdf)

**Comment by xtaci** [comment]
> 本发明已经部分部署在边境监控审查系统平台中，具有对大量数据的分析能力，且检全率和准确率均在90％以上。
> 
> [一种KCP协议加密流量检测方法.pdf](https://github.com/xtaci/kcptun/files/13915565/KCP.pdf)

他们方法不太对，加密数据是无法按照字节推断的。一定是从流量特征入手，加上AI大数据模型。

**Comment by zzlinwq** [comment]
我想也没啥流量特征吧？流量比较大？

**Comment by nxtreaming** [comment]
流量特征与流量大小没什么关系。
