### ISSUE TITLE
会浪费5倍以上流量

### ISSUE THREAD

**Issue by isbaseby** [xtaci/kcptun#91]
经过多次测试，发现下载一个100M的文件服务器实际产生的出站流量是600多M甚至更多

本地带宽50M，附上配置

server_linux_amd64 -l :554 -t 127.0.0.1:3389 --crypt none --mtu 1400 --sndwnd 2048 --rcvwnd 2048 -dscp 46 -mode fast2

lient_darwin_amd64 -l 127.0.0.1:1081 -r 1.1.1.1:554 --crypt none --mtu 1400 --sndwnd 128 --rcvwnd 1024 -dscp 46 -mode fast2

**Comment by xtaci** [comment]
出现这个情况有几种可能:
1. ISP 对UDP丢包极高，例如50%
2. 服务器，客户端本身的带宽较低，可以适当调低sndwnd /rcvwnd
3. 可以尝试 -dscp 46参数降低丢包率。

**Comment by oyrx** [comment]
我这边大概两倍而已，可能你的ISP。。。

**Comment by isbaseby** [comment]
实际消耗流量稳定到了2倍多一点

**Comment by xtaci** [comment]
@isbaseby  FEC前向纠错默认参数就会多消耗30%（可以调整）,   KCP协议头部平均多消耗5%（无法调整）， 加上丢包，2倍还算正常。

**Comment by hbxntsxw** [comment]
@isbaseby @oyrx 能麻烦你们贴出消耗2倍的配置参数吗？我这里都消耗8-10倍了

**Comment by hbxntsxw** [comment]
下午和晚上再试了几次，发现消耗了13.7倍的流量，太恐怖了！模式选的是fast2，-dscp 46两端都加上了。不知道怎么优化？

**Comment by xtaci** [comment]
@hbxntsxw 多半是sndwnd/rcvwnd太高，你可以在client先降低到 128，然后慢慢再加，边加边观察。

**Comment by hbxntsxw** [comment]
我的服务端是-mtu 1350 -crypt none -nocomp -dscp 46 -sndwnd 1024 -rcvwnd 1024 -mode fast2 > kcptun.log 2>&1 
客户端是-crypt none -mtu 1350 -sndwnd 32 -rcvwnd 1024 -mode fast2 -dscp 46 -nocomp。

我的sndwnd和rcvwnd已经很低了吧。

**Comment by xtaci** [comment]
你的服务器能提供的带宽未知，丢包率未知，你需要把client的rcvwnd降下来，然后再慢慢加上去试，出现这种情况的可能性:
1. 服务器不能够提供充足的带宽，在机房其实就丢包了，但会计入带宽使用，需要降低rcvwnd。
2. 线路严重丢包50%以上，导致大量重传
3. 接收端导致的丢包，比如2.4Ghz 信号串扰，超出ADSL下行物理限制都可能导致大量重传。

**Comment by nxtreaming** [comment]
浪费这点流量算什么？
既然用了UDP，就必然会浪费部分流量，即使浪费10倍流量都没什么，因为国外流量极其便宜，20刀一个月的vps就有3TB流量了。

如果心疼流量直接用tcp的实现。

-----------------------------------------
Inspired by http://scale100.com

2016-08-07 23:30 GMT+08:00 xtaci <notifications@github.com>:

**Comment by hbxntsxw** [comment]
@xtaci 服务器是搬瓦工的，肯定超过100M，今天降低客户端rcvwnd到128，发现有很大改善，最好情况降到了3.6倍。已经可以接受了。

**Comment by xtaci** [comment]
@hbxntsxw 是的，你说的对，100M肯定是超卖，实际一定达不到，否则不会出现这种程度的重传。

**Comment by testcaoy7** [comment]
@hbxntsxw 为什么要降低客户端的rcvwnd呢，我觉得应该降低服务器端的sndwnd来调节速度，客户端的rcvwnd应该保持一个较大的值，服务器发来的数据照单全收

**Comment by hbxntsxw** [comment]
@testcaoy7 不知道是基于什么原理，我降低后消耗变小了。

**Comment by testcaoy7** [comment]
@hbxntsxw 也许是触发了congestion control的关系，服务器的发送速率在达到客户端接受极限后开始减速了

**Comment by testcaoy7** [comment]
@xtaci 我这边测试，保守估计也会浪费20倍的流量

**Comment by xtaci** [comment]
带宽不够就不要使用大窗口，量力而行

**Comment by testcaoy7** [comment]
@xtaci 刚刚为了测试sndwnd和rcvwnd故意把服务器的snd设置的极大，客户端的rcv设的很小，主要想试试客户端的rcvwnd是不是真的可以用来调节速度，可能正是这样造成大量丢包和重传的

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/blob/master/kcp.go#L657  取二者的小者

**Comment by sosmygirl** [comment]
rcvwnd为2048，我的刚好是10倍，rcvwnd降低为128，下载速度就没有加速一样，都不想改了

**Comment by isbaseby** [comment]
@hbxntsxw @testcaoy7 

我的配置
--crypt none --mtu 1400 --sndwnd 2048  --rcvwnd 2048  -dscp 46 -mode fast2
--crypt none --mtu 1400 --sndwnd 128  --rcvwnd 512  -dscp 46 -mode fast2

实际消耗流量不到两倍

**Comment by sosmygirl** [comment]
@isbaseby 我用你的配置小号大概2.5-3倍

**Comment by xtaci** [comment]
@sosmygirl 两边 ```-datashard 0 -parityshard 0``` 还可以更低，不过响应会慢，看你的接受程度。

**Comment by hbxntsxw** [comment]
@isbaseby 非常感谢！我的服务器是搬瓦工不知道行不行？

**Comment by testcaoy7** [comment]
@isbaseby 我现在把服务器的sndwnd和客户端的rcvwnd均设置为512，流量也在2.5到3倍，流量高的原因其实很简单，中国电信的国际出口是小水管，应该按国际出口的带宽设置，如果直接按买了多少兆的带宽来设只会因为大量丢包而无意义地焚烧流量

**Comment by hbxntsxw** [comment]
@testcaoy7 你这2.5-3倍有没有算上服务器从其他网站下载资源的流量啊？我是总的服务器进出流量消耗3.7倍，减去进入服务器的1倍流量，这样从服务器到客户端实际上只消耗了2.7倍。

**Comment by xmac1** [comment]
手机上使用shadowssocks统计的网速和安卓系统统计的网速比较之后实际流量大约是有效流量的1.5-2倍，用了楼上的配置，之前默认配置是2.5倍（已经接近物理带宽了，不知道能够达到几倍）！我才发现我用手机刷一下twitter就消耗了几百兆流量！

**Comment by kmahyyg** [comment]
我这1.5x......自己的配置

2016年11月7日 23:42，"xmac1" <notifications@github.com>写道：
