### ISSUE TITLE
target不能为udp端口嘛？

### ISSUE THREAD

**Issue by omaidb** [xtaci/kcptun#925]
之前的target都是为tcp端口，效果都很明显。
今天有个target为udp端口，客户端指定localaddr端口后，查看竟然是tcp协议，直接连不上了，因为不是udp。
kcptun不能为udp加速的嘛？

另外，请教下大佬们，如何打印详细的debug日志呢？方便诊断

**Comment by omaidb** [comment]
看到历史issue，就是不支持

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/942
