### ISSUE TITLE
关于kcptun的多端口跟udp2raw结合的配置问题

### ISSUE THREAD

**Issue by maojianyou** [xtaci/kcptun#935]
我现在如果kcptun配置
{
        "smuxver": 2,
        "listen": ":33666-34690", 
        "target": "127.0.0.1:2000", // 修改此处，指向：不用ss，改成其他服务
        "key": "PASSWORDPASSWORDPASSWORDPASSWORD", // 修改此处
        "crypt": "twofish",
        "mode": "fast3",
        "mtu": 1400,
        "sndwnd": 2048,
        "rcvwnd": 2048,
        "datashard": 10,
        "parityshard": 0,
        "dscp": 0,
        "nocomp": true,
        "acknodelay": false,
        "nodelay": 1,
        "interval": 20,
        "resend": 2,
        "nc": 1,
        "sockbuf": 16777217,
        "smuxbuf": 16777217,
        "streambuf":4194304,
        "keepalive": 10,
        "pprof":false,
        "quiet":false,
        "tcp":false
}
然后listen": ":33666-34690", 是公开的，那我看udp2raw不支持多端口，这种要怎么配置

**Comment by HiGarfield** [comment]
用脚本，开多个udp2raw的实例，每个实例负责一个端口。

**Comment by maojianyou** [comment]
> 用脚本，开多个udp2raw的实例，每个实例负责一个端口。

那如果我开100个端口，岂不是需要创建100个udp2raw进程，这种感觉太繁琐了

**Comment by maojianyou** [comment]
> 用脚本，开多个udp2raw的实例，每个实例负责一个端口。

这个Kcptun支持伪造源站目标IP给客户端回包不
