### ISSUE TITLE
连接成功后突发长时间卡顿（可重现，卡顿较长时间自动恢复）

### ISSUE THREAD

**Issue by Shilyx** [xtaci/kcptun#938]
client_windows_amd64.exe -l :155 -r 127.0.0.1:155
server_windows_amd64.exe -l :155 -t 127.0.0.1:80 

运行后畅通，此时观看一个视频后返回，则卡死。等待较长时间后自动恢复。
与此同时，直连tcp端口则没有问题。
此问题必现。
操作系统 win10 企业版，浏览器是 chrome beta 122.0.6261.6，软件是最新release：kcptun-windows-amd64-20240107（我自己编译的也有同样表现）

我录制了一个视频： https://github.com/xtaci/kcptun/assets/7777741/a180b91a-eee6-41e7-b919-70274a5f45c4

问问题前先搜索ISSUE，并搞清楚下面的问题:

1. 检查 ```-key xxx``` 至少三遍, ***保证***两边一致。【未传入key，使用默认key，因此一致】
2. 保证```-nocomp, -datashard, -parityshard,  -key, -crypt, -smuxver```两边一致。【未指定这些参数】
3. 是否在服务器端，正确设定了转发的目标服务器地址 ***--target***。【正确】
4. 是否在客户端，正确的连接到了 client的监听端口。【正确】
5. 如果第3条不确定，尝试在服务器上telnet target port试试。【成功时畅通】
6. 防火墙是否关闭了UDP通信，或者设置了UDP的最大发包速率？【无防火墙，127网络】
7. 两端的版本是否一致？【一致，kcptun-windows-amd64-20240107】
8. 是不是最新版本？【是最新版本】
9. 两端分别是什么操作系统？【本机，win10 企业版】
10. 两端的输出日志是什么？【见视频】

**Comment by fulirockx** [comment]
```
 "streambuf":4194304,
 "smuxver": 2,
```
试试加上这两个

**Comment by xtaci** [comment]
```
 "streambuf":4194304,
 "smuxver": 2,
```
试试加上这两个?

**Comment by xtaci** [comment]
如果可以，可以调大smuxbuf，并调小streambuf，多次测试，确认一下问题。

**Comment by Shilyx** [comment]
"smuxver": 2  这个管用
