### ISSUE TITLE
希望能增加监听UDP的功能

### ISSUE THREAD

**Issue by chainofhonor** [xtaci/kcptun#942]
客户端监听UDP端口 
服务器转发到UDP端口

这个需求是想用KCPTUN转发wireguard的流量

比如这样
client_windows_amd64.exe -l 192.168.0.2:4000/UDP -r 1.2.3.4:10000
server_windows_amd64.exe -l 1.2.3.4:10000 -t 127.0.0.1:4000/UDP

希望能增加这个功能

**Comment by linnuxx** [comment]
did udp2raw not help?

**Comment by xtaci** [comment]
https://github.com/xtaci/reorg
这个就是干这个事情的，在tun/tap上，模拟了一个设备。 但效果不尽人意，因为可能上层又有一层的ARQ算法。导致上层的ARQ模型错误了。

**Comment by linnuxx** [comment]
will it be possible to connect wireguard via kcptun sometime?
wireguard>udp2raw>kcptun not a working option.

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/issues/942
