### ISSUE TITLE
linux客户端占用CPU太大了。

### ISSUE THREAD

**Issue by kathylincn** [xtaci/kcptun#95]
直接跑满87% 相当于100%了。。速度上不去。在WINDOWS下用客户端，速度倒是能上的去。麻烦检测一下呢。用的最新版0725的

**Comment by oyrx** [comment]
，，，你的linux CPU是多少，，，VPS？

**Comment by kathylincn** [comment]
说的占用CPU太大，不是说的server,是说的client.客户端是debian7,也就是用的client_linux_amd64,内存占用低.CPU占用太高。

**Comment by xtaci** [comment]
@kathylincn please     cat /proc/cpuinfo
