### ISSUE TITLE
Linux最新客户端会导致关机重启很慢

### ISSUE THREAD

**Issue by golden777** [xtaci/kcptun#969]
关机时显示,要等很久
[16.834951] systemd-shutdown[1] : Waitingg for process: 591 (client_linux_am)
如果提前结束进程,再重启关机就很快

**Comment by xtaci** [comment]
了解，可能是信号处理问题。试下这个 @golden777 
[kcptun-linux-amd64-20240919.tar.gz](https://github.com/user-attachments/files/17055503/kcptun-linux-amd64-20240919.tar.gz)

**Comment by xtaci** [comment]
![image](https://github.com/user-attachments/assets/a39dd233-5e2a-44bd-944e-d79705bded91)

**Comment by golden777** [comment]
> 了解，可能是信号处理问题。试下这个 @golden777 [kcptun-linux-amd64-20240919.tar.gz](https://github.com/user-attachments/files/17055503/kcptun-linux-amd64-20240919.tar.gz)

这个好了,感谢
