### ISSUE TITLE
Support self proxy feature

### ISSUE THREAD

**Issue by buaazp** [xtaci/kcptun#98]
今天看到一个一键打包脚本：https://github.com/clangcn/kcp-server
实际上是打包了一个kcptun的修改版：https://github.com/loveuall/kcptun
这个修改版主要功能是自带了socks5服务器，确实会方便一些。但是没走fork，无法和kcptun master版本同步，所以将来会有很多问题。
不知道作者是否故意不想支持proxy功能，如果不是的话，我这有个分之增加了这功能：
https://github.com/buaazp/kcptun/blob/self-proxy/server/main.go#L78
如果启动参数`--target`是`self`的话，则自己做socks5代理服务器进行转发，已经用上应该没啥问题。

**Comment by xtaci** [comment]
是的，故意不支持的。 太敏感。

**Comment by buaazp** [comment]
果然，我自己玩了~
